return {
  ["S_T"] = {
    ["pathableOnly"] = false,
    ["losOnly"] = false,
    ["zoom"] = 0.5,
    ["followPlayer"] = true,
    ["showSearchRadius"] = true,
    ["showNPCs"] = true,
    ["colorModeIndex"] = 1,
    ["layer0"] = true,
    ["layer1"] = true,
    ["zFilterRange"] = 45,
    ["lineThickness"] = 1,
    ["showLabels"] = true,
    ["showGrid"] = true,
    ["showPCs"] = true,
    ["showGroup"] = true,
    ["showRaid"] = true,
    ["showPets"] = false,
    ["showCorpses"] = false,
    ["showNPCNames"] = false,
    ["showNavLine"] = true,
    ["showCampRadius"] = true,
    ["showPullRadius"] = true,
    ["showWaypoints"] = true,
    ["showHazards"] = true,
    ["showAnchor"] = true,
    ["layer2"] = true,
    ["layer3"] = true,
    ["layerLabels"] = true,
    ["zFilterMode"] = 1,
    ["zDepthFading"] = true,
    ["npcNodeRadius"] = 4.5,
    ["playerNodeRadius"] = 6,
    ["activeMapFolder"] = "No maps directory found",
    ["showPoiDrawer"] = false,
    ["atlasTypeFilterIdx"] = 1,
    ["atlasEraFilterIdx"] = 1,
    ["conFilterIndex"] = 1
  },
  ["__global"] = {
    ["selectedMapFolder"] = "No maps directory found",
    ["customMapsDir"] = ""
  }
}
