-- ============================================================================
-- TRIUNE QUEST GUIDE: Expansion Index (00 - 32)
-- ============================================================================

return {
  {
    id = "00",
    name = "Original EverQuest",
    release = "March 1999",
    level_cap = "50",
    quest_count = 0,
  },
  {
    id = "01",
    name = "The Ruins of Kunark",
    release = "March 2000",
    level_cap = "60",
    quest_count = 403,
  },
  {
    id = "02",
    name = "The Scars of Velious",
    release = "December 2000",
    level_cap = "--",
    quest_count = 319,
  },
  {
    id = "03",
    name = "The Shadows of Luclin",
    release = "December 2001",
    level_cap = "--",
    quest_count = 316,
  },
  {
    id = "04",
    name = "The Planes of Power",
    release = "October 2002",
    level_cap = "65",
    quest_count = 27,
  },
  {
    id = "05",
    name = "The Legacy of Ykesha",
    release = "February 2003",
    level_cap = "--",
    quest_count = 121,
  },
  {
    id = "06",
    name = "Lost Dungeons of Norrath",
    release = "September 2003",
    level_cap = "--",
    quest_count = 15,
  },
  {
    id = "07",
    name = "Gates of Discord",
    release = "February 2004",
    level_cap = "--",
    quest_count = 48,
  },
  {
    id = "08",
    name = "Omens of War",
    release = "September 2004",
    level_cap = "70",
    quest_count = 56,
  },
  {
    id = "09",
    name = "Dragons of Norrath",
    release = "February 2005",
    level_cap = "--",
    quest_count = 54,
  },
  {
    id = "10",
    name = "Depths of Darkhollow",
    release = "September 2005",
    level_cap = "--",
    quest_count = 4,
  },
  {
    id = "11",
    name = "Prophecy of Ro",
    release = "February 2006",
    level_cap = "--",
    quest_count = 41,
  },
  {
    id = "12",
    name = "The Serpent's Spine",
    release = "September 2006",
    level_cap = "75",
    quest_count = 59,
  },
  {
    id = "13",
    name = "The Buried Sea",
    release = "February 2007",
    level_cap = "--",
    quest_count = 3,
  },
  {
    id = "14",
    name = "Secrets of Faydwer",
    release = "November 2007",
    level_cap = "80",
    quest_count = 8,
  },
  {
    id = "15",
    name = "Seeds of Destruction",
    release = "October 2008",
    level_cap = "85",
    quest_count = 3,
  },
  {
    id = "16",
    name = "Underfoot",
    release = "December 2009",
    level_cap = "--",
    quest_count = 54,
  },
  {
    id = "17",
    name = "House of Thule",
    release = "October 2010",
    level_cap = "90",
    quest_count = 148,
  },
  {
    id = "18",
    name = "Veil of Alaris",
    release = "November 2011",
    level_cap = "95",
    quest_count = 143,
  },
  {
    id = "19",
    name = "Rain of Fear",
    release = "November 2012",
    level_cap = "100",
    quest_count = 227,
  },
  {
    id = "20",
    name = "Call of the Forsaken",
    release = "October 2013",
    level_cap = "--",
    quest_count = 89,
  },
  {
    id = "21",
    name = "The Darkened Sea",
    release = "November 2014",
    level_cap = "105",
    quest_count = 118,
  },
  {
    id = "22",
    name = "The Broken Mirror",
    release = "November 2015",
    level_cap = "--",
    quest_count = 55,
  },
  {
    id = "23",
    name = "Empires of Kunark",
    release = "November 2016",
    level_cap = "--",
    quest_count = 83,
  },
  {
    id = "24",
    name = "Ring of Scale",
    release = "December 2017",
    level_cap = "110",
    quest_count = 53,
  },
  {
    id = "25",
    name = "The Burning Lands",
    release = "December 2018",
    level_cap = "--",
    quest_count = 65,
  },
  {
    id = "26",
    name = "Torment of Velious",
    release = "December 2019",
    level_cap = "115",
    quest_count = 39,
  },
  {
    id = "27",
    name = "Claws of Veeshan",
    release = "December 2020",
    level_cap = "--",
    quest_count = 40,
  },
  {
    id = "28",
    name = "Terror of Luclin",
    release = "December 2021",
    level_cap = "120",
    quest_count = 49,
  },
  {
    id = "29",
    name = "Night of Shadows",
    release = "December 2022",
    level_cap = "--",
    quest_count = 47,
  },
  {
    id = "30",
    name = "Laurion's Song",
    release = "December 2023",
    level_cap = "125",
    quest_count = 43,
  },
  {
    id = "31",
    name = "The Outer Brood",
    release = "December 2024",
    level_cap = "--",
    quest_count = 40,
  },
  {
    id = "32",
    name = "Shattering of Ro",
    release = "December 2025",
    level_cap = "130",
    quest_count = 48,
  },
}
