-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Sarith, City of Tides (akheva)
-- Total Quests: 19
-- ============================================================================

return {
  zone = "akheva",
  zone_name = "Sarith, City of Tides",
  quests = {
    {
      id = "5456",
      title = "Diminishing the Temple - Ophidians",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Renarra",
      loc = nil,
      triggers = {
        "Hail, Renarra",
        "Take down the temple?",
        "I",
        "_Quests_",
        "take down",
        "help",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Sarith, City of Tides [zone=808]\n**Who:**\n- Renarra [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Alaran Language:** | 73\n**Quest Goal:**\n- Experience\n- Money\n**Related Zones:**\n- Rubak Oseka, Temple of the Sea [zone=809]\n**Related Creatures:**\n- a coral ophidian [npc=38556]\n- a revered ophidian [npc=38555]\n- a ringed ophidian [npc=38554]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Nov 21 20:10:47 2011\nModified: Tue Dec 5 05:21:04 2023 | | **For an overview of the Veil of Alaris expansion, a task listing, and information about group/raid progression, spells, and armor, **click here**.**\n\n---\n\n_This is a kill task that begins with a Kedge named Renarra in Sarith, located at about -60, -800, -2 (northeast part of the dock area)._\n_Pre-requisites for requesting the task:_\n\\- No tasks\n\\- 73 Skill Level in Alaran\nYou say, 'Hail, Renarra'\nRenarra says '\\_\\_\\_\\_\\_! In the name of the Prexus, it's time to [take down] the Temple of Rubak Oseka!'\nYou say, 'Take down the temple?'\nRenarra says 'Before we launch our offense against the Temple, we need to weaken its inhabitants. Are you here to [help]?'\nYou say, 'I'll help!'\nRenarra says 'The Temple is filled with various inhabitants; mainly the Alarans and Hadal. There may also be ophidians as they are the beloved animals of Oseka, the God of Tides. Take your pick and remove them. Prexus will ensure you are greatly rewarded for your valiant efforts.'\n_A task window pops up with five tasks to choose from._\nYou have been assigned the task 'Diminishing the Temple - Ophidians'.\nBeing Oseka's beloved animals, Renarra believes that killing the sacred ophidians may reduce Oseka's power. Dive into the watery depths and take out the ophidians.\n\n---\n\nDefeat the coraled ophidians 0/4 (Rubak Oseka)\nDefeat the revered ophidians 0/4 (Rubak Oseka)\nDefeat the ringed ophidians 0/4 (Rubak Oseka)\n_The ophidians are snakes found mostly in the bottom floor of the temple, and in greater numbers in the water under the bottom floor._\nSpeak with Renarra 0/1 (Sarith)\nYou say, 'Hail, Renarra'\nYou've taken out the ophidians in the Temple of Rubak Oseka.\n_Reward:_\nExperience\n136 platinum",
    },
    {
      id = "12470",
      title = "It Takes Two to Tangle",
      exp = "29",
      exp_name = "Night of Shadows",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Terro Kai",
      loc = { y = 2295.0, x = 54.0, z = 0.0 },
      triggers = {
        "Hail, Terro Kai",
        "underhanded plot",
        "What was it that you found?",
        "scene",
        "I will prove that you have not gone mad.",
        "Hail, Sentry Kedra Kai",
        "I have something important to report.",
        "_Quests_",
      },
      items_required = {
        { name = "me more jawbones?'", count = 1 },
      },
      rewards = {
        { id = 145128, name = "Shak Dratha Token", type = "item" },
        { id = 145128, name = "6 Shak Dratha Token", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Shadeweaver's Tangle [zone=1309]\n**Who:**\n- Terro Kai [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Quest Items:**\n- Shak Dratha Token [item=145128]\n**Related Creatures:**\n- Sentry Kedra Kai [npc=58349]\n- Zun Tetorau [npc=58664]\n**Related Quests:**\n- Partisan of Shadeweaver's Tangle (10 Points) [quest=12235]\n**Era:** | !Night of Shadows\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 6 15:30:22 2022\nModified: Sat Jan 27 08:11:08 2024 | | **Night of Shadows Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this task from Terro Kai [npc=58357] in Shadeweaver's Tangle. You can find Terro Kai at /waypoint 474, 91, -198. He/she is on the find tool as well CTRL F.\nYou say, 'Hail, Terro Kai'\nTerro Kai's ears perk up, a telltale sign that he is very pleased to see you again. '\\_\\_\\_\\_\\_! I am so glad to see you! You helped me with trying to find out what happened to my brother back in Ka Vethan. As you can see, I was able to make it out of there with my life intact, thanks to your help. Now I seem to find myself amidst another [underhanded plot] and could use your experience to get to the bottom of this once and for all.'\nYou say, 'underhanded plot'\nTerro Kai says, 'Indeed, I need you to believe me when I tell you that I have stumbled upon a stomach-turning scene within the caves here. One day, I heard a bunch of voices and chanting echoing through the cave system, so I decided to investigate. I was not prepared for what I [found].'\nYou say, 'What was it that you found?'\nTerro Kai's eyes grow wide as he stares at nothing. He is very distraught by what he found. 'Bodies, \\_\\_\\_\\_\\_, bodies everywhere. They were tied down onto burning beds of coal. The stench was unbearable. Each of the pits that had a body in it was surrounded by a dark energy that I only saw when I was in Ka Vethan. I think that the Akheva may be behind this sudden rush of Shak Dratha into the area. All of this feels all too familiar to me. I know it is a lot to ask, but could you please try to find this [scene] somewhere in these caves?'\nYou say, 'scene'\nTerro Kai says, 'I fear my mind is playing tricks on me. I fear that I didn't actually see what I saw. It was so visceral, so vile. Please, \\_\\_\\_\\_\\_, I am begging for your help. Have I [gone mad]? Survey these caves and tell me that I did not conjure up what I saw from a nightmare.'\nYou say, 'I will prove that you have not gone mad.'\nYou have been assigned the task 'It Takes Two to Tangle'.\nTerro Kai's shoulders slump as he lets out a sigh of relief. 'Thank you \\_\\_\\_\\_\\_, I knew I could count on you for this. Come back to me once you find it, so I know I haven't lost my mind.'\n\n---\n\n1\\. Prove Terro is not insane 0/1 Shadeweaver's Tangle\nEnter the cave tunnels and go north the 3rd cave up has some graves that has a spot at /loc +2295, +54 to update this task, along with a yellow emote :\nAs you enter this part of the caves, the smell of burning flesh is overwhelming. This must be the scene that Terro was talking about. You wretch for a moment as you cover your mouth and nose to mask the smell.\n2\\. Return to Terro and tell him what you found 0/1 Shadeweaver's Tangle\nYou say, 'Hail, Terro Kai'\nTerro Kai has a worried look on his face before speaking. 'You found it! So I'm not mad! This is both terrible and good news. A real Luclin's Gambit, if you will.' He winces as he says that. 'I just made that up.' An awkward pause is felt between the two of you. It is almost painfully long. You try to speak, but he interrupts you. 'Anyway, this is clearly something we need to warn the local guards about. Visit Sentry Kedra Kai in the training area and tell him what you found.'\n3\\. Visit Sentry Kedra Kai 0/1 Shadeweaver's Tangle\nSentry Kedra Kai is located at +208, -1389, -169.06 at the first crossroads west of Shar Vahl.\nYou say, 'Hail, Sentry Kedra Kai'\nSentry Kedra Kai's demeanor is stern, stoic, and determined as you approach. He addresses you with an intensity that tells you that he is not in the mood for small talk. 'Another adventurer graces my presence yet again. Tell me, do you have anything [important to report], or are you here to give me more jawbones?'\nYou say, 'I have something important to report.'\nSentry Kedra Kai's tone changes as you inform him of what you and Terro have found. His face grows more concerned as you continue. 'I see, \\_\\_\\_\\_\\_, that actually is something important to report. The Shak Dratha have been pouring in from the north, but we are not sure what is driving them to do so. We have some suspicions as to what it could be.' He snorts the air and looks to the west. \"Akheva, probably. We need to clear out those caves first. \\_\\_\\_\\_\\_, thank you for reporting this to me, I'll have to work with the other guards to clear out those caves. In the meantime, we would all benefit from less Shak Dratha around here. Get rid of them for us.'\n4\\. Cull the Shak Dratha 0/10 Shadeweaver's Tangle\nThese are the mobs in the tunnels.\n5\\. Loot the strange trinket 0/1 Shadeweaver's Tangle\nThe 10th and last kill will have 1-6 Shak Dratha Token [item=145128] on the body for everyone in the group with the task.\n6\\. Deliver the trinket to Terro 0/1 Shadeweaver's Tangle\nTerro Kai is relieved to see you leave the caves. 'You're still alive, \\_\\_\\_\\_\\_! I was afraid that you were being burned alive and your soul torn asunder. I am very happy to be wrong.' His face grows concerned as he looks at the trinket you handed him. 'I know these markings. These are from Ka Vethan. The Akheva have been using the Shak Dratha as fodder for their campaign to take over Luclin. I need you to bring this to Sentry Kedra Kai immediately, \\_\\_\\_\\_\\_!'\nYou have been given: Shak Dratha Token\n7\\. Bring the trinket to Sentry Kedra Kai 0/1 Shadeweaver's Tangle\nSentry Kedra Kai takes the trinket and holds it in the palm of his hand silently for a few moments before speaking. 'Well, whatever suspicions we had about who was behind this have been quashed, not that it was too hard to figure out.' He tucks the token into his pocket. 'We have been hearing reports of voices being heard from within the caves to the south. We think this is where the Akheva have built a headquarters. I want you to find this place and if you see anybody who looks to be in charge, kill them so we can be done with this.'\n8\\. Locate the Akhevan headquarters 0/1 Shadeweaver's Tangle\nGo back in to the tunnel and go south, the task will update before the last room at /loc +60, +1227, -344.71.\nThe voices you have been hearing echo in the mines are getting louder as you approach. This is the place that Sentry Kedra told you to go. Locate who may be running things and end their reign of terror.\n9\\. Slay Zun Tetorau 0/1 Shadeweaver's Tangle\nmob is in the south tunnel last small room room has two adds.\n10\\. Catch up with Terro Kai 0/1 Shadeweaver's Tangle\n\n---\n\nReward(s):\n265 platinum 6 gold 2 silver 5 copper\nYou gain experience!",
    },
    {
      id = "12471",
      title = "A Knight to Remember",
      exp = "29",
      exp_name = "Night of Shadows",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Krastoraab Puremane",
      loc = { y = 698.0, x = -1603.0, z = -172.41 },
      triggers = {
        "Hail, Krastoraab Puremane",
        "Tell me what you know about Loda Kai",
        "What kind of snag?",
        "How will we find out what went wrong?",
        "Hail, Trainer Shali",
        "Hail, Trainer Kabrin",
        "Hail, Trainer Shekar",
        "Hail, Trainer Ahele",
      },
      items_required = {
        { name = "him the twn Kai Clan Rings", count = 1 },
        { name = "him the Loda Kai's Lunch", count = 1 },
      },
      rewards = {
        { id = 145360, name = "Cleaned Lunch Plate", type = "item" },
        { id = 145359, name = "Loda Kai's Lunch", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Shadeweaver's Tangle [zone=1309]\n**Who:**\n- Krastoraab Puremane [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 120\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Cleaned Lunch Plate [item=145360]\n- Loda Kai's Lunch [item=145359]\n**Related Creatures:**\n- Guard Arjin [npc=58021]\n- Loda Kai [npc=58108]\n- Trainer Ahele [npc=58384]\n- Trainer Kabrin [npc=58388]\n- Trainer Shali [npc=58390]\n- Trainer Shekar [npc=58391]\n- a Loda Kai battler [npc=58270]\n- a Loda Kai brigand [npc=58271]\n- a Loda Kai champion [npc=58272]\n- a Loda Kai contender [npc=58273]\n- a Loda Kai diviner [npc=58274]\n- a Loda Kai fighter [npc=58275]\n- a Loda Kai guard commander [npc=58627]\n- a Loda Kai guardian [npc=58276]\n- a Loda Kai informant [npc=58628]\n- a Loda Kai informant [npc=58277]\n- a Loda Kai knight [npc=58278]\n- a Loda Kai magus [npc=58279]\n- a Loda Kai raider [npc=58280]\n- a Loda Kai sage [npc=58281]\n- a Loda Kai seer [npc=58282]\n- a Loda Kai spiritist [npc=58283]\n- a Loda Kai thug [npc=58284]\n**Related Quests:**\n- Partisan of Shadeweaver's Tangle (10 Points) [quest=12235]\n**Era:** | !Night of Shadows\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 6 15:34:46 2022\nModified: Tue Dec 5 05:21:04 2023 | | **Night of Shadows Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou say, 'Hail, Krastoraab Puremane'\nKrastoraab Puremane notices you approach and greets you warmly. 'Greetings, adventurer. Blessings upon you from Sahteb Mahlni. May your drive for life never fade. If you are here, you must be aware of the problems that have come from one known as [Loda Kai]. The brigands to the west are in disarray since Loda's imprisonment. Would you like to know more about Loda Kai?'\nYou say, 'Tell me what you know about Loda Kai'\nKrastoraab Puremane says, 'Loda Kai was the leader of the brigands. Some would argue that he still is their leader, but he has been apprehended by the constabulary in Shar Vahl. From what has been rumored, he is the main reason that the Shak Dratha first made it to the Tangle. Because of his transgressions, he has been placed in custody and is not talking to anybody. Here is where I think we can use your skills as a negotiator to seek an audience with him. Unfortunately, we have discovered a [snag] in the plan.'\nYou say, 'What kind of snag?'\nKrastoraab Puremane says, 'Well, the guards are not too keen on letting the leader of the brigands just speak with whomever he wishes. You will have to earn Guard Arjin's favor first. However, you will want to be prepared for when you get to speak to Loda Kai. I do not believe that this outcome was his intention, so let us gather some information before we speak with Loda. First, we need to understand where [things went wrong].'\nYou say, 'How will we find out what went wrong?'\nYou have been assigned the task 'A Knight to Remember'.\nKrastoraab Puremane says, 'We can't just come out and ask him what happened. We need to understand that he has a side to this story as well. Speak with the trainers here in this camp. They have been on the front lines of this fight for long enough. They will have a better understanding as to what we are up against in the Tangle.'\n\n---\n\n1\\. Speak with Trainer Shali 0/1 Shadeweaver's Tangle\nTrainer Shail is located at +698, -1603, -172.41.\nYou say, 'Hail, Trainer Shali'\nTrainer Shali addresses her class. 'Remember, a good counter is a strong crescendo into the chorus. Keep practicing, I'll be right back.' She turns to address you. 'Cello! I mean, hello! You're asking about the Shak Dratha? Yeah, they started off as a small nuisance. However, after the explosion that shook Luclin, they have been pouring out of the caves in record numbers. They do not fight like they are going to be remembered, that's for sure. Good luck with whatever you're planning.'\n2\\. Speak with Trainer Kabrin 0/1 Shadeweaver's Tangle\nTrainer Kabrin is located at +601, -1656, -172.37.\nYou say, 'Hail, Trainer Kabrin'\nTrainer Kabrin says, 'Ah, \\_\\_\\_\\_\\_. It's nice to finally speak with you. As I understand it, you are attempting to get to the bottom of our Shak Dratha issue? I can tell you that they have become unnaturally strong. We noticed the change shortly after the quake. They became stronger than normal, with reckless abandon for their own lives. Almost as if they know they will not be completely destroyed. I hope you find what you are looking for, \\_\\_\\_\\_\\_.'\n3\\. Speak with Trainer Shekar 0/1 Shadeweaver's Tangle\nTrainer Shekar is located at +254, -1615, -169.15.\nYou say, 'Hail, Trainer Shekar'\nTrainer Shekar barks at his trainees, 'If you don't get that foot higher, you will never land a kick! Remember, center of gravity is the best place to aim for!' He addresses you. 'Ah, you're looking into the Shak Dratha for us now? Good, they are not acting like they did when we first got here. They are sturdier and can withstand a heartier beating before they die. They'd make great training dummies if you could get them to sit still long enough. Good luck. Oh, and bring a bigger stick than you usually do.'\n4\\. Speak with Trainer Ahele 0/1 Shadeweaver's Tangle\nTrainer Ahele is located at +10, -1528, -177.08.\nYou say, 'Hail, Trainer Ahele'\nTrainer Ahele silently nods to the trainees. In unison, they each take a seat and begin kibitzing with each other. She turns to you. 'The Shak Dratha have become harder and harder to hide from, not because of their increase in numbers, but something is heightening their senses, almost supernaturally. While we do our work in the shadows, it seems that the shadows are on the side of the Shak Dratha as of late. I wish you luck in your journey, \\_\\_\\_\\_\\_.'\n5\\. Return to Krastoraab 0/1 Shadeweaver's Tangle\nYou say, 'Hail, Krastoraab Puremane'\nKrastoraab Puremane says, 'So you have finished speaking to the trainers. I bet they were able to provide you with a better understanding of what has happened since the Akhevan empire made their advance. Now we have something to bring to Loda to help him understand that we are not simply trying to understand his side of things. However, we now have to work on getting the trust of [Guard Arjin].'\nYou say, 'How do you think we gain the trust of Guard Arjin?'\nKrastoraab Puremane's whiskers swish around as he thinks, mumbling quietly to himself as he sorts out the information in his mind. He turns to you and addresses you, but you have to stifle a laugh as his lip is stuck on his now dry fang, taking the seriousness out of everything else he has said. He fixes his lip before continuing. 'Many of the brigands have started carrying Kai clan rings on them as a way to show allegiance to Loda Kai. Collect some of those rings and bring them to Guard Arjin. This will prove that you are not on the brigand's side.'\n6\\. Collect Kai rings from the Loda Kai Brigands 0/10 Shadeweaver's Tangle\n_There's a bandit camp in the Northwest. Kill them and loot 10 Kai Clan Rings._\n7\\. Deliver the Rings to Guard Arjin in the Shar Vahl Prison 0/10 Shar Vahl, Divided\nGuard Arjin is located at +134, -583, -237.11. Give him the twn Kai Clan Rings.\nGuard Arjin is holding a tray of bloody meat when you approach him. It seems he is very happy about who he is guarding. 'Hey! Feast your eyes upon the great and powerful Loda Kai!' He points at Loda Kai's jail cell door and guffaws before continuing. 'Oh, lighten up. This criminal isn't going anywhere anytime soon. He deserves to rot. We know about the Shak Dratha he is [commanding].'\nYou say, 'You think he is still commanding the Shak Dratha while here?'\nGuard Arjin laughs heartily at the question. 'You think,' he pauses to wipe a tear from his eye. 'You think that anyone is getting near him any time soon, I have a bridge in Halas to sell you!' He eventually calms down from laughing so hard. 'Okay, \\_\\_\\_\\_\\_, you gave me a pile of rings and a good laugh. What is it you want? You want to talk to Loda Kai? Why don't you bring him his lunch. Make sure he eats up. We need him in good health when we execute him. Mainly because it's funny to us.'\nYou have been given: Loda Kai's Lunch\n8\\. Bring Loda Kai his Lunch 0/1 Shar Vahl, Divided\nLoda Kai is in a nearby cell. Give him the Loda Kai's Lunch.\nYou offered 1 Loda Kai's Lunch to Loda Kai.\nLoda Kai glares at you, then glares at the plate of meat before reluctantly taking it. He smells each piece and after an inspection, ravenously devours the bloody meat. After a few moments, his hunger is sated enough for him to look up and notice you are still standing at his cell door. He swallows the meat and wipes the blood away from his mouth with the back of his hand before continuing. 'You? What do you want? You've come to heckle me? You think you can scare me? You've got the [wrong guy].'\n9\\. Listen to Loda Kai's Story 0/1 Shadeweaver's Tangle\nYou say, 'wrong guy'\nLoda Kai says, 'You all like to assume that just because you are on that side of the cell door, that you are in the right. When I led my clan into Shadeweaver's Tangle, I thought that the Shak Dratha would be a powerful tool for us. At first, we thought that if we were to get rid of their competition, the Gor Taku, the Shak Dratha would be a powerful ally to us. What we didn't anticipate was that the Shak Dratha, after having won their turf war, would be essentially hijacked by the Akheva and imbued with whatever [shadow magicks] they are using.'\nYou say, 'What are these shadow magicks you speak of?'\nLoda Kai stares at the blood that is still on the back of his hand. He licks it clean with a small laugh. 'You know the tegi here were not that strong, but after the Akheva started their crusade across the moon, they have been using desperate means to increase their strength. I only intended to use the [Shak Dratha] for fodder. The Akheva were able to take the reins and turn them into killing machines. The fools still think that they are owed this moon. This moon is owed to no one but Luclin herself.\nYou say, 'Tell me about the Shak Dratha.'\nLoda Kai angrily winces at your request. A dull growl can be heard before he continues speaking. 'Those abominations can be controlled, but whatever method the Akheva are using is stronger than the influence I had. I was a naive fool, but mark my words, \\_\\_\\_\\_\\_. This cage is temporary. I will finish what I started. When I do, you and your kind will remember the Kai name. Now, get away from me. I wish to be alone with my thoughts and I have plenty to think about. Take this back to where you found it.'\nYou have been given: Cleaned Lunch Plate\n10\\. Return the plate to Guard Arjin 0/1 Shadeweaver's Tangle\nYou offered 1 Cleaned Lunch Plate to Guard Arjin.\nGuard Arjin takes the plate from you with a smile. 'Did you get what you needed from the criminal? Would you believe that he only eats bloody meat? He had the audacity to request his meals be just piles of meat. A bit odd, but hey, at least he respects our cook's time. I'd think him more of a monster if he wanted his steaks cooked well done.' He guffaws again. 'Okay, get out of here. You've entertained us enough for one day.'\n11\\. Catch up with Krastoraab Puremane 0/1 Shadeweaver's Tangle\nYou say, 'Hail, Krastoraab Puremane'\nYou discovered that the Shak Dratha were introduced to Shadeweaver's Tangle because of Loda Kai. He originally used them as foot soldiers for his brigands. He unknowingly gave the Akheva shock troops they could manipulate for their cause. The guards in Shar Vahl keep him under close watch at all times. You are not sure what Loda Kai's fate will become. You just know that for now, he is not going anywhere anytime soon.\n\n---\n\nReward(s):\n177 platinum 8 silver 4 copper\nYou have gained 24 ability point(s)!\nYou gain experience!",
    },
    {
      id = "12473",
      title = "That's Not Going to Grow Back",
      exp = "29",
      exp_name = "Night of Shadows",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Ian Naelev",
      loc = nil,
      triggers = {
        "Hail, Ian Naelev",
        "Vermin? It doesn",
        "You have built?",
        "You should find a different place to call home?",
        "I will kill some hoppers.",
        "_Quests_",
        "vermin",
        "built",
      },
      items_required = {
      },
      rewards = {
        { id = 145133, name = "Severed Hopper Head", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Shadeweaver's Tangle [zone=1309]\n**Who:**\n- Ian Naelev [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 120\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Severed Hopper Head [item=145133]\n**Related Creatures:**\n- a clawed hopper [npc=58260]\n- a firefall hopper [npc=58263]\n- a firefall saurek hopper [npc=58264]\n- a needle clawed hopper [npc=58289]\n- a saurek hopper [npc=58290]\n- a small firefall hopper [npc=58308]\n**Related Quests:**\n- Mercenary of Shadeweaver's Tangle (10 Points) [quest=12234]\n**Era:** | !Night of Shadows\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 6 16:14:31 2022\nModified: Tue Dec 5 05:21:04 2023 | | **Night of Shadows Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this task from Ian Naelev [npc=58342] in Shadeweaver's Tangle. You can find Ian Naelev at /waypoint 848, -212, -192. He/she is on the find tool as well CTRL F.\nYou say, 'Hail, Ian Naelev'\nIan Naelev says, 'Hail and watch your step. The [vermin] around these parts will take a bite out of any in their path.'\nYou say, 'Vermin? It doesn't sound like you care for the wildlife.'\nIan Naelev says, 'These beasts do nothing but attack anything that moves and destroy what we have [built].'\nYou say, 'You have built?'\nIan Naelev says, 'Well, yes. Don't we all work hard to make our [home] more hospitable?'\nYou say, 'You should find a different place to call home?'\nIan Naelev says, 'Ha. What we need is someone to kill some [hoppers], [shik`nar] and [beetles].'\nYou say, 'I will kill some hoppers.'\nYou have been assigned the task 'That's Not Going to Grow Back'.\nIan Naelev says, 'The beasts run around these hills with their sharp claws and pointy teeth. Return their heads to me and you will be compensated.'\n\n---\n\n1\\. Kill hoppers in the Shadeweaver's Tangle 0/7 Shadeweaver's Tangle\n_These are found on the south wall._\n2\\. Loot severed hopper heads 0/7 Shadeweaver's Tangle\n3\\. Deliver the severed hopper heads to Ian Naelev 0/7 Shadeweaver's Tangle\n\n---\n\nReward(s):\n118 p 5s 6cp\nExperience",
    },
    {
      id = "12474",
      title = "Pocket Full of Claws",
      exp = "29",
      exp_name = "Night of Shadows",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Ian Naelev",
      loc = nil,
      triggers = {
        "I will kill some shik`nar.",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
        { id = 145224, name = "Severed Shik Nar Claws", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Shadeweaver's Tangle [zone=1309]\n**Who:**\n- Ian Naelev [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 120\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Severed Shik Nar Claws [item=145224]\n**Related Creatures:**\n- a chitterling [npc=58255]\n- a chitterling shik`nar [npc=58256]\n**Related Quests:**\n- Mercenary of Shadeweaver's Tangle (10 Points) [quest=12234]\n**Era:** | !Night of Shadows\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 6 16:15:29 2022\nModified: Tue Dec 5 05:21:04 2023 | | **Night of Shadows Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this task from Ian Naelev [npc=58342] in Shadeweaver's Tangle. You can find Ian Naelev at /waypoint 848, -212, -192. He/she is on the find tool as well CTRL F.\nIan Naelev says, 'The beasts run around these hills with their sharp claws and pointy teeth. Return their heads to me and you will be compensated.'\nYou say, 'I will kill some shik`nar.'\nYou have been assigned the task 'Pocket Full of Claws'.\n\n---\n\n1\\. Kill shik`nar in the Shadeweaver's Tangle 0/5 Shadeweaver's Tangle\n2\\. Loot severed shik`nar claws 0/5 Shadeweaver's Tangle\n3\\. Deliver the severed shik`nar claws to Ian Naelev 0/5 Shadeweaver's Tangle\n\n---\n\nReward(s):\n118 platinum 5 silver 6 copper\nYou gain experience!",
    },
    {
      id = "12475",
      title = "These Feet Don't Clap",
      exp = "29",
      exp_name = "Night of Shadows",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Ian Naelev",
      loc = nil,
      triggers = {
        "I will kill some beetles.",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Shadeweaver's Tangle [zone=1309]\n**Who:**\n- Ian Naelev [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 120\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Severed Cht`Thk Feet [item=145134]\n**Related Creatures:**\n- a Cht`Thk ash beetle [npc=58257]\n- a Cht`Thk horned ash beetle [npc=58258]\n- a Cht`Thk scorched beetle [npc=58259]\n**Related Quests:**\n- Mercenary of Shadeweaver's Tangle (10 Points) [quest=12234]\n**Era:** | !Night of Shadows\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 6 16:16:23 2022\nModified: Tue Dec 5 05:21:04 2023 | | **Night of Shadows Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this task from Ian Naelev [npc=58342] in Shadeweaver's Tangle. You can find Ian Naelev at /waypoint 848, -212, -192. He/she is on the find tool as well CTRL F.\nIan Naelev says, 'The creatures run around these hills with their clicking claws and sharp beaks. Return their claws to me and you will be compensated.'\nYou say, 'I will kill some beetles.'\nYou have been assigned the task 'These Feet Don't Clap'.\nIan Naelev says, 'The creatures run around these hills with their sticky feet and shiny shells. Return their feet to me and you will be compensated.'\n\n---\n\n1\\. Kill Cht`Thk beetles in the Shadeweaver's Tangle 0/7 Shadeweaver's Tangle\n2\\. Loot severed Cht`Thk feet 0/7 Shadeweaver's Tangle\n3\\. Deliver the severed Cht`Thk feet to Ian Naelev 0/7 Shadeweaver's Tangle\n\n---\n\nReward(s):\n118 platinum 5 silver 6 copper\nYou gain experience!",
    },
    {
      id = "13422",
      title = "Empty Shadows",
      exp = "32",
      exp_name = "Shattering of Ro",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Zeivan",
      loc = nil,
      triggers = {
        "Hail, Zeivan",
        "I need a job.",
        "I want to hunt the husks.",
        "_Quests_",
        "crude",
        "job",
        "husks",
        "spiders",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Labyrinth of Spite [zone=1386]\n**Who:**\n- Zeivan [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 105\n**Maximum Level:** | 130\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Related Creatures:**\n- a malicious husk [npc=61017]\n- a malicious vessel [npc=60978]\n- a nameless husk [npc=61002]\n**Era:** | !Shattering of Ro\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 13 02:53:01 2025\nModified: Thu Nov 27 14:40:22 2025 | | You can obtain this task from Zeivan just outside the cast area's gates down from The Vortex zone line at /way 679, 27, -13. She is on the find tool CTRL F.\nYou say, 'Hail, Zeivan'\nZeivan says, 'Isn't this just a friendly group of sunshine and rainbows?' The rogue hisses a chuckle of amusement. 'To get to the bottom of business here, it's best to thin the herd, so to speak. A crude way to put it, but we can afford to be a little [crude] in this realm of envy and spite, don't you think? That's enough rhetorical questions. Do you want a [job]? You'll be paid for your service to Norrath, I assure you.'\nYou say, 'I need a job.'\nZeivan says, 'Take your pick: The [husks], the [spiders], the [elves and gnomes], or perhaps the [minions] beneath our feet.'\nYou say, 'I want to hunt the husks.'\nYou have been assigned the task 'Empty Shadows'.\nZeivan says, 'These, uh, shadowy figures -- are they truly people anymore?' Mischief is alight in her eyes. 'Is it amusing to think about? Oh, I love asking these thought-provoking questions. Well, perhaps they've lost their sentience or sanity, and you're releasing them from their torture. If any good in your heart is holding you back, just think of the mercy you're giving them.'\n\n---\n\nWith Norrath's good intentions at heart, and a bit of sass, the rogue Zeivan has a few jobs to reduce the ranks of the locals. She's asked that you take\nout several of the husks around the Labyrinth of Spite.\nKill eight of the robed husks and vessels.\n1\\. Kill 8 Husks and Vessels 0/8 Labyrint of Spite\nMobs that count:\na malicious vessel\na malicious husk\na nameless husk\n\n---\n\nReward(s):\n?\n**Submitted by:** Gidono",
    },
    {
      id = "3063",
      title = "Norrath's Keepers Tier 5b: In the Shadows",
      exp = "09",
      exp_name = "Dragons of Norrath",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Captain Areha Burina",
      loc = nil,
      triggers = {
        "Hail, Captain Areha Burina",
        "Hail, mournful spirit",
        "Shoulder my burden",
        "shoulder your burden",
      },
      items_required = {
      },
      rewards = {
        { id = 34904, name = "Accursed Earhoop of Pain", type = "item" },
        { id = 34903, name = "Belt of the Black Dragon", type = "item" },
        { id = 34901, name = "Cloak of Deepshadow", type = "item" },
        { id = 34905, name = "Dark Heart of Vishimtar", type = "item" },
        { id = 35002, name = "Dragonkiller", type = "item" },
        { id = 35004, name = "Face of Unfeeling", type = "item" },
      },
      factions = {
        { name = "Vishimtar", change = -1 },
        { name = "Cursed Drakes", change = -1 },
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Lavastorm Mountains 3.0 [zone=31]\n**Who:**\n- Captain Areha Burina [npc=17807]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 70\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Faction\n- Loot\n**Time Limit:** | 06:00:00\n**Faction Required:**\nNorrath's Keepers (Min: Warmly)\n**Related Zones:**\n- Accursed Nest: In the Shadows [zone=375]\n**Related Creatures:**\n- Vishimtar the Fallen [npc=17716]\n- a chest - In the Shadows [npc=23792]\n- a spirit wraith [npc=21407]\n- cloud of concentrated chaos [npc=21411]\n- corrupted drake [npc=21409]\n- incorporeal shadow [npc=21353]\n- lifedrain shadow [npc=21408]\n- mournful spirit [npc=21410]\n**Related Quests:**\n- Dragons of Norrath Progression (Norrath's Keepers) [quest=3061]\n**Era:** | !Dragons of Norrath\nRecommended:\n**Group Size:** | Raid\n**Min. # of Players:** | 6\n**Max. # of Players:** | 54\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sun Mar 13 21:05:56 2005\nModified: Tue Dec 5 05:21:04 2023 |\n---\n\n**For an overview of the Dragons of Norrath expansion, see this wiki article.**\n**For an overview of progression, see quest entries for Norrath's Keepers [quest=3061] and the Dark Reign [quest=3062].**\n\n---\n\n_This raid task begins with Captain Areha Burina ( **click for map image**) in the Norrath's Keepers camp of the Lavastorm Mountains._\n_Pre-requisites for requesting this task:_\n\\- Minimum 6 players; maximum 54 players\n\\- Must be warmly faction with Norrath's Keepers\n\\- Completion of all Tier 4 tasks and flags (including the raids)\n\\- Completion of \"Origins of the Curse\" (group mission)\n\\- Completion of \"The Curse of Ju`rek\" (raid)\nYou say, 'Hail, Captain Areha Burina'\nCaptain Areha Burina bows. 'I see a good heart in you and a measure of bravery. Serve Firiona Vie and Norrath's Keepers well!'\nYou have been assigned the task 'In the Shadows'.\nTerrible events came to pass as Yar`Lir was taken from her perch. There was a dragon that protected the Nest beneath the islands in the sky, but now that place has turned to ruin and darkness. After seeing the effects the corruption has caused the Nest, we can only guess what has happened to the dragon that inhabited it. Go now and be swift. If this dragon is a plague on our lands, it must be stopped.\n\n---\n\n**Task Steps**\nTouch the portal to The Nest 0/1 (The Broodlands)\nConfront Vishimtar the Fallen 0/1 (The Accursed Nest)\n**TASK LOCKS HERE**\nKill Vishimtar the Fallen 0/1 (The Accursed Nest)\n\n---\n\n**The Event**\n_In this raid instance, you will find a formidable foe: Vishimtar the Fallen, who comes with numerous adds and tricks. Vishimtar hits for a max ~4,500; AE rampages (mitigated to ~1,000 per hit); and casts \"Vishimtar's Shadow\", \"Vishimtar's Aura\", and \"Withering Corruption\" throughout the event:_\nVishimtar the Fallen says 'The nest, the children... must be protected.'\nVishimtar's Shadow: PB AE 2000', Chromatic (-500)\n1: Decrease HP when cast by 1250\n2: Decrease Hitpoints by 850 per tick\n4: Decrease Movement by 5%\n11: Decrease Mana by 5 per tick\nVishimtar's Aura: Self 0', Magic (0)\n1: Increase Damage Shield by 15\n2: Increase Spell-Damage Shield by 250\nWithering Corruption: Single Target, Magic (-1000)\n1: Decrease Hitpoints by 100 per tick\n2: Cast Upon Fade: Vishimtar's Corruption\nVishimtar's Corruption: Self 0', Magic (-1000)\n1: Decrease AC by 600\n2: Max HP change by (-75%)\n3: Decrease Agro Multiplier by 95%\n_At about 75% health, 4x \"incorporeal shadow\" spawn. These don't hit hard at all and have relatively few hitpoints. If killed, a \"lifedrain shadow\" spawns in its place. The lifedrain shadows hit for a max ~2,000 and flurry, so you want to avoid killing the incorporeal shadows if you can._\n_3-6 minutes after Vishimtar is initially aggro'd and every 75-120 seconds thereafter, a \"tainted egg\" spawns at a random location. If these aren't killed within a few moments of spawning (blunt-weapons only), multiple mobs called \"a corrupted drakeling\" spawn from it and attack. These hit for a max ~1,200 and flurry._\n_At 50% health, the four \"corrupted drake\" mobs around the room go aggro. These are snareable and, if killed, immediately respawn._\n_At 25% health, Vishimtar locks health and starts casting \"Creeping Doom\" on random targets (45-second intervals, maximum four targets at a time). This spell must be cured before it fades (48 seconds), otherwise the inflicted player is death touched. To cure this, go to one of the \"mournful spirit\" dervishes that roam around the perimeter of the event area and say \"shoulder my burden\" to it:_\nYou say, 'Hail, mournful spirit'\nAn otherworldly voice rings in your mind, 'I can sense that you have been afflicted by Vishimtar, \\_\\_\\_\\_\\_. You will not survive long - soon death will take you and corrupt your body into a twisted shell of hatred. Allow me to help you. I can [shoulder your burden].'\nYou say, 'Shoulder my burden'\nThe mournful spirit draws corruption from your body and absorbs it, destroying itself in the process.\nmournful spirit died.\n_For each cure of \"Creeping Doom\", Vishimtar's health unlocks 1%._\nCreeping Doom: Single Target, Unresistable (-1000)\n1: Decrease Stats by 120\n2: Cast Upon Fade: Creeping Doom Trigger\n_If anyone dies or goes linkdead at any time in the event, \"a spirit wraith\" spawns in their place. These skeletons hit for a max ~1,500; have zonewide aggro; and are mezzable (note: pet deaths don't spawn adds)._\n_Note: Throughout the event, you'll sometimes get a \"cloud of concentrated chaos\" spawn. You can kill these to fill up everyone's health and mana._\n\n---\n\n**Completion & Loot**\n_Kill Vishimtar to complete the task:_\nVishimtar the Fallen has been slain by \\_\\_\\_\\_\\_!\nVishimtar crumples. His corrupted form no longer casts shadows upon the cavern walls.\nYour faction standing with Vishimtar has been adjusted by -1.\nYour faction standing with Cursed Drakes has been adjusted by -1.\nVishimtar's feeble attempts to protect the Nest were no match for your prowess.\n_Following Vishimtar's death, all adds despawn and a chest spawns with loot. Vishimtar himself drops 9x \"Shadowscale of Vishimtar\" (Tier 5 progression item) + 1x \"Eye of Vishimtar\" (turn-in item for **a mask** [quest=3090])._\n_The chest contains 3 items from this loot table:_\nAccursed Earhoop of Pain\nBelt of the Black Dragon\nCloak of Deepshadow\nCord of the Cunning\nDark Heart of Vishimtar\nDragonkiller\nFace of Unfeeling\nMottled Black Dragonscale\nObsidian Pauldrons\nRod of Shaded Wrath\nSkull of Vishimtar\n_Task Rewards:_\n9x \"Radiant Crystal\"\n1x \"Norrath's Keepers Token\" (faction **turn-in** [quest=3134] item)\n_Note: If doing this raid as part of progression, you'll want to check in with some NPCs to make sure your flags are up to date. See **this quest entry** [quest=3061] for more details._\n**Submitted by:** Saraban of Darkwind\n- Accursed Earhoop of Pain [item=34904]\n- Belt of the Black Dragon [item=34903]\n- Cloak of Deepshadow [item=34901]\n- Dark Heart of Vishimtar [item=34905]\n- Dragonkiller [item=35002]\n- Face of Unfeeling [item=35004]\n- Mottled Black Dragonscale [item=35003]\n- Norrath's Keepers Token [item=34991]\n- Obsidian Pauldrons [item=35206]\n- Radiant Crystal [item=34988]\n- Rod of Shaded Wrath [item=34902]\n- Shadowscale of Vishimtar [item=35001]\n- Skull of Vishimtar [item=35000]",
    },
    {
      id = "5227",
      title = "The Sword of Shadows",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Shadows",
      loc = { y = 445.0, x = 685.0, z = 0.0 },
      triggers = {
        "Hail, Xilixizan",
      },
      items_required = {
      },
      rewards = {
        { id = 93254, name = "Mysterious Sword", type = "item" },
        { id = 93392, name = "Globe of Pure Light", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Miragul's Nightmare [zone=755]\n**What:**\n- Mysterious Sword [item=93254]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 90\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Quest Items:**\n- Globe of Pure Light [item=93392]\n**Related Creatures:**\n- Xilixizan [npc=36505]\n- a battered chest [npc=36531]\n- a forgotten guardian [npc=36521]\n- a pool of darkness [npc=36508]\n- a shadowed beast [npc=36857]\n- a sorrowful shade [npc=36509]\n- a stalking shadow [npc=36511]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Nov 15 23:48:01 2010\nModified: Wed Jan 29 08:15:28 2025 | | _This is one of five pre-requisite tasks leading up to the Miragul's Nightmare mission, \"Miragul's Vendetta\". There are no pre-requisites for requesting this task._\n_To get this solo task, pick up \"A Mysterious Sword\", a groundspawn at approximately -100, 300 in Miragul's Nightmare (in the first clearing west of the zone-in), and right-click it._\nYou have been assigned the task 'The Sword of Shadows'.\nYou have found a mysterious sword that seems to whisper thoughts into your mind. What is its purpose? Perhaps only time will tell.\n\n---\n\n1\\. The sword thirsts for shadow. Defeat sorrowful shades to sate its desires 0/3 (Miragul's Nightmare)\n2\\. The sword thirsts for shadow. Defeat stalking shadows to sate its desires 0/3 (Miragul's Nightmare)\n3\\. The sword thirsts for shadow. Defeat pools of darkness to sate its desires 0/3 (Miragul's Nightmare)\n4\\. The sword calls for its former master. Talk to Xilixizan in Miragul's Nightmare 0/1 (Miragul's Nightmare)\n_Xilixizan is a mephit found at location 445, 685 (in the large clearing that is northwest of the sword's location)._\nYou say, 'Hail, Xilixizan'\nXilixizan says 'I was hoping this day would never come. You found the sword. Lest you wish to be overcome by shadow by its curse, you must listen to what I have to say. The sword must be destroyed. After the sword consumed me and made me shadow, I had nothing but time to find a way to permanently destroy the sword. Through my endless hours of research, I believe I have discovered the means to destroy the sword. The sword shuns light and the the only means to obtain such powerful items of light is from the forgotten guardians that guard the palace to the north. Gather these globes of pure light from the forgotten guardians and return to me. It is the only means to destroy the sword.'\n5\\. Collect a globe of pure light from the forgotten guardians 0/1 (Miragul's Nightmare)\n_This is a common drop from \"a forgotten guardian\" in the castle of Miragul's Nightmare. NOTE: The step will only update if dropped by a forgotten guardian. The ancient guardians drop the globe as well, but won't update the step._\n6\\. Return to Xilixizan and speak with him 0/1 (Miragul's Nightmare)\nYou say, 'Hail, Xilixizan'\nXilixizan says 'You collected the orbs? That is excellent news. The next step is to take the orbs of light along with the sword and place them in a chest. The chest is infused with a spell to destroy the sword. If all works as I hope it does, the sword will be destroyed and you will be safe from its curse. Look for the chest in the nearby ruins.'\n7\\. Place the globe of pure light into the battered chest 0/1 (Miragul's Nightmare)\n8\\. Place the mysterious sword into the battered chest 0/1 (Miragul's Nightmare)\n_A battered chest spawns at about 445, 440 (in the ruins east of Xilixizan's location)._\n9\\. The sword has been destroyed, but it has spawned a shadowed beast. Destroy it! 0/1 (Miragul's Nightmare)\n_A shadowed beast spawns as soon as you get the above updates. It attacks, hits for a max ~6,500 and is stunnable. If you got to this point in the task, you should handle this mob with ease._\na shadowed beast has been slain by \\_\\_\\_\\_\\_!\na shadowed beast's corpse is no longer a problem.\n10\\. Return to Xilixizan and inform him the sword has been destroyed 0/1 (Miragul's Nightmare)\nYou say, 'Hail, Xilixizan'\nXilixizan says 'I saw the flash of light from here when the sword was destroyed. I am pleased that you will not end up a servant of shadow as I have become. Although it is too late for me, I am glad you were able to save yourself. Please take this as a token of my gratitude. I will rest a bit easier knowing the sword will no longer trouble anyone.'\n\n---\n\n_Rewards:_\n315 platinum\nExperience\nFaction with Dream Delvers\n30 Dream Motes\n- Dream Mote [item=90255]",
    },
    {
      id = "5452",
      title = "Diminishing the Temple - Alarans",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Renarra",
      loc = nil,
      triggers = {
        "Hail, Renarra",
        "Take down the temple?",
        "I",
        "_Quests_",
        "take down",
        "help",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Sarith, City of Tides [zone=808]\n**Who:**\n- Renarra [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Alaran Language:** | 73\n**Quest Goal:**\n- Experience\n- Money\n**Related Zones:**\n- Rubak Oseka, Temple of the Sea [zone=809]\n**Related Creatures:**\n- a follower [npc=38549]\n- a worshipper [npc=38552]\n- an adherent [npc=38559]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Nov 21 20:10:25 2011\nModified: Tue Dec 5 05:21:04 2023 | | **For an overview of the Veil of Alaris expansion, a task listing, and information about group/raid progression, spells, and armor, **click here**.**\n\n---\n\n_This is a kill task that begins with a Kedge named Renarra in Sarith, located at about -60, -800, -2 (northeast part of the dock area)._\n_Pre-requisites for requesting the task:_\n\\- No tasks\n\\- Level 91\n\\- 73 Skill Level in Alaran\nYou say, 'Hail, Renarra'\nRenarra says '\\_\\_\\_\\_\\_! In the name of the Prexus, it's time to [take down] the Temple of Rubak Oseka!'\nYou say, 'Take down the temple?'\nRenarra says 'Before we launch our offense against the Temple, we need to weaken its inhabitants. Are you here to [help]?'\nYou say, 'I'll help!'\nRenarra says 'The Temple is filled with various inhabitants; mainly the Alarans and Hadal. There may also be ophidians as they are the beloved animals of Oseka, the God of Tides. Take your pick and remove them. Prexus will ensure you are greatly rewarded for your valiant efforts.'\n_A task window pops up with five tasks to choose from._\nYou have been assigned the task 'Diminishing the Temple - Alarans'.\nTo weaken Oseka's power, Renarra in Sarith wants you to defeat several of Oseka's followers in the Temple of Rubak Oseka. Go to the temple and defeat the Alarans.\n\n---\n\nDefeat the worshippers 0/4 (Rubak Oseka)\nDefeat the followers 0/4 (Rubak Oseka)\nDefeat the adherents 0/4 (Rubak Oseka)\nSpeak with Renarra 0/1 (Sarith)\nYou say, 'Hail, Renarra'\nThe number of Alarans in the Temple of Rubak Oseka has been significantly diminished.\n_Reward:_\nExperience\n136 platinum",
    },
    {
      id = "5453",
      title = "Diminishing the Temple - Zealots",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Renarra",
      loc = nil,
      triggers = {
        "Hail, Renarra",
        "Take down the temple?",
        "I",
        "_Quests_",
        "take down",
        "help",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Sarith, City of Tides [zone=808]\n**Who:**\n- Renarra [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Alaran Language:** | 73\n**Quest Goal:**\n- Experience\n- Money\n**Related Zones:**\n- Rubak Oseka, Temple of the Sea [zone=809]\n**Related Creatures:**\n- a zealot [npc=38561]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Nov 21 20:10:30 2011\nModified: Tue Dec 5 05:21:04 2023 | | **For an overview of the Veil of Alaris expansion, a task listing, and information about group/raid progression, spells, and armor, **click here**.**\n\n---\n\n_This is a kill task that begins with a Kedge named Renarra in Sarith, located at about -60, -800, -2 (northeast part of the dock area)._\n_Pre-requisites for requesting the task:_\n\\- No tasks\n\\- 73 Skill Level in Alaran\nYou say, 'Hail, Renarra'\nRenarra says '\\_\\_\\_\\_\\_! In the name of the Prexus, it's time to [take down] the Temple of Rubak Oseka!'\nYou say, 'Take down the temple?'\nRenarra says 'Before we launch our offense against the Temple, we need to weaken its inhabitants. Are you here to [help]?'\nYou say, 'I'll help!'\nRenarra says 'The Temple is filled with various inhabitants; mainly the Alarans and Hadal. There may also be ophidians as they are the beloved animals of Oseka, the God of Tides. Take your pick and remove them. Prexus will ensure you are greatly rewarded for your valiant efforts.'\n_A task window pops up with five tasks to choose from._\nYou have been assigned the task 'Diminishing the Temple - Zealots'.\nIn preparation of the attack on the Temple of Rubak Oseka, Renarra in Sarith wants you to defeat Oseka's followers in Rubak Oseka. You've been asked to reduce the amount of Alaran zealots in the temple.\n\n---\n\nDefeat the zealots 0/10 (Rubak Oseka)\nSpeak with Renarra 0/1 (Sarith)\nYou say, 'Hail, Renarra'\nThe population of Alaran zealots in the Temple of Rubak Oseka has been decreased.\n_Reward:_\nExperience\n205 platinum",
    },
    {
      id = "5454",
      title = "Diminishing the Temple - Priests and Acolytes",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Renarra",
      loc = nil,
      triggers = {
        "Hail, Renarra",
        "Take down the temple?",
        "I",
        "_Quests_",
        "take down",
        "help",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Sarith, City of Tides [zone=808]\n**Who:**\n- Renarra [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Alaran Language:** | 73\n**Quest Goal:**\n- Experience\n- Money\n**Related Zones:**\n- Rubak Oseka, Temple of the Sea [zone=809]\n**Related Creatures:**\n- a priest [npc=38550]\n- an acolyte [npc=38560]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Nov 21 20:10:36 2011\nModified: Tue Dec 5 05:21:04 2023 | | **For an overview of the Veil of Alaris expansion, a task listing, and information about group/raid progression, spells, and armor, **click here**.**\n\n---\n\n_This is a kill task that begins with a Kedge named Renarra in Sarith, located at about -60, -800, -2 (northeast part of the dock area)._\n_Pre-requisites for requesting the task:_\n\\- No tasks\n\\- 73 Skill Level in Alaran\nYou say, 'Hail, Renarra'\nRenarra says '\\_\\_\\_\\_\\_! In the name of the Prexus, it's time to [take down] the Temple of Rubak Oseka!'\nYou say, 'Take down the temple?'\nRenarra says 'Before we launch our offense against the Temple, we need to weaken its inhabitants. Are you here to [help]?'\nYou say, 'I'll help!'\nRenarra says 'The Temple is filled with various inhabitants; mainly the Alarans and Hadal. There may also be ophidians as they are the beloved animals of Oseka, the God of Tides. Take your pick and remove them. Prexus will ensure you are greatly rewarded for your valiant efforts.'\n_A task window pops up with five tasks to choose from._\nYou have been assigned the task 'Diminishing the Temple - Priests and Acolytes'.\nThe Hadal priests and acolytes contribute remarkably to Oseka's might. Renarra has asked you to extract them so they can provide no more power to his command.\n\n---\n\nDefeat the priests 0/5 (Rubak Oseka)\nDefeat the acolytes 0/5 (Rubak Oseka)\nSpeak with Renarra 0/1 (Sarith)\nYou say, 'Hail, Renarra'\nYou've stopped the Hadal priests and acolytes from strengthening Oseka. Victory is now one step closer.\n_Reward:_\nExperience\n136 platinum",
    },
    {
      id = "5455",
      title = "Diminishing the Temple - Hadal",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Renarra",
      loc = nil,
      triggers = {
        "Hail, Renarra",
        "Take down the temple?",
        "I",
        "_Quests_",
        "take down",
        "help",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Sarith, City of Tides [zone=808]\n**Who:**\n- Renarra [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Alaran Language:** | 73\n**Quest Goal:**\n- Experience\n- Money\n**Related Zones:**\n- Rubak Oseka, Temple of the Sea [zone=809]\n**Related Creatures:**\n- a servant [npc=38553]\n- a templar [npc=38557]\n- an altar attendant [npc=38558]\n- an evangelizer [npc=38551]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Nov 21 20:10:43 2011\nModified: Tue Dec 5 05:21:04 2023 | | **For an overview of the Veil of Alaris expansion, a task listing, and information about group/raid progression, spells, and armor, **click here**.**\n\n---\n\n_This is a kill task that begins with a Kedge named Renarra in Sarith, located at about -60, -800, -2 (northeast part of the dock area)._\n_Pre-requisites for requesting the task:_\n\\- No tasks\n\\- 73 Skill Level in Alaran\nYou say, 'Hail, Renarra'\nRenarra says '\\_\\_\\_\\_\\_! In the name of the Prexus, it's time to [take down] the Temple of Rubak Oseka!'\nYou say, 'Take down the temple?'\nRenarra says 'Before we launch our offense against the Temple, we need to weaken its inhabitants. Are you here to [help]?'\nYou say, 'I'll help!'\nRenarra says 'The Temple is filled with various inhabitants; mainly the Alarans and Hadal. There may also be ophidians as they are the beloved animals of Oseka, the God of Tides. Take your pick and remove them. Prexus will ensure you are greatly rewarded for your valiant efforts.'\n_A task window pops up with five tasks to choose from._\nYou have been assigned the task 'Diminishing the Temple - Hadal'.\nThe Hadal were the original creators of Oseka's temple. Renarra believes that killing their descendants may partially cripple Oseka's power. Sneak into the temple and annihilate the aboriginal inhabitants.\n\n---\n\nDefeat the altar attendants 0/2 (Rubak Oseka)\nDefeat evangelizers 0/4 (Rubak Oseka)\nDefeat the servants 0/2 (Rubak Oseka)\nDefeat the templars 0/2 (Rubak Oseka)\nSpeak with Renarra 0/1 (Sarith)\nYou say, 'Hail, Renarra'\nThe number of Hadal in the Temple of Rubak Oseka has been reduced.\n_Reward:_\nExperience\n136 platinum",
    },
    {
      id = "7201",
      title = "Putrid Skeletons",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 5,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = false,
      group_size = "Solo",
      npc = "The temple",
      loc = { y = -123.51, x = -127.12, z = 2.19 },
      triggers = {
        "Who is Niclaus?",
      },
      items_required = {
        { name = "him the note", count = 1 },
        { name = "it to Niclaus", count = 1 },
      },
      rewards = {
        { id = 2517, name = "Potion of Disease Warding", type = "item" },
        { id = 2555, name = "Potion of Light Healing", type = "item" },
        { id = 113106, name = "Shield of Nife", type = "item" },
        { id = 103981, name = "Skullcap of Rodcet Nife", type = "item" },
      },
      factions = {
        { name = "Priests of Life", change = 50 },
        { name = "Knights of Thunder", change = 15 },
        { name = "Guards of Qeynos", change = 25 },
        { name = "Bloodsabers", change = -12 },
        { name = "Antonius Bayle", change = 7 },
        { name = "Priests of Life", change = 50 },
      },
      walkthrough = "**Level:** 5\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nRoesager Thusten is the Paladin Guildmaster in the building on the right when you enter the Temple of Life complex in North Qeynos (/loc -123.51, -127.12, 2.19).\nYou will need to be at least Amiable to Priests of Life for Niclaus to talk to you.\nYou say, 'Who is Niclaus?'\nHow do you know to say this?\nRoesager Thusten says 'Niclaus Ressinn? Have you seen him? He is one of our paladins who was sent out to investigate the undead sightings in Qeynos Hills. I have a message from Jahnda for him, but I must continue my own search here in Qeynos. Could you take this to Niclaus? Your help would be appreciated.'\nAt indifferent faction, Roseager says 'The Temple of Life smiles upon you, friend...  but such a delicate matter can only be entrusted to our most loyal members.'\nYou receive a Note to Niclaus.\nYou need 200 faction (high amiable) to get the note to Niclauss.\nNiclaus roams the Qeynos Hills.  Give him the note.\nNiclaus Ressinn says 'Oh, things are becoming dire here in Norrath. May Rodcet protect us! I have gathered most of the evidence I will need to present to Jahnda, but I could still use your assistance with one final piece. I need to recover a rib bone from of the undead beasts that wander these hills. Be sure the rib bone comes from one of the putrid skeletons. They are the spawn of Bertoxxulous.'\n(need confirmation that there are no faction hits for this step)\nYou receive 4 copper.\nYou gain experience!!\nFind and kill a putrid skeleton and loot a Putrid Rib Bone.  Give it to Niclaus.\nNiclaus Ressinn says 'Excellent! Rodcet smiles upon us this day! Here, please take this pouch of evidence to Jahnda in the Temple of Life. She will know what we must do. I will remain here to keep an eye out for the minions of Bertoxxlous. Also, accept this small reward as a token of my appreciation of your efforts to rid Norrath of the influence of the Plaguebringer.'\nYour faction standing with Priests of Life has been adjusted by 50.\nYour faction standing with Knights of Thunder has been adjusted by 15.\nYour faction standing with Guards of Qeynos has been adjusted by 25.\nYour faction standing with Bloodsabers has been adjusted by -12.\nYour faction standing with Antonius Bayle has been adjusted by 7.\nYou receive 1 gold.\nYou receive 2 silver.\nYou receive 6 copper.\nYou gain experience!!\nYou receive a Pouch of Evidence.  Give it to Priestess Jahnda in the Temple of Life in North Qeynos, found at -64.93, -677.59, -11.81.\nPriestess Jahnda says 'Excellent work! You are surely under the protection and guidance of the Prime Healer. This evidence will help us greatly to convince Antonious and the guild leaders of Qeynos that the Bloodsabers are here and seek to destroy all we have worked so long for.'\nYour faction standing with Priests of Life has been adjusted by 50.\nYour faction standing with Knights of Thunder has been adjusted by 15.\nYour faction standing with Guards of Qeynos has been adjusted by 25.\nYour faction standing with Bloodsabers has been adjusted by -12.\nYour faction standing with Antonius Bayle has been adjusted by 7.\nYou receive 5 gold.\nYou gain experience!!\nCommon rewards are a Potion of Disease Warding or Potion of Light Healing.  Rare rewards are a Skullcap of Rodcet Nife or a Shield of Nife.Submitted by: alla4eqRewards:\n- Potion of Disease Warding [item=2517]\n- Potion of Light Healing [item=2555]\n- Shield of Nife [item=113106]\n- Skullcap of Rodcet Nife [item=103981]\n[",
    },
    {
      id = "8583",
      title = "Hunter of The Temple of Droga [RoK] (30 Points)",
      exp = "05",
      exp_name = "The Legacy of Ykesha",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "The temple",
      loc = nil,
      triggers = {
        "RoK",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon defeating the following rare monsters in Temple of Droga:\nMagic Adept Xabok\nBone Trooper Grolin\nBone Caller Nathid\nStone Crook Piklo\nWhip Cracker Krazzim\nEarth Mystic Gedak\nBone Knight Runri\nDirt Criminal Vakov\na savage drogan spider\nCave Guardian Prehtil\nIce Adept Amozik\nStone Seer Kaigek\nStalag Trooper Biamas\nDeath Ritualist Stromik\nRock Sneak Nrillip\na fierce drogan spider\nFlame Master Japal\nBone Caster Fizzik\nIce Master Cialin\nDust Hoodlum Heaprit\nKing Dronan\nEarth Seer Gamolk\nJailor Maufan\nDirt Defender Gropp\nFlame Adept Verdalix\nMoss Knight Yortal\nBlood Ritualist Taprom\nSlinker Ukul\nAdd the following points to the droga_1.txt file:\nP -300.0000, -1400.0000, 0.0000,     0, 127, 0,  3,      Frontier_Mountains\nP -100.0000, 1300.0000, 0.0000,      0, 127, 0,  3,      Mines_of_Nurga\nP 919.0000, 1319.0000, 0.0000,       0, 127, 0,  3,      Mines_of_Nurga\nP -2195.2881, 419.3750, -351.8430,   0, 0, 240,  2,      a_goblin_food_supplier\nP -1297.1486, 218.9572, -254.3749,   0, 0, 240,  2,      Gillia_Brissok\nP -1736.2939, -474.7800, -254.3103,  0, 0, 240,  2,      Jeren_Manri\nP -1280.9291, 215.7526, -254.3712,   240, 240, 240,  1,  Droga_Jail_Key\nP -1251.4043, 237.8119, -254.2655,   240, 240, 240,  1,  Droga_Jail_Key\nP -1147.2338, 201.1825, -254.3807,   240, 240, 240,  1,  Droga_Jail_Key\nP -1241.4268, 173.7716, -254.3478,   240, 240, 240,  1,  Droga_Jail_Key\nP -1240.3267, 148.3416, -254.3468,   240, 240, 240,  1,  Droga_Jail_Key\nP -290.0000, -1375.0000, 0.0000,     240, 240, 240,  3,  Succor_Point\nP -1108.7170, 196.8150, -255.9050,   240, 240, 240,  1,  Tinmizer's_Stupendous_Contraption\nAdd the following points to the droga_2.txt file:\nP -1461.5597, -546.4302, -254.2626,     240, 0, 0,  2,  Blood_Ritualist_Taprom\nP 835.0000, 339.0000, 0.0000,           240, 0, 0,  2,  Blood_Ritualist_Taprom\nP -1787.6104, -344.3056, -270.3123,     240, 0, 0,  2,  Bone_Caller_Nathid\nP -227.0000, -367.0000, 0.0000,         240, 0, 0,  2,  Bone_Caller_Nathid\nP -1790.0000, 33.0000, 0.0000,          240, 0, 0,  2,  Bone_Caster_Fizzik\nP -1457.8199, -460.8020, -255.9040,     240, 0, 0,  2,  Bone_Caster_Fizzik\nP 296.0000, -224.0000, 0.0000,          240, 0, 0,  2,  Bone_Knight_Runri\nP -1986.5430, -124.6460, -287.8730,     240, 0, 0,  2,  Bone_Knight_Runri\nP -567.0000, -49.0000, 0.0000,          240, 0, 0,  2,  Bone_Trooper_Grolin\nP -1749.8921, -357.6024, -270.3083,     240, 0, 0,  2,  Bone_Trooper_Grolin\nP -160.0000, 575.0000, 0.0000,          240, 0, 0,  2,  Cave_Guardian_Prehtil\nP -2080.0659, -261.4020, -287.3710,     240, 0, 0,  2,  Cave_Guardian_Prehtil\nP -1417.9335, -350.9600, -254.3389,     240, 0, 0,  2,  Death_Ritualist_Stromik\nP -1012.0000, 648.0000, 0.0000,         240, 0, 0,  2,  Death_Ritualist_Stromik\nP 106.0000, -380.0000, 0.0000,          240, 0, 0,  2,  Dirt_Criminal_Vakov\nP -2008.2690, -125.7110, -287.8730,     240, 0, 0,  2,  Dirt_Criminal_Vakov\nP 1405.0000, 276.0000, 0.0000,          240, 0, 0,  2,  Dirt_Defender_Gropp\nP -1475.8180, -617.3190, -255.9040,     240, 0, 0,  2,  Dirt_Defender_Gropp\nP -2118.0000, 571.0000, 0.0000,         240, 0, 0,  2,  Dust_Hoodlum_Heaprit\nP -1371.9821, -542.7980, -255.9040,     240, 0, 0,  2,  Dust_Hoodlum_Heaprit\nP 195.0000, 105.0000, 0.0000,           240, 0, 0,  2,  Earth_Mystic_Gedak\nP -1956.3320, -194.1250, -287.8730,     240, 0, 0,  2,  Earth_Mystic_Gedak\nP -1944.0000, -629.0000, 50.0000,       240, 0, 0,  2,  Earth_Seer_Gamolk\nP -396.0000, 234.0000, 0.0000,          240, 0, 0,  2,  a_fierce_drogan_spider_(roamer)\nP -1261.3220, 286.0930, -255.9040,      240, 0, 0,  2,  a_fierce_drogan_spider\nP -2118.6960, 577.2060, -335.8730,      240, 0, 0,  2,  a_fierce_drogan_spider\nP 954.0000, 363.0000, 0.0000,           240, 0, 0,  2,  Flame_Adept_Verdalix\nP -1508.5400, -606.5950, -255.9040,     240, 0, 0,  2,  Flame_Adept_Verdalix\nP -1608.0000, -126.0000, 0.0000,        240, 0, 0,  2,  Flame_Master_Japel\nP -1444.0950, -506.0760, -255.5220,     240, 0, 0,  2,  Flame_Master_Japal\nP -226.0000, 488.0000, 0.0000,          240, 0, 0,  2,  Ice_Adept_Amozik\nP -2044.3910, -265.0310, -287.5050,     240, 0, 0,  2,  Ice_Adept_Amozik\nP -1400.0830, -499.8590, -255.9040,     240, 0, 0,  2,  Ice_Master_Cialin\nP -2015.0000, 464.0000, 0.0000,         240, 0, 0,  2,  Ice_Master_Cialin\nP -1053.0000, 2.0000, 0.0000,           240, 0, 0,  2,  Jailor_Maufan\nP -1428.5439, -620.9950, -255.9040,     240, 0, 0,  2,  Jailor_Maufan\nP -1941.1742, -748.0585, -266.3487,     240, 0, 0,  2,  King_Dronan\nP -541.0000, -317.0000, 0.0000,         240, 0, 0,  2,  Magic_Adept_Xabok\nP -1712.8440, -337.0180, -271.9040,     240, 0, 0,  2,  Magic_Adept_Xabok\nP -1509.9680, -563.1590, -255.9040,     240, 0, 0,  2,  Moss_Knight_Yortal\nP 877.0000, -237.0000, 0.0000,          240, 0, 0,  2,  Moss_Knight_Yortal\nP -385.0000, 246.0000, 0.0000,          240, 0, 0,  2,  Rock_Sneak_Nrillip\nP -1435.3051, -375.9070, -255.9040,     240, 0, 0,  2,  Rock_Sneak_Nrillip\nP -1976.2950, -736.4280, -266.8740,     240, 0, 0,  2,  A_savage_drogan_spider\nP -2161.6050, 60.1940, -335.8730,       240, 0, 0,  2,  Slinker_Ukul\nP 1062.0000, -190.0000, 0.0000,         240, 0, 0,  2,  Slinker_Ukul\nP -1997.0830, 142.9510, -351.8420,      240, 0, 0,  2,  Stalag_Trooper_Biamas\nP 623.0000, 481.0000, 0.0000,           240, 0, 0,  2,  Stalag_Trooper_Biamas\nP -193.0000, -92.0000, 0.0000,          240, 0, 0,  2,  Stone_Crook_Piklo\nP -1803.4628, -320.1422, -270.3308,     240, 0, 0,  2,  Stone_Crook_Piklo\nP -2185.4500, 253.8130, -335.8730,      240, 0, 0,  2,  Stone_Seer_Kaigek\nP 524.0000, 886.0000, 0.0000,           240, 0, 0,  2,  Stone_Seer_Kaigek\nP 181.0000, -2.0000, 0.0000,            240, 0, 0,  2,  Whip_Cracker_Krazzim\nP -1792.1311, -287.1335, -270.3201,     240, 0, 0,  2,  Whip_Cracker_Krazzim\nP -1084.8621, 58.8510, -255.9050,       240, 0, 0,  2,  a_goblin_prison_warden\nAdd the following points to the droga_3.txt file:\nP 0.0000, 0.0000, 0.0000,          127, 64, 0,  2,  0\nP -2000.0000, -1775.0000, 0.0000,  127, 64, 0,  2,  2000\nP -1500.0000, -1775.0000, 0.0000,  127, 64, 0,  2,  1500\nP -1000.0000, -1775.0000, 0.0000,  127, 64, 0,  2,  1000\nP -500.0000, -1775.0000, 0.0000,   127, 64, 0,  2,  500\nP 0.0000, -1775.0000, 0.0000,      127, 64, 0,  2,  0\nP 500.0000, -1775.0000, 0.0000,    127, 64, 0,  2,  -500\nP 1000.0000, -1775.0000, 0.0000,   127, 64, 0,  2,  -1000\nP 1500.0000, -1775.0000, 0.0000,   127, 64, 0,  2,  -1500\nP -2503.0000, -1510.0000, 0.0000,  127, 64, 0,  2,  1500\nP -2503.0000, -1010.0000, 0.0000,  127, 64, 0,  2,  1000\nP -2503.0000, -510.0000, 0.0000,   127, 64, 0,  2,  500\nP -2503.0000, 0.0000, 0.0000,      127, 64, 0,  2,  0\nP -2503.0000, 490.0000, 0.0000,    127, 64, 0,  2,  -500\nP -2503.0000, 990.0000, 0.0000,    127, 64, 0,  2,  -1000\nP -2503.0000, 1490.0000, 0.0000,   127, 64, 0,  2,  -1500\nP 0.0000, 1490.0000, 0.0000,       127, 64, 0,  2,  File_Set_=_droga.txtSubmitted by: GidonoRewards:\n[",
    },
    {
      id = "8617",
      title = "Conqueror of The Temple of Veeshan",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "The temple",
      loc = nil,
      triggers = {
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon completing the following raids in The Temple of Veeshan:\nCasalen\nCekenar\nDagarn the Destroyer\nDozekar the Cursed\nEashen of the Sky\nEssedera\nGozzrem\nGrozzmel\nIkatiar the Venom\nJorlleag\nKrigara\nLady Mirenilla\nLady Nevederia\nLendiniara the Keeper\nLepethida\nLord Feshlak\nLord Vyemm\nMidayor\nSevalak\nTavekalem\nTelkorenar\nVulak`Aerr\nYmmeln\nZemmSubmitted by: GidonoRewards:\n[",
    },
    {
      id = "9497",
      title = "The Temple of Droga Traveler (10 Points)",
      exp = "05",
      exp_name = "The Legacy of Ykesha",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "The temple",
      loc = nil,
      triggers = {
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon visiting The Temple of Droga.\nVisit The Temple of DrogaSubmitted by: GidonoRewards:\n[",
    },
    {
      id = "9512",
      title = "The Tower of Frozen Shadow Traveler (10 Points)",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "Shadows",
      loc = nil,
      triggers = {
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon visiting The Tower of Frozen Shadow.\nVisit The Tower of Frozen ShadowSubmitted by: GidonoRewards:\n[",
    },
    {
      id = "9526",
      title = "The Temple of Veeshan Traveler (10 Points)",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "The temple",
      loc = nil,
      triggers = {
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon visiting The Temple of Veeshan Traveler.\nVisit The Temple of VeeshanSubmitted by: GidonoRewards:\n[",
    },
  },
}
