-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Valley of Lunanyn (arelis)
-- Total Quests: 13
-- ============================================================================

return {
  zone = "arelis",
  zone_name = "Valley of Lunanyn",
  quests = {
    {
      id = "5418",
      title = "Lunanyn \\#2: The Assassination Game",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Geirdan Ath",
      loc = { y = 2295.0, x = -1700.0, z = 46.0 },
      triggers = {
        "Hail, Geirdan Ath",
        "Convinced?",
        "My stomach",
        "help",
        "convinced",
        "stomach",
      },
      items_required = {
        { name = "up the fight against Geirdan's army", count = 1 },
      },
      rewards = {
        { id = 98146, name = "Life and Death\n- Eltarki's Diary - Life and Death", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Valley of Lunanyn [zone=807]\n**Who:**\n- Geirdan Ath [npc=38147]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 90\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n**Success Lockout Timer**: 06:00:00\n**Related Creatures:**\n- Algot Yor [npc=38154]\n- Egot Mek [npc=38153]\n- Hemot Talas [npc=38280]\n- a mosstrooper [npc=38263]\n**Related Quests:**\n- Lunanyn #1: Raid and Recover [quest=5395]\n- Lunanyn #3: Uncharted Territory [quest=5419]\n- Lunanyn #4: The Enemy of My Enemy [quest=5420]\n- Lunanyn #5: The Memory Remains [quest=5421]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 16 02:37:15 2011\nModified: Tue Dec 5 05:21:04 2023 | | **Veil of Alaris Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This task is the second in a series of five; a solo task that begins with Geirdan Ath in the Valley of Lunanyn, located at 2295, -1700, 46 (in a building in the southeast part of the upper section of the zone)._\n_Pre-requisites for requesting the task:_\n\\- Completion of \"Raid and Recover\"\n\\- (no minimum required skill level in Alaran Language)\nYou say, 'Hail, Geirdan Ath'\nGeirdan Ath says 'I am glad to have you back. Your [help] was much appreciated last time. Our occupation here is important in finding out what happened to Cazic Thule and who stole his power. But until then, these farmers are causing some problems for us. Their involvement makes it more difficult than necessary in our fight against the Prophet's Army. Perhaps they can be [convinced] that our fight is not with them.'\nYou say, 'Convinced?'\nGeirdan Ath says 'You may have to be... blunt... in the manner in which you convince them of this. But I trust you can find a way. Unless your [stomach] is not in this.'\nYou say, 'My stomach's in it'\nGeirdan Ath says 'Excellent! There are three leaders that you must deal with. Egot Mek, Algot Yor, and Hemot Talas. Once they are dealt with, I am sure the others will fall in line. '\nYou have been assigned the task 'The Assassination Game'.\nGeirdan Ath is concerned about the farmers within the valley. Although they share a common enemy, the farmers still choose to fight the Rallosian forces. They pray to nature to create barbarous mosstroopers, which make it difficult to concentrate on the Prophet's army itself. Perhaps if the farmers had no leadership, it would convince them to give up the fight against Geirdan's army.\nPerhaps you can convince Egot Mek to lay down alir arms. Al tends the land high in the northwestern terraces.\n\n---\n\n_You'll have to hail and kill three named farmers in the northwestern boundary part of the zone._\n_NOTE: If you have multiple people in the same party doing this task at the same, you can prevent non-update issues by doing the hails while everyone is invisible, then breaking the invis to kill the mob._\nSpeak to Egot Mek 0/1 (Valley of Lunanyn)\nKill Egot Mek 0/1 (Valley of Lunanyn)\nSpeak to Algot Yor 0/1 (Valley of Lunanyn)\nKill Algot Yor 0/1 (Valley of Lunanyn)\nSpeak to Hemot Talas 0/1 (Valley of Lunanyn)\nKill Hemot Talas 0/1 (Valley of Lunanyn)\nSpeak to Geirdan Ath 0/1 (Valley of Lunanyn)\nYou say, 'Hail, Geirdan Ath'\nGeirdan Ath says 'Excellent work! Now kill those moss troopers they have been creating. Thinning their number should help quite a bit.'\nKill 4 mosstroopers 0/4 (Valley of Lunanyn)\nSpeak to Geirdan Ath 0/1 (Valley of Lunanyn)\nYou say, 'Hail, Geirdan Ath'\nGeirdan Ath says 'Perhaps now these farmers will cooperate! '\nYou were able to put a stop to the raiders and have freed the missing soldiers, at least until more their reinforcements can arrive. With fewer moss troopers around, it should make traveling a bit easier for his men.\n_Rewards:_\nEltarki's Diary - Life and Death\n- Eltarki's Diary - Life and Death [item=98146]",
    },
    {
      id = "5395",
      title = "Lunanyn \\#1: Raid and Recover",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Geirdan Ath",
      loc = { y = 2295.0, x = -1700.0, z = 46.0 },
      triggers = {
        "Hail, Geirdan Ath",
        "How were they lost?",
        "What about the crops?",
        "I",
        "lost",
        "crops",
        "help",
      },
      items_required = {
      },
      rewards = {
        { id = 98146, name = "Life and Death\n- Eltarki's Diary - Life and Death", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Valley of Lunanyn [zone=807]\n**Who:**\n- Geirdan Ath [npc=38147]\nRating:\n0/3**_\\*__\\*__\\*__\\*__\\*_**\n(Average from 3 ratings)\nInformation:\n**Level:** | 90\n**Maximum Level:** | 95\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n**Related Creatures:**\n- a missing soldier [npc=38156]\n- a trooper [npc=38157]\n**Related Quests:**\n- Lunanyn #2: The Assassination Game [quest=5418]\n- Lunanyn #3: Uncharted Territory [quest=5419]\n- Lunanyn #4: The Enemy of My Enemy [quest=5420]\n- Lunanyn #5: The Memory Remains [quest=5421]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 15 17:31:48 2011\nModified: Fri Mar 11 02:00:08 2022 | | **Veil of Alaris Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This task is the first in a series of five; a solo task that begins with Geirdan Ath in the Valley of Lunanyn, located at 2295, -1700, 46 (in a building in the southeast part of the upper section of the zone)._\n_Pre-requisites for requesting the task:_\n\\- No tasks\n\\- (no minimum required skill level in Alaran Language)\n\n---\n\nYou say, 'Hail, Geirdan Ath'\nGeirdan Ath says 'You are not one of mine! But you can be of use to me! We have [lost] many men recently and are unable to stop the Prophet's Army from raiding the crops here.'\nYou say, 'How were they lost?'\nGeirdan Ath says 'Most of them have been killed in battle, but we are missing some that were on patrol. They seem to have vanished without a trace. I suspect the Prophet's Army is to blame. They are struggling to take the [crops] here to support their army and it is only a matter of time before they will outlast us.'\nYou say, 'What about the crops?'\nGeirdan Ath says 'They take the crops from their own people, who hide in fear from their own army. Will you [help] us?'\nYou say, 'I'll help'\nGeirdan Ath says 'Excellent! I will see to it that you rewarded should your efforts prove successful!'\nYou have been assigned the task 'Raid and Recover'.\nGeirdan Ath is spread thin until reinforcements arrive. He will need you to seek out the Erillion Army raiding parties and put a stop to their taking of the local crops. You will need to be careful during your engagements as the Prophet's army has been taking prisoners for a reason that Geirdan has yet to ascertain. He would also like you to find the soldiers that have gone missing.\nYou must slow down the Prophet's army from taking the crops to their troops.\n\n---\n\nFind the camp that is keeping the soldiers hostage 0/1 (Valley of Lunanyn)\n_This is the large camp in the southern end of the zone, you can find it at /waypoint -994, 395, -40. You can update this step invis._\nKill 5 troopers 0/5 (Valley of Lunanyn)\nSpeak with a missing soldier 0/1 (Valley of Lunanyn)\nSpeak with a missing soldier 0/1 (Valley of Lunanyn)\nSpeak with a missing soldier 0/1 (Valley of Lunanyn)\nSpeak with a missing soldier 0/1 (Valley of Lunanyn)\na missing soldier says 'Thank you! I knew someone would come help me!'\na missing soldier says 'You sure took your time freeing me didn't you?'\na missing soldier says 'These Alaran scum will get what's coming to them if it's the last thing I do!'\na missing soldier says 'I knew the Geirdan wouldn't forget about me! I am his right hand man after all.'\n_The missing soldiers are found in the tents in the same camp._\nSpeak with Geirdan Ath 0/1 (Valley of Lunanyn)\nYou say, 'Hail, Geirdan Ath'\nGeirdan Ath says 'You have returned! Your efforts to stop the raiding of the crops will help greatly. Though, I am concerned that we were unable to find out why they are taking my men. '\nYou were able to put a stop to the raiders and have freed the missing soldiers, at least until their reinforcements can arrive.\n_Rewards:_\n106 platinum\nExperience\nEltarki's Diary - Life and Death\n- Eltarki's Diary - Life and Death [item=98146]",
    },
    {
      id = "5396",
      title = "Pest Control",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Mabus",
      loc = { y = 2530.0, x = -220.0, z = 15.0 },
      triggers = {
        "Hail, Mabus",
        "Share your fate?",
        "Unless...",
        "Divert them?",
        "I",
        "_Quests_",
        "share our fate",
        "Unless",
      },
      items_required = {
      },
      rewards = {
        { id = 98146, name = "Eltarki's Diary - Life and Death", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Valley of Lunanyn [zone=807]\n**Who:**\n- Mabus [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 90\n**Maximum Level:** | 95\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n**Related Creatures:**\n- a soldier [npc=38367]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 15 17:34:59 2011\nModified: Mon May 6 02:11:32 2024 | | **Veil of Alaris Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This solo kill task begins with Mabus in the Valley of Lunanyn, located at 2530, -220, 15 (along the south-southwestern wall of the upper section of the zone)._\nYou say, 'Hail, Mabus'\nMabus says, in Alaran, 'Hail, friend. You should leave this place, if you do not wish to [share our fate].'\nYou say, 'Share your fate?'\nMabus says, in Alaran, 'You see how these soldiers have destroyed many of our crops? With most of our fields smoldering, and the soldiers demanding of us all that we reap, we cannot hope to escape famine! [Unless]...'\nYou say, 'Unless...'\nMabus says, in Alaran, 'Although I know you alone could not defeat such an army as this, if you could [divert them], we may be able to gather enough food from the fields to survive.'\nYou say, 'Divert them?'\nMabus says, in Alaran, 'If you would help us, we seem to have a bit of a [vermin infestation]', it gives you an eery wink, with both sets of eyes, 'and we could also use help with [fertilizing the fields], [reaping the harvest].'\nYou say, 'I'll help with the vermin infestation'\nMabus says, in Alaran, 'Many thanks to you, \\_\\_\\_\\_\\_.'\nYou have been assigned the task 'Pest Control'.\nMabus wants you to take care of an infestation of sorts. Kill the Erillion soldiers who have invaded alir homeland.\n\n---\n\nKill 15 soldiers 0/15 (Valley of Lunanyn)\nSpeak with Mabus 0/1 (Valley of Lunanyn)\nYou say, 'Hail, Mabus'\nYou have helped Mabus rid the valley of unwanted \"pests\".\n_Rewards:_\n160 platinum\nExperience\n- Eltarki's Diary - Life and Death [item=98146]",
    },
    {
      id = "5397",
      title = "Reaping the Harvest",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Mabus",
      loc = { y = 2530.0, x = -220.0, z = 15.0 },
      triggers = {
        "Hail, Mabus",
        "Share your fate?",
        "Unless...",
        "Divert them?",
        "I",
        "_Quests_",
        "share our fate",
        "Unless",
      },
      items_required = {
      },
      rewards = {
        { id = 98146, name = "Eltarki's Diary - Life and Death", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Valley of Lunanyn [zone=807]\n**Who:**\n- Mabus [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 90\n**Maximum Level:** | 95\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n**Related Creatures:**\n- a ranger [npc=38369]\n- a trooper [npc=38157]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 15 17:35:35 2011\nModified: Sat Feb 8 15:50:13 2020 | | **Veil of Alaris Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This solo kill task begins with Mabus in the Valley of Lunanyn, located at 2530, -220, 15 (along the south-southwestern wall of the upper section of the zone)._\nYou say, 'Hail, Mabus'\nMabus says, in Alaran, 'Hail, friend. You should leave this place, if you do not wish to [share our fate].'\nYou say, 'Share your fate?'\nMabus says, in Alaran, 'You see how these soldiers have destroyed many of our crops? With most of our fields smoldering, and the soldiers demanding of us all that we reap, we cannot hope to escape famine! [Unless]...'\nYou say, 'Unless...'\nMabus says, in Alaran, 'Although I know you alone could not defeat such an army as this, if you could [divert them], we may be able to gather enough food from the fields to survive.'\nYou say, 'Divert them?'\nMabus says, in Alaran, 'If you would help us, we seem to have a bit of a [vermin infestation]', it gives you an eery wink, with both sets of eyes, 'and we could also use help with [fertilizing the fields], [reaping the harvest].'\nYou say, 'I'll help with reaping the harvest'\nMabus says, in Alaran, 'We are ever in your debt, \\_\\_\\_\\_\\_.'\nYou have been assigned the task 'Reaping the Harvest'.\nMabus told you, 'I feel there's something unusual about these Erillion rangers. Oh! I know what it is - they're all upright. I'm just not used to seeing rangers alive. They are real troopers. Willing to DIE for our cause!'\n\n---\n\nKill 5 rangers 0/5 (Valley of Lunanyn)\nKill 10 troopers 0/10 (Valley of Lunanyn)\nSpeak with Mabus 0/1 (Valley of Lunanyn)\nYou say, 'Hail, Mabus'\nAt Mabus' request, you have ensured that no ranger in the Valley is left standing!\n_Rewards:_\n106 platinum\nExperience\n- Eltarki's Diary - Life and Death [item=98146]",
    },
    {
      id = "5398",
      title = "Fertilizer for the Crops",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Mabus",
      loc = { y = 2530.0, x = -220.0, z = 15.0 },
      triggers = {
        "Hail, Mabus",
        "Share your fate?",
        "Unless...",
        "Divert them?",
        "I",
        "_Quests_",
        "share our fate",
        "Unless",
      },
      items_required = {
      },
      rewards = {
        { id = 98146, name = "Eltarki's Diary - Life and Death", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Valley of Lunanyn [zone=807]\n**Who:**\n- Mabus [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 90\n**Maximum Level:** | 95\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n**Related Creatures:**\n- an Argathian traitor [npc=38362]\n- an impaler [npc=38368]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 15 17:36:31 2011\nModified: Sat Feb 8 15:50:13 2020 | | **Veil of Alaris Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This solo kill task begins with Mabus in the Valley of Lunanyn, located at 2530, -220, 15 (along the south-southwestern wall of the upper section of the zone)._\nYou say, 'Hail, Mabus'\nMabus says, in Alaran, 'Hail, friend. You should leave this place, if you do not wish to [share our fate].'\nYou say, 'Share your fate?'\nMabus says, in Alaran, 'You see how these soldiers have destroyed many of our crops? With most of our fields smoldering, and the soldiers demanding of us all that we reap, we cannot hope to escape famine! [Unless]...'\nYou say, 'Unless...'\nMabus says, in Alaran, 'Although I know you alone could not defeat such an army as this, if you could [divert them], we may be able to gather enough food from the fields to survive.'\nYou say, 'Divert them?'\nMabus says, in Alaran, 'If you would help us, we seem to have a bit of a [vermin infestation]', it gives you an eery wink, with both sets of eyes, 'and we could also use help with [fertilizing the fields], [reaping the harvest].'\nYou say, 'I'll help with fertilizing the fields'\nMabus says, in Alaran, 'You hold our hope in your hands, \\_\\_\\_\\_\\_.'\nYou have been assigned the task 'Fertilizer for the Crops'.\nHelp Mabus rid Alir fields of Erillion impalers, as well as an Argathian traitor. Their corpses will be fertilizer for the crops; their blood, water for the fields!\n\n---\n\nKill 10 impalers 0/10 (Valley of Lunanyn)\nKill 1 Argathian traitor 0/1 (Valley of Lunanyn)\nSpeak with Mabus 0/1 (Valley of Lunanyn)\nYou say, 'Hail, Mabus'\nYou have helped Mabus acquire some unusual \"fertilizer\" for the crops in the valley.\n_Rewards:_\n106 platinum\nExperience\n- Eltarki's Diary - Life and Death [item=98146]",
    },
    {
      id = "5399",
      title = "It's a Dog-Eat-Cat World Out There",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Kallik the Cook",
      loc = { y = 1730.0, x = -1130.0, z = -46.0 },
      triggers = {
        "Hail, Kallik the Cook",
        "Bad news?",
        "What eerie cats?",
        "bad news",
        "eerie cats",
        "vermin",
      },
      items_required = {
      },
      rewards = {
        { id = 98146, name = "Eltarki's Diary - Life and Death", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Valley of Lunanyn [zone=807]\n**Who:**\n- Kallik the Cook [npc=38150]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 90\n**Maximum Level:** | 95\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n**Related Creatures:**\n- a ferocious grendlaen [npc=38377]\n- a grendlaen cub [npc=38376]\n- a wicked grendlaen [npc=38374]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 15 17:39:51 2011\nModified: Sat Feb 8 15:50:13 2020 | | **Veil of Alaris Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This solo kill task begins with Kallik the Cook in the Valley of Lunanyn, located at 1730, -1130, -46 (in the Rallosian camp in the northeastern part of the larger section of the zone)._\nYou say, 'Hail, Kallik the Cook'\nKallik the Cook says 'What is it now?!' He brandishes a cleaver, as he turns towards you, but suddenly halts in surprise, 'Oh! I'm sorry, I thought you were my assistant with more [bad news].'\nYou say, 'Bad news?'\nKallik the Cook says 'We've been having some real trouble with our food provisions. Those [eerie cats] have been raiding my meat supplies every night. And if that wasn't bad enough, the whole camp is swarming with [vermin] - some of which look as though they may be diseased! I ask you, how's a Halfling to cook in these conditions?!'\nYou say, 'What eerie cats?'\nKallik the Cook says 'Here now, if you've got nothing better to do, you could really help us out by killing some of those creepy cats that roam the hillsides.'\nYou have been assigned the task 'It's a Dog-Eat-Cat World Out There'.\nKallik wants you to kill the grendlaens which have been raiding his meat supply.\n\n---\n\nKill 2 wicked grendlaens 0/2 (Valley of Lunanyn)\nKill 3 ferocious grendlaens 0/3 (Valley of Lunanyn)\nKill 4 grendlaen cubs 0/4 (Valley of Lunanyn)\nSpeak with Kallik the Cook 0/1 (Valley of Lunanyn)\nYou say, 'Hail, Kallik the Cook'\nKallik the Cook claps his hands together in appreciation, clearly impressed with your grendlaen killing abilities.\n_Rewards:_\n160 platinum\nExperience\n- Eltarki's Diary - Life and Death [item=98146]",
    },
    {
      id = "5400",
      title = "Rat-a-Chewy",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Kallik the Cook",
      loc = { y = 1730.0, x = -1130.0, z = -46.0 },
      triggers = {
        "Hail, Kallik the Cook",
        "Bad news?",
        "What vermin?",
        "bad news",
        "eerie cats",
        "vermin",
      },
      items_required = {
      },
      rewards = {
        { id = 98146, name = "Eltarki's Diary - Life and Death", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Valley of Lunanyn [zone=807]\n**Who:**\n- Kallik the Cook [npc=38150]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 90\n**Maximum Level:** | 95\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n**Related Creatures:**\n- a dirty oashim [npc=38261]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 15 17:40:46 2011\nModified: Sat Feb 8 15:50:13 2020 | | **Veil of Alaris Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This solo kill task begins with Kallik the Cook in the Valley of Lunanyn, located at 1730, -1130, -46(in the Rallosian camp in the northeastern part of the larger section of the zone)._\nYou say, 'Hail, Kallik the Cook'\nKallik the Cook says 'What is it now?!' He brandishes a cleaver, as he turns towards you, but suddenly halts in surprise, 'Oh! I'm sorry, I thought you were my assistant with more [bad news].'\nYou say, 'Bad news?'\nKallik the Cook says 'We've been having some real trouble with our food provisions. Those [eerie cats] have been raiding my meat supplies every night. And if that wasn't bad enough, the whole camp is swarming with [vermin] - some of which look as though they may be diseased! I ask you, how's a Halfling to cook in these conditions?!'\nYou say, 'What vermin?'\nKallik the Cook says 'Don't tell the troops', he glances around conspiratorially, 'but I've been feeding them oashim-meat for a while now. After the cats ate all our meat, I had to resort to those oashim, but I only catch the fresh, healthy-looking ones. Could you get rid of the others for me?'\nYou have been assigned the task 'Rat-a-chewy'.\nKallik can't use infected or diseased rat in his stews. Go kill some of the dirty oashim that threaten to infect his 'fresh meat' supply.\n\n---\n\nKill 12 dirty oashim 0/12 (Valley of Lunanyn)\nReport back to Kallik with your success 0/1 (Valley of Lunanyn)\nYou say, 'Hail, Kallik the Cook'\nKallik the Cook says, 'Great! Now I won't have to worry about those filthy vermin infecting my fresh meat supply. Oh! There's a plump one.' He picks up his cleaver, eyeing a young oashim nearby, 'Here, mousey, mousey'. The oashim, sensing danger, skitters away, foiling Kallik's apparent dinner plans, 'Rats! Looks like it'll be porridge again tonight.\n_Rewards:_\n106 platinum\nExperience\n- Eltarki's Diary - Life and Death [item=98146]",
    },
    {
      id = "5401",
      title = "Who You Gonna Call?",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Hallay",
      loc = { y = 1725.0, x = -1150.0, z = -45.0 },
      triggers = {
        "Hail, Hallay",
        "Busy with what?",
        "I can defeat for you",
        "busy",
        "defeat",
      },
      items_required = {
      },
      rewards = {
        { id = 98146, name = "Eltarki's Diary - Life and Death", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Valley of Lunanyn [zone=807]\n**Who:**\n- Hallay [npc=38149]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 90\n**Maximum Level:** | 95\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n**Related Creatures:**\n- a wraith of Arelis [npc=38363]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 15 17:41:46 2011\nModified: Sat Feb 8 15:50:13 2020 | | **Veil of Alaris Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This solo kill task begins with Hallay in the Valley of Lunanyn, located at 1725, -1150, -45 (in the Rallosian camp in the northeastern part of the larger section of the zone)._\nYou say, 'Hail, Hallay'\nHallay says 'Grrr!' She snarls like an animal, 'What do yeh want, ye pesky Halfling? Can`na yeh see I'm [busy] thinkin'?'\nYou say, 'Busy with what?'\nHallay says 'I know we're low on supplies, but I can'na go out to collect more provisions with those wretched wraiths ou' there.' She seems to be more irritated by them than afraid, 'I'd like ta slaughter the lot o' 'em, but meh cleaver just goes clean through 'em! There must be some way fer me to [defeat] those blasted things.'\nYou say, 'I can defeat for you'\nHallay says 'Yeh think yeh can defeat them, do ye?' She seems to have taken your offer of assistance as a challenge, instead, 'If yer are so eager fer death then, be my guest!'\nYou have been assigned the task 'Who You Gonna Call?'.\nHallay has challenged you to vanquish the wraiths which haunt the valley.\n\n---\n\nKill 12 wraiths of Arelis 0/12 (Valley of Lunanyn)\nReturn to Hallay and tell ali of your triumph 0/1 (Valley of Lunanyn)\nYou say, 'Hail, Hallay'\nHallay seems momentarily stunned, and then begins to beam approvingly, 'Survived, have yeh? I had mistaken yeh fer a weakling, but it seems ye do have some fire in yer blood, after all. Well done!'\n_Rewards:_\nExperience\n106 platinum\n- Eltarki's Diary - Life and Death [item=98146]",
    },
    {
      id = "5419",
      title = "Lunanyn \\#3: Uncharted Territory",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Captain Gre Metkal",
      loc = { y = -800.0, x = 1000.0, z = 0.0 },
      triggers = {
        "Hail, Captain Gre Metkal",
        "I",
        "willing",
        "Find",
      },
      items_required = {
      },
      rewards = {
        { id = 100224, name = "Prophet Order IX", type = "item" },
        { id = 99811, name = "Prophet Order VI", type = "item" },
        { id = 100242, name = "Prophet Order XII", type = "item" },
        { id = 98146, name = "Life and Death\n160 platinum\nExperience\n- Eltarki's Diary - Life and Death", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Valley of Lunanyn [zone=807]\n**Who:**\n- Captain Gre Metkal [npc=38148]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 90\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Success Lockout Timer**: 06:00:00\n**Quest Items:**\n- Prophet Order IX [item=100224]\n- Prophet Order VI [item=99811]\n- Prophet Order XII [item=100242]\n**Related Creatures:**\n- Scout IX [npc=38274]\n- Scout IX Leader [npc=38269]\n- Scout VI [npc=38273]\n- Scout VI Leader [npc=38270]\n- Scout XII [npc=38272]\n- Scout XII Leader [npc=38271]\n**Related Quests:**\n- Lunanyn #1: Raid and Recover [quest=5395]\n- Lunanyn #2: The Assassination Game [quest=5418]\n- Lunanyn #4: The Enemy of My Enemy [quest=5420]\n- Lunanyn #5: The Memory Remains [quest=5421]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 16 02:38:08 2011\nModified: Tue Dec 5 05:21:04 2023 | | **Veil of Alaris Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This task is the third in a series of five; a solo task that begins with Captain Gre Metkal in the Valley of Lunanyn (Rallosian camp in northeastern part of the lower section of the zone)._\n_Pre-requisites for requesting the task:_\n\\- Completion of \"Raid and Recover\"\n\\- Completion of \"The Assassination Game\"\n\\- (no minimum required skill level in Alaran Language)\nYou say, 'Hail, Captain Gre Metkal'\nCaptain Gre Metkal says 'You must be the one who helped Geirdan. I can use someone who can take care of business. If you are [willing] to get your hands dirty, that is.'\nYou say, 'I'm willing...'\nCaptain Gre Metkal says 'Good to hear! I seem to be missing some scouts. I dispatched a small scouting party to keep an eye on the Erillian camp. But it has been many days since we have heard from them. They were ordered to set up in a location where they could easily see the camp, but not too close to be discovered. [Find] their camp and find out why we have not heard from them.'\nYou say, 'I'll find them...'\nCaptain Gre Metkal says 'Excellent! Be careful out there. This land holds many dangers.'\nYou have been assigned the task 'Uncharted Territory'.\nCaptain Gre Metkal is struggling to continue to fight. Once his army controls the valley, they will be able to move troops more freely into the other areas of Alaris. He has asked you to find the scouts with whom he has lost contact. Only when their whereabouts are known, will he be able to concentrate on doing something about the patrolling Erillion army nearby.\n\n---\n\nFind the Rallosian scout camp 0/1 (Valley of Lunanyn)\n_The camp is found in the southern end of the zone near location -800, 1000._\nSpeak with Captain Gre Metkal 0/1 (Valley of Lunanyn)\n_Task Window Says:_ It appears that the camp has been deserted with signs of a struggle and no survivors. Captain Metkal will be disappointed to hear that his scouts have been killed.\nYou say, 'Hail, Captain Gre Metkal'\nCaptain Gre Metkal says 'The Erillion commanders must have sent scouts of their own to slaughter my troops! You must find those who are responsible and exact deadly revenge. Not only will it hamper their own scouting, it will be payback for what they have done!'\nLoot 1 Prophet Order VI 0/1 (Valley of Lunanyn)\nLoot 1 Prophet Order XII 0/1 (Valley of Lunanyn)\nLoot 1 Prophet Order IX 0/1 (Valley of Lunanyn)\n_Task Window Says:_ The Erillion scouts who have killed Metkal's troops must be dealt with! Collect orders as proof of their demise.\n_The scouts spawn in the central area of the zone. They're not KOS. They come in groups of three (one leader; two scouts). They can be split. Each drops one Prophet Order (so, if you have a full group of six, you'll need to kill each set twice)._\n_NOTE: These items are NOT pre-lootable._\nDeliver 1 Prophet Order VI to Captain Gre Metkal 0/1 (Valley of Lunanyn)\nDeliver 1 Prophet Order XII to Captain Gre Metkal 0/1 (Valley of Lunanyn)\nDeliver 1 Prophet Order IX to Captain Gre Metkal 0/1 (Valley of Lunanyn)\nSpeak to Captain Gre Metkal 0/1 (Valley of Lunanyn)\nYou say, 'Hail, Captain Gre Metkal'\nCaptain Gre Metkal says 'More trophies for Zek! Thank you for your efforts.'\nYou have found the location of the scout's camp, and have dispatched those believed to be responsible.\n_Rewards:_\nEltarki's Diary - Life and Death\n160 platinum\nExperience\n- Eltarki's Diary - Life and Death [item=98146]",
    },
    {
      id = "5420",
      title = "Lunanyn \\#4: The Enemy of My Enemy",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Captain Gre Metkal",
      loc = nil,
      triggers = {
        "Hail, Captain Gre Metkal",
        "Subterfuge?",
        "Redirected?",
        "I",
        "Hail, Pika",
        "I don",
        "You can do a lot for the captain...",
        "subterfuge",
      },
      items_required = {
      },
      rewards = {
        { id = 100735, name = "Forged Orders", type = "item" },
        { id = 99810, name = "Orders of the Prophet", type = "item" },
        { id = 100000, name = "Poison of the Huntsman", type = "item" },
        { id = 98146, name = "Life and Death\n213 platinum\nExperience\n- Eltarki's Diary - Life and Death", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Valley of Lunanyn [zone=807]\n**Who:**\n- Captain Gre Metkal [npc=38148]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 90\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n**Success Lockout Timer**: 06:00:00\n**Quest Items:**\n- Forged Orders [item=100735]\n- Orders of the Prophet [item=99810]\n- Poison of the Huntsman [item=100000]\n**Related Creatures:**\n- Aedros [npc=38155]\n- Pika [npc=38267]\n- a deadly huntsman [npc=38278]\n- a trooper [npc=38157]\n**Related Quests:**\n- Lunanyn #1: Raid and Recover [quest=5395]\n- Lunanyn #2: The Assassination Game [quest=5418]\n- Lunanyn #3: Uncharted Territory [quest=5419]\n- Lunanyn #5: The Memory Remains [quest=5421]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 16 02:38:51 2011\nModified: Tue Dec 5 05:21:04 2023 | | **Veil of Alaris Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This task is the fourth in a series of five; a solo task that begins with Captain Gre Metkal in the Valley of Lunanyn (Rallosian camp in northeastern part of the lower section of the zone)._\n_Pre-requisites for requesting the task:_\n\\- Completion of \"Raid and Recover\"\n\\- Completion of \"The Assassination Game\"\n\\- Completion of \"Uncharted Territory\"\n\\- (no minimum required skill level in Alaran Language)\nYou say, 'Hail, Captain Gre Metkal'\nCaptain Gre Metkal says 'I have an idea. It will require a bit of [subterfuge] on your part, but should you be successful, it will help in removing the wraiths of Arelis village as another participant in the upcoming battles.'\nYou say, 'Subterfuge?'\nCaptain Gre Metkal says 'The wraiths seem to blame us for the destruction of their village. It seems to me that if their anger can be [redirected] to the Prophet army it will remove one obstacle from our efforts in controlling the valley.'\nYou say, 'Redirected?'\nCaptain Gre Metkal says 'Tell them whatever you like. I care little. You just need to get it done. Is this something that you can handle, or should I seek someone more [capable] to help Rallos?'\nYou say, 'I'm capable'\nCaptain Gre Metkal says 'Excellent! I will see to it that you rewarded should your efforts prove successful!'\nYou have been assigned the task 'The Enemy of My Enemy'.\nCaptain Gre Metkal believes it is important to get the wraiths of Arelis Village on his side of this war. Even if the wraiths do nothing more than agree to not attack the Rallosian army, it will be one less thing he will need to worry about.\nThe wraith Aedros is the leader of the former inhabitants of Arelis Village.\n\n---\n\nSpeak with Aedros 0/1 (Valley of Lunanyn)\n_Aedros spawns in the undead camp in the east-central part of the zone (about -155, -515)._\nKill troopers while searching for evidence 0/5 (Valley of Lunanyn)\n_Task Window Says:_ You need proof that the Prophet's army is responsible for the destruction of the village. It is possible that Erillion troopers may have evidence on them.\n_Kill five more troopers in the southern camp or in the farm area to the north._\nSpeak with Captain Gre Metkal 0/1 (Valley of Lunanyn)\n_Task Window Says:_ You have found nothing to tie the Prophet's army to the destruction of Arelis village. Captain Gre Metkal may know what to do next.\nYou say, 'Hail, Captain Gre Metkal'\nCaptain Gre Metkal says 'So, it wants proof? It will have its proof! Go to the foothill in the south and find Pika. He is a recluse that I have had dealings with early on. He will help you.'\nSpeak with Pika 0/1 (Valley of Lunanyn)\n_Task Window Says:_ According to Captain Metkal, the recluse, Pika, may be able to help. He loves to hide near the caves to the south.\n_Pika spawns above the cave in the southwestern part of the zone (-1100, 1300)._\nYou say, 'Hail, Pika'\nPika says 'You Norrathians always come to Pika! Not know what is... worse, you or them Prophet army thugs! What do you... [want]?'\nYou say, 'I don't want anything; Gre Metkal sent me!'\nPika says 'The Captain sent you?! Of course! Come now... What can Pika do for the [Captain]?'\nYou say, 'You can do a lot for the captain...'\nPika says 'That is all? Pika can do... um... easy! You need to find Pika some official order of the Prophet. Pika not know where to get, you just get. Bring that to me and Pika can... begin!'\nLoot the Orders of the Prophet from an Erillion soldier 0/1 (Valley of Lunanyn)\n_These drop from the same mobs in the trooper camp._\nDeliver the Orders of the Prophet to Pika 0/1 (Valley of Lunanyn)\nPika says 'This will do just fine. Now Pika will need you to get the poison from a huntsman. But it must be a mature huntsman! Not from those baby ones!'\nLoot a Poison of the Huntsman 0/1 (Valley of Lunanyn)\n_These drop from higher level huntsman spiders in the zone (Level 95+)._\nDeliver the poison to Pika 0/1 (Valley of Lunanyn)\n_Task Window Says:_ Great care must be taken when handling the highly corrosive poison that is sometimes used to make etchings in skin and parchment.\nPika says 'Very good! Pika needs just a... moment. Here are the orders the Captain needs. Tell the Captain that Pika help any time!'\nTake the Forged Orders to Aedros 0/1 (Valley of Lunanyn)\n_Task Window Says:_ These new orders from Pika should be enough to convince Aedros that the Prophet's army was involved in the destruction of Arelis village.\nSpeak with Captain Gre Metkal 0/1 (Valley of Lunanyn)\n_Task Window Says:_ Captain Gre Metkal will want to know the outcome of his ruse.\nYou say, 'Hail, Captain Gre Metkal'\nCaptain Gre Metkal says 'You have done well. I have to say that I am more than a little surprised that it worked. Thank you for your help. '\n_Rewards:_\nEltarki's Diary - Life and Death\n213 platinum\nExperience\n- Eltarki's Diary - Life and Death [item=98146]",
    },
    {
      id = "5421",
      title = "Lunanyn \\#5: The Memory Remains",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Aedros",
      loc = nil,
      triggers = {
        "Hail, Aedros",
        "I",
        "Hail, Taleg",
        "Hail, The Daevan",
        "Daevan",
        "convince",
        "mythical creature",
      },
      items_required = {
      },
      rewards = {
        { id = 98146, name = "Life and Death\n160 platinum\nExperience\n- Eltarki's Diary - Life and Death", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Valley of Lunanyn [zone=807]\n**Who:**\n- Aedros [npc=38155]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 90\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Success Lockout Timer**: 06:00:00\n**Related Creatures:**\n- Taleg [npc=38268]\n- The Daevan [npc=38289]\n- a foul reega [npc=38291]\n- a nefarious reega [npc=38292]\n- a vile reega [npc=38290]\n**Related Quests:**\n- Into the Abyss [quest=5423]\n- Lunanyn #1: Raid and Recover [quest=5395]\n- Lunanyn #2: The Assassination Game [quest=5418]\n- Lunanyn #3: Uncharted Territory [quest=5419]\n- Lunanyn #4: The Enemy of My Enemy [quest=5420]\n- The Herald of Oratory [quest=5424]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 16 02:39:27 2011\nModified: Tue Dec 5 05:21:04 2023 | | **Veil of Alaris Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This task is the fifth in the series of five; a solo task that begins with Aedros in the Valley of Lunanyn (-160, -530 -- central part of the zone's lower half)._\n_Pre-requisites for requesting the task:_\n\\- Completion of \"Raid and Recover\"\n\\- Completion of \"The Assassination Game\"\n\\- Completion of \"Uncharted Territory\"\n\\- Completion of \"The Enemy of My Enemy\"\n\\- (no minimum required skill level in Alaran Language)\nYou say, 'Hail, Aedros'\nAedros says, in Alaran, 'It appears our new agreement may have hit a snag. Taleg, another wraith here in the village is not happy with my agreement to assist you and the armies of Zek. Taleg believes the armies of Zek are responsible for destroying our village. I happen to know it was The [Daevan]. Perhaps you could [convince] Taleg otherwise?'\nYou say, 'I'll convince him'\nAedros says, in Alaran, 'Taleg should be nearby.'\nYou have been assigned the task 'The Memory Remains'.\nTaleg is not happy that Aedros has agreed to side with the forces from Norrath. In fact, Taleg blames the Norrathians for destroying alir village. Aedros has asked you to speak with Taleg and see if you can convince ali of the truth that it was The Daevan that destroyed the village and not the Norrathians.\n\n---\n\nSpeak with Taleg 0/1 (Valley of Lunanyn)\n_Taleg is found a little ways northwest of Aedros._\nYou say, 'Hail, Taleg'\nTaleg says, in Alaran, 'I do not believe Aedros' claim that our village was destroyed by some [mythical creature]. Aedros is a fool to trust you and all the armies of Zek.'\nKill the Reega in The Abyss 0/8 (Valley of Lunanyn)\n_Task Window Says:_ Enter the tunnels known as The Abyss and destroy the Reega that stand in your way.\n_You'll find reega in throughout the eastern tunnel system. These are among the higher level trash mobs in the zone, reaching up to Level 95 and hitting for ~10,000._\nSpeak with The Daevan 0/1 (Valley of Lunanyn)\n_In one of the central dead ends in the tunnel system, you'll find a Nekhon called The Daevan. Four mobs spawn in its room and should be cleared out before you hail it._\nYou say, 'Hail, The Daevan'\nThe Daevan says, in Alaran, 'I normally have to send my reega to collect victims. How nice of my food to come to me for a change!'\nThe Daevan says, in Alaran, 'I will enjoy the music of your screams as you die in agony!'\n_The Daevan attacks. It hits for a max ~11,500._\nFight The Daevan 0/1 (Valley of Lunanyn)\nThe Daevan says, in Alaran, 'You have no hope of defeating me in this place of existence. Go. Go and tell others of the coming wrath I will spread across this pitiful, battle-torn land.'\nSpeak with Taleg 0/1 (Valley of Lunanyn)\nYou say, 'Hail, Taleg'\nTaleg says, in Alaran, 'Just as I thought. You return with no proof. I grow tired of you. Now you die!'\nDefeat Taleg 0/1 (Valley of Lunanyn)\n_Taleg hits for a max ~11,000. Note that the wraiths around him will assist him._\nSpeak with Aedros 0/1 (Valley of Lunanyn)\nYou say, 'Hail, Aedros'\nAedros says, in Alaran, 'It is unfortunate that Taleg had to be killed. It does effectively end the uprising against me however. I also hear that you confronted The Daeven. I am afraid your encounter with him may not be your last.'\n_Rewards:_\nEltarki's Diary - Life and Death\n160 platinum\nExperience\n- Eltarki's Diary - Life and Death [item=98146]",
    },
    {
      id = "5422",
      title = "Filthy Oashim",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Grave Digger Undros",
      loc = nil,
      triggers = {
        "Hail, Grave Digger Undros",
        "Of course I",
        "Give me some more!",
        "_Quest_",
        "help",
        "give",
      },
      items_required = {
        { name = "me some more!'", count = 1 },
      },
      rewards = {
        { id = 98638, name = "Oashim Poison", type = "item" },
        { id = 98146, name = "Life and Death\n- Eltarki's Diary - Life and Death", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Valley of Lunanyn [zone=807]\n**Who:**\n- Grave Digger Undros [ _Quest_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 90\n**Maximum Level:** | 95\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n**Success Lockout Timer**: 06:00:00\n**Quest Items:**\n- Oashim Poison [item=98638]\n**Related Creatures:**\n- a baby oashim [npc=39123]\n- a mutated oashim [npc=39122]\n- an oashim breeder [npc=38265]\n- an oashim nest [npc=38266]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 16 02:40:33 2011\nModified: Thu Apr 30 07:34:56 2026 | | **Veil of Alaris Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This solo task begins with Grave Digger Undros in the Valley of Lunanyn at about 1400, -415, -45 (south of the small canyon that leads out from the upper section of the zone)._\n_Pre-requisites for requesting the task:_\n\\- No tasks\n\\- (no minimum required skill level in Alaran Language)\n\n---\n\nYou say, 'Hail, Grave Digger Undros'\nGrave Digger Undros says, in Alaran, 'Those filthy oashim! Here I am trying to give decent burials for those that have fallen in combat, and the oashim tear the bodies to shreds before I can do anything! They are making quite a mess. Do you think you could [help] me out?'\nYou say, 'Of course I'll help!'\nGrave Digger Undros says, in Alaran, 'See if you can find any of the oashim nests and destroy them! I know this won't solve the problem completely, but hopefully it will cut their numbers down a bit.'\nYou have been assigned the task 'Filthy Oashim!'.\nGrave Digger Undros is just trying to give a proper burial to those who have fallen in battle. The oashim however are making it difficult as they enjoy feeding on corpses, and ripping them to shreds causing a huge mess.\nFind some oashim nests and destroy them. Kill the baby oashim that emerge from the destroyed nests.\n\n---\n\nDestroy the oashim nests and kill the baby oashim that were hiding within 0/12 (Valley of Lunanyn)\n_Nests are found in the caves along the western boundary of the zone, inside a cave at /way -1091, 1284 (you can find Pika standing on the roof of the cave). Upon destroying a nest, several baby oashims pop out. These are simple kills._\nSpeak with Grave Digger Undros 0/1 (Valley of Lunanyn)\nYou say, 'Hail, Grave Digger Undros'\nGrave Digger Undros says, in Alaran, 'Good job taking those nests out. Some of the local farmers gave me this vial. They say it will kill the oashim. I haven't been able to test it though. Why don't you try it out on one of the oashim breeders? They are far too bloated with babies to attack, so this should be pretty easy. If you lose your poison, let me know and I can [give] you some more.'\nYou say, 'Give me some more!'\nGrave Digger Undros says, in Alaran, 'Try not to lose it again.'\nGive the oashim poison to an oashim breeder 0/1 (Valley of Lunanyn)\n_Breeders are found in the backs of the caves on the western boundary of the zone and one by the Rallosian camp. Upon hand-in, the oashim attacks, hitting for a max ~11,000._\nan oashim breeder does not react to the poison as you thought it would!\na mutated oashim is completely silent as it attacks.\nDefeat the mutant oashim 0/1 (Valley of Lunanyn)\n_Task Window Says:_ The poison didn't work. It did however mutate the oashim and it looks angry! Defeat it!\na mutated oashim has been slain by \\_\\_\\_\\_\\_!\na mutated oashim's corpse squeals in panic as the life leaves its body.\nSpeak with Grave Digger Undros 0/1 (Valley of Lunanyn)\nYou say, 'Hail, Grave Digger Undros'\nGrave Digger Undros says, in Alaran, 'So the poison didn't quite have the effect we were hoping for, huh? Sorry about that. Thanks for helping me out though. Take this for your efforts. The previous owner won't be needing it anymore.'\n_Rewards:_\n213 platinum\nExperience\nEltarki's Diary - Life and Death\n- Eltarki's Diary - Life and Death [item=98146]",
    },
    {
      id = "5424",
      title = "The Herald of Oratory",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Zarbak",
      loc = nil,
      triggers = {
        "Hail, Zarbak",
        "The army?",
        "What battle?",
        "He seeks what?",
        "An island?",
        "A few",
        "We",
        "Defenses?",
      },
      items_required = {
      },
      rewards = {
        { id = 100327, name = "Marks of the Gods", type = "item" },
        { id = 100359, name = "Sol Ro Ash Breather", type = "item" },
        { id = 100353, name = "Sol Ro Dark Smoker", type = "item" },
        { id = 100325, name = "Sol Ro Fire Lord", type = "item" },
        { id = 100498, name = "Sol Ro Soother", type = "item" },
        { id = 100354, name = "Zek Archer", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Valley of Lunanyn [zone=807]\n**Who:**\n- Zarbak [npc=38158]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 90\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Loot\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 06:00:00\n**Quest Items:**\n- Marks of the Gods [item=100327]\n- Sol Ro Ash Breather [item=100359]\n- Sol Ro Dark Smoker [item=100353]\n- Sol Ro Fire Lord [item=100325]\n- Sol Ro Soother [item=100498]\n- Zek Archer [item=100354]\n- Zek Bruiser [item=100326]\n- Zek Soldier [item=100894]\n**Related Zones:**\n- Valley of Lunanyn: The Herald of Oratory [zone=821]\n**Related Creatures:**\n- Herald of Oratory [npc=38321]\n- Quartermaster Gelblat [npc=38306]\n- Rallos Zek [npc=38305]\n- Solusek Ro [npc=38304]\n- Zarbak [npc=38307]\n- a Ro ash breather [npc=38314]\n- a Ro dark smoker [npc=38311]\n- a Ro fire lord [npc=38310]\n- a Ro soother [npc=38313]\n- a Windsong archer [npc=38320]\n- a Zek archer [npc=38309]\n- a Zek bruiser [npc=38308]\n- a Zek soldier [npc=38312]\n- a caster chest [npc=38327]\n- a footsoldier chest [npc=38322]\n- a juggernaut chest [npc=38326]\n- a splineguide [npc=45489]\n- an Archon chest [npc=38323]\n- an Erillian Archon [npc=38317]\n- an Erillian Caster [npc=38318]\n- an Erillian Exploder [npc=38319]\n- an Erillian footsoldier [npc=38315]\n- an Erillian juggernaut [npc=38316]\n- an archer chest [npc=38324]\n- an infiltrator chest [npc=38325]\n- an ornate chest - The Herald of Oratory [npc=38329]\n- chest of the gods [npc=38303]\n**Related Quests:**\n- Into the Abyss [quest=5423]\n- Lunanyn #1: Raid and Recover [quest=5395]\n- Lunanyn #2: The Assassination Game [quest=5418]\n- Lunanyn #3: Uncharted Territory [quest=5419]\n- Lunanyn #4: The Enemy of My Enemy [quest=5420]\n- Lunanyn #5: The Memory Remains [quest=5421]\n- Raid Expedition: The Herald of Oratory [quest=5479]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 16 20:00:20 2011\nModified: Sat Dec 9 22:19:32 2023 | | **Veil of Alaris Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n**NOTE: This is the quest entry for the group version of \"The Herald of Oratory\". See this quest entry [quest=5479] for the raid version.**\n\n---\n\n_This group mission begins with Zarbak in the Valley of Lunanyn, located in the vicinty of 1725, -1150, -45 (in the Rallosian camp in the northeastern part of the larger section of the zone)._\n_Pre-requisites for requesting the task:_\n\\- Completion of \"Raid and Recover\"\n\\- Completion of \"The Assassination Game\"\n\\- Completion of \"Uncharted Territory\"\n\\- Completion of \"The Enemy of My Enemy\"\n\\- Completion of \"The Memory Remains\"\n\\- Completion of \"Into the Abyss\"\n\\- Minimum Skill Level in Alaran Language: 10\nYou say, 'Hail, Zarbak'\nZarbak says 'You, \\_\\_\\_\\_\\_! Let Zarbak feels the meats of your head! Yes, yes, good and thick! Perfect for knowings of the bashings and smashings! In the [army] of Zek you want to fight? Are you ready to [go]?'\nYou say, 'The army?'\nZarbak says 'Army of Zek is strong! With goblins and ogres, Zarbak says no need for weakling races. But Vallon says great [battle] is coming, need to fill valley with walls of sword and shield. So, you now in army of Zek!'\nYou say, 'What battle?'\nZarbak says 'Rumblings low shiver air on southern horizon. Mirage of sound lingers over enemy camp and hides goings and doings. Powerful voice bellows in strange tongue. Even Rallos concerned. Zarbak sees Rallos talking with Sol Ro, alliances forming, armies meeting as one. Zarbak thinks Rallos finds what he [seeks].'\nYou say, 'He seeks what?'\nZarbak says 'You have not much knowings as I thought! All gods have had much talking. Cazic is dead, his plane empty! Where fled his essence? An [island] appears, and Rallos says Zarbak and army must go.'\nYou say, 'An island?'\nZarbak says 'Now search we do, resting not until Rallos satisfied. No army thwarts us, not with big thick heads like you to think for our front lines! Do you bring with you [many] companions, or but a [few]?'\nYou say, 'A few'\nZarbak says 'Much can be accomplished with little. [Go] and achieve victory!'\nYou have been assigned the task 'The Herald of Oratory'.\nYou say, 'We're ready to go'\nLOADING, PLEASE WAIT...\nYou have entered Valley of War.\nThe forces of Erillion march across Arelis Valley to defeat the armies of Rallos Zek and Solusek Ro. Command the soldiers of the Norrathian gods to stop Erillion's advance.\nPrevent the army of Erillion from reaching Solusek Ro and Rallos Zek. Defeat the Herald of Oratory.\n\n---\n\nDefend Rallos Zek and Solusek Ro from the forces of Erillion and kill the Herald of Oratory 0/1 (Valley of Lunanyn)\nClaim your reward from the chest the gods have given you 0/1 (Valley of Lunanyn)\n\n---\n\n_Buy soldiers from the Quartermaster, position both offensive and defensive soldiers around the gods and use offensive soldiers in the valley below in preparation for the named._\n_NOTE: The invaders and the named (to begin with) aren't killable by players. You have to use the soldiers, which will kill mobs as they wander through._\n_All mobs have a damage aura up which will do about 15k damage per tick as long as you're in range._\n_The Herald of Oratory has the same damage aura as well as a shield that prevents damage from being done to her._\n_In order to destroy the shield and make her killable, you have to position numerous soldiers around her. Once you get the emote saying her shield has been destroyed, you can attack and kill her by normal means. Note that even once she's live, the invading forces continue to attack the gods, so you'll have to keep them defended as well._\n\n---\n\n_Zarbak gives you details about how the task works:_\nYou say, 'Hail, Zarbak'\nZarbak says 'These streaks of light do you see? Rallos Zek and Solusek Ro light the paths of the enemy as they march from the south! If the gods stay concentrated, Zarbak thinks we can know where to place [defenses]!'\nYou say, 'Defenses?'\nZarbak says 'A thick, strong head have you, not like Zarbak! You must tell army where to defend. Keep enemy from reaching gods and distracting them. I will tell you [how].'\nYou say, 'How?'\nZarbak says 'Zek army don't trust outsider like you. They won't take orders unless you pay them. I put moneys in this chest. Take it and talk to quartermaster. He assigns you [troops] for moneys.'\nYou say, 'What about the troops?'\nZarbak says 'Stand where you want troops to stand, and call the ones you hired. They will hold strong at that spot. If they die, [pay] for more. [Fend off] the enemies, and kill the Herald of Oratory!'\nYou say, 'Pay for more?'\nZarbak says 'Rotten thieving enemies sneaked in camp at night and stole our moneys! Kill them and retrieve it! Pleased would be the quartermaster!'\nYou say, 'We'll fend off the enemies'\nZarbak says 'Speak with the quartermaster, and place your defenses. Once you do this, tell me you are ready to [begin]. If you believe you failed your task, you should [try again]. Don't even think to [leave] like a coward!'\n_Quartermaster Gelblat stands nearby:_\nYou say, 'Hail, Quartermaster Gelblat'\nQuartermaster Gelblat says 'How can I aid you in your defense?'\nQuartermaster Gelblat says '[1] Zek soldier ..... 2 Marks of the Gods'\nQuartermaster Gelblat says '[2] Zek archer ..... 4 Marks of the Gods'\nQuartermaster Gelblat says '[3] Sol Ro fire lord ..... 6 Marks of the Gods'\nQuartermaster Gelblat says '[4] Sol Ro dark smoker ..... 8 Marks of the Gods'\nQuartermaster Gelblat says '[5] Zek bruiser ..... 7 Marks of the Gods'\nQuartermaster Gelblat says '[6] Sol Ro soother ..... 1 Marks of the Gods'\nQuartermaster Gelblat says '[7] Sol Ro ash breather ..... 9 Marks of the Gods'\nQuartermaster Gelblat says 'Would you like [details]?'\nYou say, 'I'd like details'\nQuartermaster Gelblat says '[1] a Zek soldier: HP - Medium. Damage - Low. Attack Speed - Medium. Range - Medium.'\nQuartermaster Gelblat says '[2] a Zek archer: HP - Low. Damage - Very Low. Attack Speed - High. Range - Very High.'\nQuartermaster Gelblat says '[3] a Sol Ro fire lord: HP - Medium. Damage - High. Attack Speed - Low. Range - High.'\nQuartermaster Gelblat says '[4] a Sol Ro dark smoker: HP - Medium. Damage - Medium. Attack Speed - High. Range - Medium.'\nQuartermaster Gelblat says '[5] a Zek bruiser: HP - High. Damage - Very High. Attack Speed - Low. Range - Medium.'\nQuartermaster Gelblat says '[6] a Sol Ro soother: HP - Very Low. Healing - Medium. Healing Speed - High. Range - Very Low.'\nQuartermaster Gelblat says '[7] a Sol Ro ash breather: HP - Low. Slowing - Low. Slowing Speed - Very Low. Range - Very Low.'\n_A chest called \"chest of the gods\" is found by the zone-in and contains numerous \"Marks of the Gods\". You can use the marks to purchase soldiers from the Quartermaster. Simply say the number of the soldier type you'd like to use:_\nYou say, '7'\nQuartermaster Gelblat says 'You have chosen well!'\n_You receive an item which you can right-click to summon that soldier type. The soldier will be permanently rooted in place and will defend its position according to the type as listed above._\n_You'll want to have several soldiers positioned around the two gods, as well as several attack soldiers positioned in the valley below, as this is where the Herald will position herself._\n_Place the soldiers as you wish and then say \"begin\" to Zarbak to initiate the event:_\nYou say, 'We're ready to begin'\nZarbak shouts 'Everyone to their positions! The enemy will be upon us quickly!'\nLower your weapons and surrender! You will be taken under control of Erillion, unharmed!\nRallos Zek says 'Mortals, you must destroy the Herald! It commands these hordes. If you kill it, its army will retreat.'\nSolusek Ro says 'Position our troops around the Herald. With concentrated effort, the troops can destroy the Herald's shield and render it vulnerable.'\nThe full power of Erillion will bear down upon those who threaten to sunder our unification!\n_As Erillion forces reach the gods, you'll see emotes like this:_\nan Erillian footsoldier reaches the gods and drops their concentration to 190 of 200.\n_If it reaches zero from 200, the task resets:_\nYou have failed to defend Rallos Zek and Solusek Ro.\n_As the army forces kill off Erillion invaders, you'll see emotes like this:_\nYou have defeated 10 enemy units.\n_Any time a soldier kills a member of the Erillion invaders, a chest spawns in its place. Loot the chest for more Marks and use those to buy and place additional soldiers._\n_Soon after the event has been started, the Herald of Oratory makes her way into the valley and positions herself in about the center area. Once she's positioned, you'll see this emote:_\nYou interfere with an internal matter. What happens in our land concerns you not.\n_Once the soldiers have done enough collective damage to her, her shield will be destroyed:_\nHerald of Oratory's shield has been destroyed.\n_At this point, you can move in and kill her. She has about 5 million hitpoints, so if you don't have the DPS to kill it fast enough, you'll need to make sure the gods remain defended as invaders continue to attack them._\nHerald of Oratory has been slain by \\_\\_\\_\\_\\_!\nHerald of Oratory shouts 'My body's demise is not the end. The Orator shall decimate every one of you!'\n_Open the chest to complete the task:_\nYou have driven back Erillion's forces and defeated the Herald of Oratory.\nYou say, 'Hail, Zarbak'\nZarbak says 'Powerful was that [Herald]! What great strength must lie on this continent! Fear swells in Zarbak! We should [leave] from here and return to safer lands!'\nYou say, 'What about that herald?'\nZarbak says 'Zarbak hears the name of the Orator whispered on lips. He must be powerful that an entire valley trembles at his name!'\n_Rewards:_\n160 platinum\nEltarki's Diary - Life and Death\nPossible Chest Loot (1 Item + 1 Cantrip + 0-1 Valiant Ornament per task)\nBattlesteel Hammer\nMegaladon Tooth Fragment\nMourning Spikes\nOrnate Bloodstained Leather Mask\nPerak's Charm\nSharris' Weapon Belt\nShield of Grievance\nSickle of Urash\nSpiral Spear\nTear-Drenched Pauldron\nMinor Alaran Cantrip\nLesser Alaran Cantrip\nMedian Alaran Cantrip\n- Eltarki's Diary - Life and Death [item=98146]\n- Median Alaran Cantrip [item=98717]\n- Valiant Plate Feet Ornament [item=111847]",
    },
  },
}
