-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Cabilis East (cabeast)
-- Total Quests: 13
-- ============================================================================

return {
  zone = "cabeast",
  zone_name = "Cabilis East",
  quests = {
    {
      id = "3050",
      title = "Iksar Cultural Armor (DoN)",
      exp = "09",
      exp_name = "Dragons of Norrath",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Artisan Sieeva Koan",
      loc = { y = 851.0, x = -439.0, z = 0.0 },
      triggers = {
        "Hail, Sieeva Koan",
        "Glory days?",
        "What techniques?",
        "I am interested in learning the cultural armor patterns",
        "What about the cultural symbol patterns?",
        "What tasks?",
        "_Trade Skill Quests_",
        "Xinth Mixture",
      },
      items_required = {
      },
      rewards = {
        { id = 33988, name = "Ancestral Iksar Armor", type = "item" },
        { id = 34003, name = "Blessed Book of Iksar Culture", type = "item" },
        { id = 3593, name = "Bloodgill Scales", type = "item" },
        { id = 5958, name = "Bloodstone Ring", type = "item" },
        { id = 3469, name = "Cat's Eye Agate", type = "item" },
        { id = 23005, name = "Drachnid Silk", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Status: Incomplete**\n\nQuest Started By: | Description:\n**Where:**\n- Cabilis East [zone=96]\n**Who:**\n- Artisan Sieeva Koan [ _Trade Skill Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 20\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Armour Set\n- Tradeskill\n**Quest Items:**\n- Ancestral Iksar Armor [item=33988]\n- Blessed Book of Iksar Culture [item=34003]\n- Bloodgill Scales [item=3593]\n- Bloodstone Ring [item=5958]\n- Cat's Eye Agate [item=3469]\n- Drachnid Silk [item=23005]\n- Elaborate Mistwoven Swatch [item=34608]\n- Elaborate Shadowrise Swatch [item=34605]\n- Elaborate Twoscale Skyiron Bar [item=34527]\n- Eminent Book of Iksar Culture [item=34048]\n- Fractured Drake Claw [item=34052]\n- Frosty Datura [item=14765]\n- Green Goblin Skin [item=4924]\n- Huge Block of Clay [item=34078]\n- Intricate Mistwoven Swatch [item=34610]\n- Intricate Shadowrise Swatch [item=34604]\n- Intricate Twoscale Skyiron Bar [item=34526]\n- Jade Shard [item=5953]\n- Large Darkhollow Geode [item=45104]\n- Mold for Cabilisian Boots [item=34264]\n- Nodding Blue Lily [item=17533]\n- Ornate Mistwoven Swatch [item=34607]\n- Ornate Shadowrise Swatch [item=34603]\n- Ornate Twoscale Skyiron Bar [item=34525]\n- Pattern for Cabilisian Boots [item=34271]\n- Pattern for Cabilisian Gloves [item=34272]\n- Pattern for Cabilisian Helms [item=34273]\n- Pattern for Cabilisian Leggings [item=34274]\n- Pattern for Cabilisian Sleeves [item=34275]\n- Pattern for Cabilisian Tunics [item=37206]\n- Pattern for Cabilisian Wristguards [item=34277]\n- Pondfish Spine [item=3574]\n- Revered Book of Iksar Culture [item=34018]\n- Sacred Book of Iksar Culture [item=34033]\n- Scroll [Xinth Mixture]\n- Simple Mistwoven Swatch [item=34606]\n- Simple Shadowrise Swatch [item=34602]\n- Simple Twoscale Skyiron Bar [item=34524]\n- Wax Flower [item=9319]\n**Related Zones:**\n- Dreadlands [zone=75]\n- Lake of Ill Omen [zone=73]\n- Old Sebilis [zone=89]\n- Swamp of No Hope [zone=74]\n- Thundercrest Isles [zone=279]\n**Related Creatures:**\n- a Sarnak adherent [npc=3979]\n- a bloodgill goblin [npc=3960]\n- a tundra yeti [npc=4106]\n- froglok ilis shaman [npc=4579]\n- froglok krup knight [npc=4573]\n**Related Quests:**\n- Dragons of Norrath Cultural Equipment [quest=3056]\n**Era:** | !Dragons of Norrath\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- Beastlord\n- Monk\n- Necromancer\n- Shadowknight\n- Shaman\n- Warrior\n**Appropriate Races:**\n- Iksar\nEntered: Mon Feb 21 13:26:49 2005\nModified: Tue Dec 5 05:21:04 2023 | | **Click here** [quest=3056] for an overview of cultural armor introduced with Dragons of Norrath.\n_Find Sieeva Koan in East Cabilis, location +851, -439._\nYou say, 'Hail, Sieeva Koan'\nSieeva Koan says 'Hello, \\_\\_\\_\\_\\_. Returning home from conquests abroad, I hope. It fills me with pride to see there are still Iksar willing to venture out into Norrath and crusade for our empire once again. Too many of us have holed up in this city, dreaming of the [glory] days of the Iksar empire.'\nYou say, 'Glory days?'\nSieeva Koan says 'From what I have heard things were much different then, our military more refined, our craftsmanship more detailed. I have been studying the writings in the ruins of old Cabilis. They are helping me piece together the [techniques] of our ancestors.'\nYou say, 'What techniques?'\nSieeva Koan says 'From what I have learned, our craftsmanship has regressed over the years. In fact, I've uncovered some armor patterns and symbol patterns within the ruins that put our current designs to shame. Would you be interested in learning the [cultural armor patterns] and [cultural symbol patterns]? They will take time to master, but if you are patient, they will serve you well.'\nYou say, 'I am interested in learning the cultural armor patterns'\nSieeva Koan says 'Excellent. To make you a pattern book I will need a patch of bloodgill scales for the cover, a scroll for the pages, a bloodstone ring for the clasp, and a cat's eye agate to grind down and make a salve which will protect and preserve the finished product. I have heard these items can be found in the Swamp of No Hope and the Lake of Ill Omen. Bring them to me and the pattern book shall be yours.'\nYou say, 'What about the cultural symbol patterns?'\nSieeva Koan says 'You're interested in the cultural symbol patterns I see. I can give you the symbol patterns but I will need you to run a few tasks for me before I can give them to you. What do you say; would you like to run a few short [tasks] for me?'\nYou say, 'What tasks?'\nSieeva Koan says 'I have four tasks that need to be completed. The first is an adventure into [Lake of Ill Omen] where you will collect some shields for my shield collection. The next you will be tasked with venturing into the [Dreadlands] where you will confront any clans that are preventing us from doing buisness. The third task leads you into [Sebilis] where you will learn if there is any weakness in Trakanon's army. The last task will lead you onto an adventure into [Thundercrest] where you will learn about the creatures that inhabit the area.'\n**Items to return for the Ancestral Iksar Armor book:**\nBloodgill Scales (dropped by bloodgill goblins)\nA Scroll (dropped by sarnak adherants)\nBloodstone Ring (dropped by random low-to-midlevel mobs)\nCats Eye Agate (dropped and vendorbought)\n**Task given for the Journeyman's Book: Tales of Sieeva**\n1) Kill 20 Goblin Warriors in the Lake of Ill Omen\n2) Loot four Green Goblin Skins\n3) Return skins to Sieeva\n4) Kill 10 Pond Sturgeons (Firiona Vie / Lake of Ill Omen zone line)\n5) Loot one Pondfish Spine\n6) Return spine to Sieeva\n_Receive Journeyman's Book._\n**Task given for Expert's Book: Protect the Operation**\n1) Kill 50 Tundra Yeti in the Dreadlands\n2) Loot 20 Frosty Datura\n3) Return Frosty Daturas to Sieeva\n4) Kill five Dracnid silkmistresses\n5) Loot one Drachnid Silk\n6) Return Drachnid Silk to Sieeva\n_Receive Expert's Book._\n**Task given for Master's Book: Scouting the Enemy**\n1) Kill any 80 Froglok Krups in Sebilis\n2) Loot 40 Wax Flowers\n3) Return four Wax Flowers to Sieeva\n4) Kill five Froglok Ilis Shaman\n5) Loot one Nodding Blue Lilly\n6) Deliver Nodding Blue Lily to Sieeva _Receive Master's Book._\n**Task given for Grandmaster's Book:**\n1) Kill 120 Thundercrest Isle creatures (must have 'Isle' in name)\n2) Loot 80 Fractured Drake Claws\n3) Return Drake Claws to Sieeva\n4) ?\n5) ?\n6) ?\n_Receive Grandmaster's Book._\n**Types of Armor**\n_Mistwoven - Necromancer_\n_Shadowrise - Beastlord, Monk_\n_Trooper - Shadowknight, Warrior_\n_Twoscale - Shaman_\n- Elaborate Mistwoven Armband [item=38887]\n- Elaborate Mistwoven Boots [item=38886]\n- Elaborate Mistwoven Breeches [item=38885]\n- Elaborate Mistwoven Cap [item=38884]\n- Elaborate Mistwoven Gloves [item=38883]\n- Elaborate Mistwoven Robes [item=38882]\n- Elaborate Mistwoven Sleeves [item=38881]\n- Elaborate Shadowrise Armband [item=38549]\n- Elaborate Shadowrise Boots [item=38888]\n- Elaborate Shadowrise Cuirass [item=37761]\n- Elaborate Shadowrise Gloves [item=38889]\n- Elaborate Shadowrise Greaves [item=38890]\n- Elaborate Shadowrise Helm [item=38891]\n- Elaborate Shadowrise Sleeves [item=38313]\n- Elaborate Trooper Armband [item=38551]\n- Elaborate Trooper Boots [item=38557]\n- Elaborate Trooper Cuirass [item=38552]\n- Elaborate Trooper Gloves [item=38553]\n- Elaborate Trooper Greaves [item=38554]\n- Elaborate Trooper Helm [item=38555]\n- Elaborate Trooper Sleeves [item=38556]\n- Elaborate Twoscale Armband [item=38860]\n- Elaborate Twoscale Boots [item=38861]\n- Elaborate Twoscale Cuirass [item=64812]\n- Elaborate Twoscale Gloves [item=38872]\n- Elaborate Twoscale Greaves [item=38834]\n- Elaborate Twoscale Helm [item=38835]\n- Elaborate Twoscale Sleeves [item=38862]\n- Elegant Shadowrise Armband [item=71301]\n- Elegant Shadowrise Boots [item=71306]\n- Elegant Shadowrise Cuirass [item=71298]\n- Elegant Shadowrise Gloves [item=71303]\n- Elegant Shadowrise Greaves [item=71300]\n- Elegant Shadowrise Helm [item=71304]\n- Elegant Shadowrise Sleeves [item=71120]\n- Elegant Trooper Armband [item=72004]\n- Elegant Trooper Boots [item=72151]\n- Elegant Trooper Cuirass [item=71095]\n- Elegant Trooper Gloves [item=72152]\n- Elegant Trooper Greaves [item=70709]\n- Elegant Trooper Helm [item=72153]\n- Elegant Trooper Sleeves [item=72165]\n- Elegant Twoscale Armband [item=72513]\n- Elegant Twoscale Boots [item=74163]\n- Elegant Twoscale Cuirass [item=73980]\n- Elegant Twoscale Gloves [item=72585]\n- Elegant Twoscale Greaves [item=73523]\n- Elegant Twoscale Helm [item=74164]\n- Elegant Twoscale Sleeves [item=73680]\n- Intricate Mistwoven Armband [item=38320]\n- Intricate Mistwoven Boots [item=38880]\n- Intricate Mistwoven Breeches [item=38879]\n- Intricate Mistwoven Cap [item=38878]\n- Intricate Mistwoven Gloves [item=38877]\n- Intricate Mistwoven Robes [item=38876]\n- Intricate Mistwoven Sleeves [item=38875]\n- Intricate Shadowrise Armband [item=38898]\n- Intricate Shadowrise Boots [item=38897]\n- Intricate Shadowrise Cuirass [item=38896]\n- Intricate Shadowrise Gloves [item=38895]\n- Intricate Shadowrise Greaves [item=38894]\n- Intricate Shadowrise Helm [item=38893]\n- Intricate Shadowrise Sleeves [item=38892]\n- Intricate Trooper Armband [item=38913]\n- Intricate Trooper Boots [item=38912]\n- Intricate Trooper Cuirass [item=38911]\n- Intricate Trooper Gloves [item=38910]\n- Intricate Trooper Greaves [item=38909]\n- Intricate Trooper Helm [item=38908]\n- Intricate Trooper Sleeves [item=38907]\n- Intricate Twoscale Armband [item=38866]\n- Intricate Twoscale Boots [item=38867]\n- Intricate Twoscale Cuirass [item=38868]\n- Intricate Twoscale Gloves [item=38869]\n- Intricate Twoscale Greaves [item=38870]\n- Intricate Twoscale Helm [item=38873]\n- Intricate Twoscale Sleeves [item=38871]\n- Ornate Mistwoven Armband [item=38085]\n- Ornate Mistwoven Boots [item=38086]\n- Ornate Mistwoven Breeches [item=38088]\n- Ornate Mistwoven Cap [item=38089]\n- Ornate Mistwoven Gloves [item=38090]\n- Ornate Mistwoven Robes [item=38091]\n- Ornate Mistwoven Sleeves [item=38092]\n- Ornate Shadowrise Armband [item=37058]\n- Ornate Shadowrise Boots [item=37059]\n- Ornate Shadowrise Cuirass [item=37060]\n- Ornate Shadowrise Gloves [item=37061]\n- Ornate Shadowrise Greaves [item=37062]\n- Ornate Shadowrise Helm [item=37063]\n- Ornate Shadowrise Sleeves [item=37064]\n- Ornate Trooper Armband [item=38314]\n- Ornate Trooper Boots [item=38316]\n- Ornate Trooper Cuirass [item=38319]\n- Ornate Trooper Gloves [item=38899]\n- Ornate Trooper Greaves [item=38318]\n- Ornate Trooper Helm [item=38317]\n- Ornate Trooper Sleeves [item=38315]\n- Ornate Twoscale Armband [item=38854]\n- Ornate Twoscale Boots [item=37442]\n- Ornate Twoscale Cuirass [item=38855]\n- Ornate Twoscale Gloves [item=38856]\n- Ornate Twoscale Greaves [item=38857]\n- Ornate Twoscale Helm [item=38858]\n- Ornate Twoscale Sleeves [item=38859]\n- Seals of Darkhollow [item=44967]\n- Simple Mistwoven Armband [item=37072]\n- Simple Mistwoven Boots [item=37073]\n- Simple Mistwoven Breeches [item=37074]\n- Simple Mistwoven Cap [item=37075]\n- Simple Mistwoven Gloves [item=37076]\n- Simple Mistwoven Robes [item=37077]\n- Simple Mistwoven Sleeves [item=37078]\n- Simple Shadowrise Armband [item=37065]\n- Simple Shadowrise Boots [item=37066]\n- Simple Shadowrise Cuirass [item=37067]\n- Simple Shadowrise Gloves [item=37068]\n- Simple Shadowrise Greaves [item=37069]\n- Simple Shadowrise Helm [item=37070]\n- Simple Shadowrise Sleeves [item=37071]\n- Simple Trooper Armband [item=38906]\n- Simple Trooper Boots [item=38905]\n- Simple Trooper Cuirass [item=38904]\n- Simple Trooper Gloves [item=38903]\n- Simple Trooper Greaves [item=38902]\n- Simple Trooper Helm [item=38901]\n- Simple Trooper Sleeves [item=38900]\n- Simple Twoscale Armband [item=38863]\n- Simple Twoscale Boots [item=38864]\n- Simple Twoscale Cuirass [item=36757]\n- Simple Twoscale Gloves [item=36758]\n- Simple Twoscale Greaves [item=36759]\n- Simple Twoscale Helm [item=38865]\n- Simple Twoscale Sleeves [item=36760]",
    },
    {
      id = "11007",
      title = "Cabilis Quests - Shestar's Scaled Coif (5 Points)",
      exp = "01",
      exp_name = "The Ruins of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "Trooper Shestar",
      loc = nil,
      triggers = {
        "shestar scaled coif?",
        "Shestar scaled coif",
      },
      items_required = {
        { id = 12466, name = "Item #12466", count = 3 },
      },
      rewards = {
        { id = 12468, name = "Item #12468", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon completing the following Cabilis quest.\n[ ] Complete Trooper Shestar's quest \"Shestar's Scaled Coif\" in Cabilis EastSubmitted by: GidonoRewards:\n[",
    },
    {
      id = "11008",
      title = "Cabilis Quests - Geozite Tool (5 Points)",
      exp = "01",
      exp_name = "The Ruins of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "Drill Master Vygan",
      loc = nil,
      triggers = {
        "militia pike",
        "upgrade the partisan pike",
        "what geozite tool",
        "want a geozite tool",
        "true warrior of the legion",
        "done",
        "legionnaire",
        "issue is over",
      },
      items_required = {
        { id = 18203, name = "Item #18203", count = 1 },
        { id = 12675, name = "Item #12675", count = 1 },
        { id = 12677, name = "Item #12677", count = 1 },
        { id = 5130, name = "Item #5130", count = 1 },
        { id = 12658, name = "Item #12658", count = 1 },
        { id = 5135, name = "Item #5135", count = 1 },
      },
      rewards = {
        { id = 17993, name = "Item #17993", type = "item" },
        { id = 48002, name = "Item #48002", type = "item" },
        { id = 5130, name = "Item #5130", type = "item" },
        { id = 5131, name = "Item #5131", type = "item" },
        { id = 48006, name = "Item #48006", type = "item" },
        { id = 48009, name = "Item #48009", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon completing the following Cabilis quest.\n[ ] Complete Drill Master Vygan's quest \"Geozite Tool\" in Cabilis EastSubmitted by: GidonoRewards:\n[",
    },
    {
      id = "11010",
      title = "Cabilis Quests - Granite Pebbles (5 Points)",
      exp = "01",
      exp_name = "The Ruins of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "The Toilmaster",
      loc = nil,
      triggers = {
        "hammer of exoneration",
        "bag",
        "granite pebbles",
      },
      items_required = {
        { id = 12660, name = "Item #12660", count = 2 },
        { id = 18271, name = "Item #18271", count = 1 },
      },
      rewards = {
        { id = 24767, name = "Item #24767", type = "item" },
        { id = 17091, name = "Item #17091", type = "item" },
        { id = 12689, name = "Item #12689", type = "item" },
        { id = 18272, name = "Item #18272", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon completing the following Cabilis quest.\n[ ] Complete The Toilmaster's quest \"Granite Pebbles\" in Cabilis EastSubmitted by: GidonoRewards:\n[",
    },
    {
      id = "11011",
      title = "Cabilis Quests - Illweed Parchment (5 Points)",
      exp = "01",
      exp_name = "The Ruins of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "War Historian Kobl",
      loc = nil,
      triggers = {
        "what unique writing materials",
        "what blood ink",
        "what illweed parchment",
        "unique writing materials",
        "blood ink",
        "illweed parchment",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon completing the following Cabilis quest.\n[ ] Complete War Historian Kobl's quest \"Illweed Parchment\" in Cabilis EastSubmitted by: GidonoRewards:\n[",
    },
    {
      id = "11012",
      title = "Cabilis Quests - Blood Ink (5 Points)",
      exp = "01",
      exp_name = "The Ruins of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "War Historian Kobl",
      loc = nil,
      triggers = {
        "what unique writing materials",
        "what blood ink",
        "what illweed parchment",
        "unique writing materials",
        "blood ink",
        "illweed parchment",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon completing the following Cabilis quest.\n[ ] Complete War Historian Kobl's quest \"Blood Ink\" in Cabilis EastSubmitted by: GidonoRewards:\n[",
    },
    {
      id = "11013",
      title = "Cabilis Quests - Scaled Curskins (5 Points)",
      exp = "01",
      exp_name = "The Ruins of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "Klok Mugruk",
      loc = nil,
      triggers = {
        "bristle silk",
        "curscale armor",
        "small service",
        "perform a small service",
        "perform the small service",
      },
      items_required = {
        { id = 12655, name = "Item #12655", count = 1 },
        { id = 12685, name = "Item #12685", count = 1 },
      },
      rewards = {
        { id = 17992, name = "Item #17992", type = "item" },
        { id = 12687, name = "Item #12687", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon completing the following Cabilis quest.\n[ ] Complete Klok Mugruk's quest \"Scaled Curskins\" in Cabilis EastSubmitted by: GidonoRewards:\n[",
    },
    {
      id = "11014",
      title = "Cabilis Quests - Cursed Wafers (5 Points)",
      exp = "01",
      exp_name = "The Ruins of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "Hierophant Oxyn",
      loc = nil,
      triggers = {
        "hail",
        "temple tasks",
        "daily tasks",
        "mud crabs",
        "lost skulls",
        "iron cudgel",
        "larger problem",
        "ancient skull",
      },
      items_required = {
        { id = 3895, name = "Component Mortar", count = 1 },
        { id = 3886, name = "Item #3886", count = 1 },
        { id = 12403, name = "Item #12403", count = 1 },
        { id = 12721, name = "Item #12721", count = 1 },
        { id = 12722, name = "Item #12722", count = 1 },
        { id = 12723, name = "Item #12723", count = 1 },
      },
      rewards = {
        { id = 17020, name = "Component Mortar", type = "item" },
        { id = 3892, name = "Note to Oxyn", type = "item" },
        { id = 5141, name = "Bottle of Liquid Deklium", type = "item" },
        { id = 5142, name = "Chunk of Tynnonium", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon completing the following Cabilis quest.\n[ ] Complete Hierophant Oxyn's quest \"Cursed Wafers\" in Cabilis EastSubmitted by: GidonoRewards:\n[",
    },
    {
      id = "11015",
      title = "Cabilis Quests - Exterminate the Vermin for Sahizz (5 Points)",
      exp = "01",
      exp_name = "The Ruins of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "Exterminator Sahizz",
      loc = nil,
      triggers = {
      },
      items_required = {
        { id = 12466, name = "Item #12466", count = 4 },
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon completing the following Cabilis quest.\n[ ] Complete Exterminator Sahizz's quest \"Exterminate the Vermin for Sahizz\" in Cabilis EastSubmitted by: GidonoRewards:\n[",
    },
    {
      id = "13732",
      title = "Cabilis Guild Summons: Shaman",
      exp = "01",
      exp_name = "The Ruins of Kunark",
      min_lvl = 1,
      max_lvl = 130,
      quest_type = "Quest",
      repeatable = false,
      group_size = "Solo",
      npc = "Prime Hierophant Vek",
      loc = nil,
      triggers = {
        "what trades?",
        "what second book?",
        "trades",
        "second book",
        "unique weapon",
      },
      items_required = {
        { name = "it to you", count = 1 },
      },
      rewards = {
        { id = 51121, name = "Item #51121", type = "item" },
        { id = 51122, name = "Item #51122", type = "item" },
        { id = 5140, name = "Item #5140", type = "item" },
        { id = 7881, name = "Item #7881", type = "item" },
        { id = 7881, name = "Item #7881", type = "item" },
        { id = 14784, name = "Item #14784", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 130\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nWhen your new character enters Norrath for the first time, you might receive this message:\nAs your reptilian eyes adjust to the darkness of the room, an imposing Iksar turns towards you, addressing you with a sharp hiss. 'I am Prime Hierophant Vek. The time has come young one. You have chosen the path of the Shaman. Open your inventory and read the note within. Once you are ready to begin your training, hand the note to me and we will continue.'\nYour new character spawns with a \"Guild Summons\" in its inventory. Right-clicking this item opens a window showing the following text:\nBy the will of the Hierophants of Cabilis, you are hereby summoned to the spired crimson towers of the Temple of Terror. You have reached the age of rebirth and it is time for you to begin your teachings of the ancients and learn the ways of the shaman. You shall offer this summons to Prime Hierophant Vek and be welcomed. We await your arrival.\nPrime Hierophant Vek is located inside the Temple of Terror in Cabilis East at /waypoint ??? . He stands in front in front of your new character when it enters Norrath for the first time.\nUpon giving him the Guild Summons:\nPrime Hierophant Vek says 'Welcome, young petitioner. You have been summoned to this temple to join with the Scaled Mystics. Ours is the way of pain and suffering. Here is the weapon of a petitioner. Through you the power of our ancestors shall flow. As your wisdom grows, so shall your power. Someday you may be a vessel for the supreme might of the ancients. Seek knowldege with Oxyn, he is here to help you. Return to me when you have become more experienced in our art, I will be able to further instruct you on how to progress through your early ranks, as well as in some of the various [trades] you will have available to you.'\nYour faction standing with Scaled Mystics got better.\nYour faction standing with Legion of Cabilis got better.\nYou gain experience!!\nYou receive ???.\nYou say, 'what trades?'\nPrime Hierophant Vek says 'I thought you might be one who was interested in the various different trades, but which one would suit you? Ahh, alas, it would be better to let you decide for yourself, perhaps you would even like to master them all! That would be quite a feat. Well, lets not get ahead of ourselves, here, take this book. When you have finished reading it, ask me for the [second book], and I shall give it to you. Inside them you will find the most basic recipes for each trade. These recipes are typically used as a base for more advanced crafting, for instance, if you wished to be a smith, one would need to find some ore and smelt it into something usable. Good luck!'\nYou receive Tradeskill Basics Vol. I.\nYou say, 'what second book?'\nPrime Hierophant Vek says 'Here is the second volume of the book you requested, may it serve you well!'\nYou receive Tradeskill Basics Vol. II.\nMissing info on reward and faction hits Submitted by: iventheassassinRewards:\n- Tradeskill Basics Vol. I [item=46947]\n- Tradeskill Basics Vol. II [item=46948]\n[",
    },
    {
      id = "3961",
      title = "Journey to Cabilis (Iksar Shadowknight Bracer)",
      exp = "01",
      exp_name = "The Ruins of Kunark",
      min_lvl = 10,
      max_lvl = 15,
      quest_type = "Task",
      repeatable = false,
      group_size = "Solo",
      npc = "Arch Duke Xog",
      loc = nil,
      triggers = {
        "greenmist",
        "argest",
        "ancient library",
        "where",
        "strange iksar",
        "test",
      },
      items_required = {
        { id = 18205, name = "Item #18205", count = 1 },
        { id = 18051, name = "Item #18051", count = 1 },
        { id = 5126, name = "Item #5126", count = 1 },
        { id = 14791, name = "Item #14791", count = 1 },
        { id = 14807, name = "Item #14807", count = 1 },
        { id = 10034, name = "Item #10034", count = 2 },
      },
      rewards = {
        { id = 55285, name = "Black Scale Armguard", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 10\n**Maximum Level:** 15\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Task\n**Group Size:** Solo\n\nYou receive this immediately after completing \"The Cabilisian Trade Route.\"  Take the Note About Your First Trial you just received to Arch Duke Xog.\nYour task 'Journey to Cabilis' has been updated.\nYour faction standing with Crusaders Of Greenmist got better.\nYour faction standing with Legion of Cabilis got better.\nYou gain experience!!\nYou have been given: Black Scale ArmguardRewards:\n- Black Scale Armguard [item=55285]\n[",
    },
    {
      id = "3962",
      title = "Cabilis Guild Summons: Shadow Knight",
      exp = "01",
      exp_name = "The Ruins of Kunark",
      min_lvl = 1,
      max_lvl = 130,
      quest_type = "Quest",
      repeatable = false,
      group_size = "Solo",
      npc = "Arch Duke Xog",
      loc = nil,
      triggers = {
        "greenmist",
        "argest",
        "ancient library",
        "where",
        "strange iksar",
        "test",
      },
      items_required = {
        { id = 18205, name = "Item #18205", count = 1 },
        { id = 18051, name = "Item #18051", count = 1 },
        { id = 5126, name = "Item #5126", count = 1 },
        { id = 14791, name = "Item #14791", count = 1 },
        { id = 14807, name = "Item #14807", count = 1 },
        { id = 10034, name = "Item #10034", count = 2 },
      },
      rewards = {
        { id = 22631, name = "Pawn's Khukri", type = "item" },
      },
      factions = {
        { name = "Crusaders Of Greenmist", change = 100 },
        { name = "Legion of Cabilis", change = 25 },
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 130\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nWhen your new character enters Norrath for the first time, you might receive this message:\nAs your reptilian eyes adjust to the darkness of the room, an imposing Iksar turns towards you, addressing you with a sharp hiss. 'I am Arch Duke Xog. The time has come young one. You have chosen the path of the Shadowknight. Open your inventory and read the note within. Once you are ready to begin your training, hand the note to me and we will continue.'\nYour new character spawns with \"Guild Summons\" in its inventory. Right-clicking this item opens a window showing the following text:\nThe Age of Rebirth has been reached. You are hereby summoned to Cabilis and the spired towers of the Temple of Terror. Under the watchful eye of the Lords of Pain shall you become a shadowknight of the Crusaders of Greenmist, should you survive. Bring this summons to me and receive your orders. Arch Duke Xog Crusaders of Greenmis\nArch Duke Xog is located inside the Temple of Terror in Cabilis East at /waypoint +1015, -190, +74 . He stands in front of your new character when it enters Norrath for the first time.\nUpon giving him the Guild Summons:\nArch Duke Xog says 'Welcome into our brotherhood. Know you that our way is the way of pain. Do as we say and you shall climb the rungs of knighthood. Listen well to the Lords of Pain within this temple and follow the words of the hierophants, for Cazic-Thule speaks to us through them. Take this khukri. It is the chosen weapon of the Crusaders and can deliver great pain unto our foes. Go now and learn our ways. Seek out Lord Gikzic.'\nYour faction standing with Crusaders Of Greenmist has been adjusted by 100.\nYour faction standing with Legion of Cabilis has been adjusted by 25.\nYou gain experience!!\nYou receive 3 copper from Arch Duke Xog.\nYou receive 1 silver from Arch Duke Xog.\nYou receive Pawn's Khukri.\nSubmitted by: iventheassassinRewards:\n- Pawn's Khukri [item=22631]\n[",
    },
    {
      id = "4817",
      title = "Cabilis Guild Summons: Monk",
      exp = "01",
      exp_name = "The Ruins of Kunark",
      min_lvl = 1,
      max_lvl = 130,
      quest_type = "Quest",
      repeatable = false,
      group_size = "Solo",
      npc = "Grand Master Glox",
      loc = nil,
      triggers = {
        "trial of agility",
        "ready",
      },
      items_required = {
        { id = 18204, name = "Item #18204", count = 1 },
        { id = 14788, name = "Item #14788", count = 1 },
        { id = 14782, name = "Item #14782", count = 1 },
        { id = 10032, name = "Item #10032", count = 1 },
      },
      rewards = {
        { id = 778, name = "Shackle of Dust", type = "item" },
      },
      factions = {
        { name = "Swift Tails has been adjust by 200\nYour faction standing with Legion of Cabilis", change = 50 },
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 130\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nWhen your new character enters Norrath for the first time, you might receive this message:\nAs you enter the Court of Pain, Grand Master Glox, sits in mediation. Without even looking up, he addresses you. 'The time has come for discipline. Read the note in your inventory and then hand it to me to begin your training.'\nYour new character spawns with \"Guild Summons\" in its inventory. Right-clicking this item opens a window showing the following text:\nThis Broodling has reached the Age of Rebirth. The Broodling is called forth to Cabilis to begin training in the art of fist and tail. Within the walls of the Court of Pain shall I wait. This summons shall be presented to me upon arrival. Discipline awaits. Grand Master Glox The Swifttail Caste\nGrand Master Glox is located at the entrance of the Court of Pain in East Cabilis at /waypoint +420, -31 . He stands in front of your new character when it enters Norrath for the first time.\nUpon giving him the Guild Summons:\nGrand Master Glox breaks his meditation and quickly grabs your forearms. You feel the raw power in his heavily callused hands. Out of nowhere, his tail sweeps forward and places a small shackle upon your wrist. He then points southward towards Master Bain and returns to his meditation.\nYour faction standing with Swift Tails has been adjust by 200\nYour faction standing with Legion of Cabilis has been adjusted by 50\nYou gain experience!!\nYou receive Shackle of Dust.\nDo not lose this or you won't be able to do any of the Monk Shackle Quests!\nSubmitted by: iventheassassinRewards:\n- Shackle of Dust [item=778]\n[",
    },
  },
}
