-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Chapterhouse of the Fallen (chapterhouse)
-- Total Quests: 17
-- ============================================================================

return {
  zone = "chapterhouse",
  zone_name = "Chapterhouse of the Fallen",
  quests = {
    {
      id = "5987",
      title = "Hunter of Chapterhouse of the Fallen",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Unknown",
      loc = nil,
      triggers = {
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | No\n**Can Be Shrouded?:** | No\n**Quest Type:** | Achievement\n**Quest Goal:**\n- Advancement\n**Related Creatures:**\n- A Lost Soul [npc=41239]\n- A Mournful Spirit [npc=41240]\n- Braintaster [npc=41241]\n- Falhotep the Cursed [npc=41242]\n- Halstor Bonewalker [npc=41243]\n- Kaficus the Undying [npc=41244]\n- Plaguetooth [npc=41245]\n- Ralstok Plaguebone [npc=41246]\n- Sergeant Malorin [npc=41247]\n- Sir Raint [npc=41248]\n- The Flesheater [npc=41249]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 28 05:29:13 2012\nModified: Tue Jan 21 07:05:09 2025 | | This is a Hunter achievement for Rain of Fear.\nThis achievement is gained upon defeating the following rare monsters in Chapterhouse of the Fallen:\nA Lost Soul\nA Mournful Spirit\nBraintaster\nFalhotep the Cursed\nHalstor Bonewalker\nKaficus the Undying\nPlaguetooth\nRalstok Plaguebone\nSergeant Malorin\nSir Raint\nThe Flesheater\n_Reward:_\nNone\n\n---\n\n_\"chapterhouse\" map file (also click links to the left for location information):_\nP -154.6016, -163.3873, -93.0016, 0, 127, 0, 1, Ralstok\\_Plaguebone\nP -511.3125, -215.6028, -247.0159, 0, 127, 0, 1, Braintaster\nP -246.4048, -450.7532, -222.5278, 0, 127, 0, 1, A\\_Lost\\_Soul\nP -505.6104, -124.7897, -3.0015, 0, 127, 0, 1, Sir\\_Raint\nP -943.5858, -80.6713, -93.0016, 0, 127, 0, 1, Kaficus\\_the\\_Undying\nP -595.6697, -222.0096, -93.0019, 0, 127, 0, 1, The\\_Flesheater\nP -590.1962, -2.5473, -93.0016, 0, 127, 0, 1, The\\_Flesheater\nP -745.0349, -3.9462, -93.0016, 0, 127, 0, 1, Kaficus\\_the\\_Undying\nP -831.7731, -62.0005, -244.5212, 0, 127, 0, 1, Braintaster\nP -303.6992, 333.7224, -93.0016, 0, 127, 0, 1, Halstor\\_Bonewalker\nP -437.4200, -320.8759, -93.0016, 0, 127, 0, 1, Falhotep\\_the\\_Cursed\nP -343.9235, -88.1400, -2.9958, 0, 127, 0, 1, Sir\\_Raint\nP 21.8590, -18.2465, -93.0010, 0, 127, 0, 1, A\\_Mournful\\_Spirit\nP 56.6388, -182.1184, -3.0015, 0, 127, 0, 1, Plaguetooth\nP -481.0835, 119.3652, -2.9768, 0, 127, 0, 1, Sergeant\\_Malorin\n_Note: This covers every named in the zone, but is not a complete list of possible spawn points._",
    },
    {
      id = "6097",
      title = "Chapterhouse \\#1: Infiltrating the Burning Dead",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Sir Birton",
      loc = { y = 65.0, x = 545.0, z = 0.0 },
      triggers = {
        "Hail, Sir Birton",
        "What threat?",
        "How do we stop them?",
        "Who is Falsin Bonecraft?",
        "I will infiltrate them",
        "Hail, Falsin Bonecraft",
        "Hail, Yarin Shroudfear",
        "Hail, Plinki Bonebrood",
      },
      items_required = {
        { name = "you some more", count = 1 },
        { name = "them some of this energy elixir", count = 1 },
      },
      rewards = {
        { id = 106473, name = "Burning Dead Robes", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\n**Who:**\n- Sir Birton [npc=41326]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Burning Dead Robes [item=106473]\n**Related Creatures:**\n- Falsin Bonecraft [npc=42313]\n- Orson Gravegloom [npc=41332]\n- Plinki Bonebrood [npc=41331]\n- Yarin Shroudfear [npc=41330]\n**Related Quests:**\n- A Matter of Life and Death [quest=6104]\n- Breaking Bones [quest=6099]\n- Chapterhouse #2: Operation [quest=6101]\n- Chapterhouse #3: Dead Gnomes Tell No Tales... Or Do They? [quest=6102]\n- Organ Trail [quest=6100]\n- Raid Expedition: A Matter of Life and Death [quest=6105]\n- Run, You Fools! [quest=6103]\n- Undead Maintenance [quest=6098]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 29 05:46:57 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This task begins with Sir Birton ( map) in the Chapterhouse of the Fallen. He is found at location 65, 545, 0 (on the main floor are two large rooms -- he is in the northwest part of the west room)._\n_Pre-Requisites:_\n\\- Level 85\n\\- No tasks\nYou say, 'Hail, Sir Birton'\nSir Birton says 'Stay your weapons; I have no intent on harming you. A much greater [threat] dwells in the depths of these once sacred halls.'\nYou say, 'What threat?'\nSir Birton says 'The necromancers of the Burning Dead have infiltrated the lower levels, and seek to raise the dead for some nefarious scheme. We must find a way to stop them. No; you must find a way to [stop them].'\nYou say, 'How do we stop them?'\nSir Birton says 'If you are not afraid of the walking dead, and if you are, I don't know why you have traveled here, you must find a way to infiltrate the ranks of the Burning Dead and discover their plans. I may have a way to help you gain access to one of their leaders, [Falsin Bonecraft].'\nYou say, 'Who is Falsin Bonecraft?'\nSir Birton says 'Falsin is a despicable little gnome who delights in having undead servants do his dirty work. However, I do not think he would be opposed to having a new gnomish recruit if the opportunity presented itself. Will you help to [infiltrate] the ranks of the Burning Dead?'\nYou say, 'I will infiltrate them'\nSir Birton says 'I knew I could count on you. Take these Burning Dead robes. When used, they will cast an illusion spell upon you so that you can blend in among the necromancers. The undead however may see through your disguise, so use caution. If you [need more robes] just let me know and I will give you some more. That is all. May Marr's blessing be upon you.'\n_You receive \"Burning Dead Robes\"._\nYou have been assigned the task 'Infiltrating the Burning Dead'.\nAn undead paladin named Sir Birton has asked you to infiltrate the Burning Dead cult that has spread throughout the deeper regions of the Chapterhouse.\nUse the Burning Dead Robes to disguise yourself as a member of the Burning Dead and speak with Falsin Bonecraft.\n\n---\n\nSpeak with the leader of the Burning Dead, Falsin Bonecraft 0/1 (Chapterhouse of the Fallen)\n_Falsin Bonecraft ( map) is found at /location 0, 815, -91 (down one level from the main floor -- the western half of that level)._\n_Use the illusion before speaking to him._\nYou say, 'Hail, Falsin Bonecraft'\nFalsin Bonecraft says 'Ah, another initiate eager to prove their worth to the Burning Dead? So be it. There is a lot to be done before the ritual commences, and you will prove your worth by completing some tasks given by some of my neophytes. Seek out Yarin Shroudfear, Plinki Bonebrood, and Orson Gravegloom and do what they say. Disobey, and I will kill you and then reanimate your bones to clean the latrines. Now go.'\nSpeak with Yarin Shroudfear 0/1 (Chapterhouse of the Fallen)\nYou say, 'Hail, Yarin Shroudfear'\nYarin Shroudfear says 'Falsin sent you to help me? Good, I am very busy and there are lots of things that need to be done. Some of the mummies need their linen wrappings changed, the ghouls need to be fed, and some of the zombies need some pep, as they are becoming too complacent. Give them some of this energy elixir. Let me know if you need more [linen wrappings], [rotten flesh], or [energy elixir]. Oh, I almost forgot; there is also a skeleton that has become too intelligent and continues to resist our efforts to control him. Seek out Coffinhowl and destroy him.'\nYou have been assigned the task 'Undead Maintenance'.\nComplete the task that Yarin Shroudfear has assigned to you 0/1 (Chapterhouse of the Fallen)\n_Complete the task \" Undead Maintenance [quest=6098]\"._\nSpeak with Plinki Bonebrood 0/1 (Chapterhouse of the Fallen)\nYou say, 'Hail, Plinki Bonebrood'\nPlinki Bonebrood says 'Some of our more unconventional experiments have gone awry. Seek out these failed experiments and destroy them. And make sure to kill the neophyte responsible for these failed experiments. His name is Jurso Fumblefink.'\nYou have been assigned the task 'Breaking Bones'.\nComplete the task that Plinki Bonebrood has assigned to you 0/1 (Chapterhouse of the Fallen)\n_Complete the task \" Breaking Bones [quest=6099]\"._\nSpeak with Orson Gravegloom 0/1 (Chapterhouse of the Fallen)\nYou say, 'Hail, Orson Gravegloom'\nOrson Gravegloom says 'Oh, hello. I'm Orson. The others here like to make fun of me because they think I am not so smart, but I will prove them wrong! In the meantime, can you [take care] of something for me? I am way behind in my studies and if I raise another zombie that decides it would rather recite poetry than act all zombie-like, I will fail my exam again.'\nYou say, 'I'd love to take care of it...'\nOrson Gravegloom says 'We need lots of organs for some sort of upcoming ritual. I'm not sure what it's all about, but I am sure it will be all gory and stuff. We will need an appendix, a spleen, a liver, a tongue, a pair of eyes, a spinal cord, and a heart. I was told that the heart we need belongs to a paladin named, Sir Graxton Talonheart. He probably wants to keep his heart, so expect a fight. Once you have all that stuff, place everything into the coffin nearby. Why? I don't know, just cause that's what you're supposed to do.'\nYou have been assigned the task 'Organ Trail'.\nComplete the task that Orson Gravegloom has assigned to you 0/1 (Chapterhouse of the Fallen)\n_Complete the task \" Organ Trail [quest=6100]\"._\nSpeak with Sir Birton 0/1 (Chapterhouse of the Fallen)\nYou say, 'Hail, Sir Birton'\nSir Birton says 'My sources inform me that you have blended in well with the Burning Dead and are well on your way to getting on their good side; if they have one that is. I just hope you didn't enjoy your grisly tasks too much. There is still much to be done before you fully gain their trust however. We must find out more about their upcoming ritual. Use the burning dead robes to disguise yourself again and seek out a necromancer known as Bertrand the Butcher. I hear he is eager to show new recruits the tricks of the trade. Gain his trust and hopefully we can learn more about the upcoming ritual. If you [need more robes] just let me know.'\n_Rewards:_\n450 platinum\nExperience (6 AAs)",
    },
    {
      id = "6098",
      title = "Undead Maintenance",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Yarin Shroudfear",
      loc = { y = 115.0, x = 720.0, z = -91.0 },
      triggers = {
        "Hail, Yarin Shroudfear",
        "linen wrappings",
        "rotten flesh",
        "energy elixir",
      },
      items_required = {
        { name = "them some of this energy elixir", count = 1 },
      },
      rewards = {
        { id = 106493, name = "Linen Wrappings", type = "item" },
        { id = 106495, name = "Red Ghoul Energy Elixir", type = "item" },
        { id = 106494, name = "Rotten Flesh", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\n**Who:**\n- Yarin Shroudfear [npc=41330]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n**Quest Items:**\n- Linen Wrappings [item=106493]\n- Red Ghoul Energy Elixir [item=106495]\n- Rotten Flesh [item=106494]\n**Related Creatures:**\n- Coffinhowl [npc=42311]\n- a complacent zombie [npc=42245]\n- a crumbling mummy [npc=42247]\n- a deteriorating mummy [npc=42251]\n- a ravenous ghoul [npc=42282]\n- a starving ghoul [npc=42292]\n- an apathetic zombie [npc=41522]\n- an emaciated ghoul [npc=42299]\n- an unmotivated zombie [npc=42307]\n- an unravelling mummy [npc=42308]\n**Related Quests:**\n- Chapterhouse #1: Infiltrating the Burning Dead [quest=6097]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 29 05:47:01 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a sub-task whose purpose is to progress its parent task \"Infiltrating the Burning Dead\". It is automatically assigned as you progress through that task._\nYou say, 'Hail, Yarin Shroudfear'\nYarin Shroudfear says 'Falsin sent you to help me? Good, I am very busy and there are lots of things that need to be done. Some of the mummies need their linen wrappings changed, the ghouls need to be fed, and some of the zombies need some pep, as they are becoming too complacent. Give them some of this energy elixir. Let me know if you need more [linen wrappings], [rotten flesh], or [energy elixir]. Oh, I almost forgot; there is also a skeleton that has become too intelligent and continues to resist our efforts to control him. Seek out Coffinhowl and destroy him.'\nYou have been assigned the task 'Undead Maintenance'.\n_You receive 3x \"Linen Wrappings\" + 3x \"Rotten Flesh\" + 3x \"Red Ghoul Energy Elixir\"._\nYarin Shroudfear has asked you to complete a task he doesn't have time to do himself.\n\n---\n\n_For chapterhouse.txt map file:_\nP -718.5917, -115.8979, -93.0016, 240, 0, 0, 1, unraveling\nP -938.0940, -371.0284, -93.0016, 240, 0, 0, 1, crumbling\nP -1090.6154, 1.3193, -93.0016, 240, 0, 0, 1, starving\nP -872.5763, 252.7368, -93.0016, 240, 0, 0, 1, ravenous\nP -717.3637, 297.2747, -93.0016, 240, 0, 0, 1, emaciated\nP -392.3173, 251.5591, -93.0016, 240, 0, 0, 1, complacent\nP -288.6473, 281.1876, -93.0016, 240, 0, 0, 1, unmotivated\nP -449.0786, 150.4914, -93.0016, 240, 0, 0, 1, apathetic\nP -469.0016, 144.8229, -93.0016, 240, 0, 0, 1, deteriorating\n\n---\n\n_NOTE: The three zombies involved with this task have a chance to turn aggro upon turn-in. If this happens, it will not accept any further turn-ins (needs to be killed and respawn before being able to do another)._\n_The aggro'd zombies are permanently rooted in place._\nDeliver the linen wrappings to an unraveling mummy 0/1 (Chapterhouse of the Fallen)\n_Found at 115, 720, -91 (in the room north of Yarin Shroudfear)._\nDeliver the linen wrappings to a crumbling mummy 0/1 (Chapterhouse of the Fallen)\n_Found at 370, 935, -91 (follow the hallway north from the starving ghoul)._\nDeliver the linen wrappings to a deteriorating mummy 0/1 (Chapterhouse of the Fallen)\n_Found at -145, 470, -91 (from the large center room in the same area, this is one room southeast)._\nDeliver some rotten flesh to a starving ghoul 0/1 (Chapterhouse of the Fallen)\n_Found at 0, 1090, -91 (due west from Yarin Shroudfear's location)._\nDeliver some rotten flesh to a ravenous ghoul 0/1 (Chapterhouse of the Fallen)\n_Found at -250, 875, -91 (from the emaciated ghoul, go west into a room, and then into the hall to the southwest)._\nDeliver some rotten flesh to an emaciated ghoul 0/1 (Chapterhouse of the Fallen)\n_Found at -300, 715, -91 (from the complacent zombie, follow the hallway west)._\nDeliver the red ghoul energy elixir to a complacent zombie 0/1 (Chapterhouse of the Fallen)\n_Found at -250, 390, -91 (in the hallway due south of the apathetic and deteriorating zombies). NOTE: This mob has a chance to aggro you after the turn-in. If this happens, it will still update this task step, but will not accept any turn-ins from anyone else until it's killed and respawns (respawn timer is only a few minutes)._\nDeliver the red ghoul energy elixir to an unmotivated zombie 0/1 (Chapterhouse of the Fallen)\n_Found at -280, 290, -91 (in the hallway southeast of the apathetic zombie -- the far southeastern part of this section). NOTE: This mob has a chance to aggro you after the turn-in. If this happens, it will still update this task step, but will not accept any turn-ins from anyone else until it's killed and respawns (respawn timer is only a few minutes)._\nDeliver the red ghoul energy elixir to an apathetic zombie 0/1 (Chapterhouse of the Fallen)\n_Found at -150, 450, -91 (in the hallway adjacent to the deteriorating mummy's room). NOTE: This mob has a chance to aggro you after the turn-in. If this happens, it will still update this task step, but will not accept any turn-ins from anyone else until it's killed and respawns (respawn timer is only a few minutes)._\nKill Coffinhowl 0/1 (Chapterhouse of the Fallen)\n_Coffinhowl ( map) is a skeleton located in the hallway directly north of Yarin and the other three Burning Dead NPCs. This fight doesn't seem to be any more difficult than a standard trash mob fight._\n_Rewards:_\n\\- Progresses the task \"Infiltrating the Burning Dead\"",
    },
    {
      id = "6099",
      title = "Breaking Bones",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Plinki Bonebrood",
      loc = nil,
      triggers = {
        "Hail, Plinki Bonebrood",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\n**Who:**\n- Plinki Bonebrood [npc=41331]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n**Related Creatures:**\n- Jurso Fumblefink [npc=42316]\n- a failed experiment [npc=42258]\n**Related Quests:**\n- Chapterhouse #1: Infiltrating the Burning Dead [quest=6097]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 29 05:47:09 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a sub-task whose purpose is to progress its parent task \"Infiltrating the Burning Dead\". It is automatically assigned as you progress through that task._\nYou say, 'Hail, Plinki Bonebrood'\nPlinki Bonebrood says 'Some of our more unconventional experiments have gone awry. Seek out these failed experiments and destroy them. And make sure to kill the neophyte responsible for these failed experiments. His name is Jurso Fumblefink.'\nYou have been assigned the task 'Breaking Bones'.\nPlinki Bonebrood has asked you to complete a task that she doesn't have time to do herself.\nKill some failed experiments. Jurso Fumblefink has failed for the last time. Find him and kill him!\n\n---\n\nKill failed experiments 0/3 (Chapterhouse of the Fallen)\nKill Jurso Fumblefink 0/1 (Chapterhouse of the Fallen)\n_Failed experiments can found in the halls throughout this same area, while Jurso Fumblefink ( map) is found in the room just east of Plinki Bonebrood._\n_Rewards:_\n\\- Progresses the task \"Infiltrating the Burning Dead\"",
    },
    {
      id = "6100",
      title = "Organ Trail",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Orson Gravegloom",
      loc = { y = 225.0, x = 60.0, z = -91.0 },
      triggers = {
        "Hail, Orson Gravegloom",
        "I",
        "take care",
      },
      items_required = {
      },
      rewards = {
        { id = 106598, name = "Appendix", type = "item" },
        { id = 106614, name = "Liver", type = "item" },
        { id = 106520, name = "Pair of Eyes", type = "item" },
        { id = 106618, name = "Sir Graxton's Heart", type = "item" },
        { id = 106575, name = "Spinal Cord", type = "item" },
        { id = 106532, name = "Spleen", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\n**Who:**\n- Orson Gravegloom [npc=41332]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n**Quest Items:**\n- Appendix [item=106598]\n- Liver [item=106614]\n- Pair of Eyes [item=106520]\n- Sir Graxton's Heart [item=106618]\n- Spinal Cord [item=106575]\n- Spleen [item=106532]\n- Tongue [item=106605]\n**Related Creatures:**\n- Sir Graxton Talondrake [npc=42321]\n- a coffin [npc=42244]\n**Related Quests:**\n- Chapterhouse #1: Infiltrating the Burning Dead [quest=6097]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 29 05:47:12 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a sub-task whose purpose is to progress its parent task \"Infiltrating the Burning Dead\". It is automatically assigned as you progress through that task._\nYou say, 'Hail, Orson Gravegloom'\nOrson Gravegloom says 'Oh, hello. I'm Orson. The others here like to make fun of me because they think I am not so smart, but I will prove them wrong! In the meantime, can you [take care] of something for me? I am way behind in my studies and if I raise another zombie that decides it would rather recite poetry than act all zombie-like, I will fail my exam again.'\nYou say, 'I'd love to take care of it...'\nOrson Gravegloom says 'We need lots of organs for some sort of upcoming ritual. I'm not sure what it's all about, but I am sure it will be all gory and stuff. We will need an appendix, a spleen, a liver, a tongue, a pair of eyes, a spinal cord, and a heart. I was told that the heart we need belongs to a paladin named, Sir Graxton Talonheart. He probably wants to keep his heart, so expect a fight. Once you have all that stuff, place everything into the coffin nearby. Why? I don't know, just cause that's what you're supposed to do.'\nYou have been assigned the task 'Organ Trail'.\nOrson Gravegloom has asked you to complete a task that he doesn't have time to do himself.\nFind an appendix, a spleen, a liver, a tongue, a pair of eyes, and a spinal cord, and then place them in the coffin near Orson Gravegloom. These parts are scattered throughout the tunnels that the Burning Dead inhabit as well as the prison area. Locate the imprisoned paladin, Sir Graxton Talondrake, and then take his heart.\n\n---\n\nPlace an appendix inside the coffin 0/1 (Chapterhouse of the Fallen)\nPlace a spleen inside the coffin 0/1 (Chapterhouse of the Fallen)\nPlace a liver inside the coffin 0/1 (Chapterhouse of the Fallen)\nPlace a tongue inside the coffin 0/1 (Chapterhouse of the Fallen)\nPlace a pair of eyes inside the coffin 0/1 (Chapterhouse of the Fallen)\nPlace a spinal cord inside the coffin 0/1 (Chapterhouse of the Fallen)\n_The above six items are scattered throughout the area as ground spawns (appear as hunks of meat on the ground)._\nKill Sir Graxton Talondrake and take his heart 0/1 (Chapterhouse of the Fallen)\n_Sir Graxton Talondrake ( map) is found in a prison cell on the same floor, but on the eastern side (you will have to leave the floor and reach the prison through either the basement caverns or the main floor)._\n_He is found at /location 225, 60, -91 (the first cell to the east from the north entrance to the prison area). Note that while he is KOS, he is not social with any other mobs in the zone._\nPlace Sir Graxton's heart inside the coffin 0/1 (Chapterhouse of the Fallen)\n_Rewards:_\n\\- Progresses the task \"Infiltrating the Burning Dead\"",
    },
    {
      id = "6101",
      title = "Chapterhouse \\#2: Operation",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Bertrand the Butcher",
      loc = { y = -265.0, x = 81.0, z = -91.0 },
      triggers = {
        "Hail, Bertrand the Butcher",
        "I",
        "Raise the Halfling",
        "Hail, Gertrude Darksworn",
        "prove her wrong",
      },
      items_required = {
      },
      rewards = {
        { id = 106473, name = "Burning Dead Robes", type = "item" },
        { id = 106504, name = "Halfling Brain", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\n**Who:**\n- Bertrand the Butcher [npc=41327]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Burning Dead Robes [item=106473]\n**Related Creatures:**\n- Gertrude Darksworn [npc=42314]\n- a necromancer boneraiser [npc=42278]\n- a skeletal nurse [npc=42288]\n- an unconscious halfling [npc=42303]\n- an undead halfling [npc=42305]\n**Related Quests:**\n- A Matter of Life and Death [quest=6104]\n- Chapterhouse #1: Infiltrating the Burning Dead [quest=6097]\n- Chapterhouse #3: Dead Gnomes Tell No Tales... Or Do They? [quest=6102]\n- Raid Expedition: A Matter of Life and Death [quest=6105]\n- Run, You Fools! [quest=6103]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 29 05:47:19 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This solo task is the second in a series of three. It begins with Bertrand the Butcher ( map) in the Chapterhouse of the Fallen. He is found at location -265, 81, -91. This is the south hallway that extends from the prison area (the prison area being one floor down from the zone-in level, east side)._\n_Pre-Requisites:_\n\\- Level 85\n\\- Completed \"Infiltrating the Burning Dead\"\n_Note: You must use the \"Burning Dead Robes\" illusion before you can speak with Bertrand (say \"need more robes\" to Sir Birton - map)._\nYou say, 'Hail, Bertrand the Butcher'\nBertrand the Butcher says 'So you're the new initiate everyone has been talking about? Good, I need you to do something for me. A colleague of mine named Gertrude Darksworn and I have a bet. I believe that Halflings would make suitably fine undead minions, and Gertrude thinks they will not. Let's [prove her wrong].'\nYou say, 'I'll prove her wrong'\nBertrand the Butcher says 'Head to the examination room behind me and find the unconscious Halflings. A skeletal nurse and a necromancer boneraiser will be waiting to assist you with the surgery to prepare them to be raised as an undead minion, so I can prove Gertrude wrong once and for all. Don't worry; the Halfling won't feel a thing, and if they do feel it, that's just too bad!'\nGertrude Darksworn says 'I can't wait to prove you wrong, Bertrand!'\nYou have been assigned the task 'Operation'.\nBertrand has a bet going with one of his colleagues named Gertrude Darksworn regarding if Halflings make suitable undead servants or not. Bertrand thinks they will and Gertrude thinks they will not. Head to the examination room behind Bertrand and Gertrude and try to pick an operating table that is not already being used by a fellow adventurer.\n\n---\n\nAsk the skeletal nurse to make an incision in the unconscious Halfling's chest 0/1 (Chapterhouse of the Fallen)\n_/say \"Make an incision\" until you get the update._\nAsk the skeletal nurse to extract unconscious Halfling's heart 0/1 (Chapterhouse of the Fallen)\n_/say \"Extract the heart\" until you get the update._\nAsk the skeletal nurse to extract a blood sample from the unconscious Halfling 0/1 (Chapterhouse of the Fallen)\n_/say \"Extract a blood sample\" until you get the update._\nAsk the skeletal nurse to use the saw to cut open the unconscious Halfling's skull 0/1 (Chapterhouse of the Fallen)\n_/say \"Use the saw\" until you get the update._\nAsk the skeletal nurse to extract the unconscious Halfling's brain 0/1 (Chapterhouse of the Fallen)\n_/say \"Extract the brain\" until you get the update._\n_Fail emotes you'll see as you go along:_\na skeletal nurse faints at the sight of the blood. You will need to try again.\na skeletal nurse breaks the scalpel and fails to make the incision. You will need to try again.\na skeletal nurse breaks the tongs and fails to extract the heart. You will need to try again.\na skeletal nurse breaks the syringe and fails to obtain the blood sample. You will need to try again.\na skeletal nurse breaks the saw. You will need to try again.\na skeletal nurse breaks the tongs and fails to extract the brain. You will need to try again.\n_Success emotes as you go along:_\na skeletal nurse executes the incision flawlessly.\na skeletal nurse extracts the heart from the unconscious halfing.\na skeletal nurse successfully extracts a blood sample from the unconscious halfling.\na skeletal nurse saws open the unconscious halfling's skull flawlessly.\na skeletal nurse extracts the brain from the unconscious halfing.\n\n---\n\nLet the necromancer boneraiser know that the Halfling is ready to be raised as an undead servant 0/1 (Chapterhouse of the Fallen)\n_With the illusion, tell the boneraiser to \"raise the halfling\". A skeletal halfling spawns and runs out of the room, updating the step._\nYou say, 'Raise the Halfling'\na necromancer boneraiser has raised the halfling and turned him into an undead minion. The halfling does not appear to be pleased however.\nan undead halfling shouts, 'Jumjum! I mean brainsss! Brainsss!'\n\n---\n\nDefeat the undead Halfling 0/1 (Chapterhouse of the Fallen)\n_Task Window Says:_ The Halfling has been raised as a skeleton, but has run away. Find where he is hiding and defeat him!\n_Kill any \"an undead halfling\" (found throughout the zone's lower caverns)._\nan undead halfling has been slain by \\_\\_\\_\\_\\_!\nan undead halfling's corpse crumples to the ground.\n\n---\n\nSpeak with Gertrude Darksworn 0/1 (Chapterhouse of the Fallen)\n_Gertrude ( map) is found next to the Butcher._\n_NOTE: You must be in the Burning Robes Illusion in order to get credit for this hail._\nYou say, 'Hail, Gertrude Darksworn'\nGertrude Darksworn says 'See, Bertrand! I was right! You cannot rely on a raised Halfling! Now pay up! Thanks for helping to prove my point, adventurer. Now that we have settled that little matter, I want you to talk to Wilfred Gorefinder. He is investigating a rather curious matter involving members of the Burning Dead being turned into the undead, which just isn't right. See if you can help him with his investigation.'\n_Rewards:_\n112 platinum, 5 gold\nExperience\nHalfling Brain _(used in the second Lost Puppet [quest=6191] task)_\n- Halfling Brain [item=106504]",
    },
    {
      id = "6102",
      title = "Chapterhouse \\#3: Dead Gnomes Tell No Tales... Or Do They?",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Wilfred Gorefinder",
      loc = { y = -325.0, x = 930.0, z = -91.0 },
      triggers = {
        "Hail, Wilfred Gorefinder",
        "Perplexed?",
        "I will find them",
        "Hail, Gibble",
        "perplexed",
        "find",
        "know",
      },
      items_required = {
      },
      rewards = {
        { id = 106473, name = "Burning Dead Robes", type = "item" },
        { id = 106512, name = "Elgan's Clue", type = "item" },
        { id = 107672, name = "Elgan's Remains", type = "item" },
        { id = 106514, name = "Ghost-o-Matic", type = "item" },
        { id = 107664, name = "Ghostly Parchment", type = "item" },
        { id = 106511, name = "Ophelia's Clue", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\n**Who:**\n- Wilfred Gorefinder [npc=41328]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Burning Dead Robes [item=106473]\n- Elgan's Clue [item=106512]\n- Elgan's Remains [item=107672]\n- Ghost-o-Matic [item=106514]\n- Ghostly Parchment [item=107664]\n- Ophelia's Clue [item=106511]\n- Ophelia's Remains [item=107671]\n- Poira's Clue [item=106513]\n- Poira's Remains [item=107673]\n**Related Creatures:**\n- Elgan Tombson [npc=42312]\n- Gibble [npc=42315]\n- Ophelia Bonesnap [npc=42318]\n- Poira the Pale [npc=42319]\n- Slizis Slicetail [npc=42322]\n**Related Quests:**\n- A Matter of Life and Death [quest=6104]\n- Chapterhouse #1: Infiltrating the Burning Dead [quest=6097]\n- Chapterhouse #2: Operation [quest=6101]\n- Raid Expedition: A Matter of Life and Death [quest=6105]\n- Run, You Fools! [quest=6103]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 29 05:47:22 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This task is the third in a series of three. It is a solo task that begins with Wilfred Gorefinder ( map) in the Chapterhouse of the Fallen. He is found at location -325, 930, -91. This is in the southwestern area of the Burning Dead halls in the western half of the zone's second floor._\n_Pre-Requisites:_\n\\- Level 85\n\\- Completed \"Infiltrating the Burning Dead\"\n\\- Completed \"Operation\"\n_Note: You must use the \"Burning Dead Robes\" illusion before you can speak with Wilfred (say \"need more robes\" to Sir Birton - map)._\nYou say, 'Hail, Wilfred Gorefinder'\nWilfred Gorefinder says 'You're the new initiate, eh? There's something not right about you, but if Falsin trusts you, I guess I have no choice but to do the same. I can use your help though. There are a lot of tasks that we need to complete before we can turn our full attention to the upcoming ritual. The task I need your help with has me particularly [perplexed].'\nYou say, 'Perplexed?'\nWilfred Gorefinder says 'Someone is killing members of the Burning Dead and raising them as skeletons. This has to stop. We don't know who the murderer is yet. That's where you come in. I want you to [find] whoever is responsible for these heinous crimes and kill them.'\nYou say, 'I will find them'\nWilfred Gorefinder says 'I have just finished working on a device that should help you with your investigation. I call it the Ghost-o-Matic. It is a wondrous contraption that combines the best of gnomish necromancy and tinkering. To use it, simply place the remains of the one you wish to contact into the device along with a piece of ghostly parchment, and a message from the recently deceased will pop out for you to read. I know; it's quite brilliant if I do say so myself. Take the Ghost-o-Matic and this parchment and find the murderer! If you lose your parchment or the Ghost-o-Matic, let me [know], so I can replace them for you. Once you have dealt with the murderer, speak with my assistant, Gibble. I have other matters to attend to.'\nYou have been assigned the task 'Dead Gnomes Tell No Tales... Or Do They?'.\nWilfred Gorefinder is investigating a rather curious matter involving members of the Burning Dead being murderer and raised as skeletons, which just isn't right. See if you can help him with his investigation.\n_You receive 1x \"Ghost-o-Matic\" + 3x \"Ghostly Parchment\"._\n\n---\n\n**Map Locs**\n_Locations for your chapterhouse.txt map file:_\nP -411.2793, -231.2680, -254.0211, 0, 127, 0, 3, Elgan\\_Tombson\nP -846.1398, 212.7341, -247.8676, 0, 127, 0, 3, Ophelia\\_Bonesnap\nP -838.3505, -514.9295, -180.6994, 0, 127, 0, 3, Poira\\_the\\_Pale\n\n---\n\nKill Ophelia Bonesnap and loot her remains 0/1 (Chapterhouse of the Fallen)\n_Ophelia Bonesnap ( map) is found in the zone's lowest section - the caverns. Approximate location: -220, 800, -245. This is in the northern part of the caverns' southwestern-most room._\nObtain the first clue 0/1 (Chapterhouse of the Fallen)\n_In the Ghost-O-Matic, combine 1x \"Ophelia's Remains\" + 1x \"Ghostly Parchment\" to produce \"Ophelia's Clue\"._\n\n---\n\nKill Elgan Tombson and loot his remains 0/1 (Chapterhouse of the Fallen)\n_Elgan Tombson ( map) is located at 225, 420, -250 (this is in the largest room of the caverns -- in the northeastern part of the large room west of the river)._\nObtain the second clue 0/1 (Chapterhouse of the Fallen)\n_In the Ghost-O-Matic, combine 1x \"Elgan's Remains\" + 1x \"Ghostly Parchment\" to produce \"Elgan's Clue\"._\n\n---\n\nKill Poira the Pale and loot her remains 0/1 (Chapterhouse of the Fallen)\n_Poira the Pale ( map) is located in the northernmost tunnel that leads from the basement caverns to the zone's middle floor._\nObtain the third clue 0/1 (Chapterhouse of the Fallen)\n_In the Ghost-O-Matic, combine 1x \"Poira's Remains\" + 1x \"Ghostly Parchment\" to produce \"Poira's Clue\"._\n\n---\n\nFind and defeat the murderer 0/1 (Chapterhouse of the Fallen)\n_The clues read:_\nMy killer has a toothy grin.\nMy killer has scales.\nMy killer has a tail.\n_Slizis Slicetail ( map) can be found swimming back and forth in the underground river in the zone's basement. Note that he sees invisibility and is KOS, but is not social with any other mobs in the zone._\nSlizis Slicetail says 'The Burning Dead wouldn't have me, so they will be punished! All their members will die and so will you!'\n_He hits for a max ~13,000 and casts necromancer spells (no known special abilities and not a particularly difficult fight)._\nSlizis Slicetail has been slain by \\_\\_\\_\\_\\_!\n\n---\n\nSpeak with Gibble 0/1 (Chapterhouse of the Fallen)\n_Note: You need to have the \"Burning Dead Robes\" illusion on in order to get task credit with Gibble ( map)._\nYou say, 'Hail, Gibble'\nGibble says 'So the murderer was an iksar who was angered by the Burning Dead not letting him join? Well I'm glad you have dealt with him. I will let Wilfred know that you have done what was asked of you.'\n_Rewards:_\n150 platinum\nExperience (2 AAs + 2-3% exp in Level 96)",
    },
    {
      id = "6103",
      title = "Run, You Fools!",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Holy Defender Ioris",
      loc = { y = -125.0, x = -70.0, z = -1.0 },
      triggers = {
        "Hail, Holy Defender Ioris",
        "What plot?",
        "I will help",
        "Let",
        "plot",
        "help",
        "enter",
      },
      items_required = {
      },
      rewards = {
        { id = 108203, name = "Force of Two", type = "item" },
        { id = 106497, name = "Glowing Dreadmote", type = "item" },
        { id = 106464, name = "Greater Dreadmote", type = "item" },
        { id = 106476, name = "Lesser Dreadmote", type = "item" },
        { id = 108122, name = "Medal of Honor", type = "item" },
        { id = 106509, name = "Median Dreadmote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\n**Who:**\n- Holy Defender Ioris [npc=41329]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Loot\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 06:00:00\n**Related Zones:**\n- Chapterhouse: Run, You Fools! [zone=895]\n**Related Creatures:**\n- High Lord William Taros [npc=42677]\n- Holy Defender Ioris [npc=42686]\n- Menizzia [npc=42672]\n- a bloodthirsty ghoul - Chapterhouse of the Fallen [npc=42685]\n- a corrupt paladin [npc=42682]\n- a corrupted poltergeist [npc=42684]\n- a deathly shadow [npc=42688]\n- a fallen defender [npc=42675]\n- a fleshrend beetle [npc=42674]\n- a lost spirit of light [npc=42681]\n- a shambling corpse [npc=42676]\n- a summoned skeleton [npc=42687]\n- a vile priest [npc=42680]\n- a wrapped soul [npc=42683]\n- an animated corpse [npc=42689]\n- an old chest - Run, You Fools! [npc=42466]\n- an undead lord [npc=42678]\n- an undead noble [npc=42679]\n- corpse of Marnek [npc=42673]\n**Related Quests:**\n- A Matter of Life and Death [quest=6104]\n- Chapterhouse #1: Infiltrating the Burning Dead [quest=6097]\n- Chapterhouse #2: Operation [quest=6101]\n- Chapterhouse #3: Dead Gnomes Tell No Tales... Or Do They? [quest=6102]\n- Raid Expedition: A Matter of Life and Death [quest=6105]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 29 05:47:25 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This group mission begins with Holy Defender Ioris ( map) in the Chapterhouse of the Fallen at location -125, -70, -1 -- in the side room just north of the zone-in from the Commonlands (southeast of the Shard's Landing portal)._\n_Pre-Requisites:_\n\\- Level 85\n\\- Completed \"Infiltrating the Burning Dead\"\n\\- Completed \"Operation\"\n\\- Completed \"Dead Gnomes Tell No Tales... Or Do They?\"\nYou say, 'Hail, Holy Defender Ioris'\nHoly Defender Ioris nods in acknowledgement of your greeting. 'You're really earning a name for yourself, \\_\\_\\_\\_\\_. Sir Birton has informed me that your infiltration efforts are the reason we were able to uncover Menizzia's [plot].\nYou say, 'What plot?'\nHoly Defender Ioris says 'Menizzia plans to raise an ancient necromancer by the name of Marnek Jaull. His summoning must be stopped. It is not a task I can accomplish alone, however.'\nBloodreaver Narek smiles slyly, 'If you need the assistance of a Knight of Innoruuk, all you need to do is ask, Ioris.'\nHoly Defender Ioris focuses her stern gaze straight ahead, refusing to look Narek in the eye. 'A Paladin of Marr does not require help from those that commune with the dead.'\nBloodreaver Narek says 'As you wish. But heed this warning Ioris; if the summoning succeeds, Marnek Jaull will have power within the realm of the living, as well as the dead. You may find someone with my...' A smooth smile spreads across the shadowknight's face, '...skills, handy.''\nHoly Defender Ioris shivers at the thought before turning her attention toward you, 'Enough of the idle chatter. I will take care of Mezinnia myself if I have to, but I'm counting on your [help], \\_\\_\\_\\_\\_.'\nYou say, 'I will help'\nHoly Defender Ioris nods. 'We should make haste then. Mezzinia has likely already begun her ritual. Let me know when you are ready to [enter] the summoning chamber.'\nYou have been assigned the task 'Run, You Fools!'.\nFind Menizzia and put a stop to her attempt to summon Marnek Jaull. Destroy Menizzia's minions and then press the attack upon her.\nYou say, 'Let' enter!'\nHoly Defender Ioris says 'This way then. I hope you can swim, as much of the path is under water.'\nLOADING, PLEASE WAIT...\nYou have entered Chapterhouse of the Fallen.\n\n---\n\nFind Menizzia 0/1 (Chapterhouse of the Fallen)\n_From the zone-in, head up the ramp and into Menizzia's room. Three aggro mobs spawn and attack._\nMenizzia shouts 'NO! The resurrection must not be interrupted. Marnek MUST rise again! Perhaps this will keep you occupied while I complete the ritual!'\n\n---\n\nDestroy Menizzia's minions 0/1 (Chapterhouse of the Fallen)\n_Kill the three mobs (simple fights). Upon the death of the last mob, be ready to move and keep moving until you reach the end of the task. (If you stop or slow down at any point, it will result in your group's deaths._\na fleshrend beetle has been slain by \\_\\_\\_\\_\\_!\na fleshrend beetle's corpse shudders and falls to the ground\na fallen defender has been slain by \\_\\_\\_\\_\\_!\na fallen defender's corpse collapses to the ground\na shambling corpse has been slain by \\_\\_\\_\\_\\_!\na shambling corpse's corpse stumbles and falls\nMenizzia shouts 'Ridiculous! Will these interruptions never end? Perhaps I need to turn up the heat a bit. Lord Taros will make short work of you!'\nHoly Defender Ioris' voice seems to float through your mind, \"Do not engage Lord Taros, as he is not one to be trifled with. You MUST flee if you can.\"\nHigh Lord William Taros shouts 'Flee while you can, insects! You only delay the inevitable.'\n\n---\n\nEscape from Lord Taros 0/1 (Chapterhouse of the Fallen)\n_Task Window Says:_ Menizzia has summoned High Lord William Taros, a fallen knight of incredible power. You cannot possibly hope to defeat him now. Run, for your lives!\n_You'll need to avoid Taros without getting too close to him (damage aura) or too far behind him (death touch) while clearing the area of mobs._\n_From Menizzia's room: Head through the east tunnel, fight the single mob there, and then go into the second room. Kill five mobs there._\n_From the second room: Head through the north tunnel and into the third room. Kill four mobs there._\n_From the third room: Head into the tunnel to your west, to the end of it, fight the single mob there, and then into the connecting room to that tunnel's south. This is the final room (a few more mobs to kill)._\n_Once in this room, wait for Lord Taros to catch up, and for the script to unfold. Afterwards, Menizzia goes aggro._\n_Note: For reference points, see the map associated with Braintaster. His northeastern spawn location is the \"third room\" as described above. His southwestern spawn location is the final room._\n_As you make your way through the task, you'll see emotes (just flavor text):_\nHigh Lord William Taros shouts 'Run away, little meat sacks!'\nHigh Lord William Taros shouts 'Do you not feel the hand of death closing around your neck? Soon you will be nothing but worm food!'\nHigh Lord William Taros shouts 'Try to flee if you must. Death marches on. None can escape my blade!'\n_Upon reaching the final room and killing the mobs there:_\nHigh Lord William Taros shouts 'I see our little chase has come to the inevitable end. There will be no escape this time. Take your last, pointless breaths while you still can!'\nHoly Defender Ioris shouts 'Not so fast Taros! These brave adventurers will NOT fall today. Not if I have anything to say about it!'\nHigh Lord William Taros shouts 'The living are so predictable. I will not be deterred, not by the likes of you, Ioris!'\nHoly Defender Ioris shouts 'Death has addled what brain you once had, Taros. Come, feel the might of my blade!'\nHoly Defender Ioris shouts 'You there, I will keep Taros occupied. You must return to Menizzia and stop the resurrection of Marnek at any cost, even your own lives! All will perish if Marnek returns!'\nMenizzia shouts 'Did someone call my name? Your efforts here have all been for naught. Marnek lives again, and nothing you do here can change that, yet clearly I cannot trust this walking bag of bones to dispatch the likes of you. Better I deal with you myself and be done with it!'\nMenizzia shouts 'I may not be able to destroy you Ioris, but this is MY realm, and you have no power here. Begone!'\nMenizzia banishes Holy Defender Ioris and saps any remaining energy from Taros in the process. Taros falls to the ground in a heap of lifeless bones.\nHigh Lord William Taros collapses to the ground\nHigh Lord William Taros died.\nMenizzia shouts 'Now then, I will deal with you fleshlings. Marnek lives, you will die, and nothing will stand in my way any longer!'\n_Menizzia goes auto-aggro and attacks._\n\n---\n\nKill Menizzia once and for all 0/1 (Chapterhouse of the Fallen)\n_Menizzia hits for a max ~18,000. She also has a run-away emote (flashes on screen), a 9-second warning preceding a 50' range AE nuke for 150,000hp:_\nMenizzia begins to pulse with the fury of the dead. You should probably run away!\nNecromantic Fury: PB AE 50', (0)\n1: Decrease Hitpoints by 150000\nNecromantic energy explodes outward from Menizzia melting all living flesh in range.\n_Every 45 seconds, she spawns 1x \"a deathly shadow\" + 1x \"an animated corpse\". These need to be killed. If left alive, they despawn with an AE + heal on Menizzia:_\nCorpse Explosion: PB AE 100', (0)\n1: Decrease Hitpoints by 50000\n_As Menizzia's health lowers, she will occasionally spawn a wave of 5x \"a summoned skeleton\":_\nMenizzia shouts 'Why must I waste my time with you? Perhaps some more of my minions will help relieve you of your mortal coil?!'\n_Kill her to update this step:_\nMenizzia has been slain by \\_\\_\\_\\_\\_!\nMenizzia's corpse collapses to the ground.\n\n---\n\nOpen the old chest and claim your reward 0/1 (Chapterhouse of the Fallen)\nYou have defeated Menizzia, but unfortunately she was able to summon Marnek Jaull before you dispatched her.\n_Rewards:_\n150 platinum\nExperience\n_Possible Chest Loot (1 Item + 1 Dreadmote per task):_\nFang Whistle\nForce of Two\nGentleman's Flair\nMedal of Honor\nOssein Cloak\nPain Nullifier\nXanture's Lens of Untold Secrets\nLesser Dreadmote\nMedian Dreadmote\nGreater Dreadmote\nGlowing Dreadmote\n- Force of Two [item=108203]\n- Glowing Dreadmote [item=106497]\n- Greater Dreadmote [item=106464]\n- Lesser Dreadmote [item=106476]\n- Medal of Honor [item=108122]\n- Median Dreadmote [item=106509]\n- Ossein Cloak [item=109239]\n- Pain Nullifier [item=108410]\n- Xanture's Lens of Untold Secrets [item=110330]",
    },
    {
      id = "6104",
      title = "A Matter of Life and Death",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Holy Defender Ioris",
      loc = { y = -125.0, x = -70.0, z = -1.0 },
      triggers = {
        "Hail, Holy Defender Ioris",
        "What failure?",
        "I have a group",
        "Let",
        "help",
        "failure",
        "group",
        "raid",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\n**Who:**\n- Holy Defender Ioris [npc=41329]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Loot\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 06:00:00\n**Related Zones:**\n- Chapterhouse: A Matter of Life and Death [zone=896]\n**Related Creatures:**\n- Marnek Jaull [npc=42690]\n- a ghost [npc=42691]\n- a skeleton - Chapterhouse of the Fallen [npc=42692]\n- a wraith [npc=42963]\n- an ornate chest - A Matter of Life and Death [npc=42467]\n- pool of death [npc=42693]\n- pool of revival [npc=42694]\n**Related Quests:**\n- Chapterhouse #1: Infiltrating the Burning Dead [quest=6097]\n- Chapterhouse #2: Operation [quest=6101]\n- Chapterhouse #3: Dead Gnomes Tell No Tales... Or Do They? [quest=6102]\n- Raid Expedition: A Matter of Life and Death [quest=6105]\n- Run, You Fools! [quest=6103]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 29 05:47:29 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n**Note: This is the group version of \"A Matter of Life and Death\". For the raid version, click here [quest=6105].**\n\n---\n\nThis group mission begins with Holy Defender Ioris [npc=41329] ( map) in the Chapterhouse of the Fallen [zone=874] at location -125, -70, -1 -- in the side room just north of the zone-in from the Commonlands (southeast of the Shard's Landing portal).\n_Pre-Requisites:_\n\\- Level 85\n\\- Completed Infiltrating the Burning Dead [quest=6097]\n\\- Completed Operation [quest=6101]\n\\- Completed Dead Gnomes Tell No Tales... Or Do They? [quest=6102]\n\\- Completed Run, You Fools! [quest=6103] (mission)\nYou say, 'Hail, Holy Defender Ioris'\nHoly Defender Ioris appears relieved at your presence. 'Praise Marr, you're alive! I was worried my stubbornness would result in your death.' The paladin lowers her head in silent acceptance of what must be done. Her eyes reveal distrust as she glares upward toward the shadowknight who stands within hearing distance. 'It was wrong of me to refuse the [help] of a foe, who was willing to banish a common enemy. Marnek's summoning was a result of my pride, not your [failure].'\nBloodreaver Narek [npc=42310] allows a smug grin to spread across his face as Ioris admits her wrongdoing.\nYou say, 'What failure?'\nHoly Defender Ioris says 'I was able to fend off Menizzia [npc=42672], allowing for your escape, but her power proved much too strong to stop the summoning. Marnek now has a foot in both the realm of the dead, as well as the living, meaning he will need to be fought on both fronts. The necromancer grows stronger with every moment we remain idle.' Ioris gestures to the shadowknight in the corner, 'Despite my distaste for the followers of Innoruk, I have agreed to accept Narek's help, as he knows more about the realm of the dead than I care to. He will aid you in passing through to the realm of the dead, while I will ensure that you return to the realm of the living unharmed. Have you prepared a small, but efficient [group], or have you gathered a [raid] force to destroy Marnek once and for all?'\nYou say, 'I have a group'\nHoly Defender Ioris says 'Very well. When you are ready to [go], I will lead your group into the summoning chamber where Marnek resides.'\nYou have been assigned the task 'A Matter of Life and Death'.\nHead into Marnek's summoning chamber and destroy the ancient necromancer who has a hold over the realm of the dead, as well as the living.\nYou say, 'Let's go'\nHoly Defender Ioris says 'May the strength of Marr be with you.'\nLOADING, PLEASE WAIT...\nYou have entered Chapterhouse of the Fallen.\nBloodreaver Narek says 'Marnek's chambers can be found through the tunnel straight ahead. I will stay here and channel the strength of Innoruuk so that the dark pool can provide passage to the realm of the dead. Remember, contact with living creatures while in the in the other realm will cause you harm; Remaining in the dead realm for too long will cause certain death.'\n\n---\n\n**Task Steps**\n1\\. Engage Marnek within the realm of the living 0/1 (Chapterhouse of the Fallen)\nTask Window Says: Marnek can be found in the summoning chamber, through the tunnel south of Holy Defender Ioris.\n2\\. Witness Marnek's transition into the realm of the dead 0/1 (Chapterhouse of the Fallen)\nTask Window Says: According to Irois and Narek, Marnek is able to switch between the realms of the living and the dead.\n3\\. Sacrifice one of your own in the pool of the dead 0/1 (Chapterhouse of the Fallen)\n4\\. Kill wraiths within Marnek's summoning chamber 0/8 (Chapterhouse of the Fallen)\nTask Window Says: Wraiths can only be harmed by those within the realm of the dead.\n5\\. Kill Marnek 0/1 (Chapterhouse of the Fallen)\nTask Window Says: Kill the ancient necromancer!\n6\\. Claim your reward from the ornate chest 0/1 (Chapterhouse of the Fallen)\nTask Window Says: After you have claimed your reward, Holy Defender Ioris will escort you back to the Chapterhouse.\n\n---\n\n**In Detail**\n1\\. Engage Marnek within the realm of the living 0/1 (Chapterhouse of the Fallen)\nThis updates when you aggro Marnek Jaull [npc=42690].\n2\\. Witness Marnek's transition into the realm of the dead 0/1 (Chapterhouse of the Fallen)\nMarnek hits for a max ~18,000 and AE rampages. He casts Necrotic Roots (single-target nuke for 21,000 + DoT for 32,000/tick + root; 60 curse counters) and Scorching Bones (DoT for 39,000/tick; cured by going into the water at either end of the room you're fighting in - north or south).\nTake him to 80% health at which point he turns into a skeleton. From here on out, he will alternate forms (human / skeleton). He is damageable by normal means in human form, but not in skeleton form (more information about this follows).\nYou'll see this emote when he turns \"dead\":\nMarnek enters the realm of the dead, growing in power while shielding himself against attacks from the living.\nYou'll see this emote when he turns \"live\" again:\nMarnek returns to the realm of the living, shielding himself from attacks from the dead.\n3\\. Sacrifice one of your own in the pool of the dead 0/1 (Chapterhouse of the Fallen)\nAt least one person needs to go into the water in the north end of the room (NOTE: This isn't the actual water; it's a \"pool\", similar to a placeable guild hall pool just below the ramp).\nWhen a player enters the north pool, two things happen: The player is put in a shroud and an add called a skeleton [npc=42692] spawns.\nThe skeleton needs to be killed. It procs the spell Stun every five seconds:\nStun: Single Target, Unresistable (-980)\n1: Stun (4.00 sec/200)\nAnyone with the shroud can use the shroud's bane ability to DPS Marnek while he in his skeleton form. The catch is that if you stay in the shroud form too long, you will be death touched. The time limit is not known for sure, but the shroud does come with a buff, so the time limit may be the duration of the buff (not confirmed). To remove the shroud form, go into the water pool at the south end of the room.\nNote: When a shrouded player removes a shroud from themselves, they get a short-term debuff called Resurrection Sickness on them that prevents them from re-shrouding. This only lasts a few ticks, however.\nYou can re-apply the shroud form any time by going into the north water (this spawns an add for each person who does this) and take it off any time by going into the south water. Just make sure you're not in it too long. Note that you cannot refresh the buff. You have to take it off and re-apply it rather than overwriting your existing buff.\nAlso note that if you approach Marnek while he is in his human form, while you are shrouded, you will take extra damage.\nMarnek continues alternating his form based on his health: 70% (human); 50% (skeleton); 40% (human); 20% (skeleton); 10% (human).\n4\\. Kill wraiths within Marnek's summoning chamber 0/8 (Chapterhouse of the Fallen)\nAdds called a wraith [npc=42963] are encountered throughout the event at health intervals. One wraith appears at 94%, 84%, 74%, 64%, 54%, 44%, 34%, 24%, 14%, and 4%. There may also be an 11th wraith, but this is not confirmed.\nThe wraiths can only be damaged with the shrouds. A shroud's \"Lure\" ability can be used to leash the wraith to the shrouded player while the wraith can be DPS'd via melee using the shroud's weapons.\nWARNING: Make sure you have all eight wraith kill updates before you kill Marnek, or the task gets bugged (the chest spawns, but you can't open it).\n5\\. Kill Marnek 0/1 (Chapterhouse of the Fallen)\n6\\. Claim your reward from the ornate chest 0/1 (Chapterhouse of the Fallen)\n_Rewards:_\n300 platinum\nExperience\n_Possible Chest Loot (1 Item + 1 Dreadmote per task):_\nAgeless Spaulders\nBladed Shoulder Blades\nCursed Sash\nGentleman's Flair\nGentleman's Sword\nPlague-borne Wall\nRune of Tainting\nSorrow's Bane\nSpirit of Heroes\nStrength of Valor\nLesser Dreadmote\nMedian Dreadmote\nGreater Dreadmote\nGlowing Dreadmote",
    },
    {
      id = "6159",
      title = "Filthy Ankle Biters",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Aislinn",
      loc = nil,
      triggers = {
        "Hail, Aislinn",
        "Information?",
        "_Quests_",
        "information",
        "indulge",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\n**Who:**\n- Aislinn [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Related Creatures:**\n- a diseased rat - Chapterhouse of the Fallen [npc=42253]\n- a filthy rat [npc=42261]\n- a plague rat [npc=42281]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 29 09:47:40 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with a Halfling named Aislinn ( map) in the Chapterhouse of the Fallen. She is found at the zone-in from the Commonlands (southeastern-most room on the main floor)._\nYou say, 'Hail, Aislinn'\nAislinn says 'I see another one of you sniveling adventurers has found your way into The Chapterhouse. I suppose you assume I have some bit of [information] for you?'\nYou say, 'Information?'\nAislinn says 'You'll have to [indulge] me if you want me to point you in the right direction.'\nYou have been assigned the task 'Filthy Ankle Biters'.\nAislinn wants you to thin out the number of rats in The Chapterhouse.\n\n---\n\nKill filthy rats 0/10 (Chapterhouse of the Fallen)\n_These are found throughout the main floor of the house._\nReturn to Aislinn 0/1 (Chapterhouse of the Fallen)\nYou say, 'Hail, Aislinn'\nDeath and disease has long been a part of this place so I doubt this will keep them away for long. I suppose some form of remuneration is called for, so take this for your efforts.\n_Rewards:_\n112 platinum, 5 gold\nExperience",
    },
    {
      id = "6160",
      title = "Lights in the Night",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Aislinn",
      loc = nil,
      triggers = {
        "Hail, Aislinn",
        "Information?",
        "_Quests_",
        "information",
        "indulge",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\n**Who:**\n- Aislinn [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Related Creatures:**\n- a lost willow wisp [npc=42271]\n- a misguided willow wisp [npc=42275]\n- an enraged willow wisp [npc=42300]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 29 09:47:43 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with a Halfling named Aislinn ( map) in the Chapterhouse of the Fallen. She is found at the zone-in from the Commonlands (southeastern-most room on the main floor)._\nYou say, 'Hail, Aislinn'\nAislinn says 'I see another one of you sniveling adventurers has found your way into The Chapterhouse. I suppose you assume I have some bit of [information] for you?'\nYou say, 'Information?'\nAislinn says 'You'll have to [indulge] me if you want me to point you in the right direction.'\nYou have been assigned the task 'Lights in the Night'.\nAislinn demands that the wisps that often plague her slumber be taken care of.\n\n---\n\nDestroy 5 willow wisps 0/5 (Chapterhouse of the Fallen)\n_These are found in the lower sections of the zone._\nReturn to Aislinn 0/1 (Chapterhouse of the Fallen)\nYou say, 'Hail, Aislinn'\nThose lousy wisps had it coming. Let them wander where they will, as long as it isn't near me.\n_Rewards:_\n112 platinum, 5 gold\nExperience",
    },
    {
      id = "6161",
      title = "From Grace",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Aislinn",
      loc = nil,
      triggers = {
        "Hail, Aislinn",
        "Information?",
        "_Quests_",
        "information",
        "indulge",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\n**Who:**\n- Aislinn [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Related Creatures:**\n- a defiled paladin of Marr [npc=42249]\n- a disgraced paladin of Marr [npc=42255]\n- a forlorn cleric of Marr [npc=42263]\n- a rotting paladin of Marr [npc=42285]\n- an unchaste cleric of Marr [npc=42302]\n- an undead cleric of Marr [npc=42304]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 29 09:47:46 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with a Halfling named Aislinn ( map) in the Chapterhouse of the Fallen. She is found at the zone-in from the Commonlands (southeastern-most room on the main floor)._\nYou say, 'Hail, Aislinn'\nAislinn says 'I see another one of you sniveling adventurers has found your way into The Chapterhouse. I suppose you assume I have some bit of [information] for you?'\nYou say, 'Information?'\nAislinn says 'You'll have to [indulge] me if you want me to point you in the right direction.'\nYou have been assigned the task 'From Grace'.\nAislinn dislikes those that have fallen in the name of Marr, and would rather not be forced to walk amongst their corpses.\n\n---\n\nPut an end to some of the undead paladins or clerics of Marr 0/10 (Chapterhouse of the Fallen)\nReturn to Aislinn 0/1 (Chapterhouse of the Fallen)\nYou say, 'Hail, Aislinn'\n'One death is never enough for those tainted by the light. Even when stripped of their flesh the stench of purity still clings to their bones.' Aislinn pauses 'But I suppose you must feel pity for them, no? Consider what you did either a justice to me or to the fallen. Whatever helps you sleep at night.'\n_Rewards:_\n112 platinum, 5 gold\nExperience",
    },
    {
      id = "6162",
      title = "Steel and Bone",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Aislinn",
      loc = nil,
      triggers = {
        "Hail, Aislinn",
        "Information?",
        "Aislinn",
        "_Quests_",
        "information",
        "indulge",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\n**Who:**\n- Aislinn [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Related Creatures:**\n- a decaying knight [npc=42248]\n- a disgraced knight [npc=42254]\n- a fallen knight [npc=42259]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 29 09:47:49 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with a Halfling named Aislinn ( map) in the Chapterhouse of the Fallen. She is found at the zone-in from the Commonlands (southeastern-most room on the main floor)._\nYou say, 'Hail, Aislinn'\nAislinn says 'I see another one of you sniveling adventurers has found your way into The Chapterhouse. I suppose you assume I have some bit of [information] for you?'\nYou say, 'Information?'\nAislinn says 'You'll have to [indulge] me if you want me to point you in the right direction.'\nYou have been assigned the task 'Steel and Bone'.\nAislinn seems to be under the impression that the knights that oversee The Chapterhouse are not to be trusted. Destroy 10 knights that are stationed throughout The Chapterhouse.\n\n---\n\nKill 10 knights 0/10 (Chapterhouse of the Fallen)\nReturn to Aislinn 0/1 (Chapterhouse of the Fallen)\nYou say, 'Aislinn'\nTrust me when I say never before have I created something that has inspired even the slightest bit of fear me until now. The re-animates are supposed to be lifeless toys, but they almost seemed to enjoy their time with a blade.\n_Rewards:_\n112 platinum, 5 gold\nExperience",
    },
    {
      id = "6163",
      title = "Rotting Sentries",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Aislinn",
      loc = nil,
      triggers = {
        "Hail, Aislinn",
        "Information?",
        "_Quests_",
        "information",
        "indulge",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\n**Who:**\n- Aislinn [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Related Creatures:**\n- a hungry ghoul [npc=42268]\n- a loathsome ghoul [npc=42269]\n- a revolting ghoul [npc=42284]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 29 09:47:51 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with a Halfling named Aislinn ( map) in the Chapterhouse of the Fallen. She is found at the zone-in from the Commonlands (southeastern-most room on the main floor)._\nYou say, 'Hail, Aislinn'\nAislinn says 'I see another one of you sniveling adventurers has found your way into The Chapterhouse. I suppose you assume I have some bit of [information] for you?'\nYou say, 'Information?'\nAislinn says 'You'll have to [indulge] me if you want me to point you in the right direction.'\nYou have been assigned the task 'Rotting Sentries'.\nAislinn has found yet another thing she dislikes, ghouls in this instance, and once again would like you to take care of it for her. Kill 10 ghouls that walk the corridors of The Chapterhouse.\n\n---\n\nKill 10 ghouls 0/10 (Chapterhouse of the Fallen)\nReturn to Aislinn 0/1 (Chapterhouse of the Fallen)\nYou say, 'Hail, Aislinn'\nWhy ghouls this time? Have you seen that look on their face? Terrifying. Why do you think I hide back here? Just take this and let us not talk about them anymore.\n_Rewards:_\n112 platinum, 5 gold\nExperience",
    },
    {
      id = "6164",
      title = "Of the Fallen",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Aislinn",
      loc = nil,
      triggers = {
        "Hail, Aislinn",
        "Information?",
        "_Quests_",
        "information",
        "indulge",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\n**Who:**\n- Aislinn [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Related Creatures:**\n- a mindless zombie [npc=42274]\n- a shambling zombie [npc=42287]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 29 09:47:54 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with a Halfling named Aislinn ( map) in the Chapterhouse of the Fallen. She is found at the zone-in from the Commonlands (southeastern-most room on the main floor)._\nYou say, 'Hail, Aislinn'\nAislinn says 'I see another one of you sniveling adventurers has found your way into The Chapterhouse. I suppose you assume I have some bit of [information] for you?'\nYou say, 'Information?'\nAislinn says 'You'll have to [indulge] me if you want me to point you in the right direction.'\nYou have been assigned the task 'Of the Fallen'.\nAislinn needs some of the excess zombies taken care of.\nKill 10 zombies that lurk through the halls of The Chapterhouse.\n\n---\n\nKill 10 zombies 0/10 (Chapterhouse of the Fallen)\nReturn to Aislinn 0/1 (Chapterhouse of the Fallen)\nYou say, 'Hail, Aislinn'\nDon't get me wrong, I love a good zombie as much as any other Necromancer, but there is such a thing as too much of a good thing. Thank you for taking care of the mess for me, I enjoy making them but prefer to stay as far away from their jaws as possible.\n_Rewards:_\n112 platinum, 5 gold\nExperience",
    },
    {
      id = "6165",
      title = "Baldrik the Insane",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Aliskar Darkbane",
      loc = { y = 20.0, x = 140.0, z = 0.0 },
      triggers = {
        "Hail, Aliskar Darkbane",
        "Help?",
        "I will find him",
        "Hail, Baldrik",
        "I need more!",
        "help",
        "find him",
        "more",
      },
      items_required = {
      },
      rewards = {
        { id = 107670, name = "Chunk of Stone", type = "item" },
        { id = 109136, name = "Glass Jar", type = "item" },
        { id = 106515, name = "Shiny Thing", type = "item" },
        { id = 106478, name = "Sir Braveblade", type = "item" },
        { id = 109180, name = "Slime-Filled Jar", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\n**Who:**\n- Aliskar Darkbane [npc=41351]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Quest Items:**\n- Chunk of Stone [item=107670]\n- Glass Jar [item=109136]\n- Shiny Thing [item=106515]\n- Sir Braveblade [item=106478]\n- Slime-Filled Jar [item=109180]\n**Related Creatures:**\n- Baldrik [npc=42309]\n- Oozles [npc=42317]\n- a starving basilisk [npc=42291]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 29 09:47:56 2012\nModified: Tue Jan 21 03:34:28 2025 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This task begins with Aliskar Darkbane ( map) in the Chapterhouse of the Fallen (location 20, 140, 0, in the large room just west of the zone-in from Shard's Landing)._\n_Pre-Requisites:_\n\\- Level 85\n\\- No tasks\nYou say, 'Hail, Aliskar Darkbane'\nAliskar Darkbane says 'Hail, adventurer. Can you spare a moment to [help] me?'\nYou say, 'Help?'\nAliskar Darkbane says 'As you can imagine, being undead has its downsides and some of us can handle it better than others. For example, my poor brother Baldrik is not handling it well at all. The years of undeath he has suffered has severely taken a toll on him. Once a proud paladin, he has been reduced to a gibbering madman. I try to help him when I can, but it has become too dangerous to venture down below to visit him ever since the Burning Dead recently started to appear in great numbers. If you can find it in your heart, please try to [find him] and see if he needs anything.'\nYou say, 'I will find him'\nAliskar Darkbane says 'Thank you. Return to me if you are successful with this task, and I will make sure you are rewarded for your efforts.'\nYou have been assigned the task 'Baldrik the Insane'.\nAliskar Darkbane has asked you to take pity on his brother Baldrik who has gone insane. Seek out Baldrik and see if you can help him.\n\n---\n\n**Map Locs**\nP -804.4173, 218.3315, -247.5711, 0, 127, 0, 3, Baldrik\\_(Quest\\_NPC)\nP -389.2286, -164.9582, -251.3892, 0, 127, 0, 3, Oozies\\_(Quest\\_Mob)\n\n---\n\nSpeak with Baldrik 0/1 (Chapterhouse of the Fallen)\n_Baldrik ( map) is found in the zone's lowest section - the caverns. Location: -220, 800, -245. This is in the northeast corner of the caverns' southwestern-most room._\nYou say, 'Hail, Baldrik'\nBaldrik shouts at you. 'Oozles! Where has Oozles gone?! You must find Oozles and return him to me!' Baldrik throws as glass jar to you. 'That is Oozles' home. Put him in there! Don't lose jar. If you lose jar, I have [more] though.'\nYou say, 'I need more!'\nBaldrik throws a glass jar to you.\n_You receive a Glass Jar._\nCapture Oozles 0/1 (Chapterhouse of the Fallen)\n_Find Oozles (an ooze -- map) in the lowest level of the zone (the caverns, at about 165, 390, -250). Fight it to 25% and right-click the jar._\nGive the Slime-Filled Jar to Baldrik 0/1 (Chapterhouse of the Fallen)\nSpeak with Baldrik 0/1 (Chapterhouse of the Fallen)\nCollect shiny things for Baldrik 0/6 (Chapterhouse of the Fallen)\n_These appear as ground spawns in the lowest part of the zone (the caverns). They appear as yellow icons on the ground and are prelootable._\nGive the shiny things to Baldrik 0/6 (Chapterhouse of the Fallen)\nSpeak with Baldrik 0/1 (Chapterhouse of the Fallen)\nLoot a Chunk of Stone from a basilisk 0/1 (Chapterhouse of the Fallen)\nGive the Chunk of Stone to Baldrik 0/1 (Chapterhouse of the Fallen)\nSpeak with Baldrik 0/1 (Chapterhouse of the Fallen)\nFind Sir Braveblade 0/1 (Chapterhouse of the Fallen)\n_This is a doll that drops from oozes, basilisks, beetles, and tentacle terrors._\nReturn Sir Braveblade to Baldrik 0/1 (Chapterhouse of the Fallen)\nSpeak with Baldrik 0/1 (Chapterhouse of the Fallen)\nSpeak with Aliskar Darkbane 0/1 (Chapterhouse of the Fallen)\n_Rewards:_\n225 platinum\nExperience (3 AAs)",
    },
    {
      id = "6166",
      title = "Feeding Time",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Grimbus",
      loc = { y = 475.0, x = 185.0, z = -220.0 },
      triggers = {
        "Hail, Grimbus",
        "Work?",
        "Injury?",
        "I can help",
        "What problems?",
        "What strange things?",
        "work",
        "injury",
      },
      items_required = {
      },
      rewards = {
        { id = 107663, name = "Bag of Unwanted Body Parts", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Chapterhouse of the Fallen [zone=874]\n**Who:**\n- Grimbus [npc=41352]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Time Limit:** | 06:00:00\n**Quest Items:**\n- Bag of Unwanted Body Parts [item=107663]\n**Related Creatures:**\n- a bloody disposal crate [npc=42242]\n- a deteriorating disposal crate [npc=42250]\n- a dilapidated disposal crate [npc=42252]\n- a dusty disposal crate [npc=42256]\n- a filthy disposal crate [npc=42260]\n- a gory disposal crate [npc=42266]\n- a reanimated bodypart [npc=42428]\n- a scavenging basilisk [npc=42427]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 29 09:48:00 2012\nModified: Tue Feb 20 00:30:12 2024 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a shared task (1-6 players) that begins with Grimbus ( map) in the Chapterhouse of the Fallen. He is found at location 475, 185, -220 (in the lowest part of the zone; the far north end of the underground river)._\n_Note: This task locks as soon as you obtain it._\n_Pre-Requisites:_\n\\- Level 85\n\\- No tasks\nYou say, 'Hail, Grimbus'\nGrimbus says 'I don't get many visitors down here. Are you looking for some [work]? If you have a strong stomach, I may just have something for you.'\nYou say, 'Work?'\nGrimbus says 'I was once part of the Burning Dead necromancers. Somehow I managed to anger the wrong person and as punishment, I was sent down here to dispose of unwanted body parts that are left over from necromantic experiments. It's a hard, lonely life, but I keep going. Lately though I have been unable to attend to my duties due to an [injury].'\nYou say, 'Injury?'\nGrimbus says 'As I was placing some body parts into the disposal crates one day, a basilisk, attracted to the smell of the rotting flesh, appeared and attacked me. I got away, but not without one of my legs being turned to stone. I can barely walk now. Hopefully it will heal on its own, but in the meantime, I am unable to dispose of the body parts. Do you think you can [help]? I don't own much, but I will find something to reward you for your help.'\nYou say, 'I can help'\nGrimbus says 'Thank you. The job itself isn't too difficult. Simply pick up the bags of unwanted body parts that are thrown down the chute into the river and place them into one of the disposal crates. Slimes will appear and dissolve both the crates and the body parts. They are rather efficient cleaners. There are a couple of [problems] you will need to keep an eye out for however.'\nYou say, 'What problems?'\nGrimbus says 'Sometimes scavenging basilisks appear to try to eat the body parts. As you can probably understand, I hate basilisks. Kill any that may show up. Also, that strange, purple shard here in the caverns can sometimes cause [strange things] to happen.'\nYou say, 'What strange things?'\nGrimbus says 'On occasion, some of the body parts will be affected by the shard's dark magic and come to life. Mostly it's severed hands, which is just plain creepy. Kill any of those that may appear as well. The last thing I need is a bunch of severed hands crawling all over me when I try to sleep. You best be on your way. The body parts are really starting to pile up. Good luck.'\nYou have been assigned the task 'Feeding Time'.\nGrimbus wants you to help him dispose of some unwanted body parts by collecting them near and in the river and then placing them in various disposal crates.\nPlace a Bag of Unwanted Body Parts into the dusty, bloody, gory, filthy, dilapidated, and deteriorating disposal crates. Kill any scavenging basilisks that may appear when you place the body parts into the crates. Kill any reanimated body parts that may appear when you place the body parts into the crates.\n\n---\n\n_Bags of Unwanted Body Parts spawn all over the lower caverns (many ground spawns in the water). You will need six of these._\nPlace a Bag of Unwanted Body Parts into the dusty disposal crate 0/1 (Chapterhouse of the Fallen)\n_This crate is located in the area almost due west of Grimbus. You will have \"a scavenging basilisk\" to contend with here._\nPlace a Bag of Unwanted Body Parts into the bloody disposal crate 0/1 (Chapterhouse of the Fallen)\n_This crate is located in the area northwest of Grimbus. You will have a reanimated body part to contend with here._\nPlace a Bag of Unwanted Body Parts into the gory disposal crate 0/1 (Chapterhouse of the Fallen)\n_This crate is located in the large area southwest of Grimbus. You will have \"a scavenging basilisk\" to contend with here._\nPlace a Bag of Unwanted Body Parts into the filthy disposal crate 0/1 (Chapterhouse of the Fallen)\n_This crate is located in the room east of the dilapidated crate. You will have a reanimated body part to contend with here._\nPlace a Bag of Unwanted Body Parts into the dilapidated disposal crate 0/1 (Chapterhouse of the Fallen)\n_This crate is located in the west-central room of the zone's lower caverns. You will have \"a scavenging basilisk\" to contend with here._\nPlace a Bag of Unwanted Body Parts into the deteriorating disposal crate 0/1 (Chapterhouse of the Fallen)\n_This crate is located in the southwest room of the zone's lower caverns. You will have a reanimated body part to contend with here._\nKill scavenging basilisks 0/3 (Chapterhouse of the Fallen)\nKill reanimated body parts 0/3 (Chapterhouse of the Fallen)\n_The above two steps update as you complete the task._\nSpeak with Grimbus 0/1 (Chapterhouse of the Fallen)\n_Rewards:_\n150 platinum\nExperience (2 AAs)",
    },
  },
}
