-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Cobalt Scar (cobaltscar)
-- Total Quests: 5
-- ============================================================================

return {
  zone = "cobaltscar",
  zone_name = "Cobalt Scar",
  quests = {
    {
      id = "10123",
      title = "Just a Good Ol' Fashioned Love Song",
      exp = "27",
      exp_name = "Claws of Veeshan",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Adella Undertow",
      loc = { y = 1780.0, x = 1773.0, z = -20.0 },
      triggers = {
        "sirens",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Cobalt Scar [CoV]\n**Who:**\n- Adella Undertow [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 113\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n**Related Creatures:**\n- a siren beguiler - CoV [npc=56126]\n- a siren enticer - CoV [npc=56127]\n- a siren harmonic - CoV [npc=56128]\n- a siren muse - CoV [npc=56129]\n- a siren songstress - CoV [npc=56130]\n- an alluring siren - CoV [npc=56136]\n**Related Quests:**\n- Mercenary of Cobalt Scar (10 Points) [quest=10274]\n**Era:** | !Claws of Veeshan\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Oct 27 23:14:24 2020\nModified: Tue Dec 5 05:21:04 2023 | | **Claws of Veeshan Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\n**Prerequisite Quests:** None.\nYou can obtained this quest from Adella Undertow in Cobalt Scar at 1780, 1773, -20 on the west side of the old sirens grotto, first underwater tunnel to the left as you drop down into the water from the old entrance. She is on the find tool CTRL F.\nYou say, 'sirens'\nYou have been assigned the task 'Just a Good Ol` Fashioned Love Song'.\nAdella Undertow says, 'Oh, I'm so happy to have heard you say that! The sirens have been using this confusion to enslave even more of the ulthorks and use them to terrorize the othmir. Those cutesy wootsy, ittle wittle sweety weeties are too cute to be terrorized by these monsters! Please! You must save the cute wittwe cweatews! Ahem, I mean, the othmir.'\n\n---\n\n**Task Window Text:** Adella Undertow needs the sirens dealt with in Siren's Grotto.\n1\\. Silence the Sirens 0/8 Cobalt Scar\nKill 8 sirens.\n\n---\n\nReward(s):\n?\n**Submitted by:** Gidono",
    },
    {
      id = "10119",
      title = "Seashells by the Seashore",
      exp = "27",
      exp_name = "Claws of Veeshan",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Provisioner Tarka - CoV",
      loc = { y = 95.0, x = -1427.0, z = 85.0 },
      triggers = {
        "Hail, Provisioner Tarka",
        "Why are you **busy**?",
        "Why do you need seashells?",
        "help",
        "fish",
        "trouble",
      },
      items_required = {
      },
      rewards = {
        { id = 140237, name = "Large-Sized Restless Seashell", type = "item" },
        { id = 140227, name = "Medium-Sized Restless Seashell", type = "item" },
        { id = 140065, name = "Small-Sized Restless Seashell", type = "item" },
        { id = 140065, name = "Sized Restless Seashells", type = "item" },
        { id = 140227, name = "Sized Restless Seashells", type = "item" },
        { id = 140237, name = "Sized Restless Seashells", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Cobalt Scar [CoV]\n**Who:**\n- Provisioner Tarka - CoV [npc=56147]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 113\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Large-Sized Restless Seashell [item=140237]\n- Medium-Sized Restless Seashell [item=140227]\n- Small-Sized Restless Seashell [item=140065]\n**Related Quests:**\n- Partisan of Cobalt Scar (10 Points) [quest=10275]\n**Era:** | !Claws of Veeshan\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Oct 27 22:11:02 2020\nModified: Tue Dec 5 05:21:04 2023 | | **Claws of Veeshan Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\n**Prerequisite Quests:** None\nThis task can be obtained from Provisioner Tarka in Cobalt Scar on the eastern beach at 95, -1427, 85\nYou say, 'Hail, Provisioner Tarka'\nProvisioner Tarka scoffs at your approach, 'Go Hail yourself someplace else. Can't you see I'm [ **busy**]?'\nYou say, 'Why are you **busy**?'\nProvisioner Tarka says, 'Our supplies of [ **seashells**] and [fish] are running low and I am trying to collect more while avoiding [trouble].'\nYou say, 'Why do you need seashells?'\nProvisioner Tarka snorts loudly, then makes a sound in their throat which sounds like they are gathering the contents that they just snorted, then spits on the ground next to them. 'Seashells come in all sizes and are useful for making many things. Small shells are great for armor, medium shells are perfect for dishes, and large shells make excellent building material. Alas, with the restless ice and the increase of activity around here I haven't been able to keep up with demand. Do you think you could [ **help**] me? Or are you here to waste my time?'\nYou say, 'help'\nYou have been assigned the task 'Seashells by the Seashore'.\nProvisioner Tarka says, 'Good, now do me a favor and get me as many of the shells as you can. If you find any pretty ones, collect those as well. Those we like to give to Chi to make as jewelry to sell to folks in Qeynos.'\n\n---\n\n**Task Window Text:** Provisioner Tarka is in need of some seashells that are located in the Cobalt Scar, amongst the restless ice. Search the shorelines for small seashells. Sirens and Neriads collect medium seashells, presumably for fashion. Large seashells are collected by the ulthorks and used as tools typically, but because they have been most taken by the ice, they have no need for the shells.\n01. Collect Small Seashells 0/10 Cobalt Scar\n\n\n\nSmall-Sized Restless Seashells [item=140065] are ground spawns along the edge of the beach.\n\n\n\n\nPut this in your cobaltscartwo\\_1.txt map file to find the seashells. They have a fast respawn.\n\n\n\n\nP 1284.6469, -722.9568, 58.3549, 0, 0, 0, 3, Seashell\n\n\nP 1244.3484, -104.3261, 66.6861, 0, 0, 0, 3, Seashell\n\n\nP 1139.2122, 117.8028, 57.1468, 0, 0, 0, 3, Seashell\n\n\nP 1006.1047, 483.0217, 65.6015, 0, 0, 0, 3, Seashell\n\n\nP 905.2831, 634.2330, 68.2489, 0, 0, 0, 3, Seashell\n\n\nP 741.7615, 681.4498, 58.4044, 0, 0, 0, 3, Seashell\n\n\nP 127.1435, 711.8127, 58.4113, 0, 0, 0, 3, Seashell\n\n\nP -62.6435, 770.9047, 58.5624, 0, 0, 0, 3, Seashell\n\n\nP -746.9645, 746.4496, 72.5468, 0, 0, 0, 3, Seashell\n\n\nP -365.8491, 719.4419, 58.7903, 0, 0, 0, 3, Seashell\n\n\nP -215.9385, 731.5972, 57.0404, 0, 0, 0, 3, Seashell\n\n\nP 301.1350, 758.4293, 56.7220, 0, 0, 0, 3, Seashell\n\n\nP 495.6748, 709.1525, 56.8961, 0, 0, 0, 3, Seashell\n\n\nP 1085.7750, 336.5470, 62.5018, 0, 0, 0, 3, Seashell\n\n\nP 1541.0151, -474.4386, 59.4009, 0, 0, 0, 3, Seashell\n\n\nP 1532.2341, -640.0653, 59.2248, 0, 0, 0, 3, Seashell\n\n\nP 1099.3217, -852.7788, 57.1871, 0, 0, 0, 3, Seashell\n05. Collect Medium Seashells 0/8 Cobalt Scar\n\n\n\n\n\nLoot Medium-Sized Restless Seashells [item=140227] from sirens and neriads.\n09. Collect Large Seashells 0/3 Cobalt Scar\n\n\n\nLoot Large-Sized Restless Seashells [item=140237] from Ulthorks.\n13. Deliver Small Seashells to Provisioner Tarka 0/10 Cobalt Scar\nProvisioner Tarka's voice is absolutely saturated with sarcasm, 'Great work! You picked up stuff on the ground! Nobody else but you could have done that!'\n19. Deliver Medium Seashells to Provisioner Tarka 0/8 Cobalt Scar\nProvisioner Tarka says, 'Braved the sirens and the mermaids did you? Well you're either brave or stupid, but I sure do appreciate you being either. Thank you.'\n25. Deliver Large Seashells to Provisioner Tarka 0/3 Cobalt Scar\n\n\n\nProvisioner Tarka says, 'I used to think all you adventurers are the same but having been helped by one of you has changed my views on you all. Thanks for this, it's good to know that there are some of you I can trust. Be safe out there and remember to cover your ears if you hear a siren's call, you don't want to end up like the ulthorks.'\n\nYour task 'Seashells by the Seashore' has been updated.\n_Tarka is pleased with your findings and will put thes shells you have gathered to good use. Chi will be pleased when she gets to sell them by the seashore in Qeunos._\nYou received 425 platinum.\nYou have gained 25 ability point(s)!\n\n---\n\nReward(s):\nExp or AA\n425 platinum\n**Submitted by:** GOMN",
    },
    {
      id = "10120",
      title = "Catch and Release",
      exp = "27",
      exp_name = "Claws of Veeshan",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Aisel Sharpnose - CoV",
      loc = { y = -883.0, x = -402.0, z = 93.0 },
      triggers = {
        "Hail, Aisel Sharpnose",
        "How can I...",
        "Just use your words to speak with me",
        "_Quests_",
        "next",
        "speaking",
      },
      items_required = {
        { name = "Aisel the note back 0/1 Cobalt Scar", count = 1 },
        { name = "Aisel the note he handed to you", count = 1 },
        { name = "Aisel his Fishing Lure Back 0/1 Cobalt Scar", count = 1 },
        { name = "Aisel a Tackle Box 0/1 Cobalt Scar", count = 1 },
        { name = "the Gift to Stella 0/1 Cobalt Scar", count = 1 },
        { name = "them to someone else", count = 1 },
      },
      rewards = {
        { id = 140224, name = "Aisel's Favorite Fishing Lure", type = "item" },
        { id = 140222, name = "Aisel's Favorite Fishing Pole", type = "item" },
        { id = 140226, name = "Aisel's Gift for Stella", type = "item" },
        { id = 140221, name = "Aisel's Note", type = "item" },
        { id = 140223, name = "Aisel's Second Note", type = "item" },
        { id = 17449, name = "Tackle Box", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Cobalt Scar [CoV]\n**Who:**\n- Aisel Sharpnose - CoV [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 113\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Aisel's Favorite Fishing Lure [item=140224]\n- Aisel's Favorite Fishing Pole [item=140222]\n- Aisel's Gift for Stella [item=140226]\n- Aisel's Note [item=140221]\n- Aisel's Second Note [item=140223]\n- Tackle Box [item=17449]\n**Related Creatures:**\n- Stella Pidginsee - CoV [npc=56150]\n- a coldwater shark - CoV [npc=56110]\n- a shallow thresher - CoV [npc=56124]\n**Related Quests:**\n- Partisan of Cobalt Scar (10 Points) [quest=10275]\n**Era:** | !Claws of Veeshan\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Oct 27 22:29:06 2020\nModified: Tue Dec 5 05:21:04 2023 | | **Claws of Veeshan Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\n**Prerequisite Quests:** None.\nYou can obtain this quest from Aisel Sharpnose on the southern beach at -883, -402, 93. He is on the find tool CTRL F.\nYou say, 'Hail, Aisel Sharpnose'\nAisel Sharpnose acknowledges your approach and looks in your direction in order to make themselves very clear with what they are about to say [next].\nYou say, ' How can I...'\nAisel Sharpnose interrupts your speaking to wave their hands around in a very deliberate matter, as if trying to communicate. You notice their face is also contorting with expressions as they continue to try and communicate without [speaking].\nYou say, ' Just use your words to speak with me'\nYou have been assigned the task 'Catch and Release'.\nAisel Sharpnose appears frustrated and very agitated. You are not quite sure what you did to offend them, but he hands you a note.\nYou are given Aisel's Note\n\n---\n\n**Task Window Text:** Aisel Sharpnose is an othmir of many words, just not many that are spoken. He appears to be planning something important to him and would like your help acquiring the item needed to do so.\nPaper is hard to come by in the Cobalt Scar, make sure that you sive Aisel back the note. It would be very rude for you not to.\n1\\. Give Aisel the note back 0/1 Cobalt Scar\nGive Aisel the note he handed to you.\nUpon hand in:\nYour task 'Catch and Release' has been updated.\nAisel Sharpnose accepts the note back and gives you a soft smile, as if to say \"I hope you do better than the others\".\n2\\. Find Aisle's Fishing pole 0/6 Cobalt Scar\n**Task Window Text:** Aisel believes that the fishing pole was last in the possession of his friend, who has presumably taken by the restless ice. Try to find the pole amongst the restless othmir.\nThe fishing pole will appear on your cursor after killing 6 restless othmir.\n_You have been given: Aisel's Favorite Fishing Pole_\n_That must have been Aisel's friend. Unfortunately, he was correct, but you were able to retrieve the fishing pole. This should be returned to Aisel immediately._\nYour task 'Catch and Release' has been updated.\n3\\. Return the fishing pole back to the right owner 0/1 Cobalt Scar\nReturn the pole back to Aisel.\n_You have been given: Aisel's Second Note_\n_Your task 'Catch and Release' has been updated._\n_Aisel Sharpnose seems shocked that you have returned. As you approach, he quickly scribbles something on the back side of the original note with a piece of charcoal._\n4\\. Locate Aisel's Fishing Lure 0/5 Cobalt Scar\n_The lure was presumably used to catch sharks, search the consents of the sharks stomachs in Cobalt Scar and see if you can locate the lure. The tackle box can be found at any fishing tackle vendors, assuming they are not sold out._\nThe Lure (Aisel's Favorite Fishing Lure) will appear on your cursor after killing 5 sharks.\n_You have been given: Aisel's Favorite Fishing Lure_\n_The last shark had a fishing lure with the letters ASL scratched onto it. This must be Aisel's lure!_\n5\\. Give Aisel his Fishing Lure Back 0/1 Cobalt Scar\n_Aisel is patiently waiting for the lure and tackle box in Cobalt's Scar._\nHand the lure back to Aisel.\n6\\. Give Aisel a Tackle Box 0/1 Cobalt Scar\n_Aisel is patiently waiting for the lure and tackle box in Cobalt's Scar._\nPurchase a tackle box from any vendor in-game and hand this in to Aisel\n_You have been given: Aisel's Gift for Stella_\nYour task 'Catch and Release' has been updated.\nAisel Sharpnose takes the tacklebox and the lure that you gave him and turns his back to you. You can see that he is fiddling with something. As you attempt to peek over his shoulder he notices, you and blocks your vision. After a few moments he turns and beams a huge smile at you. He then hands you a gift box with the name \"Stella Pidginsse\" on it and points to the west.\n7\\. Give the Gift to Stella 0/1 Cobalt Scar\n_The items were never meant for Aisel, he was going to give them to someone else, find Stella somewhere in the Cobalt Scar and deliver the gift to her._\nGive the gift to Stella Pidginsee on the far west side of the zone.\nYour task 'Catch and Release' has been updated.\n_Stella really enjoyed her gift from Aisel. The sweet gesture did not go unnoticed, you feel better having been a part of that exchange._\nYou receive 425 platinum.\nYou have gained 25 ability point(s)!\nStella Pidginsee takes the package with a curious and surprised look as she reads the tag and smiles warmly. She opens her hand and places the tips of the fingers against her chi. She drops her hand forward, palm up and mouths the words 'Thank you'.\n\n---\n\nReward(s):\n425 platinum\nExp or 25 AA at level 115\n**Submitted by:** GOMN",
    },
    {
      id = "10121",
      title = "Unchained Melody",
      exp = "27",
      exp_name = "Claws of Veeshan",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "De`ess Al'coda - CoV",
      loc = { y = 2387.0, x = 1475.0, z = 31.0 },
      triggers = {
        "Hail, De`ess Al`coda",
        "Food...Source?",
        "I would love to get rid of them for you?",
        "_Quests_",
        "food source",
        "get rid",
        "sic",
      },
      items_required = {
        { name = "them to her as proof of your deeds", count = 1 },
        { name = "them to her", count = 1 },
        { name = "the earring to Merien Gilfoyle", count = 1 },
        { name = "the necklace back to you", count = 1 },
      },
      rewards = {
        { id = 140239, name = "Al'coda's Seashell Earrings", type = "item" },
        { id = 140235, name = "Functional Othmir Fishing Pole", type = "item" },
        { id = 140240, name = "Sea-Soaked Necklace", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Cobalt Scar [CoV]\n**Who:**\n- De`ess Al'coda - CoV [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 113\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Al'coda's Seashell Earrings [item=140239]\n- Functional Othmir Fishing Pole [item=140235]\n- Sea-Soaked Necklace [item=140240]\n**Related Creatures:**\n- Merien Gilfoyle [npc=56444]\n**Related Quests:**\n- Partisan of Cobalt Scar (10 Points) [quest=10275]\n**Era:** | !Claws of Veeshan\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Oct 27 22:41:34 2020\nModified: Tue Dec 5 05:21:04 2023 | | **Claws of Veeshan Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\n**Prerequisite Quests:** None.\nYou can obtain this quest from De`ess Al`coda in what was Siren's Grotto at 2387, 1475, 31. She is on the find tool CTRL F.\nYou say, 'Hail, De`ess Al`coda'\nDe`ess Al`coda continues to hum as you approach her, only to be startled by your words, 'Oh, wow I wasn't expecting visitors.' Her voice is as soothing as you would expect a siren's to be, you remember that there is a reason that sailors fear them. 'Well, I can't very well turn away a guest! Welcome, and since you are here, would you mind helping us? There is a problem we are having with our [food source]\nYou say, ' Food...Source?'\nDe`ess Al`coda continues to speak, her voice is welcomed to your ears, especially after spending all of this time in dealing with the restless ice, 'Yes my friend, you see, the othmir out in the bay have been overfishing the bay, and because of this we have been slowly running out of our stock. Would you be a dear and [get rid] of them for us?'\nYou say, ' I would love to get rid of them for you?'\nYou have been assigned the task 'Unchained Melody'.\nDe`ess Al`coda brushes your cheek and gently taps the side of your head in approval, \"Good Wood Elf, bring me their fishing poles to prove that you have done this. The othmir don't go anywhere without them, I'll be waiting here for your return.' You feel the need to do anything that De'ess Al'coda says, she makes you feel welcomed and it is a feeling you realize you haven't felt for a while. As you turn to leave, she says, 'Oh, and if you happen to find two small seashells, you will want to collect those as well, I need them for a special project.'\n\n---\n\n**Task Window Text:** You recall only De'ess Al'coda's face and voice but cannot recall much about what she was asking you to do. You resist the urge to go back to her and stay in her company, but what was it she wanted again?\nOh, right! The siren's food supply has been running out due to overfishing from the othmir, she needed you to take away their fishing poles. Unfortunately for the othmir, they don't part with their poles easily, you may have to take it from their cold, dead hands. You also remember that she asked for two small seashells\n01. Take the fishing poles away from the othmir 0/5 Cobalt Scar\n\n\n\nKill non-restless Othmir until you collect 5 Functional Othmir Fishing Pole\n05. Deliver the poles to De'ess 0/5 Cobalt Scar\n\n\n\n_Of course! Now that you have the fishing poles, she wanted you to give them to her as proof of your deeds. You don't want to keep her waiting!_\n\n\n\nDe`ess Al`coda looks more stunning than when you first approached her, you aren't sure what is different, but you are relieved she was still here, waiting for you. 'Oh, my goodness! Look at you, you poor little thing. You went through all this trouble having to deal with those hideous creatures for me? Bless your heart!'\n09. Deliver the seashells to De`ess 0/2 Cobalt Scar\n\n\n\n_That's right! You almost forgot you collected those seashells for her! She will be happy when you give them to her._\n\n\n\n\n\nCollect 2 Small-Sized Restless Seashells from the beach and deliver to De`ess..\n\n\n\n\nPut this in your cobaltscartwo\\_1.txt map file to find the seashells. They have a fast respawn.\n\n\n\n\nP 1284.6469, -722.9568, 58.3549, 0, 0, 0, 3, Seashell\n\n\nP 1244.3484, -104.3261, 66.6861, 0, 0, 0, 3, Seashell\n\n\nP 1139.2122, 117.8028, 57.1468, 0, 0, 0, 3, Seashell\n\n\nP 1006.1047, 483.0217, 65.6015, 0, 0, 0, 3, Seashell\n\n\nP 905.2831, 634.2330, 68.2489, 0, 0, 0, 3, Seashell\n\n\nP 741.7615, 681.4498, 58.4044, 0, 0, 0, 3, Seashell\n\n\nP 127.1435, 711.8127, 58.4113, 0, 0, 0, 3, Seashell\n\n\nP -62.6435, 770.9047, 58.5624, 0, 0, 0, 3, Seashell\n\n\nP -746.9645, 746.4496, 72.5468, 0, 0, 0, 3, Seashell\n\n\nP -365.8491, 719.4419, 58.7903, 0, 0, 0, 3, Seashell\n\n\nP -215.9385, 731.5972, 57.0404, 0, 0, 0, 3, Seashell\n\n\nP 301.1350, 758.4293, 56.7220, 0, 0, 0, 3, Seashell\n\n\nP 495.6748, 709.1525, 56.8961, 0, 0, 0, 3, Seashell\n\n\nP 1085.7750, 336.5470, 62.5018, 0, 0, 0, 3, Seashell\n\n\nP 1541.0151, -474.4386, 59.4009, 0, 0, 0, 3, Seashell\n\n\nP 1532.2341, -640.0653, 59.2248, 0, 0, 0, 3, Seashell\n\n\nP 1099.3217, -852.7788, 57.1871, 0, 0, 0, 3, Seashell\n\n\n\n\nYour task 'Unchained Meolody' has been updated.\n\n\n_You have been given: Al`coda's Seasshell Earrings_\n\n10. Deliver the earrings to Merien Gilfoyle 0/1 Cobalt Scar\n\n\n\n_This time she asked you to simply deliver something to a mermaid somewhere in the grotto. You must find her and make the delivery. The sooner it is complete, the quicker you can go back to De`ess Al`coda._\n\n\n\nGive the earring to Merien Gilfoyle, who is right up the water tunnel above De`ess.\n\n\n\n\nYour task 'Unchained Melody' has been updated.\n\n\n\n\nMerien Gilfoyle looks astonished that you approached her without harming her, she appears to keep a cautious eye on you while you hand her the earrings. 'Oh!' she exclaims while looking relieved. 'De`ess sent you! That makes me feel much better about you finding me. Thank you for bringing these to me, they are fabulous! There is the problem with the deal her and I made, I seemed to have misplaced it.' She looks embarrassed, 'You see,' she gives another awkward laugh, 'anything that gets misplaced in the grotto can either be found amongst the othmir, the sharks, or the mimics. In this case, I believe the mimics have the necklace. You may need to search a few before you find it. They will be outside the cave entrance to the grotto. Bring me back the necklace to make sure you have the right one, those mimics will eat anything that is shiny.'\n14. Find the necklace amongst the mimics 0/5 Cobalt Scar\n\n\n\n_Merian.Gilfoyle, a mermaid who is in contact with De`ess, wants to replay the favor for the earrings by getting De`ess a trinket that was stolen by one of the mimics in Cobalt Scar._\n\n\n\nAfter killing the 5th Mimic (little animated boxes on the bed of the sea floor), a \"Sea-Soaked Necklace\" appears on your cursor.\n\n\n\n\n_You have been given: Sea-Soaked Necklace_\n18. Return the necklace to Merien 0/1 Cobalt Scar\n\n\n\n_Merien will want to inspect the necklace to ensure it is the correct one. Return the necklace to her._\n\n\n\nMerien Gilfoyle says, 'Perfect! That's the one! Here...' She hands back the necklace, 'Take it to De`ess, she's been waiting too long for it's return. She said it is a family heirloom and asked me to locate it for her, but I'm no fighter and those mimics bite hard. She will be happy to see it's returned [sic].\n\n\n\n\nShe will give the necklace back to you.\n22. Return the Necklace to De'ess 0/1 Cobalt Scar\n\n\n\n_De`ess is waiting for her necklace._\n\n\n\nDe`ess Al`coda entire [sic] complexion changes the moment you hand her the necklace. Her eyes are sunken, her skin looks darker, and she appears almost sinister. There is no way this is the same De`ess Al`coda that you met before, that isn't possible, there's no way she would be anything but breathtaking! As you try to get her attention, she hisses fiercely at you and for a moment you feel pure terror. You think it's best if you leave this creature and go find the real De`ess Al`coda.\n\n\n\n\nYour task 'Unchained melody' has been updated.\n\n\n\n\n_It's abundantly clear that De`ess is no longer in need of your services. Though you wonder if you will ever get to hear her voice again._\n\n\n\nYou gain 425 platinum.\n\n\nYou have gained 25 ability point(s)!\n\n\n---\n\nReward(s):\nEXP or AA\n425 platinum.\n**Submitted by:** GOMN",
    },
    {
      id = "10154",
      title = "The Crusaders",
      exp = "27",
      exp_name = "Claws of Veeshan",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Watcher Sprin - CoV",
      loc = { y = -775.0, x = -460.0, z = 78.0 },
      triggers = {
        "Hail, Watcher Sprin",
        "Othmir",
        "small",
        "ready",
        "_Raid and Mission_",
        "large",
      },
      items_required = {
        { name = "it a try anyhow", count = 1 },
      },
      rewards = {
        { id = 140013, name = "Restless Mark", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Cobalt Scar [CoV]\n**Who:**\n- Watcher Sprin - CoV [ _Raid and Mission_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 113\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Expedition\n**Quest Goal:**\n- Advancement\n- Money\n**Time Limit:** | 06:00:00\n**Related Creatures:**\n- Charayan the Crusader - CoV [npc=56369]\n- Grendish the Crusader - CoV [npc=56370]\n- Jortreva the Crusader - CoV [npc=56371]\n- Lord Yelinak - CoV [npc=56372]\n- Susarrak the Crusader - CoV [npc=56373]\n**Related Quests:**\n- Hero of Skyshrine (10 Points) [quest=10267]\n**Era:** | !Claws of Veeshan\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Fri Oct 30 14:46:19 2020\nModified: Tue Dec 5 05:21:04 2023 | | **Claws of Veeshan Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\n**Prerequisite Quests:** None.\nYou can obtain this mission from Watcher Sprin in Cobalt Scar. You can find him at /loc -775, -460, 78 on the south beach and he is on the find tool CTRL F.\nYou say, 'Hail, Watcher Sprin'\nWatcher Sprin raises an eyebrow at you, a surprisingly aggressive gesture, 'Hmm... a Wood Elf. I have been asked to keep an eye out for strangers and see if I can direct them into that dragon temple thing. Last I heard the dragons are probably responsible for this whole mess.' He gestures out to the frozen sea. 'That isn't helping these poor [Othmir] any, along with all the death and wandering corpses. So, if you are interested in stopping this, I can show you a way in. I imagine that any of them hideous wurms you find in there will try to stop you. I suggest a [large] force if you can muster the help, but if you only have a [small] number of allies, you can give it a try anyhow.'\nYou say, 'Othmir'\nWatcher Sprin says, 'They live mostly off fish. There isn't that much open water and so there aren't that many fish out there, they tell me. So, I keep my eye out for wandering dangers that I can cut to bits to make their lives a little easier.'\nYou say, 'small'\nWatcher Sprin says, 'Well, best of luck to you. Them dragons are evil and dangerous. I can send you to your death whenever you are [ready].'\nYou have been assigned the task 'The Crusaders'.\nYou say, 'ready'\nWatcher Sprin says, 'Off you go.'\nLOADING, PLEASE WAIT...\nYou have entered Skyshrine.\n\n---\n\n**Task Window Text:** Yelinak must know how to stop the restless ice. You will need to defeat the crusaders that have been stationed as guards around his lair.\nYou can speak to Watcher Sprin in the instance to leave the instance. He is located right where you port in.\n1\\. Defeat the Crusaders 0/1 Skyshrine\n2\\. Loot the Dragon's Horde 0/1 Skyshrine\n\n---\n\nReward(s):\n177 platinum 8 silver 3 copper\nYou gain experience!\n45 Restless Marks\n**Submitted by:** Gidono\n- Restless Mark [item=140013]",
    },
  },
}
