-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for The Eastern Wastes (eastwastestwo)
-- Total Quests: 9
-- ============================================================================

return {
  zone = "eastwastestwo",
  zone_name = "The Eastern Wastes",
  quests = {
    {
      id = "10149",
      title = "The Call (Group Mission)",
      exp = "27",
      exp_name = "Claws of Veeshan",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Essedera - CoV",
      loc = nil,
      triggers = {
        "Hail, Essedera",
        "visit",
        "small",
        "ready",
        "Hail, a worried golem",
        "Hail, Sivar",
        "choose to interfere",
        "_Raids and Mission_",
      },
      items_required = {
      },
      rewards = {
        { id = 140285, name = "Chaos Infused Velium Shard", type = "item" },
        { id = 140312, name = "Fire Infused Velium Shard", type = "item" },
        { id = 140270, name = "Frost Infused Velium Shard", type = "item" },
        { id = 140288, name = "Lightning Infused Velium Shard", type = "item" },
        { id = 140013, name = "Restless Mark", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Eastern Wastes [ToV]\n**Who:**\n- Essedera - CoV [ _Raids and Mission_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 112\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Experience\n- Loot\n- Money\n**Time Limit:** | 05:08:00\n**Quest Items:**\n- Chaos Infused Velium Shard [item=140285]\n- Fire Infused Velium Shard [item=140312]\n- Frost Infused Velium Shard [item=140270]\n- Lightning Infused Velium Shard [item=140288]\n**Related Zones:**\n- Sleeper's Tomb [CoV]: The Call (Group)\n**Related Creatures:**\n- Cargalia - CoV [npc=56362]\n- Honvar - CoV [npc=56366]\n- Melalafen - CoV [npc=56363]\n- Sivar - CoV [npc=56365]\n- Vulak`Aerr - CoV [npc=56364]\n- a bulky chest - CoV [npc=56449]\n- a confused caretaker - CoV [npc=56456]\n- a slimy golem - CoV [npc=56460]\n**Era:** | !Claws of Veeshan\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Fri Oct 30 02:00:37 2020\nModified: Sun Aug 25 16:08:40 2024 | | **Claws of Veeshan Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\n**Prerequisite Quests:** None.\nYou can obtain this mission from Essedera [npc=56441] in The Eastern Wastes (ToV). You can find her at near the sleeper's tomb area. She is on the find tool CTRL F.\nYou say, 'Hail, Essedera'\nEssedera says, 'Well, Minasu, you must be one of those adventurers.' The drake \\*\\*\\*\\*\\* its head and leans toward you. 'What is it that you wish of me? Never mind, there is no longer a need to be coy, nor is there time for it. If you have come here to, um, [visit] with Vulak'Aerr, I can assist you. If not, then you should be on your way.'\nYou say, 'visit'\nEssedera says, 'Under any other circumstance I would object and offer you no assistance at all. But times are different at the moment, and one must do what needs to be done, no matter the consequences. If you come with a [small] group I can easily assist you on entry to the tomb. If you bring a [larger] group I will assist you, but it will be challenging to my magic.'\nYou say, 'small'\nEssedera says, 'So be it. This is a sad day for me and my kin, but this is what I must do. I will be [ready] when you are.'\nYou have been assigned the task 'The Call'.\nYou say, 'ready'\nEssedera says, 'I admit that I find it impossible to wish you luck.'\nLOADING, PLEASE WAIT...\nYou have entered Sleeper's Tomb: The Call.\n\n---\n\n**Task Window Text:** The source of the restless ice may be hidden in the Sleeper's Tomb. If you can, find the source and stop it.\nYou say, 'Hail, a worried golem'\nA worried golem says, 'I will not blame you if you would like to [leave]. And if you foolishly wish to [retreat] back up into the tomb, I can assist you with that as well.'\nIf you say retreat, you will be teleported up a couple of levels, to the area where zone trash mobs are, to kill for instance collectibles, otherwise the main mission awaits on the 4 platforms ahead of you.\nYou say, 'Hail, Sivar'\nSivar says, 'You should leave this place. [What] goes on here now is not a matter for your kind. We have no quarrel with you, unless you [choose to interfere].'\nYou say, 'choose to interfere'\nSivar says, 'It is as we expected. Then you shall die!'\nA roar comes from the four corners of the room, each of different timbre, but all in large volume. - Event starts here\n1\\. Stop whatever is causing the restless ice. 0/1 The Sleeper's Tomb\n> **Task Window Text:** You sense a power at the heart of the Tomb. Find that power and shut it down.\nThe 4 Protector Dragons\nThese 4 Dragons can be fought in ANY order. The event allows time to meditate between dragon kills. The crystals will always activate in a clockwise rotation, starting at Melalafen's platform always, and progressing clockwise to yellow, then clear, then blue. This order always progresses in this fashion, even after dragons are slain. Doing so you can predict which Dragon's crystal aura will activate next. Each dragon must be fought on their platform or they will tether, summon, and strip your buffs.\nYour afflictions have been stripped.\nYour afflictions have been stripped.\nSivar begins casting Balance of the Nameless.\nCrystal Aura rotation order - Red, Yellow, Clear, Blue.\nThe central gem begins to glow. - 10 Second Warning\nThe crystal over the central platform glows and sends power into the red crystal. - Red Dragon goes inactive for 10 seconds, AE aura activates\nThese 2 emotes repeat for each of the 4 platforms, and always in a clockwise progression. The AEs that activate are as follows.\nReflected Fire \\- Red Gem/Melalafen's Platform\nReflected Sickness \\- Yellow Crystal/Honvar's Platform\nReflected Lightning \\- Clear Crystal/Sivar's Platform\nReflected Freeze \\- Blue Crystal/Cargalia's Platform\nEach AE has a 10% chance to apply an additional debuff of its own. However they are completely avoidable if you run out of the aura when the crystal activates, and the dragon goes inactive.\nMelalafen - Fire Dragon, Flame Resistant\nMelalafen rears back and flexes his wings - Right Wing Swing, Left Wing Swing. These can be avoided by staying in front or back of Melalafen.\nMelalafen takes a deep breath - Melalafen casts Velium Boosted Lava Breath, a frontal AE for 120320 dmg, but which also grants the players a Fire Infused Velium Shard [item=140312]\nMelalafen\nCargalia - Ice Dragon, Cold Resistant\nCargalia takes a deep breath - Cargalia casts Velium Boosted Frost Breath, a frontal AE for 120320 dmg, but which also grants the players a Frost Infused Velium Shard [item=140270]\nCargalia raises her tail - Tail Swing. This can be avoided by staying to the front or sides.\nSivar - Grey Dragon, Magic Resistant\nSivar roars a call to allies! - Summons A confused caretaker (gargoyle add)\nSivar takes a deep breath - Sivar casts Velium Boosted Lightning Breath, a frontal AE for 120320 dmg, but which also grants the players a Lightning Infused Velium Shard [item=140288]\nHonvar - Green Dragon, Poison/Disease Resistant\nHonvar takes a deep breath - Honvar casts Velium Boosted Chaos Breath, a frontal AE for 120320 dmg, but which alsos grants the players a Chaos Infused Velium Shard [item=140285]\nHonvar's claws scrape the ground - Claw Slash This can be avoided by staying to the sides or back.\nYou have time to meditate and recover mana between kills. However, once the fourth protector is slain, you must go DIRECTLY to Vulak Aerr in the center platform, or the event will reset after 30 seconds.\nAs the last guardian dragon falls, the barrier protecting the central platform fades away. - Engage Vulak Aerr in 30 seconds, or the event resets.\nVULAK`AERR - The Final Hurdle\nAt this point you must use all your burn abilities and kill Vulak`Aerr as quickly as possible. Thankfully he has far fewer HP than the previous 4 dragons. But Vulak has the same Wing and Tail AE's as Melalafen and Cargalia. Thankfully, if you are quick, he won't get to cast them much.\nPower flows out from the central gem to the smaller gems. Something forms under one of them.\nWhen you see this emote, time is running out, and several golems will start converging on the center from the 4 outer platforms. Kill him quickly, or the golems will reach the center and explode, each with a different AE.\nYou have slain Vulak`Aerr!\nEven though Vulak`Aerr is dead, you are still in danger from the golems that are converging at the center. Quickly, run underneath the central gem and touch it to de-activate the gem and spawn the Chest.\nThe magical device thrums loudly for a moment, and just stops spinning.\nThe moment you touch the device you sense a presence. All around this presence is the deepest cold, colder than you have ever imagined. The presence seems to be floating in pure silence. As you become aware of it, it becomes aware of you. As it begins to turn its attention to you a deep dread overcomes you and you pull away. The moment you flee the presence the device shuts down. Whatever that thing was, you know that it was beyond your comprehension.\nYour task 'The Call' has been updated.\n2\\. Open the chest and claim your reward. 0/1 The Sleeper's Tomb\nEven with the chest spawned, the golems will remain active, so quickly open the chest to despawn all the golems and auras permanently.\n_The restless ice will slowly fades [sic] now that the device is off. You hope._\nYour task 'The Call' has been updated.\nYou have received a replay timer for 'The Call': 0d:5h:8m remaining.\n\n---\n\nReward(s):\n177 platinum 8 silver 3 copper\nExperience\n45 Restless Marks\n**Submitted by:** Minasu\n- Restless Mark [item=140013]",
    },
    {
      id = "9734",
      title = "Oh, its you again!",
      exp = "26",
      exp_name = "Torment of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Emli Widgetton",
      loc = { y = -2497.0, x = -2381.0, z = -1.0 },
      triggers = {
        "Hail, Emli Widgetton",
        "**vampire blood**",
        "**help**",
        "terrified",
      },
      items_required = {
      },
      rewards = {
        { id = 137833, name = "Vial of Frozen Vampire Blood", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Eastern Wastes [ToV]\n**Who:**\n- Emli Widgetton [npc=54985]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n**Quest Items:**\n- Vial of Frozen Vampire Blood [item=137833]\n**Related Zones:**\n- The Tower of Frozen Shadow [ToV]\n**Related Creatures:**\n- a maid of honor [npc=55609]\n- an undead bridesmaid [npc=55025]\n- an undead dancer [npc=55026]\n- an undead musician [npc=55027]\n**Related Quests:**\n- Mercenary of The Tower of Frozen Shadow (10 Points) [quest=9801]\n**Era:** | !Torment of Velious\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Oct 24 20:16:26 2019\nModified: Sat Nov 1 10:28:53 2025 | | **Torment of Velious Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nThis task starts with Emli Widgetton [npc=54985] in the southeaster corner of The Eastern Wastes at -2497, -2381, -1, she is on the Find tool (Ctrl+F).\nYou say, 'Hail, Emli Widgetton'\nEmli Widgetton says, 'Gidonorog!? I haven't seen you in since Mearatas! Apparently the jann didn't appreciate my...aggressive diplomatic tactics and I have been reassigned here for further research of the restless ice. I sure am glad to see you're still in one piece and by the gods I could use your expertise at this moment. I was tasked to collect chilled [ **vampire blood**] from the vampires within the tower. I am in need of these samples to see how the restless ice has been corrupting the undead. The vampires here appear to be affected differently than the other undead within and my constituents want a closer look at how they are being corrupted. I just have one small problem...I'm [terrified] of vampires.'\nYou say, ' **vampire blood**'\nEmli Widgetton says, 'The vampires in that tower still need to imbibe in vitae but the restless ice doesn't affect their blood like it would any other creature. While other creatures, the blood becomes solid, the vampire's blood remains viscous. Theoretically speaking, this means that the blood is immune to the effects of what is haunting Velious. I plan to use this research to create a way to stop the restless ice to make sure it doesn't spread anymore than it currently has. So, will you do me a favor and collect some of the blood for me? It would really [ **help**] me with my work.'\nYou say, ' **help**'\nYou have been assigned the task 'Oh, its you again!'.\nEmli Widgetton says, 'Oh thank Brell! Head inside and dispatch a few of the vampires and bring me samples of their blood. We can get a much better situation as to what is going on inside with this information. You may have to convince them to show themselves, they like to remain bats when they are in the tower. If you find bats, you'll more than likely find vampires!'\n\n---\n\n_Emli has asked you to provide her with chilled vampire blood for her tests._\n01. Destroy Vampires 0/7 (The Tower of Frozen Shadow)\nHead to floor 6 within Tower of Frozen Shadows and kill the required vampires. Someone in the group will need to have the appropriate amount of keys to get the group there.\n08. Deliver Vials of Vampire Blood to Emli Widgetton 0/7 (The Eastern Wastes)\nWhile killing vampires, loot the Vials of Frozen Vampire Blood [item=137833].\nUpon turning in the seven vials of blood to Emli:\nYour task 'Oh, It's You Again!' has been updated.\n_Emli lifts the vials to her eye level and looks at the light passing through them._\nYou receive 5 gold.\nYou receive 212 platinum.\n\n---\n\nReward(s):\n212 platinum, 5 gold\n**Submitted by:** Gidono\n- 12 platinum 5 gold",
    },
    {
      id = "9736",
      title = "The Last of the Storm Boars",
      exp = "26",
      exp_name = "Torment of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Yealdin Stormfell",
      loc = { y = -2394.0, x = -2373.0, z = -1.0 },
      triggers = {
        "Hail, Yealdin Stormfell",
        "seeking",
        "assist them",
        "aid",
        "The soldiers are dead.",
        "_Quest_",
      },
      items_required = {
      },
      rewards = {
        { id = 137729, name = "Insignia of the Storm Boar", type = "item" },
        { id = 137727, name = "Terse Note", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Eastern Wastes [ToV]\n**Who:**\n- Yealdin Stormfell [ _Quest_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Time:** | 360\n**Level:** | 100\n**Maximum Level:** | 130\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Money\n**Time Limit:** | 06:00:00\n**Quest Items:**\n- Insignia of the Storm Boar [item=137729]\n- Terse Note [item=137727]\n**Related Creatures:**\n- a storm boar soldier [npc=55595]\n- a wandering corpse [npc=55594]\n- an undying dire wolf [npc=55596]\n**Related Quests:**\n- Partisan of The Eastern Wastes (10 Points) [quest=9795]\n**Era:** | !Torment of Velious\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Oct 24 20:51:44 2019\nModified: Thu Jan 15 02:07:49 2026 | | **Torment of Velious Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can get this shared task from Yealdin Stormfell in The Eastern Wastes in the southeastern corner of the zone at -2394, -2373, -1, he is on the find tool (CTRL F).\nTip: If you failed a step, everyone in the group needs to go back to Yealdin and hail him and say \"Try Again\"\nYou say, 'Hail, Yealdin Stormfell'\nYealdin Stormfell says, 'If you have come to threaten me there is no need. I have sworn to protect this place in exchange for refuge. The coldain have accepted my oath, as they should, and allow me to remain. As much as I might prefer to be out [seeking] my warband, I must remain here.'\nYou say, 'seeking'\nYealdin Stormfell says, 'I was separated from my soldiers when a horde of undead Ry'Gorr assaulted our fortress. I managed to fight my way out and was pursued here by a small group of monsters. In times like these it seems that even the oldest enemies must assist each other. The coldain aided me in defeating them and I have been here since. I am certain that my soldiers have held their posts and I would like to [assist them].'\nYou say, 'assist them'\nYealdin Stormfell says, 'It seems that if the coldain and I can remain civil under the circumstances, perhaps I can trust you to aid me and go to the fort and assist my war band. We living must band together if we are to survive. If you can [aid] my soldiers and return them here, we will be better able to guard this place, which is important for all of us.'\nYou say, 'aid'\nYealdin Stormfell says, 'A reasonable decision. Go to the fortress and provide some assistance and certainly my soldiers will be able to escape.'\nYou have been assigned the task 'The Last of the Storm Boars'.\n\n---\n\n_Yealdin Stormfell has dedicated himself to defending the coldain wall until whatever is causing the upheaval here. However, he was forced to leave some companions in the giant fortress and is now worried about them. He has asked you to see if you can find them and bring them here._\n_Head to the giant fort. Yealdin believes that his soldiers are still defending the fortress. He wants you to talk to them and bring them to him._\n1\\. Go to the giant fort and find where the Storm Boars are. 0/1 (The Eastern Wastes)\n_An enormous restless dead orc leaps into the room and attacks._\nHead to the building on the south and just inside, \"a wandering corpse\" (orc style monster) will spawn. Kill for task update.\nYour task 'The Last of the Storm Boars' has been updated.\n2\\. Find a clue about where the Storm Boars have gone 0/1 (The Eastern Wastes)\nLoot the _Terse Note_ from the just-slain orc.\nYour task 'The Last of the Storm Boars' has been updated.\n3\\. Head to the great bridge 0/1 (The Eastern Wastes)\nHead east--just north of the Crystal Caverns zone line--towards the two Coldain huts.\n_Around location: 382, -1757, -25_, 3x \"A wandering corpse\" will spawn.\nYour task 'The Last of the Storm Boars' has been updated.\n4\\. Defeat the undead orcs 0/1 (The Eastern Wastes)\nKill the three undead orcs that spawned.\nYour task 'The Last of the Storm Boars' has been updated.\n5\\. Pick up the insignia ring as it surely indicates that the Storm Boars came this way 0/1 (The Eastern Wastes)\nLoot an _Insignia of the Storm Boar_ from a wandering corpse's corpse.\n6\\. Find the lost Storm Boars somewhere near the great bridge 0/1 (The Eastern Wastes)\n3 wolves and 2 giants will spawn under the south side of the bridge.\nKill the 3 wolves then go to the spot on the bridge at /way -153, -2462, 44\n7\\. Defeat the undead dire wolves surrounding the Storm Boars 0/1 (The Eastern Wastes)\nKill the 3 wolves. The wolves can be singled pull without aggroing one another.\nThis will update after you go to the spot on the bridge.\nYour task 'The Last of the Storm Boars' has been updated.\n8\\. Defeat the Storm Boars and gather proof that you found them 0/1 (The Eastern Wastes)\nKill the 2 giants.\nLoot an _Insignia of the Storm Boar_ from a storm boar soldier's corpse.\nYour task 'The Last of the Storm Boars' has been updated.\n9\\. Deliver 1 Terse Note to Yealdin 0/1 (The Eastern Wastes)\nYealdin Stormfell says, 'Their plan makes some tactical sense, as expected. Did you eventually find them?'\nYour task 'The Last of the Storm Boars' has been updated.\n10\\. Deliver 2 Insignia of the Storm Boar to Yealdin 0/2 (The Eastern Wastes)\nYealdin Stormfell says, 'Please, tell me what happened to my soldiers. It is important to me to know what their fate was.'\nYour task 'The Last of the Storm Boars' has been updated.\n11\\. Tell Yealdin what happened to his soldiers 0/1 (The Eastern Wastes)\nYou say, 'The soldiers are dead.'\nYealdin Stormfell hardens his face, 'There was nothing to be done if they were already dead. Certainly they died a worthy death with many corpses piled around them. I thank you for this information.'\nYour task 'The Last of the Storm Boars' has been updated.\n\n---\n\nReward(s):\nYou receive 425 platinum.\n**Submitted by:** Gidono\n- 425 platinum",
    },
    {
      id = "9738",
      title = "Giants with a Big Heart",
      exp = "26",
      exp_name = "Torment of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Reclamation Officer Borminn",
      loc = { y = -2426.0, x = -2292.0, z = -2.0 },
      triggers = {
        "Hail, Reclamation Officer Borminn",
        "fight",
        "What can I do about the undead?",
        "What do you mean by",
        "hearts",
        "_Quests_",
        "undead",
        "fueling",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Status: Incomplete**\n\nQuest Started By: | Description:\n**Where:**\n- The Eastern Wastes [ToV]\n**Who:**\n- Reclamation Officer Borminn [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n**Related Creatures:**\n- a corrupted giant [npc=55360]\n- a reinforced giant [npc=54973]\n- an exiled sentry [npc=54977]\n**Related Quests:**\n- Mercenary of The Eastern Wastes (10 Points) [quest=9794]\n**Era:** | !Torment of Velious\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Oct 24 21:19:30 2019\nModified: Tue Dec 5 05:21:04 2023 | | **Torment of Velious Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can get this solo task from Reclamation Officer Borminn in The Eastern Wastes at -2426, -2292, -2 in the southeastern corner of the zone. he is on the Find tool (Ctrl+F).\nYou say, 'Hail, Reclamation Officer Borminn'\nReclamation Officer Borminn says, 'Finally, it's good to see someone here who can [fight] as hard as one of us. I'm not going to sweeten this story, the wastes are looking more grim than usual, and the living are going to need all of the help we can get. I'm the reclamation officer of this camp. It's nice to meet you, but we will have to eschew the normal pleasantries, as we have bigger issues happening at the moment. I hope you brought a source of heat because it's going to be a long night.'\nYou say, 'fight'\nReclamation Officer Borminn says, 'You may have noticed that we are up to our necks in denizens who refused to journey to the plane of their gods. Because of this, we need to find strong willed individuals such as yourself to take up the mantle and assist the living with culling the ranks of the [undead]. We are not sure what is going on around here, but we are pretty sure it has something to do with that accursed tower.'\nYou say, ' What can I do about the undead?'\nReclamation Officer Borminn says, 'We need to reduce the numbers of undead in the Eastern Wastes, but these undead are far more tenacious than ones we have encountered before. The only thing any of us can guess is that something happening an that cursed tower is causing them to become harder to kill... again. While they become only mildly inconvenienced when we destroy their physical form, we can make lasting change by destroying what is [fueling] their return.'\nYou say, ' What do you mean by 'fueling'?'\nReclamation Officer Borminn says, 'Each monster we must face will require a different method of destruction. Some must have their [essence] removed and obliterated by special magics, some need to have their frozen [hearts] shattered. I have associates with the ability to destroy these things, but first we must acquire them.'\nYou say, 'hearts'\nYou have been assigned the task 'Giants with a Big Heart'.\nReclamation Officer Borminn says, 'The hearts of the corrupted giants are protected within their bodies. Unfortunately, breaking through their tough skin will be more difficult than usual because their bodies are being reinforced by the restless ice. Luckily, once you destroy their husks, the hearts will shatter on their own. Good luck \\_\\_\\_\\_\\_, you're going to need it.'\n\n---\n\n_The Eastern Wastes is being overrun by corrupted giants who are being empowered by the restless ice in the area. Destruction of their frozen hearts is the only way to destroy them, but getting to the hearts is the real issue. Their numbers need to be culled or they could easily take over the wastes, with more joining their ranks every moment._\n1. Destroy Restless Giants 0/6 (Eastern Wastes)\n\nKill corrupted giants and exiled sentry for updates.\n\n\n\nKill any 6 giants within the zone for credit.\n\n---\n\nReward(s):\n106 platinum 2 gold 5 silver\n**Submitted by:** Gidono\n- 106 Platinum, 2 Gold, 5 Silver",
    },
    {
      id = "9740",
      title = "Icebound Avatar",
      exp = "26",
      exp_name = "Torment of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Iceweaver Sjeon",
      loc = { y = -1359.0, x = 2106.0, z = 5.0 },
      triggers = {
        "Hail, Iceweaver Sjeon",
        "assistance",
        "Will",
        "small",
        "_Raids and Mission_",
        "large",
        "ready",
      },
      items_required = {
      },
      rewards = {
        { id = 137538, name = "Froststone Ducat", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Eastern Wastes [ToV]\n**Who:**\n- Iceweaver Sjeon [ _Raids and Mission_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Expedition\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Time Limit:** | 06:00:00\n**Related Zones:**\n- Kael Drakkel [ToV]: Icebound Avatar\n**Related Creatures:**\n- Icebound Avatar of War [npc=55604]\n- a minion of Sullon [npc=55613]\n- a minion of Vallon [npc=55614]\n- a restless guardian of Zek [npc=55615]\n- a restless spectator [npc=55617]\n- an animated axe [npc=55616]\n- an icebound chest [npc=55603]\n**Related Quests:**\n- All Credit to Rallos (10 Points) [quest=9907]\n- Bend the Knee (Group) (10 Points) [quest=9908]\n**Era:** | !Torment of Velious\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Oct 24 22:35:46 2019\nModified: Tue Dec 5 05:21:04 2023 | | This group mission starts out with Iceweaver Sjeon outside of Kael in The Eastern Wastes at -1359, +2106, +5.\nYou say, 'Hail, Iceweaver Sjeon'\nIceweaver Sjeon says, 'Hello, tiny one. You may just be the creature I need to speak with. King Tormax ordered me to leave Kael and seek [assistance].'\nYou say, 'assistance'\nIceweaver Sjeon says, 'It is to our shame that we need assistance, but the truth cannot be denied. Our city is being overrun by these,' he pauses, seeking the words he needs and failing to find them. 'This horrible magic is claiming our fallen kin. It is hard for us to strike them. We revere our fallen and seeing them walking again has cause some to hesitate. That hesitation has cost many lives. I would beg you to come and speak with our King. He wishes to speak with some of the so-called heroes of Norrath. You look like one of those. [Will] you come with me?'\nYou say, 'Will'\nIceweaver Sjeon says, 'Good. In order to teleport you into the keep I must know if you plan to bring a [large] or [small] host.'\nYou say, 'small'\nIceweaver Sjeon says, 'I can send you to see King Tormax in when you are [ready].'\nYou have been assigned the task 'Icebound Avatar'.\n\n---\n\n_King Tormax is in need of help. The king's ability to defend against the undead giants was dramatically reduced when the icebound avatar of war destroyed the protective magical barrier. Tormax is extremely concerned that the statue to his god, the one that has been inhabited by an avatar of that same god, has been animated by this strange restless ice. He would like you to stop the statue, even if it means destroying it._\nDefeat the Icebound Avatar of War. 0/1 Kael Drakkel\nThe Avatar is in the Arena. Hail him to trigger the event.\nAt various points, he will emote \" **Avatar of War shouts that \\_\\_\\_ must bend the knee**\". That player has to duck or he will die. The player can stand once the Avatar emotes, 'The Avatar of War nods, accepting the subservience of those that gave it.'\nAt 60% the Avatar teleports to the north room.\nThe Avatar of War changes the rules and chooses a new field of battle!\nWith his soldiers defeated, it is now possible to defeat the Avatar.\nAdds keep spawning, kill them and get the Avatar down.\nOpen the chest and claim your reward 0/1 Kael Drakkel\nOpen an icebound chest [npc=55603].\n\n---\n\nReward(s):\n283 platinum 3 gold 3 silver 3 copper\nYou gain experience!\n23 Froststone Ducats\n\n---\n\nKeal Mission - ToV - 3 Cheeve - YouTube\nTap to unmute\nKeal Mission - ToV - 3 Cheeve bronut norotaku\nbronut norotaku41 subscribers\nWatch on\n**Submitted by:** Gidono\n- Froststone Ducat [item=137538]",
    },
    {
      id = "9760",
      title = "Stubborn, Even in Death",
      exp = "26",
      exp_name = "Torment of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Reclamation Officer Borminn",
      loc = nil,
      triggers = {
        "Hail, Reclamation Officer Borminn",
        "fight",
        "What can I do about the undead?",
        "What do you mean by",
        "essence",
        "The coldain are corrupted?",
        "_Quests_",
        "undead",
      },
      items_required = {
      },
      rewards = {
        { id = 137906, name = "Restless Coldain Essence", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Eastern Wastes [ToV]\n**Who:**\n- Reclamation Officer Borminn [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n**Quest Items:**\n- Restless Coldain Essence [item=137906]\n**Related Creatures:**\n- a restless Coldain [npc=54974]\n**Related Quests:**\n- Mercenary of The Eastern Wastes (10 Points) [quest=9794]\n**Era:** | !Torment of Velious\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sun Nov 10 04:35:49 2019\nModified: Tue Dec 5 05:21:04 2023 | | **Torment of Velious Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nTo get this task, speak with Reclamation Officer Borminn (CTRL F) in the coldain camp in the far southwest corner of Eastern Wastes.\nYou say, 'Hail, Reclamation Officer Borminn'\nReclamation Officer Borminn says, 'Finally, it's good to see someone here who can [fight] as hard as one of us. I'm not going to sweeten this story, the wastes are looking more grim than usual, and the living are going to need all of the help we can get. I'm the reclamation officer of this camp. It's nice to meet you, but we will have to eschew the normal pleasantries, as we have bigger issues happening at the moment. I hope you brought a source of heat because it's going to be a long night.'\nYou say, 'fight'\nReclamation Officer Borminn says, 'You may have noticed that we are up to our necks in denizens who refused to journey to the plane of their gods. Because of this, we need to find strong willed individuals such as yourself to take up the mantle and assist the living with culling the ranks of the [undead]. We are not sure what is going on around here, but we are pretty sure it has something to do with that accursed tower.'\nYou say, ' What can I do about the undead?'\nReclamation Officer Borminn says, 'We need to reduce the numbers of undead in the Eastern Wastes, but these undead are far more tenacious than ones we have encountered before. The only thing any of us can guess is that something happening an that cursed tower is causing them to become harder to kill... again. While they become only mildly inconvenienced when we destroy their physical form, we can make lasting change by destroying what is [fueling] their return.'\nYou say, ' What do you mean by 'fueling'?'\nReclamation Officer Borminn says, 'Each monster we must face will require a different method of destruction. Some must have their [essence] removed and obliterated by special magics, some need to have their frozen [hearts] shattered. I have associates with the ability to destroy these things, but first we must acquire them.'\nYou say, 'essence'\nReclamation Officer Borminn says, 'Collecting these will be no small feat. if you manage to destroy any [banshees] or [coldain], you may be able to collect what remains of their spirit from the bodies. Now, some of the recently turned coldains or banshees won't have enough essence to gather, which is a good thing as I see it. This means we won't have to worry about them coming back to bother us anymore.'\nYou say, ' The coldain are corrupted?'\nYou have been assigned the task 'Stubborn, Even in Death'.\nReclamation Officer Borminn grumbles expletives under his breath 'I was afraid you would ask about them. Look, we coldain are stubborn while they are alive, but it seems that the restless ice has made them even more stubborn in death. We have sent out scouting parties, but they failed to return. If on your adventures you happen to run into any, kill their husks and bring me their essences. I will contact my friends to be sure that the spirits are properly destroyed.'\n\n---\n\n_The coldain hunting parties that were sent to scout the Eastern Wastes failed to return. Upon further reconnaissance, it was discovered that they too have been lost to the restless ice. In order to ensure their final death, they need to be killed and their essences taken in order to be destroyed. Reclamation Officer Borminn has contacts that can assist with this, but you are being asked to bring the essences of the fallen back to him so that he can free them._\n01. Kill Restless Coldains and collect their essences. 0/6 (The Eastern Wastes)\n\n\n\nSeek out Restless Coldains, they are plentyfull towards the Ry`Gorr Mines/Crystal Caverns zone-line area and kill them to collect their essences.\n\n\n\n\nYour task 'Stubborn, Even in Death' has been updated.\n05. Deliver Restless Coldain Essences to Reclamation Officer Borminn 0/6 (The Eastern Wastes)\n\n\n\nReturn to Borminn and turn-in the looted essences for task update.\n\n\n\n\nYour task 'Stubborn, Even in Death' has been updated.\n\n---\n\nReward(s):\n106 Platinum, 2 Gold, 5 Silver\n**Submitted by:** Gidono\n- 106 Platinum, 2 Gold, 5 Silver",
    },
    {
      id = "9766",
      title = "You Can't Go Back Home",
      exp = "26",
      exp_name = "Torment of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Grunak",
      loc = nil,
      triggers = {
        "Hail, Grunak, Ry`Gorr Refugee",
        "help",
        "guards",
        "Why are you here?",
        "Orctooth",
        "Hail, a Coldain reclaimer",
        "orctooth",
        "Clan.",
      },
      items_required = {
        { name = "Orctooth to Grunak", count = 1 },
        { name = "the 7 necklaces", count = 1 },
        { name = "him back the torch 0/1 (The Eastern Wastes)", count = 1 },
        { name = "the Ry`Gorr Blessed Torch to Grunak", count = 1 },
      },
      rewards = {
        { id = 138530, name = "Orctooth", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Eastern Wastes [ToV]\n**Who:**\n- Grunak [ _Ry'gorr Refugee_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Time:** | 360\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Time Limit:** | 06:00:00\n**Quest Items:**\n- Orctooth [item=138530]\n- Ry`Gorr Blessed Sack [item=137701]\n- Ry`Gorr Blessed Torch [item=137724]\n- Ry`Gorr Tooth Necklace [item=137700]\n**Related Creatures:**\n- Orctooth [npc=54992]\n- Restless Ry`Gorr [npc=55344]\n- Ry`Gorr Corpse [npc=55345]\n- an infected orc [npc=55356]\n**Related Quests:**\n- Partisan of The Eastern Wastes (10 Points) [quest=9795]\n**Era:** | !Torment of Velious\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 3 21:01:50 2019\nModified: Tue Dec 5 05:21:04 2023 | | **Torment of Velious Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\nIf you don't know the Orchish language, just say \"Orctooth\" to Grunak to get the quest.\nYou say, 'Hail, Grunak, Ry`Gorr Refugee'\nGrunak, Ry`Gorr Refugee stares longingly into the fire, eventually looking up and catching your gaze. His eyes appear to be welling over, which is unusual for an orc but you get the feeling this is not an ordinary orc you're dealing with. 'You, Half Elf, come closer. Need [help].\nYou say, 'help'\nGrunak, Ry`Gorr Refugee says, in Orcish, 'Lost Orctooth. You find Orctooth. Orctooth not here anymore. Maybe [guards] know where.'\nYou say, 'guards'\nGrunak, Ry`Gorr Refugee says, in Orcish, 'Guard take prisoner. No can look for Orctooth. Say too dangerous. Say need to be watched. Have nothing. All gone. I stay [here]. You go find Orctooth.'\nYou say, ' Why are you here?'\nGrunak, Ry`Gorr Refugee says, in Orcish, 'Left home after ice attack. Am prisoner. Oracles and mystics no help. Nothing left home. This better than home. Need new home. Ry`Gorr clan out there, somewhere. No other orcs here. Ask guard. Maybe [Orctooth] know where Ry`Gorr gone.'\nYou say, 'Orctooth'\nGrunak, Ry`Gorr Refugee says, in Orcish, 'Orctooth missing. Need to find Orctooth. Ask where Orctooth is. Might know.'\nYou have been assigned the task 'You Can't Go Back Home'.\n\n---\n\n1\\.  Ask the guards if they have seen a kitten named Orctooth 0/1 (The Eastern Wastes)\nSay _**orctooth**_ to a Coldain reclaimer in the same vicinity as Grunak. You may have to speak to multiple NPCs until you receive the update.\nYou say, 'Hail, a Coldain reclaimer'\nA Coldain reclaimer says, 'Hello there, Half Elf. Have ye come to join the reclamation efforts? We can certainly use someone with your skillset to help us with that endeavor. Why don't ye take a moment and talk to the Reclamation Officer over there? He'll likely be needing your help.'\nYou say, 'orctooth'\nA Coldain reclaimer says, 'Aye, now that you mention it, I did hear a scout say that they spotted a wee kitty to the northwest at the abandoned ruins. If you still think the cat is alive and you want to find them, then good luck, my friend. You're braver than I.'\nYour task 'You Can't Go Back Home' has been updated.\n2\\. Return to Grunak and inform them of what you learned 0/1 (The Eastern Wastes)\nYou say, 'Hail, Grunak, Ry`Gorr Refugee'\nGrunak, Ry`Gorr Refugee says, 'Dwarf see Orctooth? You find! Go to Ry`Gorr home, bring me Orctooth.'\nYour task 'You Can't Go Back Home' has been updated.\nYou have been given: Ry`Gorr Blessed Sack\nYour task 'You Can't Go Back Home' has been updated.\n3\\. Search for Orctooth at the ruins to the northwest of the Coldain camp 0/1 (The Eastern Wastes)\nHead to the fort with the entrance to Ry`Gorr Mines. Orctooth (a small black cat), will be moving pearched on a broken tree or circling the for ruins.\nRight-click the Sack on it.\nOrctooth reluctantly gets inside the sack, but you hear a terrifying growling sound that's getting louder.\nYour task 'You Can't Go Back Home' has been updated.\n4\\. Defend yourself from the restless Ry`Gorr 0/1 (The Eastern Wastes)\nRestless Ry`Gorr says, 'Freeeee uuuuuussss...'\nAn orc will spawn: _Restless Ry`Gorr (level 113)_. Kill the orc for the update (note: this orc has way more HP than standard mobs and hits extremely hard. Be ready for a long fight and for possible pathing mobs).\nYour task 'You Can't Go Back Home' has been updated.\n5\\. Recover the necklace from the restless orc 0/1 (The Eastern Wastes)\nLoot a _Ry`Gorr Tooth Necklace_ from the corpse.\nYour task 'You Can't Go Back Home' has been updated.\n6\\. Return Orctooth to Grunak 0/1 (The Eastern Wastes)\nReturn to and turn in Orctooth to Grunak.\nGrunak, Ry`Gorr Refugee says, 'You find Orctooth! Orctooth safe! Other Ry`Gorr like warg. I like Orctooth. What you holding? Where you find that? I see?\nYour task 'You Can't Go Back Home' has been updated\n7\\. Give Grunak the necklace you found 0/1 (The Eastern Wastes)\nTurn the necklace in to Grunak.\nGrunak, Ry`Gorr Refugee blinks, allowing for more tears to roll down his cheek. 'This... is clan symbol. Am alone now. Home gone. Clan gone. It just Orctooth and me. Me need time to be alone. Go.'\nAs you turn to leave, the refuge calls you back. 'High Elf, wait. [Clan] need help.'\nYour task 'You Can't Go Back Home' has been updated\nYou have been given: Ry`Gorr Blessed Torch\nYou say, 'Clan.'\nGrunak, Ry`Gorr Refugee looks north, 'Clan die, but still move. Stop them moving. Take tooths.' He grabs a flaming piece of wood from the fire and uses his nail to scratch some runes into it, 'Here, take fire. Burn them to stop moving again.'\n8\\. Kill infected orcs 0/7 (The Eastern Wastes)\nHead to the center of the zone near the Ry`Gorr Mines zone area and kill orcs.\n9\\. Recover Ry`Gorr Tooth Necklaces 0/7 (The Eastern Wastes)\nLoot 7 _Ry`Gorr Tooth Necklace_ from the orcs just killed. The necklaces can drop in multiple quantities.\n10\\. Burn Ry`Gorr Corpses 0/1 (The Eastern Wastes)\nUse the Ry`Gorr Blessed Torch, right-click it on _Ry`Gorr Corpse_ bodies on the ground around the fort area.\n11\\. Return the Ry`Gorr Necklaces to Grunak 0/7 (The Eastern Wastes)\nReturn to Grunak and hand in the 7 necklaces.\n'You Can't Go Back Home' has been updated.\n12\\. Return to Grunak and give him back the torch 0/1 (The Eastern Wastes)\nTurn in the Ry`Gorr Blessed Torch to Grunak.\n'You Can't Go Back Home has been updated.\nGrunak, Ry`Gorr Refugee looks into the fire, tossing what is left of the torch back into it. 'You help, I thank... need to be alone, need to rebuild... Maybe Orctooth keep me happy. Thank you, friend.'\nYour task 'You Can't Go Back Home' has been updated.\nGrunak wishes to be alone for the time being, needing to reflect on the loss of his clan. For now, it seems, you have helped him come to terms with what has happened. He is grateful for your assistance.\n\n---\n\nReward(s):\n212 platinum 5 gold\nYou gain experience!\n**Submitted by:** Larth\n- You receive 5 gold. You receive 212 platinum.",
    },
    {
      id = "9775",
      title = "Restless Mess",
      exp = "26",
      exp_name = "Torment of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Emli Widgetton",
      loc = nil,
      triggers = {
        "What **velium golems**?",
        "What **shards**?",
      },
      items_required = {
      },
      rewards = {
        { id = 137795, name = "Velium Shard", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Eastern Wastes [ToV]\n**Who:**\n- Emli Widgetton [npc=54985]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Money\n**Quest Items:**\n- Velium Shard [item=137795]\n**Related Zones:**\n- The Tower of Frozen Shadow [ToV]\n**Related Creatures:**\n- a golem usher [npc=55005]\n**Related Quests:**\n- Mercenary of The Tower of Frozen Shadow (10 Points) [quest=9801]\n**Era:** | !Torment of Velious\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 3 22:24:24 2019\nModified: Tue Dec 5 05:21:04 2023 | | **Torment of Velious Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nEmli Widgetton is located at the coldain camp in the southeast corner of The Eastern Wastes.\nUpon completion of the previous task: 'Oh, It's You Again!',\nEmli Widgetton says, 'Well, now that we have the vampire blood, we can move into other tasks that could help with our research. I have been asked to collect pieces that fall off the [ **Velium Golems**]. These pieces can be reforged and turned into armor that can protect our troops from the spectral attacks from the spirits wiithin this accursed tower. We discovered recently that the only way that we can ward off these creatures is by using the velium itself, but only velium that has been imbued with the restless ice.'\nYou say, 'What **velium golems**?'\nEmli Widgetton says, 'This tower holds many denizens but the ones that are most intriguing are the Velium Golems. These golems were already constructed but then came in contact with the restless ice, causing them to morph into something even more terrifying. I was only able to hear reports of these creatures, but when we found a small piece that must have fallen off one of them, it was discovered that the ghosts inside actively try to avoid contact with the material. You will find more of these [ **shards**] inside the tower, but you may need to take down a few of the golems in order to cllect large enough samples for us to use in smithing.'\nYou say, 'What **shards**?'\nEmli Widgetton says, 'Collect about 10 of these shards and that will be enough to create some armor to protect our soldiers from further harm.'\nYou have been assigned the task, 'Restless Mess.'\n\n---\n\n1. Destroy Velium Golems 0/6 The Tower of Frozen Shadow\n\n\n\nEnter the ToFS and slay any six velium golems, mostly on floor 5 for task update.\n\n\n\n\nVelium Shards [item=137795] drop off the golems you are killing, so loot six shards.\n4. Deliver Shards of Velium to Emli Widgetton 0/6 The Eastern Wastes\n\n\n\nDeliver the six looted shards to Emli for task update.\nYour task 'Restless Mess' has been updated.\n_Emli takes the shards you hand her and places them into a pouch she has kept at her side, gently patting it as it settles, saying 'Interesting, the blood seems to freeze as soon as it leaves the body'._\nYou receive 5 gold.\nYou receive 212 platinum.\n\n---\n\nReward(s):\n212 platinum 5 gold\n**Submitted by:** Larth",
    },
    {
      id = "9776",
      title = "This Will Come Back to Haunt Us",
      exp = "26",
      exp_name = "Torment of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Emli Widgetton",
      loc = nil,
      triggers = {
      },
      items_required = {
      },
      rewards = {
        { id = 137832, name = "Necromancy Research Notes", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Eastern Wastes [ToV]\n**Who:**\n- Emli Widgetton [npc=54985]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Money\n**Quest Items:**\n- Necromancy Research Notes [item=137832]\n**Related Zones:**\n- The Tower of Frozen Shadow [ToV]\n**Related Creatures:**\n- a ghostly scholar [npc=55003]\n- a ghostly student [npc=55004]\n**Related Quests:**\n- Mercenary of The Tower of Frozen Shadow (10 Points) [quest=9801]\n**Era:** | !Torment of Velious\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 3 22:26:52 2019\nModified: Tue Dec 5 05:21:04 2023 | | **Torment of Velious Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nEmli Widgetton is located at the coldain camp in the southeast corner of The Eastern Wastes.\nSay **study** to request the task.\nEmli Widgetton says, 'The only good thing these monsters did during their time alive was document their work. They are very thorough with their research and it is one of the most impressive things about their school of study. They kept journals, meticulously keeping track of each experiment and how it would help them have a better understanding of the process of life and death. Their work is what keeps them tied to this plane, which is unfortunate. Relieve them of their research and bring the pages of their dedication to me for proper disposal.\n\n---\n\n1. Destroy Ghostly Scholars 0/5 The Tower of Frozen Shadow\n\n\n\nHead to floor 2 and kill ghostly scholars and students for kill update and to loot five Necromancy Research Notes.\n4. Deliver Necromancy Research Notes to Emli Widgetton 0/5 The Eastern Wastes\nUpon handing in the five research notes to Emli:\nYour task, 'This Will Come Back to Haunt Us' has been updated.\n_You get an uneasy feeling that maybe this won't be the last time you see this knowledge._\nYou receive 5 gold.\nYou receive 212 platinum.\n\n---\n\nReward(s):\n212 platinum 5 gold\n**Submitted by:** Larth\n- 212 platinum 5 gold",
    },
  },
}
