-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Eastwastes (eastwastes)
-- Total Quests: 9
-- ============================================================================

return {
  zone = "eastwastes",
  zone_name = "Eastwastes",
  quests = {
    {
      id = "13293",
      title = "Erollisi Day: Lures Hurt",
      exp = "01",
      exp_name = "The Ruins of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Task",
      repeatable = true,
      group_size = "Solo",
      npc = "You have",
      loc = nil,
      triggers = {
        "Hail, Muku Wolfeetz",
        "Are you calling me short?",
        "What tasks are you working on?",
        "I could collect the supplies you need.",
        "Don",
        "Yes. I have a iksar tailbone. Why did you want this thing?",
        "What kind of secrets?",
        "That does sound nice. Did you need anything else for that friend?",
      },
      items_required = {
        { name = "you the one I have", count = 1 },
        { name = "him the totem", count = 1 },
      },
      rewards = {
        { id = 151169, name = "Converts to - 6x Scrumpious Sultry Candy Heart", type = "item" },
        { id = 151170, name = "Box of Scrumpious Sassy Candy Hearts", type = "item" },
        { id = 151169, name = "Scrumpious Sassy Candy Heart", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Task\n**Group Size:** Solo\n\nThis Erollisi Day task starts with Muku Wolfeetz [npc=60445] in The Overthere (old Kunark zone) at /way -3075, 1932, -48 outside the city walls on the east side.\n(Note: Before starting, make sure you have a fishing pole, you will need for a later step).\nYou say, 'Hail, Muku Wolfeetz'\nMuku Wolfeetz says, 'Hail, _____. The day is long, and the night is too [short]. '\nYou say, 'Are you calling me short?'\nMuku Wolfeetz says, 'Nay, _____. I hate handling my [tasks] in the day, and don't have enough time in the night.  '\nYou say, 'What tasks are you working on?'\nMuku Wolfeetz says, 'I am working on a secret project and am still collecting all of the [supplies] I need.'\nYou say, 'I could collect the supplies you need.'\nMuku Wolfeetz says, 'Why would you want to [help me]? I am not going to reward a Wood Elf. And I am not telling you what I am working on.  '\nYou say, 'Don't  think of it as me helping you. Think of it as you helping me.'\nYou have been assigned the task 'Lures Hurt'.\nMuku Wolfeetz says, 'Fine, go collect some bones for me and then we can talk some more. '\nMuku Wolfeetz isn't sure about trusting you. You will need to work on getting his trust before you can ask him about Darenne's missing treats. He has a few tasks that he is willing to have you do for him.\nHead east along the shore and search for an iksar skeleton's bones.\n- 1. Head east past the wreck 0/1 The Overthere\nThis is a location update at /way 3188.33, -1790.69, -24.38 which is straight east of the city.\nOnce you get the location update an iksar skeleton spawns and attacks.\n- 2. Kill the iksar skeleton 0/1 The Overthere\nKill it. You get Iksar Tailbone [item=151173] on your cursor.\n- 3. Return to Muku and talk to him 0/1 The Overthere\nYou say, 'Hail, Muku Wolfeetz'\nMuku Wolfeetz says, 'Hail, ______. Did you get that [iksar tailbone]?'\nYou say, 'Yes. I have a iksar tailbone. Why did you want this thing?'\nMuku Wolfeetz says, 'Well, now. I'm not sure why I would want to tell you that. A guy must have some [secrets].'\nYou say, ' What kind of secrets?'\nMuku Wolfeetz says, 'It is the season of love, and no one ever said what type of love. Maybe I want to do something [nice] for a friend.'\nYou say, 'That does sound nice. Did you need anything else for that friend?'\nMuku Wolfeetz says, 'Hrrm. I do need a part from an [sarnak skeleton].'\nYou say, 'I can get a part from an sarnak skeleton'\nYour task 'Lures Hurt' has been updated.\nMuku Wolfeetz says, 'Head a bit south from where you found the first skeleton. There you should be able to find the next. '\n- 4. Head south from where you found the skeleton 0/1 The Overthere\nThis is a location update at /way 1932, -1657, -42. There is a sarnak skeleton near a boulder at this location. It will attack you, kill it. It drops Sarnak Voicebox [item=151174], loot it.\n- 5. Return to Muku and hail 0/1 The Overthere\nYou say, 'Hail, Muku Wolfeetz'\nYour task 'Lures Hurt' has been updated.\nMuku Wolfeetz says, 'Good to see you again _____. I was worried that I would have to go [save] you. '\nYou say, ' There is no need to save me. Since we are friends now, do you know anything about Darenne missing treats or who took them?'\nYour task 'Lures Hurt' has been updated.\nMuku Wolfeetz says, 'I heard about that, I am not sure who took them, but I was given one as a gift. You help me [finish] my gift and I will give you the one I have. '\nYou say, 'I can help you finish, but I want to know who gave it to you.'\nMuku Wolfeetz says, 'Ha. We aren't that good of friends. Once you find the last two items you can go ahead and can make the lure. I can't wait to see your craftmanship. '\n- 6. Fish up a cockatrice claw 0/1 The Overthere\nFish along the shore, doesn't matter where along the shore. Catch a Cockatrice Claw [item=151175], don't spill your beer in the process.\n....sigh, you spilled your beer didn't you?\n- 7. Collect beach grass 0/1 The Overthere\nBunch of Beach Grass [item=151176] looks like a purple collectible on the ground near /way 3556, 1559, 127. Loot it.\n- 8. Craft the Totem of Love and Ocean 0/1 ALL\nThe Cockatrice Claw is a container. Place the Tailbone, Voicebox and the Bunch of Beach Grass inside the claw and combine to make the Totem of Love and Ocean [item=151177].\n- 9. Deliver the Totem of Love and Ocean 0/1 The Overthere\nReturn to Muku and give him the totem. Squeezed Glee [item=151172] (needed for Only Fools Fall In [quest=13292]) will appear on your cursor.\nYou offered 1 Totem of Love and Ocean to Muku Wolfeetz.\nYou have been given: Squeezed Glee\nYour task 'Lures Hurt' has been updated.\nYou have successfully earned Muku's trust and received the Squeezed Glee drink from him.\nMuku Wolfeetz says, 'Now that is a fine-looking lure. Nice and sharp too. Here you can have this drink. It looks way too sweet for me away. '\nYou complete the trade with Muku Wolfeetz.\nYou are given: Squeezed Glee\nReward(s):\nBox of Scrumpious Sultry Candy Hearts [item=151170] - Converts to - 6x Scrumpious Sultry Candy Heart [item=151169] (Req Level 45: HP: 10, Mana: 10 - Miraculous meal)\nSubmitted by: GidonoRewards:\n- Box of Scrumpious Sassy Candy Hearts [item=151170]\n- Scrumpious Sassy Candy Heart [item=151169]\n[",
    },
    {
      id = "4147",
      title = "Necropolis Vermin Cleanup",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 55,
      max_lvl = 125,
      quest_type = "Task",
      repeatable = false,
      group_size = "Solo",
      npc = "You have",
      loc = { y = -1350.0, x = -1590.0, z = 0.0 },
      triggers = {
        "Hail, Artisan Irisi",
        "I have come for armor more suited to the Drakkin.",
        "I am interested.",
        "What symbols?",
        "The Dragon Necropolis.",
        "I wish to gain this book.",
        "armor",
        "interested",
      },
      items_required = {
      },
      rewards = {
        { id = 64709, name = "Sacred Book of Drakkin Culture", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 55\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Task\n**Group Size:** Solo\n\nArtisan Irisi may be found on the second floor of Crescent Reach, at -1350, -1590.\nYou say, 'Hail, Artisan Irisi'\nArtisan Irisi says 'Oh dear, that just won't do. Tell me you have come for [armor] more suited to the Drakkin?'\nYou say, 'I have come for armor more suited to the Drakkin.'\nArtisan Irisi says 'Oh good. You had me worried for a moment. So you are [interested] in some of the armor specifically made for our culture?'\nYou say, 'I am interested.'\nArtisan Irisi says 'Well then, let's get started. You will need various [books] that hold patterns you will need in order to make the armor. There is the [basic] book of armor patterns, and five different books to make [symbols] to augment the efficacy of the armor.'\nYou say, 'What symbols?'\nArtisan Irisi says 'Once you have your armor, you will want to reinforce it with these symbols. Fetch me a few things so I can make the symbol patterns. There's reagents I need in [Crescent Reach], [Dreadlands], [The Dragon Necropolis], and the [valley] beyond the Lavastorm mountains. I have also heard about the [underground] place called Darkhollow.'\nYou say, 'The Dragon Necropolis.'\nYou have been assigned the task 'Necropolis Vermin Cleanup'.\nArtisan Irisi says 'There are vermin in the sacred Dragon Necropolis, and I would like for you to remove them. I will also be able to use some of what you retrieve from them as supplies for more books. Remove the rat men from their lairs within Dragon Necropolis, and collect two old dragon horns from them while you are at it. Do you wish to gain this [book]?'\nYou say, 'I wish to gain this book.'\nArtisan Irisi says 'Here is a list of the tasks you will need to complete to get each book. You will only be offered that chance to get books that you will have enough experience to attain.'\nYou have been assigned the task 'Necropolis Vermin Cleanup'.\nKill 80 Chelaki or Chetari - Dragon Necropolis\nLoot 2 Old Dragon Horn - Dragon Necropolis\nDeliver 2 Old Dragon Horn to Artisan Irisi - Crescent Reach\nKill 10 Phase Spiders - Dragon Necropolis\nLoot 1 Phase Spider Silk - Dragon Necropolis\nDeliver 1 Phase Spider Silk to Artisan Irisi - Crescent Reach\nUpon completing the last step:\nYou have cleaned some of the vermin from Dragon Necropolis.\nYou receive a Master's Book of Drakkin Culture.Rewards:\n- Sacred Book of Drakkin Culture [item=64709]\n[",
    },
    {
      id = "4251",
      title = "Tormax's Head - Dwarves",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 55,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "You have",
      loc = nil,
      triggers = {
        "Hail, Dain Frostreaver IV",
      },
      items_required = {
      },
      rewards = {
        { id = 4760, name = "Tri-Plated Golden Hackle Hammer", type = "item" },
      },
      factions = {
        { name = "Dain Frostreaver IV", change = 100 },
        { name = "Coldain", change = 100 },
        { name = "King Tormax", change = -50 },
      },
      walkthrough = "**Level:** 55\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nUpon turning in King Tormax's Head, obtained by killing King Tormax in Kael Drakkel, to Dain Frostreaver IV:\nYou say, 'Hail, Dain Frostreaver IV'\nDain Frostreaver IV says, 'You have done what no Coldain could do, _______! This is indeed a glorious day in our people's history. In return for your invaluable service I present you with the Tri-plated Golden Hackle Hammer. Its magic is powerful and I am sure it will serve you well.'\nDain Frostreaver IV shouts, 'Let it be known from this day forth that _______ and their companions are Heroes of the Coldain Kingdom. King Tormax has been slain, it is a time for celebration. Let no tankard go unfilled!'\nYour faction standing with Dain Frostreaver IV has been adjusted by 100.\nYour faction standing with Coldain has been adjusted by 100.\nYour faction standing with King Tormax has been adjusted by -50.\nYou gain experience! Submitted by: Onstill Drastill, Keepers of the Elements, Luclin/VeeshanRewards:\n- Tri-Plated Golden Hackle Hammer [item=4760]\n[",
    },
    {
      id = "4308",
      title = "Lost Heirlooms (Level 25)",
      exp = "01",
      exp_name = "The Ruins of Kunark",
      min_lvl = 25,
      max_lvl = 125,
      quest_type = "Task",
      repeatable = true,
      group_size = "Solo",
      npc = "You have",
      loc = nil,
      triggers = {
        "Hail, Aiden Silverwing",
      },
      items_required = {
      },
      rewards = {
        { id = 69357, name = "Radiant Band of the Silverwing", type = "item" },
        { id = 69413, name = "Shimmering Circlet of the Silverwing", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 25\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Task\n**Group Size:** Solo\n\nThis task begins when you loot a Silverwing Circlet from Permafrost.\n--You have looted a Silverwing Circlet.--\nYou have been assigned the task 'Lost Heirlooms (Level 25)'.\nSpeak to Aiden Silverwing about the ring you found. (0/1) - Plane of Knowledge\nAiden Silverwing is located outside the Guild Lobby. If you do not yet have a Silverwing Lockbox in your inventory, you will receive it upon hailing him.\nYou say, 'Hail, Aiden Silverwing'\nAiden Silverwing says 'You've found Gallien's ring! Gallien never was happy here in Crescent Reach. Always wanting to see the rest of Norrath that one. It's no surprise he wound up in Permafrost really. Obsessed with the ancient dragons he was. He sent word many months ago about needing to talk to Sillien about some magical shard he'd found, but that was the last I heard from him.'\nFind a shard of power to infuse with Aiden's heirloom. (0/1) - Trakanon's Teeth\nLoot a Radiant Shard from Trakanon's Teeth.\nPut the circlet and shard into the lockbox and combine them. (0/1) - ALL\nCasters/priests craft a Radiant Band of the Silverwing, while melees/hybrids craft a Shimmering Circlet of the Silverwing.Submitted by: HeinrikkRewards:\n- Radiant Band of the Silverwing [item=69357]\n- Shimmering Circlet of the Silverwing [item=69413]\n[",
    },
    {
      id = "6922",
      title = "Finding Your Way in the World - Using the Zone Guide",
      exp = "03",
      exp_name = "The Shadows of Luclin",
      min_lvl = 1,
      max_lvl = 10,
      quest_type = "Task",
      repeatable = false,
      group_size = "Solo",
      npc = "You have",
      loc = { y = 114.0, x = -80.0, z = -157.0 },
      triggers = {
        "Hail, Secalna Galnor",
        "Hail, Nermin",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 10\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Task\n**Group Size:** Solo\n\nSecalna Galnor is located at +114, -80, -157.\nYou say, 'Hail, Secalna Galnor'\nYou have been assigned the task 'Finding Your Way in the World - Using the Zone Guide'.\nTalk to Secalna. She will tell you about the Zone Guide. 0/1 (Plane of Knowledge)\nYou say, 'Hail, Secalna Galnor'\nYour task 'Finding Your Way in the World - Using the Zone Guide' has been updated.\nUse the Zone Guide to find your way to the Bazaar. 0/1 (The Bazaar)\nA mystical path appears before you.\nThe mystical path fades away.\nLOADING, PLEASE WAIT...\nYou have entered The Bazaar.\nWelcome to The Bazaar!\nThere are currently 293 traders selling a total of 17826 items in the bazaar.\nType /bazaar to begin viewing items for sale or type /trader to begin putting items up for sale.\nThere are 16 Buyers waiting to purchase your loot.  Type /barter to search for them, or use /buyer to set up your own Buy Lines.\nYour task 'Finding Your Way in the World - Using the Zone Guide' has been updated.\nSpeak with Nermin.  He has something he needs delivered. 0/1 (Plane of Knowledge)\nLOADING, PLEASE WAIT...\nYou have entered The Plane of Knowledge.\nLOADING, PLEASE WAIT...\nYou have entered The Bazaar.\nWelcome to The Bazaar!\nThere are currently 293 traders selling a total of 17826 items in the bazaar.\nType /bazaar to begin viewing items for sale or type /trader to begin putting items up for sale.\nThere are 16 Buyers waiting to purchase your loot.  Type /barter to search for them, or use /buyer to set up your own Buy Lines.\nYou have been charged a mercenary upkeep cost of 0 plat, and 0 gold and your mercenary upkeep cost timer has been reset to 15 minutes.\nYou say, 'Hail, Nermin'\nYour task 'Finding Your Way in the World - Using the Zone Guide' has been updated.\nUse the Zone Guide to find your way to the Guild Lobby. 0/1 (Guild Lobby)\nLOADING, PLEASE WAIT...\nYou have entered The Plane of Knowledge.\nLOADING, PLEASE WAIT...\nYou have entered Guild Lobby.\nYour task 'Finding Your Way in the World - Using the Zone Guide' has been updated.\nDeliver 1 Personal Note to Magus Alaria. 0/1 (Plane of Knowledge)\nYour task 'Finding Your Way in the World - Using the Zone Guide' has been updated.\nUse the Zone Guide to find your way to the Plane of Knowledge. 0/1 (Plane of Knowledge)\nLOADING, PLEASE WAIT...\nYou have entered The Plane of Knowledge.\nYour task 'Finding Your Way in the World - Using the Zone Guide' has been updated.\nTell Secalna Galnor of your success. 0/1 (Plane of Knowledge)\nYou say, 'Hail, Secalna Galnor'\nYour task 'Finding Your Way in the World - Using the Zone Guide' has been updated.\nYou have learned how to use the Zone Guide.  It can help you find your way around the world and should prove useful to you in many of your adventures in the future.\nYou don't have to actually use the zone guide feature.\nNeed quest items.Submitted by: BijouRewards:\n[",
    },
    {
      id = "8305",
      title = "Beastlord Thurgadin Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 45,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Icefang",
      loc = { y = 44.0, x = -564.0, z = 0.0 },
      triggers = {
        "Hail, Pearce Icefang",
        "I am a beastlord",
        "armor",
        "bracers",
        "boots",
        "sleeves",
        "gloves",
        "cap",
      },
      items_required = {
        { name = "Pearce 3x Crushed Coral and an Eroded Leather Cap", count = 1 },
      },
      rewards = {
        { id = 10149, name = "Armband of the Beastlord", type = "item" },
        { id = 10334, name = "Boots of the Beastlord", type = "item" },
        { id = 10576, name = "Bracer of the Beastlord", type = "item" },
        { id = 13145, name = "Chestguard of the Beastlord", type = "item" },
        { id = 9009, name = "Crown of the Beastlord", type = "item" },
        { id = 11384, name = "Gloves of the Beastlord", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 45\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nPearce Icefang in a wolf den in the back of the zone near the mines offers a series of quests for beastlord to obtain a set of \"of the Beastlord\" Armor. He can be found around location 44, -564.\nYou must be at least KINDLY with Coldain in order to complete these quests.\nYou say, 'Hail, Pearce Icefang'\nPearce Icefang speaks in a rumbling tone.\nPearce Icefang says, 'Greetings. I only wish to speak to a beastlord. Are you a beastlord?'\nYou say, 'I am a beastlord'\nPearce Icefang says, 'I sense that you are in tune with yourself and with nature. You have learned much from your travels and I shall help you by providing you with protection from harm and the elements in the form of armor.'\nYou say, 'armor'\nPearce Icefang says, 'For you I shall make a cap, tunic, sleeves, bracers, gloves, leggings, and boots. Each piece is a quest unto itself.  To seek the components you must search the lands for them and test the power of the spirit within.'\nEroded Armor molds drop from giants in the Kael Arena. Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Flame Emerald + Eroded Leather Bracelet\nBoots - 3x Crushed Black Marble + Eroded Leather Boots\nArms - 3x Flawed Emerald + Eroded Leather Sleeves\nGloves - 3x Crushed Topaz + Eroded Leather Gloves\nHelm - 3x Crushed Coral + Eroded Leather Cap\nLegs - 3x Flawed Sea Sapphire + Eroded Leather Leggings\nChest - 3x Flawless Diamond + Eroded Leather Tunic\nBracer\nYou say, 'bracers'\nPearce Icefang says, 'Bracers are quite easy to imbue. Simply find three crushed flame emeralds and a eroded leather bracelet and I will complete the ritual to enchant them.'\nGive Pearce 3x Crushed Flame Emerald and a Eroded Leather Wristband\nPearce Icefang smiles warmly as he hands you your reward.\nPearce Icefang says 'You have done well.'\nYou receive: Bracer of the Beastlord\nBoots\nYou say, 'boots'\nPearce Icefang says, 'Simply bring me a set of three crushed black marbles and a pair of eroded leather boots and I will imbue them. I bid you good luck in finding such things.'\nGive Pearce 3x Crushed Black Marble and a Eroded Leather Boots\nPearce Icefang smiles warmly as he hands you your reward.\nPearce Icefang says 'You have done well.'\nYou receive: Boots of the Beastlord\nArms\nYou say, 'sleeves'\nPearce Icefang says, 'Three flawed emeralds and a set of eroded leather sleeves might be an interesting combination. The powers of the gems may be harnessed to imbue the sleeves.'\nGive Pearce 3x Flawed Emerald and a Eroded Leather Sleeves\nPearce Icefang smiles warmly as he hands you your reward.\nPearce Icefang says 'You have done well.'\nYou receive: Armband of the Beastlord\nGloves\nYou say, 'gloves'\nPearce Icefang says, 'Strong protection for one's hands is important. I may be able to craft you a set of enchanted leather gloves if you find a set of eroded leather gloves and a set of three crushed topaz.'\nGive Pearce 3x Crushed Topaz and a Eroded Leather Gloves\nPearce Icefang smiles warmly as he hands you your reward.\nPearce Icefang says 'You have done well.'\nYou receive: Gloves of the Beastlord\nHelm\nYou say, 'cap'\nPearce Icefang says, 'Those who are wise as we are know that protection of the head is most important. I may be able to sew you something most interesting if you were to bring me an eroded leather cap and three pieces of crushed coral.'\nGive Pearce 3x Crushed Coral and an Eroded Leather Cap\nPearce Icefang smiles warmly as he hands you your reward.\nPearce Icefang says 'You have done well.'\nYou receive: Crown of the Beastlord\nLegs\nYou say, 'leggings'\nPearce Icefang says, 'Leggings are a bit trickier to imbue. Three flawed sea sapphires will allow me to channel the correct energies into a pair of eroded leather leggings. However, those flawed sea sapphires are somewhat rare. Return to me if you find such things in your journeys.'\nGive Pearce 3x Flawed Sea Sapphire and a Eroded Leather Leggings\nPearce Icefang smiles warmly as he hands you your reward.\nPearce Icefang says 'You have done well.'\nYou receive: Leggings of the Beastlord\nChest\nYou say, 'tunic'\nPearce Icefang says, 'If you find an eroded leather tunic and three flawless diamonds bring them to me and I shall attempt to create an enchanted tunic that will serve you well.'\nGive Pearce 3x Flawless Diamond and a Corroded Leather Tunic\nPearce Icefang smiles warmly as he hands you your reward.\nPearce Icefang says 'You have done well.'\nYou receive: Chestguard of the Beastlord\nSubmitted by: BobbybickRewards:\n- Armband of the Beastlord [item=10149]\n- Boots of the Beastlord [item=10334]\n- Bracer of the Beastlord [item=10576]\n- Chestguard of the Beastlord [item=13145]\n- Crown of the Beastlord [item=9009]\n- Gloves of the Beastlord [item=11384]\n- Leggings of the Beastlord [item=8884]\n[",
    },
    {
      id = "8463",
      title = "Dithgar's Defender",
      exp = "01",
      exp_name = "The Ruins of Kunark",
      min_lvl = 60,
      max_lvl = 130,
      quest_type = "Quest",
      repeatable = false,
      group_size = "Solo",
      npc = "Priest of Brell",
      loc = nil,
      triggers = {
        "Hail, Dithgar Irongut",
        "Were you hoping to discover something in particular in these theoretical adventures?",
        "Perhaps I can aid you.",
        "adventure and discovery",
        "some aid",
      },
      items_required = {
        { name = "you a Heartstone", count = 1 },
        { name = "them to you", count = 1 },
        { name = "Vows of Undying Devotion to Auraline", count = 1 },
        { name = "Sealed Azure Box to Auraline", count = 1 },
        { name = "Thoric's Sacred Hammer", count = 1 },
        { name = "Thoric's Sacred Hammer to Dithgar Irongut", count = 1 },
      },
      rewards = {
        { id = 128108, name = "Defender of the Faithful Heart", type = "item" },
      },
      factions = {
        { name = "Inhabitants of Firiona Vie", change = 10 },
        { name = "Emerald Warriors", change = 7 },
        { name = "Storm Guard", change = 7 },
        { name = "Legion of Cabilis", change = -1 },
        { name = "Pirates Of Gunthak", change = -1 },
        { name = "Inhabitants of Firiona Vie", change = 5 },
      },
      walkthrough = "**Level:** 60\n**Maximum Level:** 130\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nThis is one of the finished Kunark quests added on the February 15, 2017, update.\nFind Dithgar Irongut in Firiona Vie at /waypoint +808, -3323, +160.\nYou say, 'Hail, Dithgar Irongut'\nDithgar Irongut says, 'Well, good day to you, _____! You may call me Dithgar Irongut, priest of Brell. I'm at your service... or I would be if I could get out of this blasted, crumbling pile of poor craftsmanship. Aaah, well. Duties are duties and the ale is strong enough to stomach, so I shouldn't complain. Though, I do wish I could be out there in the lands where you venture, traveler, for I have a bit of my own thirst for [adventure and discovery].'\nYou say, 'Were you hoping to discover something in particular in these theoretical adventures?'\nDithgar Irongut says, 'Well, since you asked, I might as well share. It seems to be no secret any longer now that Kaelana, Levaios, and Taluran have arrived. I am searching specifically for a rumored item, held by a group of ancient travelers, much like yourself. Unfortunately, this item was destroyed. But Brell has blessed me with the ability of a craftsman and I believe myself able to replicate our fallen brother's sacred defender. There is one thing keeping me from doing so, however, and that is the fact that I am stuck here and cannot collet the needed components to craft such an item. Perhaps if I had [some aid], this would not be such an issue.'\nYou say, 'Perhaps I can aid you.'\nDithgar Irongut says, 'Will you now, Bobbybic? I'm pleased to hear it! The first order of business will be to retrieve the documents that will instruct me on what it is we should be looking for. Venture deep into the lair of the sarnak and find the Book of the Righteous. Once you have the book, venture into Nurga and there you will find the Prayer of the Righteous. Bring those to me and we shall progress further!'\nLoot Prayer of the Righteous [item=128076] in Mines of Nurga which drops from \"The Rockchanter\", as well as Book of the Righteous [item=128235] which drops from Battle Master Ska`tu in the \"crypt\" area of Chardok\nGive the Prayer of the Righteous and the Book of the Righteous to Dithgar Irongut\nDithgar Irongut says, 'Well done, Chain! Here, Levaios was kind enough to forge this for me. You will need to take it to one named Seshkar in Trakanon's Teeth along with the essence of Tzirathk, from the vile creature Tzirathk himself. If you can locate Seshkar, give him both of those items once you have had an enchanter of great might subdue the angry villain. He should give you a Heartstone, or so says Levaios from his research. Return the Heartstone to me, along with the Tainted Shield of Blessed Faith.'\nYour faction standing with Inhabitants of Firiona Vie has been adjusted by 10.\nYour faction standing with Emerald Warriors has been adjusted by 7.\nYour faction standing with Storm Guard has been adjusted by 7.\nYour faction standing with Legion of Cabilis has been adjusted by -1.\nYour faction standing with Pirates Of Gunthak has been adjusted by -1.\nYou gain experience!\nReceive: Hollowed Stone Orb [item=128553]\nThe Essence of Tzirathk [item=24926] comes from Tzirathk in City of Mist. PH is a black reaver at the top of the elevator.\nTo get the Heartstone [item=128554], have an Enchanter/Bard charm Seshkar [npc=51909] in Trakanon's Teeth if you don't have good faction with him. You may also charm him yourself if you have a set of Puppet Strings [item=3656]. Evil races should start off with at least apprehensive faction with him since he is on Venril Sathir faction. He roams close to all the other ghosts near Emperor Ganak.\nGive Seshkar the Hollowed Stone Orb and the Essence of Tzirathk\nUpon turn in:\nReceive: Heartstone [item=128554] and positive Venril Sathir faction.\nLoot the Tainted Shield of Blessed Faith [item=8986] from the Howling Stones which drops from \"golem, skeleton, and goo\" type mobs then return to Dithgar Irongut in Firiona Vie\nGive Dithgar the Tainted Shield of Blessed Faith and the Heartstone\nDithgar Irongut says, 'Again, Chain, well done! Kaelana has given these vows to me... and now I give them to you, my friend. And no, do not think that they are meant for you from me. They are for one named Auraline, a mermaid who has returned to her home. She was the love of old Thoric Stormhammer, a priest of Brell like myself and quite distant relative to King Stormhammer -- though Thoric was not of true royalty, at least not of his time. Auraline will know what to do once she has the vows... but like Seshkar and many who have come into contact with the Righteous Order, she has become cruel and will need some persuasion of the magical sort.'\nYour faction standing with Inhabitants of Firiona Vie has been adjusted by 5.\nYour faction standing with Emerald Warriors has been adjusted by 3.\nYour faction standing with Storm Guard has been adjusted by 3.\nYour faction standing with Legion of Cabilis has been adjusted by -1.\nYour faction standing with Pirates Of Gunthak has been adjusted by -1.\nYou gain experience!\nReceive: Vows of Undying Devotion [item=128555]\nCollect Blessed Mallet [item=11624] from Construct of Sathir in Karnor's Castle and Ancient Charred Wooden Handle [item=128062] from Ghorgash in Burning Woods prior to proceeding to reduce extra trips.\nBring an Enchanter/Bard to charm Auraline in Kedge Keep or use Puppet Strings if you have some. Or open trade window and invis for turn in.\nTurn in Vows of Undying Devotion to Auraline.\nAuraline reads the vow, scanning each line carefully, then laughs, a melody of fizzing bubbles, 'Undying devotion, for me? Well, flattery will get you everywhere, Chain. I see that you need something from me, and I can provide it, if you combine a Blessed Mallet and an Ancient Charred Wooden Handle in this box. If you are truly my paramour, you will waste no time. I'm waiting.' The mermaid blows you a heart-shaped bubbly kiss.\nYou gain experience!\nReceive: Shimmering Azure Box [item=133097]\nCombine Blessed Mallet and Ancient Charred Wooden Handle in box to create a Sealed Azure Box [item=128556]\nTurn in Sealed Azure Box to Auraline.\nAuraline blows you another heart-shaped bubbly kiss upon receipt of the sealed box, 'I knew you wouldn't be able to stay away, Chain. I've fused these two mundane objects into something much greater. If this is not to your liking, perhaps the dwarf will take it in trade for something else. Don't act surprised - I could smell the dwarf's unmistakable stink on the vow. In any case, please think of me often. I'll be thinking of you.'\nYou gain experience!\nReceive: Thoric's Sacred Hammer [item=128550].\nReturn to Dithgar Irongut in Firiona Vie\nYou'll need indifferent faction with Storm Guard at this point to turn in Thoric's Sacred Hammer.\nTurn in Thoric's Sacred Hammer to Dithgar Irongut.\nDithgar Irongut says, 'Aye! This is perfect! I have done it, as suspected... and to think that Kaelana doubted me! Here, Chain. Take this defender and wield it proudly. One just like it was carried by one of the greatest priests to ever walk these lands!'\nYou gain experience!\nReceive: Defender of the Faithful Heart [item=128108].\n- Defender of the Faithful Heart\n- Kunark Archaeologist player title suffix if first per server\nSubmitted by: MaxTheLionRewards:\n- Defender of the Faithful Heart [item=128108]\n[",
    },
    {
      id = "8608",
      title = "Dulak Bandits",
      exp = "05",
      exp_name = "The Legacy of Ykesha",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = false,
      group_size = "Solo",
      npc = "You have",
      loc = { y = -205.0, x = -672.0, z = -34.0 },
      triggers = {
        "Hail, Assistant Vagli",
        "What task?",
        "task",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nYou say, 'Hail, Assistant Vagli'\nAssistant Vagli says 'Greetings, friend. If you have come to study under the great Alvarik you have come to the right place! I help by carrying his research tomes for him. If there is one you would like to buy, feel free to browse through what we have. If you're looking for something to do, I may have a [task] available for you to get started on. Alvarik has much he needs done and I can't do it all myself!'\nYou say, 'What task?'\nHe offers you 3 tasks, one of which is 'Dulak Bandits'\nMedium length task, begins in Gulf of Gunthak\nObjective Instructions\n- Speak with Welligorn (Gunthank beach at -205, -672, -34)\n- Explore the ship Stormwave at one of the southern docks (Dulak's Harbor)\n- Kill 10 Broken Skull brigands (Dulak's Harbor - found within the cabins along the south side of the docks)\n- Speak with Zalil Nyvin (Plane of Knowledge - Inside of a building on the north side of PoK south of the Kelethin stone)\nTask description in Quest Journal:\nIt's difficult to keep a farm running on a daily basis, what with all the trouble farmers face today. One thing they can count on is vicious predators on the prowl for their next meal, usually livestock. There's one farmer that's tired of it and wants help. Go speak with Welligorn, for more information.\nUpon hailing Zalil Hyvin;\nThanks for contacting me, ______. Your information on this matter has been most useful.\nYou receive Experience\nYou receive 9 copper\nYou receive 1 silver\nYou receive 7 gold\nYou receive 45 platinumSubmitted by: SentientShamanRewards:\n- Experience, Coin.\n[",
    },
    {
      id = "8627",
      title = "Hunter of Eastern Wastes",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "Warden Bruke",
      loc = nil,
      triggers = {
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon defeating the following rare monsters in Eastern Wastes:\nChief Ry`Gorr\nFirbrand the Black\na Ry`Gorr minstrel\nWarden Bruke\nAdd the following points to the eastwastes_1.txt file:\nP -480.4730, 4067.3210, 141.9490,    0, 127, 0,  3,  Crystal_Caverns\nP -8.9600, 7252.7539, 158.7350,      0, 127, 0,  3,  Sleeper's_Tomb\nP -6561.6182, 1791.3170, 120.3960,   0, 127, 0,  3,  The_Great_Divide\nP -6993.1968, 6254.4761, -304.5300,  0, 127, 0,  3,  Kael_Drakkal\nP 5905.0229, 4513.1050, 557.5190,    0, 127, 0,  3,  Iceclad\nP -4406.0000, 0.0000, 0.0000,        0, 127, 0,  3,  Iceclad\nP 4191.0000, 9091.0000, 143.0967,    0, 127, 0,  3,  Zeixshi-Kar's_Awakening\nP 4296.0000, 5049.0000, 0.0000,      240, 240, 240,  3,  Succor_Point\nP -500.0000, 3400.0000, 0.0000,      240, 240, 240,  2,  Orc_Fort\nP -3300.0000, 1750.0000, 0.0000,     240, 240, 240,  2,  Giant_Fort\nP 2117.6841, -635.5590, 143.3290,    240, 240, 240,  2,  Safe_Tree\nP -3425.8799, 6949.7500, 209.7770,   240, 240, 240,  2,  Safe_Ridge\nP -4213.4341, 9593.1191, 148.5590,   240, 240, 240,  2,  Walrus_Safe_Camp\nP -3285.8521, 6151.1279, 169.3480,   240, 240, 240,  2,  Giant_Hill\nP 3208.3049, 548.8660, 154.4820,     240, 240, 240,  2,  Coldain_Huts\nP 2174.0000, 7859.0000, 0.0000,      0, 0, 240,  3,   Coldain_Outcast_(Merchant)\nP -3230.0000, 8083.0000, 0.0000,     0, 0, 240,  3,   Icefang\nP -1565.4150, 2461.1179, 304.9510,   0, 0, 240,  3,   Boridain_Glacierbane\nP -3285.1189, 7938.1699, 142.9390,   0, 0, 240,  3,   Korrigain\nP 2623.9260, 4926.7100, 142.9380,    0, 0, 240,  3,   Tain_Hammerfrost\nP 388.4470, 2708.9919, 178.0940,     0, 0, 240,  3,   Garadain_Glacierbane\nP 443.0870, 2631.2930, 174.7840,     0, 0, 240,  3,   Gloradin_Coldheart\nP -78.5300, -215.0430, 29.8360,      0, 0, 240,  3,   Corbin_Blackwell_0\nP 1899.3900, 539.9870, 159.8400,     0, 0, 240,  3,   Corbin_Blackwell_1\nP 3175.8721, 573.6350, 154.0650,     0, 0, 240,  3,   Corbin_Blackwell_2\nP -4112.0000, 6759.0000, 144.3630,   240, 64, 0,  1,  possible_Tanik\nP -4397.0000, 6294.0000, 144.3630,   240, 64, 0,  1,  possible_Tanik\nP -3564.0000, 6088.0000, 144.3630,   240, 64, 0,  1,  possible_Tanik\nP -3476.8821, 6335.0112, 144.3630,   240, 64, 0,  1,  possible_Tanik\nP -4126.0000, 5680.0000, 144.3630,   240, 64, 0,  1,  possible_Tanik\nP -4576.0000, 5670.0000, 144.3630,   240, 64, 0,  1,  possible_Tanik\nP -4307.0000, 5672.0000, 144.3630,   240, 64, 0,  1,  possible_Tanik\nP -4206.0000, 5679.0000, 144.3630,   240, 64, 0,  1,  possible_Tanik\nP -4252.0000, 5683.0000, 144.3630,   240, 64, 0,  1,  possible_Tanik\nP -4435.0000, 5687.0000, 144.3630,   240, 64, 0,  1,  possible_Tanik\nP -3600.0000, 5696.0000, 144.3630,   240, 64, 0,  1,  possible_Tanik\nP -4505.0000, 5702.0000, 144.3630,   240, 64, 0,  1,  possible_Tanik\nP -4384.0000, 5702.0000, 144.3630,   240, 64, 0,  1,  possible_Tanik\nP -4337.0000, 6644.0000, 144.3630,   240, 64, 0,  1,  possible_Tanik\nP -3885.0000, 6703.0000, 144.3630,   240, 64, 0,  1,  possible_Tanik\nP -4410.0000, 6759.0000, 144.3630,   240, 64, 0,  1,  possible_Tanik\nP -4202.0000, 6759.0000, 144.3630,   240, 64, 0,  1,  possible_Tanik\nAdd the following points to the eastwastes_2.txt file:\nP -479.9366, 3842.6758, 167.6741,   240, 0, 0,  3,  Chief_Ry`Gorr\nP -207.5880, 3833.6255, 145.1393,   240, 0, 0,  3,  Firbrand_the_Black\nP -613.0410, 3965.5374, 143.1778,   240, 0, 0,  3,  a_Ry`Gorr_minstrel\nP 366.3540, -272.0400, 4.0320,      240, 0, 0,  3,  Warden_Bruke\nP -4728.9502, 9133.8330, 258.4280,  240, 0, 0,  3,  Man_O_War_Hill\nAdd the following points to the eastwastes_3.txt file:\nP 0.0000, 0.0000, 0.0000,          127, 64, 0,  2,  0\nP -7000.0000, -1675.0000, 0.0000,  127, 64, 0,  2,  7000\nP -6500.0000, -1675.0000, 0.0000,  127, 64, 0,  2,  6500\nP -6000.0000, -1675.0000, 0.0000,  127, 64, 0,  2,  6000\nP -5500.0000, -1675.0000, 0.0000,  127, 64, 0,  2,  5500\nP -5000.0000, -1675.0000, 0.0000,  127, 64, 0,  2,  5000\nP -4500.0000, -1675.0000, 0.0000,  127, 64, 0,  2,  4500\nP -4000.0000, -1675.0000, 0.0000,  127, 64, 0,  2,  4000\nP -3500.0000, -1675.0000, 0.0000,  127, 64, 0,  2,  3500\nP -3000.0000, -1675.0000, 0.0000,  127, 64, 0,  2,  3000\nP -2500.0000, -1675.0000, 0.0000,  127, 64, 0,  2,  2500\nP -2000.0000, -1675.0000, 0.0000,  127, 64, 0,  2,  2000\nP -1500.0000, -1675.0000, 0.0000,  127, 64, 0,  2,  1500\nP -1000.0000, -1675.0000, 0.0000,  127, 64, 0,  2,  1000\nP -500.0000, -1675.0000, 0.0000,   127, 64, 0,  2,  500\nP 0.0000, -1675.0000, 0.0000,      127, 64, 0,  2,  0\nP 500.0000, -1675.0000, 0.0000,    127, 64, 0,  2,  -500\nP 1000.0000, -1675.0000, 0.0000,   127, 64, 0,  2,  -1000\nP 1500.0000, -1675.0000, 0.0000,   127, 64, 0,  2,  -1500\nP 2000.0000, -1675.0000, 0.0000,   127, 64, 0,  2,  -2000\nP 2500.0000, -1675.0000, 0.0000,   127, 64, 0,  2,  -2500\nP 3000.0000, -1675.0000, 0.0000,   127, 64, 0,  2,  -3000\nP 3500.0000, -1675.0000, 0.0000,   127, 64, 0,  2,  -3500\nP 4000.0000, -1675.0000, 0.0000,   127, 64, 0,  2,  -4000\nP 4500.0000, -1675.0000, 0.0000,   127, 64, 0,  2,  -4500\nP 5000.0000, -1675.0000, 0.0000,   127, 64, 0,  2,  -5000\nP 5500.0000, -1675.0000, 0.0000,   127, 64, 0,  2,  -5500\nP 6000.0000, -1675.0000, 0.0000,   127, 64, 0,  2,  -6000\nP -7503.0000, -1010.0000, 0.0000,  127, 64, 0,  2,  1000\nP -7503.0000, -510.0000, 0.0000,   127, 64, 0,  2,  500\nP -7503.0000, 0.0000, 0.0000,      127, 64, 0,  2,  0\nP -7503.0000, 490.0000, 0.0000,    127, 64, 0,  2,  -500\nP -7503.0000, 990.0000, 0.0000,    127, 64, 0,  2,  -1000\nP -7503.0000, 1490.0000, 0.0000,   127, 64, 0,  2,  -1500\nP -7503.0000, 1990.0000, 0.0000,   127, 64, 0,  2,  -2000\nP -7503.0000, 2490.0000, 0.0000,   127, 64, 0,  2,  -2500\nP -7503.0000, 2990.0000, 0.0000,   127, 64, 0,  2,  -3000\nP -7503.0000, 3490.0000, 0.0000,   127, 64, 0,  2,  -3500\nP -7503.0000, 3990.0000, 0.0000,   127, 64, 0,  2,  -4000\nP -7503.0000, 4490.0000, 0.0000,   127, 64, 0,  2,  -4500\nP -7503.0000, 4990.0000, 0.0000,   127, 64, 0,  2,  -5000\nP -7503.0000, 5490.0000, 0.0000,   127, 64, 0,  2,  -5500\nP -7503.0000, 5990.0000, 0.0000,   127, 64, 0,  2,  -6000\nP -7503.0000, 6490.0000, 0.0000,   127, 64, 0,  2,  -6500\nP -7503.0000, 6990.0000, 0.0000,   127, 64, 0,  2,  -7000\nP -7503.0000, 7490.0000, 0.0000,   127, 64, 0,  2,  -7500\nP -7503.0000, 7990.0000, 0.0000,   127, 64, 0,  2,  -8000\nP -7503.0000, 8490.0000, 0.0000,   127, 64, 0,  2,  -8500\nP -7503.0000, 8990.0000, 0.0000,   127, 64, 0,  2,  -9000\nP -7503.0000, 9490.0000, 0.0000,   127, 64, 0,  2,  -9500\nP -7503.0000, 9990.0000, 0.0000,   127, 64, 0,  2,  -10000\nP 0.0000, 10290.0000, 0.0000,      127, 64, 0,  2,  File_Set_=_eastwastes.txt  Submitted by: GidonoRewards:\n[",
    },
  },
}
