-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Frontier Mountains (frontiermtn)
-- Total Quests: 22
-- ============================================================================

return {
  zone = "frontiermtn",
  zone_name = "Frontier Mountains",
  quests = {
    {
      id = "8271",
      title = "Goblins and Fools",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Praetor Aberic",
      loc = { y = -3404.0, x = -872.0, z = -301.0 },
      triggers = {
        "Hail, Praetor Aberic",
        "goblin problem",
        "willing",
        "ready",
        "EoK",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
        { id = 126749, name = "Sathir Trade Gem", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Praetor Aberic [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Adventure\n**Quest Goal:**\n- Advancement\n**Related Zones:**\n- Temple of Droga: Goblins and Fools [zone=1096]\n**Related Creatures:**\n- Death Shaman Yugg [npc=53844]\n- Merchant Triala [npc=50997]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Oct 18 05:22:48 2016\nModified: Sat Nov 16 11:14:45 2024 | | You can obtain this quest from Praetor Aberic [npc=51126] in Frontier Mountains [EoK] at /loc -3404, -872, -301 South side of zone in middle with other quest/raid givers.\nYou say, 'Hail, Praetor Aberic'\nPraetor Aberic says 'Hello compatriot. Hopefully you were sent by the leadership in Lceanium. I've been asking for help with the potential problem here for quite some time. But internal politics isn't what you're here to discuss, is it? No, let's talk about the problem, shall we?'\nYou say, 'goblin problem'\nPraetor Aberic says 'Everyone is worried about the Sarnak or the giants, but I've been watching the goblins in the place they call Droga, and I don't think they can be ignored. From what I understand of their history, they have been disorganized and frequently spent their energies on infighting. But now a group called the Mountain Death Clan appears to have gained power. They are organized and, apparently, willing to seek allies, things that most goblins tend to avoid. I need you to get in there and weaken their structure. If you are [willing], I need you to destroy supplies and find and kill their leaders'\nYou say, 'willing'\nPraetor Aberic says 'Good! I know a secret way into their stronghold. Just let me know when you are [2] and I'll show you the way.'\nYou have received a request timer for 'Goblins and Fools': 0d:0h:5m remaining.\nYou have been assigned the task 'Goblins and Fools'.\nYou say, 'ready' Praetor Aberic says 'Let us go.'\nYou have entered The Temple of Droga\n========================================\nGoblins and Fools\nSay willing to him to get the HA.\nYou have been assigned the task 'Goblins and Fools'.\nYou say, ready to Zone in.\n**All HA versions lock after Step 3.**\n\n---\n\nSteps are random in this task. Below are a list of the steps with various versions of that step.\nNote: The east side of zone was almost completely barren of mobs, and did not have anything useful from a quest perspective.\n\n---\n\n**Step 1**\nKill 20 Mountain Death Clan goblins 0/20 (The Temple of Droga)\nKill 20 death mountain goblins, found throughout the zone.\nKill 4 drill sergeants 0/4 (The Temple of Droga)\nKill 4 drill sergeants, found deeper in the zone.\nKill 1 Trilog, Master of Flames 0/1 (The Temple of Droga)\nKill Trilog, Master of Flames.\nKill 20 Mountain Death Clan goblins 0/20 (The Temple of Droga)\nDestroy barrels of weapon oil 0/10 (The Temple of Droga)\n\n---\n\n**Step 2**\nDestroy Barrels of weapon oil 0/10 (The Temple of Droga)\nDestroy Barrels of weapon oil, found on the West side of the zone. /open them.\nKill 1 Wyg, the Dust Lord 0/1 (The Temple of Droga)\nKill Wyg, the Dust Lord.\nDestroy crates of weapon-grade steel 0/8 (The Temple of Droga)\nKill 3 weapon smiths 0/3 (The Temple of Droga)\nKill 3 weapon smiths 0/3\nKill 4 drill sergeants 0/4\n\n---\n\n**Step 3**\nSpeak with Praetor Aberic 0/1 (The Temple of Droga)\nReturn to the zone in area, just past the drop down area is Praetor Aberic, Hail him\nKill 3 weapon smiths 0/3 (The Temple of Droga)\nKill weapon smiths\nKill 1 War-Leader Grazzil 0/1 (The Temple of Droga)\nKill War-Leader Grazzil.\nKill 1 Wyg, the Dust Lord 0/1 (The Temple of Droga)\nKill 1 Death Shaman Yugg (The Temple of Droga)\nKill 1 War-leader Grazzil\nKill 1 Wyg, the Dust Lord 0/1\nKill 1 War-leader Grazzil 0/1\n\n---\n\n**Step 4**\nSpeak with Praetor Aberic 0/1 (The Temple of Droga)\nReturn to the zone in area, just past the drop down area is Praetor Aberic, Hail him\n\n---\n\nReward(s):\nRandom Cash\nExperience\nRandom amount of Sathir Trade Gems [item=126749]\n- Sathir Trade Gem [item=126749]",
    },
    {
      id = "8278",
      title = "Blood in the Mountains",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Bothrosz Aspaar",
      loc = nil,
      triggers = {
        "Hail, Bothrosz Aspaar",
        "How can I help you?",
        "EoK",
        "help",
        "Empires of Kunark",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Bothrosz Aspaar [npc=51204]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Related Creatures:**\n- a Syldon defiler [npc=51205]\n**Related Quests:**\n- Mercenary of Frontier Mountains [quest=8349]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sat Oct 22 02:43:35 2016\nModified: Tue Dec 5 05:21:04 2023 | | You say, 'Hail, Bothrosz Aspaar'\nBothrosz Aspaar looks at you with contempt and points a bloody finger at the iksar statue below. Dark magic swirls out the corners of his eyes. He appears to be asking for [help].\nYou say, 'How can I help you?'\nYou have been assigned the task 'Blood in the Mountains'.\n\n---\n\n1\\. Kill Syldon Defilers 0/10 Frontier Mountains [Empires of Kunark]\nSyldon Defilers are location on the moutaintop next to Bothrosz.\nWhen you engage the defilers they say \"You'd help the filthy Iksar? You're dead!\"\n2\\. Return to Bothrosz Aspaar 0/1 Frontier Mountains [Empires of Kunark]\nBothrosz Aspaar cackles as he surveys the sarnak corpses strewn all over the mountaintop. He throws your reward on the ground and rushes off to collect body parts.\nYou helped Bothrosz Aspaar collect the sarnak corpses he needed to perform a blood magic ritual. You got the impression that it would weaken the nearby sarnak, but you don't notice any difference.\nYou receive 5 gold .\nYou receive 106 platinum .\nYou gain experience!\n\n---\n\nReward(s):\n106pp 5gp\nExperience\n- 106pp 5gp, Experience",
    },
    {
      id = "8279",
      title = "Safety of the Herd",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Blocker Wigh",
      loc = nil,
      triggers = {
        "Hail, Blocker Wigh",
        "I will help you.",
        "EoK",
        "_Quests_",
        "Empires of Kunark version",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Blocker Wigh [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Related Creatures:**\n- a hungry brute [npc=51295]\n**Related Quests:**\n- Mercenary of Frontier Mountains [quest=8349]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sat Oct 22 02:53:46 2016\nModified: Tue Dec 5 05:21:04 2023 | | You say, 'Hail, Blocker Wigh'\nBlocker Wigh looks out at the rhinos stampeding across the plains in front of him. He spits on the ground and says, 'Coward Gnome too small and scared [help:I will help you.] herd.'\nYou say, 'I will help you.'\nYou have been assigned the task 'Safety of the Herd'.\nBlocker Wigh says 'Bad brutes eat horn herd. Kill brute. Save horn herd. Stop tiny dragons.'\n\n---\n\nKill Hungry Brutes. 0/10 Frontier Mountains [Empires of Kunark version]\nHungry brutes are located northeast of Blocker\nReturn to Blocker Wigh 0/1 Frontier Mountains [Empires of Kunark version]\nBlocker Wigh says \"Herd strong. Tiny Dragon people scared of herd! Gnome scared! Herd is Best!\"\nReward(s):\n142 platinum\nYou gain experience!\n- 142pp, Experience",
    },
    {
      id = "8280",
      title = "By Smile or By Guile",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Diplomat Dirtlick",
      loc = nil,
      triggers = {
        "Hail, Diplomat Dirtlick",
        "I will help the Legion.",
        "EoK",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Diplomat Dirtlick [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Related Quests:**\n- Mercenary of Frontier Mountains [quest=8349]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n**Appropriate Races:**\nEntered: Sat Oct 22 03:04:18 2016\nModified: Tue Dec 5 05:21:04 2023 | | You say, 'Hail, Diplomat Dirtlick'\nDiplomat Dirtlick looks frightened by your presence and says hurriedly, 'Don't kill me! Please, I need to convince these stubborn goblins that they should form a military alliance with my people. Can you [help:I will help the Legion.] me in a very... unconventional way?'\nYou say, 'I will help the Legion.'\nYou have been assigned the task 'By Smile or By Guile'.\nDiplomat Dirtlick casts an illusion on you so you appear to be a Legion soldier and says, 'I need you to pretend to be a Legion soldier and fight alongside the Drogan below. It's the fastest way to convince them the Legion would be a strong military ally!'\n_Make sure to keep this illusion until you are done with the task or else you will fail._\n\n---\n\nAid Drogan Eradicators in battle as a Burnai. 0/5 Frontier Mountains\nKill pairs of the Syldon Vanguards that are attacking the Drogan Eradicators around Droga.\nAfter you kill a pair of them you'll see an emote \"a Drogan eradicator looks at you during the break in fighting, clearly impressed.\" That counts for 1 task update. You need to kill 5 pairs total.\nReturn to Diplomat Dirtlick 0/1 Frontier Mountains\nYou say, 'Hail, Diplomat Dirtlick'\nOops! Diplomat Dirtlick tries to transform you back into your original form, but he's not very good at magic yet. He got a few things wrong.\nYour task 'By Smile or By Guile' has been updated.\nYou helped Diplomat Dirtlick convince some of the Drogan goblins that the burynai could be useful in combat against the sarnak. Which may or may not be actually true, since it was you who helped them. Diplomacy is confusing.\nYou receive 5 gold .\nYou receive 106 platinum .\nYou gain experience!!\nDiplomat Dirtlick removes your illusion and says quietly, 'I've already heard the Drogan talking about you, Dwarf. Hopefully the news continues to spread. Thank you for your aid. You may leave now.'\nReward(s):\n106pp 5gp\nExperience\n**Need more info on this quest.**\n- 106pp 5gp, Experience",
    },
    {
      id = "8282",
      title = "All Noisy on the Southern Front",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Odd Algot",
      loc = nil,
      triggers = {
        "Hail, Odd Algot",
        "I",
        "EoK",
        "_Quests_",
        "Empires of Kunark",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Odd Algot [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Time:** | Unlimited\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Related Quests:**\n- Mercenary of Frontier Mountains [quest=8349]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sat Oct 22 04:21:18 2016\nModified: Tue Dec 5 05:21:04 2023 | | You say, 'Hail, Odd Algot'\nOdd Algot eyes you suspiciously and hides one of his maracas behind his back before asking slowly, 'You come help you. me?'\nYou say, 'I'll help you.'\nYou have been assigned the task 'All Noisy on the Southern Front'.\nOdd Algot says 'Good! Go kill scalp gobbies dere who hate giants and music. So we fight tiny dragons. Save music and we dance!''\n\n---\n\nKill Drogan Scalpers 0/10 Frontier Mountains [Empires of Kunark]\nDrogan scalpers are located in the mid southern region of the zone.\nReturn to Odd Algot 0/1 Frontier Mountains\nReward(s):\n106pp 5gp\nExperience\n- 106pp 5gp, Experience",
    },
    {
      id = "8316",
      title = "Stacks of Sacs",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Vasyryx Teken`tlar",
      loc = nil,
      triggers = {
        "Hail, Vasyryx Teken`tlar",
        "represent",
        "tasks",
        "can do",
        "EoK",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
        { id = 127598, name = "Briarweb Venom Sac", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Vasyryx Teken`tlar [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Time:** | Unlimited\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Briarweb Venom Sac [item=127598]\n**Related Zones:**\n- Temple of Droga [EoK]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Oct 25 19:26:32 2016\nModified: Tue Dec 5 05:21:04 2023 | | You say, 'Hail, Vasyryx Teken`tlar'\nVasyryx Teken`tlar says 'Hello Burynai. I welcome you to Kunark on behalf of the Combine. I, obviously, officially (represent) that entity. You are not considering entering the (Temple of Droga), are you?'\nYou say, 'represent'\nVasyryx Teken`tlar says 'My task is to learn as much as I can of the goblins of Droga. My overseer is called Praetor Denik, who is responsible for most of the, um, outreach we are doing. To that end, I have several (tasks) that I need to find someone to accomplish for me. Apparently my knowledge is too valuable to be risked. I am to find adventurers to (assist) me.'\nYou say, 'tasks'\nVasyryx Teken`tlar says 'Simple things, really. Only brute strength required. Is this something you (can do) for us?'\nYou say, 'can do'\nVasyryx Teken`tlar says 'Ah, good. I knew not to expect too much mental effort from you.'\nYou have been assigned the task 'Stacks of Sacs'.\n\n---\n\nCollect 7 Briarweb Venom Sac(s) 0/7 The Temple of Droga\nThey drop off spiders and are pre lootable.\nDeliver 7 Briarweb Venom Sac to Vasyryx Teken`tlar\nReward(s):\n106 platinum 5 gold\nYou gain experience!!\n- 106pp 5gp, Experience",
    },
    {
      id = "8317",
      title = "Mounds of Mud",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Vasyryx Teken`tlar",
      loc = nil,
      triggers = {
        "Hail, Vasyryx Teken`tlar",
        "Temple of Droga",
        "title",
        "appeased",
        "represent",
        "tasks",
        "can do",
        "EoK",
      },
      items_required = {
      },
      rewards = {
        { id = 127626, name = "Living Mudball", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Vasyryx Teken`tlar [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Time:** | Unlimited\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Living Mudball [item=127626]\n**Related Zones:**\n- Temple of Droga [EoK]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Oct 25 19:28:48 2016\nModified: Fri Nov 15 09:07:17 2024 | | You say, 'Hail, Vasyryx Teken`tlar'\nVasyryx Teken`tlar says 'Hello Burynai. I welcome you to Kunark on behalf of the Combine. I, obviously, officially (represent) that entity. You are not considering entering the (Temple of Droga), are you?'\nYou say, 'Temple of Droga'\nVasyryx Teken`tlar says 'Let me tell you what we know of the recent history of the place before you consider entering. It seems that three or four generations ago the citizens, if a mine can have citizens, of Droga grew restless. Revolt was imminent when one of the royal line, apparently they are all called Dronan, which makes tracking their history very challenging, challenged the reigning king to a duel. The younger Dronan one, and the citizens were appeased. This ended the official line of 'royalty' among the goblins. The new leader returned to the (title) 'chief'.'\nYou say, 'title'\nVasyryx Teken`tlar says 'As far as I can tell, all they have done is traded the title 'king' for 'chief'. They still pass the title down, at least for the last three or so generations, through the family of their leader. It seems that the citizenry of the mines are (appeased) by the simple change of nomenclature.'\nYou say, 'appeased'\nVasyryx Teken`tlar says 'Certainly. But this has not prevented all strife. From what we have been able to gather from a few escaped slaves, the priesthood is unhappy with the level of worship, of Rallos Zek, I would assume. We assume this is their god. Of course when the priesthood claims that there is not enough faith, that generally just means that the priesthood feels ignored or wants more power for themselves. But who am I to judge such things'\nYou say, 'represent'\nVasyryx Teken`tlar says 'My task is to learn as much as I can of the goblins of Droga. My overseer is called Praetor Denik, who is responsible for most of the, um, outreach we are doing. To that end, I have several (tasks) that I need to find someone to accomplish for me. Apparently my knowledge is too valuable to be risked. I am to find adventurers to (assist) me.'\nYou say, 'tasks'\nVasyryx Teken`tlar says 'Simple things, really. Only brute strength required. Is this something you (can do) for us?'\nYou say, 'can do'\nVasyryx Teken`tlar says 'Ah, good. I knew not to expect too much mental effort from you.'\nYou have been assigned the task 'Mounds of Mud'.\n\n---\n\nCollect 3 Living Mudball(s) 0/3 The Temple of Droga\nThey drop off mudmans.\n**Map file location of Mudmen: Insert this into your map file for Temple of Droga.**\nP 913.6794, 554.1532, -174.0620, 0, 0, 0, 2, mudmen\nDeliver 3 Living Mudball to Vasyryx Teken`tlar.\nReward(s):\n106 platinum 5 gold\nYou gain experience!!\n- 106pp 5gp, Experience",
    },
    {
      id = "8318",
      title = "Drogan Toes",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Vasyryx Teken`tlar",
      loc = { y = -3399.0, x = -881.0, z = -303.0 },
      triggers = {
        "Hail, Vasyryx Teken`tlar",
        "Temple of Droga",
        "title",
        "appeased",
        "represent",
        "tasks",
        "can do",
        "EoK",
      },
      items_required = {
      },
      rewards = {
        { id = 127535, name = "Drogan Toes", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Vasyryx Teken`tlar [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Success Lockout Timer**: 00:30:00\n**Quest Items:**\n- Drogan Toes [item=127535]\n**Related Zones:**\n- Temple of Droga [EoK]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Oct 25 19:29:45 2016\nModified: Tue Dec 5 05:21:04 2023 | | Find Vasyryx Teken`tlar in Frontier Mountains at -3399, -881, -303. She is on CTRL F.\nYou say, 'Hail, Vasyryx Teken`tlar'\nVasyryx Teken`tlar says 'Hello Burynai. I welcome you to Kunark on behalf of the Combine. I, obviously, officially (represent) that entity. You are not considering entering the (Temple of Droga), are you?'\nYou say, 'Temple of Droga'\nVasyryx Teken`tlar says 'Let me tell you what we know of the recent history of the place before you consider entering. It seems that three or four generations ago the citizens, if a mine can have citizens, of Droga grew restless. Revolt was imminent when one of the royal line, apparently they are all called Dronan, which makes tracking their history very challenging, challenged the reigning king to a duel. The younger Dronan one, and the citizens were appeased. This ended the official line of 'royalty' among the goblins. The new leader returned to the (title) 'chief'.'\nYou say, 'title'\nVasyryx Teken`tlar says 'As far as I can tell, all they have done is traded the title 'king' for 'chief'. They still pass the title down, at least for the last three or so generations, through the family of their leader. It seems that the citizenry of the mines are (appeased) by the simple change of nomenclature.'\nYou say, 'appeased'\nVasyryx Teken`tlar says 'Certainly. But this has not prevented all strife. From what we have been able to gather from a few escaped slaves, the priesthood is unhappy with the level of worship, of Rallos Zek, I would assume. We assume this is their god. Of course when the priesthood claims that there is not enough faith, that generally just means that the priesthood feels ignored or wants more power for themselves. But who am I to judge such things'\nYou say, 'represent'\nVasyryx Teken`tlar says 'My task is to learn as much as I can of the goblins of Droga. My overseer is called Praetor Denik, who is responsible for most of the, um, outreach we are doing. To that end, I have several (tasks) that I need to find someone to accomplish for me. Apparently my knowledge is too valuable to be risked. I am to find adventurers to (assist) me.'\nYou say, 'tasks'\nVasyryx Teken`tlar says 'Simple things, really. Only brute strength required. Is this something you (can do) for us?'\nYou say, 'can do'\nVasyryx Teken`tlar says 'Ah, good. I knew not to expect too much mental effort from you.'\nYou have been assigned the task 'Drogan Toes'.\n\n---\n\n3. Collect 8 Drogan Toes. 0/8 The Temple of Droga [Empires of Kunark]\n\n\n\nThe Drogan Toes are pre lootable.\n\n\n---\n\nReward(s):\n106pp 5gp\nExperience (1AA at level 105)\n**Need more info on this quest.**\n- 106pp 5gp, Experience",
    },
    {
      id = "8382",
      title = "Informal Diplomacy",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Agent Honeydrop",
      loc = nil,
      triggers = {
        "Hail, Stak",
        "EoK",
        "_Combine Operative_",
        "_Blacksmith_",
        "_Warmonger_",
        "Inside fort",
      },
      items_required = {
        { name = "Huge Food Bundle to it", count = 1 },
      },
      rewards = {
        { id = 127744, name = "Frontier Lumber", type = "item" },
        { id = 127743, name = "Frontier Ore", type = "item" },
        { id = 127745, name = "Frontier Silk", type = "item" },
        { id = 127611, name = "Giant Burlap Sheet", type = "item" },
        { id = 127612, name = "Huge Bear Tendon", type = "item" },
        { id = 127614, name = "Huge Brute Brain", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Agent Honeydrop [ _Combine Operative_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Success Lockout Timer**: 00:01:00\n**Quest Items:**\n- Frontier Lumber [item=127744]\n- Frontier Ore [item=127743]\n- Frontier Silk [item=127745]\n- Giant Burlap Sheet [item=127611]\n- Huge Bear Tendon [item=127612]\n- Huge Brute Brain [item=127614]\n- Huge Food Bundle [item=127740]\n- Huge Goblin Leg [item=127613]\n- Huge Resource Bundle [item=127746]\n- Huge Sarnak Tail [item=127601]\n- Huge Wolf Flank [item=127646]\n**Related Creatures:**\n- Gasi [ _Blacksmith_]\n- Stak [ _Warmonger_]\n- a Drogan hulk [npc=51293]\n- a Konikor evacuee [npc=51864]\n- a Legion miner [npc=51124]\n- a grove guardian [npc=51280]\n- a highweb spitter [npc=51283]\n- a huge frontier bear [npc=51125]\n- a huge frontier brute [npc=51300]\n- an experimental behemoth [npc=51261]\n**Related Quests:**\n- Concerned Citizens [quest=8272]\n- Contacting the Leadership [quest=8385]\n- Disappearing Dragons [quest=8262]\n- Pentalateral Negotiations [quest=8453]\n- Sneaky Sarnak [quest=8392]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Nov 14 07:21:19 2016\nModified: Sun Sep 8 03:20:59 2024 | | Prerequisite: Concerned Citizens [quest=8272], Contacting the Leadership [quest=8385], Disappearing Dragons [quest=8262], Sneaky Sarnak [quest=8392], and Pentalateral Negotiations [quest=8453].\nThis is a shared task.\nSpeak to Agent Honeydrop in Frontier Mountains.\nSay \"help\" to her to get this task.\n\n---\n\n1\\. Speak with Stak the Warmonger. Inside the large central fortress. 0/1 Frontier Mountains\nHe assigns you step two and gives you a giant to escort\n2\\. Lead a Konikor Warmonger to the Western Sarnak Outposts 0/1 Frontier Mountains\nThis step updates at /way 364, 2541, 126 at the west part of the zone not far from the outpost.\n3\\. Kill sarnak for the Konikor Warmonger 0/5 Frontier Mountains\nYour accomplice heads back and leaves you with five collect tasks. You can find sarnaks in the western part of the zone in the fort neat the waypoint from the previous step.\nA Giant Burlap Sheet will be placed in your inventory.\n4\\. Collect Huge Bear Tendons 0/3 Frontier Mountains\nDrops from a huge frontier bear, not from a frontier bear. You can find bears in the southwestern part of the zone not far from Earthcaller Quill which is on the find tool CTRL F.\n5\\. Collect Huge Goblin Legs 0/3 Frontier Mountains\nHill above Droga entrance. South of the druid rings. Also south wall, east side. Drops from a Drogan hulk.\n6\\. Collect Huge Wolf Flanks 0/3 Frontier Mountains\nNorth center to North east. Drops from a huge frontier wolf, but not from a frontier wolf.\nNote: if none are up kill frontier wolf and wait for respawns.\n7\\. Collect Huge Brute Brains 0/3 Frontier Mountains\nAlong the east wall. Drops from a huge frontier brute, but not from an invading brute or a frontier brute.\n8\\. Collect Huge Sarnak Tails 0/3 Frontier Mountains\nHuge Sarnak Tails can not be prelooted.\nFrom the same fort that was in the prior step. Drops from an experimental behemoth, but not from an enchanted Sydon stalker, a Sarmak peacekeeper or a syldon greenhorn. [Inside fort]\n9\\. Use Giant Burlap Sheet to bundle up all the body parts 0/1 Frontier Mountains\nThis appeared in your inventory at the end of step 3. Just click it. It's not a container and it's tradeable. Clicking puts a Huge Food Bundle in your inventory\n10\\. Travel to Konikor's central fort 0/1 Frontier Mountains\nThis step updates around /way 154, -953, -148 outside the central giant fort on the north wall.\n11\\. Give Huge Food Bundle to a Konikor Evacuee 0/1 Frontier Mountains\nAfter the update on step 10 a Konikor evacuee spawns and follows you. Give Huge Food Bundle to it.\n12\\. Lead a Konikor evacuee to Stak 0/1 Frontier Mountains\nStak is in the giant fort near the north side. Hail Stak for the update. Listen to Stak's Speech.\n13\\. Listen to Stak's speech 0/1 Frontier Mountains\nFollow Stak until he stops. He speaks a bunch of dialogue.\n14\\. Speak with Gasi the Blacksmith 0/1 Frontier Mountains\nGasi the Blacksmith is in the giant fort in the building on the north side. Hail him and you get three more collect steps.\n15\\. Collect Frontier Ore from Legion miners 0/6 Frontier Mountains\nYou can find legion miners near a cave in the southwestern part of the zone near /way -2016, 2306, -324. They respawn fairly quickly, within a few minutes.\n16\\. Collect Frontier Lumber from Grove Guardians 0/6 Frontier Mountains\nYou can find grove guardians near the druid ring in the northwest corner of the zone.\n17\\. Collect Frontier Silk from Highland Weavers 0/6 Frontier Mountains\nThese drop from spiders in the southeastern part of the zone.\n18\\. Use the Giant Burlap Sheet to bundle up all the materials 0/1 Frontier Mountains\nRight click the Giant Burlap Sheet once you have the above materials. This makes a Huge Resource Bundle that shows up in your inventory.\n19\\. Give the Huge Weapon Bundle to Gasi 0/1 Frontier Mountains\nIt's actually called Huge Resource Bundle.\nGasi eagerly grabs the supplies from you. He smiles and shouts, \" XXX bring us stuff for weapons! Soon we ready to war!\n20\\. Speak with Stak 0/1 Frontier Mountains\nYou say, 'Hail, Stak'\nStak nods and says, 'Thanks Barbarian, Time next step. You stay. We take from here.'\nYou gain experience!\nStak says, 'Walk with me if want. I meet with Honey now.'\nStak walks West, and meets Honey\nStak say, 'Goo see you, Honey. Ready go?'\nAgent Honeydrop smiles at you and nods in greeting.\nAgent Honeydrop says, 'I trust my agent coordinated all of the preparations with you, Stak? Is everything taken care of?'\nStak nods and says, 'Agent good. Konikor angry, ready fight. Have weapons. Below close.'\nAgent Honeydrop says, 'Good. Then let's get going. We need to convince your reluctant friends below to join our cause quickly if we don't want to be overrun. I trust you have a few more tricks up your sleeve, Stak.'\nStaks says, 'Of course, Honey.'\nAgent Honeydrop says, 'You're testing my patience, Stak. I've told you a hundred times to call me Agent, not Honey. I know you do it on purpose!'\nAgent Honeydrop sighs.\nAgent Honeydrop says, 'You did well here, Agent. I'll be in touch soon. Our next brunch will be glorious.'\n\n---\n\nReward(s):\n638pp\nExperience or 10 AA's\n**Submitted by:** Deloehne\n- 638pp, Experience or 10 AA's",
    },
    {
      id = "8409",
      title = "Sarnak Among Us",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Urul Twigslam",
      loc = nil,
      triggers = {
        "EoK",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
        { id = 127747, name = "Syldon Spy Log", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Urul Twigslam [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Lore\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 00:30:00\n**Quest Items:**\n- Syldon Spy Log [item=127747]\n**Related Creatures:**\n- Rala`zan the Mindshadow [npc=51707]\n- Rikk`ti Crikk`t [npc=51253]\n- a Syldon deserter [npc=51695]\n- a Syldon lavamancer [npc=54226]\n- a mega lavabomb [npc=59971]\n- a siege lavabomb [npc=59972]\n**Related Quests:**\n- Partisan of Frontier Mountains [quest=8350]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n**Appropriate Races:**\nEntered: Fri Dec 2 01:17:51 2016\nModified: Sat Nov 16 08:35:11 2024 | | Pre req: You'll need to have completed the following tasks in order to request this task.\nConcerned Citizens [quest=8272], Contacting the Leadership [quest=8385], Disappearing Dragons [quest=8262], Sneaky Sarnak [quest=8392] and Rocks Boom for Twigslam [quest=8410].\nSpeak to Urul Twigslam [npc=51230] to request this task. He is located in the big giant fort mid zone on the west side.\nSay book to request the task.\n\n---\n\n1\\. Read the Syldon Spy Log [item=127747] that Urul Twigslam found 0/6 Frontier Mountains\nHe gives you the spy log, right click it 6 times until it updates the task.\n2\\. Tell Urul what you found in the log 0/1 Frontier Mountains\nHail Urul Twigslam [npc=51230] and go through his dialogue.\n3\\. Find the Syldon spy South of Konikor 0/1 Frontier Mountains\nThe spy is located directly south of the giant fort. It's name is a Syldon deserter [npc=51695]. The task will update at it.\n4\\. Confront the nearby Syldon Spy 0/1 Frontier Mountains\nHail the a Syldon deserter [npc=51695] and follow its dialogue. Be ready for back to back fights.\nBug - if you /say the bracketed text to the spy he does not respond but if you click on the bracketed text the task updates\n5\\. Kill Drogan Burrowers 0/4 Frontier Mountains\nKill all 4 of them, they should spawn right after you talk to the Syldon deserter.\n6\\. Kill Dominated Wormcallers 0/2 Frontier Mountains\nKill the worms.\n7\\. Kill Rala`zan the Mindshadow [npc=51707] 0/1 Frontier Mountains\nThe deserter turns into this named, kill it.\n8\\. Find the Syldon spies South of Nearpost in the East 0/1 Frontier Mountains\nThe nearpost is located in the east south east part of the zone. This part of the task will update at Rikki`ti Crikk`t [npc=51253], it is located south of the nearpost.\n9\\. Confront the Syldon spies above Nearpost 0/1 Frontier Mountains\nHail Rikki`ti Crikk`t [npc=51253] and go through its dialogue.\n10\\. Kill Siege Lavabombs 0/6 Frontier Mountains\n6 Lavabombs will spawn in total, 2 at a time. They CANNOT be snared, rooted or mezzed. Kill them before they reach the tower. Chanter can knock them back.\n11\\. Kill Syldon Lavamancers 0/2 Frontier Mountains\nKill Syldon lavamancers.\n12\\. Kill Mega Lavabomb 0/1 Frontier Mountains\nKill it very fast. They CANNOT be snared, rooted or mezzed. Chanter can knock them back. If you fail, Rikki`ti Crikk`t [npc=51253] should spawn about 20 seconds later and you can rehail to start over.\n13\\. Return to speaker Urul 0/1 Frontier Mountains\nHail Urul Twigslam [npc=51230] back at the big giant fort. Go through his dialogue.\n\n---\n\nReward(s):\n283pp 5gp\nExperience\n**Submitted by:** Gidono\n- 283pp 5gp, Experience",
    },
    {
      id = "8410",
      title = "Rocks Boom for Twigslam",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Urul Twigslam",
      loc = { y = -1898.7, x = 2094.4, z = -324.45 },
      triggers = {
        "EoK",
        "_Quests_",
      },
      items_required = {
        { name = "him the Hyper-condensed Coal", count = 1 },
        { name = "Seething Sulfur  to Urul 0/1 Frontier Mountains", count = 1 },
        { name = "it to him", count = 1 },
      },
      rewards = {
        { id = 126780, name = "Hyper-condensed Coal", type = "item" },
        { id = 127590, name = "Saturated Ley Nitre", type = "item" },
        { id = 127592, name = "Seething Sulfur", type = "item" },
        { id = 126780, name = "condensed Coal", type = "item" },
        { id = 126780, name = "condensed Coal", type = "item" },
        { id = 126780, name = "condensed Coal", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Urul Twigslam [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Time:** | 6 Hours\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Success Lockout Timer**: 00:01:00\n**Quest Items:**\n- Hyper-condensed Coal [item=126780]\n- Saturated Ley Nitre [item=127590]\n- Seething Sulfur [item=127592]\n**Related Quests:**\n- Partisan of Frontier Mountains [quest=8350]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Fri Dec 2 01:57:36 2016\nModified: Tue Nov 12 01:44:04 2024 | | Pre req: You'll need to have the following tasks done in order to request this task.\nConcerned Citizens [quest=8272], Contacting the Leadership [quest=8385], Disappearing Dragons [quest=8262] and Sneaky Sarnak [quest=8392].\nFind Urul Twigslam [npc=51230] in Frontier Mountains. He is located in the big giant fort located near mid zone on the west side of the giant fort.\nSay help to him to get the task.\n\n---\n\n1. Persuade Urul that you're useful 0/1 Frontier Mountains\n\n\n\nHail Urul Twigslam [npc=51230] and go though his dialogue.\n\n2. Collect Saturated Ley Nitre [item=127590] 0/1 Frontier Mountains\n\n\n\nKill the drogans in the south part of the zone and loot a Saturated Ley Nitre [item=127590].\n\n3. Collected Hyper-condensed Coal [item=126780] 0/1 Frontier Mountains\n\n\n\nThere is a cave northeast of the Scorched Woods zone line. A bucket inside the Burnyai cave at /loc -1898.70, +2094.40, -324.45, click on it to get the coal.\n\n4. Collect Seething Sulfur [item=127592] 0/1 Frontier Mountains\n\n\n\nThis drops off the Syldon miners found in the northwest corner of the zone.\n\n5. Give Saturated Ley Nitre [item=127590] to Urul 0/1 Frontier Mountains\n\n\n\nGive the Saturated Ley Nitre [item=127590] to Urul Twigslam [npc=51230].\n\n6. Give Hyper-condensed Coal [item=126780] to Urul 0/1 Frontier Mountains\n\n\n\nGive him the Hyper-condensed Coal [item=126780].\n\n7. Give Seething Sulfur [item=127592] to Urul 0/1 Frontier Mountains\n\n\n\nGive it to him.\n\n8. Convince Urul to swear an oath of loyalty 0/1 Frontier Mountains\n\n\n\nHail him and go through his dialogue.\n\n\n\n\n\n\nReward(s):\n\n\n177pp 5gp\n\n\nExperience\n**Submitted by:** Gidono\n- 177pp 5gp, Experience",
    },
    {
      id = "8431",
      title = "Methods of Sarnak Destruction",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Ingisitorma Varro",
      loc = { y = 1873.0, x = -1648.0, z = 255.0 },
      triggers = {
        "EoK",
        "_Quests_",
        "failed",
        "success",
      },
      items_required = {
      },
      rewards = {
        { id = 127835, name = "Ancient Sarnak Bones", type = "item" },
        { id = 127842, name = "Cleaned Korshan Sarnak Scale", type = "item" },
        { id = 127837, name = "Cleaned White Dragon Scale", type = "item" },
        { id = 127836, name = "Cloudy Brown Liquid", type = "item" },
        { id = 127599, name = "Dronan Ore", type = "item" },
        { id = 127843, name = "Enchanted Ancient Sarnak Bones", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Ingisitorma Varro [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Success Lockout Timer**: 00:01:00\n**Quest Items:**\n- Ancient Sarnak Bones [item=127835]\n- Cleaned Korshan Sarnak Scale [item=127842]\n- Cleaned White Dragon Scale [item=127837]\n- Cloudy Brown Liquid [item=127836]\n- Dronan Ore [item=127599]\n- Enchanted Ancient Sarnak Bones [item=127843]\n- Enchanted Dronan Ore [item=127840]\n- Enchanted Giant Lymph Fluid [item=127839]\n- Enchanted Imperial Ore [item=127841]\n- Enchanted Meteorite Fragment [item=127838]\n- Giant Lymph Node [item=127550]\n- Imperial Ore [item=127774]\n- Intact White Dragon Scale [item=127310]\n- Korshan Portal Resonance [item=127844]\n- Korshan Sarnak Scale [item=127814]\n- Mana of the Sarnak [item=127952]\n- Mana of the Sarnak Compressor [item=127772]\n- Metallurgy of Souls [item=127628]\n- Meteorite Fragment [item=127302]\n- Vial of Viscous Mana [item=14352]\n**Related Zones:**\n- Chardok [EoK]\n- Frontier Mountains [EoK]\n- Gates of Kor-Sha [zone=1091]\n- Kor-Sha Laboratory [zone=1092]\n- Lceanium [zone=1086]\n- Scorched Woods [zone=1087]\n- Temple of Droga [EoK]\n**Related Quests:**\n- Essence of the Dragon I (Group) [quest=8376]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 13 02:34:04 2016\nModified: Thu Feb 27 21:37:34 2025 | | Pre Req:\n\\- Achievement: Partisan of Lceanium (Concerned Citizens, Contacting the Leadership, Disappearing Dragons, Sneaky Sarnak)\n\\- Achievement: Partisan of The Scorched Woods (Digging Yourself Deeper, The Last Grove, Where is Burning Woods?, On Nobody's Side)\n\\- Achievement: Partisan of Frontier Mountains (Pentalateral Negotiations, Informal Diplomacy, Rocks Boom for Twigslam, Sarnak Among Us)\n\\- Achievement: Partisan of The Temple of Droga (Corrupt Before the Fall, Purifying the Purifier, Corrupting the Corrupt, Pure Success, Rebellion of the Pure)\n\\- Achievement: Mercenary of Gates of Kor-Sha (Preparations for Forward Action I, Preparations for Forward Action II, Preparations for Forward Action III)\n\\- Probing the Fortress, Their Own Medicine, Destabilizing Chardok (from Partisan of Chardok)\n\\- Investigating the Mysterious Sarnak (from Partisan of Kor-Sha Laboratory)\nTalk to Ingisitorma Varro [npc=51218] in Frontier Mountains to get this task.\nSay task to get the task.\n\n---\n\n**Collect 2 of each drop, they are pre lootable. Later in the quest you'll need another of each for some combines.**\n02. Collect 1 Intact White Dragon Scale [item=127310] 0/1 Lceanium\n\n\n\nKill Yeti's to the east of the city in Lceanium. Loot a Intact White Dragon Scale.\n\n03. Collect 1 Meteorite Fragment [item=127302] 0/1 Scorched Woods\n\n\n\nMeteorite Fragment drops from the Burynai at the crater in Scorched Woods.\n\n04. Collect 1 Giant Lymph Node [item=127550] 0/1 Frontier Mountains\n\n\n\nGiants in Frontier Mountains at the fort mid zone drop the Giant Lymph Node.\n\n05. Collect 1 Dronan Ore [item=127599] 0/1 The Temple of Droga\n\n\n\nDronan Ore drops from Goblins in Temple of Droga.\n\n06. Collect 1 Imperial Ore [item=127774] 0/1 Chardok\n\n\n\nTravel to Chardok. Imperial Ore drops from multitude of mobs. Click on them item link above to get a listing of mobs we have on record dropping it.\n\n07. Collect 1 Korshan Sarnak Scale [item=127814] 0/1 Gates of Kor-Sha\n\n\n\nSarnak's in Gates of Kor-Sha drop the Korshan Sarnak Scale.\n\n08. Collect 1 Ancient Sarnak Bones [item=127835] 0/1 Kor-Sha Laboratory\n\n\n\nAncient Sarnak Bones drop from Goblins in Kor-Sha Laboratory.\n\n09. Create a Mana of the Sarnak 0/1 \\- ( Recipe)\n\n\n\n\nIn a forge, combine all 7 items. Trivial at 202, You MAY fail.\n\n\n\n\nIf successful, the item will disappear and you will see the following.\n\n\n\n\nYou have fashioned the items together to create something new: Cloudy Brown Liquid.\n\n\n\n\nThe mixture boils and bubbles, quickly expanding to crack the vial you put it in. It quickly pours out and falls grossly to the ground only to quickly evaporate into a pungent cloud.\n\n10. Tell Ingisitorma Varro [npc=51218] that your first attempt [failed] 0/1 Frontier Mountains\n\n\n\nHead back to Ingisitorma Varro in Frontier Mountains. Hail him and then say smiths.\n\n11. Collect 1 Metallurgy of Souls [item=127628] 0/1 Brell's Temple\n\n\n\nNow you'll need to travel out of expansion back to the Underfoot expansion to Brell's Temple. The Metallurgy of Souls (book) is a ground spawn on a table near Brell Serilis.\n\n12. Collect 1 Cleaned White Dragon Scale [item=127837] 0/1 \\- ( Recipe [item=127837])\n\n\n\n\nIn a mixing bowl, combine 1 Intact White Dragon Scale and 1 Vial of Viscous Mana [item=14352].\n\n13. Collect 1 Enchanted Meteorite Fragment [item=127838] 0/1 \\- ( Recipe)\n\n\n\n\nIn a forge, combine 1 Vial of Viscous Mana and 1 Meteorite Fragment.\n\n14. Collect 1 Enchanted Giant Lymph Fluid [item=127839] 0/1 \\- ( Recipe)\n\n\n\n\nIn a Brew Barrel, combine 1 Vial of Viscous Mana and 1 Giant Lymph Node.\n\n15. Collect 1 Enchanted Dronan Ore [item=127840] 0/1 \\- ( Recipe)\n\n\n\n\nIn a forge, combine 1 Vial of Viscous Mana and 1 Dronan Ore.\n\n16. Collect 1 Enchanted Imperial Ore [item=127841] 0/1 \\- ( Recipe)\n\n\n\n\nIn a forge, combine 1 Vial of Viscous Mana and 1 Imperial Ore.\n\n17. Collect 1 Cleaned Korshan Sarnak Scale [item=127842] 0/1 \\- ( Recipe)\n\n\n\n\nIn a mixing bowl, combine 1 Vial of Viscous Mana [item=14352] and 1 Korshan Sarnak Scale.\n\n18. Collect 1 Korshan Portal Resonance [item=127844] 0/1\n\n\n\nIn Gates of Kor-Sha, go to the farthest east portion of the zone and stand on the portal at /loc +1873, -1648, +255 with a Vial of Viscous Mana [item=14352] in your inventory. You should receive Korshan Portal Resonance.\n\n19. Collect 1 Enchanted Ancient Sarnak Bones [item=127843] 0/1 \\- ( Recipe)\n\n\n\n\nIn a oven, combine 1 Vial of Viscous Mana and 1 Ancient Sarnak Bones.\n\n20. Create 1 Mana of the Sarnak [item=127952] using tradeskills 0/1 \\- ( Recipe) Trivial < 115\n\n\n\n\nIn a forge, combine 1 Cleaned Korshan Sarnak Scale, 1 Cleaned White Dragon Scale, 1 Enchanted Ancient Sarnak Bone, 1 Enchanted Dronan Ore, 1 Enchanted Giant Lymph Node, 1 Enchanted Meteorite Fragment, 1 Enchanted Imperial Ore, 1 Korshan Portal Resonance.\n\n\n\n\nIt has been reported you can do an alternative combine to get this item. I need confirmation for the recipe to make Mana of the Sarnak Compressor [item=127772]. ( Recipe)\n\n21. Report your [success] to Ingisitorma Varro [npc=51218] 0/1 Frontier Mountains\n\n\n\nOn completion you get the achievement Essence of the Dragon I (Group) [quest=8376] that grants you the first rank of the special AA \"Essence of the Dragon\". You also get the mercenary AA \"Essence of the Dragon\" for your mercenary.\n**Submitted by:** Gidono\n- 638pp, Experience, AA: Essence of the Dragon, Merc",
    },
    {
      id = "8432",
      title = "Investigating the Mysterious Sarnak",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Ingisitorma Varro",
      loc = { y = 3701.0, x = -3081.0, z = 165.0 },
      triggers = {
        "EoK",
        "_Quests_",
        "banished",
      },
      items_required = {
        { name = "the Tuned Elimination Device to Ingistorma Varro", count = 1 },
      },
      rewards = {
        { id = 127829, name = "Chokidai Sample", type = "item" },
        { id = 127824, name = "Chokidai Sample", type = "item" },
        { id = 127818, name = "Elimination Device", type = "item" },
        { id = 127826, name = "Goblin Sample", type = "item" },
        { id = 127823, name = "Insect Sample", type = "item" },
        { id = 127827, name = "Insect Sample", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Ingisitorma Varro [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Success Lockout Timer**: 00:01:00\n**Quest Items:**\n- Chokidai Sample [item=127829]\n- Chokidai Sample [item=127824]\n- Elimination Device [item=127818]\n- Goblin Sample [item=127826]\n- Insect Sample [item=127823]\n- Insect Sample [item=127827]\n- Kor'Sha Quartz [item=127305]\n- Mysterious Sarnak Research Powder [item=127627]\n- Sarnak Sample [item=127825]\n- Sarnak Sample [item=127828]\n- Snake Sample [item=127822]\n- Tuned Elimination Device [item=127821]\n**Related Quests:**\n- Concerned Citizens [quest=8272]\n- Contacting the Leadership [quest=8385]\n- Corrupt Before the Fall [quest=8724]\n- Corrupting the Corrupt [quest=8725]\n- Destabilizing Chardok [quest=8457]\n- Digging Yourself Deeper [quest=8395]\n- Disappearing Dragons [quest=8262]\n- Informal Diplomacy [quest=8382]\n- On Nobody's Side [quest=8381]\n- Partisan of Kor-Sha Laboratory [quest=8357]\n- Pentalateral Negotiations [quest=8453]\n- Preparations for Forward Action I [quest=8498]\n- Preparations for Forward Action II [quest=8773]\n- Preparations for Forward Action III [quest=8774]\n- Probing the Fortress [quest=8389]\n- Pure Success [quest=8726]\n- Purifying the Purifier [quest=8723]\n- Rebellion of the Pure [quest=8727]\n- Rocks Boom for Twigslam [quest=8410]\n- Sarnak Among Us [quest=8409]\n- Sneaky Sarnak [quest=8392]\n- The Last Grove [quest=8363]\n- Their Own Medicine [quest=8455]\n- Where is Burning Woods? [quest=8403]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 20 16:55:18 2016\nModified: Wed Dec 4 23:50:30 2024 | | Pre Req: The following tasks must be completed before requesting this task.\nConcerned Citizens, Contacting the Leadership, Disappearing Dragons, Sneaky Sarnak, Digging Yourself Deeper, The Last Grove, Where is Burning Woods?, On Nobody's Side, Pentalateral Negotiations, Informal Diplomacy, Rocks Boom for Twigslam, Sarnak Among Us, Probing the Fortress, Their Own Medicine, Destabilizing Chardok, Corrupt Before the Fall, Purifying the Purifier, Corrupting the Corrupt, Pure Success, Rebellion of the Pure, Preparations for Forward Action I, Preparations for Forward Action II and Preparations for Forward Action III.\nFind Ingisitorma Varro [npc=51218] in Frontier Mountains located in the northeast corner of the zone at 3701, -3081, 165.\nRequest Phrase: task\n\n---\n\nCollect 1 Kor'Sha Quartz 0/1 Gates of Kor-Sha\nThese Quartz pieces are ground spawns in the pond near the Frontier Mountains zone line area.\nCreate 1 Tuned Elimination Device using tradeskills 0/1\nIngistorma gave you a Elimination Device, put the Kor'Sha Quartz in it and combine, making a Tuned Elimination Device.\nObtain a sample from a sarnak 0/1 Gates or Kor-Sha\nIn Gates of Kor-Sha, kill Sarnak until you get a Sarnak Sample. Stick it in the Tuned Elimination Device and combine. Resulting in a Mysterious Research Powder.\nObtain a sample from a chokadai 0/1 Gates of Kor-Sha\nIn Gates of Kor-Sha, kill Chokadai until you loot a Chokadai Sample. Stick it in the Tuned Elimination Device and combine. Resulting in a Mysterious Research Powder.\nObtain a sample from a snake 0/1 Gates of Kor-Sha\nIn Gates of Kor-Sha, kill Snakes until you loot a Snake Sample. Stick it in the Tuned Elimination Device and combine. Resulting in a Mysterious Research Powder.\nObtain a sample from an insect 0/1 Gates of Kor-Sha\nIn Gates of Kor-Sha, kill Insects until you loot a Insect Sample. Stick it in the Tuned Elimination and combine. Resulting in a Mysterious Research Powder.\nObtain a sample from a goblin 0/1 Kor-Sha Laboratory\nIn Kor-Sha Laboratory, kill Goblins until you loot a Goblin Sample. Stick it in the Tuned Elimination Device and combine. Resulting in a Mysterious Research Powder.\nObtain a sample from a sarnak 0/1 Kor-Sha Laboratory\nIn Kor-Sha Laboratory, kill Sarnak until you loot a Sarnak Sample. Stick it in the Tuned Elimination Device and combine. Resulting in a Mysterious Research Powder.\nObtain a sample from a chokadai 0/1 Kor-Sha Laboratory\nIn Kor-Sha Laboratory, kill chokadai until you loot a Chokadai Sample. Stick it in the Tuned Elimination Device and combine. Resulting in a Mysterious Research Powder.\nObtain a sample from an insect 0/1 Kor-Sha Laboratory\nIn Kor-Sha Laboratory, kill insects until you loot a Insect Sample. Stick it in the Tuned Elimination Device and combine. Resulting in a Mysterious Research Powder.\nDeliver 8 mysterious Sarnak Research Powder to Ingistorma Varro 0/1 Frontier Mountains\nIn Frontier Mountains, deliver all of these Mysterious Research Powders to Ingistorma Varro.\nObtain a sample from a Kar'Zok 0/1 Kor-Sha Laboratory\nIn Kor-Sha Laboratory, attack one of the Kar'Zok Sarnaks (green), they will banish you to Gates of Kor-Sha.\nDeliver 1 Tuned Elimination Device to Ingistorma Varro 0/1 Frontier Mountains\nIn Frontier Mountains, turn in the Tuned Elimination Device to Ingistorma Varro.\nTell Ingistorma Varry you were [banished] 0/1 Frontier Mountains\nHail him and say banished.\nReward(s):\n319pp\nExperience\n**Submitted by:** Gidono\n- 319pp, Experience",
    },
    {
      id = "8453",
      title = "Pentalateral Negotiations",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Envoy Kresh`va",
      loc = nil,
      triggers = {
        "EoK",
        "_Quests_",
        "_Exodus Sentinel_",
        "_Rathe Heretic_",
        "_Flastpost Head_",
        "_Farpost Head_",
        "_The Coppicer_",
        "_Talk Talker_",
      },
      items_required = {
      },
      rewards = {
        { id = 127543, name = "Enchanted Syldon Bark", type = "item" },
        { id = 127546, name = "Glowing Frontier Gem", type = "item" },
        { id = 127608, name = "Sticky Drogan Net", type = "item" },
        { id = 127544, name = "Syldon Cautery", type = "item" },
      },
      factions = {
        { name = "Guardians of Konikor", change = 1 },
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Envoy Kresh`va [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Factions Raised:**\n- Guardians of Konikor +1\n**Factions Lowered:**\n**Quest Items:**\n- Enchanted Syldon Bark [item=127543]\n- Glowing Frontier Gem [item=127546]\n- Sticky Drogan Net [item=127608]\n- Syldon Cautery [item=127544]\n**Related Creatures:**\n- Asza Do`Saraken [ _Exodus Sentinel_]\n- Earthcaller Quill [ _Rathe Heretic_]\n- Ottar [ _Flastpost Head_]\n- Roald [ _Farpost Head_]\n- Tenlu Coi [ _The Coppicer_]\n- Venomrider Di`aak [ _Talk Talker_]\n- a Drogan eradicator [npc=51278]\n- a Lake of Ill Omen refugee [npc=51301]\n- a Syldon ambusher [npc=52843]\n- a Syldon flamewarden [npc=51258]\n- a Syldon slaver [npc=51274]\n- a Syldon tracker [npc=52842]\n- a possessed gemsniffer [npc=53857]\n- an enchanted grove guardian [npc=51698]\n**Related Quests:**\n- Partisan of Frontier Mountains [quest=8350]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Feb 6 22:36:19 2017\nModified: Mon Nov 11 08:24:32 2024 | | Pre Req: The following tasks must be completed before requesting this task.\nConcerned Citizens, Contacting the Leadership, Disappearing Dragons, Sneaky Sarnak.\nFind Envoy Kresh`va [npc=51221] in Frontier Mountains located in the ???.\nRequest Phrase: help\nThis task does not lock at any point.\n\n---\n\n03. Speak with Tenlu Coi at the druid ring 0/1 (Frontier Mountains)\n\n\n\nHead over to and Hail Tenlu Coi.\n\n04. Collect Enchanted Syldon Bark from Syldon Grove Guardians 0/4 (Frontier Mountains)\n\n\n\nIn the same area are grove guardians, kill them and loot Enchanted Syldon Bark.\n\n05. Use Enchanted Syldon Bark to ward 4 Drogan Eradicators 0/1 (Frontier Mountains)\n\n\n\nRight Click the Enchanted Bark on Drogan Eradicators.\n\n06. Return to Tenlu Coi at the druid ring 0/1 (Frontier Mountains)\n\n\n\nReturn to and Hail Tenlu Coi.\n\n07. Speak with Ottar at the Flatpost giant tower to the Southeast 0/1 (Frontier Mountains)\n\n\n\nHead over to and Hail Ottar.\n\n08. Travel to the Farpost giant tower to the Southwest 0/1 (Frontier Mountains)\n\n\n\nThis will auto update at the spot.\n\n09. Kill Syldon Flamewardens assaulting Farpost 0/6 (Frontier Mountains)\n\n\n\nIn the same area are Syldon Flamewardens, kill them.\n\n10. Heal Injured Farpost Guards 0/1 (Frontier Mountains)\n\n\n\nThe Flamewardens can drop Syldon Cautery, you can Right Click these on the giants to update this.\n\n\n\n\nYour faction standing with Guardians of Konikor has been adjusted by 1.\n\n11. Speak with Roald outside Farpost 0/1 (Frontier Mountains)\n\n\n\nHead over to and Hail Roald.\n\n12. Speak with Earthcaller Quill to the South 0/1 (Frontier Mountains)\n\n\n\nHead over to and Hail Earthcaller Quill.\n\n13. Collect Glowing Frontier Gems 0/6 (Frontier Mountains)\n\n\n\nIn Frontier Mountains, deliver all of these Mysterious Research Powders to Ingistorma Varro.\n\n14. Click on Gems in the area, these will spawn mobs, kill them and Loot the gems\n\n\n\nGive Glowing Frontier Gems to Earthcaller Quill 0/6 (Frontier Mountains).\n\n15. Speak with Venomrider Di'aak to the East 0/1 (Frontier Mountains)\n\n\n\nHead over to and Hail Venomrider Di'aak.\n\n16. Use Sticky Drogan Net to capture Highweb Spitters 0/6 (Frontier Mountains)\n\n\n\nAround the mountain area of Venomrider and to the North are highweb spitters, DPS them to 50% and then Right Click the Net you were given on them\n\n17. Return to Venomrider Di'aak 0/1 (Frontier Mountains)\n\n\n\nReturn to and Hail Venomrider Di'aak\n\n18. Speak with Asza Do'Saraken to the Northeast 0/1 (Frontier Mountains)\n\n\n\nHead over to and Hail Asza Do'Saraken.\n\n19. Tell Asza Do'Saraken you're ready to escort a refugee 0/1 (Frontier Mountains)\n\n\n\nHail Asza Do'Saraken again when ready\n\n20. Escort your Lake of Ill Omen refugee to the Northern Combine Camp 0/1 (Frontier Mountains)\n\n\n\nThis stage involves escorting a Lake of Ill Omen refugee [npc=51301] to the NE corner of the zone at the Combine encampment where you will find , [npc=51221] a Lake of Ill Omen refugee (Wwein) [npc=51301] spawns. It is tethered to the hailer and will not wander off, though has pathing difficulties. At various stages of the hike a number of mobs will spawn and immediately attack the refugee. She will kneel down and stay put during the fights. All mobs that spawn will stay attacking the refugee unless pulled or taunted away - this includes proximity social agro such as heals. The refugee has a lot of hit points and does not need a great deal of guarding until the final fight:\n\n\n\n\n**-356 -4833 36:** 1x a Syldon tracker spawns nearby\n\n\n**A Lake of Ill Omen refugee freezes in fear and shouts, 'I knew they'd find us! This is the first of many.'**\n\n\n\n**-384, -4190, 62:** 1x a Syldon slaver [npc=51274] spawns nearby\n\n\n**A Lake of Ill Omen refugee freezes in fear and shouts, 'Slaver! Don't let him take me!'**\n\n\n\n**823, -3347, 37:** 1x a Syldon tracker and 3x a Syldon ambusher [npc=52843] spawns nearby\n\n\n**A Lake of Ill Omen refugee freezes in fear and shouts, 'Syldon sends reinforcements against us now. We're doomed!'**\n\n\n\n**1728, -3477, -23:** 1x a Syldon slaver [npc=51274] and 3x a Syldon ambusher [npc=52843] spawns nearby\n\n\n**A Lake of Ill Omen refugee freezes in fear and shouts, 'What did we do to deserve this?'**\n\n\n\n**2716, -3686, 133:** 1x a Syldon tracker, 1x a Syldon slaver [npc=51274], and 3x a Syldon ambusher [npc=52843] spawns nearby\n\n\n**A Lake of Ill Omen refugee freezes in fear and shouts, 'An entire army approaches! What have I done that makes them care so much about me?'**\n\n\n\nFinally, deliver the refugee to **3578, -3304, 199**\n\n**A Lake of Ill Omen refugee says, 'Glory to Wwein and the Combine! I live for their bravery!'**\n\n21. Report your mission findings to Envoy Kresh'va 0/1 (Frontier Mountains)\n\n\n\nHail Envoy Kresh`va.\n\n\n---\n\nReward(s):\n319pp\nExperience\n- 683 pp, Experience",
    },
    {
      id = "8498",
      title = "Preparations for Forward Action I",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Praetor Elsivine",
      loc = nil,
      triggers = {
        "EoK",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Praetor Elsivine [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Time:** | Unlimited\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Loot\n- Money\n**Success Lockout Timer**: 00:01:00\n**Related Zones:**\n- Gates of Kor-Sha [zone=1091]\n**Related Quests:**\n- Mercenary of Gates of Kor-Sha [quest=8355]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sun Apr 23 04:57:23 2017\nModified: Mon Dec 2 01:41:05 2024 | | The following tasks must be completed before you can request this task.\nConcerned Citizens, [quest=8272] Contacting the Leadership [quest=8385], Corrupt Before the Fall, Corrupting the Corrupt, Destabilizing Chardok [quest=8457], Digging Yourself Deeper [quest=8395], Disappearing Dragons [quest=8262], Informal Diplomacy [quest=8382], On Nobody's Side [quest=8381], Pentalateral Negotiations [quest=8453], Probing the Fortress [quest=8389], Pure Success, Rebellion of the Pure, Purifying the Purifier, Rocks Boom for Twigslam [quest=8410], Sarnak Among Us [quest=8409], Sneaky Sarnak [quest=8392], The Last Grove [quest=8363], Their Own Medicine [quest=8455] and Where is Burning Woods? [quest=8403]\nThis task comes from Praetor Elsivine [npc=51222] in Frontier Mountains. Say do it to get the task.\n\n---\n\nClear out some of the guardians at the entrance to the Laboratory of Kor-Sha 0/8 Gates of Kor-Sha\nKill 8 Sarnak's near the entrance of Kor-Sha Laboratory zone in in the northwest part of the zone.\nSpeak with Praetor Elsivine about your success 0/1 Frontier Mountains\nHail Preator Elsivine\nReward(s):\n212pp, 5g\nExperience\n**Submitted by:** Gidono\n- 212pp, 5g & Experience",
    },
    {
      id = "8723",
      title = "Purifying the Purifier",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Vasyryx Teken`tlar",
      loc = nil,
      triggers = {
        "EoK",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
        { id = 127600, name = "Drogan Medicinal Herb Bundle", type = "item" },
        { id = 127776, name = "Drogan Ore", type = "item" },
        { id = 127622, name = "Glowing Goblin Blood Sample", type = "item" },
        { id = 127809, name = "Goblin Mushroom Loaf", type = "item" },
        { id = 127798, name = "Goblin Priest Blood Sample", type = "item" },
        { id = 127799, name = "Goblin Rogue Blood Sample", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Status: Incomplete**\n\nQuest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Vasyryx Teken`tlar [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 95\n**Maximum Level:** | 130\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 01:00:00\n**Quest Items:**\n- Drogan Medicinal Herb Bundle [item=127600]\n- Drogan Ore [item=127776]\n- Glowing Goblin Blood Sample [item=127622]\n- Goblin Mushroom Loaf [item=127809]\n- Goblin Priest Blood Sample [item=127798]\n- Goblin Rogue Blood Sample [item=127799]\n- Goblin Spell Caster Blood Sample [item=127804]\n- Goblin Warrior Blood Sample [item=127797]\n- Substance Delivery Device [item=127621]\n**Related Zones:**\n- Frontier Mountains [EoK]\n- Temple of Droga [EoK]\n**Related Creatures:**\n- a goblin adept mystic [npc=51371]\n- a goblin mystic - Temple of Droga - EoK - 1 [npc=51379]\n- a goblin slave - Temple of Droga - EoK [npc=51381]\n- a stalwart goblin mystic [npc=51378]\n- a stalwart stone mystic [npc=51386]\n- a stone mystic [npc=51385]\n**Related Quests:**\n- Partisan of The Temple of Droga [quest=8352]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Jul 4 19:28:36 2017\nModified: Tue Aug 11 05:14:02 2026 | | **Prerequisites: Achievement: Partisan of Lceanium [quest=8274], Achievement: Partisan of Frontier Mountains [quest=8350] and the task Corrupt Before the Fall from the same NPC.**\n\n---\n\n_**Vasyryx Teken`tlar is located in the Frontier Mountains (EoK).**_\n_**/waypoint -3399, -881, -303**_\n_**/Say interested to her to trigger the task. All requested items can be pre-looted.**_\n**Missing dialogue**\n_**You receive Substance Delivery Device [item=127621].**_\n\n---\n\n**Gather and deliver 3 samples of the ores these goblins mine to Vasyryx - 0/3 - Frontier Mountains**\n_**Head into the Temple of Droga (EoK). The Drogan Ore drops from goblin slaves.**_\n_**You receive Drogan Ore [item=127776].**_\n_**You receive Drogan Ore [item=127776].**_\n_**You receive Drogan Ore [item=127776].**_\n\n---\n\n**Gather and deliver 3 samples of the food these goblins eat to Vasyryx - 0/3 - Frontier Mountains**\n_**Goblin Mushroom Loaf is found in barrels in the kitchen. Attack them and right click the corpse to loot the loaves. If they have trash in them, kill them, they will respawn again.**_\n_**You receive Goblin Mushroom Loaf [item=127809].**_\n_**You receive Goblin Mushroom Loaf [item=127809].**_\n_**You receive Goblin Mushroom Loaf [item=127809].**_\n\n---\n\n**Gather and deliver 3 samples of the medicinal herbs these goblins use to Vasyryx - 0/3 - Frontier Mountains**\n_**Drogan Medicinal Herb Bundle drops from shaman goblins that have mystic in their name.**_\n_**You receive Drogan Medicinal Herb Bundle [item=127600].**_\n_**You receive Drogan Medicinal Herb Bundle [item=127600].**_\n_**You receive Drogan Medicinal Herb Bundle [item=127600].**_\n\n---\n\n**Gather and deliver 3 samples of goblin blood using the new mist in the Delivery Device and deliver them to Vasyryx - 0/3 - Frontier Mountains**\n_**You can get Glowing Goblin Blood ~~, Goblin Priest Blood Sample, Goblin Rogue Blood Sample, Goblin Spell Caster Blood Sample and Goblin Warrior Blood Sample~~ from using the Substance Delivery Device Vasyryx gave you. ~~Any three of them will work.~~**_\n_**Use the device on any goblins while they are above 90%. It will say something like \"glowing with infused magic\" under mob name. Better pick easier blue con goblins for this because once infused, they gain a nasty AoE.**_\n_**You receive Glowing Goblin Blood Sample [item=127622].**_\n_**You receive Glowing Goblin Blood Sample [item=127622].**_\n_**You receive Glowing Goblin Blood Sample [item=127622].**_\n\n---\n\n**Return the Delivery Device to Vasyryx Teken'tlar - 0/1 - Frontier Mountains**\n_**Hand the Substance Delivery Device to Vasyryx Teken'tlar.**_\n**Missing dialogue**\n**Submitted by:** Revamped by iventheassassin\n- Experience, Platinum coins",
    },
    {
      id = "8724",
      title = "Corrupt Before the Fall",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Vasyryx Teken`tlar",
      loc = nil,
      triggers = {
        "EoK",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
        { id = 127798, name = "Goblin Priest Blood Sample", type = "item" },
        { id = 127799, name = "Goblin Rogue Blood Sample", type = "item" },
        { id = 127805, name = "Goblin Shadowknight Blood Sample", type = "item" },
        { id = 127804, name = "Goblin Spell Caster Blood Sample", type = "item" },
        { id = 127797, name = "Goblin Warrior Blood Sample", type = "item" },
        { id = 127808, name = "Infused Goblin Priest Blood Sample", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Vasyryx Teken`tlar [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 01:00:00\n**Quest Items:**\n- Goblin Priest Blood Sample [item=127798]\n- Goblin Rogue Blood Sample [item=127799]\n- Goblin Shadowknight Blood Sample [item=127805]\n- Goblin Spell Caster Blood Sample [item=127804]\n- Goblin Warrior Blood Sample [item=127797]\n- Infused Goblin Priest Blood Sample [item=127808]\n- Infused Goblin Rogue Blood Sample [item=127806]\n- Infused Goblin Shadowknight Blood Sample [item=127800]\n- Infused Goblin Spell Caster Blood Sample [item=127807]\n- Infused Goblin Warrior Blood Sample [item=127802]\n- Substance Delivery Device [item=127621]\n**Related Zones:**\n- Temple of Droga [EoK]\n**Related Quests:**\n- Partisan of The Temple of Droga [quest=8352]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Jul 5 18:18:25 2017\nModified: Sat Nov 16 23:31:57 2024 | | Prerequisites : Achievement: Partisan of Lceanium [quest=8274], Achievement: Partisan of Frontier Mountains [quest=8350].\nSay **interested** to Vasyryx Teken`tlar in Frontier Mountains to trigger the task.\n\n---\n\n1\\. Deliver a blood sample from a goblin spell caster in Droga to Vasyryx 0/1 (Frontier Mountains)\n2\\. Deliver a blood sample from a goblin priest in Droga to Vasyryx 0/1 (Frontier Mountains)\n3\\. Deliver a blood sample from a goblin warrior in Droga to Vasyryx 0/1 (Frontier Mountains)\n4\\. Deliver a blood sample from a goblin shadowknight in Droga to Vasyryx 0/1 (Frontier Mountains)\n5\\. Deliver a blood sample from a goblin rogue in Droga to Vasyryx 0/1 (Frontier Mountains)\n6\\. Inject a goblin spell caster in Droga, then gather a sample from it and deliver it to Vasyryx 0/1 (Frontier Mountains)\nYou can inject all the mobs without doing any damage to them.\n7\\. Inject a goblin priest in Droga, then gather a sample from it and deliver it to Vasyryx 0/1 (Frontier Mountains)\n8\\. Inject a goblin warrior in Droga, then gather a sample from it and deliver it to Vasyryx 0/1 (Frontier Mountains)\n9\\. Inject a goblin shadowknight in Droga, then gather a sample from it and deliver it to Vasyryx 0/1 (Frontier Mountains)\n10\\. Inject a goblin rogue in Droga, then gather a sample from it and deliver it to Vasyryx 0/1 (Frontier Mountains)\n11\\. Return the Delivery Device to Vasyryx Teken'tlar 0/1 (Frontier Mountains)\n\n---\n\nReward(s) :\nExperience, Platinum",
    },
    {
      id = "8725",
      title = "Corrupting the Corrupt",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Vasyryx Teken`tlar",
      loc = nil,
      triggers = {
        "EoK",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
        { id = 127621, name = "Substance Delivery Device", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Vasyryx Teken`tlar [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 01:00:00\n**Quest Items:**\n- Substance Delivery Device [item=127621]\n**Related Zones:**\n- Temple of Droga [EoK]\n**Related Quests:**\n- Partisan of The Temple of Droga [quest=8352]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Jul 5 18:51:23 2017\nModified: Tue Dec 5 05:21:04 2023 | | Prerequisites : Achievement: Partisan of Lceanium [quest=8274], Achievement: Partisan of Frontier Mountains [quest=8350] as well as the tasks Corrupt Before the Fall and Purifying the Purifier from the same NPC.\nSay **interested** to Vasyryx Teken`tlar in Frontier Mountains to trigger the task.\n\n---\n\n1\\. Inject at least 5 goblins with the Corrupting Mist that Vasyryx loaded into the delivery device 0/5 (The Temple of Droga)\n2\\. Kill any goblins that are affected by the mist to ensure they do not return to the general population 0/1 (The Temple of Droga)\nOne of the corrupted/infected goblins will turn into a corrupted orc. Kill it and proceed\n3\\. Return the Delivery Device to Vasyryx Teken'tlar 0/1 (Frontier Mountains)\n\n---\n\nReward(s) :\nExperience, Platinum",
    },
    {
      id = "8726",
      title = "Pure Success",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Vasyryx Teken`tlar",
      loc = { y = -1217.0, x = -880.0, z = -170.0 },
      triggers = {
        "EoK",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
        { id = 127621, name = "Substance Delivery Device", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Vasyryx Teken`tlar [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 01:00:00\n**Quest Items:**\n- Substance Delivery Device [item=127621]\n**Related Zones:**\n- Temple of Droga [EoK]\n**Related Creatures:**\n- Cave Overlord Snally [npc=51415]\n- Depredator Overlord Boilwart [npc=51406]\n- Legate Overlord Werlgra [npc=51422]\n- Whip Overlord Gentza [npc=51408]\n**Related Quests:**\n- Partisan of The Temple of Droga [quest=8352]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Jul 5 18:59:23 2017\nModified: Mon Nov 18 05:13:05 2024 | | Prerequisites : Achievement: Partisan of Lceanium [quest=8274], Achievement: Partisan of Frontier Mountains [quest=8350] as well as the tasks Corrupt Before the Fall [quest=8724], Purifying the Purifier [quest=8723] and Corrupting the Corrupt [quest=8725] from the same NPC.\nSay **interested** to Vasyryx Teken`tlar in Frontier Mountains to trigger the task.\n1\\. Speak with the goblin overlord Snally of Droga about the Combine 0/1 (The Temple of Droga)\nCave Overlord Snally [npc=51415] is located at -1217, -880, -170. Say combine to get this update.\n2\\. Speak with the goblin overlord Gentza of Droga about the Combine 0/1 (The Temple of Droga)\nWhip Overlord Gentza [npc=51408] is located at -488, -618, -170. Say combine to get this update.\n3\\. Speak with the goblin overlord Boilwart of Droga about the Combine 0/1 (The Temple of Droga)\nDepredator Overlord Boilwart [npc=51406] is located at -455, +55, -170. Say combine to get this update.\n4\\. Speak with the goblin overlord Werlgra of Droga about the Combine 0/1 (The Temple of Droga)\nLegate Overlord Werlgra [npc=51422] is located at +418, -203, -137. Say combine to get this update.\n5\\. Defeat the overly aggressive overlord 0/1 (The Temple of Droga)\n6\\. Return the Delivery Device to Vasyryx Teken'tlar 0/1 (Frontier Mountains)\nReward(s) :\nExperience, Platinum",
    },
    {
      id = "8727",
      title = "Rebellion of the Pure",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Vasyryx Teken`tlar",
      loc = nil,
      triggers = {
        "leadership",
        "Snally",
        "Dronan",
        "stronger",
        "me",
        "EoK",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
        { id = 127621, name = "Substance Delivery Device", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Vasyryx Teken`tlar [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 01:00:00\n**Quest Items:**\n- Substance Delivery Device [item=127621]\n**Related Zones:**\n- Temple of Droga [EoK]\n**Related Creatures:**\n- Cave Overlord Snally [npc=51415]\n- Depredator Overlord Boilwart [npc=51406]\n- Legate Overlord Werlgra [npc=51422]\n- Whip Overlord Gentza [npc=51408]\n- a goblin bruiser [npc=51752]\n**Related Quests:**\n- Corrupt Before the Fall [quest=8724]\n- Corrupting the Corrupt [quest=8725]\n- Partisan of Frontier Mountains [quest=8350]\n- Partisan of Lceanium [quest=8274]\n- Partisan of The Temple of Droga [quest=8352]\n- Pure Success [quest=8726]\n- Purifying the Purifier [quest=8723]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Jul 5 19:05:18 2017\nModified: Mon Nov 18 08:00:48 2024 | | Prerequisites : Achievement: Partisan of Lceanium [quest=8274], Achievement: Partisan of Frontier Mountains [quest=8350] as well as the tasks Corrupt Before the Fall, Purifying the Purifier, Corrupting the Corrupt and Pure Success from the same NPC.\nSay **interested** to Vasyryx Teken`tlar in Frontier Mountains to trigger the task.\n\n---\n\n1\\. Speak with the goblin overlord Snally of Droga about leadership 0/1 (The Temple of Droga)\nYou say, 'leadership'\nCave Overlord Snally says, 'Why, you ask? Leadership hard. You too stupid to do it. Leave that to [Snally].'\nYou say, 'Snally'\nCave Overlord Snally says, 'Snally not stupid, Snally say YOU stupid! Snally not try to be leader of clan. That stupid!'\nSay _control_ to Cave Overlord Snally.\n2\\. Speak with the goblin overlord Gentza of Droga about leadership 0/1 (The Temple of Droga)\nYou say, 'leadership'\nWhip Overlord Gentza says, 'You want to be leader now? No? Then why you asking about it? It is simple. Dragons control sarnak. Sarnak control everything else. And [Dronan] controls Droga.'\nYou say, 'Dronan'\nWhip Overlord Gentza says, 'He rules here. Unless that changes, you shouldn't talk about anyone else ruling the clan.'\nSay _dronan_ to Whip Overlord Gentza.\n3\\. Speak with the goblin overlord Boilwart of Droga about leadership 0/1 (The Temple of Droga)\nYou say, 'leadership'\nDepredator Overlord Boilwart says, 'Little goblin, you not need to understand being in charge. You need know how to do what you told. Let smarter, [stronger] goblin do leading.'\nYou say, 'stronger'\nDepredator Overlord Boilwart says, 'Of course me stronger, and smarter, than any chief. But me smart enough to not try to be chief unless priests want me to. Now go away.'\nSay _stronger_ to Depredator Overlord Boilwart.\n4\\. Speak with the goblin overlord Werlgra of Droga about leadership 0/1 (The Temple of Droga)\nYou say, 'leadership'\nLegate Overlord Werlgra says, 'That is a complicated subject for a minion like you. You should just put your head down and work. Let [me] worry about leading the clan.'\n\n---\n\nAt this point, say _me_ to whichever Overlord is the last one you talk to. This will spawn 3 trash mobs that attack.\nYou say, 'me'\nLegate Overlord Werlgra says, 'Ha! Even if I want take leadership, I will never talk to you about it.'\n\n---\n\n5\\. Don't let the bruisers beat you up 0/3 (The Temple of Droga)\nKill them.\n6\\. Return the Delivery Device to Vasyryx Teken'tlar 0/1 (Frontier Mountains)\n\n---\n\nReward(s) :\nExperience, Platinum",
    },
    {
      id = "8773",
      title = "Preparations for Forward Action II",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Praetor Elsivine",
      loc = nil,
      triggers = {
        "EoK",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Praetor Elsivine [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Success Lockout Timer**: 00:01:00\n**Related Quests:**\n- Concerned Citizens [quest=8272]\n- Contacting the Leadership [quest=8385]\n- Corrupt Before the Fall [quest=8724]\n- Corrupting the Corrupt [quest=8725]\n- Destabilizing Chardok [quest=8457]\n- Digging Yourself Deeper [quest=8395]\n- Disappearing Dragons [quest=8262]\n- Informal Diplomacy [quest=8382]\n- On Nobody's Side [quest=8381]\n- Pentalateral Negotiations [quest=8453]\n- Probing the Fortress [quest=8389]\n- Pure Success [quest=8726]\n- Purifying the Purifier [quest=8723]\n- Rebellion of the Pure [quest=8727]\n- Rocks Boom for Twigslam [quest=8410]\n- Sarnak Among Us [quest=8409]\n- Sneaky Sarnak [quest=8392]\n- The Last Grove [quest=8363]\n- Their Own Medicine [quest=8455]\n- Where is Burning Woods? [quest=8403]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Jul 31 21:37:25 2017\nModified: Mon Dec 2 01:41:08 2024 | | The following quests must be done in order to request this.\nConcerned Citizens, Contacting the Leadership, Corrupt Before the Fall, Corrupting the Corrupt, Destabilizing Chardok, Digging Yourself Deeper, Disappearing Dragons, Informal Diplomacy, On Nobody's Side, Pentalateral Negotiations, Probing the Fortress, Pure Success, Purifying the Purifier, Rebellion of the Pure, Rocks Boom for Twigslam, Sarnak Among Us, Sneaky Sarnak, Their Own Medicine, The Last Grove, Where is Burning Woods?\nFind Praetor Elsivine in Frontier Mountains in the far northeast corner of the zone.\nSay **do it** to get the task.\n\n---\n\nVersion #1\n2. Get rid of some of the aggressive bugs in the valley. 0/7 Gates of Kor-Sha\nKill 7 bugs in Gates of Kor-sha.\n6. Speak with Praetor Elsivine about your success 0/1 Frontier Mountains\nHail Praetor Elsivine in Frontier Mountains.\n\n---\n\nVersion #2\n2. Get rid of some of the aggressive bugs in the valley. 0/12 Gates of Kor-Sha\nKill 12 bugs in Gates of Kor-sha.\n6. Speak with Praetor Elsivine about your success 0/1 Frontier Mountains\nHail Praetor Elsivine in Frontier Mountains.\n\n---\n\nReward(s):\n212pp, 5 gold\nExperience\n**Submitted by:** Gidono\n- 212pp, 5 gold. Experience.",
    },
    {
      id = "8774",
      title = "Preparations for Forward Action III",
      exp = "23",
      exp_name = "Empires of Kunark",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Praetor Elsivine",
      loc = nil,
      triggers = {
        "EoK",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Frontier Mountains [EoK]\n**Who:**\n- Praetor Elsivine [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Time:** | Unlimited\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Related Quests:**\n- Concerned Citizens [quest=8272]\n- Contacting the Leadership [quest=8385]\n- Corrupt Before the Fall [quest=8724]\n- Corrupting the Corrupt [quest=8725]\n- Destabilizing Chardok [quest=8457]\n- Digging Yourself Deeper [quest=8395]\n- Disappearing Dragons [quest=8262]\n- Informal Diplomacy [quest=8382]\n- On Nobody's Side [quest=8381]\n- Pentalateral Negotiations [quest=8453]\n- Probing the Fortress [quest=8389]\n- Pure Success [quest=8726]\n- Purifying the Purifier [quest=8723]\n- Rebellion of the Pure [quest=8727]\n- Rocks Boom for Twigslam [quest=8410]\n- Sarnak Among Us [quest=8409]\n- Sneaky Sarnak [quest=8392]\n- The Last Grove [quest=8363]\n- Their Own Medicine [quest=8455]\n- Where is Burning Woods? [quest=8403]\n**Era:** | !Empires of Kunark\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Jul 31 22:05:44 2017\nModified: Mon Dec 2 01:41:12 2024 | | This task requires you to complete the following tasks first before being able to request this task.\nConcerned Citizens, Contacting the Leadership, Corrupt Before the Fall, Corrupting the Corrupt, Destabilizing Chardok, Digging Yourself Deeper, Disappearing Dragons, Informal Diplomacy, On Nobody's Side, Pentalateral Negotiations, Probing the Fortress, Pure Success, Purifying the Purifier, Rebellion of the Pure, Rocks Boom for Twigslam, Sarnak Among Us, Sneaky Sarnak, Their Own Medicine, The Last Grove and Where is Burning Woods?\nFind Praetor Elsivine in the far north east corner of the zone.\nSay **do it** to get the task.\n\n---\n\n2. Wipe out potentially dangerous wild chokidai 0/10 Gates of Kor-Sha\nKill 10 chokidai. The named Chokidai Wardog doesn't count towards this step.\n6. Speak with Praetor Elsivine about your success 0/1 Frontier Mountains\nHail Praetor Elsivine.\nReward(s):\n212pp, 5 gold\nExperience\n**Submitted by:** Gidono\n- 212pp, 5 gold. Experience.",
    },
  },
}
