-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for The Great Divide (greatdivide)
-- Total Quests: 8
-- ============================================================================

return {
  zone = "greatdivide",
  zone_name = "The Great Divide",
  quests = {
    {
      id = "9743",
      title = "Lake-Effect Snow Devils",
      exp = "26",
      exp_name = "Torment of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Brollo Aleslay",
      loc = { y = -3211.0, x = 1890.0, z = -146.0 },
      triggers = {
        "Hail, Brollo Aleslay",
        "hills",
        "monsters",
        "We were talking about...",
        "Of course I",
        "What hunt?",
        "whit",
        "**dervishes**",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Status: Incomplete**\n\nQuest Started By: | Description:\n**Where:**\n- The Great Divide [ToV]\n**Who:**\n- Brollo Aleslay [ _Quest_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 130\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n**Related Creatures:**\n- a frigid cadaver [npc=55103]\n- a restless tizmak [npc=55347]\n- a windchill sprite [npc=55114]\n**Related Quests:**\n- Mercenary of The Great Divide (10 Points) [quest=9799]\n**Era:** | !Torment of Velious\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Oct 24 23:41:32 2019\nModified: Sun Jan 18 06:55:32 2026 | | **Torment of Velious Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nThis solo task can be obtained from Brollo Aleslay [npc=55122] at -3211, +1890, -146 in the southwestern side of the zone.\nYou say, 'Hail, Brollo Aleslay'\nBrollo Aleslay says, 'Ye daft? Whit brings ye intae these [hills]?'\nYou say, 'hills'\nBrollo Aleslay says, 'Aye, these hills, these huir uv a ones? Wa ur ye haur? Wa woods ye e'en come haur? Cannae ye see 'at aw forms ay [monsters] hae taken ower thes place? only a a bampot bodie woods e'en consider comin' haur. But since ye ur haur, ye micht an aw dae some guid haur.'\nYou say, 'monsters'\nBrollo Aleslay says, 'Aye! th' monsters! Dinnae tell me ye haven't run intae thaim! They're a' ower 'n' they're grawin by th' moment! Whitevur haes bin bothering a' o' Velious didn't hain this steid, that?s fur sure! Thare mair undead ice critters 'ere than ever afore 'n' ye don't see me complaining aboot that noo dae ye? Dae ye?! Da ye don't! even whin ah hae tae rammy mah ain kin. Ah beat mah cousin th' ither day wi' a rock fur he wis bitten by yin o' they creatures 'n' he turned intae yin, then ah beat him tae death wi' a shovel, bless his soul, 'n' then he git back up a' covered wi' that ice stuff 'n' then ah picked up a rock 'n' beat him! tis whit ah hud tae dae in order tae protect his fowk, brassic guy. Noo, whit wur we [talking] aboot? och aye! th' critters that need tae be murdurred! Ah hae a slew o' thaim that need tae be...slewed.'\nYou say, ' We were talking about...'\nBrollo Aleslay says, 'Right, aye ye blether tae muckle as it's 'n' we hae a dire situation at haun, if we don't cut doon thae critters sooner ower than efter we ur aff tae be in a heap o' trauchle come th' future. Ah hae a seicont cousin twa times lifted wha hud fought thae hings afore 'n' he said that if ye skelp thaim upside th' heid thay mak' a funny sound lik' BONK or something 'n' then thare wis a SQUISH bit that's beside th' point stoap asking aboot mah cousins! We hae bigger problems tae tak' care o'! A'm needin' ye tae focus at th' hing at haun. Sae 'ere in th' Great Divide, ye kin see that th' coldain hae bin pushed back intae th' caves, hiding fae ilka cratur that haes crawled up fae th' frost. Thay dae this in order tae survive fur if thay don't th' critters wull overwhelm thaim. Bit thay aren't tae bricht ye see, th' monsters wull juist swarm th' caves soon 'n' thay wull be deid anyways 'n' that?s nae whit a' body wants. Urr ye even [listening]?'\nYou say, ' Of course I'm listening, I'm just trying to understa...'\nBrollo Aleslay says, 'Good! yer listening. Sae, ah hae bin oot in thae wastes fur some time noo peepin' whit's gaun oan 'n' learned that thare ur some monsters that ur mair abundant than ithers 'n' they ur th' ones we wull need tae focus. Howfur is yer hunting skills? Likelie nae nearly as guid as mah sisters. She wance hunted 'n' trapped a ran clood. Ah didn't even think sic a thing cuid be maybee aye wi'oot usin` magic. 'n' sin ye brought it up a'm waantin' ye tae ken that usin` magic tae [hunt] is cheating. Ah don't care howfur kin books yer read in yer fancy schools bit that's aye cheating. That defeats th' purpose o' th' hunt itself. Yi''ll need tae git clatty, become yin wi' nature, breath in dirt 'n' cop th' win` atween yer toes! That's howfur ye hunt! nae wi' whispering some curses or drawing fancy stick figures in a rock. Sae if ye uise magic, na offense that's braw 'n' a' bit if ye care aboot mah opinion, whilk ye shuid, ye shuid ken that yer cheating 'n' that's wrong! whin ye pockle at hunting ye pockle at '\nYou say, ' What hunt?'\nBrollo Aleslay says, 'Aye, hunt. That's [whit] ye'r aff tae dae!'\nYou say, 'whit'\nBrollo Aleslay says, 'Gidonoroglets out a long, drawn out sigh and says in a slow, over-enunciated tone, 'Can you hunt [dervishes], [skeletons], or [wurms]?''\nYou say, ' **dervishes**'\nYou have been assigned the task 'Lake-Effect Snow Devils'.\n\n---\n\n_Not even the dervishes are safe from what is affecting the Great Divide. Clear them out._\nKill Windchill Sprites 0/9 (The Great Divide)\nSlay 9 a windchill sprite [npc=55114] (snow dervish model) for task update. These can be found in the NW portion of the zone and in the Coldain mines south of the giant fort but seem to share spawn points with the tizmak and cadavers.\nNOTE: January ( **year?**) patch messed up the kill mobs.\nA frigid cadaver. That's what is ph for the sprites now due to January patch changes might be a bug or not??\nYour task 'Lake-Effect Snow Devils' has been updated.\n_The wind seems calmer since you killed the dervishes._\n\n---\n\nReward(s):\n141 platinum 6 gold 6 silver 6 copper\n**Submitted by:** Gidono\n- 141 platinum 6 gold 6 silver 6 copper",
    },
    {
      id = "9741",
      title = "Give Us Your Tired",
      exp = "26",
      exp_name = "Torment of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Tobart Dirkins",
      loc = { y = -36.0, x = -83.0, z = -122.0 },
      triggers = {
        "Hail, Tobart Dirkins",
        "help",
        "scout",
        "**News**.",
        "_Quest_",
      },
      items_required = {
        { name = "Us Your Tired", count = 1 },
        { name = "Us Your Tired'", count = 1 },
        { name = "Us Your Tired' has been updated", count = 1 },
        { name = "Us Your Tired' has been updated", count = 1 },
        { name = "Us Your Tired' has been updated", count = 1 },
        { name = "Us Your Tired' has been updated", count = 1 },
      },
      rewards = {
        { id = 138528, name = "Tobart's Torch", type = "item" },
        { id = 138529, name = "Travit's Missive", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Status: Incomplete**\n\nQuest Started By: | Description:\n**Where:**\n- The Great Divide [ToV]\n**Who:**\n- Tobart Dirkins [ _Quest_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Money\n**Success Lockout Timer**: 00:30:00\n**Quest Items:**\n- Tobart's Torch [item=138528]\n- Travit's Missive [item=138529]\n**Related Creatures:**\n- Travit Conwil [npc=55139]\n**Related Quests:**\n- Partisan of The Great Divide (10 Points) [quest=9800]\n**Era:** | !Torment of Velious\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Oct 24 23:09:15 2019\nModified: Tue Dec 5 05:21:04 2023 | | **Torment of Velious Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\n**You can get this task from Tobart Dirkins in The Great Divide at -36, -83, -122 near where Thurgadin is supposed to be. Findable via CTRL+F**\nYou say, 'Hail, Tobart Dirkins'\nTobart Dirkins says, 'Go away! We have enough mouths to feed and trouble finding a new home and we don?t need you causing any trou...oh wait, you! I remember you! I have a task that needs doing and I could certainly use your [help] in getting it done.'\nYou say, 'help'\nTobart Dirkins says, 'Wonderful, we just barely escaped Thurgadin with our lives. Many of us are still trapped inside and it is unknown what has happened to them. The ones that made it out are here. There were a lot more survivors than what you see here, most of them left to find shelter on their own and we haven't heard a thing back from them. I assume they have all been killed by the undead roaming these lands. I'm here trying to organize what is left of us so we can survive, but it is looking grim for us unless we can get some help from the local giants. I sent a [scout] to the giant's fort to the south east but they have not returned, and we have need of someone to track them down.'\nYou say, 'scout'\nYou have been assigned the task 'Give Us Your Tired'.\nTobart Dirkins says, 'The scout was last seen heading south, I believe they wanted to check the guard towers first before heading to the giant's fort. You may want to start your search there.'\n\n---\n\n_Tobart is worried about the scout that was sent to the giant's fort to the southeast. He fears the worst and needs someone to look into what happened while he tends to the survivors. He can't fetch the scout and look after everyone's safety and he has asked you to look into it._\n_Tobart mentioned that the count may have gone south and went to the guard huts along the river._\n1\\. Find Travit 0/1 (The Great Divide)\nTravit Conwill is inside one of the small towers (east tower) just a few steps south of Tobart along the frozen river. Enter to tower for quest update.\nYour task, 'Give Us Your Tired' has been updated.\n2\\. Return to Tobart and explain to him what you found 0/1 (The Great Divide)\nYou say, 'Hail, Tobart Dirkins'\nYou have been given: Tobart's Torch\nYour task 'Give Us Your Tired' has been updated.\nTobart Dirkins says, 'That news is... rather unsettling. Well, we know that if he stays out there like that, he will only return as a bigger problem as one of those... things. Please take this and dispose of his body. In the meantime, I will write up a new missive for the giants.\nYou receive a Tobart's Torch [item=138528] on your cursor.\n3\\. Return to Travit's body with Tobart's Torch 0/1 (The Great Divide)\nUpon getting within close proximity to Travit, he will attack you.\nTravit jumps up and attacks you!\nTravit Conwil says, 'Leeeeave... meeeee... aloooooone...'\n4\\. Dispose of Travit's body using Tobart's Torch 0/1 (The Great Divide)\nEngage with Travit Conwill.\nTravit Conwil's corpse cries out, 'Forgive me... master...'\nTravit Conwil has been slain!\nYour task 'Give Us Your Tired' has been updated.\nYour task 'Give Us Your Tired' has been updated.\n5\\. Return the torch to Tobart 0/1 (The Great Divide)e\nHand the torch back to Tobart.\nYou have been given: Travit's Missive [item=138529] (appears on cursor)\nYour task 'Give Us Your Tired' has been updated.\nTorbart Dirkins says, 'Well, as if things couldn't get any worse for us here, now I have to put up guards to watch out for our own. Every one of us that falls will become consumed by the ice, and then become one of them. They no longer have any semblance of free will. They become animals, feral and inhumane. Hopefully the giants will be a bit more [ **welcoming**] than the rest of this wasteland.'\nYou say, **welcoming**.\nTobart Dirkins says, 'Well, I guess you won't be needing that torch anymore. Thank you for your help with Travit, adventurer. He will be missed. You seem more than capable of handling yourself. Should the giants be less than welcoming, handle them too. Please, protect us from these harsh elements.\n6\\. Deliver the missive to the giants 0/1 (The Great Divide)e\nHand the _Travit's Missive_ over to Bekerak Coldbones.\nYour task, 'Give us Your Tired' has been updated.\nBekerak Coldbones says, 'This is unfortunate, tiny one. My people are starving and have nothing more to give. As you can see, the undead have also taken over the Great Divide. From what I understand, we aren't the only ones in this place and have been sundered by the ice. Not only have my people been affected, but so have the tizmak and the Coldain. The Coldain from Thurgadin have come to a place that is just as plagued as the place that they hail from. If we have any change in our situation, we will be able to welcome them, as we need allies in these dark times. However, until then, I have my own people to worry about and we cannot assist them. Please send my apologies.'\n7\\. Return to Tobart and let him know what Bekerak said 0/1 (The Great Divide)\nYou say, 'Hail, Tobart Dirkins'\nYour task 'Give Us Your Tired' has been updated.\nWhat happened to Travit was tragic, but it is a sullen reminder even the strongest needs to be careful in this cursed land.\nTobart Dirkins says, 'Please tell me that you have good [ **news**].'\nYou say, ' **News**.'\nTobart Dirkins says, 'This is... less than fortunate for our situation. Though we are hearty folks, I'm not sure how much longer we can hold out. Hopefully some bright tidings are in our future soon. I will try to send more people to find the cave the other survivors reconnoitered. If you have any booze, while it pains me to say, you may want to keep a distance from here. You will cause a scene with Horasug and everyone here is already on edge.\n\n---\n\nReward(s):\n106platinum 2 gold 5 silver\n**Submitted by:** Gidono",
    },
    {
      id = "9742",
      title = "Reliks of the Past",
      exp = "26",
      exp_name = "Torment of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Loremaster Dorinan",
      loc = nil,
      triggers = {
        "Hail, Loremaster Dorinan",
        "What kind of **matters** can I help with?",
        "**Relik**",
        "**Frozen**.",
        "Where is the giant",
        "_Quest_",
        "hail",
        "cleric",
      },
      items_required = {
        { name = "up hope on Relik", count = 1 },
      },
      rewards = {
        { id = 145983, name = "Frozen Bag of Food", type = "item" },
        { id = 138531, name = "Ornate Pickaxe", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Great Divide [ToV]\n**Who:**\n- Loremaster Dorinan [ _Quest_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 130\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Success Lockout Timer**: 00:12:00\n**Quest Items:**\n- Frozen Bag of Food [item=145983]\n- Ornate Pickaxe [item=138531]\n**Related Quests:**\n- Partisan of The Great Divide (10 Points) [quest=9800]\n**Era:** | !Torment of Velious\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Oct 24 23:28:40 2019\nModified: Sun Jan 18 06:19:18 2026 | | **Torment of Velious Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nThis shared task can be obtained from Loremaster Dorinan in The Great Divide at /way -3453, +1976, -120 which is in a cave on the southwest side of the zone.\nYou say, 'Hail, Loremaster Dorinan'\nLoremaster Dorinan says, 'Oh, Gidonorog! What a surprise! I haven't seen you since back when ye helped me with the mine in Thurgadin. As you can tell, things have gotten quit dire since the last time we crossed paths. The ice seems to have taken over all of the continent and has forced us to block the entrance to our home. We relocated to this cave, but my people are scattered across the great divide. I understand that the situation grows worse by the moment and the survivors to the north have made little headway in getting back into Thurgadin. There are other, more pressing [ **matters**] at hand.'\nYou say, ' What kind of **matters** can I help with?'\nLoremaster Dorinan says, 'Well we need to collect the rest of the coldain that are un accounted for. As I understand it, some are in the cave to the southeast are lost to us. However, there is one miner that we hear is still seen roaming the area, and that's [ **Relik**].'\nYou say, ' **Relik**'\nLoremaster Dorinan says, 'Yes, the gruff ol' miner used to help facilitate the coldain mines to the east. But with the ice creeping in and taking over everything it touches, the situation out there has gotten a wee bit too terrifying for many of us. Would you mind taking a moment out of your busy day to try and locate him for us? We are pretty worried that he hasn't checked recently, and some have started to whisper about his demise.'\nYou have been assigned the task 'Reliks of the Past'.\n\n---\n\n_Loremaster Dorian is worried that Relik hasn't checked in from the mines to the east. Search for clues to what may have happened to him and figure out where he could be._\n01. Bring whatever evidence you find near the Coldain ruins back to Loremaster. 0/1 (The Great Divide)\n\n\n\nHead to _/way -3420, -1880, -350 (about center-west of zone, under a tree)_ and loot Frozen Bag of Food [item=145983] (looks like a small bag).\n\n\n\n\nReturn to Dornian with the bag.\n05. Talk to Loremaster Dornian about the frozen food 0/1 (The Great Divide)\n\n\n\nHand the bag over to Dornian.\n\n\n\n\nLoremaster Dorinan says, 'This was his favorite meal, two apples, a container of fish, potatoes and leek soup, and a flagon of ale. It's [ **frozen**] which means it was out in the elements for quite some time.'\n\n\n\n\nYour task 'Reliks of the Past' has been updated.\n\n\n\n\nYou say, ' **Frozen**.'\n\n\n\n\nLoremaster Dorinan says, 'It... it appears that the soup was also 'infected' with the ice. Look! You can see the soup churning within the container. That is very strange. This doesn't help us get any closer to where Relik may be, but it does tell us where he isn't, which is at his normal spot that he eats his lunch. Perhaps we can check in with Hakon. He said they used to have lunch together. Maybe that can help narrow down where he went.'\n\n\n\n\nYour task 'Reliks of the Past' has been updated.\n09. Ask Hakon Brightsteel about Relik 0/1 (The Great Divide)\n\n\n\nYou say, Where is **Relik**?.'\n\n\n\n\nHakon Brightsteel straightens himself up before talking. It is apparent that he has been shaken up by the events that have happened. 'Oh, hello there, adventurer. I'm happy to hear that you will help in looking for our brethren, Relik. Him and I used to have lunch together over b the mines and...'\n\n\n\n\nBrimgald Brightsteel says, 'There you go again! Trying to get others to do what you should be doing but are too scared to do yourself! Why would you ask this stranger to look after your friend when you could have just asked any of us? What makes you think that this person is even willing to help you?'\n\n\n\n\nHakon Brightsteel says, 'Stop! We need to recoup what we have lost and we can't afford sending more of us out there to die. This adventurer looks strong enough to weather the storm out there and look into what is going on. This is a trivial matter for them so, please, let us just this one time reach out to the others to help us! I'm sorry, Laurana. As I was saying,' he regains his composure 'we used to meet up near the giant's [ **fort**]. Maybe one of them has seen Relik lately. I would suggest continuing your search with them.'\n\n\n\n\nYou say, 'Where is the giant's **fort**?\n\n\n\n\nHakon Brightsteel says, 'You will be able to find their fort to the northeast. Please be careful. There are a lot of those... things out there still and they are very dangerous.'\n\n\n\n\nYour task 'Reliks of the Past' has been updated.\n13. Ask the giants in the camp to the northeast if they have seen Relik 0/1 (The Great Divide)\n\n\n\nHead over to the giant fort on the east side of the zone and seek out Bekerak Coldbones in the southern most building.\n\n\n\n\nYou say, Have you seen Relik?'\n\n\n\n\nBekerak Coldbones says, 'Aye. I remember seeing those two off to the south. They never came into our territory and were always sure to clean up after themselves, which I found not only amusing but courteous. I have only seen one of them as of late. He was roaming around outside the Coldain mines near a campsite that was destroyed by the ice. That may be a good place to continue your search.'\n\n\n\n\nYour task 'Reliks of the Past' has been updated.\n17. Examine the camp to the south 0/1 (The Great Divide)\n\n\n\nHead over to the Southeast area of the zone to _/way -3300, -1600, -435_ It looks like a small abandoned camp with some broken building blocks and tattered rags. Click around on the blocks until you get an update. 2 _a familiar looking Coldain_ will spawn. Kill both coldain.\n\n\n\n\nA familiar looking Coldain's corpse cries 'I... want... to... be... hooooome.'\n\n\nYour task 'Reliks of the Past' has been updated.\n21. Recover the Ornate Pickaxe 0/1 (The Great Divide)\n\n\n\nAn Ornate Pickaxe [item=138531] will be placed in your inventory after slaying the coldains.\n25. Return the Pickaxe to Loremaster Dornian 0/1 (The Great Divide)\n\n\n\nUpon handing in the pickaxe to Dornian:\n\n\n\n\nLoremaster Dorinan: 'This... this was Relik's pick. You can see by the runes etched on it that it was his. This is not a good sign. If he no longer has his pick, then he no longer is... well, let us not dwell on that too much. Until we know for certain, we cannot give up hope on Relik. Thank you, Laurana. We will continue to keep an eye out for him and see what comes up. For now, take this as a token of our gratitude and please... stay safe out there.'\n\n\n\n\nYour 'Reliks of the Past' h as been updated.\nYou have an uneasy feeling that you won't know what happened to Relik until you find him. Until that day comes, you will have to keep on the lookout.\nYou receive 6 copper.\nYou receive 6 silver.\nYou receive 6 gold.\nYou receive 141 platinum.\n\n---\n\nReward(s):\n141 platinum 6 gold 6 silver 6 copper\n**Submitted by:** Gidono",
    },
    {
      id = "9744",
      title = "Just Play Dead",
      exp = "26",
      exp_name = "Torment of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Brollo Aleslay",
      loc = { y = -3211.0, x = 1890.0, z = -146.0 },
      triggers = {
        "Hail, Brollo Aleslay",
        "hills",
        "monsters",
        "We were talking about...",
        "Of course I",
        "What hunt?",
        "whit",
        "skeletons",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Great Divide [ToV]\n**Who:**\n- Brollo Aleslay [ _Quest_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n**Related Creatures:**\n- a frosttouched corpse [npc=55416]\n- a windchilled marrow [npc=55115]\n- a windtorn marrow [npc=55116]\n**Related Quests:**\n- Mercenary of The Great Divide (10 Points) [quest=9799]\n**Era:** | !Torment of Velious\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Fri Oct 25 00:04:25 2019\nModified: Tue Dec 5 05:21:04 2023 | | **Torment of Velious Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\n**This solo task can be obtained from Brollo Aleslay at -3211, +1890, -146 in the southwestern side of the zone.**\nYou say, 'Hail, Brollo Aleslay'\nBrollo Aleslay says, 'Ye daft? Whit brings ye intae these [hills]?'\nYou say, 'hills'\nBrollo Aleslay says, 'Aye, these hills, these huir uv a ones? Wa ur ye haur? Wa woods ye e'en come haur? Cannae ye see 'at aw forms ay [monsters] hae taken ower thes place? only a a bampot bodie woods e'en consider comin' haur. But since ye ur haur, ye micht an aw dae some guid haur.'\nYou say, 'monsters'\nBrollo Aleslay says, 'Aye! th' monsters! Dinnae tell me ye haven't run intae thaim! They're a' ower 'n' they're grawin by th' moment! Whitevur haes bin bothering a' o' Velious didn't hain this steid, that?s fur sure! Thare mair undead ice critters 'ere than ever afore 'n' ye don't see me complaining aboot that noo dae ye? Dae ye?! Da ye don't! even whin ah hae tae rammy mah ain kin. Ah beat mah cousin th' ither day wi' a rock fur he wis bitten by yin o' they creatures 'n' he turned intae yin, then ah beat him tae death wi' a shovel, bless his soul, 'n' then he git back up a' covered wi' that ice stuff 'n' then ah picked up a rock 'n' beat him! tis whit ah hud tae dae in order tae protect his fowk, brassic guy. Noo, whit wur we [talking] aboot? och aye! th' critters that need tae be murdurred! Ah hae a slew o' thaim that need tae be...slewed.'\nYou say, ' We were talking about...'\nBrollo Aleslay says, 'Right, aye ye blether tae muckle as it's 'n' we hae a dire situation at haun, if we don't cut doon thae critters sooner ower than efter we ur aff tae be in a heap o' trauchle come th' future. Ah hae a seicont cousin twa times lifted wha hud fought thae hings afore 'n' he said that if ye skelp thaim upside th' heid thay mak' a funny sound lik' BONK or something 'n' then thare wis a SQUISH bit that's beside th' point stoap asking aboot mah cousins! We hae bigger problems tae tak' care o'! A'm needin' ye tae focus at th' hing at haun. Sae 'ere in th' Great Divide, ye kin see that th' coldain hae bin pushed back intae th' caves, hiding fae ilka cratur that haes crawled up fae th' frost. Thay dae this in order tae survive fur if thay don't th' critters wull overwhelm thaim. Bit thay aren't tae bricht ye see, th' monsters wull juist swarm th' caves soon 'n' thay wull be deid anyways 'n' that?s nae whit a' body wants. Urr ye even [listening]?'\nYou say, ' Of course I'm listening, I'm just trying to understa...'\nBrollo Aleslay says, 'Good! yer listening. Sae, ah hae bin oot in thae wastes fur some time noo peepin' whit's gaun oan 'n' learned that thare ur some monsters that ur mair abundant than ithers 'n' they ur th' ones we wull need tae focus. Howfur is yer hunting skills? Likelie nae nearly as guid as mah sisters. She wance hunted 'n' trapped a ran clood. Ah didn't even think sic a thing cuid be maybee aye wi'oot usin` magic. 'n' sin ye brought it up a'm waantin' ye tae ken that usin` magic tae [hunt] is cheating. Ah don't care howfur kin books yer read in yer fancy schools bit that's aye cheating. That defeats th' purpose o' th' hunt itself. Yi''ll need tae git clatty, become yin wi' nature, breath in dirt 'n' cop th' win` atween yer toes! That's howfur ye hunt! nae wi' whispering some curses or drawing fancy stick figures in a rock. Sae if ye uise magic, na offense that's braw 'n' a' bit if ye care aboot mah opinion, whilk ye shuid, ye shuid ken that yer cheating 'n' that's wrong! whin ye pockle at hunting ye pockle at '\nYou say, ' What hunt?'\nBrollo Aleslay says, 'Aye, hunt. That's [whit] ye'r aff tae dae!'\nYou say, 'whit'\nBrollo Aleslay says, 'Gidonoroglets out a long, drawn out sigh and says in a slow, over-annunciated tone, 'Can you hunt [dervishes], [skeletons], or [wurms]?''\nYou say, 'skeletons'\nYou have been assigned the task 'Just Play Dead'.\n\n---\n\n_The skeletons in the Great Divide have threatened all of the life here, destroying camps and killing of creatures that called this palce home. They must be destroyed before they cause even more destruction. There is but one problem, understanding Brollo._\n1. Destroy Skeletons 0/7 (The Great Divide)\n\n\n\nSlay 7 skeleton model enemies throughout the zone, mostly concentrated in the north and eastern parts.\n\n\n\n\nYour task 'Just Play Dead' has been updated.\n\n_The hills here seem much quieter with fewer skeletons, but you can't help but feel that there will be more._\n\n---\n\nReward(s): 141 platinum, 6 gold, 6 silver, 6 copper.\n**Submitted by:** Gidono\n- Platinum",
    },
    {
      id = "9745",
      title = "Cool and Refreshing",
      exp = "26",
      exp_name = "Torment of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Brollo Aleslay",
      loc = { y = -3211.0, x = 1890.0, z = -146.0 },
      triggers = {
        "Hail, Brollo Aleslay",
        "hills",
        "monsters",
        "We were talking about...",
        "Of course I",
        "What hunt?",
        "whit",
        "wurms",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Great Divide [ToV]\n**Who:**\n- Brollo Aleslay [ _Quest_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n**Related Creatures:**\n- a restless shardwurm [npc=55417]\n- a restless wurm - The Great Divide - ToV [npc=55110]\n**Related Quests:**\n- Mercenary of The Great Divide (10 Points) [quest=9799]\n**Era:** | !Torment of Velious\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Fri Oct 25 00:08:02 2019\nModified: Tue Dec 5 05:21:04 2023 | | **Torment of Velious Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nThis solo task can be obtained from Brollo Aleslay at -3211, +1890, -146 in the southwestern side of the zone.\nYou say, 'Hail, Brollo Aleslay'\nBrollo Aleslay says, 'Ye daft? Whit brings ye intae these [hills]?'\nYou say, 'hills'\nBrollo Aleslay says, 'Aye, these hills, these huir uv a ones? Wa ur ye haur? Wa woods ye e'en come haur? Cannae ye see 'at aw forms ay [monsters] hae taken ower thes place? only a a bampot bodie woods e'en consider comin' haur. But since ye ur haur, ye micht an aw dae some guid haur.'\nYou say, 'monsters'\nBrollo Aleslay says, 'Aye! th' monsters! Dinnae tell me ye haven't run intae thaim! They're a' ower 'n' they're grawin by th' moment! Whitevur haes bin bothering a' o' Velious didn't hain this steid, that?s fur sure! Thare mair undead ice critters 'ere than ever afore 'n' ye don't see me complaining aboot that noo dae ye? Dae ye?! Da ye don't! even whin ah hae tae rammy mah ain kin. Ah beat mah cousin th' ither day wi' a rock fur he wis bitten by yin o' they creatures 'n' he turned intae yin, then ah beat him tae death wi' a shovel, bless his soul, 'n' then he git back up a' covered wi' that ice stuff 'n' then ah picked up a rock 'n' beat him! tis whit ah hud tae dae in order tae protect his fowk, brassic guy. Noo, whit wur we [talking] aboot? och aye! th' critters that need tae be murdurred! Ah hae a slew o' thaim that need tae be...slewed.'\nYou say, ' We were talking about...'\nBrollo Aleslay says, 'Right, aye ye blether tae muckle as it's 'n' we hae a dire situation at haun, if we don't cut doon thae critters sooner ower than efter we ur aff tae be in a heap o' trauchle come th' future. Ah hae a seicont cousin twa times lifted wha hud fought thae hings afore 'n' he said that if ye skelp thaim upside th' heid thay mak' a funny sound lik' BONK or something 'n' then thare wis a SQUISH bit that's beside th' point stoap asking aboot mah cousins! We hae bigger problems tae tak' care o'! A'm needin' ye tae focus at th' hing at haun. Sae 'ere in th' Great Divide, ye kin see that th' coldain hae bin pushed back intae th' caves, hiding fae ilka cratur that haes crawled up fae th' frost. Thay dae this in order tae survive fur if thay don't th' critters wull overwhelm thaim. Bit thay aren't tae bricht ye see, th' monsters wull juist swarm th' caves soon 'n' thay wull be deid anyways 'n' that?s nae whit a' body wants. Urr ye even [listening]?'\nYou say, ' Of course I'm listening, I'm just trying to understa...'\nBrollo Aleslay says, 'Good! yer listening. Sae, ah hae bin oot in thae wastes fur some time noo peepin' whit's gaun oan 'n' learned that thare ur some monsters that ur mair abundant than ithers 'n' they ur th' ones we wull need tae focus. Howfur is yer hunting skills? Likelie nae nearly as guid as mah sisters. She wance hunted 'n' trapped a ran clood. Ah didn't even think sic a thing cuid be maybee aye wi'oot usin` magic. 'n' sin ye brought it up a'm waantin' ye tae ken that usin` magic tae [hunt] is cheating. Ah don't care howfur kin books yer read in yer fancy schools bit that's aye cheating. That defeats th' purpose o' th' hunt itself. Yi''ll need tae git clatty, become yin wi' nature, breath in dirt 'n' cop th' win` atween yer toes! That's howfur ye hunt! nae wi' whispering some curses or drawing fancy stick figures in a rock. Sae if ye uise magic, na offense that's braw 'n' a' bit if ye care aboot mah opinion, whilk ye shuid, ye shuid ken that yer cheating 'n' that's wrong! whin ye pockle at hunting ye pockle at '\nYou say, ' What hunt?'\nBrollo Aleslay says, 'Aye, hunt. That's [whit] ye'r aff tae dae!'\nYou say, 'whit'\nBrollo Aleslay says, 'Gidonoroglets out a long, drawn out sigh and says in a slow, over-annunciated tone, 'Can you hunt [dervishes], [skeletons], or [wurms]?''\nYou say, 'wurms'\nYou have been assigned the task 'Cool and Refreshing'.\n\n---\n\n_The restless ice has infected the wurms here. You have been asked, you think, to reduce their numbers in order to maintain their population. Hopefully, helping Brollo with this problem will bring you one step closer to understanding what he's trying to say._\n1. Kill Restless Wurms 0/9 (The Great Divide)\n\n\n\nSlay wurms found in the central tunnels of the zone.\nYour task 'Cool and Refreshing' has been updated.\n_Hopefully that will keep their population down while you try to figure out what's happening here. However, you are still not any closer to understanding Brollo._\n\n---\n\nReward(s):\n141 platinum 6 gold 6 silver 6 copper\n**Submitted by:** Gidono\n- 141 platinum 6 gold 6 silver 6 copper",
    },
    {
      id = "9765",
      title = "O.M.A.D.",
      exp = "26",
      exp_name = "Torment of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Taskmaster Abyott - ToV",
      loc = { y = -2109.0, x = -1571.0, z = -1.0 },
      triggers = {
        "Hail, Taskmaster Abyott",
        "destroy",
        "Well, here I come then",
        "I",
        "Instead of withering, what if I could help?",
        "assist",
        "What kind of creatures do you eat?",
        "weapon",
      },
      items_required = {
      },
      rewards = {
        { id = 137798, name = "Coldain Lunch Bucket", type = "item" },
        { id = 137796, name = "Fresh Kodiak Meat", type = "item" },
        { id = 137797, name = "Fresh Tizmak Meat", type = "item" },
        { id = 137907, name = "Giant Rations", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Great Divide [ToV]\n**Who:**\n- Taskmaster Abyott - ToV [npc=55136]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n**Quest Items:**\n- Coldain Lunch Bucket [item=137798]\n- Fresh Kodiak Meat [item=137796]\n- Fresh Tizmak Meat [item=137797]\n- Giant Rations [item=137907]\n**Related Creatures:**\n- a corrupted giant [npc=55099]\n- a failed reclaimer [npc=55100]\n- a hardened giant [npc=55108]\n- a relentless tizmak [npc=55109]\n- a vicious kodiak [npc=55113]\n**Related Quests:**\n- Partisan of The Great Divide (10 Points) [quest=9800]\n**Era:** | !Torment of Velious\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sat Nov 30 23:41:47 2019\nModified: Tue Dec 5 05:21:04 2023 | | **Torment of Velious Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this group task from Taskmaster Abyott in Great Divide at -2109, -1571, -1 in the Giant fort on the east side of the zone in the middle building.\nYou say, 'Hail, Taskmaster Abyott'\nTaskmaster Abyott slowly raises his head. You can see his cheekbones protruding from his face. His skin is clearly sunken due to malnourishment. 'Come any closer tiny one, and I will have to eat you! I'm not afraid to...' he attempts to lift his fist but succumbs to weakness. 'I'm not afraid to [destroy] you where you stand!'\nYou say, 'destroy'\nTaskmaster Abyott says, 'You heard me! I'll... we'll... crush you and use your bones for our stews! Ready your [weapon] so that you may die in glorious combat against the kromrif!'\nYou say, ' Well, here I come then'\nTaskmaster Abyott attempts to raise their weapon, only to let it fall to the ground again. 'Oh, well, here they are, Gidonorog, slayer of gods here to wipe out what is left of our small camp. As if things couldn't get any worse for us here. First the ice closed off all exits and entrances to the great divide, making it impossible to get supplies. Then the tizmak and the coldain become those hideous monsters, and now Gidonorog shows up to finish us of. Well you won't get to write in your history books that the kromrif went without a fight, even though we are all [starving]. I bet you wont take that part into consideration when you write what happened today!'\nYou say, 'I'm not going to fight you'\nTaskmaster Abyott says, 'So get on with it then? What do you want? You want to slowly watch us [wither] away? Is that it? Well then good. If you can't fight us yourself like the coward you are, then I will ask that you leave us to our fate. You won't have me begging for my life to the likes of you!'\nYou say, ' Instead of withering, what if I could help?'\nTaskmaster Abyott says, 'You, you would do that for us? Even after all that we have been through you'd still be willing to... save us? Why tiny one? If we survive this, we wont bow to you. Why do you feel the need to [assist] us like that?'\nYou say, 'assist'\nTaskmaster Abyott says, 'Morale is low and, as you can see, we are all starving. We haven't been able to get any food since the ice started killing the animals. Every time we send hunting parties out they either don't come back or they come back empty handed. The [creatures] have all gone to hiding in caves and well, being our size makes attempting to collect them very difficult. As you can also see, we aren't the most inconspicuous of people, so they see our scouts coming from long distances then retreat.'\nYou say, 'What kind of creatures do you eat?'\nTaskmaster Abyott says, 'The kodiaks used to roam these lands freely but have since gone underground. Their meat was tough but hearty. If you can bring us some of their meat, we can use that to get started on a stew to quickly get to our people for some sustenance.'\nYou have been assigned the task 'O.M.A.D.'.\n\n---\n\n_The giants in the Great Divide are starving and have been running out of food. They are too weak to go and fight and forage food for themselves. They need your help to provide them with the food they need to survive._\n1\\. Collect Kodiak Meat 0/10 (The Great Divide)\nTaskmaster Abyott says that the kodiak can be found to the southwest while in or around a cave.\nlooted 5 Fresh Kodiak Meat from a vicious kodiak's corpse\nYour task 'O.M.A.D.' has been updated.\n2\\. Deliver Kodiak Meat 0/10 (The Great Divide)\nBring the meat back to Taskmaster Abyott quickly, as lives are at stake!\nTaskmaster Abyott looks as if they are going to cry, but doesn't. 'This... this is a start. This is hope. Thank you, tiny one, for this offering. Maybe there's a chance we can survive this ordeal. I have another humble request to ask of you. The tizmak were the first to go into hiding when the ice came, and we have been unable to locate any of them. Their meat is something that our people can use for meals as well. Please collect meat from tizmak and bring it back to me.\nYour task 'O.M.A.D.' has been updated.\n3\\. Collect Tizmak Meat 0/10 (The Great Divide)\nThe tizmak have been corrupted but gathering their meat appears to be something that the giants want. Perhaps they can find a way to prepare the meat in order to fill their bellies.\nlooted 5 Fresh Tizmak Meat from a relentless tizmak's corpse.--\nYour task 'O.M.A.D.' has been updated\n4\\. Deliver Tizmak Meat 0/10 (The Great Divide)\nThe meat from the tizmak is already frozen and feels like it's covered with thousands of small creatures as the ice wiggles around within.\nTaskmaster Abyott says, 'This meat is already frozen. You mean to tell me that you found the tizmak still moving and this is what you found on their bodies? I must say that I have seen stranger things, but this is certainly something that is a shock to find. The coldain have also retreated into their mine. While meat is delicious, their lunches used to have assortments of vegetables and brews that could really lift our spirits. From what we have seen so far, the Coldain have also succumbed to this confounding ice. They won't be needing their lunches anymore. Please bring us some of those and we will be able to gather our strength even further.'\nYour task 'O.M.A.D.' has been updated.\n5\\. Collect Coldain Lunch Buckets 0/10 (The Great Divide)\nThe Coldains to the southeast will no longer need their lunch buckets. The giants can use those for nutrition instead of just letting them to go waste on the undead Coldain.\nYour task 'O.M.A.D.' has been updated\n6\\. Deliver Coldain Lunch Buckets 0/10 (The Great Divide)\nOf course, the beer has already been consumed. Why wouldn't it be?\nTaskmaster Abyott says, 'Thank you, tiny one! You have saved my people! This is a good start in helping us survive here, but we still need one more thing in order to thrive. Our scouts that we sent out never came back. They are still out there. We know it. When they left us, they would take rations of dried meats and other fruits with them. These keep for a very long time and new scouts could certainly use them more than... well... than they're currently being used. Please, collect the rations from our fallen brethren.'\nYour task 'O.M.A.D.' has been updated\n7\\. Collect Rations from Giants 0/10 (The Great Divide)\nMany of the giants who were lost didn't get very far, it seems. They can mostly be found around the giant's camp, as if something is preventing them from leaving.\nLoot 6 Giant Rations from a hardened giant or a corrupted giant.\nYour task 'O.M.A.D.' has been updated\n8\\. Deliver Rations from Giants 0/10 (The Great Divide)\nThe rations that the giants can use consist of berries, dried meats, and bread. All of which are frozen solid. Nothing a good fire can't fix.\nTaskmaster Abyott smiles, 'Words cannot describe the appreciation we have for your efforts, tiny one. On behalf of my sundered people, we thank you. We look forward to the days when we regain our full strength and meet you in the field of combat for Rallos Zek! Now, if you will, please leave before I regain enough strength to actually eat you!' The giant gives you a knowing smirk as you turn to leave.\nYour task 'O.M.A.D.' has been updated\n_The Kromrif in the Great Divide are no longer starving and are on the path to recovery because of your efforts today. Though you hope that you didn't create a future problem for yourself, you do see the giants in the camp become more lively because of your actions._\n\n---\n\nReward(s):\n425 platinum\nYou gain experience!\nYou have gained 7 mercenary ability point(s)!\n**Submitted by:** Gidono",
    },
    {
      id = "9912",
      title = "Seeking the Sorcerer",
      exp = "26",
      exp_name = "Torment of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Horasug",
      loc = nil,
      triggers = {
        "Hail, Horasug",
        "What **cause**?",
        "We are **ready**.\nRestless Tijeoly roars as it turns to face its enemies. You hear a responding roar from inside the structure.\nAn icy watcher says,",
        "What about your **people**?\n\n\n\n\nVelketor the Sorcerer says,",
        "_Raid and Quest_",
        "army",
        "sic",
        "leave",
      },
      items_required = {
      },
      rewards = {
        { id = 137865, name = "Glob of Vile Bile", type = "item" },
        { id = 137538, name = "Froststone Ducat", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Status: Incomplete**\n\nQuest Started By: | Description:\n**Where:**\n- The Great Divide [ToV]\n**Who:**\n- Horasug [ _Raid and Quest_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Experience\n- Loot\n- Money\n**Quest Items:**\n- Glob of Vile Bile [item=137865]\n**Related Zones:**\n- Velketor's Labyrinth [ToV]: Seeking the Sorcerer\n**Related Creatures:**\n- Bled Enraged [npc=56391]\n- Icebound Bledrek [npc=55605]\n- Restless Tijoely [npc=55599]\n- a giant chest [npc=55645]\n- a restless fleshpile [npc=55600]\n- an icy watcher [npc=55598]\n**Era:** | !Torment of Velious\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Dec 18 21:02:31 2019\nModified: Tue Dec 5 05:21:04 2023 | | **Torment of Velious Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nThis group mission starts out with Horasug in The Great Divide TOV\nYou say, 'Hail, Horasug'\nHorasug says, 'Hail, adventurer. I hope you have come to help us deal with the [ **cause**] of this nightmare.'\nYou say, 'What **cause**?'\nHorasug says, 'Well, it must be those rotten giants. It's that sorcerer they got, the one that lives in those caves. Why, if our army wasn't locked up safe and snug inside Thurgadin, we'd have an army in there by now to take off his head and stop all this. But you... you might be able to help us. You can gather up an [army] of your adventurin' types and go on in there and deal with him, right? I mean, you might even have success with a smaller [ **group**] if you were real, real tough. I'm not gonna lie to you, that old giant with the stupid hat is dangerous, but maybe you should at least try.\nYou say, We have a small **group**.'\nHorasug says, 'You think you can do it, eh? Well then, when yer [ **ready**] I know a secret way in. Learnt it from my pa.' _[sic]_\nYou have been assigned the task 'Seeking the Sorcerer'.\n\n---\n\nUpon zoning in, there will be a gargoyle to your left named _an icy watcher_ Hail to begin the event.\nYou say, Hail, an icy watcher'\nAn icy watcher says, 'Hush! It will hear you. It's gone mad. The whole place has gone mad. Wait, I know what you are. You're one of those creatures that goes into other people's homes and kills them, right? Well, why don't you go kill the insane creatures that used to serve Velketor and are now trying to kill him? Go do what you do, whenever you are [ **ready**]. Sooner would be better. Of course you could just [leave]. I sure wish I could.'\nYou say, 'We are **ready**.\nRestless Tijeoly roars as it turns to face its enemies. You hear a responding roar from inside the structure.\nAn icy watcher says, 'Good. Good. Free the sorcerer. He'll be able to set things right. I know it.'\n_The Coldain think that Velketor might be the source of the evil ice that has devastated Velious. Your task is to clear out the undead and force the sorcerer to tell you how to stop the evil that he has created._\n1. Free the sorcerer Velketor so that you can speak with him about his restless ice 0/1 (Velketor's Labyrinth)\n\n\n\nBoss 1: Restless Tijeoly - DPS as fast as possible. If you get adds, push-root them away if possible. You manage adds during a mechanic in the second phase of the event.\n\n\n\n\nBoss 2: Icebound Bledrek - During this phase, there will be red rings placed around the ground. There is an AoE that goes off, but does little damage. After the AoE/red ring, a hay-looking object will be on the ground. Have a member of the group pick it up. This item is clickable and allows you to place a green ring somewhere. Place this green ring away from the current min-boss you are fighting. Once placed, all the adds will be attracted to this green ring and leave your group alone.\n\n\n\n\nBoss 3: Bled Enraged - DPS fast again. There shouldn't be any more adds at this point. Occasionally during this phase, a witch may appear. Mez or root away as able, then deal with after the boss.\n5. Convince Velketor to stop his evil ice 0/1 (Velketor's Labyrinth)\n\n\n\nYou say, Hail, Vlketor the Sorcerer'\n\n\n\n\nVelketor the Sorcerer says, 'Thank you! You've saved my life. I hope you've been sent by my king to help, though he has never been overly fond of [ **me**].\n\n\n\n\nYou say, Why hasn't he been fond of **me**?\n\n\n\n\nVelketor the Sorcerer says, 'Me? Tormax has no love for me. But I do have some idea as to the source of this horrible magic. I want this horror to stop, but I must protect my [ **people**]. I refuse to tell you what I know unless you can promise to help me.\n\n\n\n\nYou say, 'What about your **people**?\n\n\n\n\nVelketor the Sorcerer says, 'Rescue them. I will tell you what I can when I can also report what I know to my King.'\n\n\n\n\nYour task ' Seeking the Sorcerer' has been updated.\n9. Open the giant chest 0/1 (Velketor's Labyrinth)\n\n\n\nYour task ' Seeking the Sorcerer' has been updated.\n\n---\n\nReward(s):\n425 platinum\nYou gain experience!\n68x Froststone Ducat\n**Submitted by:** Cylius & Laurana\n- Froststone Ducat [item=137538]",
    },
    {
      id = "8612",
      title = "Conqueror of Icewell Keep",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "Seneschal Aldikar",
      loc = nil,
      triggers = {
        "hail",
      },
      items_required = {
        { id = 30369, name = "Item #30369", count = 1 },
        { id = 30369, name = "Item #30369", count = 1 },
        { id = 1739, name = "Item #1739", count = 1 },
      },
      rewards = {
        { id = 30369, name = "Item #30369", type = "item" },
        { id = 18511, name = "Item #18511", type = "item" },
        { id = 30385, name = "Item #30385", type = "item" },
        { id = 1741, name = "Item #1741", type = "item" },
        { id = 1746, name = "Item #1746", type = "item" },
        { id = 1745, name = "Item #1745", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon completing the following raids in Icewell Keep:\nChamberlain Krystorf\nDain Frostreaver IV\nSeneschal AldikarSubmitted by: GidonoRewards:\n[",
    },
  },
}
