-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for The Grounds (housegarden)
-- Total Quests: 10
-- ============================================================================

return {
  zone = "housegarden",
  zone_name = "The Grounds",
  quests = {
    {
      id = "5174",
      title = "Mashing Pumpkins",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Barkley",
      loc = { y = 890.0, x = -1970.0, z = -190.0 },
      triggers = {
        "Hail, Barkley",
        "Tired, why?",
        "Pumpkins?",
        "I",
        "_Mission_",
        "tired",
        "pumpkins",
        "rid",
      },
      items_required = {
        { name = "Giladan the book", count = 1 },
      },
      rewards = {
        { id = 92870, name = "Leaf Engraved Tome", type = "item" },
        { id = 92904, name = "Missing Page", type = "item" },
        { id = 92714, name = "Ripe Pumpkin", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Grounds [zone=749]\n**Who:**\n- Barkley [ _Mission_]\nRating:\n0/4**_\\*__\\*__\\*__\\*__\\*_**\n(Average from 4 ratings)\nInformation:\n**Level:** | 85\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Loot\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 06:00:00\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Quest Items:**\n- Leaf Engraved Tome [item=92870]\n- Missing Page [item=92904]\n- Ripe Pumpkin [item=92714]\n**Related Zones:**\n- The Grounds: Mashing Pumpkins [zone=767]\n**Related Creatures:**\n- Azarianel [npc=36543]\n- Barkley [npc=36536]\n- Ghrechla the Patch Warden [npc=36535]\n- Giladan the Botanist [npc=36537]\n- The Spirit of the Patch [npc=36542]\n- a peponnite [npc=36541]\n- an ornate chest - Mashing Pumpkins [npc=36534]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 2 00:43:24 2010\nModified: Thu Jan 30 06:13:38 2025 | | _This is a non-progression group task (3-6 players) that begins with Barkley in the Grounds at location 890, -1970, -190 (northern part of the zone in the pumpkin patch)._\n_There are no pre-requisites for requesting the task._\nYou say, 'Hail, Barkley'\nBarkley says 'Fear not, little one. I will not harm you. I am too [tired] to do so even if I wanted to.'\nYou say, 'Tired, why?'\nBarkley says 'If only I could stretch my legs a bit. The [pumpkins] growing nearby have entangled my feet with their unbreakable roots, making it impossible for me to move. It is becoming rather uncomfortable.'\nYou say, 'Pumpkins?'\nBarkley says 'A while back, a spirit appeared and then the pumpkins began sprouting up. Their roots grew fast and strong, entangling my feet. I normally fend for myself, but I am unable to do so at the moment. Would you be willing to help me get [rid] of those pumpkins?'\nYou say, 'I'll get rid of them'\nBarkley says 'You will help me? Thank you. When you are ready to [start] just let me know.'\nYou have been assigned the task 'Mashing Pumpkins'.\n\n---\n\n_Note: All mobs in this instance see invisibility. They have low aggro ranges, but medium assist ranges. Nothing respawns. Peponnites may be unmezzable._\nSpeak with Ghrechla near the pumpkin patch 0/1 (The Grounds)\nReturn to Barkley and speak with him 0/1 (The Grounds)\nSee if you can find Giladan somewhere in the garden and speak with him 0/1 (The Grounds)\nFind the book in the hedge maze area of the garden and return it to Giladan 0/1 (The Grounds)\n_A Leaf Engraved Tome is found at +570, -1640, -190 (exact center of the hedge)._\nSpeak with Giladan regarding the book 0/1 (The Grounds)\nFind the three missing pages of the book and return them to Giladan 0/3 (The Grounds)\n_These pages are found as ground spawns where the rotdogs are located._\n_When you give Giladan the book, the rotdogs begin spawning nearby. You'll want to move away as soon as you do the book turn-in and hail otherwise you may get swarmed._\n_The pages appear as tiny scrolls:_\n+440, -2070, -177\n+360, -1895, -158\n+227, -1745, -132\nSpeak with Giladan 0/1 (The Grounds)\nSpeak with Barkley 0/1 (The Grounds)\nGather Ripe Pumpkins from the pepponites and smash them in the pumpkin smasher near Barkley 0/10 (The Grounds)\n_These drop off the peponnites. To smash them, right-click them in the building near Barkley._\nSpeak with the Spirit of the Patch and reveal his name to him 0/1 (The Grounds)\nDefeat Azarianel! 0/1 (The Grounds)\nReturn to Barkley and speak with him 0/1 (The Grounds)\nClaim your reward from the ornate chest 0/1 (The Grounds)\n\n---\n\n_Task Rewards:_\n315 platinum\nExperience (about 6% regular exp at Level 86 or 4-14 AAs worth depending on your current count)\nFaction with Dream Delvers\n40 Dream Motes\n_Known chest rewards (1 item + 1 spell per task):_\nAlluring Ivory Dagger\nCane of Feral Essence\nChipped Shard of Appeasement\nDiamondcast Ailettes of the Champion\nEngraved Prayer Earring\nRunewand of Necropotence\nThulian Linked Armguards\nThulian Linked Boots\nTotem of Riggbit's Bouncing Banality\nTreant Refuse\nMinor Nebulous Dream Fragment\nLesser Nebulous Dream Fragment\nMedian Nebulous Dream Fragment\nGreater Nebulous Dream Fragment\nGlowing Nebulous Dream Fragment\n**Submitted by:** Vanrau of Xegony\n- Dream Mote [item=90255]",
    },
    {
      id = "5170",
      title = "Here Doggy Doggy",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Giladan the Botanist",
      loc = { y = -65.0, x = -1700.0, z = -105.0 },
      triggers = {
        "Hail, Giladan the Botanist",
        "Dogs?",
        "Anything I can do?",
        "_Quests_",
        "work",
        "peponnites",
        "tree",
        "bixies",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Grounds [zone=749]\n**Who:**\n- Giladan the Botanist [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Creatures:**\n- a rotdog [npc=35731]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 2 00:03:40 2010\nModified: Thu Jul 28 14:53:14 2011 | | _This is a solo kill task that begins with Giladan the Botanist at location -65, -1700, -105 in the Grounds (due east of the zone-in; just east of the central garden and next to Spensur, the Rk. III spell NPC)._\nYou say, 'Hail, Giladan the Botanist'\nGiladan the Botanist says 'These blasted things won't let me get any [work] done! First it's those rude [peponnites], then the arrogant [tree] things, then the buzzing [bixies], then those flea infested [dogs], and finally that awful pond scum [snake] and its offspring! It's no wonder why this once beautiful place is gone in the gutter!'\nYou say, 'Dogs?'\nGiladan the Botanist says 'Nothing worse than a mangy canine! They ruin the plants, as well as eat everything in sight! They are just no good to a flourishing garden. Is there [anything] you can do?'\nYou say, 'Anything I can do?'\nGiladan the Botanist says 'Kill as many of them as you can! The flea-ridden pests!'\nYou have been assigned the task 'Here Doggy Doggy'.\nThere is nothing that Giladan despises more than rotdogs. He has asked you to kill some for him.\n\n---\n\nKill 6 rotdogs 0/6 (The Grounds)\nSpeak with Giladan the Botanist 0/1 (The Grounds)\nYou say, 'Hail, Giladan the Botanist'\nGilanda the Botanist says 'Thank you! The only good rotdog is a dead rotdog. That's what I say!'\n_Rewards:_\nExperience\nMinor Faction with Dream Delvers",
    },
    {
      id = "5157",
      title = "Giladan \\#1: Giladan's Assistant",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Giladan the Botanist",
      loc = { y = -65.0, x = -1700.0, z = -105.0 },
      triggers = {
        "Hail, Giladan the Botanist",
        "What work?",
        "What fauna?",
        "What trouble?",
        "I will help",
        "Hail, Ikaena the Bonesmith",
        "I want the flower...",
        "What something is that?",
      },
      items_required = {
      },
      rewards = {
        { id = 92542, name = "Golem Bones", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Grounds [zone=749]\n**Who:**\n- Giladan the Botanist [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 85\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Success Lockout Timer**: 06:00:00\n**Factions Raised:**\n- Dream Delvers +10\n**Factions Lowered:**\n**Quest Items:**\n- Golem Bones [item=92542]\n**Related Creatures:**\n- Ikaena the Bonesmith [npc=36088]\n- Lost Golem [npc=35923]\n**Related Quests:**\n- Giladan #2: What a Mess [quest=5158]\n- Giladan #3: It Only Gets Worse [quest=5159]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Oct 27 02:56:24 2010\nModified: Tue Dec 5 05:21:04 2023 | | This task is the first in a series of three that begins with Giladan the Botanist [npc=36092] at location -65, -1700, -105 in the Grounds (due east of the zone-in; just east of the central garden and next to Spensur [npc=35726], the Rk. III spell NPC).\nYou say, 'Hail, Giladan the Botanist'\nGiladan the Botanist says 'These blasted things won't let me get any [work] done! First it's those rude [peponnites], then the arrogant [tree] things, then the buzzing [bixies], then those flea infested [dogs], and finally that awful pond scum [snake] and its offspring! It's no wonder why this once beautiful place is gone in the gutter!'\nYou say, 'What work?'\nGiladan the Botanist says 'This garden used to be such a lovely place, and I've come a long way just to study the [fauna] here.'\nYou say, 'What fauna?'\nGiladan the Botanist says 'I am a botanist, and there are some especially rare plants that grow here. But I've come into a bit of [trouble], so I am unable to do much of anything.'\nYou say, 'What trouble?'\nGiladan the Botanist says 'It is utter chaos here! Well, at least for me! I cannot go anywhere without getting attacked by something or other. And this is why I need your [help].'\nYou say, 'I will help'\nGiladan the Botanist says 'Thank you! You'll need to speak to Ikaena the Bonesmith at the mausoleum. He has information regarding one of the plants I am looking for.'\nYou have been assigned the task 'Giladan's Assistant'.\n\n---\n\nSpeak to Ikaena the Bonesmith 0/1 (The Grounds)\nIkaena the Bonesmith [npc=36088] is found in a building in the northeastern corner of the Grounds. There are numerous bone casters and bone golems around the area, many of which see through invisibility.\nYou say, 'Hail, Ikaena the Bonesmith'\nIkaena the Bonesmith says 'Giladan is too scared to come himself? HA! That little gnome should have stayed home then! It is the Antheia Bloom [flower] you want then? '\nYou say, 'I want the flower...'\nIkaena the Bonesmith says 'Very well... But you have to do [something] for me first, since you are so... willing to help.'\nYou say, 'What something is that?'\nIkaena the Bonesmith says 'One of our golems seems to have wandered away. You must track it down and [destroy] it.'\nYou say, 'Destroy it?'\nIkaena the Bonesmith says 'Yes. It has been gone far too long for us to ever hope that it will follow orders. Kill it and bring back its bones so we can rebuild another.'\nKill 1 Lost Golem 0/1 (The Grounds)\nYou can find Lost Golem [npc=35923] in the western part of the zone's northwestern quadrant. It hits for a max ~6,500.\nLost Golem has been slain by \\_\\_\\_\\_\\_!\nLost Golem's corpse uses its last bit of strength to stand and fight before dying at your feet.\nLoot the Golem Bones 0/1 (The Grounds)\nGive the Golem Bones to Ikaena the Bonesmith 0/1 (The Grounds)\nSpeak with Ikaena the Bonesmith 0/1 (The Grounds)\nYou say, 'Hail, Ikaena the Bonesmith'\nIkaena the Bonesmith says 'You have done what I asked, and I would tell you how to find the Antheia Bloom. But unfortunately, it is no longer here. Destroyed by those foul rotdogs! They eat them, among other things. But even that information may be of use to Giladan. Now go.'\nSpeak with Giladan the Botanist 0/1 (The Grounds)\nYou say, 'Hail, Giladan the Botanist'\nYou've brought Giladan the information he sought.\n_Rewards:_\n210 platinum\nExperience (about 1.5 AAs at Level 90 or a little less than 1 AA at Level 95)\nFaction with Dream Delvers (+10)\n13 Dream Motes [item=90255]\n- Dream Mote [item=90255]",
    },
    {
      id = "5158",
      title = "Giladan \\#2: What a Mess",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Giladan the Botanist",
      loc = { y = -65.0, x = -1700.0, z = -105.0 },
      triggers = {
        "Hail, Giladan the Botanist",
        "Someone?",
        "The warden?",
        "I",
        "Strangers?",
        "Giladan wants to know about an antheia bloom",
        "Rotdogs?",
        "Who",
      },
      items_required = {
        { name = "you the information you seek", count = 1 },
      },
      rewards = {
        { id = 92622, name = "Antheia Bloom Seed", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Grounds [zone=749]\n**Who:**\n- Giladan the Botanist [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Success Lockout Timer**: 06:00:00\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Quest Items:**\n- Antheia Bloom Seed [item=92622]\n**Related Creatures:**\n- Ghrechla the Patch Warden [npc=36093]\n- Meikona the Keeper [npc=36095]\n- a rotdog [npc=35731]\n**Related Quests:**\n- Giladan #1: Giladan's Assistant [quest=5157]\n- Giladan #3: It Only Gets Worse [quest=5159]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Oct 27 02:56:35 2010\nModified: Tue Dec 5 05:21:04 2023 | | _This task is the second in a series of three that begins with Giladan the Botanist at location -65, -1700, -105 in the Grounds (due east of the zone-in; just east of the central garden and next to Spensur, the Rk. III spell NPC)._\n_You must have completed his first task prior to being able to request this one._\nYou say, 'Hail, Giladan the Botanist'\nGiladan the Botanist says 'Ah, you've returned just in time! I believe I know [someone] who can help us.'\nYou say, 'Someone?'\nGiladan the Botanist says 'The patch [warden] of the peponnites! Goes by the name Gren... Ghor... Ghrechla, that's it!'\nYou say, 'The warden?'\nGiladan the Botanist says 'Ghrechla oversees the patch to the north. If anyone knows about what grows here, it would be Ghrechla! You must [speak] with him at once!'\nYou say, 'I'll speak with him'\nGiladan the Botanist says 'Thank you. Your help really is appreciated.'\nYou have been assigned the task 'What a Mess'.\n\n---\n\nSpeak to Ghrechla the Patch Warden 0/1 (The Grounds)\n_Ghrechla is found in the north-central part of the zone, in the pumpkin patch._\nGhrechla the Patch Warden says 'Ghrechla has no time for [strangers] now. Leave or suffer your fate at the hands of Ghrechla!'\nYou say, 'Strangers?'\nGhrechla the Patch Warden says 'You are not stranger to Ghrechla? He does not know you he thinks. He thinks you are a [pretender]!'\nYou say, 'I'm not a pretender!'\nGhrechla the Patch Warden says 'Giladan? Ghrechla knows of this [Giladan]. He hides from all that is here in the garden. Ghrechla knows everything that goes on in the garden!'\nYou say, 'Giladan wants to know about an antheia bloom'\nGhrechla the Patch Warden says 'The antheia bloom? There be no antheia bloom here! Not since the [rotdogs] devoured them.'\nYou say, 'Rotdogs?'\nGhrechla the Patch Warden says 'Ghrechla knows it is futile to look. No hope. No way. Nothing can do. But... Ghrechla knows [Meikona] would know a way, if one exists.'\nYou say, 'Who's Meikona?'\nGhrechla the Patch Warden says 'The [leader] of the bixies to the south. Not as great as Ghrechla, but they did be the ones that planted the Antheia Bloom long time ago, refuse to re-plant because of the rotdogs!'\nYou say, 'The leader?'\nGhrechla the Patch Warden says 'Them bixies do not take kindly to strangers. You will no doubt have to fight your way in just to speak with her. Ghrechla has much to do. '\nSpeak with Meikona the Keeper 0/1 (The Grounds)\n_Meikona the Keeper is in a building inside the bixie fort in the south-central part of the Grounds._\nYou say, 'Meikona the Keeper'\nMeikona the Keeper says '(Angry) What gives you the right to [attack] us?!'\nYou say, 'Attack?'\nMeikona the Keeper says 'My workers were only protecting the hive! It is their duty! Many you have killed, and now you seek [audience] with me?!'\nYou say, 'I do seek an audience with you'\nMeikona the Keeper says 'Antheia bloom?! You [kill] my people over a flower?!'\nYou say, 'Kill?'\nMeikona the Keeper says 'Uh... My death would solve nothing... so... I will give you the information you seek, if that means you will [leave].'\nYou say, 'I'll leave if you tell me'\nMeikona the Keeper says 'Very well... The seeds of the Antheia Bloom are very resilient. They do not digest easily, if at all. You will have to take them from the rotdogs directly. There! I gave you what you wanted, whatever good that will do.'\nLoot 4 Antheia Bloom Seeds from rotdogs 0/4 (The Grounds)\n_Rotdogs drop the seeds._\n_NOTE: These are not pre-lootable._\nGive 4 Antheia Bloom Seeds to Giladan the Botanist 0/4 (The Grounds)\nSpeak with Giladan the Botanist 0/1 (The Grounds)\nYou say, 'Hail, Giladan the Botanist'\nGiladan the Botanist says 'You found them where?! I don't envy you at all! Ha, ha, ha! But I do thank you!'\n_Rewards:_\n210 platinum\nExperience\nFaction with Dream Delvers\n13 Dream Motes\n- Dream Mote [item=90255]",
    },
    {
      id = "5160",
      title = "The Gardener",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Gardener Aeriht",
      loc = nil,
      triggers = {
        "Hail, Gardener Aeriht",
        "What do you want my help for?",
        "I will stop them",
        "Ready!",
        "_Mission_",
        "help",
        "stop",
      },
      items_required = {
      },
      rewards = {
        { id = 90476, name = "Aeriht's Book Binding", type = "item" },
        { id = 92555, name = "Piece of Aeriht's Book", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Grounds [zone=749]\n**Who:**\n- Gardener Aeriht [ _Mission_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 65\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Faction\n- Loot\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 06:00:00\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Quest Items:**\n- Aeriht's Book Binding [item=90476]\n- Piece of Aeriht's Book [item=92555]\n**Related Zones:**\n- The Grounds: The Gardener [zone=765]\n**Related Creatures:**\n- Aerihts Construct [npc=36362]\n- Bulwark of the Orchard [npc=36356]\n- Deceiver Aeriht [npc=36361]\n- Gardener Aeriht [npc=36360]\n- Protector of the Patch [npc=36355]\n- Soldier of the Hive [npc=36357]\n- Thule Servant [npc=36359]\n- a dirty chest [npc=36363]\n**Related Quests:**\n- Giladan #1: Giladan's Assistant [quest=5157]\n- Giladan #2: What a Mess [quest=5158]\n- Giladan #3: It Only Gets Worse [quest=5159]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Oct 27 03:40:14 2010\nModified: Wed May 1 14:34:05 2024 | | _This is a group progression mission (3-6 players) that begins with Gardener Aeriht in the Grounds (just north of the Well entrance in the southern part of the zone)._\n_In order to request this task, you must have previously completed Giladan the Botanist's three solo tasks (not the kill tasks) as well as the Tier 1 group progression missions \"Fall of the Tae Ew\" and \"Welcome to My Nightmare\"._\nYou say, 'Hail, Gardener Aeriht'\nGardener Aeriht says 'So, you are the one that has been helping that botanist fellow. I have heard of you! Making a mess of things around here! Sure, this place is dangerous, but that is just how I like it! It keeps out the riff raff! Now, you have gone and upset the balance of things around here. But since you like helping so much, perhaps you can [help] me?'\nYou say, 'What do you want my help for?'\nGardener Aeriht says 'The place is in turmoil! And because of you, they are planning an uprising! That, I cannot have! You must put a [stop] to them before they gain any more momentum.'\nYou say, 'I will stop them'\nGardener Aeriht says 'There is also something I need from you while you are ending this revolt. I seemed to have lost my book. But with the natives so aggravated, they have torn it into three pieces and each is keeping a piece. You will get these pieces back. That is what you are good for anyway, is it not? Let me know when you are ready, so that we can proceed.'\nYou have been assigned the task 'The Gardener'.\nBlaming you for the current state of unrest here in the garden, Aeriht wants you to end the uprising of certain creatures, while also retrieving his book that is being held by them.\nYou say, 'Ready!'\nGardener Aeriht says 'Be careful! And do not forget the pieces of the book!'\n\n---\n\nRecon the bixie's forces in the hive 0/1 (The Grounds)\nRecon the peponnite's forces in the patch 0/1 (The Grounds)\nRecon the treant's forces in the orchard 0/1 (The Grounds)\n_The bixies are in the south. The patch is in the north. The treants are in the northwest. These steps update just outside the areas for each of the above._\nReport to Aeriht about all three forces 0/1 (The Grounds)\nYou say, 'Hail, Gardener Aeriht'\nGardener Aeriht says 'Excellent! I mean... very well. They will need to be dealt with immediately before they can grow in numbers.'\nGardener Aeriht says 'The garden creatures are rising up against me! I must have your assistance!'\nCommence attack on the bixie hive 0/8 (The Grounds)\nRetrieve a piece of Aeriht's book from the bixie who stole it 0/1 (The Grounds)\n_Kill any eight of the bixies and loot part of the book from their corpses. Repeat this process for the peponnites and the treants._\n_Target mobs in this task hit for a max ~6,500. All kill targets see invisibility and are in close proximity to each other (you'll have 2-3 per pull without a splitter). Peponnites, bixies, and treants are mezzable. The peponnites can flurry. Some of the Thule Servants are mezzable while some may be immune._\nCommence attack on the peponnite's patch 0/8 (The Grounds)\nRetrieve a piece of Aeriht's book from the Protector of the Patch who stole it 0/1 (The Grounds)\nCommence attack on the treant's orchard 0/8 (The Grounds)\nRetrieve a piece of Aeriht's book from the Bulwark of the Orchard who stole it 0/1 (The Grounds)\nDeliver the pieces of the book to Aeriht 0/1 (The Grounds)\nGardener Aeriht says 'I see now why the botanist relied on you so much. This is most excellent! I just need one more thing from you. I have just discovered that one of those irritating servants has the binding to my book. You will need to retrieve it.'\nRetrieve the binding from the Thule servants 0/1 (The Grounds)\n_Numerous Thule Servants can be found in the western part of the zone (the area leading the House of Thule zone-in)._\nDeliver the book binding to Aeriht 0/1 (The Grounds)\nGardener Aeriht says 'Finally! I have it! All I have ever been was a stinking gardener! But no more! Now, you will see the power of Aeriht!'\n_He respawns as Deceiver Aeriht and attacks immediately along with a few \"Aerihts Construct\". Deceiver Aeriht hits for a max ~8,500. He is slowable, but not rootable/snareable. The constructs hit for a little less and are rootable/snareable. There is an achievement associated with leaving them alive._\n_Note: You can have someone with FD or fade do the turn-in and then single-pull Aeriht from a distance._\nKill Deceiver Aeriht 0/1 (The Grounds)\nAfter this, the task locks.\n4 Aeriht's Constructs spawn with Aeriht. They are not mezzable.\nCollect your reward from the dirty chest 0/1 (The Grounds)\n\n---\n\n_Task Rewards:_\nExperience (about 2 AAs at Level 90)\n315 platinum\n30 Dream Motes\nFaction with Dream Delvers\n_Known chest rewards (1 item + 1 spell per task):_\nEmpyrean Hammer\nEthereal Focus Blade\nNighmarish Page of Empowerment\nPrismatic Hukus Ring\nSpirit Sword of the Slain\nTantarene Gem of Heretical Power\nThulian Linked Gauntlets\nThulian Linked Legplates\nVenilinam's Serpentine Band\nVial of Death Stinger's Venom\nMinor Nebulous Dream Fragment\nLesser Nebulous Dream Fragment\nMedian Nebulous Dream Fragment\nGreater Nebulous Dream Fragment\nGlowing Nebulous Dream Fragment\n- Dream Mote [item=90255]",
    },
    {
      id = "5168",
      title = "Taking on the Hive",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Giladan the Botanist",
      loc = { y = -65.0, x = -1700.0, z = -105.0 },
      triggers = {
        "Hail, Giladan the Botanist",
        "Bixies?",
        "I",
        "_Quests_",
        "work",
        "peponnites",
        "tree",
        "bixies",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Grounds [zone=749]\n**Who:**\n- Giladan the Botanist [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 80\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Creatures:**\n- a bixie guard [npc=36107]\n- a wasp - The Grounds [npc=35732]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 2 00:03:32 2010\nModified: Sun Feb 15 15:44:34 2026 | | This is a solo kill task that begins with Giladan the Botanist [npc=36092] at location -65, -1700, -105 in the Grounds (due east of the zone-in; just east of the central garden and next to Spensur, the Rk. III spell NPC).\nYou say, 'Hail, Giladan the Botanist'\nGiladan the Botanist says 'These blasted things won't let me get any [work] done! First it's those rude [peponnites], then the arrogant [tree] things, then the buzzing [bixies], then those flea infested [dogs], and finally that awful pond scum [snake] and its offspring! It's no wonder why this once beautiful place is gone in the gutter!'\nYou say, 'Bixies?'\nGiladan the Botanist says 'They are so vital to the pollination of all the plants here, that it was only natural that I would be interested in talking to them. But you know what I got for my trouble? Aggression and just all around bad manners! Maybe if you could... [persuade] them, if you know what I mean.'\nYou say, 'I'll persuade them...'\nGiladan the Botanist says 'You may want to exterminate some of their wasp helpers too.'\nYou have been assigned the task 'Taking on the Hive'.\nGiladan has asked you to persuade the bixie hive into letting him into that area to speak with them.\n\n---\n\n1\\. Kill 6 bixies 0/6 (The Grounds)\n2\\. Kill 5 wasps 0/5 (The Grounds)\n3\\. Speak with Giladan the Botanist 0/1 (The Grounds)\nYou say, 'Hail, Giladan the Botanist'\nGiladan the Botanist says 'Thank you so much for your help. Perhaps now they will be more open to outsiders!'\n_Rewards:_\nExperience\nMinor Faction with Dream Delvers",
    },
    {
      id = "5169",
      title = "The Bigger They Are",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Giladan the Botanist",
      loc = { y = -65.0, x = -1700.0, z = -105.0 },
      triggers = {
        "Hail, Giladan the Botanist",
        "What about those tree things?",
        "I",
        "_Quests_",
        "work",
        "peponnites",
        "tree",
        "bixies",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Grounds [zone=749]\n**Who:**\n- Giladan the Botanist [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Creatures:**\n- a souring treant [npc=35738]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 2 00:03:36 2010\nModified: Thu Jul 28 14:50:45 2011 | | _This is a solo kill task that begins with Giladan the Botanist at location -65, -1700, -105 in the Grounds (due east of the zone-in; just east of the central garden and next to Spensur, the Rk. III spell NPC)._\nYou say, 'Hail, Giladan the Botanist'\nGiladan the Botanist says 'These blasted things won't let me get any [work] done! First it's those rude [peponnites], then the arrogant [tree] things, then the buzzing [bixies], then those flea infested [dogs], and finally that awful pond scum [snake] and its offspring! It's no wonder why this once beautiful place is gone in the gutter!'\nYou say, 'What about those tree things?'\nGiladan the Botanist says 'There are some very peculiar trees in the orchard, but the treants won't let me do my work. Maybe if you [cleared] out some of them I will have a short opportunity to get what I need.'\nYou say, 'I'll see them cleared'\nGiladan the Botanist says 'Thank you. Just a handful would probably help.'\nYou have been assigned the task 'The Bigger They Are'.\nGiladan needs you to thin out the number of treants in the orchard so that he can study the trees there.\n\n---\n\nKill 5 souring treants 0/5 (The Grounds)\n_Souring treants are found in the northwestern part of the zone as well as the southeastern section._\nSpeak with Giladan the Botanist 0/1 (The Grounds)\nYou say, 'Hail, Giladan the Botanist'\nYour task 'The Bigger They Are' has been updated.\nGiladan the Botanist says 'Excellent! Thank you so much!'\n_Rewards:_\nExperience\nMinor Faction with Dream Delvers",
    },
    {
      id = "5172",
      title = "The Last One",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Grithlan Vraniq",
      loc = { y = -185.0, x = -1935.0, z = -223.0 },
      triggers = {
        "Hail, Grithlan Vraniq",
        "Help you how?",
        "Deirdre?",
        "I",
        "Hail, Orloh",
        "I want to know about Grithlan",
        "You know Grithlan...",
        "What do you remember?",
      },
      items_required = {
      },
      rewards = {
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Grounds [zone=749]\n**Who:**\n- Grithlan Vraniq [npc=36109]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Factions Raised:**\n- Dream Delvers +10\n**Factions Lowered:**\n**Related Zones:**\n- Feerrott, the Dream [zone=747]\n- The Foundation [zone=709]\n- The Grounds [zone=749]\n**Related Creatures:**\n- Orloh [npc=35822]\n- Shalma [npc=35810]\n- Weaver [npc=37450]\n- Weavers bodyguard [npc=37451]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 2 00:17:09 2010\nModified: Sun Apr 7 14:12:14 2024 | | _This solo task begins with Grithlan Vraniq in the Grounds. He is located at -185, -1935, -223._\nYou say, 'Hail, Grithlan Vraniq'\nGrithlan Vraniq says 'Thank the gods! I've been waiting for what seems like an eternity for someone who can [help] me!'\nYou say, 'Help you how?'\nGrithlan Vraniq says 'I've been trapped in this damnable place for many seasons now searching for my [Deirdre]. She'd come to see the garden, but unfortunately, I could not come with her as I was away at the time. But when I returned, I found that she had not.'\nYou say, 'Deirdre?'\nGrithlan Vraniq says 'I know she traveled through many places to get here, so I started here. But I've not been able to leave this place! If you could [assist] me, I'd be eternally grateful!'\nYou say, 'I'll assist you'\nYou have been assigned the task 'The Last One'.\nGrithlan is looking for his lost love Deidre. Help him find out what her fate was and help him find his way back to her.\n\n---\n\n1\\. Speak with Orloh in the Feerrott 0/1 (Feerrott, the Dream)\n_You can find Orloh at location -255, 535, -10._\nYou say, 'Hail, Orloh'\nOrloh says 'What you [want]? No time for chit chat. No time at all. Time!'\nYou say, 'I want to know about Grithlan'\nOrloh says 'Grithlan? I know no [Grithlan]! Nonsense! You bug me with nonsense! Nonsense!'\nYou say, 'You know Grithlan...'\nOrloh says 'I told you...Oh yes... [Remember] him I do. Remember.'\nYou say, 'What do you remember?'\nOrloh says 'Not my business. No business of mine. And no [business] of yours too, if you know what is good for you. No business.'\nYou say, 'What business?'\nOrloh says 'As I told him, the garden is no place to visit. He did not listen, and seen him no more have I. Him or his girl. His [girl].'\nYou say, 'His girl?'\nOrloh says 'So he got you looking for [her] eh? Sucker born... blah, blah, blah. Sucker!'\nYou say, 'Who is 'her'?'\nOrloh says 'Tell you same thing I told him. Same thing. She came here looking to get passage to the garden. But she talked to Weaver.'\nYou say, 'Weaver?'\nOrloh says 'How should I know where he is? Do I look like his keeper? No I do not. Do not! [Shalma] is who you need to speak with. Speak with.'\nYou say, 'Shalma?'\nOrloh says 'Shalma is partnered with Weaver! She is around here somewhere. Perhaps near the temple. Always poking her nose into things that don't concern her. Concern her!'\n2\\. Find and speak with Shalma 0/1 (Feerrott, the Dream)\n_Shalma can be found in the Feerrott at location -1110, 630._\nYou say, 'Hail, Shalma'\nShalma says 'Greetings stranger. What can Shalma [do] for you?'\nYou say, 'Here's what you can do...'\nShalma says 'Weaver is not available right now, but I am sure Shalma can [help] you.'\nYou say, 'Help me...'\nShalma says 'You are wasting my time, something I value. As I told you Weaver is not [here]!'\nYou say, 'He's not here?'\nShalma says 'Fine! Enough! He went to the Underfoot. Had some business in Foundation. '\n3\\. Kill the bodyguards that protect Weaver 0/5 (The Foundation)\n_When you zone into the Foundation, hug the right wall take the tunnel. You'll arrive at the Weaver camp._\n_The bodyguards are KOS, but don't aggro. You can talk to Weaver first if you want, or kill the five bodyguards and then talk._\n_They are snarable and don't summon._\n4\\. Speak to Weaver about Grithlan 0/1 (The Foundation)\nYou say, 'Hail, Weaver'\nWeaver says 'Shalma needs to learn to keep her mouth shut! What do you [want]?'\nYou say, 'I want to know about Grithlan'\nWeaver says 'Grithlan??? That fool? I told him his search was futile. The garden is not the place in which one would want to be lost. Many travelers have been lost there. Especially because of what they do to [people] that do go there.'\nYou say, 'People?'\nWeaver says 'They change them! How do you think they get the many servants that roam that place? That was most likely her fate at the hands of the garden.'\n5\\. Tell Grithlan what you have found out 0/1 (The Grounds)\nYou say, 'Hail, Grithlan Vraniq'\nGrithlan Vraniq says 'Weaver did tell me that. But I refuse to believe that until I see it with my own eyes! You must find her! If she made it here, I am sure there are others who have seen her. But they will not talk to me. I am ignored like I am not even here!'\n6\\. Speak to Ikaena about Deirdre 0/1 (The Grounds)\n_Ikaena is found in a building in the northeastern corner of the Grounds. There are numerous bone casters and bone golems around the area, many of which see invisibility._\nYou say, 'Hail, Ikaena the Bonesmith'\nIkaena the Bonesmith says 'I have not seen anyone like you describe. But it is true that she may have fallen to the hands of the servants.'\n7\\. Speak to Meikona about Deirdre 0/1 (The Grounds)\n_Meikona the Keeper is in a building inside the bixie fort in the south-central part of the Grounds._\nYou say, 'Hail, Meikona the Keeper'\nMeikona the Keeper says 'Can you not just leave us be?! I have not seen who you are looking for!'\n8\\. Speak to Giladan about Deirdre 0/1 (The Grounds)\nYou say, 'Hail, Giladan the Botanist'\nGiladan the Botanist says 'Hmm. . . very interesting indeed. I do recall seeing a young woman some time ago. But it was just once, and I never saw her again. But she did ask for directions to the maze.'\n9\\. Search the maze for Deirdre 0/1 (The Grounds)\n_Find Deirdre in the hedge maze in the north-central part of the zone._\nYou say, 'Hail, Deirdre'\nDeirdre says 'You have freed me. For that I am in your debt. Please tell Grithlan that I will see him again, where we can spend eternity together.'\n10\\. Kill 4 servants of Thule 0/4 (The Grounds)\n11\\. Return to Grithlan Vraniq 0/1 (The Grounds)\nYou say, 'Hail, Grithlan Vraniq'\nYou have found out the fate of Deirdre and helped Grithlan so that they can be together again.\nGrithlan Vraniq says, 'You found her?! My dear Deirdre? She has gone to a better [place]. Of that, I am certain.'\nYou say, 'You're dead, brother. You and her are in the same place.'\nGrithlan Vraniq says, 'I am what? Dead? How can that be? I remember... I remember... I fell to the serpent of the pond. I remember now. That is why I could not leave. That is why no one would listen. It all makes [sense].'\nYou say, 'Now that this all makes sense... What will you do?'\nGrithlan Vraniq says, 'I can now be at peace. I can move on and be with Deirdre forever. Thank you. You have done so much for me. I must go now. My Deirdre will be waiting.'\n\n---\n\n_Rewards:_\n210 platinum\nExperience (about 2.5 AAs worth)\nFaction with Dream Delvers has been adjusted by 10\n13 Dream Motes\n- Dream Mote [item=90255]",
    },
    {
      id = "5173",
      title = "Dissolution of Reason",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Paltra Harins",
      loc = nil,
      triggers = {
        "Hail, Paltra Harins",
        "Something?",
        "Constable?",
        "I will find them.",
        "_Quest_",
        "_Quests_",
        "something",
        "constable",
      },
      items_required = {
      },
      rewards = {
        { id = 93034, name = "Fetid Venom", type = "item" },
        { id = 94298, name = "Heart of the Profane", type = "item" },
        { id = 94880, name = "Unknown Blood", type = "item" },
        { id = 94869, name = "Unknown Claw", type = "item" },
        { id = 94879, name = "Unknown Hair", type = "item" },
        { id = 94868, name = "Unknown Scale", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Grounds [zone=749]\n**Who:**\n- Paltra Harins [ _Quest_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 80\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Factions Raised:**\n- Dream Delvers +10\n**Factions Lowered:**\n**Quest Items:**\n- Fetid Venom [item=93034]\n- Heart of the Profane [item=94298]\n- Unknown Blood [item=94880]\n- Unknown Claw [item=94869]\n- Unknown Hair [item=94879]\n- Unknown Scale [item=94868]\n**Related Zones:**\n- House of Thule, Lower Floors [zone=748]\n- House of Thule, Upper Floors [zone=753]\n- The Well [zone=750]\n**Related Creatures:**\n- Alboct Vinn [npc=35796]\n- Constable Erulin [npc=36338]\n- Dtaemi [ _Quests_]\n- Fetid Spider [npc=36125]\n- Granger Rivenbel [npc=36553]\n- Profane Fiend [npc=36312]\n- Vorga the Anathema [npc=37099]\n- Vorga the Killer [npc=37100]\n- first missing bonecrafter [npc=36098]\n- fourth missing bonecrafter [npc=36101]\n- garden bandit [npc=37101]\n- garden hooligan [npc=37102]\n- garden outlaw [npc=37103]\n- second missing bonecrafter [npc=36099]\n- third missing bonecrafter [npc=36100]\n**Related Quests:**\n- Giladan #1: Giladan's Assistant [quest=5157]\n- Giladan #2: What a Mess [quest=5158]\n- Giladan #3: It Only Gets Worse [quest=5159]\n- The Last One [quest=5172]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 2 00:30:11 2010\nModified: Tue Apr 2 21:11:58 2024 | | _This solo task begins with Paltra Harins in the Grounds. She is found in the building in the northeastern part of the zone. Location approximately 400, -2490._\n_You must have completed the other four Partisan solo tasks for The Grounds before you can request this one. (Giladan's three tasks as well as \"The Last One\")_\n_You will be required to have access to Tier 3 zones in order to complete this task. (See this link for progression information.)_\nYou say, 'Hail, Paltra Harins'\nPaltra Harins says 'Greetings traveler. I am hoping you can help me with [something].'\nYou say, 'Something?'\nPaltra Harins says 'It seems we have a number of people missing. And unfortunately, our [constable] is unlikely to find out for himself the whereabouts of our missing bonecrafters.'\nYou say, 'Constable?'\nPaltra Harins says 'His fear keeps him close to home. My only fear is that more of my kinsmen will fall to whatever force is at work here, be it man or monster. Will you [find] our missing compatriots?'\nYou say, 'I will find them.'\nYou have been assigned the task 'Dissolution of Reason'.\nPaltra Harins says 'If you are able to discover the identity of who, or what, is responsible, please put a stop to it... in our name. Be sure to speak to Constable Erulin if you find anything.'\n\n---\n\nFind the 1st missing bonecrafter 0/1 (The Grounds)\nFind the 2nd missing bonecrafter 0/1 (The Grounds)\nFind the 3rd missing bonecrafter 0/1 (The Grounds)\nFind the 4th missing bonecrafter 0/1 (The Grounds)\n_NOTE: For each hail, you will be ambushed by three mobs (\"garden \\_\\_\\_\\_\\_\"), but you don't actually have to kill them as part of the task._\nSpeak to Constable Erulin 0/1 (The Grounds)\nGive Granger Rivenbel the claw you found 0/1 (The Grounds)\nGive Granger Rivenbel the hair you found 0/1 (The Grounds)\nGive Granger Rivenbel the blood you found 0/1 (The Grounds)\nGive Granger Rivenbel the scale you found 0/1 (The Grounds)\nSpeak to Granger Rivenbel 0/1 (The Grounds)\nSpeak to Dtaemi 0/1 (The Well)\nKill the Fetid Spider 0/1 (The Well)\nGive the Fetid Venom to the Granger Rivenbel 0/1 (The Grounds)\nSpeak to Granger Rivenbel 0/1 (The Grounds)\nSpeak to Alboct Vinn 0/1 (House of Thule)\n_Alboct Vinn is a dwarf in the eastern half of the courtyard in the House of Thule's lower floors._\nFind and kill the Profane Fiend 0/1 (House of Thule, Upper Floors)\n_Location for thulehouse2.txt mapfile:_\nP 608.7167, -133.8700, 68.4953, 127, 0, 0, 3, Profane\\_Fiend\n_If going through the halls of the zone's southeastern wing, it's the first door that leads to a dead-end area, on your right._\nLoot the Heart of the Profane 0/1 (House of Thule, Upper Floors)\nTake the Heart of the Profane to the east shore of the lake 0/1 (The Grounds)\n_WARNING: If you have more than one person in your group who's on this step, they should stay far away from the quest NPCs at the lake. If you have multiple people on this task and everyone is at the eastern edge of the lake, all but one person will lose their item and have to repeat the entire task._\nUpdate is very near where Riggbit [npc=35931] spawns, on the east coast of the lake southern half. You might need to remove Levitate.\nSpeak to Vorga the Anathema 0/1 (The Grounds)\n_Hail Vorga and say \"trickery\" to him to spawn a KOS \"Vorga the Killer\"._\nKill Vorga the Anathema 0/1 (The Grounds)\nSpeak to Paltra Harins 0/1 (The Grounds)\n_Rewards:_\n210 platinum\nExperience (about 2.5 AAs)\nFaction\n13 Dream Motes\n- Dream Mote [item=90255]",
    },
    {
      id = "5190",
      title = "What Lies Below",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Groundskeeper Seamus",
      loc = nil,
      triggers = {
        "Hail, Groundskeeper Seamus",
        "Back?",
        "The well?",
        "What",
        "Unusual water?",
        "Dry?",
        "Hunger?",
        "What do you feed it?",
      },
      items_required = {
        { name = "up his dynamite without a fight", count = 1 },
      },
      rewards = {
        { id = 93258, name = "Bundle of Dynamite", type = "item" },
        { id = 93480, name = "Edgar's Backpack", type = "item" },
        { id = 91898, name = "Pile of Rubble", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Grounds [zone=749]\n**Who:**\n- Groundskeeper Seamus [npc=36097]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Loot\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 06:00:00\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Quest Items:**\n- Bundle of Dynamite [item=93258]\n- Edgar's Backpack [item=93480]\n- Pile of Rubble [item=91898]\n**Related Zones:**\n- The Well: What Lies Below [zone=769]\n**Related Creatures:**\n- Edgar Steelmor [npc=36573]\n- Foreman Dreck [npc=36574]\n- Zurlak the Soul Leech [npc=36563]\n- an ornate chest - What Lies Below [npc=36562]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 3 21:14:28 2010\nModified: Sun Sep 15 21:10:55 2024 | | This is a non-progression group mission (3-6 players) that begins with Groundskeeper Seamus just outside the Well in the southern part of the Grounds.\n_There are no pre-requisites for requesting this task._\n_Note: Unlike the other group mission for the Well, this task is of Tier 3 difficulty._\nYou say, 'Hail, Groundskeeper Seamus'\nGroundskeeper Seamus says 'What are you doing snooping about in the garden? Your fingernails are far too clean to be a groundskeeper! If you had any sense about you, stranger, you'd scurry [back] to wherever it is that you came from.'\nYou say, 'Back?'\nGroundskeeper Seamus says 'Yes, go back. Run home, shoo! Do I need to spell it out for you? This place is much too dangerous for someone who looks as delicate as you. If you are so eager to meet your demise, then please, by all means, stick around. Just heed one bit of advice... Show extra caution around the [well]'s edge; it's a long way down.'\nYou say, 'The well?'\nGroundskeeper Seamus says 'This well dug itself for the most part, starting as a circular patch of land that radiated life. The soil was so moist and light that it appeared to float above the earth, until one day the fertile mound collapsed upon itself, creating what seemed to be an endless [hole].'\nYou say, 'What's this about an endless hole?'\nGroundskeeper Seamus says 'While the core of the hole continued to erode deeper into the earth, the area near its surface flourished, thanks to the unusual [water] from the natural well. The beautiful life that blossomed was the stuff of dreams. So much so, that those who came to linger near the fragrant flowers that encircled the well often fell into a euphoric slumber.'\nYou say, 'Unusual water?'\nGroundskeeper Seamus says 'Of course like most wells, the garden's life source couldn't sustain itself forever. It wasn't long before the well ran [dry], and the land surrounding it cried out in hunger. While most would assume water to be nourishing, what was secreted from the well was anything but.'\nYou say, 'Dry?'\nGroundskeeper Seamus says 'Like any good predator, the well used its enchanted water to lure life to its mouth. Those that lingered around the well were too concerned with bliss to notice its insatiable [hunger]. Completely dependant on the well, many sought to expand it, sending diggers into the hole in an effort to strike that precious vein of water again.'\nYou say, 'Hunger?'\nGroundskeeper Seamus says 'Of course the diggers haven't had any luck, and the well remains dry. They are too blinded by their quest for bliss to understand the true essence of the well. They should be happy that someone as knowledgeable as me knows what the well needs; what it hungers for. As long as I am here to [feed] the well, a trickle of water still remains.'\nYou say, 'What do you feed it?'\nGroundskeeper Seamus says 'Do you really want to know what I feed the well? Come close and I will whisper it to you. After all, it's a little known secret... that the well feeds off of [souls]!'\nYou have been assigned the task 'What Lies Below'.\nYou say, 'Souls...?'\nGroundskeeper Seamus gives you a hostile shove, offsetting your balance. 'What souls you ask? Why the souls of unsuspecting travelers like you!' The trail of Groundskeeper Seamus' laughter can be heard as you tumble down the well.\nLOADING, PLEASE WAIT...\nYou have entered The Well.\n\n---\n\n_All mobs in the zone are immune to mez and root/snare. Scorpions and nameds see invisibility (there's also a mix of live and undead)._\nDiscover the source of the cries 0/1 (The Well)\nContinue to investigate the source of the cries 0/1 (The Well)\nThe cries fill with agony as they grow louder, 'Is anyone still alive out there? Help me... please!'\n_These steps update as you proceed through the tunnel to the south of the zone-in._\nSpeak to Edgar Steelmor 0/1 (The Well)\n_In the first cavern, you'll find Edgar Steelmor who's surrounded by several scorpions._\nYou say, 'Hail, Edgar Steelmor'\nEdgar Steelmor strains to talk, but through the pain his voice is hardly louder than a whisper. 'I...I haven't much time. The...scorpion's sting, it's... it's making my limbs numb. Antidote... in my pack, but it was lost in the mud. Please ...help. I will tell you everything.'\nFind Edgar's backpack and return it to him 0/1 (The Well)\n_Edgar's Backpack can be found in the mud area. It's in the room with the mud pool (same room as the Lower Denizen in the \"No Freedom in Death\" task. Pick it up and deliver it to Edgar._\nSpeak to Edgar Steelmor 0/1 (The Well)\nYou say, 'Hail, Edgar Steelmor'\nEdgar Steelmor says 'You're a sight for my weary eyes. It's been longer than I can remember since I've seen a face so vibrant and full of life. I came down here with my digging crew ages ago; our foreman was determined to see the well restored. As countless days went on, our strained efforts proved fruitless. Many diggers began to grow pale. Some thought it was due to a loss of spirit, but I wasn't as convinced. The well seemed to be sucking the life right out of them! So I went to [Foreman] Dreck with my concerns.'\nYou say, 'Foreman Dreck?'\nEdgar Steelmor says 'Blinded by his desperation to find water, Dreck ignored my pleads to return to the surface. Instead, he banished me from camp, tossing me into the pit here with spiders, scorpions, and a myriad of other creatures who'd love to have me for dinner. I've been searching for a way [out] ever since. Death seems a better fate than spending an eternity as a soulless digger, picking away at the well's walls.'\nYou say, 'A way out?'\nEdgar Steelmor says 'I've located a weak spot on the wall. It's a little out of my reach, but I imagine with all the loose rubble around here I can create a something sturdy enough to climb on. My supply is limited, and I'll need your help collecting more loose stones. It's not an easy task, but it's our best bet at getting out of here alive.'\nCollect 8 piles of rubble and deliver them to Edgar 0/1 (The Well)\n_Piles of Rubble can be found as groundspawns throughout the area. They appear as rocks on the ground. Collect eight of them and hand them to Edgar._\nSpeak to Edgar Steelmor 0/1 (The Well)\nYou say, 'Hail, Edgar Steelmor'\nEdgar Steelmor says 'This should be plenty, but I fear upon further inspection that the wall can't be breeched with my basic mining tools. It's going to take a large blast to create a hole large enough for us to escape. I know of only one person with those kinds of explosives... Foreman Dreck. He won't give up his dynamite without a fight.'\nDefeat Foreman Dreck 0/1 (The Well)\n_Foreman Dreck spawns a distance away. He hits for a max ~6,500 and has about 840,000 hitpoints._\nForeman Dreck has been slain by \\_\\_\\_\\_\\_!\nForeman Dreck's corpse collapses.\nLoot a Bundle of Dynamite 0/1 (The Well)\nSpeak to Edgar Steelmor 0/1 (The Well)\nYou say, 'Hail, Edgar Steelmor'\nEdgar Steelmor says 'I take it you didn't have any trouble snagging the dynamite... I stacked the rubble you brought me into a fairly sturdy pile. If you climb to the top you should be close enough to the weak spot in the wall to light the dynamite and blast a hole.'\nUse the dynamite near the weak part of the wall 0/1 (The Well)\n_Right-click the dynamite in the area southwest of Edgar (towards the wall). This will open up a tunnel._\nSearch the tunnel for a way out 0/1 (The Well)\nAn icy chill blows through the tunnel as the resting place of Zurlak the Soul Leech is disturbed.\nZurlak the Soul Leech scurries toward you, ready to kill.\nDefeat Zurlak the Soul Leech 0/1 (The Well)\n_Task Window Says:_ You have uncovered the creature that's sucking life from within the well. Destroy it before it consumes you!\n_At the end of the tunnel is an insanity mob. It hits for a max ~8,000; has about 1 million hitpoints; and casts the spell \"Soul Siphon\":_\nSoul Siphon: PB AE 200', Disease (-700)\n1: Decrease Hitpoints by 3000 per tick\n2: Decrease Mana by 2000 per tick\n3: Improved Spell Effect (Barren Soul)\n4: Increase Disease Counter by 30\nZurlak the Soul Leech has been slain by \\_\\_\\_\\_\\_!\nZurlak the Soul Leech's corpse collapses.\nSpeak to Edgar Steelmor 0/1 (The Well)\nYou say, 'Hail, Edgar Steelmor'\nEdgar Steelmor says 'Hey, you're still here! It's a good thing, too. You wouldn't believe what I found! When you set off those explosives, beneath all the rubble I uncovered this ornate chest. Funny enough, there was a gate potion inside! I didn't bother with the rest of the treasure though. Just let me keep the potion, and you can have what's left.'\nClaim your reward from the ornate chest 0/1 (The Well)\n\n---\n\n_Task rewards:_\n315 platinum\nExperience (~4.1 AA at level 90)\nFaction with Dream Delvers\n40 Dream Motes\n_Known chest rewards [npc=36562] (1 item + 1 spell per task):_\nChilling Short Staff\nFireflash Chain Wrist Bands\nJyleel's Seal\nMurderer's Knife\nPlaugebone's Sigil [sic]\nQueen's Horn\nRing of the Eyes\nSabre of Icy Retribution\nStone of Insanity\nWarder's Eye\nMinor Nebulous Dream Fragment\nLesser Nebulous Dream Fragment\nMedian Nebulous Dream Fragment\nGreater Nebulous Dream Fragment\nGlowing Nebulous Dream Fragment\n- Dream Mote [item=90255]",
    },
  },
}
