-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Windsong Sanctuary (kael)
-- Total Quests: 14
-- ============================================================================

return {
  zone = "kael",
  zone_name = "Windsong Sanctuary",
  quests = {
    {
      id = "5505",
      title = "The Sound of Silence",
      exp = "18",
      exp_name = "Veil of Alaris",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Gibbledon Cogboggle",
      loc = nil,
      triggers = {
        "Hail, Gibbledon Cogboggle",
        "Ready to test it!",
        "Let",
        "ready to test",
        "begin",
        "leave",
      },
      items_required = {
      },
      rewards = {
        { id = 101310, name = "Harmonic Disruptor", type = "item" },
        { id = 101314, name = "Harmonic Disruptor", type = "item" },
        { id = 101313, name = "Harmonic Disruptor", type = "item" },
        { id = 101311, name = "Harmonic Disruptor", type = "item" },
        { id = 101312, name = "Harmonic Disruptor", type = "item" },
        { id = 101315, name = "Harmonic Disruptor", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Windsong Sanctuary [zone=813]\n**Who:**\n- Gibbledon Cogboggle [ _Quests, Mission_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Alaran Language:** | 81\n**Quest Goal:**\n- Advancement\n- Experience\n- Loot\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 06:00:00\n**Quest Items:**\n- Harmonic Disruptor [item=101310]\n- Harmonic Disruptor [item=101314]\n- Harmonic Disruptor [item=101313]\n- Harmonic Disruptor [item=101311]\n- Harmonic Disruptor [item=101312]\n- Harmonic Disruptor [item=101315]\n- Harmonic Disruptor [item=101278]\n- Harmonic Disruptor [item=101309]\n**Related Zones:**\n- Windsong Sanctuary: The Sound of Silence [zone=835]\n**Related Creatures:**\n- Gibbledon Cogboggle [npc=39968]\n- High Priest Aldior [npc=39455]\n- a deactivated sentry stone [npc=39970]\n- a flowing wind elemental [npc=39981]\n- a musical spirit [npc=39983]\n- a muted brute [npc=39982]\n- a treasure chest - The Sound of Silence [npc=39454]\n- an active sentry stone [npc=39969]\n- an unspeaking sentinel [npc=39971]\n**Related Quests:**\n- The Cacophony of Power [quest=5506]\n- Windsong #1: Stranger in a Strange Land [quest=5499]\n- Windsong #2: Getting Down to Business [quest=5500]\n- Windsong #3: Making Music [quest=5501]\n**Era:** | !Veil of Alaris\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Dec 1 22:43:15 2011\nModified: Tue Dec 5 05:21:04 2023 | | **Veil of Alaris Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This group mission begins with Gibbledon Cogboggle in Windsong Sanctuary, located at about 20, -185, -32 (due west of the zone-in -- the southern entrance to the inner grassy area)._\n_Pre-requisites for requesting the task:_\n\\- Completion of \"Stranger in a Strange Land\"\n\\- Completion of \"Getting Down to Business\"\n\\- Completion of \"Making Music\"\n\\- 81 Skill Level in Alaran\nYou say, 'Hail, Gibbledon Cogboggle'\nGibbledon Cogboggle says 'The harmonic disruptor is complete! It is time to test it out. There is a little problem though. Somehow the Alarans have learned of our plans to test out the disruptor and have been preparing for our attack. I'm sure that won't be a problem for someone like you though! Are you [ready to test] the disruptor?'\nYou say, 'Ready to test it!'\nGibbledon Cogboggle says 'Ok, it looks like we are all set. When you are ready to [begin], just let me know.'\nYou have been assigned the task 'The Sound of Silence'.\nThe Harmonic Disruptor has been completed and Gibbledon wants you to use it to launch an attack on the Alarans in Windsong. The Alarans are aware of your plans, however, and are ready for your attack.\nYou say, 'Let's begin'\nGibbledon Cogboggle says 'See you on the other side!'\nLOADING, PLEASE WAIT...\nYou have entered Windsong Sanctuary.\n\n---\n\nSpeak with Gibbledon Cogboggle 0/1 (Windsong Sanctuary)\n_Whoever hails Gibbledon receives a \"Harmonic Disruptor\"._\nYou say, 'Hail, Gibbledon Cogboggle'\nGibbledon Cogboggle says 'The Alarans have set up numerous sentry stones that are generating a magical barrier preventing entry to the inner section of the temple. You must use the harmonic disruptor on the sentry stones to lower the magical barrier. Each sentry stone is tuned to listen to a particular note from an instrument. After each use of the disruptor, return it to me so that I can properly tune it to disable the next sentry stone. If you feel you are not up to handling this however, just let me know and I will help you [leave].'\n_The next 16 steps open up one at a time. Whoever has the Harmonic Disruptor will right-click the first sentry stone, bring the disruptor back to Gibbledon, then go right-click the second sentry stone, bring it back to Gibbledon, etc., until all eight sentry stones have been clicked._\n_If you try to enter the very center, you'll see this emote and be knocked back:_\nA barrier prevents you from entering!\n_The eight \"an active sentry stone\" are found surrounding the very center of the zone. You have to stand right under the stone for the click to take effect._\n_If you click the wrong one, you'll see:_\nYou are not near the correct sentry stone!\n_If you click the right one, you'll see:_\nThe harmonic disruptor has deactivated the sentry stone controlling the barrier to the inner section of the temple!\n_You'll then bring it back to Gibbledon for a tuning:_\nGibbledon Cogboggle quickly tunes the harmonic disruptor and then hands it back to you.\n_NOTE: After you do the first tuning with Gibbledon, golems called \"an unspeaking sentinel\" (hit for a max ~12,500) spawn all around the center area. The further you progress in the task, the more golems you'll see appearing. Killing them has no bearing on the task (although there are achievements for leaving them all alive as well as killing them all)._\n_Once you right-click a correct active sentry stone, it turns into \"a deactivated sentry stone\"._\nUse the harmonic disruptor on the first active sentry stone 0/1 (Windsong Sanctuary)\nReturn the harmonic disruptor to Gibbledon so that he can tune it 0/1 (Windsong Sanctuary)\nUse the harmonic disruptor on the second active sentry stone 0/1 (Windsong Sanctuary)\nReturn the harmonic disruptor to Gibbledon so that he can tune it 0/1 (Windsong Sanctuary)\nUse the harmonic disruptor on the third active sentry stone 0/1 (Windsong Sanctuary)\nReturn the harmonic disruptor to Gibbledon so that he can tune it 0/1 (Windsong Sanctuary)\nUse the harmonic disruptor on the fourth active sentry stone 0/1 (Windsong Sanctuary)\nReturn the harmonic disruptor to Gibbledon so that he can tune it 0/1 (Windsong Sanctuary)\nUse the harmonic disruptor on the fifth active sentry stone 0/1 (Windsong Sanctuary)\nReturn the harmonic disruptor to Gibbledon so that he can tune it 0/1 (Windsong Sanctuary)\nUse the harmonic disruptor on the sixth active sentry stone 0/1 (Windsong Sanctuary)\nReturn the harmonic disruptor to Gibbledon so that he can tune it 0/1 (Windsong Sanctuary)\nUse the harmonic disruptor on the seventh active sentry stone 0/1 (Windsong Sanctuary)\nReturn the harmonic disruptor to Gibbledon so that he can tune it 0/1 (Windsong Sanctuary)\nUse the harmonic disruptor on the eighth active sentry stone 0/1 (Windsong Sanctuary)\nReturn the harmonic disruptor to Gibbledon so that he can tune it 0/1 (Windsong Sanctuary)\nGibbledon Cogboggle says 'All of the teleport auras that were blocking the way into the inner area of the temple should be disabled now. Unfortunately, a High Priest has appeared. Looks like you will need to take them out. Good luck!'\n_Upon the final turn-in, the center area spawns full of mobs: 1x \"High Priest Aldior\" and several \"a silentsong worshipper\" in his audience. Clear the area of mobs and then fight the High Priest._\nDefeat High Priest Aldior 0/1 (Windsong Sanctuary)\n_Aldior hits for a max ~18,000 and spawns adds at 75% (3x \"a musical spirit\"), 50% (3x \"a muted brute\"), and 25% (3x \"a flowing wind elemental\"):_\nHigh Priest Aldior says, in Alaran, 'Denizens of Windsong! Come to my aid!'\n_These adds are regular trash mobs (they are not weakened) and do NOT despawn upon his death._\nSpeak with Gibbledon Cogboggle 0/1 (Windsong Sanctuary)\nYou say, 'Hail, Gibbledon Cogboggle'\nGibbledon Cogboggle noisily munches on a pickle. 'Oh, you took care of that priest? Nice job. The harmonic disruptor successfully interfered with the sentry stones and allowed you access to the inner sanctum of the temple and one of the high priests, just as I knew it would! Well, my job here is done, and I suppose you are ready to [leave]. Don't forget to loot the chest for your reward before you leave!'\nLoot the treasure chest for your reward 0/1 (Windsong Sanctuary)\n_Rewards:_\n375 platinum\nEltarki's Diary - Music of the Mind\nPossible Chest Loot (1 Item + 1 Cantrip + 0-1 Valiant Ornament per task)\nBrilliant Band of Arcane Knowledge\nCoin of Weight Balancing\nDeepblade's Longshield\nEarring of Soothing Melodies\nGlowing Eyes of the Wind\nGraven Grave-Glaive\nPendant of Compelling Song\nShaded Orb of Infusion\nTendros' Healing-Stick\nWavecrasher's Raw-Hide Belt\nGreater Alaran Cantrip\nGlowing Alaran Cantrip\n- Eltarki's Diary - Music of the Mind [item=99795]",
    },
    {
      id = "8284",
      title = "Bard Kael Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Bygloirn Omorden",
      loc = nil,
      triggers = {
        "Hail, Bygloirn Omorden",
        "I am a bard",
        "I seek a new outfit",
        "bracer",
        "boots",
        "armplates",
        "gauntlets",
        "helm",
      },
      items_required = {
      },
      rewards = {
        { id = 5101, name = "Troubadour's Boots", type = "item" },
        { id = 5176, name = "Troubadour's Bracer", type = "item" },
        { id = 6223, name = "Troubadour's Breastplate", type = "item" },
        { id = 5318, name = "Troubadour's Gauntlets", type = "item" },
        { id = 5150, name = "Troubadour's Greaves", type = "item" },
        { id = 6222, name = "Troubadour's Helm", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nBygloirn Omorden in the quest room behind King Tormax's throneroom offers a series of quests for bards to obtain a set of Troubadour's Armor. He is by the banker\nYou must be at least ALLY with Kromzek in order to complete these quests.\nYou say, 'Hail, Bygloirn Omorden'\nBygloirn Omorden says, 'Hail! I long to speak with a minstrel. I am curious about what has gone on beyond our borders here. Are you a bard? If not then I have no use for you.'\nYou say, 'I am a bard'\nBygloirn Omorden says, 'So troubadour, what news and stories have you from the New World? Oh, I forget my manners. We shall exchange talk another time. You seek something do you not? A new outfit perhaps?'\nYou say, 'I seek a new outfit'\nBygloirn Omorden says, 'Well then, I have just what you need. Now, my terms of payment is thus, you gather some things for me and in return I shall craft you the finest armor a bard has ever seen! A new outfit comprised of a helm, breastplate, armplates, bracers, gauntlets, greaves, and boots shall make you the envy of your peers, my little friend.'\nAncient Tarnished Armor molds drop from zone trash throughout Temple of Veeshan with the exception of Halls of Testing(the east wing). Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Flame Emerald + Ancient Tarnished Plate Bracelet\nBoots  - 3x Crushed Black Marble + Ancient Tarnished Plate Boots\nArms - 3x Flawed Emerald + Ancient Tarnished Vambraces\nGloves - 3x Crushed Topaz + Ancient Tarnished Plate Gauntlets\nHelm - 3x Crushed Coral + Ancient Tarnished Plate Helmet\nLegs - 3x Flawed Sea Sapphire + Ancient Tarnished Greaves\nChest - 3x Flawless Diamond + Ancient Tarnished Breastplate\nBracer\nYou say, 'bracer'\nBygloirn Omorden says 'A pair of bracers shall be yours upon receipt of an ancient tarnished plate bracer and three crushed flame emeralds. May your songs never falter during a tactical retreat.\nGive Bygloirn 3x Crushed Flame Emerald and a Ancient Tarnished Plate Bracelet\nBygloirn Omorden smiles warmly as he hands you your reward.\nBygloirn Omorden says 'You have done well.'\nYou receive: Troubadour's Bracers\nBoots\nYou say, 'boots'\nBygloirn Omorden says 'A fancy pair of boots you want is it? Yes, I can see the pair you have now looks a bit worn from running so much. All I require is a set of three crushed pieces of black marble and a pair of ancient tarnished plate boots.'\nGive Bygloirn 3x Crushed Black Marble and an Ancient Tarnished Plate Boots\nBygloirn Omorden smiles warmly as he hands you your reward.\nBygloirn Omorden says 'You have done well.'\nYou receive: Troubadour's Boots\nArms\nYou say, 'armplates'\nBygloirn Omorden says 'A gorgeous pair of armplates shall be yours once you have retrieved a pair of ancient tarnished plate vambraces and three flawed emeralds. The detail and craftsmanship is stunning!'\nGive Bygloirn 3x Flawed Emerald and an Ancient Tarnished Plate Vambraces\nBygloirn Omorden smiles warmly as he hands you your reward.\nBygloirn Omorden says 'You have done well.'\nYou receive: Troubadour's Vambraces\nGloves\nYou say, 'gauntlets'\nBygloirn Omorden says 'It would be a shame if your hands were to be injured and not be able to play your instruments wouldn't it? I shall craft some gauntlets so that your nimble digits remain intact. Bring me a pair of ancient tarnished plate gauntlets as well as three crushed topaz.'\nGive Bygloirn 3x Crushed Topaz and an Ancient Tarnished Plate Gauntlets\nBygloirn Omorden smiles warmly as he hands you your reward.\nBygloirn Omorden says 'You have done well.'\nYou receive: Troubadour's Gauntlets\nHelm\nYou say, 'helm'\nBygloirn Omorden says 'A brand new shiny helm shall be yours once I have an ancient tarnished plate helmet and three pieces of crushed coral. May the audience swoon in your presence.'\nGive Bygloirn 3x Crushed Coral and a Ancient Tarnished Plate Helmet\nBygloirn Omorden smiles warmly as he hands you your reward.\nBygloirn Omorden says 'You have done well.'\nYou receive: Troubadour's Helm\nLegs\nYou say, 'greaves'\nBygloirn Omorden says 'Some new greaves would do you some good. The pair you have now looks quite stained and worn. Nevermind, fetch me a pair of ancient tarnished plate greaves and three flawed sea sapphires.'\nGive Bygloirn 3x Flawed Sea Sapphire and an Ancient Tarnished Plate Greaves\nBygloirn Omorden smiles warmly as he hands you your reward.\nBygloirn Omorden says 'You have done well.'\nYou receive: Troubadour's Greaves\nChest\nYou say, 'breastplate'\nBygloirn Omorden says 'I have need of an ancient tarnished breastplate and three flawless diamonds. Find these for me and I shall craft you a breastplate, minstrel. May it protect you from unruly audiences with rotten vegetables.'\nGive Bygloirn 3x Flawless Diamond and a Ancient Tarnished Breastplate\nBygloirn Omorden smiles warmly as he hands you your reward.\nBygloirn Omorden says 'You have done well.'\nYou receive: Troubadour's Breastplate\nSubmitted by: BobbybickRewards:\n- Troubadour's Boots [item=5101]\n- Troubadour's Bracer [item=5176]\n- Troubadour's Breastplate [item=6223]\n- Troubadour's Gauntlets [item=5318]\n- Troubadour's Greaves [item=5150]\n- Troubadour's Helm [item=6222]\n- Troubadour's Vambraces [item=5125]\n[",
    },
    {
      id = "8285",
      title = "Magician Kael Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "King Tormax",
      loc = nil,
      triggers = {
        "Hail, Mjeldor Felstorm",
        "I am a magician",
        "wristband",
        "boots",
        "sleeves",
        "gloves",
        "cap",
        "leggings",
      },
      items_required = {
        { name = "Mjeldor 3x Nephrite and a Ancient Silk Pantaloons", count = 1 },
      },
      rewards = {
        { id = 5720, name = "Summoner's Boots", type = "item" },
        { id = 5887, name = "Summoner's Circlet", type = "item" },
        { id = 6390, name = "Summoner's Gloves", type = "item" },
        { id = 5877, name = "Summoner's Pantaloons", type = "item" },
        { id = 5719, name = "Summoner's Robe", type = "item" },
        { id = 5931, name = "Summoner's Sleeves", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nMjeldor Felstorm in the quest room behind King Tormax's throneroom offers a series of quests for magicians to obtain a set of Summoner's Armor.\nYou must be at least ALLY with Kromzek in order to complete these quests.\nYou say, 'Hail, Mjeldor Felstorm'\nMjeldor Felstorm says 'Greetings to you.  I seek those who call themselves magicians.  Are you a magician, little one?'\nYou say, 'I am a magician'\nMjeldor Felstorm says 'I thought so.  I have several tasks for you to accomplish.  Once you have completed them I will have a cap, a robe, sleeves, wristbands, gloves, leggings and boots to reward you with.'\nAncient Silk Armor molds drop from zone trash throughout Temple of Veeshan with the exception of Halls of Testing(the east wing). Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Onyx Sapphire + Ancient Silk Wristband\nBoots  - 3x Crushed Jaundice Gem + Ancient Silk Boots\nArms - 3x Flawed Topaz + Ancient Silk Sleeves\nGloves - 3x Crushed Topaz + Ancient Silk Gloves\nHelm - 3x Crushed Flame Opal + Ancient Silk Turban\nLegs - 3x Nephrite + Ancient Silk Pantaloons\nChest - 3x Pristine Emerald + Ancient Silk Robe\nBracer\nYou say, 'wristband'\nMjeldor Felstorm says 'The crafting of this wristband requires that you bring me an ancient silk wristband and three crushed onyx sapphire pieces.'\nGive Mjeldor 3x Crushed Onyx Sapphire and a Ancient Silk Wristband\nMjeldor Felstorm smiles warmly as he hands you your reward.\nMjeldor Felstorm says 'You have done well.'\nYou receive: Summoner's Warband\nBoots\nYou say, 'boots'\nMjeldor Felstorm says 'These supple boots shall be yours upon receipt of a pair of ancient silk boots and three crushed jaundice gems.'\nGive Mjeldor 3x Crushed Jaundice Gem and a Ancient Silk Boots\nMjeldor Felstorm smiles warmly as he hands you your reward.\nMjeldor Felstorm says 'You have done well.'\nYou receive: Summoner's Boots\nArms\nYou say, 'sleeves'\nMjeldor Felstorm says 'For these durable sleeves, you must fetch me a pair of ancient silk sleeves and three flawed topaz.'\nGive Mjeldor 3x Flawed Topaz and a Ancient Silk Sleeves\nMjeldor Felstorm smiles warmly as he hands you your reward.\nMjeldor Felstorm says 'You have done well.'\nYou receive: Summoner's Sleeves\nGloves\nYou say, 'gloves'\nMjeldor Felstorm says 'For this fine pair of gloves you must seek out and return to me a pair of ancient silk gloves and three crushed topaz.'\nGive Mjeldor 3x Crushed Topaz and a Ancient Silk Gloves\nMjeldor Felstorm smiles warmly as he hands you your reward.\nMjeldor Felstorm says 'You have done well.'\nYou receive: Summoner's Gloves\nHelm\nYou say, ' cap'\nMjeldor Felstorm says 'For you to receive my gift, I shall require an ancient silk turban and three crushed flame opals.'\nGive Mjeldor 3x Crushed Flame Opal and an Ancient Silk Turban\nMjeldor Felstorm smiles warmly as he hands you your reward.\nMjeldor Felstorm says 'You have done well.'\nYou receive: Summoner's Circlet\nLegs\nYou say, 'leggings'\nMjeldor Felstorm says 'This pair of leggings will yours provided you supply me with a pair of ancient silk pantaloons as well as three nephrites.'\nGive Mjeldor 3x Nephrite and a Ancient Silk Pantaloons\nMjeldor Felstorm smiles warmly as he hands you your reward.\nMjeldor Felstorm says 'You have done well.'\nYou receive: Summoner's Pantaloons\nChest\nYou say, 'robe'\nMjeldor Felstorm says 'This exquisite robe shall be yours in exchange for an ancient silk robe and three pristine emeralds.'\nGive Mjeldor 3x Pristine Emerald and a Ancient Silk Robe\nMjeldor Felstorm smiles warmly as he hands you your reward.\nMjeldor Felstorm says 'You have done well.'\nYou receive: Summoner's Robe\nSubmitted by: BobbybickRewards:\n- Summoner's Boots [item=5720]\n- Summoner's Circlet [item=5887]\n- Summoner's Gloves [item=6390]\n- Summoner's Pantaloons [item=5877]\n- Summoner's Robe [item=5719]\n- Summoner's Sleeves [item=5931]\n- Summoner's Warband [item=5718]\n[",
    },
    {
      id = "8286",
      title = "Enchanter Kael Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = false,
      group_size = "Solo",
      npc = "King Tormax",
      loc = nil,
      triggers = {
        "Hail, Stoem Lekbar",
        "I am an enchanter",
        "wristband",
        "boots",
        "sleeves",
        "gloves",
        "cap",
        "leggings",
      },
      items_required = {
        { name = "Stoem 3x Flawed Topaz and a Ancient Silk Sleeves", count = 1 },
        { name = "Stoem 3x Crushed Topaz and a Ancient Silk Gloves", count = 1 },
        { name = "Stoem 3x Nephrite and a Ancient Silk Pantaloons", count = 1 },
        { name = "Stoem 3x Pristine Emerald and a Ancient Silk Robe", count = 1 },
      },
      rewards = {
        { id = 5003, name = "Dazzling Circlet", type = "item" },
        { id = 4668, name = "Dazzling Gloves", type = "item" },
        { id = 5078, name = "Dazzling Robe", type = "item" },
        { id = 5269, name = "Dazzling Sleeves", type = "item" },
        { id = 5004, name = "Dazzling Slippers", type = "item" },
        { id = 5013, name = "Dazzling Trousers", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nStoem Lekbar in the quest room behind King Tormax's throneroom offers a series of quests for enchanters to obtain a set of Dazzling Armor.\nYou must be at least ALLY with Kromzek in order to complete these quests.\nYou say, 'Hail, Stoem Lekbar'\nStoem Lekbar says 'Greetings to you. I seek those who call themselves enchanters. Are you an enchanter?'\nYou say, 'I am an enchanter'\nStoem Lekbar says 'I thought so.  I have several tasks for you to accomplish.  Once you have completed them I will have a cap, a robe, sleeves, wristbands, gloves, leggings and boots to reward you with.'\nAncient Silk Armor molds drop from zone trash throughout Temple of Veeshan with the exception of Halls of Testing(the east wing). Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Onyx Sapphire + Ancient Silk Wristband\nBoots  - 3x Crushed Jaundice Gem + Ancient Silk Boots\nArms - 3x Flawed Topaz + Ancient Silk Sleeves\nGloves - 3x Crushed Topaz + Ancient Silk Gloves\nHelm - 3x Crushed Flame Opal + Ancient Silk Turban\nLegs - 3x Nephrite + Ancient Silk Pantaloons\nChest - 3x Pristine Emerald + Ancient Silk Robe\nBracer\nYou say, 'wristband'\nStoem Lekbar says 'The crafting of this wristband requires that you bring me an ancient silk wristband and three crushed onyx sapphire pieces.'\nGive Stoem 3x Crushed Onyx Sapphire and a Ancient Silk Wristband\nStoem Lekbar smiles warmly as he hands you your reward.\nStoem Lekbar says 'You have done well.'\nYou receive: Dazzling Wristguard\nBoots\nYou say, 'boots'\nStoem Lekbar says 'These supple boots shall be yours upon receipt of a pair of ancient silk boots and three crushed jaundice gems.'\nGive Stoem 3x Crushed Jaundice Gem and a Ancient Silk Boots\nStoem Lekbar smiles warmly as he hands you your reward.\nStoem Lekbar says 'You have done well.'\nYou receive: Dazzling Slippers\nArms\nYou say, 'sleeves'\nStoem Lekbar says 'For these durable sleeves, you must fetch me a pair of ancient silk sleeves and three flawed topaz.'\nGive Stoem 3x Flawed Topaz and a Ancient Silk Sleeves\nStoem Lekbar smiles warmly as he hands you your reward.\nStoem Lekbar says 'You have done well.'\nYou receive: Dazzling Sleeves\nGloves\nYou say, 'gloves'\nStoem Lekbar says 'For this fine pair of gloves you must seek out and return to me a pair of ancient silk gloves and three crushed topaz.'\nGive Stoem 3x Crushed Topaz and a Ancient Silk Gloves\nStoem Lekbar smiles warmly as he hands you your reward.\nStoem Lekbar says 'You have done well.'\nYou receive: Dazzling Gloves\nHelm\nYou say, ' cap'\nStoem Lekbar says 'For you to receive my gift, I shall require an ancient silk turban and three crushed flame opals.'\nGive Stoem 3x Crushed Flame Opal and an Ancient Silk Turban\nStoem Lekbar smiles warmly as he hands you your reward.\nStoem Lekbar says 'You have done well.'\nYou receive: Dazzling Circlet\nLegs\nYou say, 'leggings'\nStoem Lekbar says 'This pair of leggings will yours provided you supply me with a pair of ancient silk pantaloons as well as three nephrites.'\nGive Stoem 3x Nephrite and a Ancient Silk Pantaloons\nStoem Lekbar smiles warmly as he hands you your reward.\nStoem Lekbar says 'You have done well.'\nYou receive: Dazzling Trousers\nChest\nYou say, 'robe'\nStoem Lekbar says 'This exquisite robe shall be yours in exchange for an ancient silk robe and three pristine emeralds.'\nGive Stoem 3x Pristine Emerald and a Ancient Silk Robe\nStoem Lekbar smiles warmly as he hands you your reward.\nStoem Lekbar says 'You have done well.'\nYou receive: Dazzling Robe\nSubmitted by: BobbybickRewards:\n- Dazzling Circlet [item=5003]\n- Dazzling Gloves [item=4668]\n- Dazzling Robe [item=5078]\n- Dazzling Sleeves [item=5269]\n- Dazzling Slippers [item=5004]\n- Dazzling Trousers [item=5013]\n- Dazzling Wristguard [item=5131]\n[",
    },
    {
      id = "8288",
      title = "Necromancer Kael Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Bjarorm Mjlorn",
      loc = nil,
      triggers = {
        "Hail, Bjarorm Mjlorn",
        "I am a necromancer",
        "I will undertake your tasks",
        "wristband",
        "boots",
        "sleeves",
        "gloves",
        "cap",
      },
      items_required = {
        { name = "Bjarorm 3x Nephrite and a Ancient Silk Pantaloons", count = 1 },
      },
      rewards = {
        { id = 5122, name = "Plague Bearer's Boots", type = "item" },
        { id = 5515, name = "Plague Bearer's Circlet", type = "item" },
        { id = 4881, name = "Plague Bearer's Gloves", type = "item" },
        { id = 5236, name = "Plague Bearer's Robe", type = "item" },
        { id = 5805, name = "Plague Bearer's Sleeves", type = "item" },
        { id = 6417, name = "Plague Bearer's Trousers", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nBjarorm Mjlorn in the quest room behind King Tormax's throneroom offers a series of quests for necromancers to obtain a set of Plague Bearer's Armor.\nYou must be at least ALLY with Kromzek in order to complete these quests.\nYou say, 'Hail, Bjarorm Mjlorn'\nBjarorm Mjlorn eyes you malevolently.\nBjarorm Mjlorn says 'I seek those who practice the dark magicks. I seek those who call themselves necromancers. Are you a necromancer?'\nYou say, 'I am a necromancer'\nBjarorm Mjlorn says 'Excellent. Are you sure enough of your skills to undertake my tasks? If not, get out of my sight, weakling!'\nYou say, 'I will undertake your tasks'\nBjarorm Mjlorn says 'I thought so. One should never back down from a challenge. Once you have completed them I will have a cap, a robe, sleeves, wristbands, gloves, leggings and boots to reward you with.'\nAncient Silk Armor molds drop from zone trash throughout Temple of Veeshan with the exception of Halls of Testing(the east wing). Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Onyx Sapphire + Ancient Silk Wristband\nBoots  - 3x Crushed Jaundice Gem + Ancient Silk Boots\nArms - 3x Flawed Topaz + Ancient Silk Sleeves\nGloves - 3x Crushed Topaz + Ancient Silk Gloves\nHelm - 3x Crushed Flame Opal + Ancient Silk Turban\nLegs - 3x Nephrite + Ancient Silk Pantaloons\nChest - 3x Pristine Emerald + Ancient Silk Robe\nBracer\nYou say, 'wristband'\nBjarorm Mjlorn says 'The crafting of this wristband requires that you bring me an ancient silk wristband and three crushed onyx sapphire pieces.'\nGive Bjarorm 3x Crushed Onyx Sapphire and a Ancient Silk Wristband\nBjarorm Mjlorn smiles warmly as he hands you your reward.\nBjarorm Mjlorn says 'You have done well.'\nYou receive: Plague Bearer's Wristguard\nBoots\nYou say, 'boots'\nBjarorm Mjlorn says 'These supple boots shall be yours upon receipt of a pair of ancient silk boots and three crushed jaundice gems.'\nGive Bjarorm 3x Crushed Jaundice Gem and a Ancient Silk Boots\nBjarorm Mjlorn smiles warmly as he hands you your reward.\nBjarorm Mjlorn says 'You have done well.'\nYou receive: Plague Bearer's Boots\nArms\nYou say, 'sleeves'\nBjarorm Mjlorn says 'For these durable sleeves, you must fetch me a pair of ancient silk sleeves and three flawed topaz.'\nGive Bjarorm 3x Flawed Topaz and a Ancient Silk Sleeves\nBjarorm Mjlorn smiles warmly as he hands you your reward.\nBjarorm Mjlorn says 'You have done well.'\nYou receive: Plague Bearer's Sleeves\nGloves\nYou say, 'gloves'\nBjarorm Mjlorn says 'For this fine pair of gloves you must seek out and return to me a pair of ancient silk gloves and three crushed topaz.'\nGive Bjarorm 3x Crushed Topaz and a Ancient Silk Gloves\nBjarorm Mjlorn smiles warmly as he hands you your reward.\nBjarorm Mjlorn says 'You have done well.'\nYou receive: Plague Bearer's Gloves\nHelm\nYou say, 'cap'\nBjarorm Mjlorn says 'For you to receive my gift, I shall require an ancient silk turban and three crushed flame opals.'\nGive Bjarorm 3x Crushed Flame Opal and an Ancient Silk Turban\nBjarorm Mjlorn smiles warmly as he hands you your reward.\nBjarorm Mjlorn says 'You have done well.'\nYou receive: Plague Bearer's Circlet\nLegs\nYou say, 'leggings'\nBjarorm Mjlorn says 'This pair of leggings will yours provided you supply me with a pair of ancient silk pantaloons as well as three nephrites.'\nGive Bjarorm 3x Nephrite and a Ancient Silk Pantaloons\nBjarorm Mjlorn smiles warmly as he hands you your reward.\nBjarorm Mjlorn says 'You have done well.'\nYou receive: Plague Bearer's Trousers\nChest\nYou say, 'robe'\nBjarorm Mjlorn says 'This exquisite robe shall be yours in exchange for an ancient silk robe and three pristine emeralds.'\nGive Bjarorm 3x Pristine Emerald and a Ancient Silk Robe\nBjarorm Mjlorn smiles warmly as he hands you your reward.\nBjarorm Mjlorn says 'You have done well.'\nYou receive: Plague Bearer's Robe\nSubmitted by: BobbybickRewards:\n- Plague Bearer's Boots [item=5122]\n- Plague Bearer's Circlet [item=5515]\n- Plague Bearer's Gloves [item=4881]\n- Plague Bearer's Robe [item=5236]\n- Plague Bearer's Sleeves [item=5805]\n- Plague Bearer's Trousers [item=6417]\n- Plague Bearer's Wristguard [item=5445]\n[",
    },
    {
      id = "8291",
      title = "Paladin Kael Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Barlek Stonefist",
      loc = nil,
      triggers = {
        "Hail, Barlek Stonefist",
        "I am a paladin",
        "I wish to partake of your quests",
        "bracer",
        "boots",
        "armplates",
        "gauntlets",
        "helm",
      },
      items_required = {
      },
      rewards = {
        { id = 5121, name = "Shining Boots", type = "item" },
        { id = 5097, name = "Shining Bracer", type = "item" },
        { id = 5226, name = "Shining Breastplate", type = "item" },
        { id = 4790, name = "Shining Gauntlets", type = "item" },
        { id = 5248, name = "Shining Greaves", type = "item" },
        { id = 5148, name = "Shining Helm", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nBarlek Stonefist in the quest room behind King Tormax's throneroom offers a series of quests for paladins to obtain a set of Shining Armor.\nYou must be at least ALLY with Kromzek in order to complete these quests.\nYou say, 'Hail, Barlek Stonefist'\nBarlek Stonefist says, 'Greetings to you. I seek the service of devout knights who have distinguished themselves. Are you a paladin? If not then be gone.'\nYou say, 'I am a paladin'\nBarlek Stonefist says, 'A paladin of your order has not made it this far for quite some time. Well, I wonder what it is you seek here. Do you seek heroic and chivalrous deeds to distinguish yourself from your brethren? Do you need accoutrements to aid you in your battles perhaps? You are in luck, knight for I have both for you. Do you wish to partake of my quests?'\nYou say, 'I wish to partake of your quests'\nBarlek Stonefist says, 'Excellent. By serving my cause, you, in turn, will further your own. I require certain components to aid me and if you bring them to me, I shall reward you for your honorable service. You may choose from among these items, a helm, a breastplate, armplates, bracers, gauntlets, greaves, and boots.'\nAncient Tarnished Armor molds drop from zone trash throughout Temple of Veeshan with the exception of Halls of Testing(the east wing). Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Flame Emerald + Ancient Tarnished Plate Bracelet\nBoots  - 3x Crushed Black Marble + Ancient Tarnished Plate Boots\nArms - 3x Flawed Emerald + Ancient Tarnished Plate Vambraces\nGloves - 3x Crushed Topaz + Ancient Tarnished Plate Gauntlets\nHelm - 3x Crushed Coral + Ancient Tarnished Plate Helmet\nLegs - 3x Flawed Sea Sapphire + Ancient Tarnished Plate Greaves\nChest - 3x Flawless Diamond + Ancient Tarnished Breastplate\nBracer\nYou say, 'bracer'\nBarlek Stonefist says 'Bracers for the mighty? Retrieve these components and I shall forge the item for you. Bring me an ancient tarnished plate bracelet as well as three crushed flame emeralds.'\nGive Barlek 3x Crushed Flame Emerald and a Ancient Tarnished Plate Bracelet\nBarlek Stonefist smiles warmly as he hands you your reward.\nBarlek Stonefist says 'You have done well.'\nYou receive: Shining Bracers\nBoots\nYou say, 'boots'\nBarlek Stonefist says 'A pair of boots you shall have once you have gotten a pair of an ancient tarnished plate boots and a set of three crushed pieces of black marble.'\nGive Barlek 3x Crushed Black Marble and an Ancient Tarnished Plate Boots\nBarlek Stonefist smiles warmly as he hands you your reward.\nBarlek Stonefist says 'You have done well.'\nYou receive: Shining Boots\nArms\nYou say, 'armplates'\nBarlek Stonefist says 'So, a pair of armplates, is what you require? Well, I require an ancient tarnished plate vambraces as well as three flawed emeralds before you will receive your prize.'\nGive Barlek 3x Flawed Emerald and an Ancient Tarnished Plate Vambraces\nBarlek Stonefist smiles warmly as he hands you your reward.\nBarlek Stonefist says 'You have done well.'\nYou receive: Shining Vambraces\nGloves\nYou say, 'gauntlets'\nBarlek Stonefist says 'Mighty gauntlets to smite your foes for the glory of the greater good. It is no easy task but I shall require a pair of an ancient tarnished plate gauntlets and three crushed topaz.'\nGive Barlek 3x Crushed Topaz and an Ancient Tarnished Plate Gauntlets\nBarlek Stonefist smiles warmly as he hands you your reward.\nBarlek Stonefist says 'You have done well.'\nYou receive: Shining Gauntlets\nHelm\nYou say, 'helm'\nBarlek Stonefist says 'All that I require is an ancient tarnished plate helmet and three pieces of crushed coral. This should be a small task for one such as you. Go now and I shall await your return.'\nGive Barlek 3x Crushed Coral and a Ancient Tarnished Plate Helmet\nBarlek Stonefist smiles warmly as he hands you your reward.\nBarlek Stonefist says 'You have done well.'\nYou receive: Shining Helm\nLegs\nYou say, 'greaves'\nBarlek Stonefist says 'Sturdy are the pillars that support the temple. I shall make you as strong with these leggings. Gather three flawed sapphires of the sea and a set of ancient tarnished plate greaves.'\nGive Barlek 3x Flawed Sea Sapphire and an Ancient Tarnished Plate Greaves\nBarlek Stonefist smiles warmly as he hands you your reward.\nBarlek Stonefist says 'You have done well.'\nYou receive: Shining Greaves\nChest\nYou say, 'breastplate'\nBarlek Stonefist says 'As the resolve of your faith shall protect you, so shall this breastplate. All that is required is an ancient tarnished breastplate, and three flawless diamonds. Do this quickly so that you may return to your place in the field of battle.'\nGive Barlek 3x Flawless Diamond and a Ancient Tarnished Breastplate\nBarlek Stonefist smiles warmly as he hands you your reward.\nBarlek Stonefist says 'You have done well.'\nYou receive: Shining Breastplate\nSubmitted by: BobbybickRewards:\n- Shining Boots [item=5121]\n- Shining Bracer [item=5097]\n- Shining Breastplate [item=5226]\n- Shining Gauntlets [item=4790]\n- Shining Greaves [item=5248]\n- Shining Helm [item=5148]\n- Shining Vambraces [item=5325]\n[",
    },
    {
      id = "8292",
      title = "Cleric Kael Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "King Tormax",
      loc = nil,
      triggers = {
        "Hail, Vylleam Vyaeltor",
        "I am a cleric",
        "I wish your aid",
        "bracer",
        "boots",
        "armplates",
        "gauntlets",
        "helm",
      },
      items_required = {
        { id = 30501, name = "Item #30501", count = 1 },
        { id = 24984, name = "Item #24984", count = 1 },
      },
      rewards = {
        { id = 5127, name = "Templar's Boots", type = "item" },
        { id = 5126, name = "Templar's Bracer", type = "item" },
        { id = 4952, name = "Templar's Chestplate", type = "item" },
        { id = 5168, name = "Templar's Crown", type = "item" },
        { id = 4859, name = "Templar's Gauntlets", type = "item" },
        { id = 4983, name = "Templar's Leggings", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nVylleam Vyaeltor in the quest room behind King Tormax's throneroom offers a series of quests for clerics to obtain a set of Templar's Armor.\nYou must be at least ALLY with Kromzek in order to complete these quests.\nYou say, 'Hail, Vylleam Vyaeltor'\nVyllaem Vyaeltor bows.\nVylleam Vyaeltor says 'Greetings to you. You are far away from your homelands, stranger. I am looking for someone. Someone that the outlanders call a cleric. Are you a cleric?'\nYou say, 'I am a cleric'\nVylleam Vyaeltor says 'Ahhh... most pious one. I sense the aura of your devotion and conviction and it is strong about you. A shame you are so short lived, mortal. But I see potential in you and for that I shall aid you in your calling. Do you wish my aid?'\nYou say, 'I wish your aid'\nVylleam Vyaeltor says 'Then I have a set of goals for you. Once you have achieved them, you shall be rewarded with such as these; a helm, a breastplate, armplates, bracers, gauntlets, greaves and boots. May they protect you from your enemies.'\nAncient Tarnished Armor molds drop from zone trash throughout Temple of Veeshan with the exception of Halls of Testing(the east wing). Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Opal + Ancient Tarnished Plate Bracelet\nBoots  - 3x Crushed Flame Emerald + Ancient Tarnished Plate Boots\nArms - 3x Jaundice Gem + Ancient Tarnished Vambraces\nGloves - 3x Crushed Lava Ruby + Ancient Tarnished Plate Gauntlets\nHelm - 3x Crushed Onyx Sapphire + Ancient Tarnished Plate Helmet\nLegs - 3x Chipped Onyx Sapphire + Ancient Tarnished Greaves\nChest - 3x Black Marble + Ancient Tarnished Breastplate\nBracer\nYou say, 'bracer'\nVylleam Vyaeltor says 'For the bracers, faithful one, I shall require the acquisition of an ancient tarnished plate bracer and three crushed opals.'\nGive Vylleam 3x Crushed Opal and a Ancient Tarnished Plate Bracelet\nVylleam Vyaeltor smiles warmly as he hands you your reward.\nVylleam Vyaeltor says 'You have done well.'\nYou receive: Templar's Bracer\nBoots\nYou say, 'boots'\nVylleam Vyaeltor says 'With your aid I shall make a pair of fine boots for you. All that is needed is a pair of an ancient tarnished plate boots and a trilogy of crushed flame emeralds.'\nGive Vylleam 3x Crushed Flame Emerald and an Ancient Tarnished Plate Boots\nVylleam Vyaeltor smiles warmly as he hands you your reward.\nVylleam Vyaeltor says 'You have done well.'\nYou receive: Templar's Boots\nArms\nYou say, 'armplates'\nVylleam Vyaeltor says 'For the armplates, I shall require a pair of an ancient tarnished plate armplates as well as three jaundice gems. Go forth and seek these out.'\nGive Vylleam 3x Jaundice Gem and an Ancient Tarnished Vambraces\nVylleam Vyaeltor smiles warmly as he hands you your reward.\nVylleam Vyaeltor says 'You have done well.'\nYou receive: Templar's Vambraces\nGloves\nYou say, 'gauntlets'\nVylleam Vyaeltor says 'I will need a pair of a ancient tarnished gauntlets three crushed lava rubys, so that I may make your reward.'\nGive Vylleam 3x Crushed Lava Ruby and an Ancient Tarnished Plate Gauntlets\nVylleam Vyaeltor smiles warmly as he hands you your reward.\nVylleam Vyaeltor says 'You have done well.'\nYou receive: Templar's Gauntlets\nHelm\nYou say, 'helm'\nVylleam Vyaeltor says 'I shall craft a helm for you but you must seek these items out for me first. I have need of an ancient tarnished plate helmet and three crushed onyx sapphires.'\nGive Vylleam 3x Crushed Onyx Sapphire and a Ancient Tarnished Plate Helmet\nVylleam Vyaeltor smiles warmly as he hands you your reward.\nVylleam Vyaeltor says 'You have done well.'\nYou receive: Templar's Crown\nLegs\nYou say, 'greaves'\nVylleam Vyaeltor says 'You shall acquire a pair of an ancient tarnished plate greaves and three chipped onyx sapphires for me. I await your return.'\nGive Vylleam 3x Chipped Onyx Sapphire and an Ancient Tarnished Greaves\nVylleam Vyaeltor smiles warmly as he hands you your reward.\nVylleam Vyaeltor says 'You have done well.'\nYou receive: Templar's Leggings\nChest\nYou say, 'breastplate'\nVylleam Vyaeltor says 'Such as your faith protects you so shall this breastplate. I must have an ancient tarnished breastplate and three pieces of black marble.'\nGive Vylleam 3x Black Marble and a Ancient Tarnished Breastplate\nVylleam Vyaeltor smiles warmly as he hands you your reward.\nVylleam Vyaeltor says 'You have done well.'\nYou receive: Templar's Breastplate\nSubmitted by: BobbybickRewards:\n- Templar's Boots [item=5127]\n- Templar's Bracer [item=5126]\n- Templar's Chestplate [item=4952]\n- Templar's Crown [item=5168]\n- Templar's Gauntlets [item=4859]\n- Templar's Leggings [item=4983]\n- Templar's Vambraces [item=5088]\n[",
    },
    {
      id = "8294",
      title = "Ranger Kael Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Gragek Mjlorkigar",
      loc = nil,
      triggers = {
        "Hail, Gragek Mjlorkigar",
        "I am a ranger",
        "i am ready to submit to your will",
        "bracer",
        "boots",
        "sleeves",
        "gauntlets",
        "coif",
      },
      items_required = {
      },
      rewards = {
        { id = 5261, name = "Forest Stalker's Boots", type = "item" },
        { id = 5147, name = "Forest Stalker's Bracer", type = "item" },
        { id = 5300, name = "Forest Stalker's Breastplate", type = "item" },
        { id = 4880, name = "Forest Stalker's Coif", type = "item" },
        { id = 5146, name = "Forest Stalker's Gauntlets", type = "item" },
        { id = 5098, name = "Forest Stalker's Greaves", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nGragek Mjlorkigar in the quest room behind King Tormax's throneroom offers a series of quests for rangers to obtain a set of Forest Stalker's Armor.\nYou must be at least ALLY with Kromzek in order to complete these quests.\nYou say, 'Hail, Gragek Mjlorkigar'\nGragek Mjlorkigar says, 'Greetings to you. I seek one who is a protector of nature. A ranger is what you call them I believe. Are you a ranger?'\nYou say, 'I am a ranger'\nGragek Mjlorkigar says, 'I have not seen your kind in quite some time. Do you seek aid in your never-ending fight against those who do nature harm? There is no need to answer for I see within your eyes, the commitment and the conviction. None the less, the tasks I set before you shall be none the easier. Are you ready to submit to my will?\"'\nYou say, 'i am ready to submit to your will'\nGragek Mjlorkigar says, 'That is good for there is nothing like the wrath of nature, woodlands warrior. And Natures wrath shall you be, with this armor to protect you in your struggle. I shall forge a coif, breastplate, sleeves, bracers, gauntlets, leggings, and boots for you.'\nAncient Tarnished Armor molds drop from zone trash throughout Temple of Veeshan with the exception of Halls of Testing(the east wing). Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Flame Emerald + Ancient Tarnished Chain Bracelet\nBoots  - 3x Crushed Black Marble + Ancient Tarnished Chain Boots\nArms - 3x Flawed Emerald + Ancient Tarnished Chain Sleeves\nGloves - 3x Crushed Topaz + Ancient Tarnished Chain Gauntlets\nHelm - 3x Crushed Coral + Ancient Tarnished Chain Coif\nLegs - 3x Flawed Sea Sapphire + Ancient Chain Leggings\nChest - 3x Flawless Diamond + Ancient Tarnished Chain Tunic\nBracer\nYou say, 'bracer'\nGragek Mjlorkigar says 'This shall help shield your forearms from any stray blows. Bring me an ancient tarnished chain wristguard and a trilogy of crushed flame emeralds.'\nGive Gragek 3x Crushed Flame Emerald and a Ancient Tarnished Chain Bracelet\nGragek Mjlorkigar smiles warmly as he hands you your reward.\nGragek Mjlorkigar says 'You have done well.'\nYou receive: Forest Stalker's Bracers\nBoots\nYou say, 'boots'\nGragek Mjlorkigar says 'For the boots, I shall require a pair of an ancient tarnished chain boots and three crushed pieces of black marble.'\nGive Gragek 3x Crushed Black Marble and an Ancient Tarnished Chain Boots\nGragek Mjlorkigar smiles warmly as he hands you your reward.\nGragek Mjlorkigar says 'You have done well.'\nYou receive: Forest Stalker's Boots\nArms\nYou say, 'sleeves'\nGragek Mjlorkigar says 'I require an ancient tarnished chain sleeves and three flawed emeralds. Do this so that I may grant you these special sleeves as a gift for your diligence.'\nGive Gragek 3x Flawed Emerald and an Ancient Tarnished Chain Sleeves\nGragek Mjlorkigar smiles warmly as he hands you your reward.\nGragek Mjlorkigar says 'You have done well.'\nYou receive: Forest Stalker's Vambraces\nGloves\nYou say, 'gauntlets'\nGragek Mjlorkigar says 'Bring me these items, for I will not grant you your pair until then. A pair of ancient tarnished chain gauntlets as well as three crushed topaz.'\nGive Gragek 3x Crushed Topaz and an Ancient Tarnished Chain Gauntlets\nGragek Mjlorkigar smiles warmly as he hands you your reward.\nGragek Mjlorkigar says 'You have done well.'\nYou receive: Forest Stalker's Gauntlets\nHelm\nYou say, 'coif'\nGragek Mjlorkigar says 'This coif shall protect you from battle and the elements. What I require of you is this. Three crushed coral pieces and a ancient tarnished chain coif.'\nGive Gragek 3x Crushed Coral and a Ancient Tarnished Chain Coif\nGragek Mjlorkigar smiles warmly as he hands you your reward.\nGragek Mjlorkigar says 'You have done well.'\nYou receive: Forest Stalker's Coif\nLegs\nYou say, 'leggings'\nGragek Mjlorkigar says 'A pair of leggings you seek? I seek something as well. Bring me a pair of an ancient tarnished chain leggings and three flawed sea sapphires. Go now. The struggle continues as we speak.'\nGive Gragek 3x Flawed Sea Sapphire and an Ancient Tarnished Chain Leggings\nGragek Mjlorkigar smiles warmly as he hands you your reward.\nGragek Mjlorkigar says 'You have done well.'\nYou receive: Forest Stalker's Greaves\nChest\nYou say, 'breastplate'\nGragek Mjlorkigar says 'Even as the hardiest tree in the forest requires protection, so shall this breastplate protect you. Bring these components for me, an ancient tarnished chain tunic as well as three flawless diamonds.'\nGive Gragek 3x Flawless Diamond and a Ancient Tarnished Chain Tunic\nGragek Mjlorkigar smiles warmly as he hands you your reward.\nGragek Mjlorkigar says 'You have done well.'\nYou receive: Forest Stalker's Breastplate\nSubmitted by: BobbybickRewards:\n- Forest Stalker's Boots [item=5261]\n- Forest Stalker's Bracer [item=5147]\n- Forest Stalker's Breastplate [item=5300]\n- Forest Stalker's Coif [item=4880]\n- Forest Stalker's Gauntlets [item=5146]\n- Forest Stalker's Greaves [item=5098]\n- Forest Stalker's Vambraces [item=5144]\n[",
    },
    {
      id = "8295",
      title = "Monk Kael Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Dagron Stonecutter",
      loc = nil,
      triggers = {
        "Hail, Dagron Stonecutter",
        "I am a monk",
        "bracer",
        "boots",
        "sleeves",
        "gauntlets",
        "cap",
        "leggings",
      },
      items_required = {
        { name = "Dagron 3x Crushed Coral and a Ancient Leather Cap", count = 1 },
      },
      rewards = {
        { id = 5489, name = "Fist of the Golden Star", type = "item" },
        { id = 4972, name = "Golden Star Arm Wraps", type = "item" },
        { id = 6224, name = "Golden Star Chest Wraps", type = "item" },
        { id = 5448, name = "Golden Star Headband", type = "item" },
        { id = 5174, name = "Golden Star Pants", type = "item" },
        { id = 5173, name = "Golden Star Slippers", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nDagron Stonecutter in the quest room behind King Tormax's throneroom offers a series of quests for monks to obtain a set of Golden Star Armor.\nYou must be at least ALLY with Kromzek in order to complete these quests.\nYou say, 'Hail, Dagron Stonecutter'\nDagron Stonecutter says, 'Greetings to you. I seek one who has chosen the path of monkhood. What do you call yourself?'\nYou say, 'I am a monk'\nDagron Stonecutter says, 'Good. I had hoped you were one. As seeker of the way you are in constant training to push yourself to your physical and mental limits. It is an admirable quality and I wish to aid you. I will provide you with a cap, a tunic, sleeves, bracers, gloves, leggings and boots.'\nAncient Leather Armor molds drop from zone trash throughout Temple of Veeshan with the exception of Halls of Testing(the east wing). Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Flame Emerald + Ancient Leather Bracelet\nBoots  - 3x Crushed Black Marble + Ancient Leather Boots\nArms - 3x Flawed Emerald + Ancient Leather Sleeves\nGloves - 3x Crushed Topaz + Ancient Leather Gauntlets\nHelm - 3x Crushed Coral + Ancient Leather Coif\nLegs - 3x Flawed Sea Sapphire + Ancient Leather Leggings\nChest - 3x Flawless Diamond + Ancient Leather Tunic\nBracer\nYou say, 'bracer'\nDagron Stonecutter says 'For a bracer I shall require an ancient leather bracelet and a set of three crushed flame emeralds. Do this and the reward shall be yours to keep.'\nGive Dagron 3x Crushed Flame Emerald and a Ancient Leather Bracelet\nDagron Stonecutter smiles warmly as he hands you your reward.\nDagron Stonecutter says 'You have done well.'\nYou receive: Golden Star Wrist Wraps\nBoots\nYou say, 'boots'\nDagron Stonecutter says 'Your feet are hard as any stone and as swift as a coiled serpent but even the swiftest feet require protection so I shall provide you with these. They should help. Acquire a pair of ancient tarnished boots and three crushed pieces of black marble.'\nGive Dagron 3x Crushed Black Marble and an Ancient Leather Boots\nDagron Stonecutter smiles warmly as he hands you your reward.\nDagron Stonecutter says 'You have done well.'\nYou receive: Golden Star Slippers\nArms\nYou say, 'sleeves'\nDagron Stonecutter says 'As the mighty stone that parts the flow of water, so shall these sleeves divert harm against you. Bring me three flawed emeralds and a pair of ancient leather sleeves.'\nGive Dagron 3x Flawed Emerald and an Ancient Leather Sleeves\nDagron Stonecutter smiles warmly as he hands you your reward.\nDagron Stonecutter says 'You have done well.'\nYou receive: Golden Star Arm Wraps\nGloves\nYou say, 'gauntlets'\nDagron Stonecutter says 'Your hands are like the wind, everflowing and moving. Subtle one moment, then a howling wind raining blow upon blow to your foes. These gloves shall aid you. In order to complete them I require a pair of ancient leather gloves and three crushed topaz.'\nGive Dagron 3x Crushed Topaz and an Ancient Leather Gloves\nDagron Stonecutter smiles warmly as he hands you your reward.\nDagron Stonecutter says 'You have done well.'\nYou receive: Fist of the Golden Star\nHelm\nYou say, 'cap'\nDagron Stonecutter says 'I shall weave one of exceptional quality for you but you must gather the items first. I require an ancient leather cap and a set of three pieces of crushed coral.'\nGive Dagron 3x Crushed Coral and a Ancient Leather Cap\nDagron Stonecutter smiles warmly as he hands you your reward.\nDagron Stonecutter says 'You have done well.'\nYou receive: Golden Star Headband\nLegs\nYou say, 'leggings'\nDagron Stonecutter says 'The leggings shall protect you, as the valley shelters the still pool within its center from the howling winds. Furnish a pair of ancient leather leggings and a set of three flawed sea sapphires for me and they are yours.'\nGive Dagron 3x Flawed Sea Sapphire and an Ancient Leather Leggings\nDagron Stonecutter smiles warmly as he hands you your reward.\nDagron Stonecutter says 'You have done well.'\nYou receive: Golden Star Pants\nChest\nYou say, 'Tunic'\nDagron Stonecutter says 'You shall be an imposing force with this tunic. Solid as the unmoving mountains, it shall protect you. Once I have gained an ancient leather tunic and three flawless diamonds, the item is yours.'\nGive Dagron 3x Flawless Diamond and a Ancient Leather Tunic\nDagron Stonecutter smiles warmly as he hands you your reward.\nDagron Stonecutter says 'You have done well.'\nYou receive: Golden Star Chest Wraps\nSubmitted by: BobbybickRewards:\n- Fist of the Golden Star [item=5489]\n- Golden Star Arm Wraps [item=4972]\n- Golden Star Chest Wraps [item=6224]\n- Golden Star Headband [item=5448]\n- Golden Star Pants [item=5174]\n- Golden Star Slippers [item=5173]\n- Golden Star Wrist Wraps [item=5447]\n[",
    },
    {
      id = "8296",
      title = "Beastlord Kael Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "King Tormax",
      loc = nil,
      triggers = {
        "Hail, Nerik Wolfsoul",
        "I am a beastlord",
        "bracer",
        "boots",
        "sleeves",
        "gauntlets",
        "cap",
        "leggings",
      },
      items_required = {
        { name = "Nerik 3x Crushed Coral and a Ancient Leather Cap", count = 1 },
      },
      rewards = {
        { id = 11619, name = "Armband of Beast Mastery", type = "item" },
        { id = 11617, name = "Boots of Beast Mastery", type = "item" },
        { id = 11618, name = "Bracer of Beast Mastery", type = "item" },
        { id = 14114, name = "Chestguard of Beast Mastery", type = "item" },
        { id = 13260, name = "Crown of Beast Mastery", type = "item" },
        { id = 15969, name = "Gloves of Beast Mastery", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nNerik Wolfsoul in the quest room behind King Tormax's throneroom offers a series of quests for beastlords to obtain a set of Beast Mastery Armor.\nYou must be at least ALLY with Kromzek in order to complete these quests.\nYou say, 'Hail, Nerik Wolfsoul'\nNerik Wolfsoul says, 'Greetings to you. I seek one who is known as a beastlord. What do you call yourself, (playername)?'\nYou say, 'I am a beastlord'\nNerik Wolfsoul says, 'Then perhaps you would be interested in some armor that I can make you. I can make you a cap, tunic, leggings, bracer, boots, sleeves, and gloves if you bring me the correct items.'\nAncient Leather Armor molds drop from zone trash throughout Temple of Veeshan with the exception of Halls of Testing(the east wing). Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Flame Emerald + Ancient Leather Bracelet\nBoots  - 3x Crushed Black Marble + Ancient Leather Boots\nArms - 3x Flawed Emerald + Ancient Leather Sleeves\nGloves - 3x Crushed Topaz + Ancient Leather Gauntlets\nHelm - 3x Crushed Coral + Ancient Leather Coif\nLegs - 3x Flawed Sea Sapphire + Ancient Leather Leggings\nChest - 3x Flawless Diamond + Ancient Leather Tunic\nBracer\nYou say, 'bracer'\nNerik Wolfsoul says 'For a bracer I shall require an ancient leather bracelet and a set of three crushed flame emeralds. Do this and the reward shall be yours to keep.'\nGive Nerik 3x Crushed Flame Emerald and a Ancient Leather Bracelet\nNerik Wolfsoul smiles warmly as he hands you your reward.\nNerik Wolfsoul says 'You have done well.'\nYou receive: Bracer of Beast Mastery\nBoots\nYou say, 'boots'\nNerik Wolfsoul says 'Your feet are hard as any stone and as swift as a coiled serpent but even the swiftest feet require protection so I shall provide you with these. They should help. Acquire a pair of ancient tarnished boots and three crushed pieces of black marble.'\nGive Nerik 3x Crushed Black Marble and an Ancient Leather Boots\nNerik Wolfsoul smiles warmly as he hands you your reward.\nNerik Wolfsoul says 'You have done well.'\nYou receive: Boots of Beast Mastery\nArms\nYou say, 'sleeves'\nNerik Wolfsoul says 'As the mighty stone that parts the flow of water, so shall these sleeves divert harm against you. Bring me three flawed emeralds and a pair of ancient leather sleeves.'\nGive Nerik 3x Flawed Emerald and an Ancient Leather Sleeves\nNerik Wolfsoul smiles warmly as he hands you your reward.\nNerik Wolfsoul says 'You have done well.'\nYou receive: Armband of Beast Mastery\nGloves\nYou say, 'gauntlets'\nNerik Wolfsoul says 'Your hands are like the wind, everflowing and moving. Subtle one moment, then a howling wind raining blow upon blow to your foes. These gloves shall aid you. In order to complete them I require a pair of ancient leather gloves and three crushed topaz.'\nGive Nerik 3x Crushed Topaz and an Ancient Leather Gloves\nNerik Wolfsoul smiles warmly as he hands you your reward.\nNerik Wolfsoul says 'You have done well.'\nYou receive: Gloves of Beast Mastery\nHelm\nYou say, 'cap'\nNerik Wolfsoul says 'I shall weave one of exceptional quality for you but you must gather the items first. I require an ancient leather cap and a set of three pieces of crushed coral.'\nGive Nerik 3x Crushed Coral and a Ancient Leather Cap\nNerik Wolfsoul smiles warmly as he hands you your reward.\nNerik Wolfsoul says 'You have done well.'\nYou receive: Crown of Beast Mastery\nLegs\nYou say, 'leggings'\nNerik Wolfsoul says 'The leggings shall protect you, as the valley shelters the still pool within its center from the howling winds. Furnish a pair of ancient leather leggings and a set of three flawed sea sapphires for me and they are yours.'\nGive Nerik 3x Flawed Sea Sapphire and an Ancient Leather Leggings\nNerik Wolfsoul smiles warmly as he hands you your reward.\nNerik Wolfsoul says 'You have done well.'\nYou receive: Leggings of Beast Mastery\nChest\nYou say, 'Tunic'\nNerik Wolfsoul says 'You shall be an imposing force with this tunic. Solid as the unmoving mountains, it shall protect you. Once I have gained an ancient leather tunic and three flawless diamonds, the item is yours.'\nGive Nerik 3x Flawless Diamond and a Ancient Leather Tunic\nNerik Wolfsoul smiles warmly as he hands you your reward.\nNerik Wolfsoul says 'You have done well.'\nYou receive: Chestguard of Beast Mastery\nSubmitted by: BobbybickRewards:\n- Armband of Beast Mastery [item=11619]\n- Boots of Beast Mastery [item=11617]\n- Bracer of Beast Mastery [item=11618]\n- Chestguard of Beast Mastery [item=14114]\n- Crown of Beast Mastery [item=13260]\n- Gloves of Beast Mastery [item=15969]\n- Leggings of Beast Mastery [item=15970]\n[",
    },
    {
      id = "8297",
      title = "Druid Kael Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Jaglorm Ygorr",
      loc = nil,
      triggers = {
        "Hail, Jaglorm Ygorr",
        "I am a druid",
        "bracer",
        "boots",
        "sleeves",
        "gloves",
        "cap",
        "leggings",
      },
      items_required = {
      },
      rewards = {
        { id = 4953, name = "Nature Walker's Boots", type = "item" },
        { id = 5245, name = "Nature Walker's Bracer", type = "item" },
        { id = 4961, name = "Nature Walker's Chestguard", type = "item" },
        { id = 5490, name = "Nature Walker's Circlet", type = "item" },
        { id = 5611, name = "Nature Walker's Gauntlets", type = "item" },
        { id = 4958, name = "Nature Walker's Greaves", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nJaglorm Ygorr in the quest room behind King Tormax's throneroom offers a series of quests for druids to obtain a set of Nature Walker's Armor.\nYou must be at least ALLY with Kromzek in order to complete these quests.\nYou say, 'Hail, Jaglorm Ygorr'\nJaglorm Ygorr says, 'Greetings to you. I seek one that calls himself a druid. What do you call yourself, manling?\"'\nYou say, 'I am a druid'\nJaglorm Ygorr says, 'Good. I had hoped you were one. As nature's guardian, you fight the never-ending struggle against those who seek to defile it. It is an admirable quality and I wish to aid you. I will provide you with a cap, a tunic, sleeves, bracers, gloves, leggings and boots.'\nAncient Leather Armor molds drop from zone trash throughout Temple of Veeshan with the exception of Halls of Testing(the east wing). Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Opal + Ancient Leather Bracelet\nBoots  - 3x Crushed Flame Emerald + Ancient Leather Boots\nArms - 3x Jaundice Gem + Ancient Leather Sleeves\nGloves - 3x Crushed Lava Ruby + Ancient Leather Gauntlets\nHelm - 3x Crushed Onyx Sapphire + Ancient Leather Coif\nLegs - 3x Chipped Onyx Sapphire + Ancient Leather Leggings\nChest - 3x Black Marble + Ancient Leather Tunic\nBracer\nYou say, 'bracer'\nJaglorm Ygorr says 'For a bracer I shall require an ancient leather bracelet, and three crushed opals. Do this and the reward shall be yours to keep.'\nGive Jaglorm 3x Crushed Opal and a Ancient Leather Bracelet\nJaglorm Ygorr smiles warmly as he hands you your reward.\nJaglorm Ygorr says 'You have done well.'\nYou receive: Nature Walker's Bracer\nBoots\nYou say, 'boots'\nJaglorm Ygorr says 'Even the swiftest feet need protection so I shall provide you with these. They should help. Acquire a pair of ancient boots and three crushed flame emeralds.'\nGive Jaglorm 3x Crushed Flame Emerald and an Ancient Leather Boots\nJaglorm Ygorr smiles warmly as he hands you your reward.\nJaglorm Ygorr says 'You have done well.'\nYou receive: Nature Walker's Boots\nArms\nYou say, 'sleeves'\nJaglorm Ygorr says 'As the bark protects the limbs of the tree, so shall these sleeves protect your arms. Bring me a pair of an ancient leather sleeves and three jaundice gems.'\nGive Jaglorm 3x Jaundice Gem and an Ancient Leather Sleeves\nJaglorm Ygorr smiles warmly as he hands you your reward.\nJaglorm Ygorr says 'You have done well.'\nYou receive: Nature Walker's Vambraces\nGloves\nYou say, 'gloves'\nJaglorm Ygorr says 'The gloves shall help protect you from the elements and harm. In order for me to complete them I require a pair of an ancient leather gloves and three crushed lava rubys.'\nGive Jaglorm 3x Crushed Lava Ruby and an Ancient Leather Gloves\nJaglorm Ygorr smiles warmly as he hands you your reward.\nJaglorm Ygorr says 'You have done well.'\nYou receive: Nature Walker's Gauntlets\nHelm\nYou say, 'cap'\nJaglorm Ygorr says 'I shall weave one of exceptional quality for you but you must gather the ingredients first. I require an ancient leather cap and three crushed onyx sapphires.'\nGive Jaglorm 3x Crushed Onyx Sapphire and a Ancient Leather Cap\nJaglorm Ygorr smiles warmly as he hands you your reward.\nJaglorm Ygorr says 'You have done well.'\nYou receive: Nature Walker's Circlet\nLegs\nYou say, 'leggings'\nJaglorm Ygorr says 'As the roots support the mighty oak, so shall these leggings support you. Furnish a pair of an ancient leather leggings as well as three chipped onyx sapphires and they are yours.'\nGive Jaglorm 3x Chipped Onyx Sapphire and an Ancient Leather Leggings\nJaglorm Ygorr smiles warmly as he hands you your reward.\nJaglorm Ygorr says 'You have done well.'\nYou receive: Nature Walker's Greaves\nChest\nYou say, 'Tunic'\nJaglorm Ygorr says 'You shall be a force of nature with this tunic. Once I have gained an ancient leather tunic and three pieces of black marble the item is yours.'\nGive Jaglorm 3x Black Marble and a Ancient Leather Tunic\nJaglorm Ygorr smiles warmly as he hands you your reward.\nJaglorm Ygorr says 'You have done well.'\nYou receive: Nature Walker's Chestguard\nSubmitted by: BobbybickRewards:\n- Nature Walker's Boots [item=4953]\n- Nature Walker's Bracer [item=5245]\n- Nature Walker's Chestguard [item=4961]\n- Nature Walker's Circlet [item=5490]\n- Nature Walker's Gauntlets [item=5611]\n- Nature Walker's Greaves [item=4958]\n- Nature Walker's Vambraces [item=5007]\n[",
    },
    {
      id = "8315",
      title = "Berserker Kael Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 45,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = false,
      group_size = "Solo",
      npc = "King Tormax",
      loc = nil,
      triggers = {
        "Hail, Regbor Vallgerthon",
        "i am a berserker",
        "bracer",
        "boots",
        "sleeves",
        "gloves",
        "coif",
        "leggings",
      },
      items_required = {
        { id = 30501, name = "Item #30501", count = 1 },
        { id = 24984, name = "Item #24984", count = 1 },
      },
      rewards = {
        { id = 32974, name = "Firebrand's Boots", type = "item" },
        { id = 32973, name = "Firebrand's Bracer", type = "item" },
        { id = 57128, name = "Firebrand's Coif", type = "item" },
        { id = 57129, name = "Firebrand's Gauntlets", type = "item" },
        { id = 26689, name = "Firebrand's Leggings", type = "item" },
        { id = 33657, name = "Firebrand's Sleeves", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 45\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Era:** Unset\n**Group Size:** Solo\n\nThis quest is currently very incomplete.  Little to no information has ever been posted on it but the rewards are known.\nRegbor Vallgerthon in the quest room behind King Tormax's throneroom offers a series of quests for berserkers to obtain a set of Firebrand's Armor.\nYou must be at least ?ALLY? with Kromzek in order to complete these quests.\nYou say, 'Hail, Regbor Vallgerthon'\nRegbor Vallgerthon says 'If you be one who lives the life of a berserker, I can perhaps assist you.  If not, then be gone.'\nYou say, 'i am a berserker'\nNeed missing dialogue\nAncient Tarnished Armor molds drop from zone trash throughout Temple of Veeshan with the exception of Halls of Testing(the east wing). Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Flame Emerald + Ancient Tarnished Chain Bracelet\nBoots  - 3x Crushed Black Marble + Ancient Tarnished Chain Boots\nArms - 3x Flawed Emerald + Ancient Tarnished Chain Sleeves\nGloves - 3x Crushed Topaz + Ancient Tarnished Chain Gauntlets\nHelm - 3x Crushed Coral + Ancient Tarnished Chain Coif\nLegs - 3x Flawed Sea Sapphire + Ancient Chain Leggings\nChest - 3x Flawless Diamond + Ancient Tarnished Chain Tunic\nBracer\nYou say, 'bracer'\nNeed missing dialogue\nGive Regbor 3x Crushed Flame Emerald and a Ancient Tarnished Chain Bracelet\nRegbor Vallgerthon smiles warmly as he hands you your reward.\nRegbor Vallgerthon says 'You have done well.'\nYou receive: Firebrand's Bracer\nBoots\nYou say, 'boots'\nNeed missing dialogue\nGive Regbor 3x Crushed Black Marble and an Ancient Tarnished Chain Boots\nRegbor Vallgerthon smiles warmly as he hands you your reward.\nRegbor Vallgerthon says 'You have done well.'\nYou receive: Firebrand's Boots\nArms\nYou say, 'sleeves'\nNeed missing dialogue\nGive Regbor 3x Flawed Emerald and an Ancient Tarnished Chain Sleeves\nRegbor Vallgerthon smiles warmly as he hands you your reward.\nRegbor Vallgerthon says 'You have done well.'\nYou receive: Firebrand's Sleeves\nGloves\nYou say, 'gloves'\nNeed missing dialogue\nGive Regbor 3x Crushed Topaz and an Ancient Tarnished Chain Gauntlets\nRegbor Vallgerthon smiles warmly as he hands you your reward.\nRegbor Vallgerthon says 'You have done well.'\nYou receive: Firebrand's Gauntlets\nHelm\nYou say, 'coif'\nNeed missing dialogue\nGive Regbor 3x Crushed Coral and a Ancient Tarnished Chain Coif\nRegbor Vallgerthon smiles warmly as he hands you your reward.\nRegbor Vallgerthon says 'You have done well.'\nYou receive: Firebrand's Coif\nLegs\nYou say, 'leggings'\nNeed missing dialogue\nGive Regbor 3x Flawed Sea Sapphire and an Ancient Tarnished Chain Leggings\nRegbor Vallgerthon smiles warmly as he hands you your reward.\nRegbor Vallgerthon says 'You have done well.'\nYou receive: Firebrand's Leggings\nChest\nYou say, 'tunic'\nNeed missing dialogue\nGive Regbor 3x Flawless Diamond and a Ancient Tarnished Chain Tunic\nRegbor Vallgerthon smiles warmly as he hands you your reward.\nRegbor Vallgerthon says 'You have done well.'\nYou receive: Firebrand's Tunic\nSubmitted by: BobbybickRewards:\n- Firebrand's Boots [item=32974]\n- Firebrand's Bracer [item=32973]\n- Firebrand's Coif [item=57128]\n- Firebrand's Gauntlets [item=57129]\n- Firebrand's Leggings [item=26689]\n- Firebrand's Sleeves [item=33657]\n- Firebrand's Tunic [item=26688]\n[",
    },
    {
      id = "8613",
      title = "Conqueror of Kael Drakkel",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "Derakor the Vindicator",
      loc = nil,
      triggers = {
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon completing the following raids in Kael Drakkel:\nThe Avatar of War\nDerakor the Vindicator\nKing TormaxSubmitted by: GidonoRewards:\n[",
    },
    {
      id = "8631",
      title = "Hunter of Kael Drakkel",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "Achievement",
      repeatable = false,
      group_size = "Solo",
      npc = "Bjoskhua Blackfist",
      loc = nil,
      triggers = {
        "study",
        "clrakk",
        "chest straps",
        "fist",
      },
      items_required = {
        { id = 20524, name = "Item #20524", count = 1 },
      },
      rewards = {
        { id = 25053, name = "Item #25053", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 1\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** No\n**Can Be Shrouded?:** No\n**Quest Type:** Achievement\n**Group Size:** Solo\n\nThis achievement is gained upon defeating the following rare monsters in Kael Drakkel:\nBjoskhua Blackfist\nBjrakor the Cold\nCaptain Bvellos\nClrakk Blackfist\nDlammaz Stormslayer\nGkrean Prophet of Tallon\nGleed Dragonhunter\nKlaggan Iceshard\nKorakaz\nKyenka\nNojas Blackfist\nReivaj the Battlerager\nSemkak Prophet of Vallon\nSlaggak the Trainer\na Storm Giant Warlord\nTuuak\nVealok the Angry\nVorken Iceshard\nYetarrSubmitted by: GidonoRewards:\n[",
    },
  },
}
