-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Esianti: Palace of the Winds (palace of the winds=esianti)
-- Total Quests: 10
-- ============================================================================

return {
  zone = "palace of the winds=esianti",
  zone_name = "Esianti: Palace of the Winds",
  quests = {
    {
      id = "9241",
      title = "Mercenary of Esianti: Palace of the Winds (10 Points)",
      exp = "25",
      exp_name = "The Burning Lands",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Unknown",
      loc = nil,
      triggers = {
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Esianti: Palace of the Winds [zone=1211]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | No\n**Can Be Shrouded?:** | No\n**Quest Type:** | Achievement\n**Quest Goal:**\n- Advancement\n**Related Quests:**\n- Armor of Acrophobia [quest=9449]\n- Beyond the Ex-pyre-ation Date [quest=9451]\n- Champion of The Burning Lands (30 Points) [quest=9255]\n- Not as Swell as You Would Think [quest=9450]\n- Sweeping Up the Brumes [quest=9452]\n**Era:** | !The Burning Lands\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Oct 31 00:23:34 2018\nModified: Tue Dec 5 05:21:04 2023 | | This achievement is gained upon completing the following quests in Esianti: Palace of the Winds\nPhibbit - Armor of Acrophobia\nPhibbit - Not as SWELL as you would think\nPhibbit - Beyond the ex-PYRE-ation date\nPhibbit - Sweeping up the Brumes\nReward(s):\nNone\n**Submitted by:** Gidono",
    },
    {
      id = "9242",
      title = "Partisan of Esianti: Palace of the Winds (10 Points)",
      exp = "25",
      exp_name = "The Burning Lands",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Unknown",
      loc = nil,
      triggers = {
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Esianti: Palace of the Winds [zone=1211]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | No\n**Can Be Shrouded?:** | No\n**Quest Type:** | Achievement\n**Quest Goal:**\n- Advancement\n**Related Quests:**\n- All Hail the King [quest=9267]\n- Champion of The Burning Lands (30 Points) [quest=9255]\n- Of Mice and Jann [quest=9447]\n- Serving Another Master [quest=9453]\n**Era:** | !The Burning Lands\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Oct 31 00:25:54 2018\nModified: Tue Dec 5 05:21:04 2023 | | This achievement is gained upon completing the following quests in Esianti: Palace of the Winds\nGreat Sky Ocean in Stratos - All Hail the King\nObsidian Sundering Master - Serving Another Master\nJoyous Blossom - Of Mice and Jann\nReward(s):\nNone\n**Submitted by:** Gidono",
    },
    {
      id = "9447",
      title = "Of Mice and Jann",
      exp = "25",
      exp_name = "The Burning Lands",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Joyous Blossom",
      loc = { y = -213.0, x = -1591.0, z = -62.0 },
      triggers = {
        "Hail, Joyous Blossom",
        "What",
        "Hail, Hammer Tearing Strike",
        "It all started when...",
        "Hail, Sadness of Distant Mountains",
        "_Quests_",
        "this",
      },
      items_required = {
        { name = "of Crisp stack of papers [quest=9447]", count = 1 },
        { name = "Hammer Tearing Strike my rebuttal", count = 1 },
        { name = "of Crisp stack of papers [quest=9447]", count = 1 },
        { name = "of Stained", count = 1 },
        { name = "of Stained", count = 1 },
        { name = "this to Hammer Tearing Strike", count = 1 },
      },
      rewards = {
        { id = 135802, name = "Crisp stack of papers", type = "item" },
        { id = 135803, name = "Singed stack of papers", type = "item" },
        { id = 135806, name = "Stack of insults", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Esianti: Palace of the Winds [zone=1211]\n**Who:**\n- Joyous Blossom [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Crisp stack of papers [item=135802]\n- Singed stack of papers [item=135803]\n- Stack of insults [item=135806]\n- Stained, singed stack of papers [item=135804]\n- Stained, singed, stabbed stack of papers [item=135805]\n**Related Creatures:**\n- Hammer Tearing Strike [npc=54252]\n- Lydia Springstrong [npc=54364]\n- Sadness of Distant Mountains [npc=54367]\n**Related Quests:**\n- Brass Palace [quest=9445]\n- Fight Fire [quest=9263]\n- Key to the Kingdom [quest=9264]\n- Palace of Embers [quest=9433]\n- Prisoner's Dilemma [quest=9265]\n- Soldier of Air [quest=9225]\n- Trial of Three (Trial of Smoke) [quest=9281]\n- Trial of the Ashes of Rusted Cliff's Glory (Trial of Smoke) [quest=9335]\n- Trial of the Eternal Cyclone (Trial of Smoke) [quest=9336]\n- Trial of the Speaker's Amphitheater (Trial of Smoke) [quest=9282]\n- Trial of the Wending Ways (Trial of Smoke) [quest=9337]\n**Era:** | !The Burning Lands\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 4 04:26:41 2018\nModified: Tue Dec 5 05:21:04 2023 | | Prerequisite Quests: Soldier of Air, Fight Fire, any one Trial of Smoke, Prisoner's Dilemma, Palace of Embers, Brass Palace, and Key to the Kingdom.\nFind Joyous Blossom in Esianti at -213, -1591, -62 on the far east island across the bridge near the west edge, she is on the Find tool.\nYou say, 'Hail, Joyous Blossom'\nJoyous Blossom says, 'Hey, have you seen Sadness of Distant Mountains? Bring [this] to him.'\nYou say, ' What's this?'\nShe gives you Crisp stack of papers.\nYou have been assigned the task 'Of Mice and Jann'.\n\n---\n\n2. Deliver the Crisp stack of papers to Sadness of Distant Mountains 0/1 Esianti: Palace of the Winds\n\n\n\n**Task Window:** Joyous Blossom asked you to hand deliver what appears to be some documents to Sadness of Distant Mountains because apparently you have that kind of time on hand and they don't, being immortal and all.\n\n\n\n\nYou would think that the jann would have been able to perform their own menial tasks by now.\n\n\n\n\nUpon hand in of Crisp stack of papers [quest=9447].\n\n\n\n\nSadness of Distant Mountains is fuming as he is going over piles of paperwork\n\n\n\n\nHe gives you Crisp stack of papers [quest=9447].\n\n\n\n\nSadness of Distant Mountains begins to read through some of the information in the packet, his expression sours as he gets to the end of the summons, 'Well I never!'. He furiously begins to write in the packet of paper\n\n\n\n\nYour task 'Of Mice and Jann' has been updated.\n\n\n\n\nHe is still writing.\n\n\n\n\nHe gets more livid with each of his quill strokes.\n\n\n\n\nIt feels like he may never stop writing.\n\n\n\n\nSadness of Distant Mountains says, 'Give Hammer Tearing Strike my rebuttal, I will NOT have him casting these disparaging remarks upon the Djinn!''\n\n3. Deliver Sadness of Distant Mountain's rebuttal to Hammer Tearing Strike 0/1 Esianti: Palace of the Winds\n\n\n\n**Task Window:** Well, THAT was unexpected.\n\n\n\n\nUpon hand in of Crisp stack of papers [quest=9447].\n\n\n\n\nHammer Tearing Strike greets you with a smile 'Why hello mortal, how can I assist yo...' he stops talking abruptly and notices the packet of papers you handed him. He becomes furious as he slams the packet on a desk, pulls out a quill and begins to write in the packets, murmuring curses under his breath.\n\n\n\n\nYou have been given: Singed stack of papers [quest=9447]\n\n\n\nYour task 'Of Mice and Jann' has been updated.\n\n\n\n\nHammer Tearing Strike says, '\"I cannot believe he would...HMPH\"'\n\n\n\n\nHammer Tearing Strike breaks a quill, throws it across the desk and furiously grabs another one. He dips it in a nearby inkwell and continues writing...\n\n\n\n\nHammer Tearing Strike gets near the end of the parchment and says '... YOURS... TRUELY... Deliver this to Lydia Springstrong immediately!' in his rage he singed part of the parchment.\n\n4. Deliver Hammer Tearing Strike's retort to Lydia Springstrong 0/1 Esianti: Palace of the Winds\n\n\n\n**Task Window:** At least you learned a few new Efreeti curse words. Hopefully Lydia will be able to cool the tempers of these two.\n\n\n\n\nUpon handing Lydia Springstrong Singed stack of papers [quest=9447].\n\n\n\n\nLydia Springstrong says, 'Greetings adventurer! What can I help you with?' as you hand Lydia the packet of papers, her expression goes from jovial to dire. 'Oh no...' she grabs a quill and an inkpot nervously. 'No no no...''\n\n\n\n\nYour task 'Of Mice and Jann' has been updated.\n\n\n\n\nLydia Springstrong's hand is shaking as she is scratching words into the paper, saying while she continues with her missive, 'Please...refrain...from...further...'\n\n\n\n\nLydia Springstrong continues writing, saying aloud '...and it would be in best interest to the mortal races if we could come to a consensus...'\n\n\n\n\nLydia Springstrong spills some of her ink during her nervous scrawling, 'Earnestly yours...'\n\n\n\n\nLydia Springstrong says, 'Please bring this back to Hammer Tearing Strike, I hope we are not too late.'\n\n\n\n\nYou have been given: Stained, singed stack of papers [quest=9447]\n\n5. Deliver Lydia Springstrong's counterargument to Hammer Tearing Strike 0/1 Esianti: Palace of the Winds\n\n\n\n**Task Window:** This packet has seen some better days\n\n\n\n\nYou say, 'Hail, Hammer Tearing Strike'\n\n\n\n\nHammer Tearing Strike is waiting for you to do what you were told.\n\n\n\n\nUpon hand in of Stained, singed stack of papers [quest=9447].\n\n\n\n\nHammer Tearing Strike grabs the singed and stained stack of papers from your hand before you have a chance to say anything and begins to read.\n\n\n\n\nYour task 'Of Mice and Jann' has been updated.\n\n\n\n\nHammer Tearing Strike says, 'Mmhmm.'\n\n\n\n\nHammer Tearing Strike says 'Very well.' as he sets the papers down and begins writing again.\n\n\n\n\nHammer Tearing Strike says, 'Tell me mortal, how is it that you [started: It all started when...] being a delivery person? Why is this the way you wanted to spend your life?'\n\n\n\n\nBefore you could even answer, Hammer Tearing Strike interrupts you, 'That's fascinating, please bring my protest to Sadness of Distant Mountains'\n\n\n\n\nYou receive Stained, singed stack of papers [quest=9447].\n\n\n\n\nYou say, ' It all started when...'\n\n6. Deliver Hammer Tearing Strike's protest to Sadness of Distant Mountains 0/1 Esianti: Palace of the Winds\n\n\n\n**Task Window:** While rude, you hope that this will help smooth things over between the Djinn and the Efreeti.\n\n\n\n\nYou say, 'Hail, Sadness of Distant Mountains'\n\n\n\n\nSadness of Distant Mountains is waiting for you to do what you were told\n\n\n\n\nUpon hand in of Stained, singed stack of papers [quest=9447]\n\n\n\nYour task 'Of Mice and Jann' has been updated.\n\n\n\n\nSadness of Distant Mountains seems to visually try to maintain his composure in seeing you, and takes the singed and stained stack of papers from you calmly, as if trying to hold back his rage. 'Thank you mortal, I didn't mean to explode at you like I did, I don't think this is your fault, and it wasn't fair that I would respond to you the way I did.' He continues to read through the papers, and begins to start a response. This time his curses are met with clenched jaws, as if a tide of anger is swelling up inside of him, and finishes his writing with a flourish and a stab of the quill. 'Please give this to Hammer Tearing Strike.'\n\n\n\n\nYou have been given: Stained, singed, stabbed stack of papers [quest=9447]\n\n7. Deliver Sadness of Distant Mountain's grievance to Hammer Tearing Strike 0/1 Esianti: Palace of the Winds\n\n\n\n**Task Window:** It appears that whatever Lydia wrote helped diffuse the situation between the two\n\n\n\n\nUpon hand in of Stained, singed, stabbed stack of papers to Hammer Tearing Strike.\n\n\n\n\nHammer Tearing Strike says, 'You again, good, I wanted to see what Sadness of Distant Mountains' response was going to be.' Hammer Tearing Strike begins to read the singed, stabbed, torn, stained pack of papers. He smiles, and begins to write again.'\n\n\n\n\nYour task 'Of Mice and Jann' has been updated.\n\n\n\n\nHammer Tearing Strike says, 'Thank you for your help in this matter mortal, it was very nice knowing you. Please bring this back to Sadness of Distant Mountains.'\n\n\n\n\nYou have been given: Stained, singed, stabbed stack of papers [quest=9447]\n\n8. Deliver Hammer Tearing Strike's challenge to Sadness of the Distant Mountains 0/1 Esianti: Palace of the Winds\n\n\n\n**Task Window:** That was pretty foreboding. You have an ill feeling in the pit of your stomach, as if you were an accessory to a conflict opening up someplace else in the Planes of Power.\n\n\n\n\nUpon hand in of Stained, singed, stabbed stack of papers [quest=9447] to Sadness of the Distant Mountains.\n\n\n\n\nYour task 'Of Mice and Jann' has been updated.\n\n\n\n\n'If it is a fight he wants, then it's a fight he will get! Begone mortal, I have work to do.' Sadness of Distant Mountains throws the stack of papers back at you.\n\n\n\n\nYou have been given: Stack of insults [quest=9447]\n\n9. Bring the Stack of insults to Joyous Blossom 0/1 Esianti: Palace of the Winds\n\n\n\n**Task Window:** Perhaps Joyous Blossom will be able to shed some light as to what had happened today.\n\n\n\n\nUpon hand in of Stack of insults [quest=9447] to Joyous Blossom.\n\n\n\n\nJoyous Blossom takes the packet and begins to read it.\n\n\n\n\nYour task 'Of Mice and Jann' has been updated.\n\n\n\n\nYou leave Joyous Blossom even more confused than when you first met her.\n\n\n\n\nYou receive 5 gold .\n\n\nYou receive 212 platinum .\n\n\nYou gain experience!\n\n\n\n\nJoyous Blossom bellows out the loudest laugh you have ever heard from an ondine, and then pretends you no longer exist.\n\n\n---\n\nReward(s):\n212 platinum 5 gold\nYou gain experience!\n**Submitted by:** Gidono",
    },
    {
      id = "9448",
      title = "Royal Visits",
      exp = "25",
      exp_name = "The Burning Lands",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Sky Orchid Understanding",
      loc = { y = 37.0, x = -275.0, z = 0.0 },
      triggers = {
        "Hail, Sky Orchid Understanding",
        "continue",
        "Hail, Dirgeful Ruby Blade",
        "reason",
        "available",
        "ready",
        "Hail, Heart of Flawless Brass",
        "What would you like in exchange ?",
      },
      items_required = {
        { name = "him the Windseal", count = 1 },
        { name = "up something of [value to him]", count = 1 },
        { name = "her the Golden Ruby and Garnet Ring", count = 1 },
      },
      rewards = {
        { id = 134608, name = "Golden Ruby and Garnet Ring", type = "item" },
        { id = 134797, name = "Windseal", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Esianti: Palace of the Winds [zone=1211]\n**Who:**\n- Sky Orchid Understanding [ _Seneschal of Esianti_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Success Lockout Timer**: 00:30:00\n**Quest Items:**\n- Golden Ruby and Garnet Ring [item=134608]\n- Windseal [item=134797]\n**Related Zones:**\n- Aalishai: Queen's Chambers [zone=1227]\n- Esianti: Audience with a King [zone=1228]\n**Related Creatures:**\n- Dirgeful Ruby Blade [ _Seneschal of Flames_]\n- Heart of Flawless Brass [npc=54585]\n- Moon Serf of Harmonious Heavens [npc=54586]\n**Related Quests:**\n- All Hail the King [quest=9267]\n- Brass Palace [quest=9445]\n- Contract of War [quest=9446]\n- Fight Fire [quest=9263]\n- Key to the Kingdom [quest=9264]\n- Palace of Embers [quest=9433]\n- Prisoner's Dilemma [quest=9265]\n- Soldier of Air [quest=9225]\n- Trial of Three (Trial of Smoke) [quest=9281]\n- Trial of the Ashes of Rusted Cliff's Glory (Trial of Smoke) [quest=9335]\n- Trial of the Eternal Cyclone (Trial of Smoke) [quest=9336]\n- Trial of the Speaker's Amphitheater (Trial of Smoke) [quest=9282]\n- Trial of the Wending Ways (Trial of Smoke) [quest=9337]\n**Era:** | !The Burning Lands\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 4 04:48:35 2018\nModified: Tue Dec 5 05:21:04 2023 | | Prerequisite Quests: Soldier of Air, Fight Fire, and any one of the Trials of Smoke, Prisoner's Dilemma, Place of Embers, Brass Palace, Key to the Kingdom, Contract of War, and All Hail the King.\nSpeak to Sky Orchid Understanding in Esianti: Palace of the Winds in the center of the city in the middle of the zone.\nYou say, 'Hail, Sky Orchid Understanding'\nSky Orchid Understanding says, 'You are even more of a nuisance than the councilors. If you are here to [continue] your crusade, you know what you need to do.'\nYou say, 'continue'\nYou have been assigned the task 'Royal Visits'.\nSky Orchid Understanding says, 'You must obtain ascent from the queen of the efreeti before you can have your resolution to the war. Even then, I must warn you that these things take time. Take this, it might allow you to get a meeting with her.'\nShe gives you Windseal.\n\n---\n\n3. Get access to the queen of the efreeti. 0/1 Aalishai: Palace of Embers\n\n\n\n\n\n> **Task Window:** Sky orchid Understanding suggested that you should try to gain ascent to end the war from the queen of the efreeti, Heart of Flawless Brass. She gave you some sort of token that might allow you to get a meeting.\n>\n> If the king has a seneschal, the queen probably does too. See if you can find who that is and get a meeting with the Heart of Flawless Brass.\n\n\n\nGo inside the palace at loc +37, -275 in the corner next to Dirgeful Ruby Blade, so you won't aggro mobs nearby.\n\n\n\nYou say, 'Hail, Dirgeful Ruby Blade'\n\n\n\n\nDirgeful Ruby Blade says, 'Get out of the throne room immediately! You have no [reason] nor right to be here!'\n\n\n\n\nYou say, 'reason'\n\n\n\n\nDirgeful Ruby Blade says, 'Reasons in your tiny mortal mind are not reason enough.'\n\n\n\n\nGive him the Windseal.\n\n\n\nYour task 'Royal Visits' has been updated.\n\n\n\n\nDirgeful Ruby Blade looks carefully at the token you have given him. 'A mortal, with the Windseal? Will wonders never cease? I will arrange a meeting for you. Speak with me later and I shall see if the queen is [available].'\n\n\n\n\nYou say, 'available'\n\n\n\n\nDirgeful Ruby Blade says, 'Yes, I can grant you only a few minutes. I will escort you in to see her when you are [ready].'\n\n\n\n\nYou say, 'ready'\n\n\n\n\nDirgeful Ruby Blade says, 'Be swift, do not waste the queen's time.'\n\n\n\n\nYou have entered Aalishai: Queen's Chambers.\n\n4. Speak with Heart of Flawless Brass and convince her to stop the war. 0/1 Aalishai: Palace of Embers\n\n\n\n\n\n> **Task Window:** Convincing Heart of Flawless Brass to agree to stop the war. Undoubtedly, as you have discovered from your experience with your jann as a whole, she will want something in exchange for her cooperation. See if you can find out what this is.\n\n\n\nYou say, 'Hail, Heart of Flawless Brass'\n\n\n\n\nHeart of Flawless Brass says, 'So, mortals come even to my very court, bearing a seal from the king of the djinn even. Very well, I have granted you some of my time. Be quick and tell me what you seek.'\n\n\n\n\nYou say, 'What would you like in exchange ?'\n\n\n\n\nHeart of Flawless Brass says, 'No, of course you would not know what I desire. You surely must know that anything I desire that I cannot simply gain on my own would be far beyond your ability to acquire. It's not as if you could...' she offers a wicked, twisted grin. 'It's not as if you could waltz into the castle in Aalashia and ask the current king of the djinn to give up something of [value to him]. That would be very amusing, and perhaps even worth what you have asked.'\n\n\n\n\nYou say, 'value to him'\n\n\n\n\nYour task 'Royal Visits' has been updated.\n\n\n\n\nHeart of Flawless Brass says, 'Yes, it would have to be something he would not want to part with. After all, you mortals are always seeking epic adventures, are you not? I admit that I have something in mind. He will never part with it, he greatly over values such things. Recover from him a muhbis for me, and I will do as you ask. It is a jeweled ring, with garnets and rubies. He will know which it is. Bring that to me and I will find a way to end the war. Until then, do not return to my palace! Get out, the door will take you out of my palace.'\n\n5. Speak with Moon Serf of the Harmonious Heavens and try to obtain the muhbis. 0/1 Esianti: Palace of the Winds\n\n\n\n\n\n> **Task Window:** You must go back to Esianti and see if you can speak with Moon Serf of Harmonious Heavens and get the muhbis that the efreeti queen wants.\n\n\n\nGo back to Sky Orchid Understanding in Esianti.\n\n\n\nYou say, 'Hail, Sky Orchid Understanding'\n\n\n\n\nSky Orchid Understanding says, 'An audience with the king can be arranged, if the need is great. Be clear, however, that your privilege is not unlimited. Tell me when you are [available] and I will see if the king can make time for you.'\n\n\n\n\nYou say, 'available'\n\n\n\n\nSky Orchid Understanding says, 'He can see you, but you must be brief. When you are [ready] I shall send you into the chamber.'\n\n\n\n\nYou say, 'ready'\n\n\n\n\nSky Orchid Understanding says, 'Be respectful or you will gain little.'\n\n\n\n\nYou have entered Esianti: Audience with a King.\n\n6. Deliver the muhbis to the efreeti queen. Aalishai: Palace of Embers\n\n\n\n\n\n> **Task Window:** ?\n\n\n\nYou say, 'Hail, Moon Serf of Harmonious Heavens'\n\n\n\n\nMoon Serf of Harmonious Heavens says, 'I remember you. You are the mortal that assisted me with some minor task. What is it that you have come here for?'\n\n\n\n\nYou say, 'I came for a ring with garnets and rubies muhbis please'\n\n\n\n\n_If you get no response, zone back out and then speak to Sky Orchid Understanding again to be ported back into the instance. Then speak with Moon Serf of Harmonious Heavens again._\n\n\n\nYour task 'Royal Visits' has been updated.\n\n\n\n\nMoon Serf of Harmonious Heavens says, 'You wish, what? This is the thing I must offer in order to have peace? You can never understand the cost I paid for that, or whom it contains.' Moon Serf of Harmonious Heavens pauses and considers. When he speaks again he seems resigned. 'I shall pay the price, though the cost to me is nothing compared to the cost to the one inside the ring. Be wary of this muhbis, for it contains a clever and dangerous creature, far too complex for a mortal to deal with. Once it is in your hands you must begone from here. I do not wish to see you again. Leave through the door and do not return.'\n\n\n\n\nYou receive Golden Ruby and Garnet Ring [item=134608].\n\n\n\nHead back to Aalishai; Queen's Chambers for another audience with the queen.\n\n\n\nYou say, 'Hail, Heart of Flawless Brass'\n\n\n\n\nHeart of Flawless Brass says, 'Ah, you have returned to report failure and beg me to end our contract. I could be induced to do so, should you be able to provide me something worthwhile.'\n\n\n\n\nGive her the Golden Ruby and Garnet Ring.\n\n\n\nHeart of Flawless Brass says, 'What, you have the muhbis? Well, that is indeed a surprise. Either you mortals are smarter than you seem, or Moon Serf of Harmonious Heavens has grown weak. I am certain it is the latter. I shall honor my end of the contract, the war shall end, eventually.' the queen smiles wryly, 'as promised.'\n\n\n\n\n\n\n\n---\n\n\n\n\nReward(s):\n\n\n212 platinum 5 gold\n\n\nYou gain experience!\n**Submitted by:** Gidono\n- 212 pp, 5 gold, Experience",
    },
    {
      id = "9449",
      title = "Armor of Acrophobia",
      exp = "25",
      exp_name = "The Burning Lands",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Unknown",
      loc = { y = -796.0, x = -1078.0, z = -20.0 },
      triggers = {
        "Hail, Phibbit",
        "armors",
        "Free them?",
        "Crag",
        "Swell",
        "Brume",
        "Pyre",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Status: Incomplete**\n\nQuest Started By: | Description:\n**Where:**\n- Esianti: Palace of the Winds [zone=1211]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Money\n**Related Creatures:**\n- a crag armor - Esianti [npc=54242]\n**Related Quests:**\n- Brass Palace [quest=9445]\n- Fight Fire [quest=9263]\n- Key to the Kingdom [quest=9264]\n- Palace of Embers [quest=9433]\n- Prisoner's Dilemma [quest=9265]\n**Era:** | !The Burning Lands\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 4 16:13:21 2018\nModified: Tue Dec 5 05:21:04 2023 | | Prerequisite Quests: Soldier of Air, Fight Fire, any one Trial of Smoke, Prisoner's Dilemma, Palace of Embers, Brass Palace, and Key to the Kingdom.\nThis task starts with Phibbit in Esianti at -796, -1078, -20 in the building in the southeast portion of the zone. He is on the find tool.\nYou say, 'Hail, Phibbit'\nPhibbit says, 'Oh! A fellow traveler of Esianti! How happy am I to see you! The air is pretty thin up here and I was worried that you were a trick of the mind when I saw you approach. One of the things you may have noticed up here, as well with other areas of the jann, is the [armors] that patrol each plane.'\nYou say, 'armors'\nPhibbit says, 'Yes, they imbue the armor with elementals, trapping them inside and removing free will from them. While this works on a 'undying loyalty' level, it's absolutely harrowing to the elemental trapped inside. However, I have a plan that I have concocted that will [free: Free them?] them from their posts.'\nYou say, ' Free them?'\nPhibbit says, 'It may not be the most eloquent of plans, but each elemental can be freed by dismantling the armor. Which armor do you want to help? [Crag], [Swell], [Brume], or [Pyre].'\nYou say, 'Crag'\nYou have been assigned the task 'Armor of Acrophobia'.\nPhibbit says, 'The crag armors are in special need of assistance as the earth elementals trapped inside are terrified of heights. You will be doing them a blessing.'\n\n---\n\n3. Free Crag Armors 0/4 Esianti: Palace of the Winds\n\nKill crag armors, found throughout the South West section of the zone\n\n\n\n\n**Task Window:** Free the crag armors from their existence on this plane. The unease of not being close to the ground has been causing them great distress.\n\n4. Return to Phibbit 0/1 Esianti: Palace of the Winds\n\nReturn to and Hail Phibbit\n\n**(We need missing steps, dialogue and task window text.)**\n\n---\n\nReward(s):\n212 pp, 5 gold\n**Submitted by:** Gidono\n- 212 pp, 5 gold",
    },
    {
      id = "9450",
      title = "Not as Swell as You Would Think",
      exp = "25",
      exp_name = "The Burning Lands",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Phibbit",
      loc = { y = -796.0, x = -1078.0, z = -20.0 },
      triggers = {
        "Hail, Phibbit",
        "armors",
        "Free them?",
        "Swell",
        "_Quests_",
        "Crag",
        "Brume",
        "Pyre",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Status: Incomplete**\n\nQuest Started By: | Description:\n**Where:**\n- Esianti: Palace of the Winds [zone=1211]\n**Who:**\n- Phibbit [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Money\n**Related Creatures:**\n- a swell armor [npc=54265]\n**Related Quests:**\n- Brass Palace [quest=9445]\n- Fight Fire [quest=9263]\n- Key to the Kingdom [quest=9264]\n- Palace of Embers [quest=9433]\n- Prisoner's Dilemma [quest=9265]\n- Soldier of Air [quest=9225]\n- Trial of Three (Trial of Smoke) [quest=9281]\n- Trial of the Ashes of Rusted Cliff's Glory (Trial of Smoke) [quest=9335]\n- Trial of the Eternal Cyclone (Trial of Smoke) [quest=9336]\n- Trial of the Speaker's Amphitheater (Trial of Smoke) [quest=9282]\n- Trial of the Wending Ways (Trial of Smoke) [quest=9337]\n**Era:** | !The Burning Lands\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 4 16:31:28 2018\nModified: Tue Dec 5 05:21:04 2023 | | Prerequisite Quests: Soldier of Air, Fight Fire, any one Trial of Smoke, Prisoner's Dilemma, Palace of Embers, Brass Palace, and Key to the Kingdom.\nThis task starts with Phibbit in Esianti at -796, -1078, -20 in the building in the southeast portion of the zone. He is on the find tool.\nYou say, 'Hail, Phibbit'\nPhibbit says, 'Oh! A fellow traveler of Esianti! How happy am I to see you! The air is pretty thin up here and I was worried that you were a trick of the mind when I saw you approach. One of the things you may have noticed up here, as well with other areas of the jann, is the [armors] that patrol each plane.'\nYou say, 'armors'\nPhibbit says, 'Yes, they imbue the armor with elementals, trapping them inside and removing free will from them. While this works on a 'undying loyalty' level, it's absolutely harrowing to the elemental trapped inside. However, I have a plan that I have concocted that will [free: Free them?] them from their posts.'\nYou say, ' Free them?'\nPhibbit says, 'It may not be the most eloquent of plans, but each elemental can be freed by dismantling the armor. Which armor do you want to help? [Crag], [Swell], [Brume], or [Pyre].'\nYou say, 'Swell'\nYou have been assigned the task 'Not as Swell as You Would Think'.\nPhibbit says, 'The swell armors seem to be coming more plentiful since the tensions between the jann has been rising. This could be prove to be disastrous for keeping the balance on Esianti. Making their numbers more even with the others will be beneficial to all here...except the swell armors, I guess.'\n\n---\n\n3. Destroy Swell Armors 0/4 Esianti: Palace of Embers\n\nKill swell armors, found throughout the Eastern section of the zone\n\n\n\n\n**Task Window:** The amount of swell armors in Esianti is higher than usual. Make sure that their numbers match up with the other armors.\n\n4. Return to Phibbit 0/1 Esianti: Palace of the Winds\n\nReturn to and Hail Phibbit\n\n\n---\n\nReward(s):\n212pp, 5 gold\n**Submitted by:** Gidono\n- 212 pp, 5 gold",
    },
    {
      id = "9451",
      title = "Beyond the Ex-pyre-ation Date",
      exp = "25",
      exp_name = "The Burning Lands",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Phibbit",
      loc = { y = -796.0, x = -1078.0, z = -20.0 },
      triggers = {
        "Hail, Phibbit",
        "armors",
        "Free them?",
        "Pyre",
        "_Quests_",
        "Crag",
        "Swell",
        "Brume",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "**Status: Incomplete**\n\nQuest Started By: | Description:\n**Where:**\n- Esianti: Palace of the Winds [zone=1211]\n**Who:**\n- Phibbit [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Money\n**Related Creatures:**\n- a pyre armor [npc=54247]\n**Related Quests:**\n- Brass Palace [quest=9445]\n- Fight Fire [quest=9263]\n- Key to the Kingdom [quest=9264]\n- Palace of Embers [quest=9433]\n- Prisoner's Dilemma [quest=9265]\n- Soldier of Air [quest=9225]\n- Trial of Three (Trial of Smoke) [quest=9281]\n- Trial of the Ashes of Rusted Cliff's Glory (Trial of Smoke) [quest=9335]\n- Trial of the Eternal Cyclone (Trial of Smoke) [quest=9336]\n- Trial of the Speaker's Amphitheater (Trial of Smoke) [quest=9282]\n- Trial of the Wending Ways (Trial of Smoke) [quest=9337]\n**Era:** | !The Burning Lands\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 4 23:18:45 2018\nModified: Tue Dec 5 05:21:04 2023 | | Prerequisite Quests: Soldier of Air, Fight Fire, any one Trial of Smoke, Prisoner's Dilemma, Palace of Embers, Brass Palace, and Key to the Kingdom.\nThis task starts with Phibbit in Esianti at -796, -1078, -20 in the building in the southeast portion of the zone. He is on the find tool.\nYou say, 'Hail, Phibbit'\nPhibbit says, 'Oh! A fellow traveler of Esianti! How happy am I to see you! The air is pretty thin up here and I was worried that you were a trick of the mind when I saw you approach. One of the things you may have noticed up here, as well with other areas of the jann, is the [armors] that patrol each plane.'\nYou say, 'armors'\nPhibbit says, 'Yes, they imbue the armor with elementals, trapping them inside and removing free will from them. While this works on a 'undying loyalty' level, it's absolutely harrowing to the elemental trapped inside. However, I have a plan that I have concocted that will [free: Free them?] them from their posts.'\nYou say, ' Free them?'\nPhibbit says, 'It may not be the most eloquent of plans, but each elemental can be freed by dismantling the armor. Which armor do you want to help? [Crag], [Swell], [Brume], or [Pyre].'\nYou say, 'Pyre'\nYou have been assigned the task 'Beyond the Ex-pyre-ation Date'.\nPhibbit says, 'Pyre armors are becoming more and more aggressive towards mortals. Let us take a quick moment to remind them that we refuse to let them bully us around.'\n\n---\n\n3. Rough up Pyre Armors 0/4 Esianti: Palace of the Winds\n\nKill pyre armors, found throughout the North West section of the zone\n\n\n\n\n**Task Window:** Remind the pyre armors in Esianti that there are more pressing matters happening than bullying mortals.\n\n4. Return to Phibbit 0/1 Esianti: Palace of the Winds\n\nReturn to and Hail Phibbit\n\n\n\n\n**Task Window:** ?\n\n**(We need all dialogue, and task window text.)**\n\n---\n\nReward(s):\n212 pp, 5 gold\n**Submitted by:** Gidono",
    },
    {
      id = "9453",
      title = "Serving Another Master",
      exp = "25",
      exp_name = "The Burning Lands",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Obsidian Sundering Master",
      loc = nil,
      triggers = {
        "Hail, Obsidian Sundering Master",
        "Mearatas",
        "can do",
        "Hail, Silent Sun",
        "where is Ghost Ruby?",
        "ruined",
        "lesson",
        "spot",
      },
      items_required = {
        { name = "you a name if you [can do] something for me", count = 1 },
        { name = "you what you need", count = 1 },
        { name = "her what she wants", count = 1 },
        { name = "you a location where you can find him", count = 1 },
        { name = "the head of Ghost Ruby to Silent Sun", count = 1 },
        { name = "Ghost Rubyâ€™s head to Silent Sun", count = 1 },
      },
      rewards = {
        { id = 134801, name = "Dark Ruby Muhbis", type = "item" },
        { id = 134802, name = "Elegent Note", type = "item" },
        { id = 134653, name = "Head of Ghost Ruby", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Esianti: Palace of the Winds [zone=1211]\n**Who:**\n- Obsidian Sundering Master [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Success Lockout Timer**: 03:16:00\n**Quest Items:**\n- Dark Ruby Muhbis [item=134801]\n- Elegent Note [item=134802]\n- Head of Ghost Ruby [item=134653]\n**Related Creatures:**\n- Ghost Ruby [npc=54597]\n- Silent Sun [npc=54239]\n**Related Quests:**\n- All Hail the King [quest=9267]\n- Brass Palace [quest=9445]\n- Contract of War [quest=9446]\n- Enter Mearatas [quest=9444]\n- Fight Fire [quest=9263]\n- Key to the Kingdom [quest=9264]\n- Palace of Embers [quest=9433]\n- Prisoner's Dilemma [quest=9265]\n- Royal Visits [quest=9448]\n- Soldier of Air [quest=9225]\n- Trial of Three (Trial of Smoke) [quest=9281]\n- Trial of the Ashes of Rusted Cliff's Glory (Trial of Smoke) [quest=9335]\n- Trial of the Eternal Cyclone (Trial of Smoke) [quest=9336]\n- Trial of the Speaker's Amphitheater (Trial of Smoke) [quest=9282]\n- Trial of the Wending Ways (Trial of Smoke) [quest=9337]\n- Tyrant of Fire [quest=9463]\n**Era:** | !The Burning Lands\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Dec 5 00:34:05 2018\nModified: Tue Dec 5 05:21:04 2023 | | **Prerequisite Quests:** Soldier of Air, Fight Fire, and any one of the Trails of Smoke, Prisoner's Dilemma, Palace of Embers, Brass Palace, Key to the Kingdom, Contract of War, All Hail the King, Royal Visits, Tyrant of Fire, and Enter Mearatas.\nSpeak to Obsidian Sundering Master in Esianti on the far north side of the zone and up the ramp. She is on the find tool.\nThis is a shared task.\nYou say, 'Hail, Obsidian Sundering Master'\nObsidian Sundering Master says, 'You do seem to like the view here. Or perhaps it's my company? No, no, you are here because you want something. I do remember asking you to do a task for me to learn about entry to [Mearatas]. Did you [forget] the name I gave you earlier?'\nYou say, 'Mearatas'\nObsidian Sundering Master says, 'There is one that might be able to help you. I know this one, and can give you a name if you [can do] something for me.'\nYou say, 'can do'\nObsidian Sundering Master says, 'Well, what I wish is simple, all you have to do is ask.'\nYou have been assigned the task 'Serving Another Master'.\n\n---\n\n1\\. Speak with Obsidian Sundering Master 0/1 Esianti: Palace of the Winds\n**Task Window:** You pursue the task set upon you by Fenning Ro. To do that you must get into Mearatas. You have learned that thee is a djinn called Obsidian Sundering Master that could have a way for you to get in.\nFind and speak to Obsidian Sunder Master. Find a way to gain the information you need.\nYou say, 'Hail, Obsidian Sundering Master'\nObsidian Sundering Master says, 'You have arrived. Don't be shocked, it is my job to know as much as I can. So you want to get into the great Stone Demesne. You know there is no way the duende will let you in. They are not much for social interactions, especially with mortals. Everyone has issues accessing Mearatas, to be fair. I can help you, but this is a big favor you wish. I would have to risk a contact that I would rather keep. So I must ask you to bring me something that I very much desire. Find Silent Sun. Recover from her a muhbis, she will know which. Bring that to me and I will give you what you need, if you are clever, to get into Mearatas.'\nYour task 'Serving Another Master' has been updated.\n2\\. Speak with Silent Sun 0/1 Esianti: Palace of the Winds\n**Task Window:** Silent Sun has a muhbis that Obsidian Sundering Master appears to value highly. Speak with her and see if you can get it from her.\nYou say, 'Hail, Silent Sun'\nSilent Sun says, 'So, that beast wants White Skies. She can't even come here herself, she has to send mortals to ask. I have been angry with her for a very long time. I still am. I wanted White Skies to choose me, or at least choose. I guess part of why we love him is his ability to love so readily. So Obsidian Sundering Master and I tried to destroy each other over him. But I understand now that we were manipulated. We were horrible to each other, certainly, but we may have remained friends if not for the interference of Ghost Ruby. I don't appreciate that she could not come here to talk in person, but if you get the revenge I desire, I will give her what she wants.'\nYour task 'Serving Another Master' has been updated.\n3\\. Find the being called Ghost Ruby 0/1 Esianti: Palace of the Winds\n**Task Window:** Ghost Ruby seems to be some sort of dangerous agent who takes on tasks involving using his clever mind to destroy targets, taking them out of whatever picture his queen is painting. Somehow a djinn called White Skies became part of his schemes and was trapped in a muhbis while SIlent Sun and Obsidian Sundering Master were torn apart. Finding the elusive Ghost Ruby may be a challenge. You will have to find someone willing to risk his anger. It will probably have to be an efreeti or one of their servants or you will have no reason to trust any information you may recover. At the same time, the efreeti and their kin have to learn to trust you, and the only way to do that is by doing violence to other jann.\nAsk NPC's in the NW part: \"where is Ghost Ruby?\" They may give you a location where you can find him.\n> A pyre armor judges you amiably -- looks like it would wipe the floor with you! (Lvl: 112)\n>\n> You say, 'where is Ghost Ruby?'\n>\n> A pyre armor says, 'Don't speak to me of that... creature! He has [ruined] so many under the guise of protecting the queen!'\n>\n> You say, 'ruined'\n>\n> A pyre armor says, 'He decides, based on a whim, who is guilty and who is not. Then he makes them look guilty. A close friend of mine was one of his victims. He decided that he didn't like something he said and so he told the king that my friend had signed a contract with an ondine to help them access the palace to kill the queen! I haven't seen my friend since. I would love to teach that Ghost Ruby a [lesson].'\n>\n> You say, 'lesson'\n>\n> A pyre armor says, 'I don't know, maybe set him up with one of his own tricks. Maybe I tell him a secret, like that some efreeti are going to help some mortals kill someone or something like that. Then you just wait at the [spot] until Ghost Ruby shows up to identify the traitors, and you kill him. It's the only way to get the coward to come out of hiding, tempt him with the opportunity to destroy the lives of an efreeti or two.'\n>\n> You say, 'spot'\n>\n> A pyre armor says, 'I'll tell him that the meeting is taking place in the ravine on the northern side of Esianti. Don't \\*\\*\\*\\*\\* this up, you're risking my life as much as yours. Now leave. I will not acknowledge that we ever spoke.'\n4\\. Defeat Ghost Ruby and take his head 0/1 Esianti: Palace of the Winds\nConfirmed spawn locations: -1010, -1370\nGhost Ruby's corpse drops to the earth.\nYou have slain Ghost Ruby!\n--\\_\\_\\_\\_\\_\\_ has looted a Head of Ghost Ruby.â€\"\n5\\. Give the head of Ghost Ruby to Silent Sun. 0/1 Esianti: Palace of the Winds\n**Task Window:** You have Ghost Ruby's head. Hopefully Silent Sun will honor her agreement, though honoring agreements appears to be integral to the nature of jann.\nTurn in Ghost Rubyâ€™s head to Silent Sun.\nSilent Sun says, 'You have succeeded. I thank you. Please give this muhbis to Obsidian Sundering Master along with this note.'\nYour task 'Serving Another Master' has been updated.\nYou get a Dark Ruby Muhbis. and an Elegant Note. Warning: the person who turns in the Ghost Ruby might not be the person who gets the Dark Ruby Muhbis.\n6\\. Deliver the Dark Ruby Muhbis to Obsidian Sundering Master 0/1 Esianti: Palace of the Winds\n**Task Window:** You have the muhbis with White Skies inside. Find Obsidian Sundering Master and exchange that gruesome totem for the information you seek.\nObsidian Sundering Master says, 'You... you have brought him to me. I didn't think it would happen, that she would allow him out of her grasp. Thank you so much for doing this for me.'\n7\\. Deliver the Elegant Note to Obsidian Sundering Master 0/1 Esianti: Palace of the Winds\n**Task Window:** Silent Sun asked you to deliver a message to Obsidian Sundering Master.\nObsidian Sundering Master says, 'I do not want a message from her.' Even as she speaks the words, she slides the note into her vest.'\nObsidian Sundering Master says, 'You should speak with Dirge in the Catacomb. If your mortal mind gets confused, return to me and I will give you the name again.'\nYour task 'Serving Another Master' has been updated.\nYou have been assigned the task ' Earthen Dirge [quest=9454]'.\nObsidian Sundering Master was shaken by the return of White Skies. She told you of a being called Dirge in the Catacombs. Dirge in the Catacombs appears to have established a magical portal into Mearatas. Whatever he is doing with that portal is certainly not something he wants others to know about. Confronting him about the portal and carefully threatening him with exposure should earn you a chance to gain passage.\n\n---\n\nReward(s):\n283 platinum 3 gold 3 silver 3 copper\nYou gain experience!\n**Submitted by:** Gidono\n- Platinum, Experience",
    },
    {
      id = "9454",
      title = "Earthen Dirge",
      exp = "25",
      exp_name = "The Burning Lands",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Obsidian Sundering Master",
      loc = { y = 1175.0, x = -510.0, z = 17.0 },
      triggers = {
        "Hail, Obsidian Sundering Master",
        "forget",
        "Hail, Dirge in the Catacomb",
        "I heard something about a portal?",
        "_Quests_",
        "Mearatas",
      },
      items_required = {
        { name = "you access to the duende castle", count = 1 },
        { name = "you", count = 1 },
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Esianti: Palace of the Winds [zone=1211]\n**Who:**\n- Obsidian Sundering Master [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Related Creatures:**\n- Dirge in the Catacomb [npc=54356]\n- Funereal Dust Warrior [npc=54332]\n**Related Quests:**\n- All Hail the King [quest=9267]\n- Brass Palace [quest=9445]\n- Contract of War [quest=9446]\n- Enter Mearatas [quest=9444]\n- Fight Fire [quest=9263]\n- Key to the Kingdom [quest=9264]\n- Palace of Embers [quest=9433]\n- Prisoner's Dilemma [quest=9265]\n- Royal Visits [quest=9448]\n- Serving Another Master [quest=9453]\n- Soldier of Air [quest=9225]\n- Trial of Three (Trial of Smoke) [quest=9281]\n- Trial of the Ashes of Rusted Cliff's Glory (Trial of Smoke) [quest=9335]\n- Trial of the Eternal Cyclone (Trial of Smoke) [quest=9336]\n- Trial of the Speaker's Amphitheater (Trial of Smoke) [quest=9282]\n- Trial of the Wending Ways (Trial of Smoke) [quest=9337]\n- Tyrant of Fire [quest=9463]\n**Era:** | !The Burning Lands\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Dec 5 21:02:24 2018\nModified: Tue Dec 5 05:21:04 2023 | | **Prerequisite Quests:** Soldier of Air, Fight Fire, and any one Trail of Smoke, Prisoner's Dilemma, Palace of Embers, Brass Palace, Key to the Kingdom, Contract of War, All Hail the King, Royal Visits, Tyrant of Fire, Enter Mearatas, and Serving Another Master.\nThis task starts with Obsidian Sundering Master at +1175, -510, +17 in Esianti on the far north edge of the zone, up the ramp. She is on the find tool.\nYou say, 'Hail, Obsidian Sundering Master'\nObsidian Sundering Master says, 'You do seem to like the view here. Or perhaps it's my company? No, no, you are here because you want something. I do remember asking you to do a task for me to learn about entry to [Mearatas]. Did you [forget] the name I gave you earlier?'\nYou say, 'forget'\nYou have been assigned the task 'Earthen Dirge'.\nObsidian Sundering Master sighs, 'Of course. You should seek Dirge in the Catacomb. He has a way in, all you need to do is convince him to let you use it.\n\n---\n\n1\\. Convince Dirge in the Catacomb to let you use his portal. 0/1 Esianti: Palace of the Winds\n> **Task Window:** You have been given a name of someone that might have access to Mearatas, Dirge in the Catacombs. You need to find him and convince him to give you access to the duende castle.\n>\n> You will probably have to carefully, manipulate Dirge in the Catacombs. Obsidian Sundering Master suggested that you use your relative fame among the djinn and the fact that you know Dirge in the Catacombs has set up a portal that he certainly should not have to your best advantage. Maybe threaten to tell other that you know about his secret entrance to Mearatas.\nYou say, 'Hail, Dirge in the Catacomb'\nDirge in the Catacomb looks over his nose down upon you. After a pause and with a sneer in his voice, 'A mortal, of course. We are infested with them. What must I do to get you to leave Esianti and never return? Not that I would trust you to leave no matter what I were to give you.'\nYou say, 'I heard something about a portal?'\nDirge in the Catacomb says, 'Should I find a way to get you into Mearatas and you were to be discovered, your presence would be a danger to me. However, should you find yourself in that place and discover the head of a duende called Funereal Dust Warrior and return it to my agent in the city, well then I might no longer be concerned. Someone that, even through no fault of their own, were to kill a duende in the city would have more to fear than anything they could cause to happen to me.'\nSay \"something\"\nYour task 'Earthen Dirge' has been updated.\nDirge in the Catacomb says, 'Should I find a way to get you into Mearatas and you were to be discovered, your presence would be a danger to me. However, should you find yourself in that place and discover the head of a duende called Funereal Dust Warrior and return it to my agent in the city, well then I might no longer be concerned. Someone that, even through no fault of their own, were to kill a duende in the city would have more to fear than anything they could cause to happen to me.'\n2\\. Defeat Funereal Dust Warrior and recover his head. 0/1 Mearatas: The Stone Demesne\n> **Task Window:** Your task seems simple but the djinn implied that he was asking you to do something that would put you at risk and give him leverage over you should you choose to reveal his secret.\nFunereal Dust Warrior is located in the north eastern section of Mearatas on the outside ring. Attack him.\nFunereal Dust Warrior says, 'You do not have a warrant to be here. I must end your poor mortal existence.'\nLoot Head of Funereal Dust Warrior from its corpse.\n3\\. Deliver 1 Head of Funereal Dust Warrior to Dirge in the Catacombs. 0/1 Esianti: Palace of the Winds\n> **Task Window:** Simply bring the head to Dirge in the Catacomb's assistant.\nGive Head of Funereal Dust Warrior to Dirge in the Catacombs.\n\n---\n\nReward(s):\n141 platinum 6 gold 6 silver 7 copper\nYou gain experience!\n**Submitted by:** Gidono\n- 141pp, 6g, 6s, 7cp, Experience",
    },
    {
      id = "9465",
      title = "Mold Seeker",
      exp = "25",
      exp_name = "The Burning Lands",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Obsidian Sundering Master",
      loc = { y = 525.0, x = -290.0, z = 0.0 },
      triggers = {
        "Hail, Obsidian Sundering Master",
        "mold seeker",
        "Hail, Battleworn Obelisk",
        "Would you show me the relics?",
        "_Quests_",
        "_Relic Keeper_",
        "Mearatas",
        "forget",
      },
      items_required = {
        { name = "you a hint", count = 1 },
        { name = "you access to our relics", count = 1 },
        { name = "access to the relics when appropriate", count = 1 },
      },
      rewards = {
        { id = 134609, name = "Key of the Relic Keeper", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Esianti: Palace of the Winds [zone=1211]\n**Who:**\n- Obsidian Sundering Master [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n**Time Limit:** | 24:00:00\n**Quest Items:**\n- Key of the Relic Keeper [item=134609]\n**Related Creatures:**\n- Battleworn Obelisk [ _Relic Keeper_]\n**Related Quests:**\n- All Hail the King [quest=9267]\n- Brass Palace [quest=9445]\n- Contract of War [quest=9446]\n- Earthen Dirge [quest=9454]\n- Enter Mearatas [quest=9444]\n- Fight Fire [quest=9263]\n- Key to the Kingdom [quest=9264]\n- Palace of Embers [quest=9433]\n- Prisoner's Dilemma [quest=9265]\n- Royal Visits [quest=9448]\n- Serving Another Master [quest=9453]\n- Soldier of Air [quest=9225]\n- Trial of Three (Trial of Smoke) [quest=9281]\n- Trial of the Ashes of Rusted Cliff's Glory (Trial of Smoke) [quest=9335]\n- Trial of the Eternal Cyclone (Trial of Smoke) [quest=9336]\n- Trial of the Speaker's Amphitheater (Trial of Smoke) [quest=9282]\n- Trial of the Wending Ways (Trial of Smoke) [quest=9337]\n- Tyrant of Fire [quest=9463]\n**Era:** | !The Burning Lands\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Dec 5 23:11:52 2018\nModified: Tue Dec 5 05:21:04 2023 | | **Prerequisite Quests:** Soldier of Air, Fight Fire, and any one Trail of Smoke, Prisoner's Dilemma, Palace of Embers, Brass Palace, Key to the Kingdom, Contract of War, All Hail the King, Royal Visits, Tyrant of Fire, Enter Mearatas, Serving Another Master, and Earthen Dirge.\nObsidian Sundering Master [npc=54366] is located in Esianti: Palace of the Winds at /way +1175,-510,+17 on the far north edge of the zone, up the ramp.\nIf you're running this mission again, say \"key\" to Obsidian Sundering Master.\nOtherwise:\nYou say, 'Hail, Obsidian Sundering Master'\nObsidian Sundering Master says, 'You do seem to like the view here. Or perhaps it's my company? No, no, you are here because you want something. I do remember asking you to do a task for me to learn about entry to [Mearatas]. Did you [forget] the name I gave you earlier?'\nYou say, 'mold seeker'\nObsidian Sundering Master says, 'I have heard rumors of what the rebel efreeti hopes to do. So you are the agent of that change. That confirmation of the rumor has value to me, as well as connecting your face with all this. For that, I will give you a hint. Someone in Mearatas will know where that duende mold is kept. The worst that can happen is that you ask someone and they are offended and try to kill you. That should be something you are well used to dealing with. In a way I wish you luck. Should you succeed your name and face may become extremely valuable to me.'\nYou have been assigned the task 'Mold Seeker'.\n\n---\n\n1\\. Find out where the duende keep their unused female mold. 0/1 Mearatas: The Stone Demease\n> **Task Window :** Somewhere in this city you hope to find a mold in the shape of a female duende that you are expected to find and steal for Fennin Ro.\n>\n> See if anyone here will tell you where the duende mold is. There seems to be a good chance that this will upset some of the locals.\nHead to the North Eastern section and ask \"Where is the female duende mold?\" to mobs. Some will ignore you, others will attack.\nA granite envoy says, 'Our relics are not for you to discuss. You do not even belong here!\nEventually one will tell you where the duende mold is.\nA vekerchiki warrior says, 'If you have questions about our relics, speak with the relic keeper, not me.'\nYour task 'Mold Seeker' has been updated.\n2\\. Speak with the relic keeper and see if you can find out where the mold is kept. 0/1 Mearatas: The Stone Demease\n> **Task Window :** Find this relic keeper and see if it will show you the relics.\nBattleworn Obelisk [npc=54622] spawns at /loc 525,-290.\nYou say, 'Hail, Battleworn Obelisk'\nBattleworn Obelisk says, 'Hello, stranger. Odd, seeing you here. There are been so few mortals in Mearatas for such a very long time. If there are questions you have, I may be able to answer them. I am something of an historian, it is my task to watch over artifacts of our past and to know why they are important.'\nYou say, 'Would you show me the relics?'\nBattleworn Obelisk says, 'Hmm, I don't think I can give you access to our relics. It is my duty to guard the key and I am only to give access to the relics when appropriate. A few religious items must be present at some rituals. Some contracts need to be reviewed at times. Sometimes a historic criminal needs to be spoken with. All of these things happen with the delivery of an appropriate contract. I know you have no such contract, for no mortal ever will. I am afraid that I can not allow you into the relic chamber.'\nYour task 'Mold Seeker' has been updated.\n3\\. Get the relic keeper's key. 0/1 Mearatas: The Stone Demease\n> **Task Window :** You seem to have no other option.\nKill Battleworn Obelisk.\nBattleworn Obelisk says, 'So, you have done as asked. I admit surprise. As you are a mere mortal, must remind you that what you have done puts you in danger, should anyone find a need to report your actions to an Udex of the duende. So long as you keep that in mind, You shall have access to this portal, as promised.'\nBattleworn Obelisk's corpse avalanches to the ground.\nBattleworn Obelisk has been slain by \\_\\_\\_\\_\\_!\n4\\. Pick up the relic keeper's key. 0/1 Mearatas: The Stone Demease\nLoot the Key of the Relic Keeper [item=134609] to complete the task. It will be later used to trigger Relic Raider [quest=9462].\n\n---\n\nReward(s):\n141 platinum 6 gold 6 silver 7 copper\nYou gain experience!\n**Submitted by:** Larth, Veludeus\n- Platinum, Experience",
    },
  },
}
