-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Plane of Shadow (poshadow)
-- Total Quests: 13
-- ============================================================================

return {
  zone = "poshadow",
  zone_name = "Plane of Shadow",
  quests = {
    {
      id = "6823",
      title = "Loud Noises",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Xol Xorn",
      loc = { y = -1115.0, x = 1450.0, z = -60.0 },
      triggers = {
        "Hail, Xol Xorn",
        "What about the ancient constructs?",
        "I",
        "ancient constructs",
        "seed beetles",
        "restless spirits",
        "kill",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Shadow [zone=915]\n**Who:**\n- Xol Xorn [npc=43133]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Apr 17 17:15:23 2013\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with Xol Xorn ( map) in the Plane of Shadow at location -1115, 1450, -60 (in the battlefield area - the valley located just west of the zone-in area: findable with CTRL+F)._\n_Pre-Requisites:_\n\\- Level 85\n\\- No task requirements\nYou say, 'Hail, Xol Xorn'\nXol Xorn says 'Why did we have to set up camp here? Between the [ancient constructs] stomping around, the [seed beetles] stealing our supplies, and [restless spirits] battling non-stop, I have not been able to get one good night's rest.'\nYou say, 'What about the ancient constructs?'\nXol Xorn says 'Those infernal constructs stomp around day and night, and quite frankly it is driving me insane. If you could [kill] some of them for me, I would see to it that you will be rewarded.'\nYou say, 'I'll kill some'\nXol Xorn says 'You have my thanks, stranger. Return to me when you have thinned their numbers.'\nYou have been assigned the task 'Loud Noises'.\n\n---\n\nKill some ancient constructs 0/10 (Plane of Shadow)\nSpeak with Xol Xorn 0/1 (Plane of Shadow)\n_Rewards:_\nExperience\n112 platinum, 5 gold",
    },
    {
      id = "6824",
      title = "Kill the Vermin",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Xol Xorn",
      loc = { y = -1115.0, x = 1450.0, z = -60.0 },
      triggers = {
        "Hail, Xol Xorn",
        "Seed beetles?",
        "They must be stopped!",
        "ancient constructs",
        "seed beetles",
        "restless spirits",
        "stopped",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Shadow [zone=915]\n**Who:**\n- Xol Xorn [npc=43133]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Apr 17 17:15:49 2013\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with Xol Xorn ( map) in the Plane of Shadow at location -1115, 1450, -60 (in the battlefield area - the valley located just west of the zone-in area: findable with CTRL+F)._\n_Pre-Requisites:_\n\\- Level 85\n\\- No task requirements\nYou say, 'Hail, Xol Xorn'\nXol Xorn says 'Why did we have to set up camp here? Between the [ancient constructs] stomping around, the [seed beetles] stealing our supplies, and [restless spirits] battling non-stop, I have not been able to get one good night's rest.'\nYou say, 'Seed beetles?'\nXol Xorn says 'Seed beetles keep getting into our supplies and stealing our rations. They must be [stopped].'\nYou say, 'They must be stopped!'\nXol Xorn says 'Smash some beetles and return to me when you are done for your well-deserved reward.'\nYou have been assigned the task 'Kill the Vermin'.\n\n---\n\nKill some gleaming seed beetles 0/6 (Plane of Shadow)\nKill some shadowed seed beetles 0/6 (Plane of Shadow)\nSpeak with Xol Xorn 0/1 (Plane of Shadow)\n_Rewards:_\nExperience\n112 platinum, 5 gold",
    },
    {
      id = "6825",
      title = "Restless Spirits",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Xol Xorn",
      loc = { y = -1115.0, x = 1450.0, z = -60.0 },
      triggers = {
        "Hail, Xol Xorn",
        "Restless spirits?",
        "I will destroy some of them",
        "ancient constructs",
        "seed beetles",
        "restless spirits",
        "destroy",
      },
      items_required = {
        { name = "them the eternal rest they deserve", count = 1 },
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Shadow [zone=915]\n**Who:**\n- Xol Xorn [npc=43133]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Apr 17 17:16:15 2013\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with Xol Xorn ( map) in the Plane of Shadow at location -1115, 1450, -60 (in the battlefield area - the valley located just west of the zone-in area: findable with CTRL+F)._\n_Pre-Requisites:_\n\\- Level 85\n\\- No task requirements\nYou say, 'Hail, Xol Xorn'\nXol Xorn says 'Why did we have to set up camp here? Between the [ancient constructs] stomping around, the [seed beetles] stealing our supplies, and [restless spirits] battling non-stop, I have not been able to get one good night's rest.'\nYou say, 'Restless spirits?'\nXol Xorn says 'The spirits of light and darkness are locked in a hopeless war for all eternity on the Field of Lingering Flames. It's sad really. Perhaps you can [destroy] some of the spirits and give them the eternal rest they deserve.'\nYou say, 'I will destroy some of them'\nXol Xorn says 'The Field of Lingering Flames is just to the north of here. Return to me when you have destroyed some of the spirits and I will make sure you are compensated for your efforts.'\nYou have been assigned the task 'Restless Spirits'.\n\n---\n\nDefeat some vengeful spirits of darkness 0/5 (Plane of Shadow)\nDefeat some righteous spirits of light 0/5 (Plane of Shadow)\n_Note: The above mobs are found in the valley just west of the zone-in area (outside the palace)._\nSpeak with Xol Xorn 0/1 (Plane of Shadow)\n_Rewards:_\nExperience\n112 platinum, 5 gold",
    },
    {
      id = "6826",
      title = "I Hate Bats!",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Vil Xon Xe",
      loc = { y = -165.0, x = 10.0, z = -35.0 },
      triggers = {
        "Hail, Vil Xon Xe",
        "Those bats like you, don",
        "I will kill them!",
        "bats",
        "kill",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Shadow [zone=915]\n**Who:**\n- Vil Xon Xe [npc=43131]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Related Creatures:**\n- a bat - Plane of Shadow [npc=43276]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Apr 17 17:16:31 2013\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with Vil Xon Xe ( map) in the Plane of Shadow at -165, 10, -35 (outside the palace entrance: findable with CTRL+F)._\n_Pre-Requisites:_\n\\- Level 85\n\\- No task requirements\nYou say, 'Hail, Vil Xon Xe'\nVil Xon Xe ducks as you approach and swats at the air. 'These damn [bats] keep swooping down at me and getting tangled up in my hair! I hate bats!'\nYou say, 'Those bats like you, don't they?'\nVil Xon Xe says 'I'm sure you want to stroll about and take in the grandeur of the Plane of Shadow, but if you have the time could you [kill] some of these bats?'\nYou say, 'I will kill them!'\nVil Xon Xe says 'Thank you. I look forward to their being a few less bats fluttering around.'\nYou have been assigned the task 'I Hate Bats!'.\n\n---\n\nKill some bats 0/10 (Plane of Shadow)\nFind Vil Xon Xe's ring 0/1 (Plane of Shadow)\nSpeak with Vil Xon Xe 0/1 (Plane of Shadow)\n_Rewards:_\nExperience, 2% regular XP at level 100\n112 platinum, 5 gold",
    },
    {
      id = "6827",
      title = "Shadowy Lurkers",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Eoqua Din",
      loc = { y = 970.0, x = 3010.0, z = -18.0 },
      triggers = {
        "Hail, Eoqua Din",
        "Lurkers?",
        "I",
        "lurkers",
        "Kill",
      },
      items_required = {
      },
      rewards = {
        { id = 111105, name = "Shadowed Carp", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Shadow [zone=915]\n**Who:**\n- Eoqua Din [npc=43127]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Quest Items:**\n- Shadowed Carp [item=111105]\n**Related Creatures:**\n- a shadowy lurker [npc=43296]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Apr 17 17:16:50 2013\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with Eoqua Din ( map) in the Plane of Shadow (findable with CTRL+F), found at location 970, 3010, -18 (on one of the islands on the west side outside the palace)._\n_Pre-Requisites:_\n\\- Level 85\n\\- No task requirements\nYou say, 'Hail, Eoqua Din'\nEoqua Din blurts out what you believe to be Akhevan obscenities as you approach. 'Yes, what is it? Can't you see that I am busy trying to fish up some dinner? Who am I kidding? I am a horrible fisherman. Everytime I snag a shadowed carp, the [lurkers] come and steal it from my line.'\nYou say, 'Lurkers?'\nEoqua Din says 'Shadowy lurkers. They are horrible beasts who delight in torturing me by preventing me from catching my dinner. If they didn't terrify me, I would jump right into the water and rip the carp from their maws. You look pretty brave. [Kill] some of the lurkers, rip open their stomachs, and return a shadowed carp to me and I will make it worth your while.'\nYou say, 'I'll kill some of them'\nEoqua Din says 'I await your return; unless you get eaten alive by one of the lurkers.'\nYou have been assigned the task 'Shadowy Lurkers'.\n\n---\n\nKill some shadowy lurkers 0/6 (Plane of Shadow)\nLoot a shadowed carp from a shadowy lurker 0/1 (Plane of Shadow)\n_Note: Shadowy lurkers spawn in the water in the western part of the zone (outside the palace)._\nGive the shadowed carp to Eoqua Din 0/1 (Plane of Shadow)\nSpeak with Eoqua Din 0/1 (Plane of Shadow)\n_Rewards:_\nExperience\n112 platinum, 5 gold",
    },
    {
      id = "6828",
      title = "The Darkness",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Xilk the Exile",
      loc = { y = 1400.0, x = 1635.0, z = -16.0 },
      triggers = {
        "Hail, Xilk the Exile",
        "Darkness?",
        "darkness",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Shadow [zone=915]\n**Who:**\n- Xilk the Exile [npc=43132]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Apr 17 17:17:17 2013\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with Xilk the Exile ( map) in the Plane of Shadow (findable with CTRL+F). She is found at 1400, 1635, -16 (west side, outside the palace)._\n_Pre-Requisites:_\n\\- Level 85\n\\- No task requirements\nYou say, 'Hail, Xilk the Exile'\nXilk the Exile laughs uncontrollably as you near him. This Akhevan clearly is not in his right mind. 'Father? Is that you, father? You have been gone for so long. The pools made of [darkness]! They did this to us, father! They made you leave me! Kill them! Kill them all!'\nYou say, 'Darkness?'\nXilk the Exile says 'Always bubbling, always troubling, these creatures are. They hide in the tower, just behind me. Kill them, father! Kill them!'\nYou have been assigned the task 'The Darkness'.\n\n---\n\nKill some pools of darkness 0/6 (Plane of Shadow)\n_These are found throughout the lower halls of the palace._\nSpeak with Xilk the Exile 0/1 (Plane of Shadow)\n_Rewards:_\nExperience\n112 platinum, 5 gold",
    },
    {
      id = "6829",
      title = "Shadow \\#1: The Goddess, the Shard, and the Diabo",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Aten Ha Ra",
      loc = { y = 100.0, x = -1225.0, z = -55.0 },
      triggers = {
        "Hail, Aten Ha Ra",
        "What about the crystal shard?",
        "What pieces?",
        "I will locate him",
        "What about Diabo Va Xin Vellis?",
        "Hail, Kela Lor Telaris",
        "crystal shard",
        "pieces",
      },
      items_required = {
      },
      rewards = {
        { id = 110936, name = "Crystal Shard", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Shadow [zone=915]\n**Who:**\n- Aten Ha Ra [npc=43126]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Success Lockout Timer**: 06:00:00\n**Quest Items:**\n- Crystal Shard [item=110936]\n**Related Creatures:**\n- Kela Lor Telaris [npc=43129]\n- a corrupted Akhevan [npc=43277]\n- an Akhevan vagabond [npc=43302]\n**Related Quests:**\n- Breaking the Seal [quest=6832]\n- Dispelling the Shadows [quest=6833]\n- Shadow #2: Aten's Wrath [quest=6830]\n- Shadow #3: Dial L for Luclin [quest=6831]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Apr 17 17:42:40 2013\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a solo task and is the first task in a series of three. It begins with Aten Ha Ra ( map), findable with CTRL+F, who is found just inside the palace entrance._\n_Pre-Requisites:_\n\\- Level 85\n\\- No task requirements\nYou say, 'Hail, Aten Ha Ra'\nAten Ha Ra doesn't even look at you as she speaks 'Lumanes \\_\\_\\_\\_\\_ Something disastrous has occurred here. A strange [crystal shard] crashed into Vex Thal and pierced the veil to Vex Xi Va, the domain of my Goddess.' She turns her gaze fully upon you. 'The sanctity of this holy place has been defiled.'\nYou say, 'What about the crystal shard?'\nAten Ha Ra says 'This shard must have enormous power to force its way into the planes. Already its presence is changing Her domain in unexpected ways. I have tasked the Akhevans to find any [pieces] of this shard and remove it from the Plane of Shadow immediately. As Her holy servants, it is our duty to cleanse the home of our Goddess and seal the breach to Her domain.'\nYou say, 'What pieces?'\nAten Ha Ra says 'The crystal broke apart into many pieces upon entering Vex Xi Va. I have tasked my most trusted priest Diabo Va Xin Vellis to head our efforts to collect the shards and return them to me. However, it has been quite some time since he has reported back with shards and none of my priests have been able to [locate] him.'\nYou say, 'I will locate him'\nAten Ha Ra says 'You? You should not even be here! If it was not for this crisis, you would already be dead for defiling this place. Still, I must know how the cleanup is progressing and my people are spread thinly. I will allow you look for Diabo Va Xin Vellis. Should you find him, inform him he is to return immediately with the shards he has collected.'\nYou have been assigned the task 'The Goddess, the Shard, and the Diabo'.\nYou have been tasked by Aten Ha Ra to find Diabo Va Xin Vellis and instruct him to return with all the shards he has gathered.\n\n---\n\nSearch for Diabo Va Xin Vellis in the ancient battlefield 0/1 (Plane of Shadow)\n_This location update ( map) is findable via CTRL+F (this is the southwestern valley outside the palace)._\nAsk akhevan vagabonds in the area about Diabo Va Xin Vellis 0/1 (Plane of Shadow)\n_Akhevan vagabonds ( map) are found throughout the battlefield area. Say 'Diabo Va Xin Vellis' to one of them to update this step._\nYou say, 'What about Diabo Va Xin Vellis?'\nan Akhevan vagabond eyes you warily but somehow knows you have been sent by Aten Ha Ra. 'Yes, he was here many hours ago. After collecting all the shards in this area, he headed toward the Darkfire Islands.'\n\n---\n\nSearch for Diabo Va Xin Vellis at the darkfire islands 0/1 (Plane of Shadow)\n_This is a large update area ( map) in the western part of the outside area._\nAsk akhevan vagabonds in the area about Diabo Va Xin Vellis 0/1 (Plane of Shadow)\n_Akhevan vagabonds ( map) are found throughout the islands. Say 'Diabo Va Xin Vellis' to one of them to update this step._\nYou say, 'What about Diabo Va Xin Vellis?'\nan Akhevan vagabond looks at you with distrust as they answer,'Diabo Va Xin Vellis already collected all the shards which could be found here some time ago. He departed to speak with mercenary leader Kela Lor Telaris inside the temple. He has set up his command post at the top of the eastern root passage.'\n\n---\n\nEnter Luclin's Palace via the eastern root passage 0/1 (Plane of Shadow)\n_In the far eastern area outside the palace ( map) is a palace entrance. This updates around there (/loc 100, -1225, -55)._\nSpeak to Kela Lor Telaris about Diabo Va Xin Vellis 0/1 (Plane of Shadow)\n_Kela Lor Telaris ( map) is findable with CTRL+F. She is found in the far southeastern part of the palace (head up inside tree - he is in the first room)._\nYou say, 'Hail, Kela Lor Telaris'\nKela Lor Telaris says 'I do not have time to talk now, \\_\\_\\_\\_\\_. My mercenaries are being pressed hard by maddened akhevans. They seem to be stronger than I would have thought possible. We are barely holding our position in the chamber behind me.'\n\n---\n\nInvestigate the battle in the chamber to the north 0/1 (Plane of Shadow)\n_Head north ( map)._\nYou survey the carnage and quickly decide the mercenaries could use some help.\nKill 3 corrupted Akhevans 0/3 (Plane of Shadow)\n_Any three count towards this step. These range in level from 100-101 and are stunnable/mezzable._\na corrupted Akhevan says 'For Diabo Va Xin Vellis!'\na corrupted Akhevan has been slain by \\_\\_\\_\\_\\_!\na corrupted Akhevan's corpse violently crashes to the ground.\nObtain a crystal shard from a corrupted Akhevan 0/1 (Plane of Shadow)\n\n---\n\nReturn the crystal shard to Aten Ha Ra 0/1 (Plane of Shadow)\nAten Ha Ra listens intently, her face betraying no emotion as you relay your findings. 'I did not expect something like this could happen. These shards are more dangerous than I thought. We must find what has happened to Diabo Va Xin Vellis and recover the shards he collected.'\nYou were unable to locate Diabo Va Xin Vellis, but you did find a clue as to what may have happened to him.\n_Rewards:_\nExperience (3 AAs + 2% regular exp at Level 100)\n112 platinum, 5 gold",
    },
    {
      id = "6830",
      title = "Shadow \\#2: Aten's Wrath",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Aten Ha Ra",
      loc = nil,
      triggers = {
        "Hail, Aten Ha Ra",
        "What weakness?",
        "What mercenaries?",
        "I will deliver these orders",
        "Hail, Kela Lor Telaris",
        "weakness",
        "mercenaries",
        "delivering",
      },
      items_required = {
      },
      rewards = {
        { id = 110938, name = "Aten Ha Ra's Orders", type = "item" },
        { id = 110941, name = "Chest of Crystal Shards", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Shadow [zone=915]\n**Who:**\n- Aten Ha Ra [npc=43126]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Success Lockout Timer**: 06:00:00\n**Quest Items:**\n- Aten Ha Ra's Orders [item=110938]\n- Chest of Crystal Shards [item=110941]\n**Related Creatures:**\n- Kela Lor Telaris [npc=43129]\n- Zentha Lor Thall [npc=43309]\n- a corrupted Akhevan [npc=43277]\n**Related Quests:**\n- Breaking the Seal [quest=6832]\n- Dispelling the Shadows [quest=6833]\n- Shadow #1: The Goddess, the Shard, and the Diabo [quest=6829]\n- Shadow #3: Dial L for Luclin [quest=6831]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Apr 17 17:43:02 2013\nModified: Thu Feb 29 21:11:14 2024 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a solo task and is the second task in a series of three. It begins with Aten Ha Ra ( map), findable with CTRL+F, who is found just inside the palace entrance._\n_Pre-Requisites:_\n\\- Level 85\n\\- Completion of \"The Goddess, the Shard, and the Diabo\"\nYou say, 'Hail, Aten Ha Ra'\nAten Ha Ra is clearly displeased as she speaks, 'It seems these shards have a power that is able to corrupt the soul. Obviously they do not have this effect on everyone, so I must conclude this is a [weakness] inherent those who are affected.'\nYou say, 'What weakness?'\nAten Ha Ra raises her voice in anger, 'This weakness will not be tolerated! Those akhevans who fall to the power of these shards are not fit to live amongst our people. They must be purged and any shards they possess must be recovered!' Aten Ha Ra regains her composure. 'There is also the matter of Diabo Va Xin Vellis. We must know if he has been affected by the shards. The [mercenaries] may prove useful after all.'\nYou say, 'What mercenaries?'\nAten Ha Ra says 'Who better to conduct a purge than Kela Lor Telaris and his mercenaries? And since they have not yet succumbed to the power of the shards, they should be able to handle collecting them. \\_\\_\\_\\_\\_, you may continue to avoid my wrath by [delivering] these [orders] and assisting him in whatever way he may require.'\nYou say, 'I will deliver these orders'\nAten Ha Ra says 'A wise decision, \\_\\_\\_\\_\\_.' Aten Ha Ra fixes you with an icy stare 'I will not tolerate failure in this. Return with news of success or do not return at all.'\nYou have been assigned the task 'Aten's Wrath'.\nYou have been tasked by Aten Ha Ra to assist Kela Lor Telaris in eliminating the corrupt Akhevans and recovering any shards in their possession.\n\n---\n\nDeliver the orders to Kela Lor Telaris 0/1 (Plane of Shadow)\n_Kela Lor Telaris ( map) is findable with CTRL+F. He is found in the far southeastern part of the palace (head up inside tree - he is in the first room)._\nKela Lor Telaris reads over the orders. 'So that is what we must do. The corrupted akhevans have infested the area around Luclin's chambers. Chests of crystal shards are strewn about there as well. Go there, kill them, and bring back their shards. My mercenaries will attack on a different front than you with the same objective. Keep an eye out for signs of Diabo Va Xin Vellis.\n\n---\n\nKill 15 corrupted Akhevans 0/15 (Plane of Shadow)\n_Corrupted Akhevans are found all throughout the hallways in the upper levels of the zone, as well as in the chamber north of Kela Lor Telaris and in Luclin's chamber._\nCollect 5 chests of crystal shards 0/5 (Plane of Shadow)\n_These are ground spawns located in and all around Luclin's chamber ( map \\-\\- upper levels of the eastern part of the palace)._\n\n---\n\nInterrogate a corrupted Zentha Lor Thall priestess 0/1 (Plane of Shadow)\n_Kill \"Zentha Lor Thall\" ( map). One of these can be found in each of the hallways that extend out from the same area._\n_She hits for a max ~14,000 and doesn't have any special abilities. As she lowers in health, she will go on about Diabo Va Xin Vellis' plans:_\nZentha Lor Thall says 'You cannot stop Diabo Va Xin Vellis! He has ascended to a more powerful form through the power of the shards.'\nZentha Lor Thall says 'Very soon now he will be powerful enough to break the seal to Luclin's inner chamber, claiming the large shard that lies within.'\nZentha Lor Thall says 'He will then destroy Luclin and take her place as the ruler of this plane! If you oppose him, you too shall be destroyed.'\nZentha Lor Thall has been slain by \\_\\_\\_\\_\\_!\n\n---\n\nDeliver 5 chests of crystal shards to Kela Lor Telaris 0/5 (Plane of Shadow)\nYou can preloot the chests but you will have to give them to a merc or NPC to hand them back to you in order to get updates for this step.\nInform Kela Lor Telaris of what you have learned about Diabo Va Xin Vellis 0/1 (Plane of Shadow)\nYou say, 'Hail, Kela Lor Telaris'\nKela Lor Telaris says 'He is mad! Attempting to kill Luclin and become the God of Shadow? We must get to this large crystal shard before Diabo Va Xin Vellis and stop this insanity.'\nYou killed many corrupt akhevans and recovered their crystal shards, but Diabo Va Xin Vellis has already become powerful enough to challenge Luclin.\n_Rewards:_\nExperience (2-3% regular exp in Level 100 + 3 AAs)\n150 platinum",
    },
    {
      id = "6832",
      title = "Breaking the Seal",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Kela Lor Telaris",
      loc = nil,
      triggers = {
        "Hail, Kela Lor Telaris",
        "We will accompany you",
        "Let",
        "accompany",
        "depart",
      },
      items_required = {
      },
      rewards = {
        { id = 111152, name = "Triangulation Shard Delta", type = "item" },
        { id = 111123, name = "Triangulation Shard Epsilon", type = "item" },
        { id = 111114, name = "Triangulation Shard Gamma", type = "item" },
        { id = 111242, name = "Bestial Shoulderpads", type = "item" },
        { id = 111231, name = "Cloak of the North", type = "item" },
        { id = 111243, name = "Dulled Shissar Ulak", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Shadow [zone=915]\n**Who:**\n- Kela Lor Telaris [npc=43129]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Loot\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 06:00:00\n**Quest Items:**\n- Triangulation Shard Delta [item=111152]\n- Triangulation Shard Epsilon [item=111123]\n- Triangulation Shard Gamma [item=111114]\n**Related Zones:**\n- Plane of Shadow: Breaking the Seal [zone=919]\n**Related Creatures:**\n- Diabo Va Xin Vellis [npc=43403]\n- Kaas Thox [npc=43398]\n- Kela Lor Telaris [npc=43392]\n- Kela Va [npc=43404]\n- Kela Vas Strongbox [npc=43171]\n- Sealing Crystal [npc=43401]\n- The Dark Lady [npc=43402]\n- Volx Xi Xakra [npc=43397]\n- Xundraux Xakra [npc=43395]\n- Zel Kaxri [npc=43396]\n- a corrupted akhevan scout [npc=43394]\n- a crystal shard [npc=43400]\n- a pile of shadow [npc=43399]\n**Related Quests:**\n- Dispelling the Shadows [quest=6833]\n- Raid Expedition: Dispelling the Shadows [quest=6840]\n- Shadow #1: The Goddess, the Shard, and the Diabo [quest=6829]\n- Shadow #2: Aten's Wrath [quest=6830]\n- Shadow #3: Dial L for Luclin [quest=6831]\n- The Depths of Fear [quest=6924]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Apr 17 17:43:45 2013\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a group mission that begins with Kela Lor Telaris (findable with CTRL+F) who is found in the far southeastern part of the palace (head up inside tree - he is in the first room)._\n_For a visual of how to safely get to this area, see the image on this NPC entry [npc=43161]._\n_Pre-Requisites:_\n\\- Level 85\n\\- Completion of \"The Goddess, the Shard, and the Diabo\"\n\\- Completion of \"Aten's Wrath\"\n\\- Completion of \"Dial L for Luclin\"\nYou say, 'Hail, Kela Lor Telaris'\nKela Lor Telaris says 'We must find a way to break the seal on Luclin's Chamber before Diabo Va Xin Vellis can get to the shard! Your assistance thus far has been very helpful. I would like you to [accompany] me on this mission.'\nYou say, 'We will accompany you'\nKela Lor Telaris says 'Excellent. I will be glad to have you with me. Let me know when you are ready to [depart], but prepare quickly. We have no time to waste.'\nYou have been assigned the task 'Breaking the Seal'.\nYou have agreed to accompany Kela Lor Telaris in his attempt to break the seal on Luclin's chamber.\nYou say, 'Let's depart'\nKela Lor Telaris says 'Let us be off.'\nLOADING, PLEASE WAIT...\nYou have entered Plane of Shadow.\n\n---\n\nSpeak with Kela Lor Telaris 0/1 (Plane of Shadow)\nYou say, 'Hail, Kela Lor Telaris'\nKela Lor Telaris says 'Our first step should be to investigate the sealed doors more thoroughly and see if we can determine what type of magic is sealing them. Wait, did you hear something?'\nKela Lor Telaris says 'Over there on the stairs! Don't let him report back!'\n_This triggers the spawn of \"a corrupted akhevan scout\" on the stairs to the east._\nTry to kill the corrupted akhevan scout before he reports back 0/1 (Plane of Shadow)\n_You can either kill the scout or let him run off on his own (the step will update either way). If you kill it, the step simply updates:_\na corrupted Akhevan scout has been slain by \\_\\_\\_\\_\\_!\na corrupted Akhevan scout's corpse still clutches its sword.\n_If you let it go, you'll eventually see this, updating the step (Xundraux Xakra kills the scout):_\nXundraux Xakra shouts 'Fool! You led them right to me!'\n\n---\n\nKill Xundraux Xakra 0/1 (Plane of Shadow)\n_Xundraux Xakra ( map) casts \"Deathly Poison\" (DOT for 50,000/tick) on a random target every 25 seconds (viral to anyone in 40' range)._\nDeathly Poison: Single Target, Disease (-960)\n1: Decrease Hitpoints by 50000 per tick\n2: Decrease Endurance by 4000 per tick\n3: Increase Poison Counter by 90\nXundraux Xakra has been slain by \\_\\_\\_\\_\\_!\nXundraux Xakra's corpse lets out a deep sigh.\nSearch Xundraux Xakra for anything useful 0/1 (Plane of Shadow)\n_Loot a \"Triangulation Shard Gamma\" from its corpse._\nGive triangulation shard gamma to Kela Lor Telaris 0/1 (Plane of Shadow)\nYou hear the sound of furniture being knocked over in the room down the hall.\nKela Lor Telaris says 'Interesting, a triangulation crystal. They must be using a sealing crystal to lock these doors. If we can get the other two crystals, we will be able to locate the sealing crystal and destroy it. We should probably search outside the other two entrances to Luclin's chamber.'\n_This spawns Zel Kaxri and Volx Xi Xakra ( map), as well as Kaas Thox. (Kaas Thox is an optional kill, but killing it will generate an extra item in your loot chest.)_\n\n---\n\nKill Zel Kaxri 0/1 (Plane of Shadow)\n_Zel Kaxri casts \"Repel\" (with knockback) on a random target every 20 seconds._\nRepel: Single Target, Unresistable (0)\n1: Decrease Hitpoints by 40000\nZel Kaxri has been slain by \\_\\_\\_\\_\\_!\nZel Kaxri's corpse's face seems peaceful now.\nSearch Zel Kaxri for a triangulation shard 0/1 (Plane of Shadow)\n_Loot \"Triangulation Shard Delta\" from its corpse._\nGive triangulation shard delta to Kela Lor Telaris 0/1 (Plane of Shadow)\nKela Lor Telaris says 'Only one more to go.'\n\n---\n\nKill Volx Xi Xakra 0/1 (Plane of Shadow)\n_Every 30 seconds, Volx Xi Xakra buffs itself with \"Power of Fear\". Dispell this quickly because it AEs \"Shards of Fear\" if it fades naturally._\nVolx Xi Xakra has been slain by \\_\\_\\_\\_\\_!\nVolx Xi Xakra's corpse lies flat on the ground.\nSearch Volx Xi Xakra for a triangulation shard 0/1 (Plane of Shadow)\n_Loot \"Triangulation Shard Epsilon\" from its corpse._\nGive triangulation shard epsilon to Kela Lor Telaris 0/1 (Plane of Shadow)\nKela Lor Telaris says 'Now that we have all three, I can lead us to the location of the Sealing Crystal. Follow me!'\nFollow Kela Lor Telaris to the Sealing Crystal 0/1 (Plane of Shadow)\n\n---\n\nDestroy the Sealing Crystal 0/1 (Plane of Shadow)\n_NOTE: The task locks upon the Sealing Crystal's destruction._\n_This is located in the northwestern part of the palace ( map)._\n_Here, you will get adds called \"a crystal shard\" here. These are kiteable and should be range DPS'd (large damage aura on them). Kill the crystal to unlock the doors to Luclin's chamber._\n_Emotes you'll see here:_\nA shard of the sealing crystal breaks off. _(\"a crystal shard\" spawns and targets someone else.)_\nYou are being pursued by a crystal shard. Don't let it get close! _(\"a crystal shard\" spawns and targets you.)_\n_As the Sealing Crystal is destroyed, you see:_\nThe sealing crystal falls to pieces.\nA keening wail suddenly fills the air of the chamber, only to trail off moments later.\n_This also spawns Kela Va and The Dark Lady ( map). (The Dark Lady is an optional kill, but killing her will generate an extra item in your loot chest.)_\n\n---\n\n_Optional Kills:_\n_Kaas Thox hits for a max ~19,500 and spawns adds at 80%, 70%, 50%, and 20% (two per wave). These adds each have a melee slow aura (Sticky Tendrils) and cast a spell on random targets that flings the target to their location._\nKaas Thox has been slain by \\_\\_\\_\\_\\_!\nKaas Thox's corpse evaporates into a fetid mist.\n_The Dark Lady hits for a max ~19,500 and casts the emote-based \"Gaze of Shadows\" occurring at specific health intervals: 80%, 70%, 50%, and 20% (turn away from her when you see it)._\nThe Dark Lady turns her gaze upon you! You think it would be wise to avoid looking at her.\nThe Dark Lady turns her gaze away fro you.\nThe Dark Lady has been slain by \\_\\_\\_\\_\\_!\nThe Dark Lady's corpse collapses.\n\n---\n\nEnter Luclin's chamber 0/1 (Plane of Shadow)\nDiabo Va Xin Vellis shouts 'How resourceful of you to have broken my seal. If I was not otherwise occupied, I would destroy you myself. Kela Va will see to you in my place.'\nDefeat Kela Va 0/1 (Plane of Shadow)\n_Kela Va will hit the tank with \"Grim Siphon\" (single-target nuke for 40,000) which also increases her mana, which, when it hits 100%, causes her to AE \"Fearful Blast\" (AE nuke for 66,666)._\nKela Va has been slain by \\_\\_\\_\\_\\_!\nAs Kela Va falls to the ground, a small chest tumbles to the ground beneath her.\nClaim your reward from Kela Va's Strongbox 0/1 (Plane of Shadow)\nYou helped Kela Lor Telaris break the seal on Luclin's chamber so you could confront Diabo Va Xin Vellis and recover the large fear shard.\n_Rewards:_\nExperience (4 AAs + 3-4% regular exp at Level 100)\n300 platinum\n_Possible Chest Loot (1 Dreadmote + 1-3 Items Per Task):_\nBestial Shoulderpads\nCloak of the North\nDulled Shissar Ulak\nEffigy of the Scorned\nEye of the Hierophant\nNecklace of Dark Beauty\nPauldrons of Rage\nQuicksilver Globule\nSash of Mystic Rites\nShissar Overseer's Pauldrons\nShissar Scaled Shoulders\nSilver Cymbals\nStudly Stud\nSturdy Gorget\nMedian Dreadmote\nGreater Dreadmote\nGlowing Dreadmote\nThis also drops a \"Shifting Shard\" - used in the **Depths of Fear** [quest=6924] class-specific weapon achievement.\n- Bestial Shoulderpads [item=111242]\n- Cloak of the North [item=111231]\n- Dulled Shissar Ulak [item=111243]\n- Effigy of the Scorned [item=111232]\n- Eye of the Hierophant [item=110993]\n- Glowing Dreadmote [item=106497]\n- Greater Dreadmote [item=106464]\n- Median Dreadmote [item=106509]\n- Necklace of Dark Beauty [item=111197]\n- Pauldrons of Rage [item=111177]\n- Quicksilver Globule [item=110622]\n- Sash of Mystic Rites [item=111135]\n- Shifting Shard [item=56896]\n- Shissar Overseer's Pauldrons [item=111134]\n- Shissar Scaled Shoulders [item=111153]\n- Silver Cymbals [item=111265]\n- Studly Stud [item=111230]\n- Sturdy Gorget [item=111133]",
    },
    {
      id = "6833",
      title = "Dispelling the Shadows",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Kela Lor Telaris",
      loc = nil,
      triggers = {
        "Hail, Kela Lor Telaris",
        "I have a small group",
        "Let",
        "Ignite?",
        "Strife?",
        "Where is Luclin?",
        "We can defeat him",
        "Hail, Luclin",
      },
      items_required = {
        { name = "themselves unto obliteration", count = 1 },
      },
      rewards = {
        { id = 111270, name = "Buckle Belt\nShadow Woven Sash\nShifting Earring\nSoprano Stud\nSpiky Choker\nLesser Dreadmote\nMedian Dreadmote\nGreater Dreadmote\nGlowing Dreadmote\n- Carved Ivory Earring", type = "item" },
        { id = 106497, name = "Glowing Dreadmote", type = "item" },
        { id = 106464, name = "Greater Dreadmote", type = "item" },
        { id = 110979, name = "Hoop of the Grinning Skull", type = "item" },
        { id = 111157, name = "Iron Spike Ring", type = "item" },
        { id = 106476, name = "Lesser Dreadmote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Shadow [zone=915]\n**Who:**\n- Kela Lor Telaris [npc=43129]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Loot\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 06:00:00\n**Related Zones:**\n- Plane of Shadow: Dispelling the Shadows [zone=920]\n**Related Creatures:**\n- Bearer of Darkness [npc=43416]\n- Bearer of Light [npc=43415]\n- Diabo Va Xin Vellis [npc=43410]\n- Kela Lor Telaris [npc=43409]\n- Luclin [npc=43412]\n- Shadow of Luclin [npc=43418]\n- a chest - Dispelling the Shadows [npc=43172]\n- a dark vessel [npc=43413]\n- a light vessel [npc=43414]\n- an essence of shadow [npc=43417]\n**Related Quests:**\n- Champions of the People [quest=6822]\n- Valley of King Xorbb Event #3: The Return of King Xorbb [quest=6115]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Apr 17 17:44:33 2013\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a group mission that begins with Kela Lor Telaris (findable with CTRL+F) who is found in the far southeastern part of the palace (head up inside tree - she is in the first room)._\n_For a visual of how to safely get to this area, see the image on this NPC entry [npc=43161]._\n_Pre-Requisites:_\n\\- Level 85\n\\- Completion of Return of King Xorbb [quest=6115]\n\\- Completion of Champions of the People [quest=6822]\nYou say, 'Hail, Kela Lor Telaris'\nKela Lor Telaris says 'You tarried! Though braced by the strength of our Lady, the chamber doors will not hold against Diabo's ambition. You have faced his might. You know how tall it towers, built lofty by a scaffolding poisoned shards. Have you brought a [large] force to cut him down, or will you brave his wrath with a [small] band? If you have not done so, you should [inform] Aten Ha Ra of what is happening. You may also choose to [accompany] me on another important mission.'\nYou say, 'I have a small group'\nKela Lor Telaris says 'Though our task will be difficult with small numbers, we must [act] at once before Diabo again seals the antechamber doors.'\nYou have been assigned the task 'Dispelling the Shadows'.\nDiabo Va Xin Vellis beats upon Luclin's chamber door. Soon he will breach the inner sanctum and claim for himself lordship over the Plane of Shadow. Where hs Luclin gone? Does she cower in fear while her realm falls to ruin?\nYou say, 'Let's act'\nKela Lor Telaris says 'We shall meet in the chamber.'\nLOADING, PLEASE WAIT...\nYou have entered Plane of Shadow.\n\n---\n\n**Task Steps**\nSpeak with Kela Lor Telaris 0/1 (Plane of Shadow)\n_Task Window Says:_ Speak with Kela Lor Telaris and find out what is to be done about Diabo Va Xin Vellis.\nDefeat Luclin 0/1 (Plane of Shadow)\n_Task Window Says:_ Luclin has appeared. Meet her challenge\nClaim your reward from the chest 0/1 (Plane of Shadow)\n\n---\n\n**Summary**\n\\- Speak with Kela Lor Telaris to spawn the event (can bypass intro by saying \"attack now\").\n\\- After lore plays out, Luclin attacks.\n\\- Luclin's spells...\n\\-\\-\\- From 100%-30%, casts \"Dark Hemisphere\" and \"Light Hemisphere\".\n\\-\\-\\-\\-\\-\\- Every 35 seconds, these two spells are cast simultaneously. One will AE 180 degrees to her left; the other will AE 180 degrees to her right. The \"Dark\" AE is a nuke; the \"Light\" AE is a focus debuff that increases spell damage taken if you are hit with the \"Dark\" AE. Each time these are cast, these two AEs switch sides.\n\\-\\-\\- At 30%, buffs self with \"Shield of Shade\".\n\\-\\-\\-\\-\\-\\- This renders her undamageable as part of the script.\n\\-\\-\\- From 30% to death, casts \"Disease of Shade\".\n\\-\\-\\-\\-\\-\\- This is a single-target emote-based viral DOT for 30,000 hp/tick for 3 ticks (viral to anyone within 30' range of the inflicted target).\n\\-\\-\\- From 15% to death, casts \"Shadow Annihilation\" and \"Shadow Explosion\".\n\\-\\-\\-\\-\\-\\- Every 30 seconds, glowing particles appear in a vertical column above the central platform, and Luclin AEs \"Shadow Annihilation\".\n\\-\\-\\-\\-\\-\\- 15 seconds after this happens, the particles turn off and orbs appear, and shortly after this, Luclin AEs \"Shadow Explosion\".\n\\-\\-\\-\\-\\-\\- Both these two \"Shadow\" spells are avoidable by hiding out of line of sight (use the pillars to hide).\n\\- The Doors...\n\\-\\-\\- Once Luclin reaches 70%, several vessels (orbs) spawn around the room. They are a mix of light (white) and dark (black). You'll need to go through three phases here; the order in which you do so is up to you.\n\\-\\-\\-\\-\\-\\- Vessels can be turned the alternate type (light to dark, or dark to light) by DPS'ing them (low hps).\n\\-\\-\\-\\-\\-\\- One Phase: Turn every orb dark to spawn \"Bearer of Darkness\".\n\\-\\-\\-\\-\\-\\-\\-\\-\\- Every 30 seconds, the Bearer of Darkness AEs \"Dark Pulse\" (150' range nuke for 16,500).\n\\-\\-\\-\\-\\-\\-\\-\\-\\- Luclin buffs herself with \"Cloak of Darkness\" (increase defense) and heals herself for 10%.\n\\-\\-\\-\\-\\-\\- Another Phase: Turn every orb light to spawn \"Bearer of Light\".\n\\-\\-\\-\\-\\-\\-\\-\\-\\- Every 30 seconds, the Bearer of Darkness AEs \"Light Pulse\" (150' range nuke for 16,500).\n\\-\\-\\-\\-\\-\\-\\-\\-\\- Luclin buffs herself with \"Lucent Rending\" (increase attack) and heals herself for 10%.\n\\-\\-\\-\\-\\-\\- A Third Phase: Turn the four southern orbs light, and the four northern orbs dark to spawn the essence of shadow adds.\n\\-\\-\\-\\-\\-\\-\\-\\-\\- Luclin heals herself for 20%.\n\\-\\-\\-\\-\\-\\-\\-\\-\\- At first, one add spawns. 60 seconds later, two adds spawn. 60 seconds after that, three adds spawn. These adds continue to spawn every 60 seconds (maximum per wave is three mobs) for the remainder of the event.\n\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\- These adds have low hitpoints and don't hit too hard, and can be mezzed.\n\\- The Shadow...\n\\-\\-\\- Once Luclin reaches 30%, she becomes immune to DPS and walks to her throne. The Shadow of Luclin spawns and attacks.\n\\-\\-\\- The Shadow of Luclin casts \"Shade Siphon\" every 40 seconds.\n\\-\\-\\-\\-\\-\\- If a player has this debuff on them at a time when they are hit with another nuke, the Shadow of Luclin heals itself.\n\\-\\-\\- Shadow of Luclin has emote-based attacks:\n\\-\\-\\-\\-\\-\\- If she emotes that she \"raises its sword\" at someone, she is 10 seconds away from casting a frontal AE \"Shadow Blade\" in that players direction.\n\\-\\-\\-\\-\\-\\- If she emotes that she \"aims a straight cut\" at someone, she is 10 seconds away from casting a beam nuke (\"Shadow Blade Slash\") at that person.\n\\-\\-\\-\\-\\-\\- If she emotes that she \"glances around itself\", she is 10 seconds away from AEing the 175' range \"Shadow Blade Whorl\".\n\\-\\-\\- Kill the Shadow of Luclin to progress the event.\n\\- After the Shadow's Death: Luclin at 30%...\n\\-\\-\\- After the Shadow's death, Luclin attacks again.\n\\-\\-\\- She now has an emote-based viral DOT (\"Disease of Shade\"). She warns 15 seconds ahead of time that \"Spreading Shadows will consume you, \\_\\_\\_\\_\\_\" (where the blank is a player).\n\\- Luclin at 15%...\n\\-\\-\\- Once Luclin reaches 15% health, she gains another ability.\n\\-\\-\\- An emote will go off indicating the appearance of a vertical column of particles at the center of the room. Luclin, at this time, AEs \"Shadow Annihilation\" (avoidable by being out of line of sight).\n\\-\\-\\- 15 seconds after this, the particles disappear and NPC orbs spawn, at which point Luclin casts \"Shadow Explosion\".\n\\- Kill Luclin to complete the event.\n\n---\n\n**Triggering the Event**\n_Speak with Kela Lor Telaris to trigger the event. Note that you can bypass the introductory lore by saying \"attack now\"._\nYou say, 'Hail, Kela Lor Telaris'\nKela Lor Telaris shouts 'Do you feel it, your hair rising on its ends? The balance of light and darkness tilts back and forth, priming the energy in the air. We cannot wait. Any moment this chamber could [ignite].'\nYou say, 'Ignite?'\nKela Lor Telaris shouts 'Diabo carries the darkness within him. I can sense you bear the light. When the two meet, they shall annihilate each other, as it should be. I have seen enough to know there is no peace unless the light and the darkness come together as one and give themselves unto obliteration. Without such sacrifice, [strife] is eternal.'\nYou say, 'Strife?'\nKela Lor Telaris shouts 'You know the imbalance the shards brought to this realm. You see the looming destruction embodied in Diabo. Were he to ascend to the throne of Shadow and obtain the greatest shard secured within, this plane, Vex Thal, and perhaps the entire moon would be swallowed in darkness. If only [Luclin] had heard our pleas.'\nYou say, 'Where is Luclin?'\nKela Lor Telaris shouts 'She remains in the shadows. Where has she gone now that the spreading fear and ambition of her followers wrecks her home? Does she cower behind the door, shivering at the might of Diabo? Has she herself fallen to the madness of the shard she holds? Were you to [defeat] Diabo, perhaps Luclin would open her chamber that I might remove the shard from this plane and deliver it unto my employer, who will dispose of it. If you have no heart to confront Diabo, you should [leave] now.'\nYou say, 'We can defeat him'\nKela Lor Telaris glances around as the chamber begins to rumble and fill with shadows. 'Diabo must be breaching the chamber door! The time has come; light and darkness must collide!'\nKela Lor Telaris halts and quakes. 'Shadows betwixt the light and darkness...my Lady, could that be you? We plead only that you allow us to remove the defilement from your sight. My lady, hear my words and despise not my presence!\nLuclin shouts 'Mortal beings who live within the shadows of guilt and secrets, what makes you think I hear not every whisper, curse, or plea you utter? Under the light of my moon you spill your secrets to a darkened room, you speak your blood oaths, you cry out in your fulfillment of base desires. I see into your hearts. I know the darkness that lies within, vying with light for supremacy. You stumble about, enshrouded by darkness or blinded by light. You know not which will next lead you, or which will become your master.'\nLuclin shouts 'Diabo, darkness mastered you. Long ago light bled from your heart, pierced by the shards of fear and the blackened thorns of envy. You are but a darkened husk, a shriveled form of the creatures I created. For you there is no return to balance, only dissolution in the blackest reaches of my realm, beyond the edge of memory.'\nLuclin shouts 'And you, adventurers...you stumble into my presence, led as though blindfolded to gallows built by your own hands. I see within you. Some bear light, others carry darkness, but together your shadow walks a fated path. Will you climb the scaffolding and stand beside your dark executioner? Will you lay your necks within the noose that tightens around Norrath? Know that I will not allow you what you seek. The final piece of Cazic Thule rests in my shade for eternity. If you continue your journey, to you I grant reprieve from the gallows through death.'\n_Luclin becomes aggro (auto-aggro and summons from 100%, so be ready for a fight)._\n\n---\n\n**Luclin: 100% to 70%**\n_Luclin hits for a max ~13,000 (does not flurry or rampage at all; nor does she through the entire event). She can be pulled to any location in the entire chamber._\n_Every 35 seconds, she casts \"Dark Hemisphere\" and \"Light Hemisphere\". These two spells are cast simultaneously. One will AE 180 degrees to her left; the other will AE 180 degrees to her right. The \"Dark\" AE is a nuke; the \"Light\" AE is a focus debuff that increases spell damage taken if you are hit with the \"Dark\" AE. Each time these are cast, these two AEs switch sides._\nDark Hemisphere: Directional 400', (-150)\n1: Decrease Hitpoints by 25000\nLight Hemisphere: Directional 400', Chromatic (-975)\n1: Add effect: Light Hemisphere Effect\n2: Add effect: Light Hemisphere Effect\n_Once Luclin reaches 70%, you see these emotes:_\nVessels of light and darkness fill the chamber.\nKela Lor Telaris shouts 'Look at the vessels! Might all of them at once be changed to match the patterns on the doors? Perhaps they channel Luclins powers of Light and Darkness!'\n\n---\n\n**Luclin: 70% to 30%**\n_During this phase, Luclin continues casting her \"Hemisphere\" directional AEs. She does not cast any additional spells, nor does she gain any other abilities._\n_When she reaches 70% and the above emotes occur, eight orbs spawn around the center of the room. These are a mix of white and black (\"a light vessel\" and \"a dark vessel\")._\n_You'll need to go through three phases here; the order in which you do so is up to you. The order in which they are presented here is the recommended order for the least amount of difficulty._\n_Vessels can be turned the alternate type (light to dark, or dark to light) by DPS'ing them (low hps)._\nThe Dark Moon & Bearer of Darkness\n_One phase is the \"dark\" phase: Turn every orb dark to spawn a named called \"Bearer of Darkness\". As soon as this happens, Luclin heals herself by 10% and buffs herself with \"Cloak of Darkness\", a two-minute mitigation to all damage:_\nThe constellation of orbs resonates, and the occluded moon rises in the North.\nLuclin is revitalized by the activation of the dark-moon door, and she increases her defense.\nCloak of Darkness: Single Target, Unresistable (0)\n1: Mitigate Spell Damage by 15%, 0 total\n2: Mitigate Melee Damage by 15%, 0 total\n_The Bearer of Darkness spawns at a doorway and slowly makes its way to wherever you're fighting Luclin. It hits for a max ~9,000. Every 30 seconds, the Bearer of Darkness AEs \"Dark Pulse\":_\nDark Pulse: PB AE 150', Corruption (-150)\n1: Decrease Hitpoints by 16500\nThe Full Moon & Bearer of Light\n_A second phase is the \"light\" phase: Turn every orb light to spawn a named called \"Bearer of Light\". As soon as this happens, Luclin heals herself by 10% and buffs herself with \"Lucent Rending\", a two-minute increase to her attack:_\nThe constellation of orbs resonates, and the light of the full moon shines in the South.\nLuclin is revitalized by the activation of the full-moon door, and her strength increases.\nLucent Rending: Single Target, Unresistable (0)\n1: Increase 1H Blunt Damage Modifier by 110%\n2: Increase Attack Speed by 20%\n_The Bearer of Light spawns at a doorway and slowly makes its way to wherever you're fighting Luclin. It hits for a max ~9,000. Every 30 seconds, the Bearer of Light AEs \"Light Pulse\":_\nLight Pulse: PB AE 150', Prismatic (-150)\n1: Decrease Hitpoints by 16500\nThe Half-Moon & Essences of Shadow\n_The third phase is the \"mixed\" phase: Turn the four southern orbs light, and the four northern orbs dark:_\nThe constellation of orbs resonates, and the half moon shines in the East.\nLuclin is revitalized by the activation of the half-moon door, and beings of shadow are drawn into the fray.\nKela Lor Telaris says 'With the three doors activated, Luclin's protective powers must be exhausted!'\n_As soon as this happens, Luclin heals herself by 20%. 60 seconds later, 1x \"an essence of shadow\" spawns. 60 seconds after that, 2x \"an essence of shadow\" spawn. 60 seconds later, 3x \"an essence of shadow\". Every 60 seconds thereafter, you get another three \"an essence of shadow\". These adds have low hitpoints and hit for a max ~8,000. They are mezzable and stunnable._\nLuclin at 30%\n_WARNING: Do not take Luclin to 30% until you have spawned all three of these phases. If she reaches 30% before you have spawned them, she regenerates to 100% health._\n_Once all three phases have been spawned and Luclin reaches 30%, she goes unaggro, buffs herself with \"Shield of Shade\" and puts the aura \"Shadow Pushback\" around her:_\nShadow Pushback: PB AE 250', Unresistable (0)\n1: Slow Push (300)\nShield of Shade: Self 0', Unresistable (0)\n1: Mitigate Spell Damage by 100%\n2: Mitigate Melee Damage by 100%\n_She makes her way back to the center of the chamber where she takes a seat on a shadowed throne. Soon after, the room rumbles and the \"Shadow of Luclin\" appears._\nLuclin shouts 'You think your spirit shines in these dark hours, but I see the black cloud billowing about you, encroaching upon your horizon. You race into the moonless night, heedless of the coming destruction you hasten. That which you call light is only darkness. Can you even say where one ends and the other begins? Can you take a life that countless more might be saved? Though Cazic Thule was of my immortal kin, that which has been destroyed should never be repaired, lest he who stalks in shadows arises to claim both night and day. Those of you who cannot walk in the balance of light and darkness will be destroyed by shadow!'\n\n---\n\n**Shadow of Luclin**\n_The Shadow of Luclin auto-aggros (summons from 100% health). It hits for a max ~13,000 and can be pulled to any location in the chamber. There are no adds during this phase._\n_Every 40 seconds, it debuffs players with \"Shade Siphon\". This effect causes Luclin to be healed each time any player takes 10,000 damage (or more)._\n_It has several emote-based attacks (note that in each case here, there is a double space after the word \"Luclin\"):_\nShadow of Luclin raises its sword at \\_\\_\\_\\_\\_ for an arcing cut.\n_\\-\\-\\- 10-second warning for a frontal AE \"Shadow Blade\" in that player's direction._\nShadow Blade: Directional 300', Magic (-950)\n1: Decrease Hitpoints by 22000\nShadow of Luclin aims a straight cut at \\_\\_\\_\\_\\_.\n_\\-\\-\\- 10-second warning for a beam nuke \"Shadow Blade Slash\" at that player._\nShadow Blade Slash: Unknown(44) 20', Magic (-950)\n1: Decrease Hitpoints by 25000\nShadow of Luclin glances around itself.\n_\\-\\-\\- 10-second warning to the 175' range AE \"Shadow Blade Whorl\"._\nShadow Blade Whorl: PB AE 175', Magic (-950)\n1: Decrease Hitpoints by 19000\n_Kill the Shadow of Luclin to progress the event._\n\n---\n\n**Luclin: 30% to 15%**\n_Luclin reactivates as soon as the Shadow of Luclin dies (again, auto-aggro and instant summon). She no longer does he \"Hemisphere\" directional AEs, but she gains an emote-based viral spell attack:_\nLuclin says 'The spreading shadows will consume you, \\_\\_\\_\\_\\_'\n\\-\\-\\- 15-second warning to \"Disease of Shade\" being cast on the targeted player.\nDisease of Shade: Single Target, Disease (-975)\n1: Decrease Hitpoints by 30000 per tick _(3 ticks)_\n2: Increase Disease Counter by 30\n\\\\* Viral to anyone within 40' range\n_Note: No adds spawn during this phase, or for the remainder of the event._\n_Once Luclin reaches 15%, you see this emote:_\nLuclin says 'Those who reject equilibrium and seek to overthrow balance will find nothing but annihilation!'\n\n---\n\n**Luclin: 15% to Defeat**\n_Luclin no longer casts the viral spell, but gains a debuff (\"Shadow Annihilation\", 1200' PBAE avoidable by being out of line of sight) + explosion AE (\"Shadow Explosion\", 1200' PBAE nuke for 12,000). The \"Shadow Annihilation\" effect is a focus that makes you take additional damage from the explosion AE._\n_Kill Luclin (or rather, the Shadow of Luclin, as she tricked you into doing) to complete the event:_\nLuclin's laughter echoes throughout the chamber, and her undefeated form rises from the shadows. 'You still do not understand? The hand of darkness guided you here, stretched you out like mindless digits to grasp for itself that which should never be taken. Kela Lor Telaris, stand before your goddess!'\n_Kela Lor Telaris and Luclin have a stand-off in the center of the chamber..._\nLuclin shouts 'You are the palm of your master, the black hand of many names. You reach for coin but grab hold of Norrath's destruction. Do you even know whom you serve? Long ago it ceased to be I.'\n_Kela Lor Telaris is then destroyed..._\nLuclin shouts 'Now your death will serve Norrath as a reminder of the cost of allegiance to Xaric!'\n_Luclin makes her way to her throne..._\nLuclin shouts 'Adventurers, your courage and strength may be useful to me. But no more will I trifle with you while you remain cloaked in ignorance. If you seek to lift the veil, I await you in my chambers.'\n_A chest spawns next to the throne._\nLuclin shouts 'In another age, before even your races crawled upon the surface of Norrath, I heard the Alarans praying in their strange tongues under the light of my moon. They cowered beneath this silver eye in the black sky, and they dreaded the glimpse of winged forms flitting across its face. In this strange land, fear lurked beneath every rock and within every shadow. Even as their gods lay dead and buried, the Alarans' fear lived, growing stronger just beyond their vision.'\nLuclin shouts 'Though they could not speak its name, I knew it. Even in the darkest twilight recesses of thought I am there. I have seen where it lives, behind the brave countenance or facile smile. Lupex, the Unspoken -- it has been called many things, but its true name is Xaric, the Phantasm of unspeakable fear, the fear without name.'\nLuclin shouts 'It waits in the heart of Cazic's crystal, drawing facets of fear unto itself, becoming a god more powerful than Cazic ever was. It ends here. This piece of Cazic Thule will never leave this chamber. If you trek further upon your dark path, I offer you no leniency. You forfeit your life as Kela Lor did when he made a pact with Xaric. But there is yet a chance to atone for your misdeeds.'\nLuclin shouts 'In due time I shall open the way into the heart of fear. [Leave] here and return to your lands below. Concern yourself not with my realm, for my servants and I shall return it to equilibrium. Await the time to confront Xaric. Prepare your minds: Be not fooled by the path of light or darkness, for one is often the other. Instead, walk upon the path of shadows, and know that I hear your thoughts and am with you in the gray.'\n_As you open the chest:_\nLuclin has revealed that Xaric, the Phantasm of Fear, has been using you to gather the fallen shards of Cazic Thule. When the time is right, the way shall be opened for you to confront this unspoken evil that has been spreading its grasp over Norrath.\nYou say, 'Hail, Luclin'\nLuclin says 'You should [leave] from here. If you [fight] on in your quest to bring about Xaric's darkness, you will die.'\n_Say \"leave\" to zone out (or \"fight\" for a quick zone to your bind location)._\nYou say, 'Let me leave!'\nLuclin says 'Be ready when I call upon you to walk the path of shadow!'\nLOADING, PLEASE WAIT...\nYou have entered Plane of Shadow.\n\n---\n\n**Rewards**\nExperience\n225 platinum\n_Possible Chest Loot (2 items + 1 Dreadmote per task):_\nCarved Ivory Earring\nHoop of the Grinning Skull\nIron Spike Ring\nMask of Unending Rage\nMedallion of Shadows\nSerpent-Buckle Belt\nShadow Woven Sash\nShifting Earring\nSoprano Stud\nSpiky Choker\nLesser Dreadmote\nMedian Dreadmote\nGreater Dreadmote\nGlowing Dreadmote\n- Carved Ivory Earring [item=111270]\n- Glowing Dreadmote [item=106497]\n- Greater Dreadmote [item=106464]\n- Hoop of the Grinning Skull [item=110979]\n- Iron Spike Ring [item=111157]\n- Lesser Dreadmote [item=106476]\n- Mask of Unending Rage [item=111302]\n- Medallion of Shadows [item=111137]\n- Median Dreadmote [item=106509]\n- Serpent-Buckle Belt [item=111138]\n- Shadow Woven Sash [item=111247]\n- Shifting Earring [item=110978]\n- Soprano Stud [item=111389]\n- Spiky Choker [item=111266]",
    },
    {
      id = "6835",
      title = "Cannibalism For Fun and Profit",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Vex Derex Lux",
      loc = { y = 800.0, x = 935.0, z = 31.0 },
      triggers = {
        "Hail, Vex Derex Lux",
        "I am brave, of course!",
        "Beyond help?",
        "Shared?",
        "brave",
        "foolish",
        "beyond help",
        "shared",
      },
      items_required = {
      },
      rewards = {
        { id = 111107, name = "Eye of Xin Va", type = "item" },
        { id = 110992, name = "Fragment of Vex Derex Lux", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Shadow [zone=915]\n**Who:**\n- Vex Derex Lux [npc=43130]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Success Lockout Timer**: 06:00:00\n**Quest Items:**\n- Eye of Xin Va [item=111107]\n- Fragment of Vex Derex Lux [item=110992]\n**Related Creatures:**\n- an essence of xin va [npc=43304]\n- sentient essence of xin va [npc=43477]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Apr 17 17:45:35 2013\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a solo task that begins with Vex Derex Lux ( map) at location 800, 935, 31 (in the dervish room west of the palace entry room: findable with CTRL+F)._\n_Pre-Requisites:_\n\\- Level 85\n\\- No task requirements\nYou say, 'Hail, Vex Derex Lux'\nVex Derex Lux billows threateningly, 'You are either [brave] or [foolish] to dare approach me. Tell me, which is it?'\nYou say, 'I am brave, of course!'\nVex Derex Lux lets loose a laugh like a maelstrom of angry steam, 'Hah! A fool will think themselves brave when they do not know the danger they face! Now I will teach you-' It stops, suddenly growing calm, then continues in a gentle, breezy tone, '-anything I can that may help you in your journey. Alas! For myself, I am [beyond help].'\nYou say, 'Beyond help?'\nVex Derex Lux sighs gustily, 'It's so lonesome here, that sometimes I wish I were just a mindless essence like the others who roam this hall. Though we are all formed of the same basic elements, only I can speak and think. Alone, it is a burden, but [shared], I feel it would be the greatest gift imaginable.'\nYou say, 'Shared?'\nVex Derex Lux says 'I have long pondered how to bestow intelligence upon my fellow essences, and believe I have found a means, however, it is beyond my skill to carry out myself. If you would aid me, however, my dream of building my own army may finally come to fruition!''\n_You receive a \"Fragment of Vex Derex Lux\"._\nYou have been assigned the task 'Cannibalism for Fun and Profit'.\n\n---\n\nLoot 6 Eye of Xin Va 0/6 (Plane of Shadow)\n_These are dropped by dervish mobs inside the palace._\nUse the Fragment of Vex Derex Lux on an essence of xin va 0/1 (Plane of Shadow)\nForce feed the eyes of its kin to the sentient essence of xin va 0/1 (Plane of Shadow)\nSpeak with the sentient essence of xin va 0/1 (Plane of Shadow)\nDefend yourself against the sentient essence of xin va! 0/1 (Plane of Shadow)\nReport to Vex Derex Lux 0/1 (Plane of Shadow)\n_Rewards:_\nExperience (regular + 4 AAs)\n225 platinum",
    },
    {
      id = "6836",
      title = "Here's Ectoplasm in Your Eye!",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Vex Derex Lux",
      loc = { y = 800.0, x = 935.0, z = 31.0 },
      triggers = {
        "Hail, Vex Derex Lux",
        "Foolish...",
        "Solve?",
        "I will read them",
        "brave",
        "foolish",
        "solve",
        "read",
      },
      items_required = {
      },
      rewards = {
        { id = 110937, name = "Ectoplasm", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Shadow [zone=915]\n**Who:**\n- Vex Derex Lux [npc=43130]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Success Lockout Timer**: 06:00:00\n**Quest Items:**\n- Ectoplasm [item=110937]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Apr 17 17:45:54 2013\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_Pre-Requisites:_\n\\- Level 85\n\\- No task requirements\n_This is a solo task that begins with Vex Derex Lux ( map) at location 800, 935, 31 (in the dervish room west of the palace entry room: findable with CTRL+F)._\n_Pre-Requisites:_\n\\- Level 85\n\\- No task requirements\nYou say, 'Hail, Vex Derex Lux'\nVex Derex Lux billows threateningly, 'You are either [brave] or [foolish] to dare approach me. Tell me, which is it?'\nYou say, 'Foolish...'\nVex Derex Lux rumbles in surprise, 'One who admits what they do not know can only be called wise.' It shifts, its voice taking on a gentler tone, 'Perhaps you could [solve] a riddle that has puzzled me for many ages?'\nYou say, 'Solve?'\nVex Derex Lux says 'To the Northeast lies a hall, upon whose walls ancient runes are inscribed. They call out to me, and I sense something familiar, yet I cannot read them. I feel these runes are important to me, and would ask you to [read] them and tell me what you've learned.'\nYou say, 'I will read them'\nVex Derex Lux says 'I've learned the runes may only be read by those whose eyes possess a certain quality. And though your eyes may not, the spirits who haunt that hall are known to be able to read the runes. I believe this quality may be gained temporarily by applying their ectoplasm on one's eyes.'\nYou have been assigned the task 'Here's Ectoplasm in Your Eye!'.\nVex Derex Lux has asked you to head to the hall of records, to the northeast, and find a way to decipher the ancient runes. They can only be read by 'one whose eyes possess a certain quality' - whatever that means.\n\n---\n\nLoot 4 Ectoplasm 0/4 (Plane of Shadow)\nUse the Ectoplasm to read the runes on the North Wall - 0/1 (Plane of Shadow)\nNorth Wall 1699, -959, 33\nUse the Ectoplasm to read the runes on the East Wall - 0/1 (Plane of Shadow)\nEast Wall 1470, -1194, 33\nUse the Ectoplasm to read the runes on the South Wall - 0/1 (Plane of Shadow)\nSouth Wall 1330, -963, 33\nUse the Ectoplasm to read the runes on the West Wall - 0/1 (Plane of Shadow)\nWest Wall 1469, -728, 33\nSpeak with Vex Derex Lux - 0/1 (Plane of Shadow)\n_Rewards:_\nExperience (regular + 4 AAs)\n225 platinum\nNeed locations for quest updates, missing dialogues, faction hits if any.",
    },
    {
      id = "6838",
      title = "Hunter of the Plane of Shadow",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Unknown",
      loc = nil,
      triggers = {
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Shadow [zone=915]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | No\n**Can Be Shrouded?:** | No\n**Quest Type:** | Achievement\n**Quest Goal:**\n- Advancement\n**Related Creatures:**\n- A Thundering Tempest [npc=43152]\n- An Astral Wanderer [npc=43153]\n- Darkstone [npc=43154]\n- Gloomshell [npc=43155]\n- Kaas Thox [npc=43156]\n- Kela Rentha Xakra [npc=43157]\n- Nightwing [npc=43158]\n- Shakra Za [npc=43159]\n- The Dark Lady [npc=43160]\n- Volx Xi Xakra [npc=43161]\n- Xal Zeth [npc=43162]\n- Xi Dyn [npc=43163]\n- Xorla Vor [npc=43164]\n- Xundraux Xakra [npc=43165]\n- Zel Kaxri [npc=43166]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Apr 17 21:00:18 2013\nModified: Mon May 6 02:11:32 2024 | | This is a Hunter achievement for Rain of Fear.\nThis achievement is gained upon defeating the following rare monsters in the Plane of Shadow:\nA Thundering Tempest\nAn Astral Wanderer\nDarkstone\nGloomshell\nKaas Thox\nKela Rentha Xakra\nNightwing\nShakra Za\nThe Dark Lady\nVolx Xi Xakra\nXal Zeth\nXi Dyn\nXorla Vor\nXundraux Xakra\nZel Kaxri\n_Reward:_\nNone\n\n---\n\n_\"poshadow.txt\" map file (also click links to the left for location information):_\nP -1099.3896, -717.6580, 30.7716, 127, 0, 0, 1, A\\_Thundering\\_Tempest\nP -909.6765, -418.5154, 30.7985, 127, 0, 0, 1, A\\_Thundering\\_Tempest\nP -509.1821, -751.5281, 31.8734, 127, 0, 0, 1, A\\_Thundering\\_Tempest\nP -1244.9939, -2193.5186, 159.5419, 127, 0, 0, 1, An\\_Astral\\_Wanderer\nP -1216.3699, -2211.6787, -0.0021, 127, 0, 0, 1, An\\_Astral\\_Wanderer\nP -1216.5658, -2208.4270, 79.9929, 127, 0, 0, 1, An\\_Astral\\_Wanderer\nP -1231.8823, -1121.9244, 279.5436, 127, 0, 0, 1, Darkstone\nP 966.1602, 325.6910, -107.4160, 127, 0, 0, 1, Gloomshell\nP 1226.0129, -77.7812, -72.9515, 127, 0, 0, 1, Gloomshell\nP 381.7007, 39.4782, -77.6957, 127, 0, 0, 1, Gloomshell\nP -2450.1960, -2806.2898, -20.7862, 127, 0, 0, 1, Kaas\\_Thox\nP -2434.0620, -2207.4832, -18.7817, 127, 0, 0, 1, Kaas\\_Thox\nP -160.6257, -1183.6604, 30.8736, 127, 0, 0, 1, Kela\\_Rentha\\_Xakra\nP -116.0000, -1620.0000, 33.0000, 127, 0, 0, 1, Kela\\_Rentha\\_Xakra\nP -249.0000, -1675.0000, 33.0000, 127, 0, 0, 1, Kela\\_Rentha\\_Xakra\nP -986.6071, -41.3354, -107.0595, 127, 0, 0, 1, Nightwing\nP -1438.3300, -72.2200, -69.4200, 127, 0, 0, 1, Nightwing\nP -1202.1990, 370.9734, -63.6417, 127, 0, 0, 1, Nightwing\nP -2125.4004, -2459.9409, -170.3764, 127, 0, 0, 1, Shakra\\_Za\nP -729.4550, -1993.3024, 159.5268, 127, 0, 0, 1, The\\_Dark\\_Lady\nP -596.0294, -1533.9115, 29.4785, 127, 0, 0, 1, The\\_Dark\\_Lady\nP -694.5867, -2004.1073, 26.7783, 127, 0, 0, 1, The\\_Dark\\_Lady\nP 87.2655, -1549.6166, 432.4102, 127, 0, 0, 1, Volx\\_Xi\\_Xakra\nP -5.5824, -1428.1584, 435.3306, 127, 0, 0, 1, Volx\\_Xi\\_Xakra\nP -1422.5027, -1813.5450, -19.8505, 127, 0, 0, 1, Xal\\_Zeth\nP -2053.8306, 776.8007, -58.5061, 127, 0, 0, 1, Xi\\_Dyn\nP 213.4392, -689.7966, 30.7928, 127, 0, 0, 1, Xorla\\_Vor\nP -314.3497, -436.9351, 31.5639, 127, 0, 0, 1, Xorla\\_Vor\nP -40.2941, -691.7068, 11.2992, 127, 0, 0, 1, Xorla\\_Vor\nP 510.6012, -545.4346, 427.4121, 127, 0, 0, 1, Xundraux\\_Xakra\nP -238.3500, -2355.3000, 290.7000, 127, 0, 0, 1, Zel\\_Kaxri\n_NOTE: This is not a complete list (if you know of additional spawn points, please let us know!)._",
    },
  },
}
