-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Plane of Tranquility (potranquility)
-- Total Quests: 7
-- ============================================================================

return {
  zone = "potranquility",
  zone_name = "Plane of Tranquility",
  quests = {
    {
      id = "2263",
      title = "Plate Ornate Tranquility Armor",
      exp = "04",
      exp_name = "The Planes of Power",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Bor Wharhammer",
      loc = nil,
      triggers = {
        "Hail, Bor Wharhammer",
        "What emblem?",
        "What planar armors?",
        "What plate?",
        "emblem",
        "class",
        "chain",
        "silk",
      },
      items_required = {
        { name = "ye one fer the price of 500 platinum pieces", count = 1 },
        { name = "him 500 platinum pieces:_", count = 1 },
      },
      rewards = {
        { id = 21868, name = "Bard Emblem", type = "item" },
        { id = 16730, name = "Brick of Ethereal Energy", type = "item" },
        { id = 21870, name = "Cleric Emblem", type = "item" },
        { id = 17230, name = "Ethereal Sheet of Metal", type = "item" },
        { id = 17226, name = "Ethereal Temper", type = "item" },
        { id = 21882, name = "Mystical Furnace of Ro", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Tranquility [zone=159]\n**Who:**\n- Bor Wharhammer [npc=11924]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 60\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Armour Set\n**Quest Items:**\n- Bard Emblem [item=21868]\n- Brick of Ethereal Energy [item=16730]\n- Cleric Emblem [item=21870]\n- Ethereal Sheet of Metal [item=17230]\n- Ethereal Temper [item=17226]\n- Mystical Furnace of Ro [item=21882]\n- Ornate Boot Mold [item=21401]\n- Ornate Bracer Mold [item=21407]\n- Ornate Breastplate Mold [item=21406]\n- Ornate Gauntlet Mold [item=21402]\n- Ornate Greaves Mold [item=21404]\n- Ornate Helm Mold [item=21403]\n- Ornate Vambrace Mold [item=21405]\n- Paladin Emblem [item=21875]\n- Shadowknight Emblem [item=21881]\n- Tanaan Smithing Hammer [item=17128]\n- Warrior Emblem [item=21879]\n**Era:** | !Planes of Power\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- Bard\n- Cleric\n- Paladin\n- Shadowknight\n- Warrior\n**Appropriate Races:**\n- All\nEntered: Thu Nov 21 21:26:09 2002\nModified: Tue Dec 5 05:21:04 2023 | | You say, 'Hail, Bor Wharhammer'\nBor Wharhammer says 'Greetin's t'ye \\_\\_\\_\\_\\_\\_! Isn't the area 'round 'ere so nice an' quiet? Such a departure from me old days; slaving o'er the forge t'create masterpieces! T'be 'onest, at times I do miss the old forge, but after I created me finest breastplate, it seemed as if nothing else I made could ever live up t'it. So I left me home to'wander the land an' see what I could learn o'the world. I 'ave learned quite a bit from the elders 'ere an' the skilled craftspeople in New Tanaan. I 'ave even devised a type o'emblem that will impart the magic o'tranquility into the user t'create planar armors from pieces o'energy found in the planes.'\nYou say, 'What emblem?'\nBor Wharhammer says 'Well, the emblems dinnae be easy t'craft but I will gladly give ye one fer the price of 500 platinum pieces. They allow a planes traveler with no craftin' skills t'create many fine pieces o'planar armor in a special, magical kit I also 'ave an' will throw in with the price. The kit acts as a focal point fer the wild magic energy o'the Planes. Ye will only be able t'use each emblem an' kit once when ye create the piece, 'owever I dinnae be goin' anywhere soon! Just venture back when ye need another an' dinnae ferget the coin!'\nYou say, 'What planar armors?'\nBor Wharhammer says 'From me understanding, the very fabric o'the planes is so strong out 'ere, it can be found in raw form the deeper ye traverse. Anyone who ventures far into the planes finds that they must wear excellent armor t'protect them from the savage environment. The very essence of planar energy can be focused into a form that can fit our shape. As ye progress deeper into the planes, ye will find many molds an' patterns with which t'base a set o'armor. If ye want t'know 'ow t'craft the various types o'armor, I can instruct ye about plate, chain, leather an' silk.'\nYou say, 'What plate?'\nBor Wharhammer says 'Ahhhhh \\_\\_\\_\\_\\_\\_! The fine rigid armor that can stop a shaft from piercing yer heart! Too bad it be so cumbersome an' difficult t'move about in. To construct a piece o'plate armor, ye need t'combine a plate mold, an emblem, various amounts o'sheet metal an' use one o'those crafty Tanaan smithin' 'ammers all within a furnace touched by Ro. Ethereal metal sheet construction is another matter. Ye will need t'combine two bricks o'ethereal energy, an ethereal temper an' a Tanaan smithin' 'ammer within a Tanaan forge. I would seek a skilled craftsperson t'make the metal sheets fer ye; the emblem will enable ye t'craft the final armor piece no matter what yer skill be.'\n_If you give him 500 platinum pieces:_\nBor Wharhammer says 'Wonderful! This coin will go towards me fines with the Myrist library. They charge quite a bit fer overdue volumes! 'ere be yer emblem an' a kit in which ye may craft planar armor. The kit only 'as enough magical energy t'craft one piece before the energies expire, be sure ye understand. May the armor ye make with it provide ye with much protection.'\n_You receive a class-specific emblem and a Mystical Furnace of Ro, an 8-slot container useful only for combines involving ornate or elemental molds. The ornate molds drop in various zones._\n_Basic recipe is: appropriate ornate plate mold, class-specific emblem, tanaan smithing hammer, 1-3 ethereal sheets of metal. Combine in the Mystical Furnace of Ro. The final combine is no-fail._\n**Submitted by:** Calandria, Radric\n- Armplates of Emblazoned Souls [item=20291]\n- Boots of Emblazoned Souls [item=20963]\n- Boots of Vengeful Fury [item=17395]\n- Bracer of Emblazoned Souls [item=17888]\n- Breastplate of Emblazoned Souls [item=17396]\n- Breastplate of Vengeful Fury [item=17304]\n- Composer's Boots [item=17885]\n- Composer's Bracer [item=17822]\n- Composer's Chestplate [item=17240]\n- Composer's Gauntlets [item=21219]\n- Composer's Greaves [item=17821]\n- Composer's Helmet [item=17820]\n- Composer's Vambraces [item=17960]\n- Gauntlets of Emblazoned Souls [item=19049]\n- Gauntlets of Vengeful Fury [item=17877]\n- Greaves of Emblazoned Souls [item=17305]\n- Greaves of Vengeful Fury [item=17264]\n- Helm of Emblazoned Souls [item=17889]\n- Helm of Vengeful Fury [item=17848]\n- Jaylia's Boots of the Valiant [item=18009]\n- Jaylia's Helm of the Valiant [item=17887]\n- Jaylia's Legplates of the Valiant [item=17235]\n- Jaylia's Valiant Bracer [item=17802]\n- Jaylia's Valiant Chestplate [item=17397]\n- Jaylia's Valiant Gauntlets [item=21305]\n- Jaylia's Valiant Vambraces [item=20532]\n- Kizrak's Armband of Battle [item=17890]\n- Kizrak's Boots of Battle [item=17394]\n- Kizrak's Bracer of Battle [item=17303]\n- Kizrak's Chestplate of Battle [item=17238]\n- Kizrak's Gauntlets of Battle [item=18000]\n- Kizrak's Greaves of Battle [item=17265]\n- Kizrak's Helmet of Battle [item=17262]\n- Vambraces of Vengeful Fury [item=17849]\n- Wristplates of Vengeful Fury [item=17847]",
    },
    {
      id = "2265",
      title = "Silk Elemental Tranquility Armor",
      exp = "04",
      exp_name = "The Planes of Power",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Bor Wharhammer",
      loc = nil,
      triggers = {
        "what emblem?",
        "what silk",
        "what swatches",
        "emblem",
        "class",
        "chain",
        "silk",
        "leather",
      },
      items_required = {
        { name = "ye one fer the price of 500 platinum pieces", count = 1 },
      },
      rewards = {
        { id = 21566, name = "Druzzil's Mystical Sewing Kit", type = "item" },
        { id = 21351, name = "Elemental Silk Boot Pattern", type = "item" },
        { id = 21352, name = "Elemental Silk Bracelet Pattern", type = "item" },
        { id = 21353, name = "Elemental Silk Glove Pattern", type = "item" },
        { id = 21354, name = "Elemental Silk Pant Pattern", type = "item" },
        { id = 21355, name = "Elemental Silk Sleeve Pattern", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Tranquility [zone=159]\n**Who:**\n- Bor Wharhammer [npc=11924]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 65\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Armour Set\n**Quest Items:**\n- Druzzil's Mystical Sewing Kit [item=21566]\n- Elemental Silk Boot Pattern [item=21351]\n- Elemental Silk Bracelet Pattern [item=21352]\n- Elemental Silk Glove Pattern [item=21353]\n- Elemental Silk Pant Pattern [item=21354]\n- Elemental Silk Sleeve Pattern [item=21355]\n- Elemental Silk Turban Pattern [item=21356]\n- Enchanter Emblem [item=19213]\n- Ethereal Silk Swatch [item=17224]\n- Magician Emblem [item=21872]\n- Necromancer Emblem [item=21874]\n- Tanaan Embroidery Needle [item=17228]\n- Timeless Silk Robe Pattern [item=21884]\n- Wizard Emblem [item=21880]\n**Related Zones:**\n- Plane of Time B [zone=178]\n**Era:** | !Planes of Power\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- Enchanter\n- Magician\n- Necromancer\n- Wizard\n**Appropriate Races:**\n- All\nEntered: Mon Nov 25 20:22:43 2002\nModified: Tue Dec 5 05:21:04 2023 | | Each class gets a specific suit of armor by talking to Bor Wharhammer. This is for classes that wear silk.\nBor Wharhammer says 'Greetin's t'ye Calandria! Isn't the area 'round 'ere so nice an' quiet? Such a departure from me old days; slaving o'er the forge t'create masterpieces! T'be 'onest, at times I do miss the old forge, but after I created me finest breastplate, it seemed as if nothing else I made could ever live up t'it. So I left me home to'wander the land an' see what I could learn o'the world. I 'ave learned quite a bit from the elders 'ere an' the skilled craftspeople in New Tanaan. I 'ave even devised a type o'emblem that will impart the magic o'tranquility into the user t'create planar armors from pieces o'energy found in the planes.'\nYou say, 'what emblem?'\nBor Wharhammer says 'Well, the emblems dinnae be easy t'craft but I will gladly give ye one fer the price of 500 platinum pieces. They allow a planes traveler with no craftin' skills t'create many fine pieces o'planar armor in a special, magical kit I also 'ave an' will throw in with the price. The kit acts as a focal point fer the wild magic energy o'the Planes. Ye will only be able t'use each emblem an' kit once when ye create the piece, 'owever I dinnae be goin' anywhere soon! Just venture back when ye need another an' dinnae ferget the coin!'\nYou say, 'what silk'\nBor Wharhammer says 'Har! It be quite funny that we be referin' t'silk as armor, fer the amount o'protection it provides be miniscule at best. The planar armor made from strands o'ether can still be quite useful fer its magical properties, 'owever. Ye will need t'take up a Tanaan embroidery needle, a pattern, an emblem an' various amounts o'ether silk swatches t'create a piece. Craft it all within a sewing kit boilin' with magical energy.'\nYou say, 'what swatches'\nBor Wharhammer sighs at you. 'T'make a swatch, ye need t'combine two strands o'ether along with a curing agent in a Tanaan loom. Ye will need t'seek a skilled brew master t'make the curing agent fer ye. Just 'ave them create it by using two celestial essences, soda an' paeala sap'\nHanding Bor 500 pp will get you an emblem specific to your class and Druzzil's Mystical Sewing Kit, an 8-slot container useful only for ornate or elemental patterns. The elemental patterns drop in various zones.\nBasic recipe is: appropriate elemental pattern, tanaan embroidery needle, appropriate class emblem, 1-3 ethereal silk swatches combined in Druzzil's Sewing Kit. The final combine is no-fail.\n- Maelin's Bracelet of Lore [item=17747]\n- Maelin's Gloves of Lore [item=18002]\n- Maelin's Leggings of Lore [item=18144]\n- Maelin's Robe of Lore [item=18106]\n- Maelin's Shoes of Lore [item=18003]\n- Maelin's Skullcap of Lore [item=18001]\n- Maelin's Sleeves of Lore [item=18143]\n- Magi`Kot's Bangle of Convergence [item=18149]\n- Magi`Kot's Gloves of Convergence [item=17894]\n- Magi`Kot's Pants of Convergence [item=19046]\n- Magi`Kot's Robe of Convergence [item=18146]\n- Magi`Kot's Shoes of Convergence [item=18148]\n- Magi`Kot's Sleeves of Convergence [item=18147]\n- Magi`Kot's Tiara of Convergence [item=17893]\n- Miragul's Bracelet of Risen Souls [item=18152]\n- Miragul's Crown of Risen Souls [item=17745]\n- Miragul's Gloves of Risen Souls [item=17996]\n- Miragul's Greaves of Risen Souls [item=18675]\n- Miragul's Shoes of Risen Souls [item=18151]\n- Miragul's Shroud of Risen Souls [item=18150]\n- Miragul's Sleeves of Risen Souls [item=17895]\n- Romar's Bracer of Visions [item=18673]\n- Romar's Circlet of Visions [item=18162]\n- Romar's Gloves of Visions [item=18163]\n- Romar's Pantaloons of Visions [item=18674]\n- Romar's Robe of Visions [item=18153]\n- Romar's Sleeves of Visions [item=18201]\n- Romar's Slippers of Visions [item=18145]",
    },
    {
      id = "2259",
      title = "Silk Ornate Tranquility Armor",
      exp = "04",
      exp_name = "The Planes of Power",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Bor Wharhammer",
      loc = nil,
      triggers = {
        "what emblem?",
        "what silk?",
        "what swatches",
        "emblem",
        "class",
        "chain",
        "silk",
        "leather",
      },
      items_required = {
        { name = "ye one fer the price of 500 platinum pieces", count = 1 },
      },
      rewards = {
        { id = 14418, name = "Celestial Essence", type = "item" },
        { id = 21566, name = "Druzzil's Mystical Sewing Kit", type = "item" },
        { id = 19213, name = "Enchanter Emblem", type = "item" },
        { id = 17225, name = "Ethereal Curing Agent", type = "item" },
        { id = 17224, name = "Ethereal Silk Swatch", type = "item" },
        { id = 21872, name = "Magician Emblem", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Tranquility [zone=159]\n**Who:**\n- Bor Wharhammer [npc=11924]\nRating:\n0/2**_\\*__\\*__\\*__\\*__\\*_**\n(Average from 2 ratings)\nInformation:\n**Level:** | 55\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Armour Set\n**Quest Items:**\n- Celestial Essence [item=14418]\n- Druzzil's Mystical Sewing Kit [item=21566]\n- Enchanter Emblem [item=19213]\n- Ethereal Curing Agent [item=17225]\n- Ethereal Silk Swatch [item=17224]\n- Magician Emblem [item=21872]\n- Necromancer Emblem [item=21874]\n- Ornate Silk Boot Pattern [item=21413]\n- Ornate Silk Bracelet Pattern [item=21414]\n- Ornate Silk Glove Pattern [item=21415]\n- Ornate Silk Pant Pattern [item=21416]\n- Ornate Silk Robe Pattern [item=21417]\n- Ornate Silk Sleeve Pattern [item=21418]\n- Ornate Silk Turban Pattern [item=21419]\n- Packet of Paeala Sap [item=15754]\n- Soda [item=14915]\n- Strand of Ether [item=16729]\n- Tanaan Embroidery Needle [item=17228]\n- Wizard Emblem [item=21880]\n**Era:** | !Planes of Power\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- Enchanter\n- Magician\n- Necromancer\n- Wizard\n**Appropriate Races:**\n- All\nEntered: Thu Nov 21 20:14:17 2002\nModified: Tue Dec 5 05:21:04 2023 | | Each class gets a specific suit of armor by talking to Bor Wharhammer. This is for classes that wear silk.\nBor Wharhammer says 'Greetin's t'ye Calandria! Isn't the area 'round 'ere so nice an' quiet? Such a departure from me old days; slaving o'er the forge t'create masterpieces! T'be 'onest, at times I do miss the old forge, but after I created me finest breastplate, it seemed as if nothing else I made could ever live up t'it. So I left me home to'wander the land an' see what I could learn o'the world. I 'ave learned quite a bit from the elders 'ere an' the skilled craftspeople in New Tanaan. I 'ave even devised a type o'emblem that will impart the magic o'tranquility into the user t'create planar armors from pieces o'energy found in the planes.'\nYou say, 'what emblem?'\nBor Wharhammer says 'Well, the emblems dinnae be easy t'craft but I will gladly give ye one fer the price of 500 platinum pieces. They allow a planes traveler with no craftin' skills t'create many fine pieces o'planar armor in a special, magical kit I also 'ave an' will throw in with the price. The kit acts as a focal point fer the wild magic energy o'the Planes. Ye will only be able t'use each emblem an' kit once when ye create the piece, 'owever I dinnae be goin' anywhere soon! Just venture back when ye need another an' dinnae ferget the coin!'\nYou say, 'what silk?'\nBor Wharhammer says 'Har! It be quite funny that we be referin' t'silk as armor, fer the amount o'protection it provides be miniscule at best. The planar armor made from strands o'ether can still be quite useful fer its magical properties, 'owever. Ye will need t'take up a Tanaan embroidery needle, a pattern, an emblem an' various amounts o'ether silk swatches t'create a piece. Craft it all within a sewing kit boilin' with magical energy.'\nYou say, 'what swatches'\nBor Wharhammer sighs at you. 'T'make a swatch, ye need t'combine two strands o'ether along with a curing agent in a Tanaan loom. Ye will need t'seek a skilled brew master t'make the curing agent fer ye. Just 'ave them create it by using two celestial essences, soda an' paeala sap'\nHanding Bor 500 pp will get you an emblem specific to your class and Druzzil's Mystical Sewing Kit, an 8-slot container useful only for ornate or elemental patterns. The patterns drop in various zones.\nBasic recipe is: appropriate ornate pattern, tanaan embroidery needle, appropriate class emblem, 1-3 ethereal silk swatches combined in Druzzil's Sewing Kit. The final combine is no-fail.\n- Arantir's Bracelet of Discovery [item=17841]\n- Arantir's Circlet of Discovery [item=17398]\n- Arantir's Gloves of Discovery [item=17326]\n- Arantir's Leggings of Discovery [item=17327]\n- Arantir's Robe of Discovery [item=17263]\n- Arantir's Sandals of Discovery [item=18006]\n- Arantir's Sleeves of Discovery [item=21306]\n- Elemental Bracelet of the Prime [item=17892]\n- Elemental Cap of the Prime [item=18189]\n- Elemental Gloves of the Prime [item=22128]\n- Elemental Leggings of the Prime [item=17271]\n- Elemental Shroud of the Prime [item=17408]\n- Elemental Sleeves of the Prime [item=21883]\n- Elemental Slippers of the Prime [item=18113]\n- Silken Augmenter's Bracelet [item=17938]\n- Silken Augmenter's Cap [item=17793]\n- Silken Augmenter's Gloves [item=18672]\n- Silken Augmenter's Pantaloons [item=17059]\n- Silken Augmenter's Robe [item=17219]\n- Silken Augmenter's Shoes [item=17242]\n- Silken Augmenter's Sleeves [item=18671]\n- Vorshar's Circlet of the Blight [item=18829]\n- Vorshar's Gloves of the Blight [item=21295]\n- Vorshar's Manacle of the Blight [item=17891]\n- Vorshar's Pants of the Blight [item=17399]\n- Vorshar's Robe of the Blight [item=17272]\n- Vorshar's Sleeves of the Blight [item=21307]\n- Vorshar's Slippers of the Blight [item=18677]",
    },
    {
      id = "2260",
      title = "Leather Ornate Tranquility Armor",
      exp = "04",
      exp_name = "The Planes of Power",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Bor Wharhammer",
      loc = nil,
      triggers = {
        "What emblem?",
        "What about leather?",
        "What about swatches?",
        "emblem",
        "class",
        "chain",
        "silk",
        "leather",
      },
      items_required = {
        { name = "ye one fer the price of 500 platinum pieces", count = 1 },
      },
      rewards = {
        { id = 21869, name = "Beastlord Emblem", type = "item" },
        { id = 14418, name = "Celestial Essence", type = "item" },
        { id = 17229, name = "Cured Ethereal Energy", type = "item" },
        { id = 21871, name = "Druid Emblem", type = "item" },
        { id = 21566, name = "Druzzil's Mystical Sewing Kit", type = "item" },
        { id = 17225, name = "Ethereal Curing Agent", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Tranquility [zone=159]\n**Who:**\n- Bor Wharhammer [npc=11924]\nRating:\n0/2**_\\*__\\*__\\*__\\*__\\*_**\n(Average from 2 ratings)\nInformation:\n**Level:** | 60\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Armour Set\n**Quest Items:**\n- Beastlord Emblem [item=21869]\n- Celestial Essence [item=14418]\n- Cured Ethereal Energy [item=17229]\n- Druid Emblem [item=21871]\n- Druzzil's Mystical Sewing Kit [item=21566]\n- Ethereal Curing Agent [item=17225]\n- Ethereal Silk Swatch [item=17224]\n- Monk Emblem [item=21873]\n- Ornate Leather Boot Pattern [item=21399]\n- Ornate Leather Glove Pattern [item=21398]\n- Ornate Leather Helm Pattern [item=21397]\n- Ornate Leather Pant Pattern [item=21396]\n- Ornate Leather Sleeve Pattern [item=21400]\n- Ornate Leather Tunic Pattern [item=21394]\n- Ornate Leather Wristband Pattern [item=21395]\n- Packet of Paeala Sap [item=15754]\n- Soda [item=14915]\n- Tanaan Embroidery Needle [item=17228]\n**Era:** | !Planes of Power\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- Beastlord\n- Druid\n- Monk\n**Appropriate Races:**\n- All\nEntered: Thu Nov 21 21:10:19 2002\nModified: Tue Dec 5 05:21:04 2023 | | _Each class gets a specific suit of armor by talking to Bor Wharhammer. This is for classes that wear leather._\nBor Wharhammer says 'Greetin's t'ye! Isn't the area 'round 'ere so nice an' quiet? Such a departure from me old days; slaving o'er the forge t'create masterpieces! T'be 'onest, at times I do miss the old forge, but after I created me finest breastplate, it seemed as if nothing else I made could ever live up t'it. So I left me home to'wander the land an' see what I could learn o'the world. I 'ave learned quite a bit from the elders 'ere an' the skilled craftspeople in New Tanaan. I 'ave even devised a type o'emblem that will impart the magic o'tranquility into the user t'create planar armors from pieces o'energy found in the planes.'\nYou say, 'What emblem?'\nBor Wharhammer says 'Well, the emblems dinnae be easy t'craft but I will gladly give ye one fer the price of 500 platinum pieces. They allow a planes traveler with no craftin' skills t'create many fine pieces o'planar armor in a special, magical kit I also 'ave an' will throw in with the price. The kit acts as a focal point fer the wild magic energy o'the Planes. Ye will only be able t'use each emblem an' kit once when ye create the piece, 'owever I dinnae be goin' anywhere soon! Just venture back when ye need another an' dinnae ferget the coin!'\nYou say, 'What about leather?'\nBor Wharhammer says 'Leather armor provides little protection due t'the make-up o'the materials. We shall do our best, 'owever, t'see ye make a quality piece. T'do so, ye must combine a pattern, an emblem, various pieces o'cured ethereal energy an' a Tanaan embroidery needle all within a sewing kit boilin' with magical energy. The cured energy may be problematic fer an unskilled craftsman, 'owever. Just sew two silk ethereal swatches together using a Tanaan embroidery needle within a Tanaan loom. I can just imagine yer next question t'be about swatches, aye?'\nYou say, 'What about swatches?'\nBor Wharhammer sighs at you. 'T'make a swatch, ye need t'combine two strands o'ether along with a curing agent in a Tanaan loom. Ye will need t'seek a skilled brew master t'make the curing agent fer ye. Just 'ave them create it by using two celestial essences, soda an' paeala sap.'\n_Handing Bor 500 pp will get you an emblem specific to your class and Druzzil's Mystical Sewing Kit, an 8-slot container useful only for ornate or elemental patterns. The ornate patterns drop in various zones._\n_Basic recipe is: appropriate ornate pattern, tanaan embroidery needle, appropriate class emblem, 1-3 swatches of cured ethereal energy, combine in Druzzil's Sewing Kit. The final combine is no-fail._\n- Armguards of Enlightenment [item=17962]\n- Boots of the Khati Sha [item=17844]\n- Bracer of Enlightenment [item=21889]\n- Bracer of the Khati Sha [item=21890]\n- Chestwraps of Enlightenment [item=17328]\n- Gauntlets of Enlightenment [item=17878]\n- Gloves of the Khati Sha [item=17845]\n- Headdress of the Khati Sha [item=22186]\n- Helm of Enlightenment [item=22187]\n- Leggings of Enlightenment [item=17329]\n- Leggings of the Khati Sha [item=17239]\n- Sleeves of the Khati Sha [item=17982]\n- Slippers of Enlightenment [item=18008]\n- Tunic of the Khati Sha [item=17273]\n- Wanderer's Sylvan Boots [item=17842]\n- Wanderer's Sylvan Bracer [item=17935]\n- Wanderer's Sylvan Cap [item=21908]\n- Wanderer's Sylvan Gloves [item=17409]\n- Wanderer's Sylvan Leggings [item=17241]\n- Wanderer's Sylvan Sleeves [item=17843]\n- Wanderer's Sylvan Tunic [item=17410]",
    },
    {
      id = "2267",
      title = "Plate Elemental Tranquility Armor",
      exp = "04",
      exp_name = "The Planes of Power",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Bor Wharhammer",
      loc = nil,
      triggers = {
        "Hail, Bor Wharhammer",
        "What emblem?",
        "What planar armors?",
        "What plate?",
        "emblem",
        "class",
        "chain",
        "silk",
      },
      items_required = {
        { name = "ye one fer the price of 500 platinum pieces", count = 1 },
        { name = "him 500 platinum pieces:_", count = 1 },
      },
      rewards = {
        { id = 21868, name = "Bard Emblem", type = "item" },
        { id = 21870, name = "Cleric Emblem", type = "item" },
        { id = 21365, name = "Elemental Boot Mold", type = "item" },
        { id = 21366, name = "Elemental Bracer Mold", type = "item" },
        { id = 21367, name = "Elemental Gauntlet Mold", type = "item" },
        { id = 21369, name = "Elemental Greaves Mold", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Tranquility [zone=159]\n**Who:**\n- Bor Wharhammer [npc=11924]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 60\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Armour Set\n**Quest Items:**\n- Bard Emblem [item=21868]\n- Cleric Emblem [item=21870]\n- Elemental Boot Mold [item=21365]\n- Elemental Bracer Mold [item=21366]\n- Elemental Gauntlet Mold [item=21367]\n- Elemental Greaves Mold [item=21369]\n- Elemental Helm Mold [item=21370]\n- Elemental Vambrace Mold [item=21371]\n- Ethereal Sheet of Metal [item=17230]\n- Mystical Furnace of Ro [item=21882]\n- Paladin Emblem [item=21875]\n- Shadowknight Emblem [item=21881]\n- Tanaan Smithing Hammer [item=17128]\n- Timeless Breastplate Mold [item=21372]\n- Warrior Emblem [item=21879]\n**Related Zones:**\n- Plane of Time B [zone=178]\n**Era:** | !Planes of Power\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- Bard\n- Cleric\n- Paladin\n- Shadowknight\n- Warrior\n**Appropriate Races:**\n- All\nEntered: Mon Nov 25 20:28:05 2002\nModified: Tue Dec 5 05:21:04 2023 | | You say, 'Hail, Bor Wharhammer'\nBor Wharhammer says 'Greetin's t'ye \\_\\_\\_\\_\\_\\_! Isn't the area 'round 'ere so nice an' quiet? Such a departure from me old days; slaving o'er the forge t'create masterpieces! T'be 'onest, at times I do miss the old forge, but after I created me finest breastplate, it seemed as if nothing else I made could ever live up t'it. So I left me home to'wander the land an' see what I could learn o'the world. I 'ave learned quite a bit from the elders 'ere an' the skilled craftspeople in New Tanaan. I 'ave even devised a type o'emblem that will impart the magic o'tranquility into the user t'create planar armors from pieces o'energy found in the planes.'\nYou say, 'What emblem?'\nBor Wharhammer says 'Well, the emblems dinnae be easy t'craft but I will gladly give ye one fer the price of 500 platinum pieces. They allow a planes traveler with no craftin' skills t'create many fine pieces o'planar armor in a special, magical kit I also 'ave an' will throw in with the price. The kit acts as a focal point fer the wild magic energy o'the Planes. Ye will only be able t'use each emblem an' kit once when ye create the piece, 'owever I dinnae be goin' anywhere soon! Just venture back when ye need another an' dinnae ferget the coin!'\nYou say, 'What planar armors?'\nBor Wharhammer says 'From me understanding, the very fabric o'the planes is so strong out 'ere, it can be found in raw form the deeper ye traverse. Anyone who ventures far into the planes finds that they must wear excellent armor t'protect them from the savage environment. The very essence of planar energy can be focused into a form that can fit our shape. As ye progress deeper into the planes, ye will find many molds an' patterns with which t'base a set o'armor. If ye want t'know 'ow t'craft the various types o'armor, I can instruct ye about plate, chain, leather an' silk.'\nYou say, 'What plate?'\nBor Wharhammer says 'Ahhhhh \\_\\_\\_\\_\\_\\_! The fine rigid armor that can stop a shaft from piercing yer heart! Too bad it be so cumbersome an' difficult t'move about in. To construct a piece o'plate armor, ye need t'combine a plate mold, an emblem, various amounts o'sheet metal an' use one o'those crafty Tanaan smithin' 'ammers all within a furnace touched by Ro. Ethereal metal sheet construction is another matter. Ye will need t'combine two bricks o'ethereal energy, an ethereal temper an' a Tanaan smithin' 'ammer within a Tanaan forge. I would seek a skilled craftsperson t'make the metal sheets fer ye; the emblem will enable ye t'craft the final armor piece no matter what yer skill be.'\n_If you give him 500 platinum pieces:_\nBor Wharhammer says 'Wonderful! This coin will go towards me fines with the Myrist library. They charge quite a bit fer overdue volumes! 'ere be yer emblem an' a kit in which ye may craft planar armor. The kit only 'as enough magical energy t'craft one piece before the energies expire, be sure ye understand. May the armor ye make with it provide ye with much protection.'\n_You receive a class-specific emblem and a Mystical Furnace of Ro, an 8-slot container useful only for combines involving ornate or elemental molds. The ornate molds drop in various zones._\n_Basic recipe is: appropriate ornate plate mold, class-specific emblem, tanaan smithing hammer, 1-3 ethereal sheets of metal. Combine in the Mystical Furnace of Ro. The final combine is no-fail._\n\n---\n\nMaking Ornate or Elemental PoP Armor EverQuest TLP Mangler - YouTube\nTap to unmute\nMaking Ornate or Elemental PoP Armor EverQuest TLP Mangler Ion Blaze Gaming\nIon Blaze Gaming11.5K subscribers\nWatch on\n- Grimror's Boots of the Plagues [item=18154]\n- Grimror's Bracer of the Plagues [item=18168]\n- Grimror's Gauntlets of the Plagues [item=19047]\n- Grimror's Greaves of the Plagues [item=18155]\n- Grimror's Guard of the Plagues [item=23636]\n- Grimror's Helm of the Plagues [item=18167]\n- Grimror's Sleeves of the Plagues [item=17927]\n- Raex's Armplates of Destruction [item=17744]\n- Raex's Boots of Destruction [item=17929]\n- Raex's Bracer of Destruction [item=17931]\n- Raex's Chestplate of Destruction [item=18079]\n- Raex's Gauntlets of Destruction [item=17930]\n- Raex's Greaves of Destruction [item=17932]\n- Raex's Helm of Destruction [item=17220]\n- Rizlona's Fiery Boots [item=17830]\n- Rizlona's Fiery Bracer [item=18161]\n- Rizlona's Fiery Chestplate [item=17791]\n- Rizlona's Fiery Gauntlets [item=18195]\n- Rizlona's Fiery Greaves [item=18160]\n- Rizlona's Fiery Helm [item=17776]\n- Rizlona's Fiery Vambraces [item=17831]\n- Trydan's Armplates of Nobility [item=18014]\n- Trydan's Boots of Nobility [item=18159]\n- Trydan's Bracer of Nobility [item=17777]\n- Trydan's Chestplate of Nobility [item=18157]\n- Trydan's Gauntlets of Nobility [item=18172]\n- Trydan's Greaves of Nobility [item=18158]\n- Trydan's Helm of Nobility [item=18171]\n- Ultor's Boots of Faith [item=18166]\n- Ultor's Bracer of Faith [item=18164]\n- Ultor's Chestguard of Faith [item=22304]\n- Ultor's Gauntlets of Faith [item=18004]\n- Ultor's Greaves of Faith [item=18156]\n- Ultor's Helm of Faith [item=18165]\n- Ultor's Vambraces of Faith [item=17961]",
    },
    {
      id = "2288",
      title = "The Binden Concerrentia (Talisman \\#3)",
      exp = "04",
      exp_name = "The Planes of Power",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Elder Clinka",
      loc = { y = -385.0, x = -1275.0, z = -900.0 },
      triggers = {
        "Hail, Elder Clinka",
        "Plane of Air",
        "Plane of Fire",
        "Plane of Water",
      },
      items_required = {
        { name = "me a moment to scan over this for you", count = 1 },
      },
      rewards = {
        { id = 20930, name = "Living Fragment of Air", type = "item" },
        { id = 20929, name = "Living Fragment of Earth", type = "item" },
        { id = 20932, name = "Living Fragment of Fire", type = "item" },
        { id = 20931, name = "Living Fragment of Water", type = "item" },
        { id = 17785, name = "Powered Clockwork Talisman", type = "item" },
        { id = 34928, name = "Sealed Lined Case", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Tranquility [zone=159]\n**Who:**\n- Elder Clinka [npc=10881]\nRating:\n0/2**_\\*__\\*__\\*__\\*__\\*_**\n(Average from 2 ratings)\nInformation:\n**Level:** | 65\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Loot\n**Quest Items:**\n- Living Fragment of Air [item=20930]\n- Living Fragment of Earth [item=20929]\n- Living Fragment of Fire [item=20932]\n- Living Fragment of Water [item=20931]\n- Powered Clockwork Talisman [item=17785]\n- Sealed Lined Case [item=34928]\n- Small Lined Case [item=34927]\n- The Talisman Schematic [item=28881]\n**Related Zones:**\n- Doomfire, the Burning Lands [zone=168]\n- Eryslai, the Kingdom of Wind [zone=175]\n- Ragrax, Stronghold of the Twelve [zone=184]\n- Reef of Coirnav [zone=166]\n- Vegarlson, the Earthen Badlands [zone=169]\n**Related Creatures:**\n- a temple guardian [npc=11335]\n**Related Quests:**\n- Jimlok's Friend (Clockwork Talisman #1) [quest=2202]\n- Powered Clockwork Talisman (#2) [quest=2287]\n**Era:** | !Planes of Power\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Dec 18 21:40:41 2002\nModified: Tue Dec 5 05:21:04 2023 | | _You must complete the previous two quests before you can do this quest._\n_Elder Clinka is found in the Plane of Tranquility at loc -385, -1275, -900, not far from the Plane of Nightmare entrance._\nYou say, 'Hail, Elder Clinka'\nElder Clinka does not seem to notice you.\n_Hand her The Talisman Schematic (the note you got at the end of the previous quest)._\nElder Clinka says 'It is a pleasure to meet you. I've heard a great deal about you from the other elders. Please give me a moment to scan over this for you.'\nElder Clinka scans the schematic for a few seconds, mumbling as she reads, 'This parchment states that you are to place a small shard of concentrated elemental matter into each of the holes in your talisman.' She points a finger to the diagram as she begins to recount what she has learned from it, 'They would then need to be locked into place, as the diagram indicates here.'\nElder Clinka says 'If you bring me a fragment or shard of some living creature from each of the elemental planes, I will see if we can make this device work. Place them in this box with your talisman and combine them together before returning the box to me. In the meantime, I will continue to translate this document from its original language.'\n_You receive a Small Lined Case. Place the following five items into the case:_\n\\\\* Powered Clockwork Talisman (the reward from the previous quest in the series)\n\\\\* A Living Fragment of Air (dropped by any Temple Guardian in the Eryslai, the Kingdom of Air [Plane of Air])\n\\\\* A Living Fragment of Fire (dropped by any Jopal in Doomfire, the Burning Lands [Plane of Fire])\n\\\\* A Living Fragment of Water (dropped by any Trilouns in the Reef of Coirnav [Plane of Water])\n\\\\* A Living Fragment of Earth (dropped by any Vekerchikis in Vegarlson, the Earthen Badlands or Ragrax, Stronghold of the Twelve [Plane of Earth A and B, respectively])\n_Combine them to produce a Sealed Lined Case._\nYou have fashioned the items together to create something new!\n_Hand the Case to Elder Clinka._\nElder Clinka carefully opens the small box and takes several small tools from the pocket in her robe. Her nimble fingers place the glowing elemental pieces into the appropriate sockets and covers them with several small caps that she must have made while you were away.\nElder Clinka then looks up at you and says, 'This device is called the Binden Concerrentia. Its true power will be revealed to you soon. This document describes it as a device that is meant to convert the energy that can be found in true prime elemental matter, into an entirely new form of energy. The schematic states that this energy will 'bind you in the now'. I am not sure what that means, but I believe that you will soon find out.\nElder Clinka says 'Take care of it and keep it with you at all times. I feel that your journey from this point will only become more dangerous. Perhaps this device will play a role in all of that. Move forward along the path of enlightenment. May the Balance guide your fate.'\n_You receive The Binden Concerrentia in your inventory._\n- The Binden Concerrentia [item=17786]",
    },
    {
      id = "8049",
      title = "Into the Temple (A) (Quellious' Request)",
      exp = "22",
      exp_name = "The Broken Mirror",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Quellious",
      loc = nil,
      triggers = {
        "Hail, Quellious",
        "I hope that you don",
        "I am nothing if not discreet.",
        "_Goddess and Quest Giver_",
        "_Mayor and Quest Giver_",
        "worries",
        "discreet",
      },
      items_required = {
      },
      rewards = {
        { id = 124218, name = "Remnant of Tranquility", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Plane of Tranquility [zone=159]\n**Who:**\n- Quellious [ _Goddess and Quest Giver_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Time:** | 360\n**Level:** | 75\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | No\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Time Limit:** | 06:00:00\n**Related Zones:**\n- Plane of Health [zone=1057]\n- Sul Vius: Demiplane of Decay [zone=1059]\n- Sul Vius: Demiplane of Life [zone=1058]\n**Related Creatures:**\n- Mayor Salvador West [ _Mayor and Quest Giver_]\n**Related Quests:**\n- Into the Temple (B) [quest=8081]\n- Seal of Approval [quest=8080]\n**Era:** | !The Broken Mirror\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 26 03:33:34 2015\nModified: Tue Dec 5 05:21:04 2023 | | You say, 'Hail, Quellious'\nQuellious says 'Hello friend. It is nice to return home. I hope things are well with you and that you have no [worries].'\nYou say, 'I hope that you don't have worries.'\nQuellious says 'Even gods have worries, I'm afraid. I, for example, am concerned for my friend Rodcet Nife. You see, he has found a new ally, whom I have not met. But from my conversations with him, I sense an unusual amount of inner conflict within him. I sense that the source of this conflict, and even the conflict itself is unknown to Rodcet. I believe it is this new alliance. It is as if in his heart he knows there is something wrong, but won't see what it is. I would like to speak with him about this, but I would like to know more first. I could use a [discreet] agent to learn about this new ally, Anashti Sul.'\nYou say, 'I am nothing if not discreet.\n'\nQuellious says 'Ah, thank you very much. Please, be careful and discreet. If I am wrong I would not like to cause my friend any turmoil.'\nYou have been assigned the task 'Into the Temple.'\n\\-\\-\n'Into the Temple' is a shared task with a 6-hour time limit.\nThe first step is \"Speak with someone in authority in Sul Vius about the religion of Anashti Sul.\" (Status 0/1, Zone: ALL)\n\"At the prompting of the goddess of Tranquility, Quellious, you seek information about Anashti Sul. There is a good chance that some information about her can be found in her own realm. Find someone that can direct you to such information.\"\nFind your way to Sul Vius, Demiplane of Life. When you get there, find Mayor Salvador West.\nHail him and then say Anashti Sul\n\n---\n\n7 platinum, 5 gold\nExperience\nRemnants of Tranquility (Variable number of Remnants of Tranquility based on your level)\nThis unlocks the Seal of Approval [quest=8080] task in Plane of Health. Doing both tasks (they're easy and don't require any killing) gives close to a full level of experience at level 75.\n**Submitted by:** Oxgoad\n- Remnant of Tranquility [item=124218]",
    },
  },
}
