-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Muramite Proving Grounds (provinggrounds)
-- Total Quests: 6
-- ============================================================================

return {
  zone = "provinggrounds",
  zone_name = "Muramite Proving Grounds",
  quests = {
    {
      id = "3006",
      title = "The Mastery of Hate (Raid)",
      exp = "08",
      exp_name = "Omens of War",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Projection of Mind",
      loc = nil,
      triggers = {
        "Hail, Projection of Mind",
        "Hatred.",
        "Hail, Master of Hate",
        "We are ready to begin.",
        "begin",
      },
      items_required = {
      },
      rewards = {
        { id = 32705, name = "Bloodband of Malice", type = "item" },
        { id = 32706, name = "Earring of Mental Incursion", type = "item" },
        { id = 32687, name = "Envenomed Leggings of Enmity", type = "item" },
        { id = 30539, name = "Glowing Muramite Rune", type = "item" },
        { id = 30538, name = "Greater Muramite Rune", type = "item" },
        { id = 32711, name = "Greaves of Seething Rage", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Muramite Proving Grounds [zone=263]\n**Who:**\n- Projection of Mind [npc=16213]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 70\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Loot\n**Related Zones:**\n- Proving Grounds: The Mastery of Hate [zone=291]\n**Related Creatures:**\n- Feeble Direpup [npc=18726]\n- Ferocious Direpup [npc=18724]\n- Master of Hate [npc=17059]\n- Pliant Direpup [npc=18725]\n- Shell of the Master [npc=16928]\n- Voracious Feran [npc=17435]\n**Related Quests:**\n- Access to Asylum of Anguish [quest=2978]\n- The Mastery of Adaptation (Raid) [quest=3012]\n- The Mastery of Corruption (Raid) [quest=3008]\n- The Mastery of Endurance (Raid) [quest=2997]\n- The Mastery of Foresight (Raid) [quest=3014]\n- The Mastery of Specialization (Raid) [quest=3010]\n**Era:** | !Omens of War\nRecommended:\n**Group Size:** | Raid\n**Min. # of Players:** | 18\n**Max. # of Players:** | 54\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 7 21:22:37 2004\nModified: Tue Dec 5 05:21:04 2023 | | _This is a raid trial._\n_Find the Projection of Mind in the northern part of the Muramite Proving Grounds._\nYou say, 'Hail, Projection of Mind'\nProjection of Mind says, 'Halt, \\_\\_\\_\\_\\_\\_, and hear my words. Your background and your status are of no consequence. All are welcome to participate in the trials to prove their worth, or die trying. Whosoever approaches me has adressed the embodiment of mind, keeper of the trials of Fear and Hatred. The former is a small-scale test, while the latter is large-scale. My task is to explain the rules and usher hopefuls into the battle arena. Would you like to hear the rule for small-scale or large-scale trials or do you wish to enroll in Fear or Hatred?'\nYou say, 'Hatred.'\nProjection of Mind says, 'Anger is a tool if you wield it correctly. Invoking hatred in your enemies will provoke them into predictable and controllable behaviour. Can you harness your foe's hatred and twist it to your advantage ? If you have this ability now is the opportunity to prove your worth.'\n_You have entered Proving Grounds: The Mastery of Hate._\nYou say, 'Hail, Master of Hate'\nMaster of Hate says, 'This is the Mastery of Hate trial. You must incite your enemies to focus their rage on those who are best equpped to handle it. Should your force exhaust your defensive members at any point in time, you will fail. Are you ready to [begin]?'\nYou say, 'We are ready to begin.'\n_The trial has begun. You cannot bring additional people into your expedition at this time._\nMaster of Hate says 'Very well! Let the battle commence!'\n_As you enter the chamber you will see six Voracious Ferans (level 73+) on the small platforms. The first step towards winning this trial is killing those six mobs which will spawn loads of adds (Pliant, Ferocious and Feeble Direpup, all cast Lash Out). After they are down the Master of Hate will come alive and has to be killed as well. He summons, rampages, and enrages_\n_Upon successful completion, a Shell of the Master spawns with some loot for the raid._\n_This trial also results in the Mastery of Mind Rune, one of six pieces needed for Citadel of Anguish access._\n**Submitted by:** Saraban, Darkwind\n- Bloodband of Malice [item=32705]\n- Earring of Mental Incursion [item=32706]\n- Envenomed Leggings of Enmity [item=32687]\n- Glowing Muramite Rune [item=30539]\n- Greater Muramite Rune [item=30538]\n- Greaves of Seething Rage [item=32711]\n- Leggings of Fearsome Deeds [item=32685]\n- Legplates of Abhorrent Memories [item=32712]\n- Mastery of Mind Rune [item=33015]\n- Muramite Aggressor's Bulwark [item=32707]\n- Ring of Ire Intent [item=32708]\n- Seal: Mastery of All [item=33023]\n- Seething Fists of Slaughter [item=32709]\n- Totem of Shattered Hope [item=32710]\n- Warped Mask of Animosity [item=32686]",
    },
    {
      id = "3008",
      title = "The Mastery of Corruption (Raid)",
      exp = "08",
      exp_name = "Omens of War",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Projection of Power",
      loc = { y = -1000.0, x = -3000.0, z = 0.0 },
      triggers = {
        "Hail, Projection of Power",
        "Corruption",
        "Hail, [Name of NPC]",
        "We were expecting a fight",
        "Name of NPC",
        "expecting a fight",
      },
      items_required = {
      },
      rewards = {
        { id = 32665, name = "Bracelet of the Corrupter", type = "item" },
        { id = 32667, name = "Bracer of Corrupted Souls", type = "item" },
        { id = 32703, name = "Bracer of the Debauched", type = "item" },
        { id = 67882, name = "Brittle Blade of Strategy", type = "item" },
        { id = 58142, name = "Brittle Blade of Tactics", type = "item" },
        { id = 67881, name = "Ceremonial Battle Boots", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Muramite Proving Grounds [zone=263]\n**Who:**\n- Projection of Power [npc=16214]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 70\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Expedition\n**Quest Goal:**\n- Advancement\n- Loot\n**Failure Lockout Timer**: 03:00:00\n**Success Lockout Timer**: 123:00:00\n**Related Zones:**\n- Proving Grounds: The Mastery of Corruption [zone=325]\n**Related Creatures:**\n- Allaina Deepeyes [npc=19922]\n- Amuea Darkvein [npc=21049]\n- Bennia Hembar [npc=19899]\n- Bibladrap Mindsnapper [npc=19908]\n- Cadavrox Bonebringer [npc=19919]\n- Ceela Tullman [npc=19907]\n- Eira Varinger [npc=19909]\n- Endaar Flashpoint [npc=19912]\n- Esprit Boilingblood [npc=19928]\n- Etherrakor the Silent [npc=19897]\n- Fiddap Clakburner [npc=19916]\n- Fueanna Swarbri [npc=21047]\n- Hemik Pyus [npc=19903]\n- Huhn-Abram`s corpse [npc=19920]\n- Ikkitsoru Firekindle [npc=21050]\n- Kathien [npc=19913]\n- Kipper Twain [npc=19906]\n- Lopret Deadscream [npc=24396]\n- Mazzie Melkhor [npc=24398]\n- Nakert Grimmagus [npc=19905]\n- Nicolai Yule [npc=19901]\n- Nozbif Aetria [npc=19914]\n- Pipok Imblot [npc=19904]\n- Pirallan [npc=24397]\n- Qohme Meadra [npc=19910]\n- Rebthik Soulreaver [npc=19923]\n- Sammu Ionua [npc=21048]\n- Shell of the Corrupted [npc=16923]\n- Sheru Embraciu [npc=19900]\n- Slly Stonestance [npc=19902]\n- Tempko [npc=19911]\n- Texur Shadowprey [npc=19926]\n- Tremura Soulheart [npc=19898]\n- Truwana Graveblood [npc=19929]\n- Ulder Emberfire [npc=19927]\n- Uronius Hight [npc=19921]\n- Valerian Kimble [npc=19925]\n- Verigne Swiftshadow [npc=19924]\n- Xyrashue VitSoor [npc=19915]\n**Related Quests:**\n- Access to Asylum of Anguish [quest=2978]\n- The Mastery of Adaptation (Raid) [quest=3012]\n- The Mastery of Endurance (Raid) [quest=2997]\n- The Mastery of Foresight (Raid) [quest=3014]\n- The Mastery of Hate (Raid) [quest=3006]\n- The Mastery of Specialization (Raid) [quest=3010]\n**Era:** | !Omens of War\nRecommended:\n**Group Size:** | Raid\n**Min. # of Players:** | 7\n**Max. # of Players:** | 54\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 7 21:23:38 2004\nModified: Tue Dec 5 05:21:04 2023 | | _This is a raid trial._\n_Find the Projection of Power at location -1000, -3000 (northeastern portion of the zone)._\nYou say, 'Hail, Projection of Power'\nProjection of Power says, 'Halt, \\_\\_\\_\\_\\_, and hear my words. Your background and your status are of no consequence. All are welcome to participate in the trials to prove their worth, or die trying. Whosoever approaches me has adressed the embodiment of power, keeper of the trials of Destruction and Corruption. The former is a small-scale test, while the latter is large-scale. My task is to explain the rules and usher hopefuls into the battle arena. Would you like to hear the rule for small-scale or large-scale trials or do you wish to enroll in Destruction or Corruption?'\nYou say, 'Corruption'\nProjection of Power says \"Prepare yourself for the greatest challenge of all. The Mastery of Corruption will test your battle prowess as well as your strength of character. Can you see through corruption and rout it out, or are you corrupt yourself ? The spoils of war include the chance to rewrite history. The victor will decide who was right and who was wrong, but in the end - do such things ever matter?'\n_You have entered Proving Grounds: Mastery of Corruption._\n_Inside you see Huhn-Abram's Corpse on the platform with several NPCs lying around him._\n_Pick any of those NPCs and hail her/him..._\nYou say, 'Hail, [Name of NPC]'\n[Name of NPC] says, 'Hail to you as well, \\_\\_\\_\\_\\_, but what exactly are you doing here ? I'm sorry, but as you can see, you've arrived too late. Moments ago we defeated Huhn-Abram the Corrupted and we're currently regrouping and resurrecting our fallen members. Please respect our control of this area and leave at once. I have to admit your presence here is making me a bit nervous. We don't want any trouble.' They stare at you fearfully, '\"So, are you going to leave us in peace, or did you come [expecting a fight]?'\nYou say, 'We were expecting a fight'\n[Name of NPC] says 'I should have known the trial of corruption wouldn't be so easy. Bring it on!'\n_The trial has begun. You cannot bring additional people into your expedition at this time._\nThree waves of NPCs will spawn (6, 12, 18) which act much like real players and come in eight different classes. All NPCs are level 70. Kill them and collect your reward:\n_Shell of the Corrupted spawns afterward with a number of different loot possibilities._\n_Upon completion, you will also receive a Mastery of Power Rune, one of six pieces needed for Citadel of Anguish access._\n**What are the lockout timers?**\n**Submitted by:** Saraban, Darkwind\n- Bracelet of the Corrupter [item=32665]\n- Bracer of Corrupted Souls [item=32667]\n- Bracer of the Debauched [item=32703]\n- Brittle Blade of Strategy [item=67882]\n- Brittle Blade of Tactics [item=58142]\n- Ceremonial Battle Boots [item=67881]\n- Cloak of the Faithless [item=32700]\n- Cord of the Malcontent [item=32701]\n- Darkiron Bow of Betrayal [item=32485]\n- Fangs of the Serpent [item=32702]\n- Glowing Muramite Rune [item=30539]\n- Greater Muramite Rune [item=30538]\n- Howling Bloodstained Bulwark [item=32666]\n- Mastery of Power Rune [item=33016]\n- Screaming Skull of Discontent [item=32668]\n- Seal: Mastery of All [item=33023]\n- Shawl of Nefarious Favor [item=32482]\n- Wristband of Spectral Corruption [item=32704]",
    },
    {
      id = "3009",
      title = "The Mastery of Efficiency (Group)",
      exp = "08",
      exp_name = "Omens of War",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Projection of Arcana",
      loc = { y = -1090.44, x = 1722.92, z = -306.85 },
      triggers = {
        "Hail, Projection of Arcana",
        "Small-scale.",
        "Efficiency?",
        "Hail",
        "begin",
        "small-scale",
        "large-scale",
        "Efficiency",
      },
      items_required = {
      },
      rewards = {
        { id = 32902, name = "Eyepatch of Expert Archery", type = "item" },
        { id = 32663, name = "Girdle of Efficiency", type = "item" },
        { id = 30539, name = "Glowing Muramite Rune", type = "item" },
        { id = 30538, name = "Greater Muramite Rune", type = "item" },
        { id = 35121, name = "Journal of the Prime Disciple", type = "item" },
        { id = 31942, name = "Rime-Encrusted Pikestaff", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Muramite Proving Grounds [zone=263]\n**Who:**\n- Projection of Arcana [npc=16211]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Time:** | 30 minutes\n**Level:** | 70\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Expedition\n**Quest Goal:**\n- Advancement\n- Loot\n**Related Zones:**\n- Proving Grounds: The Mastery of Efficiency [zone=330]\n**Related Creatures:**\n- Enforcer of Efficiency [npc=17947]\n- Master of Efficiency [npc=22090]\n- Muramite Commander [npc=17049]\n- Shell of the Master [npc=16922]\n- a Muramite soldier [npc=17051]\n- an elite Muramite soldier [npc=17050]\n**Related Quests:**\n- The Mastery of Destruction (Group) [quest=3007]\n- The Mastery of Fear (Group) [quest=3005]\n- The Mastery of Ingenuity (Group) [quest=3011]\n- The Mastery of Subversion (Group) [quest=3013]\n- The Mastery of Weaponry (Group) [quest=3004]\n**Era:** | !Omens of War\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 2\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 7 21:24:15 2004\nModified: Tue Dec 5 05:21:04 2023 | | _This is a single group trial._\n_The Projection of Arcana may be found at -1090.44, 1722.92, -306.85._\nYou say, 'Hail, Projection of Arcana'\nProjection of Arcana says 'Halt, Dark Elf, and hear my words. Your background and your status are of no consequence. All are welcome to participate in the trials to prove their worth, or die trying. Whosoever approaches me has addressed the embodiment of Arcana, keeper of the trials of Efficiency and Specialization. The former is a small-scale test, while the latter is large-scale. My task is to explain the rules and usher hopefuls into the battle arena. Would you like to hear the rules for [small-scale] or [large-scale] trials, or do you wish to enroll in [Efficiency] or [Specialization]?'\nYou say, 'Small-scale.'\nProjection of Arcana says 'Every test has its rules and these trials are no exception. The following guidelines must be followed to the letter, or else you stand to forfeit or perish. You are allowed no more than six participants in the battle. Once the trial has begun, you must remain in the combat area. Violators of this rule will be warned and then destroyed. Your progress will be carefully monitored. If you take too long, you will fail. These are the rules and they are not negotiable.'\nYou say, 'Efficiency?'\nProjection of Arcana says 'While it can be admirable to defeat the opposition while in prime condition, a more accurate test of one's mettle is to tackle an opponent while fatigued and weary - yet still walk away victorious. If you have this ability, now is the opportunity to prove your worth!'\n_On zoning into the trial, you will find the Master of Efficiency standing on the central podium.._\nYou say, 'Hail'\nMaster of Efficiency says 'This is the Mastery of Efficiency trial. You must demonstrate your ability to function under less than perfect conditions, battling with limited resources. Are you ready to [begin]?'\nYou say, 'begin'\nThe trial has begun. You cannot bring any additional people into your expedition at this time.\nMaster of Efficiency says 'Very well! Let the battle commence!'\n_All mobs in this trial are fully slowable._\n_This trial is similar to the Trial of Execution in the Plane of Justice. You must survive four waves of 3-4 mobs, and kill them in sufficient time (you have four minutes per wave). The mobs involved are a Muramite soldier (mezzable), an elite Muramite soldier (unmezzable), and \"Muramite Commander\" (unmezzable)._\n_Note: Every five minutes, the unresistable AE Test of Efficiency goes off._\n_When the final wave's four minute timer runs out (and assuming you've actually survived), the Enforcer of Efficiency spawns and attacks. Kill him to win the trial. A Shell of the Master spawns with the loot._\n**Need all dialogues, /loc of quest-giver, emotes during fight, time limit for expedition, lockout timers for success and failure, minimum group size to get expedition.**\n- Eyepatch of Expert Archery [item=32902]\n- Girdle of Efficiency [item=32663]\n- Glowing Muramite Rune [item=30539]\n- Greater Muramite Rune [item=30538]\n- Journal of the Prime Disciple [item=35121]\n- Rime-Encrusted Pikestaff [item=31942]",
    },
    {
      id = "3010",
      title = "The Mastery of Specialization (Raid)",
      exp = "08",
      exp_name = "Omens of War",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Projection of Arcana",
      loc = nil,
      triggers = {
        "Hail, Projection of Arcana",
        "Specialization",
        "Hail, Master of Specialization",
        "We are ready to begin",
        "begin",
      },
      items_required = {
      },
      rewards = {
        { id = 32681, name = "Bonecleaver", type = "item" },
        { id = 32699, name = "Brute's Gaudy Shoulderspines", type = "item" },
        { id = 32678, name = "Chain Gauntlets of Adroitness", type = "item" },
        { id = 32680, name = "Deathlace", type = "item" },
        { id = 32163, name = "Gauntlets of Singular Mastery", type = "item" },
        { id = 32679, name = "Gloves of the Adept", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Muramite Proving Grounds [zone=263]\n**Who:**\n- Projection of Arcana [npc=16211]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Time:** | Hours\n**Level:** | 70\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Loot\n**Related Zones:**\n- Proving Grounds: The Mastery of Specialization [zone=328]\n**Related Creatures:**\n- Master of Specialization [npc=16710]\n- Shell of the Master [npc=16800]\n**Related Quests:**\n- Access to Asylum of Anguish [quest=2978]\n- The Mastery of Adaptation (Raid) [quest=3012]\n- The Mastery of Corruption (Raid) [quest=3008]\n- The Mastery of Endurance (Raid) [quest=2997]\n- The Mastery of Foresight (Raid) [quest=3014]\n- The Mastery of Hate (Raid) [quest=3006]\n**Era:** | !Omens of War\nRecommended:\n**Group Size:** | Raid\n**Min. # of Players:** | 18\n**Max. # of Players:** | 54\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 7 21:24:41 2004\nModified: Tue Dec 5 05:21:04 2023 | | _This is a raid trial._\n_Find the Projection of Arcana in the northwestern portion of the Muramite Proving Grounds._\nYou say, 'Hail, Projection of Arcana'\nProjection of Arcana says, 'Halt, \\_\\_\\_\\_\\_, and hear my words. Your background and your status are of no consequence. All are welcome to participate in the trials to prove their worth, or die trying. Whosoever approaches me has adressed the embodiment of Foresight, keeper of the trials of Efficiency and Specialization. The former is a small-scale test, while the latter is large-scale. My task is to explain the rules and usher hopefuls into the battle arena. Would you like to hear the rule for small-scale or large-scale trials or do you wish to enroll in Efficiency or Specialization?'\nYou say, 'Specialization'\nProjection of Arcana says, 'At times it pays to be focused in your abilities, and at times it does not. This trial will test your skill at using your strengths when they are most effective, and otherwise relying on your companions. If you have this ability now is the time to prove your worth.'\n_You have entered Proving Grounds: Mastery of Specialization._\nYou say, 'Hail, Master of Specialization'\nMaster of Specialization says, 'This is the Mastery of Specialization trial. You must demonstrate your ability to use your primary skills and fall back on your secondary skillset when necessary. Are you ready to [begin]?'\nYou say, 'We are ready to begin'\nMaster of Specialization says \"Very well ! Let the battle commence !\"\n_The trial has begun. You cannot bring additional people into your expedition at this time._\nKill Master of Specialization, who has a few AEs: Rigidity, Imprecision, Curse of Misfortune, Impurity.\n_Shell of the Master spawns following the Master of Specialization's death._\n_Also upon completion, you will also receive a Mastery of Arcana Rune, one of six pieces needed for Citadel of Anguish access._\n**Submitted by:** Saraban, Darkwind\n- Bonecleaver [item=32681]\n- Brute's Gaudy Shoulderspines [item=32699]\n- Chain Gauntlets of Adroitness [item=32678]\n- Deathlace [item=32680]\n- Gauntlets of Singular Mastery [item=32163]\n- Gloves of the Adept [item=32679]\n- Glowing Muramite Rune [item=30539]\n- Greater Muramite Rune [item=30538]\n- Jagged Pureblade [item=31904]\n- Laced Gloves of Superiority [item=32164]\n- Mastery of Arcana Rune [item=33014]\n- Seal: Mastery of All [item=33023]\n- Specialist's Green Earstone [item=32677]\n- Stud of Focused Aptitude [item=32165]\n- Two-Toned Fur Cape [item=32483]",
    },
    {
      id = "3013",
      title = "The Mastery of Subversion (Group)",
      exp = "08",
      exp_name = "Omens of War",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Projection of Tactics",
      loc = { y = -5530.0, x = -1585.0, z = 0.0 },
      triggers = {
        "Hail, Projection of Tactics",
        "Subversion.",
        "small-scale",
        "large-scale",
        "Subversion",
        "Foresight",
      },
      items_required = {
      },
      rewards = {
        { id = 34929, name = "Copper Seal of Subversion", type = "item" },
        { id = 34931, name = "Gold Seal of Subversion", type = "item" },
        { id = 24336, name = "Greater Scrying Stone", type = "item" },
        { id = 34930, name = "Silver Seal of Subversion", type = "item" },
        { id = 32980, name = "Bauble of Premonitions", type = "item" },
        { id = 32553, name = "Emblem of the False Priestess", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Muramite Proving Grounds [zone=263]\n**Who:**\n- Projection of Tactics [npc=16014]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 70\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Expedition\n**Quest Goal:**\n- Loot\n**Quest Items:**\n- Copper Seal of Subversion [item=34929]\n- Gold Seal of Subversion [item=34931]\n- Greater Scrying Stone [item=24336]\n- Silver Seal of Subversion [item=34930]\n**Related Zones:**\n- Proving Grounds: The Mastery of Subversion [zone=293]\n**Related Creatures:**\n- Master of Subversion [npc=16704]\n- Shell of the Master [npc=16801]\n- a dragorn guardian [npc=17566]\n- a dragorn patroller [npc=17565]\n- a hexed chest [npc=17740]\n- a spellbound chest [npc=17742]\n- an ironbound chest [npc=17741]\n**Related Quests:**\n- The Mastery of Destruction (Group) [quest=3007]\n- The Mastery of Efficiency (Group) [quest=3009]\n- The Mastery of Fear (Group) [quest=3005]\n- The Mastery of Ingenuity (Group) [quest=3011]\n- The Mastery of Weaponry (Group) [quest=3004]\n**Era:** | !Omens of War\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 7 21:28:05 2004\nModified: Tue Dec 5 05:21:04 2023 | | Find the Projection of Tactics in the southeastern part of the Muramite Proving Grounds, at -5530, -1585.\nYou say, 'Hail, Projection of Tactics'\nProjection of Tactics says 'Halt, \\_\\_\\_\\_\\_\\_, and hear my words. Your background and your status are of no consequence. All are welcome to participate in the trials to prove their worth, or die trying. Whosoever approaches me has addressed the embodiment of Tactics, keeper of the trials of Subversion and Foresight. The former is a small-scale test, while the latter is large-scale. My task is to explain the rules and usher hopefuls into the battle arena. Would you like to hear the rules for [small-scale] or [large-scale] trials, or do you wish to enroll in [Subversion] or [Foresight]?'\nYou say, 'Subversion.'\nProjection of Tactics says 'Knowing when to thwart your opponents using guile and subversion instead of brute force is critical to attaining true power. Wealth can be amassed without ever unsheathing a blade. The most ambitious rulers are overthrown not by their enemies on the battlefield, but by their 'allies' in the throne room. If you understand my meaning, now is the opportunity to prove your worth!'\nThe direction to the entry to your instanced zone(s) have been marked on your compass.\nLOADING, PLEASE WAIT...\nYou have entered Proving Grounds: The Mastery of Subversion.\nIn this trial, your group members must open chests to discover various-valued Seals of Subversion. Most of the chests are locked, and differently-named ones correspond to the archetype that can disarm and unlock them. Say, \"begin\" to start the trial.:\na spellbound chest [npc=17742] must be disarmed/unlocked by casters :\n\\- ENC MAG NEC : using Wuggan's Greater Discombobulation to disarm then Wuggan's Greater Extrication to unlock ;\n\\- WIZ : using Xalirilan's Greater Discombobulation to disarm then Xalirilan's Greater Extrication to unlock.\na hexed chest [npc=17740] must be disarmed/unlocked by priests :\n\\- CLR : using Iony's Greater Exorcism to disarm then Iony's Greater Cleansing to unlock ;\n\\- DRU SHM : using Reebo's Greater Exorcism to disarm then Reebo's Greater Cleansing to unlock.\nan ironbound chest [npc=17741] by rogues/bards (Pick Locks).\nFor both casters and priests, a Greater Scrying Stone [item=24336] is used as a reagent for the Disarm spell. Be sure to have enough before starting the trial if you intend to use the Disarm / Unlock spells.\nFailure to disarm the chests properly will trigger various nasty effects :\n\\- Jagged Rust : Increase Disease Counter by 20, Decrease Hitpoints by 1500 per tick ;\n\\- Disorienting Vortex : Decrease Hitpoints by 400 per tick, Decrease Movement by 40% ;\n\\- Hazy Cloudcurse : Increase Curse Counter by 20, Decrease Stats by 175, Drunk if Alcohol Tolerance not at least 50.\nYour team has recovered a copper seal, worth 10. You are a little closer to reaching your goal of 300.\nYour team has recovered a silver seal, worth 20. You are a little closer to reaching your goal of 300.\nYour team has recovered a gold seal, worth 30. You are a little closer to reaching your goal of 300.\nThe total value of seals you have acquired is XX.\nOnce you reach 300 points, the group is to kill the Master of Subversion and two dragorn guardians to win the trial.\nProblem: There are also dragorn roamers (a dragorn patroller) which will waste time and threaten wipeout if aggroed. They can drop copper seals.. but not so often as to make killing them worthwile.\nThe keys to this trial are the avoidance of aggro, LDoN-style \"unlock chest\" spells/abilities, and quick reaction times to chest traps (get cured ASAP).\nUse of pacification spells is beneficial in this trial to keep the roamers at bay while you open and loot chests. Once all 300 points are collected, the roamers despawn. The only mobs left are the Master of Subversion and his two guards.\nMaster of Subversion [npc=16704] has about 150,000 hitpoints and is fairly simple for a 10k+ tank to handle. Shell of the Master [npc=16801] spawns after successful completion with the loot.\n- Bauble of Premonitions [item=32980]\n- Emblem of the False Priestess [item=32553]\n- Glowing Muramite Rune [item=30539]\n- Greater Muramite Rune [item=30538]\n- Journal of the Prime Disciple [item=35121]\n- Stalker's Shoulderguards [item=32981]",
    },
    {
      id = "3014",
      title = "The Mastery of Foresight (Raid)",
      exp = "08",
      exp_name = "Omens of War",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Projection of Tactics",
      loc = { y = -5530.0, x = -1585.0, z = 0.0 },
      triggers = {
        "Hail, Projection of Tactics",
        "Foresight",
        "Hail, Master of Foresight",
        "We are ready to begin",
        "begin",
      },
      items_required = {
      },
      rewards = {
        { id = 32421, name = "Band of Eternal Gaze", type = "item" },
        { id = 32420, name = "Belt of Intangible Clairvoyance", type = "item" },
        { id = 32674, name = "Cudgel of the Watchful Dragorn", type = "item" },
        { id = 30539, name = "Glowing Muramite Rune", type = "item" },
        { id = 30538, name = "Greater Muramite Rune", type = "item" },
        { id = 32690, name = "Hammered Helm of Foresight", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Muramite Proving Grounds [zone=263]\n**Who:**\n- Projection of Tactics [npc=16014]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 70\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Expedition\n**Quest Goal:**\n- Advancement\n- Loot\n**Related Zones:**\n- Proving Grounds: The Mastery of Foresight [zone=327]\n**Related Creatures:**\n- Dragorn Acolyte [npc=17426]\n- Dragorn Adept [npc=17425]\n- Dragorn Annihilator [npc=17424]\n- Dragorn Flamecaster [npc=17423]\n- Dragorn Incinerator [npc=17422]\n- Dragorn Spellscribe [npc=17421]\n- Shell of the Master [npc=16927]\n- a kyv sureshot [npc=17420]\n**Related Quests:**\n- Access to Asylum of Anguish [quest=2978]\n- The Mastery of Adaptation (Raid) [quest=3012]\n- The Mastery of Corruption (Raid) [quest=3008]\n- The Mastery of Endurance (Raid) [quest=2997]\n- The Mastery of Hate (Raid) [quest=3006]\n- The Mastery of Specialization (Raid) [quest=3010]\n**Era:** | !Omens of War\nRecommended:\n**Group Size:** | Raid\n**Min. # of Players:** | 6\n**Max. # of Players:** | 54\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 7 21:28:40 2004\nModified: Tue Dec 5 05:21:04 2023 | | _Find the Projection of Tactics in the southeastern part of the Muramite Proving Grounds, at -5530, -1585._\nYou say, 'Hail, Projection of Tactics'\nProjection of Tactics says, 'Halt, \\_\\_\\_\\_\\_, and hear my words. Your background and your status are of no consequence. All are welcome to participate in the trials to prove their worth, or die trying. Whosoever approaches me has adressed the embodiment of tactics, keeper of the trials of Subversion and Foresight. The former is a small-scale test, while the latter is large-scale. My task is to explain the rules and usher hopefuls into the battle arena. Would you like to hear the rule for small-scale or large-scale trials or do you wish to enroll in Subversion or Foresight?'\nYou say, 'Foresight'\nProjection of Tactics says, 'Perception and split-second reactions are not something you can acquire in training. It's a gift learned on the battlefield, and the penalty for being a slow learner is a quick and decisive death. Can you see the arrow as it sails towards your heart and sidestep out of the way? If you have this ability now is the opportunity to prove your worth.'\n_You have entered Proving Grounds: Mastery of Foresight._\nYou say, 'Hail, Master of Foresight'\nMaster of Foresight says, 'This is the Mastery of Foresight Trial. You must react quickly to deadly and unforgiving hazards. Are you ready to [begin]?'\nYou say, 'We are ready to begin'\nMaster of Foresight says, 'Very well ! Let the battle commence !\"\n_The trial has begun. You cannot bring additional people into your expedition at this time._\nAs you enter the room, you see six Dragorns on the smaller platforms (Dragorn Annihilator, Adept, Flamecaster, Spellscribe, Incinerator, Acolyte, all lvl 70). Once all six are down, you win. Meanwhile you get orders to do stuff. If you don't obey you will get punished by the Kyv Sureshots.\n_Shell of the the Master spawns afterward with loot for the raid._\n_Also upon completion, you will also receive a Mastery of Tactics Rune, one of six pieces needed for Citadel of Anguish access._\n**Submitted by:** Saraban, Darkwind\n- Band of Eternal Gaze [item=32421]\n- Belt of Intangible Clairvoyance [item=32420]\n- Cudgel of the Watchful Dragorn [item=32674]\n- Glowing Muramite Rune [item=30539]\n- Greater Muramite Rune [item=30538]\n- Hammered Helm of Foresight [item=32690]\n- Headband of Heightened Cognizance [item=32676]\n- Helm of Inventive Perception [item=32691]\n- Mask of Uncanny Sight [item=32722]\n- Mastery of Tactics Rune [item=33018]\n- Misty Globe [item=32689]\n- Pendant of Stilled Time [item=32422]\n- Seal: Mastery of All [item=33023]\n- Thunderclap [item=32675]\n- Twisted Crown of Consciousness [item=32692]",
    },
  },
}
