-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Blackfeather Roost (roost)
-- Total Quests: 5
-- ============================================================================

return {
  zone = "roost",
  zone_name = "Blackfeather Roost",
  quests = {
    {
      id = "3606",
      title = "Blackfeather Roost \\#1 - Blackfeather Roost, The Ledge",
      exp = "12",
      exp_name = "The Serpent's Spine",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Fenith",
      loc = nil,
      triggers = {
        "Hail, Fenith",
        "Your nerves?",
        "What griffons?",
        "Into the air!",
        "I do",
        "nerves",
        "griffons",
        "into the air",
      },
      items_required = {
        { name = "it to \"a tame griffon\"", count = 1 },
      },
      rewards = {
        { id = 7797, name = "Bear Meat", type = "item" },
        { id = 52145, name = "Fenith's Griffon Treat Kit", type = "item" },
        { id = 52148, name = "Griffon Treat", type = "item" },
        { id = 46996, name = "Puma Paw", type = "item" },
        { id = 8109, name = "Snake Meat", type = "item" },
        { id = 52143, name = "Tuft of Bear Fur", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Blackfeather Roost [zone=436]\n**Who:**\n- Fenith [npc=22805]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 50\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n**Quest Items:**\n- Bear Meat [item=7797]\n- Fenith's Griffon Treat Kit [item=52145]\n- Griffon Treat [item=52148]\n- Puma Paw [item=46996]\n- Snake Meat [item=8109]\n- Tuft of Bear Fur [item=52143]\n**Related Creatures:**\n- a tame Griffon [npc=23221]\n**Related Quests:**\n- Blackfeather Roost #2 - Blackfeather Roost, The Grove [quest=3632]\n- Blackfeather Roost #3 - Blackfeather Roost, The Cliffs [quest=3672]\n- Blackfeather Roost #4 - Blackfeather Roost, The Mesa [quest=3696]\n- Blackfeather Roost #5 - Reach the Royal Throne [quest=3695]\n**Era:** | !Serpents Spine\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Sep 25 16:23:48 2006\nModified: Tue Dec 5 05:21:04 2023 | | _There are six islands in Blackfeather Roost, each with its own requirements for access (you can port from island to island after completing a short task for each):_\n\\- The Base (entered from Goru'kar Mesa)\n\\- The First Ledge (complete this task)\n\\- The Harpy Grove ( see this task [quest=3632])\n\\- The Harpy Cliffs ( see this task [quest=3672])\n\\- The Harpy Mesa ( see this task [quest=3696])\n\\- The Royal Throne ( see this task [quest=3695])\n\n---\n\n_This task begins with Fenith who is located at the opposite end of the island upon zoning into Blackfeather Roost (near the tame griffon)._\nYou say, 'Hail, Fenith'\nFenith says 'What? Who's there? Oh my [nerves]!'\nYou say, 'Your nerves?'\nFenith says 'Ever since my capture I just can't seem to stop shaking. I'm so afraid all the time now, especially of the [griffons]. Of course, that's the worst part because I have to feed them every day!'\nYou say, 'What griffons?'\nFenith says 'Oh those hateful fearsome beasts! They haunted my nightmares as a young satyr and now all my nightmares have come true. A horrible harpy, Ashrana was her name, swooped down from above commanding a griffon and whisked me, bound and helpless, [into the air]!'\nYou say, 'Into the air!'\nFenith says 'Why would you even ask me about riding them? You can't possibly want to ride a griffon [do] you?'\nYou say, 'I do'\nFenith says 'If you do then you're crazier than you look. Fine, I'll help you, but only if you help me! You can feed the griffon today instead of me! Haha! You see, if you want to ride the griffon, first you have to feed it or it just might eat you instead!. Combine some bear meat with a little snake meat, add in a puma paw and a tuft of bear fur and put it all in this Griffon Treat Kit and feed it to the griffon in the nest over there. If you're crazy enough to get that close to such a dangerous beast, he might let you ride him from place to place. Or he might eat your hand. One or the other . . .'\nYou have been assigned the task 'Blackfeather Roost, The Ledge'.\n\n---\n\nIf you want to ride the griffon first you have to feed it. Combine some bear meat with a little snake meat, add in a puma paw and a tuft of bear fur and put it all in this Griffon Treat Kit and feed it to the griffon in the nest over there. If you're crazy enough to get that close to such a dangerous beast he might let you ride him from place to place. Or he might eat your hand, one or the other...\n_You receive Fenith's Griffon Treat Kit, a 4 slot container._\n8. Give the treat to the Griffon near Fenith 0/1 (Blackfeather Roost)\n\n\n\n_The treat is made by combining the 4 items in the Treat Kit. All can be hunted in the area close to Fenith. Give it to \"a tame griffon\"._\n\n9. Return to Fenith to learn more about the Griffons 0/1 (Blackfeather Roost)\n\n\n\nYou say, 'Hail, Fenith'\n\n\n\n\nFenith says 'So you managed to feed the griffon and keep all your fingers?! Huh! Well, don't try feeding that same stale treat to the next griffon you encounter -- it won't work. Each griffon likes a different treat and it's up to you to find it. If you like, I can give you a [hint] of what the next griffon has a taste for.'\n_This is the lead-in to the second task, \"Blackfeather Roost, The Grove\"._\n**Submitted by:** Fight Clubx, Beastlord on The Nameless",
    },
    {
      id = "3632",
      title = "Blackfeather Roost \\#2 - Blackfeather Roost, The Grove",
      exp = "12",
      exp_name = "The Serpent's Spine",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Fenith",
      loc = nil,
      triggers = {
        "Give me a hint",
        "hint",
      },
      items_required = {
        { name = "it to tame griffon on the second island", count = 1 },
        { name = "me a hint'", count = 1 },
        { name = "it to \"a tame griffon\" on the 1st ledge", count = 1 },
      },
      rewards = {
        { id = 7797, name = "Bear Meat", type = "item" },
        { id = 52145, name = "Fenith's Griffon Treat Kit", type = "item" },
        { id = 52138, name = "Griffon Treat", type = "item" },
        { id = 8109, name = "Snake Meat", type = "item" },
        { id = 52153, name = "Snake Shedding", type = "item" },
        { id = 52141, name = "Spider Eggs", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Blackfeather Roost [zone=436]\n**Who:**\n- Fenith [npc=22805]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 50\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n**Quest Items:**\n- Bear Meat [item=7797]\n- Fenith's Griffon Treat Kit [item=52145]\n- Griffon Treat [item=52138]\n- Snake Meat [item=8109]\n- Snake Shedding [item=52153]\n- Spider Eggs [item=52141]\n**Related Creatures:**\n- a tame Griffon [npc=23221]\n**Related Quests:**\n- Blackfeather Roost #1 - Blackfeather Roost, The Ledge [quest=3606]\n- Blackfeather Roost #3 - Blackfeather Roost, The Cliffs [quest=3672]\n- Blackfeather Roost #4 - Blackfeather Roost, The Mesa [quest=3696]\n- Blackfeather Roost #5 - Reach the Royal Throne [quest=3695]\n**Era:** | !Serpents Spine\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sun Oct 1 06:03:01 2006\nModified: Tue Dec 5 05:21:04 2023 | | _There are six islands in Blackfeather Roost, each with its own requirements for access (you can port from island to island after completing a short task for each):_\n\\- The Base (entered from Goru'kar Mesa)\n\\- The First Ledge ( see this task [quest=3606])\n\\- The Harpy Grove (complete this task)\n\\- The Harpy Cliffs ( see this task [quest=3672])\n\\- The Harpy Mesa ( see this task [quest=3696])\n\\- The Royal Throne ( see this task [quest=3695])\n\n---\n\nDo not bother trying anything if one does not have the quest in the quest window.\n\\-\\-\\- Having just the container does not count.\n\\-\\-\\- Having just the \"treat\" does not count.\nWhen one has the quest AND the treat (sandwich), do give it to tame griffon on the second island.\n_At the end of \"Blackfeather Roost, The Ledge\":_\nFenith says 'So you managed to feed the griffon and keep all your fingers?! Huh! Well, don't try feeding that same stale treat to the next griffon you encounter -- it won't work. Each griffon likes a different treat and it's up to you to find it. If you like, I can give you a [hint] of what the next griffon has a taste for.'\nYou say, 'Give me a hint'\nFenith says 'If you want to try your luck a second time you can feed the griffon on the next ledge over. Like I said each griffon likes a different type of treat so for him you'll need to combine bear meat and snake meat along with some spider eggs and snake sheddings in this Griffon Treat Kit if you want to win his friendship. Good luck to you, \\_\\_\\_\\_, but I still think you're crazy as a loon.'\n_You receive Fenith's Griffon Treat Kit, a 4 slot container._\nGive the treat to the Griffon on the first ledge 0/1 (Blackfeather Roost)\n_The treat is made by combining the 4 items in the Treat Kit..._\nSnake Meat\nBear Meat\nSpider Eggs\nSnake Sheddings\n_All can be hunted/foraged in the area close to Fenith (spiders spawn inside the bear caves - they are aggro with the bears, so you may have to clear the area of bears first). Give it to \"a tame griffon\" on the 1st ledge. You reach this ledge by clicking on the nest of the griffon close to Fenith._\n_The reward is experience and the ability to use the 2nd griffon nest in order to reach the harpy grove._\n**Submitted by:** Lias Roxx, Defiant, Zek",
    },
    {
      id = "3672",
      title = "Blackfeather Roost \\#3 - Blackfeather Roost, The Cliffs",
      exp = "12",
      exp_name = "The Serpent's Spine",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Coryn",
      loc = nil,
      triggers = {
        "Hail, Coryn",
        "I will help",
        "I will rescue you",
        "I will take revenge",
        "help",
        "Rescue",
        "revenge",
      },
      items_required = {
        { name = "the Griffon to explore more!'", count = 1 },
        { name = "to the Griffon in this grove", count = 1 },
      },
      rewards = {
        { id = 52427, name = "Griffon Treat", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Blackfeather Roost [zone=436]\n**Who:**\n- Coryn [ _Quest 50+_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 50\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n**Quest Items:**\n- Griffon Treat [item=52427]\n**Related Creatures:**\n- a harpy noble [npc=23245]\n- a tame Griffon [npc=23221]\n**Related Quests:**\n- Blackfeather Roost #1 - Blackfeather Roost, The Ledge [quest=3606]\n- Blackfeather Roost #2 - Blackfeather Roost, The Grove [quest=3632]\n- Blackfeather Roost #4 - Blackfeather Roost, The Mesa [quest=3696]\n- Blackfeather Roost #5 - Reach the Royal Throne [quest=3695]\n**Era:** | !Serpents Spine\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Fri Oct 6 00:22:37 2006\nModified: Tue Dec 5 05:21:04 2023 | | _There are six islands in Blackfeather Roost, each with its own requirements for access (you can port from island to island after completing a short task for each):_\n\\- The Base (entered from Goru'kar Mesa)\n\\- The First Ledge ( see this task [quest=3606])\n\\- The Harpy Grove ( see this task [quest=3632])\n\\- The Harpy Cliffs (complete this task)\n\\- The Harpy Mesa ( see this task [quest=3696])\n\\- The Royal Throne ( see this task [quest=3695])\n\n---\n\n_Coryn is standing in front of you as you arrive the the harpy grove._\nYou say, 'Hail, Coryn'\nCoryn says 'No! Don't hurt poor Coryn! Coryn won't hurt you, Coryn [help] strong strangers! Please spare Coryn!'\nYou say, 'I will help'\nCoryn says 'Coryn will help you, yes! Strong strangers want to explore, yes? Coryn can help you explore if strong strangers help Coryn too! [Rescue] Coryn and Coryn will help!'\nYou say, 'I will rescue you'\nCoryn says 'Coryn is weak and the Nobles think it's fun to hurt Coryn. Coryn wants to take [revenge] but not strong enough. Will you take [revenge] for Coryn? If you do, Coryn gives you the treat you need to give the Griffon to explore more!'\nYou say, 'I will take revenge'\nCoryn says 'Kill two Nobles for Coryn and Coryn will help. Return when they are dead and Coryn will help strong strangers explore more.'\nYou have been assigned the task 'Blackfeather Roost, The Cliffs'.\nKill two Nobles for Coryn and Coryn will help. Return when they are dead and Coryn will help strong strangers explore more.\nRevenge! Kill two harpy nobles 0/1 (Blacfeather Roost)\nHarpy nobles can be found nearby. Just watch out for wandering harpy patrollers.\nReturn to Coryn and tell her the deed is done 0/1 (Blackfeather Roost)\nYou say, 'Hail, Coryn'\nCoryn says 'Thank you, thank you strong stranger! Here is the treat you need to give to the Griffon in this grove. See? Coryn helps just like she said!'\nGive the treat to the Griffon in the Grove - Blackfeather Roost\n_Give the Griffon Treat to the Tame Griffon standing a little to your North East. You can now use his nest to reach the harpy cliffs._\n**Submitted by:** Lias Roxx, Defiant, Zek",
    },
    {
      id = "3695",
      title = "Blackfeather Roost \\#5 - Reach the Royal Throne",
      exp = "12",
      exp_name = "The Serpent's Spine",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Ashrana",
      loc = nil,
      triggers = {
        "Hail, Ashrana",
        "I am interested",
        "Replace her?",
        "I will help you",
        "I will kill her",
        "Royal crest?",
        "interested",
        "replace",
      },
      items_required = {
      },
      rewards = {
        { id = 52167, name = "Royal Crest", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Blackfeather Roost [zone=436]\n**Who:**\n- Ashrana [npc=23276]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 1\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n**Time Limit:** | 08:00:00\n**Quest Items:**\n- Royal Crest [item=52167]\n**Related Creatures:**\n- Captain Slarus [npc=23286]\n- Royal Guard [npc=23285]\n**Related Quests:**\n- Blackfeather Roost #1 - Blackfeather Roost, The Ledge [quest=3606]\n- Blackfeather Roost #2 - Blackfeather Roost, The Grove [quest=3632]\n- Blackfeather Roost #3 - Blackfeather Roost, The Cliffs [quest=3672]\n- Kill the Queen of the Harpies! [quest=3694]\n**Era:** | !Serpents Spine\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sat Oct 7 03:48:45 2006\nModified: Sat Apr 20 08:23:17 2024 | | _There are six islands in Blackfeather Roost, each with its own requirements for access (you can port from island to island after completing a short task for each):_\n\\- The Base (entered from Goru'kar Mesa)\n\\- The First Ledge ( see this task [quest=3606])\n\\- The Harpy Grove ( see this task [quest=3632])\n\\- The Harpy Cliffs ( see this task [quest=3672])\n\\- The Harpy Mesa ( see this task [quest=3696])\n\\- The Royal Throne (complete this task)\n\n---\n\nAshrana is in Blackfeather Roost on the last isle before entering the Queen chambers.\nYou say, 'Hail, Ashrana'\nAshrana says 'My sister, Mestle, told me you had agreed to accept our challenge. I'm sure she bored you with threats and doom, but please allow me to tempt you instead. Great riches and treasure can be had at the end of this road if you walk it with me. Are you [interested]?'\nYou say, 'I am interested'\nAshrana says 'Excellent \\_\\_\\_. The situation is very simple as you'll soon see I'm sure. The fact is that I should be Queen, not my sad and weak sister Eletyl. I aim to [replace] her and assume my rightful role as leader of this Roost. Will you [help] me?'\nYou say, 'Replace her?'\nAshrana says 'It is far past time for the old to give way to the new and high time I take my rightful place in this roost. Will you [help] me accomplish this and reap the rewards?'\nYou say, 'I will help you'\nAshrana says 'Your role in this little Drama is quite simple - [Kill] my sister Eletyl, ransack her home and return to me. I will then assume my rightful role and place.'\nYou say, 'I will kill her'\nAshrana says 'There is one snag to our fine plan - getting to my dear older sister the Queen. You have learned to tame the Griffons of this Roost and move from place to place but a morsel of food will not be enough to accomplish this task. The Queen's abode can only be reached via specially trained Griffons. To ride these Griffons you need the [Royal Crest].'\nYou say, 'Royal crest?'\nAshrana says 'Captain Slarus leads the Queen's personal guard. Her loyalty to the Queen is unquestioned and so, of course, Slarus must die. But more than that Slarus and her top lieutenants alone have the magical Crest needed to command the Royal Griffons. Kill Slarus and retrieve a Crest for you and your companions. Return to me when you have done so.'\nYou have been assigned the task 'Blackfeather Roost - Reach the royal throne'.\nCaptain Slarus leads the Queen's personal guard. Her loyalty to the Queen is unquestioned and so, of course, Slarus must die. But more than Slarus and her top lieutenants alone have the magical Crest needed to command the Royal Griffons. Kill Slarus and retrieve a Crest for you and your companions. Return to me when you have done so.\nKill the Captain of the Guard, Captain Slarus 0/1 (Blackfeather Roost)\n_Captain Slarus can hit for up to 1,700. He has four guards next to him while a fifth guard patrols the area. The trash mobs and guards have a quick respawn time, so you may need to deal with anywhere from 3 to 8 mobs at once to get this kill._\nKill the Royal Guards 0/5 (Blackfeather Roost)\n_The guards are clustered around Captain Slarus, close to the nest leading to the Queen's Palace. Neither guards nor the Captain see invis. All drop a Royal Crest. Captain Slarus will drop an item of loot of her own._\nReturn One Royal Crest to Ashrana 0/1 (Blackfeather Roost)\nAshrana says 'Aha! Well done \\_\\_\\_! Now we can finally [accomplish] our goal!'\nThis leads you in to the task 'Kill the Queen of the Harpies!'.\n_You are now able to use the griffon nest on the Mesa to reach the Queen's palace which leads to the last task in this series Kill the Queen of the Harpies! [quest=3694]._\n**Submitted by:** Lias Roxx, Defiant, Zek",
    },
    {
      id = "3696",
      title = "Blackfeather Roost \\#4 - Blackfeather Roost, The Mesa",
      exp = "12",
      exp_name = "The Serpent's Spine",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Mestle",
      loc = nil,
      triggers = {
        "Hail, Mestle",
        "What plan?",
        "Serve?",
        "I will prove myself",
        "Strategem?",
        "I accept the challenge",
        "plan",
        "serve",
      },
      items_required = {
      },
      rewards = {
        { id = 52428, name = "Griffon Treat", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Blackfeather Roost [zone=436]\n**Who:**\n- Mestle [npc=23255]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 50\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | No\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n**Quest Items:**\n- Griffon Treat [item=52428]\n**Related Creatures:**\n- Lady Inthra [npc=23271]\n- a tame Griffon [npc=23221]\n**Related Quests:**\n- Blackfeather Roost #1 - Blackfeather Roost, The Ledge [quest=3606]\n- Blackfeather Roost #2 - Blackfeather Roost, The Grove [quest=3632]\n- Blackfeather Roost #3 - Blackfeather Roost, The Cliffs [quest=3672]\n- Blackfeather Roost #5 - Reach the Royal Throne [quest=3695]\n**Era:** | !Serpents Spine\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sat Oct 7 04:23:39 2006\nModified: Tue Dec 5 05:21:04 2023 | | _There are six islands in Blackfeather Roost, each with its own requirements for access (you can port from island to island after completing a short task for each):_\n\\- The Base (entered from Goru'kar Mesa)\n\\- The First Ledge ( see this task [quest=3606])\n\\- The Harpy Grove ( see this task [quest=3632])\n\\- The Harpy Cliffs ( see this task [quest=3672])\n\\- The Harpy Mesa (complete this task)\n\\- The Royal Throne ( see this task [quest=3695])\n\n---\n\n_Mestle is found near where you're dropped off upon porting up to this island._\nYou say, 'Hail, Mestle'\nMestle says 'He he! So her [plan] worked I see. Welcome \\_\\_\\_\\_\\_, welcome. He he!'\nYou say, 'What plan?'\nMestle says 'Why the plan to bring you here, of course! Didn't you notice how easily you've penetrated into the heart of our Roost? Our slaves Fenith and Coryn each played their part in this drama perfectly. Surely you must know that death lurks around every corner for one such as you, and you must have wondered at the ease you were able to delve deeper and deeper into our home. Now you must choose to [serve] our purpose, or die.'\nYou say, 'Serve?'\nMestle says 'If you can [prove] yourself worthy to me I will allow you to inch even further into our home. Prove yourself and you will be rewarded. Fail and you will be slain.'\nYou say, 'I will prove myself'\nMestle says 'There is one here who stands opposed to our purpose, one who must be eliminated for our [strategem] to proceed. If you [accept] my challenge, you will destroy Lady Inthra and prove you are worthy to continue onward and serve us.'\nYou say, 'Strategem?'\nMestle says 'That is none of your concern until you prove yourself to me! Now, quickly, before I lose my patience -- do you [accept] my challenge?'\nYou say, 'I accept the challenge'\nMestle says 'Kill her, \\_\\_\\_\\_, and return to me when you have done so. Only then will you be permitted to travel deeper into the roost.'\nYou have been assigned the task 'Blackfeather Roost, The Mesa'.\nDo as Mestle...asked...and kill Lady Inthra 0/1 (Blackfeather Roost)\n_Lady Inthra has no protectors and is an easy kill. She is located next to the griffon nest/port-up to the next island._\nReturn to Mestle and report that the deed is done 0/1 (Blackfeather Roost)\nYou say, 'Hail, Mestle'\nYour task 'Blackfeather Roost, The Mesa' has been updated.\nMestle says 'Well done, \\_\\_\\_\\_. Frail as you seem you may be up to the task ahead of you, if you dare. Here is the griffon food you will need to continue on. Speak with my sister Ashrana, and quickly. She has gone to great effort to bring you this far - do not fail us now or we will turn our fury on you!'\nGive the treat to the Griffon on the Cliffs 0/1 (Blackfeather Roost)\n_After handing in the treat you can now use the griffon's nest on the Cliffs to reach the Mesa, where you will find Ashrana waiting._\n**Submitted by:** Lias Roxx, Defiant, Zek",
    },
  },
}
