-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Shadow Valley (shadowvalley)
-- Total Quests: 7
-- ============================================================================

return {
  zone = "shadowvalley",
  zone_name = "Shadow Valley",
  quests = {
    {
      id = "10513",
      title = "Exploring Shadow Valley's Burn Scars",
      exp = "28",
      exp_name = "Terror of Luclin",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Daerius Jaegir",
      loc = nil,
      triggers = {
        "Hail, Daerius Jaegir",
        "More time? Is there something I could do for you?",
        "I will find more if they exist.",
        "relics",
        "Tell me more about the Barbarian weapons.",
        "What small encampment?",
        "I found these relics near the burn scars and I am trying to find out more information about them. I couldn",
        "Tell me about the chipped axe head.",
      },
      items_required = {
      },
      rewards = {
        { id = 142737, name = "Brittle Half Shield", type = "item" },
        { id = 142734, name = "Chipped Axe Head", type = "item" },
        { id = 142736, name = "Matted Bear Helm", type = "item" },
        { id = 142735, name = "Melted Sword Hilt", type = "item" },
        { id = 142746, name = "Relic Report", type = "item" },
        { id = 142739, name = "Sack of Barbarian Relics", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Status: Incomplete**\n\nQuest Started By: | Description:\n**Where:**\n- Shadow Valley [zone=1281]\n**Who:**\n- Daerius Jaegir [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 115\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Brittle Half Shield [item=142737]\n- Chipped Axe Head [item=142734]\n- Matted Bear Helm [item=142736]\n- Melted Sword Hilt [item=142735]\n- Relic Report [item=142746]\n- Sack of Barbarian Relics [item=142739]\n**Related Creatures:**\n- Istoph Banock [ _Quests_]\n- a defensive shadow [npc=56917]\n- a vengeful shadow [npc=56937]\n- an avenging mass [npc=56945]\n- an avenging shadow [npc=56946]\n**Related Quests:**\n- Partisan of Shadow Valley (10 Points) [quest=10584]\n**Era:** | !Terror of Luclin\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sat Oct 23 21:46:55 2021\nModified: Tue Dec 5 05:21:04 2023 | | **Terror of Luclin Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this quest by speaking to Daerius Jaegir close to the zone out from Ka Vethan. He is on the Find tool (Ctrl+F).\nYou say, 'Hail, Daerius Jaegir'\nDaerius Jaegir continues investigating the burn scar before him. 'Just look at this melted rock. This burn scar is simply amazing. I must know more about it. If only I had [more time]. I mean just look at these crystalized rocks.'\nYou say, 'More time? Is there something I could do for you?'\nDaerius Jaegir takes a moment to think to himself. 'Perhaps on your travels, you can keep an eye out for more of these scars. If you [find more], take note of their location, and check to see if you can find anything of interest at them.'\nYou say, 'I will find more if they exist.'\nYou have been assigned the task 'Exploring Shadow Valley's Burn Scars'.\n\n---\n\n1\\. Explore the burn scar near Darius 0/1 Shadow Valley\n> **Quest Text:** Daerius Jaegir is investigating the burn scars in Shadow Valley. He has asked for assitance in learning more about what happened here. He thinks an intense battle took place and wants to understand what happened.\n>\n> Explore Shadow Velley for burn scar locations. Hunt shadows for any relics they may have found.\nThis update is right near Darius at /waypoint -176, -1384, 4\nP 1384.8889, 176.5170, -0.3557, 0, 0, 0, 3, Update\\_1\\_Burn\\_Scars\n2\\. Explore the burn scar to the West 0/1 Shadow Valley\nThis update is at /waypoint -221, -122, 5\nP 122.4476, 221.1480, 0.8102, 0, 0, 0, 3, Update\\_2\\_Burn\\_Scars\n3\\. Explore the burn scar North West 0/1 Shadow Valley\nThis update is at /waypoint 168, 559, 26\nP -559.6478, -168.1006, 21.8169, 0, 0, 0, 3, Update\\_3\\_Burns\\_Scars\n4\\. Explore the burn scar furthest West 0/1 Shadow Valley\nThis update is at /waypoint -359, 268, 35\nP -268.7544, 359.1271, 31.4603, 0, 0, 0, 3, Update\\_4\\_Burns\\_Scars\n5\\. Collect a relic from a defensive shadow 0/1 Shadow Valley\nCollect a Chipped Axe Head [item=142734] (can be prelooted) from a defensive shadow [npc=56917].\n6\\. Collect a relic from a vengeful shadow 0/1 Shadow Valley\nCollect a Melted Sword Hilt [item=142735] (can be prelooted) from a vengeful shadow [npc=56937].\n7\\. Collect a relic from an avenging shadow 0/1 Shadow Valley\nCollect a Matted Bear Helm [item=142736] (can be prelooted) from an avenging shadow [npc=56946].\n8\\. Collect a relic from an avenging mass 0/1 Shadow Valley\nCollect a Brittle Half Shield [item=142737] (can be prelooted) from an avenging mass [npc=56945].\n9\\. Return the Chipped Axe Head to Daerius 0/1 Shadow Valley\n10\\. Return the Melted Sword Hilt to Daerius 0/1 Shadow Valley\n11\\. Return the Matted Bear Helm to Daerius 0/1 Shadow Valley\n12\\. Return the Brittle Half Shield to Daerius 0/1 Shadow Valley\nGive the 4 relics to Istoph Banock [npc=56955] at the barbarian camp (she's on Find).\n13\\. Speak with Daerius Jaegir about [the relics] 0/1 Shadow Valley\nYou say, 'relics'\nDaerius Jaegir says, 'Interesting. These remains remind me of [Barbarian weapons].\nYou say, 'Tell me more about the Barbarian weapons.'\nYou have been given: Sack of Barbarian Relics [item=142739]\nDaerius Jaegir says, 'Here take these items to the [small encampment] and see of anyone recognizes them.'\nYou say, 'What small encampment?'\nDaerius Jaegir says, 'To the west of here you will find a hill with a slope that can be climbed. Follow the bridges to the north, you should eventually find the camp. Perhaps you can ask a few of them what they know about the history of this land.'\n14\\. Show the relics to someone who knows about them 0/1 Shadow Valley\n> Show the relics to the Barbarians at the encampment and find out what they know about them.\n15\\. Speak with Istoph Banock about [these relics] 0/1 Shadow Valley\nIstoph Banock says, 'Where did you find [these relics]?'\nYou say, 'I found these relics near the burn scars and I am trying to find out more information about them. I couldn't tell how they got there.'\nIstoph Banock says, 'These relics the [chipped axe head], the [melted sword hilt], the [brittle half shield], and the [matted bear helm] belonged to mighty warriors of Halas.'\nYou say, 'Tell me about the chipped axe head.'\nIstoph Banock says, 'This chipped axe head used to belong to a strong warrior of Halas. You can tell by this etching; its owner had seen many battles.'\nYou say, 'Tell me about the melted sword hilt.'\nIstoph Banock says, 'This melted sword hilt is odd. The blade is missing, but the handle still exists. Perhaps the blade was in the molten ground. The pommel resembles a wolfs head.'\nYou say, 'Tell me about the brittle half shield.'\nIstoph Banock says, 'This piece, this brittle half shield, was once much larger. Look at how it flakes to the touch. It's as if it has seen too many seasons. The wood and metal design remind me of those used by [Wolves of the North].'\nYou say, 'Tell me about the matted bear helm.'\nIstoph Banock says, 'And this matted bear helm, I see what remains of the beaded work along the edges? It belonged to a seasoned warrior of the Tribunal.'\nYou say, ' All of these seem related to the Wolves of the North.'\nYou have been given: Relic Report [item=142746]\nYour task 'Exploring Shadow Valley's Burn Scars' has been updated.\nIstoph Banock sighs. 'Aye, they belonged to family that is missing. Knowing the state of these does not bode well for them. It may be time to head home. Here, you can have this. It's a list of the items and what they were. However, I will be keeping these relics and giving them back to the families that they belong to.'\n16\\. Return the Relic Report to Daerius 0/1 Shadow Valley\nDaerius seems intrigued by the information that you brought back to him. He needs time to investigate and study this new information.\n\n---\n\nReward(s):\nYou receive 354 platinum 1 gold 6 silver 7 copper\n**Submitted by:** Gidono",
    },
    {
      id = "10514",
      title = "Catching Lightning",
      exp = "28",
      exp_name = "Terror of Luclin",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Daerius Jaegir",
      loc = nil,
      triggers = {
        "Hail, Daerius Jaegir",
        "What about the power?",
        "What small fulgurites?",
        "What doesn",
        "Who is Lizenael Methinon?",
        "The inhabitants don",
        "What intrusion?",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
        { id = 142738, name = "Charred Umbral Fulgurite", type = "item" },
        { id = 142740, name = "Crystallized Umbral Fulgurite", type = "item" },
        { id = 142745, name = "Fossilized Umbral Fulgurite", type = "item" },
        { id = 142744, name = "Scorched Umbral Fulgurite", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Status: Incomplete**\n\nQuest Started By: | Description:\n**Where:**\n- Shadow Valley [zone=1281]\n**Who:**\n- Daerius Jaegir [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 115\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Charred Umbral Fulgurite [item=142738]\n- Crystallized Umbral Fulgurite [item=142740]\n- Fossilized Umbral Fulgurite [item=142745]\n- Scorched Umbral Fulgurite [item=142744]\n**Related Creatures:**\n- a fogfall lurker [npc=56919]\n- a gloaming beetle [npc=56921]\n- a grim lahar [npc=56923]\n- a swarm of shadows [npc=56911]\n**Related Quests:**\n- Partisan of Shadow Valley (10 Points) [quest=10584]\n**Era:** | !Terror of Luclin\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sun Oct 24 03:04:12 2021\nModified: Tue Dec 5 05:21:04 2023 | | **Terror of Luclin Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this quest from Daerius Jaegir. He can be found near the zone in from Basilica of Adumbration. He is on the find tool CTRL F.\nYou say, 'Hail, Daerius Jaegir'\nDaerius Jaegir says, 'Stop wasting my time. Did you find out more about [the power]?'\nYou say, 'What about the power?'\nDaerius Jaegir says, 'Look at the patterns in this scar. You can tell that a great power struck here, and you can even see that at certain points [small fulgurites] have formed. It must have been an intense battle.'\nYou say, 'What small fulgurites?'\nDaerius Jaegir says, 'A fulgurite forms when a source of power like lightning hits the ground and melts the material together. It just doesn't make [any sense].'\nYou say, 'What doesn't make any sense?'\nDaerius Jaegir opens his arms wide in a questioning manner. 'Everything. The patterns and damage suggest fire, but the fulgurite formations suggest lightning. Who did this? Was it [Lizenael Methinon]? How long has it been here? Why have [the inhabitants] left the scars mostly alone? You would think that they would want everything to go back to normal.'\nYou say, 'Who is Lizenael Methinon?'\nDaerius Jaegir says, 'Methinon is a fellow wizard. He went missing a while ago, and I`m trying to track him down.'\nYou say, 'The inhabitants don't seem to be that observant.'\nDaerius Jaegir says, 'These creatures are not conventional, they are territorial and have no need of subsistence. They seem to exist just to maintain this territory. They should be laboring to return this barren valley to a state prior to any [intrusion].'\nYou say, 'What intrusion?'\nYou have been assigned the task 'Catching Lightning'.\nDaerius Jaegir says, 'Well obviously, Methinon sent people here to investigate this land. It`s apparent that the investigation did not go as planned. I would even speculate that they have been repelled or eliminated. Can you [hunt some] of the creatures and see what they have been getting into. Maybe I will learn what is repelling them.'\n\n---\n\n1\\. Collect a fulgurite sample from a lurker 0/1 Shadow Valley\n2\\. Collect a fulgurite sample from a beetle 0/1 Shadow Valley\n3\\. Collect a fulgurite sample from a swarm 0/1 Shadow Valley\n4\\. Collect a fulgurite sample from a grim lahar 0/1 Shadow Valley\n5\\. Return the Charred Umbral Fulgurite to Daerius 0/1 Shadow Valley\n6\\. Return the Crystallized Umbral Fulgurite to Daerius 0/1 Shadow Valley\n7\\. Return the Scorched Umbral Fulgurite to Daerius 0/1 Shadow Valley\n8\\. Return the Fossilized Umbral Fulgurite to Daerius 0/1 Shadow Valley\n9\\. Talk to Daerius Jaegir about [the Fulgurites] 0/1 Shadow Valley\n\n---\n\nReward(s):\nMoney for your level\nExperience for your level\n**Submitted by:** Gidono",
    },
    {
      id = "10515",
      title = "Oubliette of Light (Group Mission)",
      exp = "28",
      exp_name = "Terror of Luclin",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "a worried shade",
      loc = nil,
      triggers = {
        "Hail, a worried shade",
        "save",
        "small",
        "ready",
        "_Raid and Mission_",
        "large",
      },
      items_required = {
      },
      rewards = {
        { id = 141752, name = "Scarlet Mark", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Shadow Valley [zone=1281]\n**Who:**\n- a worried shade [ _Raid and Mission_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 113\n**Maximum Level:** | 130\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Expedition\n**Quest Goal:**\n- Advancement\n- Experience\n- Loot\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 05:00:00\n**Related Zones:**\n- Basilica of Adumbration - Oubliette of Light - Group [zone=1287]\n**Related Creatures:**\n- Fade [npc=57222]\n- Keltakun, Last Word [npc=57358]\n- Speaker to Darkness [npc=57221]\n- Speaker to Light [npc=57220]\n- Thall Tetoracu Liako [npc=57229]\n- Umber [npc=57223]\n- a grasping shade [npc=57360]\n- a moonlit chest [npc=57361]\n- a shadowstone jailer [npc=57359]\n**Related Quests:**\n- Hero of Basilica of Adumbration (10 Points) [quest=10598]\n**Era:** | !Terror of Luclin\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sun Oct 24 03:21:40 2021\nModified: Sun Mar 31 02:20:12 2024 | | **Terror of Luclin Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can get this group mission from a worried shade in Shadow Valley not far from the zone in from a worried shade. a worried shade is on the find tool CTRL F.\nYou say, 'Hail, a worried shade'\nA worried shade says, 'Ah, are you come to [save] Mayong?' The creature, despite being made of cloth and darkness, looks somehow sheepish and a bit despondent.'\nYou say, 'save'\nA worried shade says, 'Well, then there may still be hope. Mayong has been imprisoned and I have been sent here to help guide you to where they are holding him. I hope you have brought a [large] force. I worry that a [small] group will simply be destroyed.'\nYou say, 'small'\nA worried shade says, 'Good enough, I hope. I can send you to a location close to where Mayong is being held. I must warn you that we are in the heart of the Lady of Shadow's realm. Defeating her minions here may prove beyond even your power. However, I can teleport you to where you need to be when you are [ready].'\nYou have received a request timer for 'Oubliette of Light': 0d:0h:1m remaining.\nYou have been assigned the task 'Oubliette of Light'.\nYou say, 'ready'\nA worried shade says, 'Into the shadows you go.'\nLOADING, PLEASE WAIT...\nYou have entered Oubliette of Light.\n\n---\n\n- 1\\. Defeat the prison guards and free Mayong 0/1 Basilica of Adumbration\n> **Quest Text:** The lord of Dreadspire has been taken prisoner by the goddess Luclin. Mayong's servant says that the goddess desires his power and it falls upon you to rescue him and prevent this. The servant implied that Luclin would use that power to some devestating effect should she get it.\n- 2\\. Open the chest and claim your reward 0/1 Basilica of Adumbration\n\n---\n\nReward(s):\n177 platinum 8 silver 3 copper\nYou gain experience!\n45 Scarlet Marks\nAchievement: Hero of Basilica of Adumbration [quest=10598] (as long as you're in zone when the chest is opened) : you may now enter Bloodfalls.\n**Submitted by:** Gidono\n- Scarlet Mark [item=141752]",
    },
    {
      id = "10620",
      title = "Chasing Shadows",
      exp = "28",
      exp_name = "Terror of Luclin",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Istoph Banock",
      loc = { y = 325.0, x = -1171.0, z = 54.0 },
      triggers = {
        "Hail, Istoph Banock",
        "Devour? Well that sounds ominous.",
        "What directions do they attack from?",
        "What attacks from the ground?",
        "_Quests_",
        "devour",
        "directions",
        "ground",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Shadow Valley [zone=1281]\n**Who:**\n- Istoph Banock [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 115\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Money\n**Related Creatures:**\n- a defensive shadow [npc=56917]\n- a vengeful shadow [npc=56937]\n- an avenging mass [npc=56945]\n**Era:** | !Terror of Luclin\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sun Nov 21 15:21:55 2021\nModified: Tue Dec 5 05:21:04 2023 | | **Terror of Luclin Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this task from Istoph Banock in Shadow Valley. She can be found on the far northeast corner of the zone at /loc 325, -1171, 54 in a camp of several quest givers. She is on the find tool CTRL F.\nYou say, 'Hail, Istoph Banock'\nIstoph Banock peers at you with narrow eyes. 'Watch where you step, this land is treacherous. The shadows themselves will try to [devour] all that wander here.'\nYou say, 'Devour? Well that sounds ominous.'\nIstoph Banock says, 'Yes, it seems that native inhabitants of this land don't appreciate visitors. They attack at all times from all [directions].'\nYou say, 'What directions do they attack from?'\nIstoph Banock raises an axe at you. 'They attack from the crevices in the [ground], and from the tops of the [cliffs].'\nYou say, 'What attacks from the ground?'\nYou have been assigned the task 'Chasing Shadows'.\nIstoph Banock says, 'The oozing ground shadows plague us. When we try to investigate the burns, they attack. When we found this camp, we had to fight to keep it. They are persistent in trying to reclaim this space and the evasive pests need to be destroyed. Kill a few and you will be rewarded.'\n\n---\n\n1\\. Eliminate some of the oozing ground shadows 0/8 Shadow Valley\n> **Quest Text:** Istoph Banock is a hot-headed fanatic on a fact-finding mission. The oozing ground shadows seem to be attracted to the encampment movements. The shadows have been hounding their travels and slowed their progress. Istoph has asked you kill oozing shadows.\n>\n> Eliminate the oozing shadows on the ground harassing the hunting party.\n\n---\n\nReward(s):\nMoney for your level\n**Submitted by:** Gidono",
    },
    {
      id = "10621",
      title = "Flights of Shadows",
      exp = "28",
      exp_name = "Terror of Luclin",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Istoph Banock",
      loc = { y = 325.0, x = -1171.0, z = 54.0 },
      triggers = {
        "Hail, Istoph Banock",
        "Devour? Well that sounds ominous.",
        "What directions do they attack from?",
        "What attacks from the cliffs?",
        "Tell me more about the ravens.",
        "_Quests_",
        "devour",
        "directions",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Shadow Valley [zone=1281]\n**Who:**\n- Istoph Banock [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 115\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Money\n**Related Creatures:**\n- a glooming bat [npc=57231]\n- a vicious gloom bat [npc=56938]\n**Era:** | !Terror of Luclin\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sun Nov 21 15:34:16 2021\nModified: Tue Dec 5 05:21:04 2023 | | **Terror of Luclin Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this task from Istoph Banock in Shadow Valley. She can be found on the far northeast corner of the zone at /loc 325, -1171, 54 in a camp of several quest givers. She is on the find tool CTRL F.\nYou say, 'Hail, Istoph Banock'\nIstoph Banock peers at you with narrow eyes. 'Watch where you step, this land is treacherous. The shadows themselves will try to [devour] all that wander here.'\nYou say, 'Devour? Well that sounds ominous.'\nIstoph Banock says, 'Yes, it seems that native inhabitants of this land don't appreciate visitors. They attack at all times from all [directions].'\nYou say, 'What directions do they attack from?'\nIstoph Banock raises an axe at you. 'They attack from the crevices in the [ground], and from the tops of the [cliffs].'\nYou say, 'What attacks from the cliffs?'\nIstoph Banock looks to the sky then back at you. 'The winged creatures like to strike with little to no warning. The shadow [ravens] and glooming bats like to shriek right before they cloud your vision. Then there are the [gargoyles] who perch high up on the cliffs forever guarding the passages.'\nYou say, 'Tell me more about the ravens.'\nYou have been assigned the task 'Flights of Shadows'.\nIstoph Banock says, 'The shadow ravens and bats can be found flying high above our heads. They tend to guard passes and high places. They are territorial and do not suffer trespassers. '\n\n---\n\n1\\. Eliminate some of the ravens or bats 0/10 Shadow Valley\n> **Quest Text:** Istoph Banock has asked for the death of the shadow ravens and glooming bats that attack from above. These creatures drop down upon unsuspecting wanderers, looking for answers. Istoph has asked that you kill the plunging ravens and glooming bats that hamper the hunting party.\n>\n> Eliminate the shadow ravens and glooming bats harassing the hunting party.\n\n---\n\nReward(s):\nMoney for your level\n**Submitted by:** Gidono",
    },
    {
      id = "10624",
      title = "A Taste of Venom",
      exp = "28",
      exp_name = "Terror of Luclin",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Eliknot Terrilon",
      loc = { y = 302.0, x = -1221.0, z = 54.0 },
      triggers = {
        "Hail, Eliknot Terrilon",
        "I don",
        "What monsters are bothering you?",
        "Tell me more about the lurkers.",
        "_Quests_",
        "attacks",
        "monsters",
        "beetles",
      },
      items_required = {
      },
      rewards = {
        { id = 142742, name = "Fogfall Lurker Venom Sac", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Shadow Valley [zone=1281]\n**Who:**\n- Eliknot Terrilon [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 115\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Money\n**Quest Items:**\n- Fogfall Lurker Venom Sac [item=142742]\n**Related Creatures:**\n- a fogfall lurker [npc=56919]\n- a rockfall lurker [npc=56930]\n**Era:** | !Terror of Luclin\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sun Nov 21 16:22:21 2021\nModified: Tue Dec 5 05:21:04 2023 | | **Terror of Luclin Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this task from Eliknot Terrilon in Shadow Valley. He can be found on the far northeast corner of the zone at /loc 302, -1221, 54 in a camp of several quest givers. He is on the Find tool (Ctrl+F).\nYou say, 'Hail, Eliknot Terrilon'\nEliknot Terrilon says, 'Hail and welcome to our meager camp. We hope to be moving along as soon as the [attacks] diminish.'\nYou say, 'I don't think that the attacks will stop.'\nEliknot Terrilon says, 'We have been under siege from creatures for some time. We have found that our mere presence enrages these [monsters].'\nYou say, 'What monsters are bothering you?'\nEliknot Terrilon says, 'The [beetles], [lurkers] and [terrors] would be the most the most pressing at this time.'\nYou say, 'Tell me more about the lurkers.'\nYou have been assigned the task 'A Taste of Venom'.\nEliknot Terrilon says, 'The fogfall lurkers can be found chewing on the sediments in the ravines, near the base of cliffs. They have a nasty venom, but we have found out that it is a great meat tenderizer. It adds a nice kick of spice. Bring back some of their venom sacs and I will find something to reward you with.'\n\n---\n\n1\\. Deliver 4 Fogfall Lurker Venom Sacs 0/4 Shadow Valley\n> **Quest Text:** Eliknot Terrilon has asked for assistance in gathering more resources and killing the Fogfall Lurkers. He is in high need of gathering more supplies for the camp.\nFogfall Lurker Venom Sac [item=142742] drops off a fogfall lurker [npc=56919] and a rockfall lurker [npc=56930]. These can be prelooted.\n\n---\n\nReward(s):\nMoney for your level\n**Submitted by:** Gidono",
    },
    {
      id = "10710",
      title = "Treading on Dangerous Territory",
      exp = "28",
      exp_name = "Terror of Luclin",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Daerius Jaegir",
      loc = nil,
      triggers = {
        "I don",
        "I have found most of them to be less than forthcoming. But Istoph Banock [npc=56955] did mention that she had family that went missing.",
        "Toxic? I have been carrying those around!",
        "How can rocks really want anything?",
        "She does not have dominion over me.",
        "the collars",
        "I have come across grim shades and drifting shadows.",
        "I think they both could have been capable of doing it.",
      },
      items_required = {
      },
      rewards = {
        { id = 142743, name = "Residue of Shadow", type = "item" },
        { id = 142747, name = "Shadowed Subjugation Collar", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Shadow Valley [zone=1281]\n**Who:**\n- Daerius Jaegir [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 115\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Residue of Shadow [item=142743]\n- Shadowed Subjugation Collar [item=142747]\n**Related Creatures:**\n- a shaded assassin [npc=57390]\n- a shadow wolf - Shadow Valley [npc=56933]\n**Related Quests:**\n- Partisan of Shadow Valley (10 Points) [quest=10584]\n**Era:** | !Terror of Luclin\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 21 18:19:36 2021\nModified: Tue Dec 5 05:21:04 2023 | | You can obtain this quest from Daerius Jaegir. He can be found near the zone in from Basilica of Adumbration. He is on the find tool CTRL F.\nPrerequisites: Catching Lightning [quest=10514] and Exploring Shadow Valley's Burn Scars [quest=10513].\n\n---\n\n1\\. Talk to Daerius Jaegir about the [toxic] results 0/1 ALL\nYou say, 'I don't know anything about what is happening. It sounds like Methinon invited a bunch of Barbarians to invade this land. The first invasion went poorly, and the subsequent rescue missions have also failed.'\nDaerius Jaegir says, 'Those Barbarians aren't the most [forthcoming].'\nYou say, 'I have found most of them to be less than forthcoming. But Istoph Banock [npc=56955] did mention that she had family that went missing.'\nDaerius Jaegir says, 'Banock. That name sounds familiar. I have heard that name before. You should look to the Basilica for more information on that family. I digress. The samples that you have brought me, from the creatures and the fulgurites, seem to be [toxic].'\nYou say, 'Toxic? I have been carrying those around!'\nDaerius Jaegir says, 'Yes, they have an interesting effect. The shadows mixed with this power. It [really want]s to keep its secret.'\nYou say, 'How can rocks really want anything?'\nDaerius Jaegir says, 'Look where you stand. This land belongs to one goddess and she holds [dominion] over all you see.'\nYou say, 'She does not have dominion over me.'\nDaerius Jaegir says, 'Indeed. And perhaps over some of the other creatures here. There are shadow wolves [npc=56933] to the west of here, that may also have been altered. I believe these unfortunate creatures were lost in this land and changed by their experiences here. Bring me any clues of their alteration and we may get to the bottom of this mystery.'\n2\\. Hunt Shadow Wolves for proof of deception 0/6 (Shadow Valley)\n3\\. Loot the Shadowed Subjugation Collars 0/6 (Shadow Valley)\nShadowed Subjugation Collar [item=142747] drops off a shadow wolf [npc=56933] and an umbra wolf [npc=56913]. They CANNOT be prelooted.\n4\\. Return Shadowed Subjugation Collars to Daerius 0/6 (Shadow Valley)\n5\\. Walk with Daerius Jaegir about [the collars] 0/1 (Shadow Valley)\nYou say, 'the collars'\nDaerius Jaegir says, 'You can feel the power emanating from these collars. There is a formidable resolve here. I am curious about the other creatures you have [come across]?'\nYou say, 'I have come across grim shades and drifting shadows.'\nDaerius Jaegir says, 'Do you think any of them [could have] put those collars on the wolves?'\nYou say, 'I think they both could have been capable of doing it.'\nDaerius Jaegir says, 'Maybe I should [go look] into their abilities.'\nYou say, 'I can go look for you, since you're so busy.'\n6\\. Collect the Residue of Shadow 0/6 (Shadow Valley)\nResidue of Shadow [item=142743] drops off grim shades and drifting shadows. They can be prelooted.\n7\\. Return the Residue of Shadow to Daerius 0/6 (Shadow Valley)\n8\\. Talk with Daerius Jaegir about [the residue] 0/1 (Shadow Valley)\n9\\. Defeat the shade assassin 0/1 (Shadow Valley)\n_Protect yourself from the shaded assassin._\nAn NPC called \"a shaded assassin\" will spawn and charge you at this state. This NPC spawns just a bit NW of Daerius. It only spawned for me when everyone in the group was at this part of the task. The whole group will get credit.\n10\\. Talk with Daerius Jaegir about the [shaded assassin] 0/1 (Shadow Valley)\n_Talk with Daerius Jaegir about what the assassin means._\nReward(s):\n354 platinum 1 gold 6 silver 7 copper\nYou gain experience!\n- Platinum, Experience",
    },
  },
}
