-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Ruins of Shadow Haven (shadowhaventwo)
-- Total Quests: 9
-- ============================================================================

return {
  zone = "shadowhaventwo",
  zone_name = "Ruins of Shadow Haven",
  quests = {
    {
      id = "11153",
      title = "Fungal Corruption",
      exp = "29",
      exp_name = "Night of Shadows",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Record Keeper Ajar",
      loc = nil,
      triggers = {
        "Hail, Record Keeper Ajar",
        "I want to find out what happened to Shadow Haven.",
        "Hail, Coglixar Xorlopodil",
        "How is your report?",
        "I see what?",
        "You will not do what?",
        "I",
        "I don",
      },
      items_required = {
        { name = "you the report", count = 1 },
        { name = "me a moment and", count = 1 },
      },
      rewards = {
        { id = 145308, name = "Coglixar Xorlopodil's Report", type = "item" },
        { id = 145306, name = "Netherbian Fungal Sample", type = "item" },
        { id = 145257, name = "Sealed Sterile Fungal Sample Bag", type = "item" },
        { id = 145299, name = "Shrieker Fungal Sample", type = "item" },
        { id = 145304, name = "Silkworm Fungal Sample", type = "item" },
        { id = 145303, name = "Skeletal Fungal Sample", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Ruins of Shadow Haven [zone=1308]\n**Who:**\n- Record Keeper Ajar [ _Quest_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 130\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Coglixar Xorlopodil's Report [item=145308]\n- Netherbian Fungal Sample [item=145306]\n- Sealed Sterile Fungal Sample Bag [item=145257]\n- Shik`Nar Fungal Sample [Ruins of Shadow Haven]\n- Shik`Nar Fungal Sample [Paludal Depths]\n- Shrieker Fungal Sample [item=145299]\n- Silkworm Fungal Sample [item=145304]\n- Skeletal Fungal Sample [item=145303]\n- Steaon Alarenier's Report [item=145307]\n- Sterile Fungal Sample Bag [item=144286]\n- Underbulk Fungal Sample [Ruins of Shadow Haven]\n- Underbulk Fungal Sample [Firefall Pass]\n- Underbulk Fungal Sample [Paludal Depths]\n**Related Creatures:**\n- Coglixar Xorlopodil [npc=57727]\n- Steaon Alarenier [ _Alchemy Supplies_]\n**Related Quests:**\n- Partisan of Ruins of Shadow Haven (10 Points) [quest=12241]\n**Era:** | !Night of Shadows\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Oct 24 00:45:29 2022\nModified: Wed Feb 21 00:03:06 2024 | | **Night of Shadows Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this task from Record Keeper Ajar in Shadow Haven. He is located at /waypoint 1104, -1062, -46. He's on the Find tool (Ctrl+F).\nYou say, 'Hail, Record Keeper Ajar'\nRecord Keeper Ajar says, 'What what? There's too much to do. Too much to research and record. What do you [want]?'\nYou say, 'I want to find out what happened to Shadow Haven.'\nRecord Keeper Ajar pauses in his frantic note-taking and looks at you. 'Well. Okay. That is worth the interruption. If you want to know, go to Coglixar Xorlopodil and get his report.' He looks at you his, brows creased and nose up. 'Bring it back and I will translate it for you. It will be gibberish to you.'\nYou have been assigned the task 'Fungal Corruption'.\n\n---\n\nRecord Keeper Ajar would like you to gather information so he and others can find the cause of the infestation.\nAsk Coglixar Xorlopodil for his report.\n1\\. Converse with Coglixar Xorlopodil 0/1 Ruins of Shadow Haven\nCoglixar Xorlopodil is located at /way -1189, 746, -74 in the southwest section of the zone, in the southeastern corner.\nYou say, 'Hail, Coglixar Xorlopodil'\nCoglixar Xorlopodil says, in Gnomish, 'Hello. What?'\nYou say, 'How is your report?'\nCoglixar Xorlopodil says, in Gnomish, 'Ah well. I see. Well. Um. Well. [You see].'\nYou say, 'I see what?'\nCoglixar Xorlopodil says, in Gnomish, 'I [will not do] it.'\nYou say, 'You will not do what?'\nCoglixar Xorlopodil says, in Gnomish, 'I won't go out there. If the report is essential to Ajar, then someone else will need to [collect the samples].'\nYou say, 'I'll collect the samples.'\nYou have been given: Sterile Fungal Sample Bag\nYour task 'Fungal Corruption' has been updated.\nCoglixar Xorlopodil says, in Gnomish, 'Splendid. That'll work. I'll put what I need in your journal there, and you go collect fungal samples for me. You do have to go pretty far, but it is necessary. We need to see how far and wide the fungal bloom goes and if it is all as... abnormal as what is being reported. Put all of the specimens in this bag and return them to me.'\nCollect fungal samples from many creatures.\nUnderbulks, Shik`Nar, and Shriekers in Ruins of Shadow Haven and Paludal Depths. These creature may have something unusual about them.\nSkeletons and silkworms in Shadeweaver's Tangle.\nUnderbulks in Firefall Pass.\nNetherbians in Umbral Plains.\n2\\. Collect 1 Underbulk Fungal Sample(s) 0/1 Ruins of Shadow Haven\nUnderbulk Fungal Sample drops from \"an infested burrower\" and \"a corrupted scuttler\"\n3\\. Collect 1 Shik`Nar Fungal Sample(s) 0/1 Ruins of Shadow Haven\nShik`Nar Fungal Sample drops from \"a plagued shik`nar\" and \"a teeming shik`nar\"\n4\\. Collect 1 Shrieker Fungal Sample(s) 0/1 Ruins of Shadow Haven\nShrieker Fungal Sample drops from \"a mature sensate reishi\"\n5\\. Collect 1 Underbulk Fungal Sample(s) 0/1 Paludal Depths\nUnderbulk Fungal Sample drops from a royal guardian, a corrupted scuttler, and an infested burrower\n6\\. Collect 1 Shik`Nar Fungal Sample(s) 0/1 Paludal Depths\nShik`Nar Fungal Sample drops from a plagued shik`nar, a dead eyed shik`nar, a teeming shik`nar, and Toxiplax.\n7\\. Collect 1 Shrieker Fungal Sample(s) 0/1 Paludal Depths\nShrieker Fungal Sample drops from any mushroom-type NPC\n8\\. Collect 1 Skeletal Fungal Sample(s) 0/1 Shadeweaver's Tangle\nSkeletal Fungal Sample drops from a charred shade, a lesser shade, a minor shade, a skeletal brigand, a skeletal hunter, a skeletal thug, and scorched bones.\n9\\. Collect 1 Silkworm Fungal Sample(s) 0/1 Shadeweaver's Tangle\nSilkworm Fungal Sample drops from a xakra larva, and a xakra borer\n10\\. Collect 1 Underbulk Fungal Sample(s) 0/1 Firefall Pass\nUnderbulk Fungal Sample drops from \"a fissure fiend\" and \"a luclinite borer\"\n11\\. Collect 1 Netherbian Fungal Sample item=145306 0/1 Umbral Plains\nNetherbian Fungal Sample drops from several \"a Netherbian\" mobs in the north tunnel in Umbral Planes (ToL). See the item page to see what all it drops from.\n12\\. Seal the Sterile Fungal Sample Bag. 0/1 (ALL)\nCombine all the previously collected items in the Sterile Fungal Sample Bag received from Coglixar Xorlopodil.\n13\\. Deliver 1 Sealed Sterile Fungal Sample Bag to Coglixar Xorlopodil\nCoglixar Xorlopodil says, 'Ah very good. Come back [tomorrow] and I'll give you the report.'\nYou complete the trade with Coglixar Xorlopodil.\nYou say, 'I don't want to wait for tomorrow.'\nCoglixar Xorlopodil says, in Gnomish, 'Well. That's how long it will take me. If you want it done faster, Steaon Alarenier can do a test. I would prefer my method as his procedure is destructive, but if you're in a hurry, he can get the results in minutes. But only if you [insist].'\nYou say, 'I insist'\nCoglixar Xorlopodil sighs, obviously disappointed, and hands the bag back to you.\nYou offered 1 Sealed Sterile Fungal Sample Bag to Steaon Alarenier.\nSteaon Alarenier takes the bag and says, 'Oh Fungus. I'll assume that Coglixar wants this analyzed. This will only take me a minute. Please stay near. We don't want to lose the samples, and you have to start all over again.' He unseals the bag and pours a liquid inside and watches the smoke that rises from the bag with intense concentration. After a few moments he scribbles a report and hands it to you. 'Bring this back to Coglixar; he'll decipher the shorthand I used and make the real report.'\nYou complete the trade with Steaon Alarenier.\n14\\. Speak with Coglixar Xorlopodil after a day has passed. 0/1 (Ruins of Shadow Haven\n_Wait a day and ask Coglixar Xorlopodil for his report, or take the bag to Steaon Alarenier for his report._\nYou offered 1 Steaon Alarenier's Report to Coglixar Xorlopodil.\nCoglixar Xorlopodil sighs. I wish you were patient. Those fungi would have been so interesting to study. Oh well. Give me a moment and... here is your report for Record Keeper Ajar. Now leave me be.\nYou have been given: Coglixar Xorlopodil's Report\nYour task 'Fungal Corruption' has been updated.\nYou complete the trade with Coglixar Xorlopodil.\n_If you wait an in-game day and ask Coglixar Xorlopodil for his report:_\nYou say, 'Hail, Coglixar Xorlopodil'\nCoglixar Xorlopodil says, in Gnomish, 'That was very interesting. Thank you for gathering the samples. The dextrinoid infundibuliform sessile has dichotomous behaviors. Bring this report to Record Keeper Ajar, and he can explain it to you. I want to go back to my research.'\nYou have been given: Coglixar Xorlopodil's Report\nYour task 'Fungal Corruption' has been updated.\n**You gain 69+ AA at level 125**\n15\\. Deliver 1 Coglixar Xorlopodil's Report to Record Keeper Aja _[sic]_ 0/2 (Ruins of Shadow Haven)\nYou offered 1 Coglixar Xorlopodil's Report to Record Keeper Ajar.\nYou have been given: Coglixar Xorlopodil's Report\nYour task 'Fungal Corruption' has been updated.\nRecord Keeper Ajar stares at the report. His eyes flick back and forth so fast they seem to blur. 'That is intriguing. It seems that the owlbear spirit that rampaged through Shadow Haven spread a spiritual corruption that caused some extra fungal bloom. This bloom has spread the many fungal creatures outside of paludal caverns. Take this report to Tarson Lonewolf; he might be able to decipher the spiritual energy.\nYou complete the trade with Record Keeper Ajar.\n16\\. Deliver 1 Coglixar Xorlopodil's Report to Tarson Lonewolf 0/1 (Ruins of Shadow Haven)\nYou offered 1 Coglixar Xorlopodil's Report to Tarson Lonewolf.\nYour task 'Fungal Corruption' has been updated.\nThe report you delivered was useful.\nYou receive 7 copper .\nYou receive 6 silver .\nYou receive 1 gold .\nYou receive 354 platinum .\nYou have gained 1 mercenary ability point(s)! You now have 3 mercenary ability point(s).\nYou have gained 39 ability point(s)! You now have 69 ability point(s).\nYou gain experience! (0.000%)\nTarson Lonewolf spends a moment reading the report. His eyes grow big then he frowns. Once done he stares at you. 'You [will help me] look into this.'\nYou complete the trade with Tarson Lonewolf.\nThis leads into the next task, Spiritual Corruption [quest=12484].\n\n---\n\nReward(s):\n354 platinum 1 gold 6 silver 7 copper\nYou gain experience!\n**Submitted by:** Gidono",
    },
    {
      id = "11155",
      title = "A Miner Setback",
      exp = "29",
      exp_name = "Night of Shadows",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Aliane SteelKnuckle",
      loc = nil,
      triggers = {
        "Hail, Aliane SteelKnuckle",
        "I am heading into the Paludal Caverns.",
        "I tell him that his family is looking for him.",
        "Hail, Noppta Mottun",
        "What was the price?",
        "Who",
        "_Quests_",
        "Paludal Caverns",
      },
      items_required = {
        { name = "Aliane Daesorak's badge 0/1 Ruins of Shadow Haven", count = 1 },
      },
      rewards = {
        { id = 145272, name = "Daesorak's Badge", type = "item" },
        { id = 145271, name = "Overslo's Badge", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Status: Incomplete**\n\nQuest Started By: | Description:\n**Where:**\n- Ruins of Shadow Haven [zone=1308]\n**Who:**\n- Aliane SteelKnuckle [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 120\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Money\n**Quest Items:**\n- Daesorak's Badge [item=145272]\n- Overslo's Badge [item=145271]\n**Related Zones:**\n- Paludal Depths [zone=1307]\n**Related Creatures:**\n- Noppta Mottun [npc=58435]\n- a shik'nar tunneler [npc=58425]\n**Related Quests:**\n- Partisan of Paludal Depths (10 Points) [quest=12239]\n**Era:** | !Night of Shadows\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Fri Oct 28 23:26:08 2022\nModified: Mon Jun 30 13:07:47 2025 | | **Night of Shadows Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this task from Aliane SteelKnuckle in Ruins of Shadow Haven at /waypoint -660, -433, -29 in the southeast part of the zone on the way to Paludal Depths. She is on the Find tool CTRL F.\nYou say, 'Hail, Aliane SteelKnuckle'\nAliane SteelKnuckle's eyes are sunken, with dark circles lined underneath them, this woman has not seen sleep for days. 'You're an adventurer, aren't you? Oh, maybe you can help me!' She nervously fumbles in her pockets for a drawing of a man and shows it to you. 'This is my husband, Daesorak Steelknuckle. Have you seen him lately? He hasn't come home in quite some time and I have grown frantic with worry. Do you plan on exploring the [Paludal Caverns]?'\nYou say, 'I am heading into the Paludal Caverns.'\nAliane SteelKnuckle eyes glisten as she begins to tear up before speaking. 'These cursed caves, Brell can have them for all I care. I just want my husband back!' She wipes the tears forming in her eyes before continuing, 'My husband is a devoted follower of Brell. If he is still in that cave it is because he thinks his god wants him to keep digging. What is the point of it all if he isn't there for his [family]?' Her tone changes from worried to angry. 'Gods can take him if he's still digging, that's for sure!'\nYou say, 'I tell him that his family is looking for him.'\nYou have been assigned the task 'A Miner Setback'.\nAliane SteelKnuckle says, 'Thank you adventurer. He had either be dead or rich when you find him. If it's the latter, I'll kill him myself!'\n\n---\n\nThe miners in the Paludal Caverns have seen better days. Though they have been blessed by Brell in finding a new cave in order to continue their work, it was not without hardships. The miners have lost contact with the outside world and their clans are worried about them. Aliane SteelKnuckle has requested that you look for the miners in the Paludal Caverns and find out what their story is.\n1\\. Find Daesorak SteelKnuckle 0/1 Paludal Depths\nAliane has asked you to look for Daesorak SteelKnuckle inside the Paludal Depths. Any information on his whereabouts will be greatly appreciated.\nThis step updates at /waypoint -1300, -1152, -176 near Sharvyn Oresinger which is on the find tool.\n2\\. Speak to Noppta 0/1 Paludal Depths\nNoppta is near Sharvyn Oresinger.\nYou say, 'Hail, Noppta Mottun'\nYour task 'A Miner Setback' has been updated.\nNoppta Mottun looks you in the eyes as you greet him. 'Adventurer, I find your kind to be proud, yet capable of taking care of themselves. As you can see, Daesorak and Farlol are no longer with us in the realm of the living.' His eyes brim over with tears. 'We lost some good people in the cave-ins. Brell commanded us to dig and so we did, and he blessed us with this new area of the caverns. The [price] was not worth it, I fear.'\nYou say, ' What was the price?'\nNoppta Mottun says, 'The price was many of my brethren's lives. I was unable to save any of them. We dug for what felt like centuries. We dug until our hands bled. Then we dug some more. Our reward was more caves. I would rather have my friends back. I am standing vigil here to ensure that they stay dead. As for the rest of the miners? I can't say for certain what has happened to them. I was able to find some of their badges and will return them when I leave this place. I was looking for one more [badge] before I left this gods-forsaken pit.'\nYou say, 'Who's badge are you looking for?'\nNoppta Mottun pats his pocket, 'Aye, Overslo Herslal, he was our leader. When the cave-ins first started he was the one who held the way open for others to get out to safety. It cost him his life and I have not been able to bring myself to hunt down what happened to his badge. I thought I saw one of those shik'nar with it, but their brains have all turned to mush because of the reishen spores. Your best bet would be to start culling them. Maybe one of those critters have the badge.\n3\\. Locate Overslo's badge amongst the shik`nar 0/6 Paludal Depths\n> **Quest Text:** Noppta Mottun is keeping vigil over the miners' graves. He has asked that you attemp to locate Overslo's badge somewhere within the Paludal Caverns. Hunt the Shik`nar, one of them was last seen with it.\n4\\. Slay the shik`nar tunneller and collect the badge 0/1 Paludal Depths\n/way -965, -835\n5\\. Return Overslo's Badge to Noppta 0/1 Paludal Depths\n6\\. Speak with Aliance SteelKnuckle 0/1 Ruins of Shadow Haven\n7\\. Give Aliane Daesorak's badge 0/1 Ruins of Shadow Haven\n\n---\n\nReward(s):\n141pp 6g 6s 7cp at Level 120\n**Submitted by:** Gidono, Veludeus",
    },
    {
      id = "12484",
      title = "Spiritual Corruption",
      exp = "29",
      exp_name = "Night of Shadows",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Tarson Lonewolf",
      loc = nil,
      triggers = {
        "Yes sir. I will help you.",
        "Commander Yaminshavraylin",
        "The spirits are in pain? Do you know what is causing this?",
        "Tarson Lonewolf.",
        "High Spiritist Jimuul said that something is consuming the spirits",
        "_Shaman Guildmaster and Quests_",
        "will help me",
        "behaving oddly",
      },
      items_required = {
        { name = "the Sealed Spiritual Sample Bag to Lewena_", count = 1 },
      },
      rewards = {
        { id = 145309, name = "Faintly Glowing Digested Pebble", type = "item" },
        { id = 145310, name = "Faintly Glowing Digested Stone", type = "item" },
        { id = 145313, name = "Glowing Rock", type = "item" },
        { id = 145312, name = "Glowing Stone", type = "item" },
        { id = 145315, name = "Sealed Spiritual Sample Bag", type = "item" },
        { id = 145314, name = "Spiritual Sample Bag", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Ruins of Shadow Haven [zone=1308]\n**Who:**\n- Tarson Lonewolf [ _Shaman Guildmaster and Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 120\n**Maximum Level:** | 130\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Faintly Glowing Digested Pebble [item=145309]\n- Faintly Glowing Digested Stone [item=145310]\n- Glowing Rock [item=145313]\n- Glowing Stone [item=145312]\n- Sealed Spiritual Sample Bag [item=145315]\n- Spiritual Sample Bag [item=145314]\n- Weakly Glowing Pebble [item=145311]\n**Related Creatures:**\n- Commander Yaminshavraylin [npc=57728]\n- High Spiritist Jimuul [npc=58026]\n- Lewena [npc=57820]\n**Related Quests:**\n- Partisan of Ruins of Shadow Haven (10 Points) [quest=12241]\n**Era:** | !Night of Shadows\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 6 22:15:26 2022\nModified: Sat May 18 08:46:28 2024 | | **Night of Shadows Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this task from Tarson Lonewolf [npc=57884] in Ruins of Shadow Haven. You can find Tarson Lonewolf at /waypoint 1107, -1160, -46. He is on the find tool as well CTRL F.\n_This quest is received at the conclusion of the previous task, Fungal Corruption._\nTarson Lonewolf spends a moment reading the report. His eyes grow big then he frowns. Once done he stares at you. 'You [will help me] look into this.'\nYou say, 'Yes sir. I will help you.'\nYou have been assigned the task 'Spiritual Corruption'.\nTarson Lonewolf says, 'Good. I heard rumors that there are some elemental beings in Shadow Haven. They should not be here. I need you to take samples and let me know if you see anything suspicious. Start with hopefully clean stone samples in another region so we can do a comparison.'\n\n---\n\n_Tarson Lonewolf needs you to check on the spirit energy found by Coglixar Xorlopodil. These samples will infuse stones._\n_Collect some stones of various sizes from nearby regions. Find them in:_\n_Underbulks in Firefall Pass and Paludal Depths. these creatures may have something unusual about them._\n_Rockhoppers in Shadeweaver's Tangle_\n_Stone creatures in the Ruins of Shadow Haven_\n_Watch the area around the spirit touched stones for something unusual._\n1\\. Collect 2 Faintly Glowing Digested Pebble(s) 0/2 (Firefall Pass)\nFaintly Glowing Digested Pebble drops from a Firefall hollower and a luclinite borer\n2\\. Collect 2 Faintly Glowing Digested Stone(s) 0/2 (Paludal Depths)\nFaintly Glowing Digested Stone drops from \"a royal guardian\"\n3\\. Collect 2 Weakly Glowing Pebble(s) 0/2 (Shadeweaver's Tangle)\nWeakly Glowing Pebble drops from \"a mature hopper\" and \"a needle clawed hopper\" and a clawed hopper\n4\\. Collect 2 Glowing Stone(s) 0/2 (Ruins of Shadow Haven)\nGlowing Stone drops from spirit touched debris, spirit-touched rubble, and spirit touched scrap.\n5\\. Collect 2 Glowing Rock(s) 0/2 (Ruins of Shadow Haven)\nGlowing Rock drops from \"animated debris\", \"animated rubble\" and \"animated scrap\".\n6\\. Watch for something unusual 0/1 (Ruins of Shadow Haven)\n_Commander Yaminsharvaylin is acting cagey._\nI received this update while standing still in the rock area dealing with loot. I was standing still for a couple minutes. Didn't have to do anything else. Not sure on specific mechanics for this update\n7\\. Create 1 Sealed Spiritual Sample Bag using tradeskills. 0/1 (ALL)\n_Seal the Spiritual Sample Bag_\nCombine the 10 rocks inside the Spiritual Sample Bag to create a Sealed Spiritual Sample Bag [item=145315].\n8\\. Deliver 1 Sealed Spiritual Sample Bag to Tarson Lonewolf 0/1 (Ruins of Shadow Haven)\n_Give the Sealed Spiritual Sample Bag to Tarson Lonewolf._\nYou offered 1 Sealed Spiritual Sample Bag to Tarson Lonewolf.\nYour task 'Spiritual Corruption' has been updated.\nTarson Lonewolf studies the contents carefully, examining each rock thoroughly. 'That is concerning. There is something odd about this spiritual energy. You will need to speak to someone with a different view on the topic. Please show these stones to Lewena. While I may be more in tune with spirits than she is, she is more skilled in the natural order of things. Did you see anything or anyone [behaving oddly]?'\nYou complete the trade with Tarson Lonewolf.\n9\\. Converse with Tarson Lonewolf 0/1 (Ruins of Shadow Haven)\n_Explain that you say Commander Yaminshavraylin acting suspicious._\nYou say, 'Commander Yaminshavraylin'\nYou have been given: Sealed Spiritual Sample Bag\nYour task 'Spiritual Corruption' has been updated.\nTarson Lonewolf's skin turns pale, and his eyes widen. 'That is disturbing. As our commander, don't approach her. I'll speak with her while you talk to Lewena.'\n10\\. Deliver 1 Sealed Spiritual Sample Bag to Lewena 0/1 (Ruins of Shadow Haven)\n_Give the Sealed Spiritual Sample Bag to Lewena_\nYou offered 1 Sealed Spiritual Sample Bag to Lewena.\nYou have been given: Sealed Spiritual Sample Bag\nYour task 'Spiritual Corruption' has been updated.\nLewena seems instantly sober. She opens the bag and looks at the rocks. Her lips snarl up toward her nose, and she frowns. 'What did someone do? This is horrible. It's like the spirits are crying out in [pain]!'\nYou complete the trade with Lewena.\nYou say, 'The spirits are in pain? Do you know what is causing this?'\nLewena says, 'Yes. Pain. And no. I do not know. [Who] told you to bring this to me?'\nYou say, 'Tarson Lonewolf.'\nLewena says 'Oh. Okay. Then this isn't a prank.' She glances over her shoulder toward one of the other buildings. 'That means that something is really wrong. Tarson won't know what it is. You should go find High Spiritist Jimuul in Shar Vahl. He might be able to shed some light on what the cause of this is. Take this bag of horrors to him.'\n11\\. Deliver 1 Sealed Spiritual Sample Bag to High Spiritist Jimuul 0/1 (Shar Vahl, Divided)\n_Give the Sealed Spiritual Sample Bag to High Spiritist Jimuul in Shar Vahl_\nYou offered 1 Sealed Spiritual Sample Bag to High Spiritist Jimuul.\nHigh Spiritist Jimuul Glares at you in anger then studies the stones in the bag. His eyebrows dip into a frown. 'That is disturbing.' He shakes his head as if he's sloughing water. 'What is here are remnants, and you have not brought me spirits that you harmed. Tell whoever started you on this research that there is something consuming the spirits.'\nYou have been given: Sealed Spiritual Sample Bag\nYour task 'Spiritual Corruption' has been updated.\nYou complete the trade with High Spiritist Jimuul.\n12\\. Deliver 1 Sealed Spiritual Sample Bag to Tarson Lonewolf 0/1 (Ruins of Shadow Haven)\n_Return the Sealed Spiritual Sample Bag to Tarson Lonewolf_\nYou offered 1 Sealed Spiritual Sample Bag to Tarson Lonewolf.\nYour task 'Spiritual Corruption' has been updated.\nTarson Lonewolf says, 'Thank you. Lewena told me she sent you to see [High Spiritist Jimuul]. What did he have to say?'\nYou complete the trade with Tarson Lonewolf.\n13\\. Converse with Tarson Lonewolf 0/1 (Ruins of Shadow Haven)\nYou say, 'High Spiritist Jimuul said that something is consuming the spirits'\nYour task 'Spiritual Corruption' has been updated.\nYou determined that something is consuming the spiritual energy, even if you have not found the reason for that energy.\nYou receive 5 copper .\nYou receive 2 silver .\nYou receive 6 gold .\nYou receive 265 platinum .\nYou have gained 1 mercenary ability point(s)! You now have 12 mercenary ability point(s).\nYou have gained 36 ability point(s)! You now have 138 ability point(s).\nYou gain experience! (0.000%)\nTarson Lonewolf says, 'That is disturbing. I expect that the explosive fungal growth is caused by the spiritual corruption. I may have an inkling of the cause, but I don't want to believe it. I need some confirmation but getting it might be somewhat dangerous. Are you [interested]?'\n_This leads into the final task of the Partisan of Ruins of Shadow Haven series: Power Corrupts._\n_\n---\n_\n_Reward(s)_\n_265 platinum 6 gold 2 silver 5 copper_\n_Experience!_\n**Submitted by:** Cylius & Laurana",
    },
    {
      id = "12485",
      title = "Power Corrupts",
      exp = "29",
      exp_name = "Night of Shadows",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Tarson Lonewolf",
      loc = nil,
      triggers = {
        "I am interested",
        "Hail, Tarson Lonewolf",
        "It started simple. She wasn",
        "Yes, it was normal. She left the library and spent a minute observing goings on from the bridge nearby. She then went to the banker and asked if anyone had been acting suspiciously. When she received a negative answer, she studied the room, then moved on. She walked around a bit, then out into the city center where the fungal creatures have taken over. Then, as she moved east towards the wall where the stone creatures are, she turned herself invisible.",
        "No. She didn",
        "Yes, they glowed purple. Once she did that at all three, she walked back. At about the same point, she cleared the invisibility and then returned to her patrol of this area. The weirdest thing of all is when she got to the door. She did absolutely nothing but stare at it. But I swear that, out of the corner of my eye, almost out of sight, the door winked at her. But, no matter how long I looked, I could not find eyes or anything like that on the door. Nothing that makes the door unusual. It",
        "_Shaman Guildmaster and Quests_",
        "interested",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Ruins of Shadow Haven [zone=1308]\n**Who:**\n- Tarson Lonewolf [ _Shaman Guildmaster and Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 120\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Related Quests:**\n- Partisan of Ruins of Shadow Haven (10 Points) [quest=12241]\n**Era:** | !Night of Shadows\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 6 22:17:18 2022\nModified: Tue Dec 5 05:21:04 2023 | | _This task is received at the conclusion of the previous task: Spiritual Corruption\"_\nTarson Lonewolf says, 'That is disturbing. I expect that the explosive fungal growth is caused by the spiritual corruption. I may have an inkling of the cause, but I don't want to believe it. I need some confirmation but getting it might be somewhat dangerous. Are you [interested]?'\nYou say, 'I am interested'\nYou have been assigned the task 'Power Corrupts'.\nTarson Lonewolf says, 'Great. I'll need you to kill some of the spirit-touched and animated rocks to release the spirits and get them away from whatever is consuming them. Then I'll want you to follow Commander Yaminshavraylin without letting her know you are following her.'\n\n---\n\n_Destroy spirit-touched and animated debris, rubble, and scrap._\n_Follow Commander Yaminshavraylin, but don't allow yourself to be seen._\n1\\. Kill 5 spirit-touched debris, rubble, and scrap 0/5 (Ruins of Shadow Haven)\n2\\. Kill 5 animated debris, rubble, and scrap 0/5 (Ruins of Shadow Haven)\n3\\. Follow Commander Yaminshavraylin 0/1 (Ruins of Shadow Haven)\n4\\. Follow Commander Yaminshavraylin 0/1 (Ruins of Shadow Haven)\n5\\. Follow Commander Yaminshavraylin 0/1 (Ruins of Shadow Haven)\n6\\. Follow Commander Yaminshavraylin 0/1 (Ruins of Shadow Haven)\n7\\. Follow Commander Yaminshavraylin 0/1 (Ruins of Shadow Haven)\n8\\. Follow Commander Yaminshavraylin 0/1 (Ruins of Shadow Haven)\n9\\. Follow Commander Yaminshavraylin 0/1 (Ruins of Shadow Haven)\n10\\. Converse with Tarson Lonewolf 0/1 (Ruins of Shadow Haven)\nYou say, 'Hail, Tarson Lonewolf'\nTarson Lonewolf says, 'So what was the Commander [doing]?'\nYou say, 'It started simple. She wasn't doing anything weird. The Commander started fairly mundanely. She walked to the library and looked about the room as usual for someone doing a patrol.'\nTarson Lonewolf says, 'That is [normal]. Continue; I'll interrupt again when you speak about something abnormal.'\nYou say, 'Yes, it was normal. She left the library and spent a minute observing goings on from the bridge nearby. She then went to the banker and asked if anyone had been acting suspiciously. When she received a negative answer, she studied the room, then moved on. She walked around a bit, then out into the city center where the fungal creatures have taken over. Then, as she moved east towards the wall where the stone creatures are, she turned herself invisible.'\nTarson Lonewolf says, 'Invisible? Really? That's weird... By all reports she is a warrior, so she should not know how to cast spells. Did she drink a [potion]? And what did she do next?'\nYou say, 'No. She didn't drink a potion. She used some sort of magic. I can't rule out that she had an item she could activate with concentration. Once she was invisible, she moved up to the piles of rubble. She spent about five minutes at the three largest piles against the outer wall. She would look for people observing her, and after a pause, her hands glowed purple for a minute or so.'\nTarson Lonewolf says, 'You say her hands [glowed]?'\nYou say, ' Yes, they glowed purple. Once she did that at all three, she walked back. At about the same point, she cleared the invisibility and then returned to her patrol of this area. The weirdest thing of all is when she got to the door. She did absolutely nothing but stare at it. But I swear that, out of the corner of my eye, almost out of sight, the door winked at her. But, no matter how long I looked, I could not find eyes or anything like that on the door. Nothing that makes the door unusual. It's just a door. I think I'm only being paranoid and the stress of following her made me imagine things.'\nYour task 'Power Corrupts' has been updated.\nCommander Yaminshavraylin is acting suspiciously, and something is very odd about the door.\nYou receive 5 copper .\nYou receive 2 silver .\nYou receive 6 gold .\nYou receive 265 platinum .\nYou have gained 1 mercenary ability point(s)! You now have 16 mercenary ability point(s).\nYou have gained 36 ability point(s)! You now have 78 ability point(s).\nYou gain experience! (0.000%)\nTarson Lonewolf says, 'That is disturbing. I'll be sure that this is looked into, but at this point, I don't have the power to gainsay her, and I don't wish for you to harm her. I would instead like for you to see Animist Khalan. Tell him about the door.'\nYou have gained 18 ability point(s)! You now have 96 ability point(s).\nYou have gained 1 mercenary ability point(s)! You now have 17 mercenary ability point(s).\nYou gain experience! (0.412%)\nYou have completed achievement: Partisan of Ruins of Shadow Haven\n\n---\n\nReward(s):\n256 platinum 6 gold 2 silver 5 copper\nYou gain experience!\n**Submitted by:** Cylius & Laurana",
    },
    {
      id = "12486",
      title = "When One Door Closes (Group Mission)",
      exp = "29",
      exp_name = "Night of Shadows",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Animist Khalan",
      loc = nil,
      triggers = {
        "Hail, Animist Khalan",
        "I don",
        "small",
        "ready",
        "_Raid and Mission_",
        "what is going on",
        "large",
      },
      items_required = {
      },
      rewards = {
        { id = 145000, name = "Shaded Specie", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Ruins of Shadow Haven [zone=1308]\n**Who:**\n- Animist Khalan [ _Raid and Mission_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 117\n**Maximum Level:** | 130\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Expedition\n**Quest Goal:**\n- Advancement\n- Experience\n- Loot\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 05:00:00\n**Related Zones:**\n- Ruins of Shadow Haven: When One Door Closes (Group) [zone=1314]\n**Related Creatures:**\n- Mutable Monstrosity [npc=58622]\n- a solid chest [npc=58623]\n**Related Quests:**\n- Hero of Ruins of Shadow Haven: When One Door Closes (10 Points) [quest=12254]\n- Power Corrupts [quest=12485]\n- Savior of Ruins of Shadow Haven: When One Door Closes (20 Points) [quest=12255]\n**Era:** | !Night of Shadows\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 6 22:20:00 2022\nModified: Sun Mar 31 01:44:24 2024 | | **Night of Shadows Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\n**Prerequisite: Complete Power Corrupts [quest=12485]**\n\n---\n\nYou can obtain this mission from Animist Khalan [npc=58436] in Ruins of Shadow Haven (NoS). You can find Animist Khalan at /waypoint 594, -668, -86. He is on the find tool as well CTRL F.\nTested minimum level so far: 117 for attending, could be lower.\nIf you are not flagged, you will see the following:\nYou say, 'Hail, Animist Khalan'\nAnimist Khalan says, 'The time has not yet come to deal with this event.'\n\\- \\- \\- - -\nIf you are flagged, you will see the following:\nYou say, 'Hail, Animist Khalan'\nAnimist Khalan says, 'Hello, Soandso. Ever since that... thing crashed through our homes, I have been concerned. It seems that everyone is just ignoring that it came from someplace and left to someplace. They act like it just appeared out of nowhere. I remember what happened; I was here when the ground shook. That sound, that horrible sound, shook the ground like nothing I've known before. Then, a moment later, the beast crashed through that door, shattering much of the stone around it. And that's how it left. I'm certain of it. But none of my investigations have explained why that door is still there. Rumor has it that you have discovered something about [what is going on].'\nYou say, 'I don't know exactly what is going on, but I don't think you are wrong. There is something wrong with that door. I was following the commander, and I know I saw the door wink. I can't prove it, but I saw it! We should take more people and look more closely at the door'\nAnimist Khalan says, 'That's good to hear. It could be better to investigate with a [small] group. However, if you can bring a [large] force to the problem I guess it would be safer for you.'\nYou say, 'small'\nAnimist Khalan says, 'Maybe I'm not the crazy one around here. I would be grateful if you were to take me with you when you test out your theory. All I ask is that you let me know when you are [ready] and I will happily go with you.'\nYou have received a request timer for 'When One Door Closes': 0d:0h:1m remaining.\nYou have been assigned the task 'When One Door Closes'.\nYou say, 'ready'\nAnimist Khalan says, 'Good, good! I can't wait to find out what is going on.'\nLOADING, PLEASE WAIT...\n\n---\n\nThere is something odd about the door in the north of Shadow Haven. Animist Khalan assures you that he saw a monster crash out of the door and completely destroy it. Hopefully you have the key that unlocks the mystery.\n1\\. Discover what is going on with the door. 0/1 (Ruins of Shadow Haven)\nDefeat 'Mutable Monstrosity'\n2\\. Open the chest. 0/1 (Ruins of Shadow Haven)\n\n---\n\nReward(s):\n177 platinum 8 silver 4 copper\nYou gain experience!\n45 Shaded Specie\n**Submitted by:** Cylius & Laurana, Veludeus\n- Shaded Specie [item=145000]",
    },
    {
      id = "12487",
      title = "Phlarg the Patog Plerg",
      exp = "29",
      exp_name = "Night of Shadows",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Commander Zaerel",
      loc = nil,
      triggers = {
        "Hail, Commander Zaerel",
        "What do you mean my type?",
        "I will help",
        "I haven",
        "I will kill fiends",
        "_Quests_",
        "type",
        "help",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Ruins of Shadow Haven [zone=1308]\n**Who:**\n- Commander Zaerel [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 120\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Related Quests:**\n- Mercenary of Ruins of Shadow Haven (10 Points) [quest=12240]\n**Era:** | !Night of Shadows\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 6 22:23:03 2022\nModified: Tue Dec 5 05:21:04 2023 | | **Night of Shadows Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this task from Commander Zaerel [npc=57729] in Ruins of Shadow Haven. He is located at /waypoint -553, -557, -34. He's not on the Find tool Ctrl F.\nYou say, 'Hail, Commander Zaerel'\nCommander Zaerel says, 'Greetings adventurer! I'm relieved to see your [type] arrive at Shadow Haven. Will you [help] with our infestation?'\nYou say, 'What do you mean my type?'\nCommander Zaerel says, 'Oh. I meant no offense. Adventurers are not perfect. Like any person, they make mistakes and sometimes do harm, but for the most part, adventurers are a boon to Norrath and Luclin. [Commander Kelrein] taught me to respect you and what you bring to Shadow Haven.'\nYou say, 'I will help'\nCommander Zaerel says, 'Thank you. Will you kill [fiends], [shik`nar], [shriekers], [underbulks], or [all of them]?'\nYou say, 'I haven't seen Commander Kelrein'\nCommander Zaerel says, 'Ah yes. I wish some adventurers were around then. When the giant owlbear spirit broke through the door and rampaged through Shadow Haven, he was killed during the attempts to turn the beast around.'\nYou say, 'I will kill fiends'\nCommander Zaerel says, 'Fantastic. Thank you.'\nYou have been assigned the task 'Phlarg the Patog Plerg'.\n\n---\n\n1\\. Kill 6 Fungal Fiends 0/6 Ruins of Shadow Haven\n_Commander Zaerel needs your help to reduce the number of creatures invading from Paludal Caverns_\n_Kill plerg phlarg fiends and patog flarg fiends._\n\n---\n\nReward(s):\n118 platinum 5 silver 6 copper\nYou gain experience!\n**Submitted by:** Cylius & Laurana",
    },
    {
      id = "12488",
      title = "Chitenous Horrors",
      exp = "29",
      exp_name = "Night of Shadows",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Commander Zaerel",
      loc = nil,
      triggers = {
        "Hail, Commander Zaerel",
        "What do you mean my type?",
        "I will help",
        "I haven",
        "I will kill shik`nar",
        "_Quests_",
        "type",
        "help",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Ruins of Shadow Haven [zone=1308]\n**Who:**\n- Commander Zaerel [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 120\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Money\n**Related Quests:**\n- Mercenary of Ruins of Shadow Haven (10 Points) [quest=12240]\n**Era:** | !Night of Shadows\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 6 22:23:41 2022\nModified: Tue Dec 5 05:21:04 2023 | | You say, 'Hail, Commander Zaerel'\nCommander Zaerel says, 'Greetings adventurer! I'm relieved to see your [type] arrive at Shadow Haven. Will you [help] with our infestation?'\nYou say, 'What do you mean my type?'\nCommander Zaerel says, 'Oh. I meant no offense. Adventurers are not perfect. Like any person, they make mistakes and sometimes do harm, but for the most part, adventurers are a boon to Norrath and Luclin. [Commander Kelrein] taught me to respect you and what you bring to Shadow Haven.'\nYou say, 'I will help'\nCommander Zaerel says, 'Thank you. Will you kill [fiends], [shik`nar], [shriekers], [underbulks], or [all of them]?'\nYou say, 'I haven't seen Commander Kelrein'\nCommander Zaerel says, 'Ah yes. I wish some adventurers were around then. When the giant owlbear spirit broke through the door and rampaged through Shadow Haven, he was killed during the attempts to turn the beast around.'\nYou say, 'I will kill shik`nar'\nCommander Zaerel says, 'Fantastic. Thank you.'\nYou have been assigned the task 'Chitenous Horrors'.\n\n---\n\n1\\. Kill 9 Shik Nar 0/9 (Ruins of Shadow Haven)\n_Commander Zaerel needs your help to reduce the number of creatures invading from Paludal Caverns._\n_Kill shik`nar outcasts, teeming shik`nars, and plagued shik`nars._\n\n---\n\nReward(s):\n118 platinum 5 silver 6 copper\nYou gain experience!\n**Submitted by:** Cylius & Laurana",
    },
    {
      id = "12489",
      title = "Fear the Shrieker",
      exp = "29",
      exp_name = "Night of Shadows",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Commander Zaerel",
      loc = nil,
      triggers = {
        "Hail, Commander Zaerel",
        "What do you mean my type?",
        "I will help",
        "I haven",
        "I will kill shriekers",
        "_Quests_",
        "type",
        "help",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Ruins of Shadow Haven [zone=1308]\n**Who:**\n- Commander Zaerel [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 120\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Money\n**Related Quests:**\n- Mercenary of Ruins of Shadow Haven (10 Points) [quest=12240]\n**Era:** | !Night of Shadows\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 6 22:24:16 2022\nModified: Tue Dec 5 05:21:04 2023 | | You say, 'Hail, Commander Zaerel'\nCommander Zaerel says, 'Greetings adventurer! I'm relieved to see your [type] arrive at Shadow Haven. Will you [help] with our infestation?'\nYou say, 'What do you mean my type?'\nCommander Zaerel says, 'Oh. I meant no offense. Adventurers are not perfect. Like any person, they make mistakes and sometimes do harm, but for the most part, adventurers are a boon to Norrath and Luclin. [Commander Kelrein] taught me to respect you and what you bring to Shadow Haven.'\nYou say, 'I will help'\nCommander Zaerel says, 'Thank you. Will you kill [fiends], [shik`nar], [shriekers], [underbulks], or [all of them]?'\nYou say, 'I haven't seen Commander Kelrein'\nCommander Zaerel says, 'Ah yes. I wish some adventurers were around then. When the giant owlbear spirit broke through the door and rampaged through Shadow Haven, he was killed during the attempts to turn the beast around.'\nYou say, 'I will kill shriekers'\nCommander Zaerel says, 'Fantastic. Thank you.'\nYou have been assigned the task 'Fear the Shrieker'.\n\n---\n\n1\\. Kill 14 Shriekers 0/14 (Ruins of Shadow Haven)\n_Commander Zaerel needs your help to reduce the number of creatures invading from Paludal Caverns._\n_Kill sensate reishi and reishi sprouts._\n\n---\n\nReward(s):\n118 platinum 5 silver 6 copper\nYou gain experience!\n**Submitted by:** Cylius & Laurana",
    },
    {
      id = "12490",
      title = "They are Under What?",
      exp = "29",
      exp_name = "Night of Shadows",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Commander Zaerel",
      loc = nil,
      triggers = {
        "Hail, Commander Zaerel",
        "What do you mean my type?",
        "I will help",
        "I haven",
        "I will kill underbulks",
        "_Quests_",
        "type",
        "help",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Ruins of Shadow Haven [zone=1308]\n**Who:**\n- Commander Zaerel [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 120\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Money\n**Related Quests:**\n- Mercenary of Ruins of Shadow Haven (10 Points) [quest=12240]\n**Era:** | !Night of Shadows\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Dec 6 22:24:51 2022\nModified: Tue Dec 5 05:21:04 2023 | | You say, 'Hail, Commander Zaerel'\nCommander Zaerel says, 'Greetings adventurer! I'm relieved to see your [type] arrive at Shadow Haven. Will you [help] with our infestation?'\nYou say, 'What do you mean my type?'\nCommander Zaerel says, 'Oh. I meant no offense. Adventurers are not perfect. Like any person, they make mistakes and sometimes do harm, but for the most part, adventurers are a boon to Norrath and Luclin. [Commander Kelrein] taught me to respect you and what you bring to Shadow Haven.'\nYou say, 'I will help'\nCommander Zaerel says, 'Thank you. Will you kill [fiends], [shik`nar], [shriekers], [underbulks], or [all of them]?'\nYou say, 'I haven't seen Commander Kelrein'\nCommander Zaerel says, 'Ah yes. I wish some adventurers were around then. When the giant owlbear spirit broke through the door and rampaged through Shadow Haven, he was killed during the attempts to turn the beast around.'\nYou say, 'I will kill underbulks'\nCommander Zaerel says, 'Fantastic. Thank you.'\nYou have been assigned the task 'They are Under What?\n\n---\n\n1\\. Kill 9 Underbulks 0/9 (Ruins of Shadow Haven)\n_Commander Zaerel needs your help to reduce the number of creatures invading from Paludal Caverns._\n_Kill grim tunnelers, sediment delvers, infested burrowers, and corrupted scuttlers._\n\n---\n\nReward(s):\n118 platinum 5 silver 6 copper\nYou gain experience!\n**Submitted by:** Cylius & Laurana",
    },
  },
}
