-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Fear Itself (thuledream)
-- Total Quests: 8
-- ============================================================================

return {
  zone = "thuledream",
  zone_name = "Fear Itself",
  quests = {
    {
      id = "5234",
      title = "An Offering to Thule",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Tiseth the Thrall",
      loc = nil,
      triggers = {
        "Hail, Tiseth the Thrall",
        "Let",
        "Ready to begin!",
        "Hail, a frightened follower",
        "meet",
        "begin",
        "out",
      },
      items_required = {
      },
      rewards = {
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Fear Itself [zone=756]\n**Who:**\n- Tiseth the Thrall [npc=36667]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 90\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Faction\n- Loot\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 06:00:00\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Zones:**\n- Fear Itself: An Offering to Thule [zone=778]\n**Related Creatures:**\n- Cazic Thule - Fear Itself - 1 [npc=36896]\n- Dread [npc=36901]\n- Fright [npc=36902]\n- Terris Thule [npc=36897]\n- Terror [npc=36903]\n- Tiseth the Thrall [npc=36898]\n- a boogeyman [npc=36922]\n- a boogeyman`s shadow [npc=36921]\n- a deranged gorgon [npc=36906]\n- a fetid fiend [npc=36911]\n- a frightfinger [npc=36925]\n- a glarelord [npc=36914]\n- a gorgon [npc=36907]\n- a lesser scareling [npc=36919]\n- a miniature frightfinger [npc=36923]\n- a phantasm [npc=36916]\n- a phoboplasm [npc=36918]\n- a rotted fetid fiend [npc=36910]\n- a scareling [npc=36920]\n- a shadow phantasm [npc=36915]\n- a small phoboplasm [npc=36917]\n- a weakened glarelord [npc=36913]\n- an amygdalan knight [npc=36904]\n- an amygdalan soldier [npc=36905]\n- an amygdalan warrior [npc=36912]\n- an ornate chest - An Offering to Thule [npc=36894]\n**Related Quests:**\n- Alezra #1: Bite of the Beast [quest=5235]\n- Alezra #2: Follower of Fear [quest=5236]\n- Alezra #3: At the Altar of Fear [quest=5237]\n- Catastrophic Power [quest=5216]\n- Miragul's Vendetta [quest=5232]\n- Redemption [quest=5202]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 17 16:10:24 2010\nModified: Tue Dec 5 05:21:04 2023 | | _This is a group progression task that begins with Tiseth the Thrall in Fear Itself (located within the Ring of Fire at the top of the temple)._\n_You must have completed the following tasks in order to request it:_\n\\- Bite of the Beast\n\\- Follower of Fear\n\\- At the Altar of Fear\n\\- Redemption (House of Thule Upper mission)\n\\- Catastrophic Power (Al'Kabor mission)\n\\- Miragul's Vendetta (Miragul's Nightmare mission)\n_Note: The Well mission \"What Lies Below\" also used to be required. However, a patch on December 8, 2010, eliminated this requirement._\nYou say, 'Hail, Tiseth the Thrall'\nTiseth the Thrall says 'With your pledge, Cazic Thule has taken notice. I can feel his power building all around us. It is finally time to [meet] our God! He will reward our efforts to spread fear in this realm, and spare us from his vengeful wrath. Followers of Thule will be welcomed into Cazic's fearful embrace, and allowed to rule alongside him in the Plane of Fear.'\nYou say, 'Let's meet him...'\n_Without pre-requisites, you see:_\nTiseth the Thrall says 'I really need you to speak to Lilth or Elard Velsorn in the house, or perhaps the Nightmare Emissary, who lives in my nightmares.'\n_With pre-requisites, you see:_\nTiseth the Thrall says 'I will gather our fellow followers, and together we will sacrifice every living creature within this realm as an offering to Cazic Thule. He cannot ignore our devotion! Are you ready to [begin]?'\nYou have been assigned the task 'An Offering to Thule'.\nYou say, 'Ready to begin!'\nTiseth the Thrall says 'We will meet again, \\_\\_\\_\\_\\_, before our God!'\n\n---\n\n_The first 13 steps are open from the start of the task. All mob types are found in groups of six. The mobs in these groups can't be split from each other (they're aggro-linked)._\n_Each group of mobs has a main mob that hits like a regular Fear mob (max ~7,500) and has a normal amount of hitpoints. In addition to the main mob, there are five lesser mobs that are usually blue-cons (though sometimes even cons), hit for much less, and have much less hitpoints._\n_Fright, Dread, and Terror each hit for a max ~7,500; are slowable; and are immune to mez, root, and snare. None of the golems has any AEs or special attacks (no flurry; no rampage)._\n_Note: There is an achievement associated with this task for leaving Fright, Dread, and Terror as the last remaining kills._\nWipe out all amygdalans 0/24 (Fear Itself)\nSlaughter all boogeymen 0/12 (Fear Itself)\nDestroy all fetid fiends 0/18 (Fear Itself)\nDefeat all frightfingers 0/12 (Fear Itself)\nEliminate all glarelords 0/12 (Fear Itself)\nKill all gorgons 0/12 (Fear Itself)\nAnnihilate all phantasms 0/12 (Fear Itself)\nExterminate every last phoboplasm 0/12 (Fear Itself)\nEradicate the entirety of samhains 0/12 (Fear Itself)\nSacrifice all scarelings 0/12 (Fear Itself)\nKill Dread 0/1 (Fear Itself)\nKill Fright 0/1 (Fear Itself)\nKill Terror 0/1 (Fear Itself)\n_NOTE: The task locks after you complete the last of any of the above steps._\n\n---\n\nMeet Tiseth and devotees at the base of the blood mound 0/1 (Fear Itself)\nSpeak with Tiseth and confront Cazic Thule 0/1 (Fear Itself)\nYou say, 'Hail, Tiseth the Thrall'\nTiseth the Thrall says 'This is it, \\_\\_\\_\\_\\_. The moment we have been preparing for. We are in the presence of a God! Cazic Thule shall recognize our efforts to spread fear, and welcome us into him realm. Come, let us confront our God and receive our humble reward!'\nTiseth the Thrall says 'Cazic Thule, God of Fear, hear us! Your loyal servants, eager to do your bidding! We await your command.'\nCazic Thule's spikes bristle, and a guttural rasp penetrates your mind. 'Death is not the only thing a mortal fears. I am an adder beneath the brush; I am a wolf beyond the gleam of campfires. I am a spy in a kingdom at war; I am a bastard in the castle of a king; I am a traitor in the ranks of an army. I am the loss of an eye or limb; I am the humiliation of courtesans; I am the scorn of a desired lover. And I am everlasting punishment.\nYour task 'An Offering to Thule' has been updated.\nCazic Thule says 'How many like you have I killed, tortured, maimed? Here their blood surges with the fear of imminent death, as undoubtedly yours does. I could dismember you inch by inch, staunching your blood each time I tear off more of your body. I could flay you and splay your living flesh like a banner over my spines, every exposed nerve pierced and wailing. I am unbearable pain that does not end in death.'\nCazic Thule says 'I am the obliteration of you and all of your companions. You have fought together and bled together. Now you shall die together.'\n_This opens the next step._\nKill Cazic Thule 0/1 (Fear Itself)\n_He hits for a max ~8,000 and casts the spells \"Cazic's Inferno\" and \"Fearful Force\":_\nCazic's Inferno: PB AE 500', Fire (-700)\n1: Decrease Hitpoints by 19000\nFearful Force: Single Target, Magic (-700)\n1: Decrease HP when cast by 10121\n2: Decrease Movement by 200%\n_Once he reaches about 50% health, Cazic Thule goes non-attackable, runs away a bit to a tower, and..._\nCazic Thule's labored words form in your mind. 'I did not think this possible, but you have proven it to me. Somehow, this plane is not my own. How long ago was it? My daughter, Terris, appeared to me and bade me walk with her. She showed to me a mansion as expansive and resplendent as the very rays of Sol. We entered, and her voice faded into memory, like chimes on the wind. I was again here, in my plane.\nCazic Thule says 'The hills soon ran with blood. Adventurers came by the thousands. I dashed their skulls against this obelisk and pulled apart their bones. They flung themselves at me, cowered, and then died in agony. But never had there been so many. And they began to look the same.'\nCazic Thule says 'I wandered this plane but found no escape. I began to see visions: A luminous horn pulsing at the edge of perception; the voice of my son, Morell, rising above my daughter's. And my strength began to wane. Longer and longer it took for me to decimate an entire regiment of soldiers.'\nCazic Thule says 'And now you have me on the cusp of death. Yes, I am now certain: My children have imprisoned me, and they weaken me unto destruction. To what end I do not know. What drives a child to harbor malice and guile against their parent? Are not dreams and nightmares bastions of fear? Does not the child learn to fight or flee from the vicious predator in the safety of dreams or nightmares? Without me, my children have no purpose.'\nCazic Thule's words come slowly. 'And what of you? What power do you have over me? What quarrel do we have? Would you walk blithely into a throng of swords and spears arrayed against you? Would you sacrifice yourself for another without hesitation, or would you thrust a companion into a rain of arrows to shield yourself from death? I can save or destroy you. You hate me, but I bring balance to your existence. Without Fear, you are all doomed.'\n_At this point, Cazic Thule's health drops to 1%, and it's possible to attack him again. You can finish him off here._\nCazic Thule has been slain by \\_\\_\\_\\_\\_!\nClaim your reward from the ornate chest 0/1 (Fear Itself)\nYou have defeated Cazic Thule within his dream realm, and are now able to further explore the House of Thule.\n_When the chest spawns, an untargettable version of Terris Thule appears and a short script runs. Some spell effects appear to show her absorbing her father's power, and then she disappears._\nTerris Thule stares at the corpse of her father. 'You were a fool, Cazic. Your power was instinctual, but mine is intellectual; you controlled the body, but I control the mind. And now I will have both. He cannot stop me; you cannot stop me!'\nTerris Thule says 'Do you hear me, adventurers? It constantly amazes me how stupid you are! Did you think you defeated me? Did you think you had any power over nightmares? Did you think these hills and corpses were anything other than dreams? And now you have killed my father. Do not fear, though. You are my precious little puppets, always running around, killing everything that poses the slightest bit of threat to you. If you had not killed him, I would have done so myself. His time was at an end.'\nTerris Thule says 'When he took me to the house, his horn was glowing brighter than ever. He said his power resonated within the walls, and near the winged statues his thoughts sprang to life: hallways that submerged into sunken caverns, gables that floated off into clouds. I touched a statue, and a banister changed to a hundred writhing adders. Morell pressed deeper into the house, but I had other plans.'\nTerris Thule says 'I brought Cazic inside, rested my hand on his arm, and touched a statue. He fell into the nightmare you see now, never to awake. Morell objected, but he was more interested in his augmented powers than my designs. And besides, since when have dreams alone held more power than nightmares? How would that weakling be able to challenge me?'\nTerris Thule says 'And now he will certainly have no recourse. I will draw to me the remnants of Cazic's power...'\nTerris Thule screams in pain and anger as a portal opens around her. 'Is this your doing, adventurers? You have no idea what magnitude of power you are playing with! Morell, help me! Do not let them take our father!'\n_A frightened follower spawns nearby as a means to zone out:_\nYou say, 'Hail, a frightened follower'\na frightened follower says 'Please, don't hurt me! I... I can show you the way [out] if you'll spare my life.'\n\n---\n\n_Task Rewards:_\n? platinum\nExperience\nFaction with Dream Delvers\n? Dream Motes\n_Known chest rewards (1 item + 1 spell per task):_\nMinor Nebulous Dream Fragment\nLesser Nebulous Dream Fragment\nMedian Nebulous Dream Fragment\nGreater Nebulous Dream Fragment\nGlowing Nebulous Dream Fragment\nDagger of Anguish\nDread's Blade\nIreblind Imp Heart\nMammoth Hide Leathers\nNightmarish Leather Coat\nOrnamental Iron Shield\nSilver Belt of Purity\nSotor's Hammer of Pain\nSpirit of the Gorgon\nStrawgolem Stuffing\n- Dream Mote [item=90255]",
    },
    {
      id = "5237",
      title = "Alezra \\#3: At the Altar of Fear",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Alezra D`Vour",
      loc = nil,
      triggers = {
        "Ready",
        "Hail, Alezra D`Vour",
        "Hail, Tiseth the Thrall",
        "_Quests_",
        "ready",
      },
      items_required = {
        { name = "the remains to Alezra 0/1 (Fear Itself)", count = 1 },
      },
      rewards = {
        { id = 93738, name = "Cursed Skeletal Remains", type = "item" },
        { id = 93679, name = "Skeletal Remains", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Fear Itself [zone=756]\n**Who:**\n- Alezra D`Vour [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 90\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Quest Items:**\n- Cursed Skeletal Remains [item=93738]\n- Skeletal Remains [item=93679]\n**Related Creatures:**\n- Tiseth the Thrall [npc=36667]\n- a fetid fiend [npc=36614]\n- a phoboplasm [npc=36620]\n- a shiverback [npc=36660]\n**Related Quests:**\n- Alezra #1: Bite of the Beast [quest=5235]\n- Alezra #2: Follower of Fear [quest=5236]\n- An Offering to Thule [quest=5234]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sun Nov 21 04:55:02 2010\nModified: Tue Dec 5 05:21:04 2023 | | _This solo task is the third in a series of three. It begins with Alezra D`Vour in Fear Itself. She's found in a small tower a little ways east of the zone-in._\n_You must have completed the \"Bite of the Beast\" and \"Follower of Fear\" tasks before you can request this one._\nAlezra D`Vour says 'After passing the trials of devotion, initiates partake in a sacred ritual, which culminates when they stand before our leader and are judged. We call her Tiseth the Thrall. She speaks to Cazic directly, and solely decides who is worthy of joining our ranks. The ritual will begin with you are [ready].'\nYou say, 'Ready'\nAlezra D`Vour says 'In Cazic's name, slaughter a myriad of creatures, and bring their remains to me.'\nYou have been assigned the task 'At the Altar of Fear'.\nIn order to join the ranks of Cazic's devotees, you must participate in a sacred ritual and appear before their leader, Tiseth the Thrall.\n\n---\n\nKill fetid fiends in the name of Cazic Thule 0/6 (Fear Itself)\nKill shiverbacks in the name of Cazic Thule 0/2 (Fear Itself)\nKill phoboplasms in the name of Cazic Thule 0/2 (Fear Itself)\nCollect skeletal remains 0/4 (Fear Itself)\n_This is a common drop off the above mobs._\nGive the remains to Alezra 0/1 (Fear Itself)\nSpeak to Alezra 0/1 (Fear Itself)\nYou say, 'Hail, Alezra D`Vour'\nAlezra D`Vour says 'Under the fearful gaze of Cazic Thule, I curse these remains so that those who gaze upon them will feel the terror and fear of a God. Let them serve as an offering, placed in Cazic's temple by an initiate of Thule, bathed in the blood of Fear.'\nBathe yourself in blood 0/1 (Fear Itself)\n_There is a room in the lower floors of the temple with a pool of blood (location is 795, 410, 75). Stand in the blood for a few moments for the update._\nPlace the remains in the temple as an offering 0/1 (Fear Itself)\nget on top of the table and CLICK the Bones\n_Go to the top floor of the temple and place the remains on the altar in the northeastern-most room of the floor._\nPresent yourself to Tiseth the Thrall 0/1 (Fear Itself)\n_Tiseth the Thrall is found at the very top of the temple (can only get to him from the outside, by using the ramp on the eastern side of the temple)._\nYou say, 'Hail, Tiseth the Thrall'\nTiseth the Thrall says 'Never before have I encountered an initiate who has shown such an affinity for fear. I believe with your pledge, we will be able to seek out Cazic Thule himself, and be welcomed into his fearful embrace!'\nYou completed the scared ritual by standing before Tiseth the Thrall, and were found to be worthy of Cazic's presence.\n_Rewards:_\n158 platinum\nExperience\nFaction with Dream Delvers\n15 Dream Motes\n_This leads into the group mission for Fear Itself, \"An Offering to Thule\"._\n- Dream Mote [item=90255]",
    },
    {
      id = "5251",
      title = "Reena \\#1: Foundation of Fear",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Reena Kedson",
      loc = { y = 665.0, x = 185.0, z = 0.0 },
      triggers = {
        "Hail, Reena Kedson",
        "Help?",
        "What about Tiseth?",
        "Sharuleth, then?",
        "Ready to fight!",
        "Hail, Sherri Ganes",
        "Hail, Jaris Calmur",
        "_Quests_",
      },
      items_required = {
        { name = "Jaris his spellbook 0/1 (Fear Itself)", count = 1 },
      },
      rewards = {
        { id = 93819, name = "Jaris' Spellbook", type = "item" },
        { id = 93817, name = "Sherri's Equipment", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Fear Itself [zone=756]\n**Who:**\n- Reena Kedson [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 90\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Quest Items:**\n- Jaris' Spellbook [item=93819]\n- Sherri's Equipment [item=93817]\n**Related Creatures:**\n- Jaris Calmur [npc=36672]\n- Sharuleth [npc=36682]\n- Sherri Ganes [npc=36673]\n**Related Quests:**\n- Reena #2: Terror Personified [quest=5252]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Dec 2 22:44:44 2010\nModified: Tue Dec 5 05:21:04 2023 | | _This is the first of two tasks that begin with Reena Kedson ( map) in Fear Itself. She's located on the hill outside the amygdalan temple (within the ring of fire) at 665, 185._\nYou say, 'Hail, Reena Kedson'\nReena Kedson says 'You there! You aren't a vile looking creature, or an insane iksar. You'll do. My friends and I need some [help] here.'\nYou say, 'Help?'\nReena Kedson says 'That's right. We have some serious problems. One of those amygdalans that serves Cazic Thule runs that temple with an iron fist. Its name is [Sharuleth]. After we deal with that creature, we still have to find a proper escape route. We'll need to deal with [Tiseth] when it comes to that.'\nYou say, 'What about Tiseth?'\nReena Kedson says 'Hm, well we can't deal with Tiseth yet. We'll need to deal with [Sharuleth] first.'\nYou say, 'Sharuleth, then?'\nReena Kedson says 'I've seen some horrible monsters in my days, but this thing is the true embodient of the word. If you'd like to help us rid this Plane of this creature, we'd appreciate it. What do you say? Are you ready to [fight]?'\nYou say, 'Ready to fight!'\nReena Kedson says 'Good. First, speak to my comrades already in the temple. Use the front entrance on the side there. They won't be too deep in.'\nYou have been assigned the task 'Foundation of Fear'.\nInfiltrate the temple of Cazic Thule and assist Reena's allies in clearing out the creatures and amygdalans who inhabit it by recovering their equipment.\n_NOTE: The following points for your \"thuledream.txt\" map file will be of use for these two tasks:_\nP -185.0000, -675.0000, 65.0000, 0, 0, 0, 2, Reena\\_Kedson\nP -440.0000, -900.0000, 115.0000, 0, 0, 0, 2, Jaris\\_and\\_Sherri\nP -410.0000, -860.0000, 115.0000, 0, 0, 0, 2, Equipment\nP -520.0000, -830.0000, 35.0000, 0, 0, 0, 2, Equipment\nP -355.0000, -690.0000, 50.0000, 0, 0, 0, 2, Equipment\nP -470.0000, -700.0000, 50.0000, 0, 0, 0, 2, Spellbook\nP -435.0000, -915.0000, 50.0000, 0, 0, 0, 2, Sharuleth\nP -400.0000, -905.0000, 50.0000, 0, 0, 0, 2, Shade\nP -425.0000, -810.0000, 215.0000, 0, 0, 0, 2, Tiseth\\_the\\_Thrall\n_In-game /locs:_\nReena:\n675, 185, 65 _(on hill outside temple)_\nJaris & Sherri:\n900, 440, 115 _(inside temple; second floor down from top)_\nEquipment Spawns:\n860, 410, 115\n830, 520, 35\n690, 355, 50\nBook Spawn:\n700, 470, 50 _(inside temple; a few floors down from top)_\nSharuleth & Shade:\n915, 435, 50 _(very bottom of the temple)_\nTiseth the Thrall:\n810, 425, 215 _(top of the temple)_\n\n---\n\nSpeak to Sherri Ganes inside the temple 0/1 (Fear Itself)\n_Sherri and Jaris are found on the second level from the top of the temple. They're in one of the first rooms._\nYou say, 'Hail, Sherri Ganes'\nSherri Ganes says 'I lost a lot of gear on our movement down deeper into this temple. We're a bit outmatched, and glad you're here to help. Can you get the lost equipment? We'll need it if we are going to leave the Plane of Fear. You should be able to find it scattered around, or some of the amygdalans might have picked some up.'\nSpeak to Jaris Calmur inside the temple 0/1 (Fear Itself)\nYou say, 'Hail, Jaris Calmur'\nJaris Calmur says 'I need you to find my spellbook. I lost it after we made it deeper into the temple, and now I can't seem to get back down. Nevermind dealing with these amygdalans. Can I count on your aid?'\nReturn Sherri's equipment 0/3 (Fear Itself)\nGive Jaris his spellbook 0/1 (Fear Itself)\nSpeak to Reena Kedson 0/1 (Fear Itself)\nYou say, 'Hail, Reena Kedson'\nReena Kedson says 'You're back. Thanks to your work, my friends are now back to full strength. There is an amygdalan shadowknight named Sharuleth who is guarding the secrets to the Plane of Fear. It is a well-favored creature of Cazic Thule's, and we must defeat it. Unfortunately, I don't think we're in any condition to do so. We'll hold the amygdalans back while you go in for the kill. We're counting on you.'\nDestroy Sharuleth deep inside the temple 0/1 (Fear Itself)\n_Sharuleth is found on the bottom floor of the temple in a room with a few other amygdalans. He hits for a max ~7,600._\nSharuleth has been slain by \\_\\_\\_\\_\\_!\nSharuleth's corpse gasps for air, choking out one final breath.\nReturn to Reena Kedson 0/1 (Fear Itself)\nYou say, 'Hail, Reena Kedson'\nReena Kedson says 'I can feel that his oppressive aura is gone already. I must admit, I could never keep up with you. I managed to get some information from a crazed Cazic Thule follower that has met with [Tiseth]. We'll have to deal with her next.'\nYou've defeated Sharuleth, an elite warrior of Cazic Thule and given Reena and her comrades an opportunity to find a way out of the Plane of Fear.\n_Rewards:_\n210 platinum (about 3 AAs)\nExperience\nFaction with Dream Delvers\n20 Dream Motes\n_The task \"Terror Personified\" follows this one._\n- Dream Mote [item=90255]",
    },
    {
      id = "5252",
      title = "Reena \\#2: Terror Personified",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Reena Kedson",
      loc = nil,
      triggers = {
        "So, about Tiseth...",
        "I",
        "Hail, Sherri Ganes",
        "Hail, Jaris Calmur",
        "Hail, Tiseth the Thrall",
        "Hail, Reena Kedson",
        "_Quests_",
        "Tiseth",
      },
      items_required = {
        { name = "her the shard", count = 1 },
      },
      rewards = {
        { id = 94299, name = "Shard of Thule's Nightmare", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Fear Itself [zone=756]\n**Who:**\n- Reena Kedson [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 90\n**Maximum Level:** | 95\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Quest Items:**\n- Shard of Thule's Nightmare [item=94299]\n**Related Creatures:**\n- Jaris Calmur [npc=36672]\n- Shade of Cazic Thule [npc=36683]\n- Sherri Ganes [npc=36673]\n- Tiseth the Thrall [npc=36667]\n- an amygdalan knight [npc=36617]\n- an amygdalan warrior [npc=36616]\n**Related Quests:**\n- Reena #1: Foundation of Fear [quest=5251]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Dec 2 22:45:25 2010\nModified: Thu Feb 16 09:36:48 2012 | | _This is the second of two tasks that begin with Reena Kedson in Fear Itself. She's located on the hill outside the amygdalan temple (within the ring of fire)._\n_You must have completed the task \"Foundation of Fear\" in order to request this one._\n_At the end of the previous task:_\nReena Kedson says 'I can feel that his oppressive aura is gone already. I must admit, I could never keep up with you. I managed to get some information from a crazed Cazic Thule follower that has met with [Tiseth]. We'll have to deal with her next.'\nYou say, 'So, about Tiseth...'\nReena Kedson says 'She's a crazed worshipper of Cazic Thule. She's too delusional to be dangerous, but she appears to have snatched up some [artifact] that has a resonance with this Plane. I'm not exactly sure I understsand how it works, but Jaris can explain it. He thinks we can escape if we get it. Can you help us get this [artifact]?'\nYou say, 'I'll get the artifact'\nReena Kedson says 'I'm glad to hear it. I'll need you to speak to Sherri and Jaris first. You'll find them inside the temple. Use the front entrance.'\nYou have been assigned the task 'Terror Personified'.\nGather the artifact requested to break the power of the amygdalans and allow Reena and the others trapped in this dream world to escape this nightmare.\n_NOTE: The following points for your \"thuledream.txt\" map file will be of use for these two tasks:_\nP -185.0000, -675.0000, 65.0000, 0, 0, 0, 2, Reena\\_Kedson\nP -440.0000, -900.0000, 115.0000, 0, 0, 0, 2, Jaris\\_and\\_Sherri\nP -410.0000, -860.0000, 115.0000, 0, 0, 0, 2, Equipment\nP -520.0000, -830.0000, 35.0000, 0, 0, 0, 2, Equipment\nP -355.0000, -690.0000, 50.0000, 0, 0, 0, 2, Equipment\nP -470.0000, -700.0000, 50.0000, 0, 0, 0, 2, Spellbook\nP -435.0000, -915.0000, 50.0000, 0, 0, 0, 2, Sharuleth\nP -400.0000, -905.0000, 50.0000, 0, 0, 0, 2, Shade\nP -425.0000, -810.0000, 215.0000, 0, 0, 0, 2, Tiseth\\_the\\_Thrall\n_In-game /locs:_\nReena:\n675, 185, 65 _(on hill outside temple)_\nJaris & Sherri:\n900, 440, 115 _(inside temple; second floor down from top)_\nEquipment Spawns:\n860, 410, 115\n830, 520, 35\n690, 355, 50\nBook Spawn:\n700, 470, 50 _(inside temple; a few floors down from top)_\nSharuleth & Shade:\n915, 435, 50 _(very bottom of the temple)_\nTiseth the Thrall:\n810, 425, 215 _(top of the temple)_\n\n---\n\nSpeak to Sherri Ganes inside the temple 0/1 (Fear Itself)\nYou say, 'Hail, Sherri Ganes'\nSherri Ganes says 'That lunatic iskar, Tiseth the Thrall, boasts that she can get out of here. She has some sort of artifact that is strengthening the Plane of Fear's denziens. I'd love to go have a word with her, but I'm afraid we'll need your help. It's all I can do to keep these amygdalans at bay.'\nSpeak to Jaris Calmur inside the temple 0/1 (Fear Itself)\nYou say, 'Hail, Jaris Calmur'\nJaris Calmur says 'There is a dark force deep inside this temple, and I'm afraid Tiseth's artifact is the key to defeating it for good. When I killed it, it just came back to life. You should be able to confront her to get the artifact. Once you do, you'll need to destroy the shade of Cazic Thule that resides here.'\nDefeat amygdalan warriors 0/3 (Fear Itself)\nDefeat amygdalan knights 0/3 (Fear Itself)\nInterrogate Tiseth the Thrall, take the Shard, and hold onto it 0/1 (Fear Itself)\n_Task Window Says:_ Interrogate Tiseth the Thrall and steal her artifact before she can do anymore damage.\n_Tiseth is found at the top of the temple._\nYou say, 'Hail, Tiseth the Thrall'\nTiseth the Thrall says 'Stay back! The Shard of Thule's Nightmare is mine! I refuse to let this paradise end! What are you doing? Unhand me! Give me that back! The master's shade cannot be destroyed so easily, even if you steal my shard!'\n_You receive a Shard of Thule's Nightmare on your cursor._\nDefeat the Shade of Cazic Thule 0/1 (Fear Itself)\n_Task Window Says:_ Steal the artifact. With the shard in your possession, you should be able to destroy the Shade of Cazic Thule inside the temple permanently.\n_The Shade of Cazic Thule spawns at the very bottom of the temple._\n_It's a Shadow Knight, hits for a max ~7,600, has a lot of hitpoints, and has a very fast respawn (within a minute or two)._\nShade of Cazic Thule has been slain by \\_\\_\\_\\_\\_!\nShade of Cazic Thule's corpse gasps for air, choking out one final breath.\nGive the Shard of Thule's Nightmare to Reena 0/1 (Fear Itself)\nSpeak with Reena 0/1 (Fear Itself)\n_Task Window Says:_ The shard you took from Tiseth has lost much of its luster. You should talk to Reena about it and give her the shard.\nYou say, 'Hail, Reena Kedson'\nReena Kedson says 'Excellent work! By destroying that echo of Cazic Thule, this shard you gave me has lost most of its power. I think we can destroy it completely. I don't know for certain if it will allow us to escape, but it should weaken the dark forces at work in this Plane. Which, I'm beginning to think, isn't the real Plane of Fear.'\nYou've destroyed the shard of Cazic Thule and have made this image of the Plane of Fear safer. Even if Reena and her friends cannot find a way out of this dream, their time trapped will be less dangerous.\n_Rewards:_\n210 platinum (about 3 AAs)\nExperience\nFaction with Dream Delvers\n20 Dream Motes\n- Dream Mote [item=90255]",
    },
    {
      id = "5253",
      title = "Corpse Camped",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Arki Battlehammer",
      loc = nil,
      triggers = {
        "Hail, Arki Battlehammer",
        "What threat?",
        "Empowers them?",
        "What about the Amygdalans?",
        "I",
        "_Quests_",
        "threat",
        "empowers them",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Fear Itself [zone=756]\n**Who:**\n- Arki Battlehammer [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 90\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Creatures:**\n- an amygdalan knight [npc=36617]\n- an amygdalan warrior [npc=36616]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sat Dec 4 00:14:27 2010\nModified: Sat Dec 4 00:19:29 2010 | | _This is a solo kill task that begins with Arki Battlehammer in Fear Itself. He is in an NPC camp right next to the zone-in area._\nYou say, 'Hail, Arki Battlehammer'\nArki Battlehammer says 'Oh, Brell protect us! It's a slaughter out there. The [threat] is so great. I've never seen it quite this bad in Fear.'\nYou say, 'What threat?'\nArki Battlehammer says 'They're putting up quite a fight today, and Cazic's bloodthirsty slaughter of mortals just [empowers them].'\nYou say, 'Empowers them?'\nArki Battlehammer says 'I mean pretty much anyone native to this plane. I suppose the biggest threat against my fellowship has been the [Amygdalans] and [fetid fiends].'\nYou say, 'What about the Amygdalans?'\nArki Battlehammer says 'The Amygdalans took down a few of our friends, and it took all the priests could muster to save the rest of us. If you wish to [take down] several of them, we may be able to go in and search for the bodies of our fallen groupmates.'\nYou say, 'I'll take down the Amygdalans'\nArki Battlehammer says 'Your assistance is greatly appreciated, \\_\\_\\_\\_\\_.'\nYou have been assigned the task 'Corpse Camped'.\nArki Battlehammer feels the Amygdalans have cut down many of their forces and requests your assistance in taking them down.\n\n---\n\nKill several amygdalan knights 0/4 (Fear Itself)\nKill several amygdalan warriors 0/4 (Fear Itself)\n_You'll find some amygdalans wandering about the ring of fire and around the small temples in the zone, but most are located in the large temple in the middle of the ring of fire._\nReport back to Arki 0/1 (Fear Itself)\nYou say, 'Hail, Arki Battlehammer'\nArki Battlehammer gives a nod of his head at your report, then bows his head for the loss of his comrades.\n_Rewards:_\nExperience (about 1 AA worth)\nMinor faction with Dream Delvers",
    },
    {
      id = "5255",
      title = "The Antidote Within",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Rashan Spiritweaver",
      loc = nil,
      triggers = {
        "Hail, Rashan Spiritweaver",
        "What kind of poison did this?",
        "Transforming?",
        "I will retrieve some",
        "_Quests_",
        "poison",
        "transforming",
        "retrieve some",
      },
      items_required = {
      },
      rewards = {
        { id = 93678, name = "Spinechiller Venom", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Fear Itself [zone=756]\n**Who:**\n- Rashan Spiritweaver [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 90\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +5\n**Factions Lowered:**\n**Quest Items:**\n- Spinechiller Venom [item=93678]\n**Related Creatures:**\n- a spinechiller spider [npc=36622]\n- a spinechiller widow [npc=36619]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sat Dec 4 00:14:35 2010\nModified: Sun Aug 8 14:41:48 2021 | | _This is a solo kill task that begins with Rashan Spiritweaver in Fear Itself. He is in an NPC camp right next to the zone-in area._\nYou say, 'Hail, Rashan Spiritweaver'\nRashan Spiritweaver seems to be lost in a chant as he leans over the faintly breathing woman before him. A seasoned adventurer would recognize his incantations as being an attempt to cleanse [poison].\nYou say, 'What kind of poison did this?'\nRashan Spiritweaver stops as he's awoken from his trance and looks up at \\_\\_\\_\\_\\_. 'Spider venom, specifically. She took ill from the venom of the spinechillers. It keeps [transforming] and moving.' He lowers his head.\nYou say, 'Transforming?'\nRashan Spiritweaver closes his eyes from the pain, but a tear soaks the fur beneath them. 'On entry into her system, the venom keeps morphing, making it difficult to treat. Just as I think I have saved her, it appears it has merely changed constitution.' He looks back up at \\_\\_\\_\\_\\_ and inquires, 'The only hope for her are pure samples of the venom that has infected her, those that have not yet been injected in flesh. I could study it and try to find a way to stop the transformations or anticipate the next forms. It's a lot to ask with how dire the situation is here, but would you [retrieve some] to save her?'\nYou say, 'I will retrieve some'\nRashan Spiritweaver places a hand on your arm and nods. 'Thank you... May your ancestors guide you, friend. Return safe.'\nYou have been assigned the task 'The Antidote Within'.\nA transforming poison was found to be slowly tearing apart Iyana T`vre and Rashan Spiritweaver has been doing all he can to help her as she suffers. However, what he cannot do while he tends to her is obtain some samples of pre-injection venom from the spinechiller spiders to examine them more completely. He has asked for you to do so in his place.\n\n---\n\nKill several spinechiller spiders and widows and search their corpses 0/4 (Fear Itself)\nLoot a few spinechiller venom samples 0/4 (Fear Itself)\n_Spinechiller spiders roam most parts of the zone, but seem to be most common in the southern half. Their venom is a common drop._\n_Note: These are not pre-lootable._\nReturn the samples to Rashan 0/1 (Fear Itself)\nRashan Spiritweaver says, 'You couldn't have come a moment too soon. Every moment without the antidote, is a moment closer to her death. I'll get started looking at these samples immediately. Thank you.'\n\n---\n\n_Rewards:_\nExperience (about 1 AA worth)\nMinor faction with Dream Delvers",
    },
    {
      id = "5257",
      title = "Frozen in Fear",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Hildran Heartguard",
      loc = nil,
      triggers = {
        "Hail, Hildran Heartguard",
        "Why are you scared?",
        "Phobias?",
        "I",
        "_Quests_",
        "scared",
        "undead",
        "phobias",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Fear Itself [zone=756]\n**Who:**\n- Hildran Heartguard [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 90\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Creatures:**\n- a frightfinger [npc=36627]\n- a scareling [npc=36681]\n- an enraged frightfinger [npc=36650]\n- an enraged scareling [npc=36649]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sun Dec 5 00:01:17 2010\nModified: Sun Dec 5 00:07:11 2010 | | _This is a solo kill task that begins with Hildran Heartguard in Fear Itself. He is found in an NPC camp on the eastern zone boundary in the northeast part of the zone._\nYou say, 'Hail, Hildran Heartguard'\nHildran Heartguard says 'For once, I'm truly [scared], \\_\\_\\_\\_\\_. What is going on here?'\nYou say, 'Why are you scared?'\nHildran Heartguard says 'The place of Fear is terrorizing today. We've been here before, fought many times against the beings here, but I'm not quite sure how we're in the position we are today. We've lost many friends on the battlefield, including our cleric, and it may be looking like a complete loss. The [undead] have been insistant on taking our camp, leaving us trying to fend them off when we can. Of course, there is also my personal [phobias] begining to play out here, causing an unwary grip on my sword. I had to switch to my two-hander for the sake of stability.'\nYou say, 'Phobias?'\nHildran Heartguard says 'I'm not normally easily frightened, even in the grips of Fear, but this appears to be over the top. The monstrocities are causing me to not be able to function as easily as the warrior of our band. If you could [take care of them], I might have a fighting chance.'\nYou say, 'I'll take care of them'\nHildran Heartguard says 'You're a life saver. Literally. Be safe out there. I'll be waiting.'\nYou have been assigned the task 'Frozen in Fear'.\nHildran Heartguard isn't afraid of much, but it appears Fear Itself has reared its ugly head. He's asked for you to take care of what frightens him, so that he can be a better functioning warrior for his camp.\n\n---\n\nKill several frightfingers 0/4 (Fear Itself)\nKill a few scarelings 0/3 (Fear Itself)\nHail Hildran Heartguard and tell him it's fine 0/1 (Fear Itself)\nYou say, 'Hail, Hildran Heartguard'\nA little more sure of himself, Hildran Heartguard hoists his sword into the air, letting out a triumphant bellow. He gives his thanks, then prepares for the next battle.\n_Rewards:_\nExperience (about 1 AA worth)\nMinor faction with Dream Delvers",
    },
    {
      id = "5259",
      title = "In Fear of Death",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Morae Windwatcher",
      loc = nil,
      triggers = {
        "Hail, Morae Windwatcher",
        "What",
        "What about the undead?",
        "I",
        "_Quests_",
        "the area",
        "undead",
        "group of creatures",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Fear Itself [zone=756]\n**Who:**\n- Morae Windwatcher [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 90\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Creatures:**\n- a boogeyman [npc=36642]\n- a boogeyman lurker [npc=36656]\n- a delirious boogeyman [npc=36657]\n- a delirious samhain [npc=36624]\n- a phantasm [npc=36625]\n- a samhain [npc=36635]\n- a shadowed phantasm [npc=36632]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sun Dec 5 00:01:24 2010\nModified: Sun Dec 5 00:12:52 2010 | | _This is a solo kill task that begins with Morae Windwatcher in Fear Itself. She is found in an NPC camp on the eastern zone boundary in the northeast part of the zone._\nYou say, 'Hail, Morae Windwatcher'\nMorae Windwatcher says 'I'm sorry. You've probably lost friends here in the Plane of Fear, as well. Do you come from another camp? No matter; you are welcome here. I've been observing [the area], to try to determine a way out, or to re-establish communication with anyone else.'\nYou say, 'What's going on in the area?'\nMorae Windwatcher says 'I fear problems with the [undead] that are encroaching on our camp. There is also a [group of creatures] that have blocked us from progressing here. Your assistance would be so great.'\nYou say, 'What about the undead?'\nMorae Windwatcher says 'They're unsettling, seemingly infused with a larger power than normal. I'm afraid they will overtake our camp any moment now, with no way to escape or alert others. Please assist us, please [slay them].'\nYou say, 'I'll slay them'\nMorae Windwatcher says 'I really appreciate your help. Tunare bless you.'\nYou have been assigned the task 'In Fear of Death'.\nUndead have been terrorizing Morae Windwatcher's fellowship, and she's asked that you slay them for the sake of her group.\n\n---\n\nTake down a number of boogeymen 0/4 (Fear Itself)\nTake down a number of samhain 0/4 (Fear Itself)\nTake down a number of phantasms 0/4 (Fear Itself)\nReturn to Morae to tell her of your deeds 0/1 (Fear Itself)\nYou say, 'Hail, Morae Windwatcher'\nMorae Windwatcher gives a faint but thankful smile at your report. 'You've been such a great help. Bless you.'\n_Rewards:_\nExperience (about 1 AA worth)\nMinor faction with Dream Delvers",
    },
  },
}
