-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for The Library (thulelibrary)
-- Total Quests: 9
-- ============================================================================

return {
  zone = "thulelibrary",
  zone_name = "The Library",
  quests = {
    {
      id = "5144",
      title = "Kintorom \\#3: Book of Secrets",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Scholar Kintorom",
      loc = nil,
      triggers = {
        "Hail Scholar Kintorom",
        "Norrath",
        "I",
        "Hail, Assistant Librarian Vesrad",
        "Hail, Scholar Kintorom",
        "_Quests_",
        "origins",
        "dream",
      },
      items_required = {
      },
      rewards = {
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Library [zone=751]\n**Who:**\n- Scholar Kintorom [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 87\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Quest Items:**\n- Vol. 1 [item=92588]\n**Related Creatures:**\n- Assistant Librarian Vesrad [npc=36180]\n- a library watcher [npc=36176]\n**Related Quests:**\n- Kintorom #1: Interview with a Scholar [quest=5124]\n- Kintorom #2: History of the World, Part 2 [quest=5143]\n- The Stuff of Dreams [quest=5145]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Fri Oct 22 23:49:40 2010\nModified: Tue Jan 28 04:43:04 2025 | | _This is a group task (3-6 players). It is the third task (the first two being solo) in a series of three and begins with Scholar Kintorom at the zone-in of The Library._\n_You must have completed his prior two tasks before being able to request this one._\n_Note: Your group's average level may need to be higher than 87. If that's the case, please let us know._\nYou say, 'Hail Scholar Kintorom'\nScholar Kintorom says 'These books you brought seem to chronicle the entire history of Norrath through the ages! Given that these volumes are numbered, there must be a first volume. If I am correct, this book would have the answers to the [origins] of Norrath and the Gods!'\nYou say, 'Norrath's origins?'\nScholar Kintorom says 'Can you imagine it? My life's work will finally be complete once I get that book. We must find out where it is. Will you help me fulfill my [dream]?'\nYou say, 'I'll help you fulfill the dream...'\nScholar Kintorom says 'I knew I could count on you! Perhaps Assistant Librarian Vesrad can help.'\nYou have been assigned the task 'Book of Secrets'.\nNow that Scholar Kintorom has proven this to be a set of books, he wants to get his hands on 'Volume 1'. He believes this book will contain the answers he is looking for.\n\n---\n\nInquire with Assistant Librarian Vesrad regarding Volume 1 0/1 (The Library)\n_The Assistant is found towards the top of the library (he's the drakkin in a red robe below the spiral staircase)._\nBring Volume 1 to Scholar Kintorom 0/1 (The Library)\nQuestion Assistant Librarian Vesrad about the authenticity of Volume 1 0/1 (The Library)\n_On hailing the Assistant, 2x \"a library watcher\" spawn and attack._\nDestroy the library watchers 0/2 (The Library)\n_They hit for a max ~6,500._\n_NOTE: The task locks after you kill the second watcher._\nDemand an explanation from Assistant Librarian Vesrad 0/1 (The Library)\nYou say, 'Hail, Assistant Librarian Vesrad'\nAssistant Librarian Vesrad says 'The Encyclopedia Norrathica is forbidden to mortals! You cannot be allowed to read it!'\nKill Assistant Librarian Vesrad 0/1 (The Library)\n_He hits for a max ~7,000._\nTell Scholar Kintorom about the Encyclopedia Norrathica 0/1 (The Library)\nYou say, 'Hail, Scholar Kintorom'\nScholar Kintorom says 'The Encyclopedia Norrathica? So that's what we've been searching for. We must confront the head librarian!'\nYou learned of the existence of the Encyclopedia Norrathica. This book has the knowledge Scholar Kintorom seeks.\nYour faction standing with Dream Delvers got better.\n_Rewards:_\n158 platinum\nExperience\nFaction with Dream Delvers\n10 Dream Motes\n\n---\n\n_Completion of this task series leads into the group mission from Scholar Kintorom, \"The Stuff of Dreams\"._\n- Dream Mote [item=90255]",
    },
    {
      id = "5145",
      title = "The Stuff of Dreams",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Scholar Kintorom",
      loc = nil,
      triggers = {
        "Hail, Scholar Kintorom",
        "Confront?",
        "_Quests_",
        "confront",
        "interview",
        "locate",
        "dream",
        "proceed",
      },
      items_required = {
      },
      rewards = {
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Library [zone=751]\n**Who:**\n- Scholar Kintorom [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 85\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Faction\n- Loot\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 06:00:00\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Zones:**\n- The Library: The Stuff of Dreams [zone=762]\n**Related Creatures:**\n- Archivist Herrdar [npc=36203]\n- Ardull the Watcher [npc=36199]\n- Compendium of Nightmares [npc=36201]\n- Curator Majda [npc=36194]\n- Head Librarian Matilda [npc=36204]\n- The Encyclopedia Norrathica [npc=36206]\n- Tome of the Fallen [npc=36197]\n- a dutiful librarian [npc=36205]\n- a fallen warrior [npc=36196]\n- a furious sweeper [npc=36195]\n- a musty tome [npc=36202]\n- a nightmare [npc=36200]\n- an armored watcher [npc=36198]\n- an ornate chest - The Stuff of Dreams [npc=36207]\n**Related Quests:**\n- Fall of the Tae Ew [quest=5136]\n- Kintorom #1: Interview with a Scholar [quest=5124]\n- Kintorom #2: History of the World, Part 2 [quest=5143]\n- Kintorom #3: Book of Secrets [quest=5144]\n- Welcome to My Nightmare [quest=5142]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Sat Oct 23 04:11:42 2010\nModified: Tue Dec 5 05:21:04 2023 | | _This group task (3-6 players) begins with Scholar Kintorom at the zone-in of The Library._\n_You must have completed the Feerrott and House of Thule group progression missions (\"Fall of the Tae Ew\" and \"Welcome to My Nightmare\"), his two solo tasks, and his shared task before being able to request this one._\nYou say, 'Hail, Scholar Kintorom'\nScholar Kintorom says 'Now that we know the answers are in the Encyclopedia Norrathica, we must travel to the top of the library to [confront] the Head Librarian on its whereabouts. Otherwise you could [interview] scholars about my research, [locate] more books, or help me fulfill my [dream].'\nYou say, 'Confront?'\nScholar Kintorom says 'I have no doubt they will try to stop us but I'm no good in a fight. I'll need you and your friends to clear the way to the head librarian. Be prepared for anything. Shall we [proceed]?\nYou have been assigned the task 'The Stuff of Dreams'.\nScholar Kintorom has discovered the existence of the Encyclopedia Norrathica, a book which contains all the information regarding the creation of Norrath and the Gods. He wants to confront the head librarian and claim the book for himself, so he can fulfill his dreams, but needs your help to clear the way to the top of the library.\n_Say \"proceed\" to zone in._\n\n---\n\n**General Information**\n_In this instance, you can expect trash mob types to hit for a max ~6,200. Nameds hit for a little more (but no flurry, no rampage, and no enrage). They may not even summon (this is not confirmed). Some nameds have an AE associated with them (if so, they are listed below)._\n_Trash mobs are rootable/snareable, stunnable, and mezzable (even with 81-85 Enchanter mezzes)._\n_The \"Make your way...\" steps (which are update locations found gradually further into the library) open up one at a time as you kill the mobs associated with them._\n_After triggering one of these steps, the trash mobs begin spawning one at a time. The named is permanently rooted, so its attacks are avoidable until you want to engage it. (There is an achievement for killing the named before the trash.)_\n_NOTE: Make sure to engage the named within a minute of killing the last add spawn. If you let too much time pass without doing so, another wave of adds spawns._\n\n---\n\nMake your way toward the top of the library 0/1 (The Library)\n_You'll see an erudite named Curator Majda. As you approach her, this step updates and the first trash mob spawns. (The rest of the task plays out the same way.)_\nKill 3 a furious sweeper 0/3 (The Library)\nKill 1 Curator Majda 0/1 (The Library)\n_These mobs appear to be pure melee._\nCurator Majda says 'Sweeper, get them!'\nCurator Majda has been slain by \\_\\_\\_\\_\\_!\nCurator Majda's corpse gasps for air, choking out one final breath.\n\n---\n\nMake your way toward the top of the library 0/1 (The Library)\nKill 3 a fallen warrior 0/3 (The Library)\n_Fallen warriors have spell procs:_\nTouch of Flame: Single Target, Fire (-700)\n1: Decrease Hitpoints by 300\nTouch of Frost: Single Target, Cold (-700)\n1: Decrease Hitpoints by 300\nTouch of Rot: Single Target, Disease (-700)\n1: Decrease Hitpoints by 300\nKill 1 Tome of the Fallen 0/1 (The Library)\n_Tome of the Fallen summons and casts:_\nBreath of the Fallen: Single Target, (-100)\n1: Decrease Hitpoints by 8000 per tick\n2: Set Healing Effectiveness to -20%\n3: Increase corruption counter by 50\nTome of the Fallen surges with increased velocity, preparing for a fight!\nTome of the Fallen has been slain by \\_\\_\\_\\_\\_!\nTome of the Fallen's corpse falls into a heap of dust and torn pages.\n\n---\n\nMake your way toward the top of the library 0/1 (The Library)\nKill 3 an armored watcher 0/3 (The Library)\nKill 1 Ardull the Watcher 0/1 (The Library)\nArdull the Watcher says 'Watcher, I call you to defend the library!'\nArdull the Watcher raises its weapons and rushes into battle!\n_Watchers appear to be pure melee, while Ardull the Watcher casts \"Focused Rage:\"_\nFocused Rage PB AE 40', Corruption (-700)\n1: Decrease Hitpoints by 22000\n2: SpinStun\n3: Add Effect: Focused Rage\nArdull the Watcher has been slain by \\_\\_\\_\\_\\_!\nArdull the Watcher's corpse crashes to the ground with unnatural force, shaking the surrounding library walls.\n\n---\n\nMake your way toward the top of the library 0/1 (The Library)\nKill 3 a nightmare 0/3 (The Library)\n_Note: The nightmares proc on their targets \"Shadow Touch\":_\nShadow Touch: Single Target, Magic (-700)\n1: Decrease Hitpoints by 1500 per tick _(3 ticks)_\nKill 1 Compendium of Nightmares 0/1 (The Library)\nCompendium of Nightmares summons forth a nightmare from its pages.\n_It casts \"Waking Nightmares\":_\nWaking Nightmares: Single Target, Magic (0)\n1: Increase Spell Haste by 10%\n2: Inhibit Melee Attacks by (15%)\n3: Ultravision\nCompendium of Nightmares has been slain by \\_\\_\\_\\_\\_!\nCompendium of Nightmares's corpse falls into a heap of dust and torn pages.\n\n---\n\nMake your way toward the top of the library 0/1 (The Library)\nKill 15 a musty tome 0/15 (The Library)\n_Note: The musty tomes come in waves of 3-5 at a time. They hit for a max ~1,300 each and are crowd-controllable._\nKill 1 Archivist Herrdar 0/1 (The Library)\n_He's found up the stairs on the next level. He casts \"Dust of the Ages:\"_\nDust of the Ages: Targeted AE 50', Chromatic (-650)\n1: Decrease Hitpoints by 8000 per tick\n2: Unknown #408 (100/80/0)\nArchivist Herrdar has been slain by \\_\\_\\_\\_\\_!\nArchivist Herrdar's corpse cries out in pain, before falling eternally still.\n\n---\n\nMake your way toward the top of the library 0/1 (The Library)\n_The Head Librarian attacks once you trigger this update._\nKill 1 Head Librarian Matilda 0/1 (The Library)\nHead Librarian Matilda raises her voice in warning, 'Those who make noise will be silenced by my hand!'\n_Matilda hits for a max ~7,000 and AEs \"Forceful Knowledge\":_\nForceful Knowledge: PB AE 50', Magic (-700)\n1: Decrease Hitpoints by 22000\n2: Decrease Mana by 3000\n3: Decrease Endurance by 2700\n_She also spawns time-based adds one at a time. They're called \"a dutiful librarian\" and will keep spawning until six of them are up. If you kill one, another will take its place. You'll want to kill the Head Librarian while offtanking or mezzing or rooting the adds._\nHead Librarian Matilda has been slain by \\_\\_\\_\\_\\_!\nHead Librarian Matilda falls over in defeat.\n\n---\n\nAllow Scholar Kintorom to claim the Encyclopedia Norrathica 0/1 (The Library)\n_After the Head Librarian and her adds are dead, approach the Encyclopedia Norrathica. Scholar Kintorom appears and has this exchange..._\nScholar Kintorom says 'Finally I've found it! All the answers I seek will surely be in the Encyclopedia Norrathica. You are mine now! Wait, what's happening? This isn't right! I was so close to fulfilling my dreams! Noooooo.....'\n_The Head Librarian then respawns (non-KOS):_\nHead Librarian Matilda says 'Because the knowledge contained in this book is forbidden, Kintorom was banished from this place. He will never be permitted to return. Some things are better left in your dreams, adventurers. Take these things and ruminate on what you have witnessed this day. Inform me when you are ready to [leave].'\nYou helped Scholar Kintorom reach the Encyclopedia Norrathica, though things didn't turn out as expected.\nClaim your reward from the ornate chest 0/1 (The Library)\n\n---\n\n_Task rewards:_\nExperience (about 3% regular exp at Level 86)\n315 platinum\n20 Dream Motes\nFaction with Dream Delvers\n_Known chest rewards (1 item + 1 spell per task):_\nBattlemage's Aegis\nGlumb's Trinket of Tactical Cowardice\nGolden Triumphal Cindercape\nHandful of the Patch Guardian's Straw\nPhantasmic Morningstar\nSap of Rejuvenation\nSlime Coated Pebble of the Deep\nThulian Linked Wristguard\nTreantwood Longbow\nWaspwing Cleaver\nMinor Nebulous Dream Fragment\nLesser Nebulous Dream Fragment\nMedian Nebulous Dream Fragment\nGreater Nebulous Dream Fragment\nGlowing Nebulous Dream Fragment\n- Dream Mote [item=90255]",
    },
    {
      id = "5182",
      title = "Book Hunt",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Curator Risald",
      loc = nil,
      triggers = {
        "Hail, Curator Risald",
        "What problem?",
        "I",
        "problem",
        "search",
      },
      items_required = {
      },
      rewards = {
        { id = 92553, name = "Denizens of the Planes", type = "item" },
        { id = 91234, name = "Everything You Wanted to Know About Breeding Worgs", type = "item" },
        { id = 92393, name = "Expositions on Theology", type = "item" },
        { id = 92798, name = "Fallen Gods", type = "item" },
        { id = 92046, name = "Genealogy of Kunark Wildlife", type = "item" },
        { id = 92492, name = "Niami's Tips for Delicious Baking", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Library [zone=751]\n**Who:**\n- Curator Risald [npc=35800]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Quest Items:**\n- Denizens of the Planes [item=92553]\n- Everything You Wanted to Know About Breeding Worgs [item=91234]\n- Expositions on Theology [item=92393]\n- Fallen Gods [item=92798]\n- Frostbitten: My Expeditions to Velious [item=91274]\n- Genealogy of Kunark Wildlife [item=92046]\n- Niami's Tips for Delicious Baking [item=92492]\n- Smooth Sailing: A Beginner's Guide to Sea Travel [item=92045]\n- The Norrathian Underground [item=92357]\n- Zombies and You [item=92552]\n**Related Zones:**\n- House of Thule, Lower Floors [zone=748]\n- The Grounds [zone=749]\n- The Well [zone=750]\n**Related Creatures:**\n- Athmos the Bard [npc=36102]\n**Related Quests:**\n- You Spoony Bard! [quest=5183]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 3 02:52:17 2010\nModified: Sat Mar 16 09:10:02 2024 | | _This solo task begins with Curator Risald in the Library. He's located in the room next to the zone-in._\nYou say, 'Hail, Curator Risald'\nCurator Risald says 'You do not appear to be a dreamer. You should not be in this place. However, since you are here, perhaps I can make use of you. I have a [problem] that must be addressed.'\nYou say, 'What problem?'\nCurator Risald says 'An inventory was recently conducted and we found several books have been removed from the library. Obviously we need these books to be returned and that's where you come in. Would you be willing to [search] the house and surrounding grounds for the missing books?'\nYou say, 'I'll search for them'\nCurator Risald says 'How fortunate. Some of these have been missing for quite some time, while others have vanished only recently. One such book, Fallen Gods, was most recently seen in the hands of Athmos the Poet. I look forward to the return of the missing volumes.'\nYou have been assigned the task 'Book Hunt'.\nCurator Risald has asked you to locate several books that have gone missing from the library. He has advised you to search the first floor of the house and the surrounding grounds.\nCurator Risald mentioned that Fallen Gods was last seen in the hands of Athmos the Bard.\n\n---\n\nRecover the book 'Expositions on Theology' 0/1 (House of Thule)\nRecover the book 'The Norrathian Underground' 0/1 (House of Thule)\nRecover the book 'Smooth Sailing: A Beginner's Guide to Sea Travel' 0/1 (House of Thule)\nRecover the book 'Geneaology of Kunark Wildlife' 0/1 (House of Thule)\nRecover the book 'Frostbitten: My Expeditions to Velious' 0/1 (The Well)\nRecover the book 'Zombies and You' 0/1 (The Grounds)\nRecover the book 'Denizens of the Planes' 0/1 (The Grounds)\nRecover the book 'Everything You Wanted to Know About Breeding Worgs' 0/1 (The Grounds)\nRecover the book 'Niami's Tips for Delicious Baking' 0/1 (The Grounds)\nRecover the book 'Fallen Gods' 0/1 (The Grounds)\nInform Curator Risald that you have found the missing books 0/1 (The Library)\nYou say, 'Hail, Curator Risald'\nIn yellow:\nYou were able to recover all the missing books from the Library and return them to Curator Risald.\nIn normal coloring:\nCurator Risald says 'Ah, very good. We appreciate the return of these books.'\n\n---\n\n_Book Locations (in-game /loc):_\nIn the House of Thule:\nExpositions of Theology (15, 255, 5 -- northwestern part of the garden area)\nThe Norrathian Underground (265, -225, 15 -- in the room next to the beastlings of rot)\nSmooth Sailing: A Beginner's Guide to Sea Travel (650, -130, 15 -- in the area where the Grounds entrance is located)\nGeneaology of Kunark Wildlife (350, -450, -45 -- in the room with the beastlings of the unknown)\nIn the Well:\nFrostbitten: My Expeditions to Velious (-325, -155, 30 -- entrance area of the cavern with the Fallen Soul)\nIn the Grounds:\nZombies and You (+198,+82 on a bench, just north of entrance from the House of Thule)\nDenizens of the Planes (-690, -1500, -175 -- north of the Well)\nEverything You Wanted to Know About Breeding Worgs (380, -2560, -220 -- in the building in the northeast)\nNiami's Tips for Delicious Baking (+615.87,-1250 on top of the pedastal where a statue is standing, west of the hedge maze)\nFallen Gods (in the possession of Athmos the Bard: see the task \"You Spoony Bard!\")\n_Book locations (copy & paste to .txt files for in-game maps):_\nthulehouse.txt:\nP -255.0000, -15.0000, 5.0000, 0, 0, 0, 2, Theology\nP 225.0000, -265.0000, 15.0000, 0, 0, 0, 2, Underground\nP 130.0000, -650.0000, 15.0000, 0, 0, 0, 2, Sailing\nP 450.0000, -350.0000, -45.0000, 0, 0, 0, 2, Wildlife\nwell.txt:\nP 155.0000, 325.0000, 30.0000, 0, 0, 0, 2, Frostbitten\nhousegarden.txt:\nP -80.0000, -200.0000, -35.0000, 0, 0, 0, 2, Zombies\nP 1500.0000, 690.0000, -175.0000, 0, 0, 0, 2, Denizens\nP 2560.0000, -380.0000, -220.0000, 0, 0, 0, 2, Worgs\nP 1250.0000, -600.0000, -180.0000, 0, 0, 0, 2, Baking\n\n---\n\n_Rewards:_\n315 platinum\nExperience\nFaction with Dream Delvers\n20 Dream Motes\n- Dream Mote [item=90255]",
    },
    {
      id = "5184",
      title = "Undesirable Dreams",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Varesa K`Zen",
      loc = { y = 150.0, x = 245.0, z = -3.0 },
      triggers = {
        "Hail, Varesa K`Zen",
        "Nightmare?",
        "How can I help",
        "nightmare",
        "help",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Library [zone=751]\n**Who:**\n- Varesa K`Zen [npc=36181]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Creatures:**\n- a disoriented dreamer [npc=36172]\n- a wayward visitor [npc=36169]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 3 03:20:45 2010\nModified: Mon Jan 31 17:34:56 2011 | | _This is a solo kill task that begins with Varesa K`Zen. She is found in the Library at location 150, 245, -3 (in the hallway north of the room with the various scholars)._\nYou say, 'Hail, Varesa K`Zen'\nVaresa K`Zen says 'I can feel my power slipping away. Why can't I remember all my spells? This is my worst [nightmare] come to life.'\nYou say, 'Nightmare?'\nVaresa K`Zen says 'Do you even know who you are talking to? I'm Varesa K'Zen. I am quite a skilled necromancer. Or was. I can't remember certain things after coming near this bloody place. But I have a feeling I could remember, if only I had proper access to this library. Normally this wouldn't be an issue, but in my weakened state, I need [help]. As much as it pains me to ask.'\nYou say, 'How can I help'\nVaresa K`Zen says 'Have you not looked around? Those armed and armored thugs patrolling around like this is a barracks. The custodians who attack anyone who passes by. The strange librarians who won't let me near the books! And even some of the books themselves are hostile. And then those researchers who are hoarding books. They are the worst! If not for them, I'd have my magic back. I'm sure of it. So, are you interested in assisting me? I will make sure you are rewarded, of course.'\n_A task window pops up with five options to choose from._\nYou have been assigned the task 'Undesirable Dreams'.\nVaresa K`Zen, a once-skilled necromancer, is losing her abilities and possibly her mind. The hostile dreamers would normally not be a problem for her, but she now requires your assistance to defeat them.\n\n---\n\nSubdue disoriented dreamers 0/4 (The Library)\nSubdue wayward visitors 0/4 (The Library)\nSpeak to Varesa K`Zen 0/1 (The Library)\nYou say, 'Hail, Varesa K`Zen'\nYou've assisted Varesa K'Zen in dealing with the dangerous dreamers.\n_Rewards:_\nExperience\nMinor Faction with Dream Delvers",
    },
    {
      id = "5185",
      title = "Research Assistant",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Varesa K`Zen",
      loc = { y = 150.0, x = 245.0, z = -3.0 },
      triggers = {
        "Hail, Varesa K`Zen",
        "Nightmare?",
        "How can I help",
        "nightmare",
        "help",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Library [zone=751]\n**Who:**\n- Varesa K`Zen [npc=36181]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Creatures:**\n- a library custodian [npc=36183]\n- an armored watcher [npc=36185]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 3 03:20:50 2010\nModified: Tue Feb 1 18:31:55 2011 | | _This is a solo kill task that begins with Varesa K`Zen. She is found in the Library at location 150, 245, -3 (in the hallway north of the room with the various scholars)._\nYou say, 'Hail, Varesa K`Zen'\nVaresa K`Zen says 'I can feel my power slipping away. Why can't I remember all my spells? This is my worst [nightmare] come to life.'\nYou say, 'Nightmare?'\nVaresa K`Zen says 'Do you even know who you are talking to? I'm Varesa K'Zen. I am quite a skilled necromancer. Or was. I can't remember certain things after coming near this bloody place. But I have a feeling I could remember, if only I had proper access to this library. Normally this wouldn't be an issue, but in my weakened state, I need [help]. As much as it pains me to ask.'\nYou say, 'How can I help'\nVaresa K`Zen says 'Have you not looked around? Those armed and armored thugs patrolling around like this is a barracks. The custodians who attack anyone who passes by. The strange librarians who won't let me near the books! And even some of the books themselves are hostile. And then those researchers who are hoarding books. They are the worst! If not for them, I'd have my magic back. I'm sure of it. So, are you interested in assisting me? I will make sure you are rewarded, of course.'\n_A task window pops up with five options to choose from._\nYou have been assigned the task 'Research Assistant'.\nThe now-helpless necromancer Varesa K`Zen cannot get past the library custodians and armored watchers to do spell research. She has asked you to put a stop to their aggression.\n\n---\n\nDefeat the library custodians 0/4 (The Library)\nDefeat the armored watchers 0/3 (The Library)\nSpeak to Varesa K`Zen 0/1 (The Library)\nYou say, 'Hail, Varesa K`Zen'\nYou've put down the library custodians and armored watchers for Varesa K'Zen, allowing her and others further access to the library.\n_Rewards:_\nExperience\nMinor Faction with Dream Delvers",
    },
    {
      id = "5186",
      title = "Independent Research",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Varesa K`Zen",
      loc = { y = 150.0, x = 245.0, z = -3.0 },
      triggers = {
        "Hail, Varesa K`Zen",
        "Nightmare?",
        "How can I help",
        "nightmare",
        "help",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Library [zone=751]\n**Who:**\n- Varesa K`Zen [npc=36181]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Creatures:**\n- a corporeal scholar [npc=36189]\n- an arcane researcher - The Library [npc=36175]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 3 03:20:53 2010\nModified: Wed Nov 3 03:23:32 2010 | | _This is a solo kill task that begins with Varesa K`Zen. She is found in the Library at location 150, 245, -3 (in the hallway north of the room with the various scholars)._\nYou say, 'Hail, Varesa K`Zen'\nVaresa K`Zen says 'I can feel my power slipping away. Why can't I remember all my spells? This is my worst [nightmare] come to life.'\nYou say, 'Nightmare?'\nVaresa K`Zen says 'Do you even know who you are talking to? I'm Varesa K'Zen. I am quite a skilled necromancer. Or was. I can't remember certain things after coming near this bloody place. But I have a feeling I could remember, if only I had proper access to this library. Normally this wouldn't be an issue, but in my weakened state, I need [help]. As much as it pains me to ask.'\nYou say, 'How can I help'\nVaresa K`Zen says 'Have you not looked around? Those armed and armored thugs patrolling around like this is a barracks. The custodians who attack anyone who passes by. The strange librarians who won't let me near the books! And even some of the books themselves are hostile. And then those researchers who are hoarding books. They are the worst! If not for them, I'd have my magic back. I'm sure of it. So, are you interested in assisting me? I will make sure you are rewarded, of course.'\n_A task window pops up with five options to choose from._\nYou have been assigned the task 'Independent Research'.\nThe dream-bound arcane researchers and corporeal scholars are taking all the useful tomes, and harming anyone who dares to interrupt them. Varesa K`Zen has asked you to put a stop to them so that she can access the library.\n\n---\n\nPunish the arcane researchers 0/5 (The Library)\nPunish the corporeal scholars 0/4 (The Library)\n_The above two mob types are found more commonly in the upper floors of the library._\nSpeak to Varesa K`Zen 0/1 (The Library)\n( **Closing dialogue?**)\n_Rewards:_\nExperience\nMinor Faction with Dream Delvers",
    },
    {
      id = "5187",
      title = "Deadly Knowledge",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Varesa K`Zen",
      loc = { y = 150.0, x = 245.0, z = -3.0 },
      triggers = {
        "Hail, Varesa K`Zen",
        "Nightmare?",
        "How can I help",
        "nightmare",
        "help",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Library [zone=751]\n**Who:**\n- Varesa K`Zen [npc=36181]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +5\n**Factions Lowered:**\n**Related Creatures:**\n- a neglected tome [npc=36170]\n- an ancient codex [npc=36171]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 3 03:20:56 2010\nModified: Fri Apr 17 00:00:09 2020 | | _This is a solo kill task that begins with Varesa K`Zen. She is found in the Library at location 150, 245, -3 (in the hallway north of the room with the various scholars)._\nYou say, 'Hail, Varesa K`Zen'\nVaresa K`Zen says 'I can feel my power slipping away. Why can't I remember all my spells? This is my worst [nightmare] come to life.'\nYou say, 'Nightmare?'\nVaresa K`Zen says 'Do you even know who you are talking to? I'm Varesa K'Zen. I am quite a skilled necromancer. Or was. I can't remember certain things after coming near this bloody place. But I have a feeling I could remember, if only I had proper access to this library. Normally this wouldn't be an issue, but in my weakened state, I need [help]. As much as it pains me to ask.'\nYou say, 'How can I help'\nVaresa K`Zen says 'Have you not looked around? Those armed and armored thugs patrolling around like this is a barracks. The custodians who attack anyone who passes by. The strange librarians who won't let me near the books! And even some of the books themselves are hostile. And then those researchers who are hoarding books. They are the worst! If not for them, I'd have my magic back. I'm sure of it. So, are you interested in assisting me? I will make sure you are rewarded, of course.'\n_A task window pops up with five options to choose from._\nYou have been assigned the task 'Deadly Knowledge'.\nVaresa K`Zen and many others have been assaulted by the animated tomes in this strange place. She has asked you to destroy them so they can cause no more trouble.\n\n---\n\nDestroy the hostile neglected tomes 0/4 (The Library)\nDestroy the hostile ancient codices 0/4 (The Library)\nSpeak to Varesa K`Zen 0/1 (The Library)\nYour task 'Deadly Knowledge' has been updated.\nYou've shredded the dangerous animated books. They should cause no more problems for would-be researchers.\nYour faction with Dream Delvers has been adjusted by 5\n_Rewards:_\nExperience\nMinor Faction with Dream Delvers",
    },
    {
      id = "5188",
      title = "Bibliophiles",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Varesa K`Zen",
      loc = { y = 150.0, x = 245.0, z = -3.0 },
      triggers = {
        "Hail, Varesa K`Zen",
        "Nightmare?",
        "How can I help",
        "nightmare",
        "help",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Library [zone=751]\n**Who:**\n- Varesa K`Zen [npc=36181]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Creatures:**\n- a listless librarian [npc=36191]\n- a lonely librarian [npc=36173]\n- a weary assistant [npc=36179]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 3 03:21:00 2010\nModified: Sat Jul 9 21:46:31 2011 | | _This is a solo kill task that begins with Varesa K`Zen. She is found in the Library at location 150, 245, -3 (in the hallway north of the room with the various scholars)._\nYou say, 'Hail, Varesa K`Zen'\nVaresa K`Zen says 'I can feel my power slipping away. Why can't I remember all my spells? This is my worst [nightmare] come to life.'\nYou say, 'Nightmare?'\nVaresa K`Zen says 'Do you even know who you are talking to? I'm Varesa K'Zen. I am quite a skilled necromancer. Or was. I can't remember certain things after coming near this bloody place. But I have a feeling I could remember, if only I had proper access to this library. Normally this wouldn't be an issue, but in my weakened state, I need [help]. As much as it pains me to ask.'\nYou say, 'How can I help'\nVaresa K`Zen says 'Have you not looked around? Those armed and armored thugs patrolling around like this is a barracks. The custodians who attack anyone who passes by. The strange librarians who won't let me near the books! And even some of the books themselves are hostile. And then those researchers who are hoarding books. They are the worst! If not for them, I'd have my magic back. I'm sure of it. So, are you interested in assisting me? I will make sure you are rewarded, of course.'\n_A task window pops up with five options to choose from._\nYou have been assigned the task 'Bibliophiles'.\nVaresa K`Zen, a once-powerful necromancer, is unsure of the true nature of the librarians and their assistants. She does want them dealt with, though, as they hoard all the knowledge that she requires to gain her magical abilities back.\n\n---\n\nDefeat the listless librarians 0/5 (The Library)\nDefeat the librarians` weary assistants 0/4 (The Library)\nSpeak to Varesa K`Zen 0/1 (The Library)\nYou say, 'Hail, Varesa K`Zen'\nYour task 'Bibliophiles' has been updated.\nYou've stopped the hostile librarians and their assistants making it safe to study in the strange library.\n_Rewards:_\nExperience\nMinor Faction with Dream Delvers",
    },
    {
      id = "5189",
      title = "A Moment of Clarity",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Tarlyn Caelith",
      loc = { y = 55.0, x = 285.0, z = -3.0 },
      triggers = {
        "Hail, Tarlyn Caelith",
        "How close?",
        "Wrong?",
        "Yes, we must acquire it...",
        "We",
        "close",
        "wrong",
        "acquire",
      },
      items_required = {
        { name = "you too much trouble? This place is mad", count = 1 },
      },
      rewards = {
        { id = 91144, name = "Ancient Spellbook", type = "item" },
        { id = 90269, name = "Old Spell Codex", type = "item" },
        { id = 90294, name = "Unusual Tome", type = "item" },
        { id = 90478, name = "Worn Book", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Library [zone=751]\n**Who:**\n- Tarlyn Caelith [npc=36186]\nRating:\n0/5**_\\*__\\*__\\*__\\*__\\*_**\n(Average from 5 ratings)\nInformation:\n**Level:** | 90\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Loot\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 06:00:00\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Quest Items:**\n- Ancient Spellbook [item=91144]\n- Old Spell Codex [item=90269]\n- Unusual Tome [item=90294]\n- Worn Book [item=90478]\n**Related Zones:**\n- The Library: A Moment of Clarity [zone=768]\n**Related Creatures:**\n- Sage Weldan [npc=36559]\n- Tarlyn Caelith [npc=38025]\n- an ornate chest - A Moment of Clarity [npc=36558]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 3 19:14:03 2010\nModified: Sat Sep 28 07:21:33 2024 | | _This is a non-progression group mission (3-6 players) that begins with Tarlyn Caelith in the Library. He is found at location 55, 285, -3 (in the hallway west of the room with the various scholars)._\n_There are no pre-requisites for requesting this task._\n_Note: This is a Tier 4 difficulty task, meaning mob difficulty will be along the same lines as Morell's Castle and Sanctum Somnium._\nYou say, 'Hail, Tarlyn Caelith'\nTarlyn Caelith says 'Please tell me you are not here to try to kill me. I'm getting quite sick of running around in this library. At least I'm having better luck than that Kintorom fellow. Still, even though I'm [close], I still need more time!'\nYou say, 'How close?'\nTarlyn Caelith says 'Very close! To finding the answers. About what is [wrong]. I'm not like the others. I know something is wrong here. Though I distinctly remember finding this library, I believe my memory, and almost everything about this place is again, for lack of a better word, [wrong].'\nYou say, 'Wrong?'\nTarlyn Caelith says 'Yes. In fact, I think you know more about this than anyone else here. Still, I'm afraid my moment of clarity won't last too long. I'll need to act fast. There is a spellbook here in this library. I saw it, I almost had it, but one of those strange librarians took it and almost killed me. We must [acquire] it!'\nYou say, 'Yes, we must acquire it...'\nTarlyn Caelith says 'I'm glad to see you agree. Let me know when you are [prepared]. I warn you, this will become violent, and I am not going to be of much use to you in a fight. However, I will be able to use that book once we find it.'\nYou have been assigned the task 'A Moment of Clarity'.\nYou say, 'We're prepared!'\nTarlyn Caelith says 'Excellent. This way. We'll return to the first floor and start there.'\nLOADING, PLEASE WAIT...\nYou have entered The Library.\n\n---\n\n_Summary: You'll have to find Unusual Tomes, Old Spell Codices, and Worn Books (groundspawns you'll find as you make your way upstairs); and kill listless librarians, weary assistants, and finally, Sage Weldan._\n_Mobs in this zone are mostly yellow /cons to Level 90 and mostly melee._\nSearch the entrance for books 0/1 (The Library)\nSearch the ground floor for books 0/1 (The Library)\nSearch the mid-floor library for books 0/1 (The Library)\nSearch the winding stairwell for books 0/1 (The Library)\nSearch the top floor for books 0/1 (The Library)\nDeliver any unusual tomes found to Tarlyn 0/3 (The Library)\nDeliver any worn books found to Tarlyn 0/3 (The Library)\nDeliver any old spell codices found to Tarlyn 0/3 (The Library)\nTarlyn Caelith says 'You've done well, my friend. These books will prove useful, but they aren't exactly the ones I'm looking for.'\nDefeat any librarians that interfere 0/10 (The Library)\nDefeat any assistants that interfere 0/8 (The Library)\nObtain information from Sage Weldan 0/1 (The Library)\nSage Weldan eyes you with disdain and runs in for the attack!\n_Sage Weldan's DPS output is only slightly higher than that of the trash mobs in the zone. He has ~1.1 million hitpoints and casts the spells \"Delusion Visage I\" and \"Shadow Lore\":_\nDelusion Visage I: PB AE 30', Chromatic (-700)\n1: Decrease Movement by 80%\nShadow Lore: PB AE 200', Magic (-650)\n1: Decrease Hitpoints by 11900\n2: Decrease Mana by 2380\nSage Weldan has been slain by \\_\\_\\_\\_\\_!\nSage Weldan's corpse gasps for air, choking out one final breath.\nObtain the ancient spellbook from Sage Weldan 0/1 (The Library)\nReturn the ancient spellbook to Tarlyn Caelith 0/1 (The Library)\nSpeak to Tarlyn Caelith 0/1 (The Library)\nYou say, 'Hail, Tarlyn Caelith'\nTarlyn Caelith says 'I knew you could do it! This is just the book I was looking for. I hope Sage Weldan didn't give you too much trouble? This place is mad. Thank you friend. With your help, I might be able to end this nightmare. At least, I hope so. I'll need some time to study. Don't let me keep you!'\nTake your reward from the chest 0/1 (The Library)\nWith your aid, Tarlyn Caelith obtained the book of magic he was looking for. However, it is unclear if he will remember what has transpired, or be lucid enough to decipher the text to assist some of the trapped dreamers. You had best continue your efforts in other areas while he studies the text.\n\n---\n\n_Task rewards:_\n315 platinum\nExperience\nFaction with Dream Delvers\n80 Dream Motes [item=90255]\n_Known Chest Loot [npc=36558] (1 item + 1 spell per task):_\nBielaisk's Cape\nConjurer's Orb\nDream Destroyer's Hand\nGuardian's Greaves\nKnight Captain's Shield\nMace of Dark Dreams\nMalleable Core of the Guardian\nNesalie's Spell Gem\nQuentin's Outfit\nShadow Warden's Rapier\nMinor Nebulous Dream Fragment\nLesser Nebulous Dream Fragment\nMedian Nebulous Dream Fragment\nGreater Nebulous Dream Fragment\nGlowing Nebulous Dream Fragment\n- Dream Mote [item=90255]",
    },
  },
}
