-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for House of Thule, Upper Floors (thulehouse1)
-- Total Quests: 14
-- ============================================================================

return {
  zone = "thulehouse1",
  zone_name = "House of Thule, Upper Floors",
  quests = {
    {
      id = "5203",
      title = "Drawn to Flame",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Karivei Skyflare",
      loc = nil,
      triggers = {
        "Hail, Karivei Skyflare",
        "Examine the elements?",
        "Entails...?",
        "Fire?",
        "I",
        "_Quests_",
        "examine the elements",
        "entails",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- House of Thule, Upper Floors [zone=753]\n**Who:**\n- Karivei Skyflare [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 90\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Creatures:**\n- a hateful fire elemental [npc=36279]\n- an ember golem [npc=36278]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 9 22:06:53 2010\nModified: Mon Apr 4 03:58:24 2011 | | _This is a solo kill task that begins with Karivei Skyflare in the House of Thule's Upper Floors (located at the western zone-in)._\nYou say, 'Hail, Karivei Skyflare'\nKarivei Skyflare says 'Vasha. Are you also here to [examine the elements] who have taken residence in the House? '\nYou say, 'Examine the elements?'\nKarivei Skyflare says 'I was promised a group of adventurers, but clearly they've yet to arrive. I can only hope you'll all be suitable replacements.' She smugly grins back at \\_\\_\\_\\_\\_. 'I hope you know what all this [entails].'\nYou say, 'Entails...?'\nKarivei Skyflare says 'There are two particular sets of element-based life forms about the second floor. While I know many of them are not elementals, their life still seems to be drawn by the elements they enhabit: [fire] and [ice].'\nYou say, 'Fire?'\nKarivei Skyflare says 'Fire, neither consuming nor ceasing, magically in a constant state of blazing heat. Several fire-like beings surround the fire, mingling with each other in the flaming rooms of the house. Will you go [seek them out] and return to me with what you find?'\nYou say, 'I'll seek them out'\nKarivei Skyflare says 'I appreciate your assistance. Return to me soon.'\nYou have been assigned the task 'Drawn to Flame'.\nKarivei Skyflare has been awaiting a group of hired adventurers for assistance in his research, but they have yet to arrive. She has taken you on as a replacement, requesting that you kill and research the elements of fire as they are manifest in the house.\n\n---\n\nKill ember golems for research 0/5 (House of Thule, Upper Floors)\nKill hateful fire elementals for research 0/5 (House of Thule, Upper Floors)\n_The above mobs are found in large numbers in the zone's southeastern wing. There are also a few hateful fire elementals in the northwestern wing._\nReport your findings back to Karivei 0/1 (House of Thule, Upper Floors)\nYou say, 'Hail, Karivei Skyflare'\nKarivei Skyflare hears your report on the fire creatures of the second floor and jotting down the details you've supplied, he nods his head in thanks.\n_Rewards:_\nExperience _(around 1 AA worth at Level 90)_\nMinor Faction with Dream Delvers",
    },
    {
      id = "5120",
      title = "The Beast of Horror",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Researcher Breoro",
      loc = nil,
      triggers = {
        "Hail, Researcher Breoro",
        "I",
        "What living nightmare?",
        "Nightmares?",
        "Why can",
        "Destroyed?",
        "What about the potion of horror?",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
        { id = 91930, name = "Bone Dust", type = "item" },
        { id = 92358, name = "Essence of Horror", type = "item" },
        { id = 92052, name = "Shrunken Head", type = "item" },
        { id = 91230, name = "Troublesome Snake Skin", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
        { id = 117793, name = "Heroic Jewel of the Self", type = "item" },
      },
      factions = {
        { name = "Dream Delvers", change = 10 },
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- House of Thule, Lower Floors [zone=748]\n**Who:**\n- Researcher Breoro [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Factions Raised:**\n- Dream Delvers +10\n**Factions Lowered:**\n**Quest Items:**\n- Bone Dust [item=91930]\n- Essence of Horror [item=92358]\n- Shrunken Head [item=92052]\n- Troublesome Snake Skin [item=91230]\n**Related Creatures:**\n- a beastling of horror [npc=35782]\n- a bone crafter [npc=35785]\n- a bone golem [npc=35784]\n- a troublesome snake [npc=35769]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Oct 14 17:35:41 2010\nModified: Tue Dec 5 05:21:04 2023 | | _This solo task begins with Researcher Breoro in the House of Thule's Lower Floors. He's located just inside the front door of the house._\nYou say, 'Hail, Researcher Breoro'\nResearcher Breoro says 'Are you yet another [figment] of my imagination seemingly come to life?'\nYou say, 'I'm not a figment of your imagination...'\nResearcher Breoro says 'No, I can tell that you are not from this accursed place. Thank the Gods. Please forgive me. I have been in this [living nightmare] for far too long. It has become difficult to tell that which is real from that which is not.'\nYou say, 'What living nightmare?'\nResearcher Breoro says 'This place, whatever it is, has trapped me within its dark grasp. You see, I am a researcher of dreams and nightmares. I have long suffered from debilitating nightmares for as long as I can remember. Long ago, I decided to dedicate my life to uncovering their meaning. As my research progressed over several weeks, the [nightmares] I was experiencing seemed to become more and more lifelike.'\nYou say, 'Nightmares?'\nResearcher Breoro says 'The nightmares always involve four horrible beasts. Night after night the nightmares grew in intensity until one night I woke up here, in this accursed place. Now I cannot [leave].'\nYou say, 'Why can't you leave?'\nResearcher Breoro says 'There seems to be some force blocking my escape from this place. I have discovered that the beasts hold some sort of influence over my mind and have brought me here. They are minions of Terris Thule. Terris is up to something, hence this house. I feel her calling to me. What she wishes to gain from this, I do not know. The beasts appear to be her tools for whatever evil plan she is envisioning however. We must stop this. The beasts must be [destroyed].'\nYou say, 'Destroyed?'\nResearcher Breoro says 'Before we can confront the beasts, several potions made from the essences of the creatures that exist here are needed. We will need a [potion of rot], a [potion of the unknown], a [potion of rage], and a [potion of horror].'\nYou say, 'What about the potion of horror?'\nResearcher Breoro says 'Collect the ingredients I need for the Potion of Horror and then bring them back to me. There is no time to waste.'\nYou have been assigned the task 'The Beast of Horror'.\nResearcher Breoro wants you to collect Bone Dust from the bone golems, Shrunken Heads from the bone crafters, Troublesome Snake Skins from snakes, and Essences of Horror from beastlings of horror. These creatures all inhabit the first floor of the House of Thule. Once you have them, deliver them to Researchrer Breoro.\n\n---\n\nCollect 2 Bone Dusts 0/2 (House of Thule)\nCollect 2 Shrunken Heads 0/2 (House of Thule)\nCollect 2 Troublesome Snake Skins 0/2 (House of Thule)\nCollect 1 Essence of Horror 0/1 (House of Thule)\n_Items are pre-lootable._\nDeliver 2 Bone Dusts to Researcher Breoro 0/2 (House of Thule)\nDeliver 2 Shrunken Heads to Researcher Breoro 0/2 (House of Thule)\nDeliver 2 Troublesome Snake Skins to Researcher Breoro 0/2 (House of Thule)\nDeliver 1 Essence of Horror to Researcher Breoro 0/1 (House of Thule)\nResearcher Breoro says 'You are doing well, my friend. The potion of horror must be mixed without error. Even the smallest mistake will ensure that I am lost to madness forever. Let's see. . . a pinch of bone dust is needed. Next the scales from the snake skins should be sloughed off into the mixture. Now, I must pour the mixture into the shrunken heads and add the essence of horror. Finally, the potion must ferment inside the shrunken heads for at least two hours. Make sure to speak with me again once all four of the potions have been brewed.'\n_Rewards:_\n158 Platinum\nExperience (about 1.5 AAs worth or more if you have a low AA count)\nYour faction standing with Dream Delvers has been adjusted by 10.\n5 Dream Motes\n_Heroic characters may receive an aug choice reward. Regular characters do not._\n- Dream Mote [item=90255]\n- Heroic Jewel of the Self [item=117793]\n- Heroic Jewel of the Self [item=116773]",
    },
    {
      id = "5121",
      title = "The Beast of Rage",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Researcher Breoro",
      loc = nil,
      triggers = {
        "Hail, Researcher Breoro",
        "I",
        "What living nightmare?",
        "Nightmares?",
        "Why can",
        "Destroyed?",
        "What about the potion of rage?",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
        { id = 92051, name = "Essence of Rage", type = "item" },
        { id = 92050, name = "Pile of Rust", type = "item" },
        { id = 92049, name = "Pulsating Ectoplasm", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
        { name = "Dream Delvers", change = 10 },
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- House of Thule, Lower Floors [zone=748]\n**Who:**\n- Researcher Breoro [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Factions Raised:**\n- Dream Delvers +10\n**Factions Lowered:**\n**Quest Items:**\n- Essence of Rage [item=92051]\n- Pile of Rust [item=92050]\n- Pulsating Ectoplasm [item=92049]\n**Related Creatures:**\n- a beastling of rage [npc=35780]\n- a quaking haunt [npc=35791]\n- a terror guard [npc=35767]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Oct 14 17:35:59 2010\nModified: Tue Dec 5 05:21:04 2023 | | _This solo task begins with Researcher Breoro in the House of Thule's Lower Floors. He's located just inside the front door of the house._\nYou say, 'Hail, Researcher Breoro'\nResearcher Breoro says 'Are you yet another [figment] of my imagination seemingly come to life?'\nYou say, 'I'm not a figment of your imagination...'\nResearcher Breoro says 'No, I can tell that you are not from this accursed place. Thank the Gods. Please forgive me. I have been in this [living nightmare] for far too long. It has become difficult to tell that which is real from that which is not.'\nYou say, 'What living nightmare?'\nResearcher Breoro says 'This place, whatever it is, has trapped me within its dark grasp. You see, I am a researcher of dreams and nightmares. I have long suffered from debilitating nightmares for as long as I can remember. Long ago, I decided to dedicate my life to uncovering their meaning. As my research progressed over several weeks, the [nightmares] I was experiencing seemed to become more and more lifelike.'\nYou say, 'Nightmares?'\nResearcher Breoro says 'The nightmares always involve four horrible beasts. Night after night the nightmares grew in intensity until one night I woke up here, in this accursed place. Now I cannot [leave].'\nYou say, 'Why can't you leave?'\nResearcher Breoro says 'There seems to be some force blocking my escape from this place. I have discovered that the beasts hold some sort of influence over my mind and have brought me here. They are minions of Terris Thule. Terris is up to something, hence this house. I feel her calling to me. What she wishes to gain from this, I do not know. The beasts appear to be her tools for whatever evil plan she is envisioning however. We must stop this. The beasts must be [destroyed].'\nYou say, 'Destroyed?'\nResearcher Breoro says 'Before we can confront the beasts, several potions made from the essences of the creatures that exist here are needed. We will need a [potion of rot], a [potion of the unknown], a [potion of rage], and a [potion of horror].'\nYou say, 'What about the potion of rage?'\nResearcher Breoro says 'Collect the ingredients I need for the Potion of Rage and then bring them back to me. There is no time to waste.'\nYou have been assigned the task 'The Beast of Rage'.\nResearcher Breoro wants you to collect Pulsating Ectoplasms from quaking haunts, Piles of Rust from terror guards, and Essences of Rage from beastlings of rage. These creatures all inhabit the first floor of the House of Thule. Once you have them, deliver them to Researchrer Breoro.\n\n---\n\n3. Collect 2 Pulsating Ectoplasms 0/2 (House of Thule)\n\n4. Collect 4 Piles of Rust 0/4 (House of Thule)\n\n5. Collect 1 Essence of Rage 0/1 (House of Thule)\n\n\n\n_Note: All of the collect pieces are pre-lootable..._\n\n6. Deliver 2 Pulsating Ectoplasms to Researcher Breoro 0/2 (House of Thule)\n\n7. Deliver 4 Piles of Rust to Researcher Breoro 0/4 (House of Thule)\n\n8. Deliver 1 Essence of Rage to Researcher Breoro 0/1 (House of Thule)\n\n\n\nResearcher Breoro says 'You have brought the components for the potion of rage? This potion must be made with extreme care. The piles of rust will taste poorly, I am sure, but they are necessary. I shall add them first. Next, the pulsating ectoplasm should be added to the mix. The fragments of stone will help ground me in the physical realm after consuming the potion. Finally, the essence of rage can be added. This potion must sit for at least an hour before I can consume it. It is far too potent at the moment. Make sure to speak with me again once all four of the potions have been brewed.'\n\n\n\n\n\n\n\n---\n\n\n\n\n_Rewards:_\n\n158 Platinum\n\n\nExperience (about 1.5 AAs worth; more if you have a low AA count)\n\n\nYour faction standing with Dream Delvers has been adjusted by 10.\n\n\n5 Dream Motes\n- Dream Mote [item=90255]",
    },
    {
      id = "5122",
      title = "The Beast of Rot",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Researcher Breoro",
      loc = nil,
      triggers = {
        "Hail, Researcher Breoro",
        "I",
        "What living nightmare?",
        "Nightmares?",
        "Why can",
        "Destroyed?",
        "What about the potion of rot?",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
        { id = 91228, name = "Bone Fragment", type = "item" },
        { id = 92356, name = "Essence of Rot", type = "item" },
        { id = 92023, name = "Rotdog Rib", type = "item" },
        { id = 92024, name = "Snake Heart", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
        { name = "Dream Delvers", change = 10 },
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- House of Thule, Lower Floors [zone=748]\n**Who:**\n- Researcher Breoro [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Factions Raised:**\n- Dream Delvers +10\n**Factions Lowered:**\n**Quest Items:**\n- Bone Fragment [item=91228]\n- Essence of Rot [item=92356]\n- Rotdog Rib [item=92023]\n- Snake Heart [item=92024]\n**Related Creatures:**\n- a beastling of rot [npc=35783]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Oct 14 17:36:17 2010\nModified: Sat Feb 9 20:43:56 2019 | | _This solo task begins with Researcher Breoro in the House of Thule's Lower Floors. He's located just inside the front door of the house._\nYou say, 'Hail, Researcher Breoro'\nResearcher Breoro says 'Are you yet another [figment] of my imagination seemingly come to life?'\nYou say, 'I'm not a figment of your imagination...'\nResearcher Breoro says 'No, I can tell that you are not from this accursed place. Thank the Gods. Please forgive me. I have been in this [living nightmare] for far too long. It has become difficult to tell that which is real from that which is not.'\nYou say, 'What living nightmare?'\nResearcher Breoro says 'This place, whatever it is, has trapped me within its dark grasp. You see, I am a researcher of dreams and nightmares. I have long suffered from debilitating nightmares for as long as I can remember. Long ago, I decided to dedicate my life to uncovering their meaning. As my research progressed over several weeks, the [nightmares] I was experiencing seemed to become more and more lifelike.'\nYou say, 'Nightmares?'\nResearcher Breoro says 'The nightmares always involve four horrible beasts. Night after night the nightmares grew in intensity until one night I woke up here, in this accursed place. Now I cannot [leave].'\nYou say, 'Why can't you leave?'\nResearcher Breoro says 'There seems to be some force blocking my escape from this place. I have discovered that the beasts hold some sort of influence over my mind and have brought me here. They are minions of Terris Thule. Terris is up to something, hence this house. I feel her calling to me. What she wishes to gain from this, I do not know. The beasts appear to be her tools for whatever evil plan she is envisioning however. We must stop this. The beasts must be [destroyed].'\nYou say, 'Destroyed?'\nResearcher Breoro says 'Before we can confront the beasts, several potions made from the essences of the creatures that exist here are needed. We will need a [potion of rot], a [potion of the unknown], a [potion of rage], and a [potion of horror].'\nYou say, 'What about the potion of rot?'\nResearcher Breoro says 'Collect the ingredients I need for the Potion of Rot and then bring them back to me. There is no time to waste.'\nYou have been assigned the task 'The Beast of Rot'.\nResearcher Breoro wants you to collect Rotdog Ribs from rotdogs, Bone Fragments from skeletons, Snake Hearts from snakes, and Essences of Rot from beastlings of rot. These creatures all inhabit the first floor of the House of Thule. Once you have them, deliver them to Researchrer Breoro.\n\n---\n\nCollect 2 Rotdog Ribs 0/2 (House of Thule)\nCollect 2 Bone Fragments 0/2 (House of Thule)\nCollect 2 Snake Hearts 0/2 (House of Thule)\nCollect 1 Essence of Rot 0/1 (House of Thule)\nDeliver 2 Rotdog Ribs to Researcher Breoro 0/2 (House of Thule)\nDeliver 2 Bone Fragments to Researcher Breoro 0/2 (House of Thule)\nDeliver 2 Snake Hearts to Researcher Breoro 0/2 (House of Thule)\nDeliver 1 Essence of Rot to Researcher Breoro 0/1 (House of Thule)\nResearcher Breoro says 'You have done well. Now I must grind these rot dog ribs along with the bone fragments into a fine powder. I must then let these snake hearts fully bleed out as to not taint the potion. Finally, the essence of rot can be added. Make sure to speak with me again once all four of the potions have been brewed.'\n_Rewards:_\n158 platinum\nExperience (about 1.5 AAs worth or more if you have a low AA count)\nYour faction standing with Dream Delvers has been adjusted by 10.\n5 Dream Motes\n- Dream Mote [item=90255]",
    },
    {
      id = "5142",
      title = "Welcome to My Nightmare",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Researcher Breoro",
      loc = nil,
      triggers = {
        "Hail, Researcher Breoro",
        "What task?",
        "We",
        "Let",
        "_Quests_",
        "task",
        "potion of rot",
        "potion of rage",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- House of Thule, Lower Floors [zone=748]\n**Who:**\n- Researcher Breoro [ _Quests_]\nRating:\n0/8**_\\*__\\*__\\*__\\*__\\*_**\n(Average from 8 ratings)\nInformation:\n**Level:** | 85\n**Maximum Level:** | 95\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Faction\n- Loot\n- Money\n**Success Lockout Timer**: 06:00:00\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Zones:**\n- House of Thule: Welcome to My Nightmare [zone=761]\n**Related Creatures:**\n- Keeper Barja [npc=36154]\n- Keeper Bianoa [npc=36147]\n- Keeper Cilkian [npc=36152]\n- Keeper Dalmari [npc=36148]\n- Keeper Eteran [npc=36151]\n- Keeper Jilam [npc=36153]\n- Keeper Moian [npc=36158]\n- Keeper Nujoi [npc=36155]\n- Keeper Polyai [npc=36149]\n- Keeper Tyoan [npc=36156]\n- Keeper Viljan [npc=36150]\n- Keeper Zilkan [npc=36157]\n- Researcher Breoro [npc=36161]\n- The Beast of Horror [npc=36166]\n- The Beast of Rage [npc=36165]\n- The Beast of Rot [npc=36162]\n- The Beast of the Unknown [npc=36164]\n- an ornate chest - Welcome to My Nightmare [npc=36167]\n**Related Quests:**\n- The Beast of Horror [quest=5120]\n- The Beast of Rage [quest=5121]\n- The Beast of Rot [quest=5122]\n- The Beast of the Unknown [quest=5123]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Oct 21 19:33:24 2010\nModified: Mon Feb 25 01:08:05 2019 | | _This is a group progression task that begins with Researcher Breoro in the lower floors of the House of Thule (just inside the front door). The task locks after killing the last mini-boss, regardless of order._\n_You must have completed his four solo tasks prior to being able to request this one._\nYou say, 'Hail, Researcher Breoro'\nResearcher Breoro says 'Now that all of the potions have been brewed, it is time to take on the beasts themselves. This will be no easy [task]. Or, just in case, you can retrieve more ingredients for me, so I can brew another [potion of rot], [potion of rage], [potion of horror], or [potion of the unknown].'\nYou say, 'What task?'\nResearcher Breoro says 'Once I drink these potions, you will be able to enter my nightmare and destroy the beasts. Each beast has three protectors that will need to be defeated before the beasts themselves can be confronted. When you are [ready], I will drink the potions.'\nYou say, 'We're ready'\nResearcher Breoro says 'I have consumed the potions and can already begin to feel their effect on me. Please let me know when you are ready to [go], and you will be able to enter my nightmare and hopefully end this once and for all.'\nYou have been assigned the task 'Welcome to My Nightmare'.\nDefeat the necromancers guarding the Beasts of Rot, Horror, Rage, and the Unknown. Once you have accomplished this, speak with Researcher Breoro.\nYou say, 'Let's go'\nResearcher Breoro says 'May the Gods be with you.'\nLOADING, PLEASE WAIT...\nYou have entered House of Thule: Breoro's Nightmare.\n\n---\n\n_The first task steps open are all the \"Destroy Keeper...\" steps. These Keepers are found in groups of three in the same locations where you'd find the \"beastling\" mobs in the non-instanced zone._\n_Killing each group of Keepers spawns the Beast associated with them. The Beasts spawn right on top of the corpse of the last Keeper to die in each set._\n_Keepers hit for a max ~6,000 and are stunnable, rootable/snareable, mezzable, and able to be harmonized._\n_The Beasts hit for a max ~8,500, enrage, have more hitpoints, and are immune to crowd control methods. They also each come with an AE debuff (listed below). These debuffs are triggered by using same-resist spells against them (The Beast of Rot's debuff, for example, would be triggered by any disease-based spell used against it)._\n_The Researcher at the end hits for a max ~8,000 and also has a lot of hitpoints._\nDestroy Keeper Bianoa 0/1 (House of Thule)\nDestroy Keeper Dalmari 0/1 (House of Thule)\nDestroy Keeper Polyai 0/1 (House of Thule)\nDestroy the Beast of Rot 0/1 (House of Thule)\nThe Beast of Rot senses that you would make a good meal and closes in for the attack!\nCurse of Rot: PB AE 400', Unresistable (0)\n1: Increase Incoming Spell Damage by 20%\n2: Limit: Resist (Disease allowed)\n3: Increase Disease Counter by 50\nRot Breath: Single Target, Disease (-700)\n1: Decrease HP when cast by 23000\n2: Decrease Hitpoints by 6000 per tick\n3: Increase Disease Counter by 40\nDestroy Keeper Viljan 0/1 (House of Thule)\nDestroy Keeper Eteran 0/1 (House of Thule)\nDestroy Keeper Cilkian 0/1 (House of Thule)\nDestroy the Beast of the Unknown 0/1 (House of Thule)\nThe Beast of the Unknown swiftly approaches.\nCurse of Fire: PB AE 400', Unresistable (0)\n1: Increase Incoming Spell Damage by 20%\n2: Limit: Resist (Fire allowed)\n3: Increase Curse Counter by 50\nDark Embrace: Single Target, Fire (-700)\n1: Decrease Hitpoints by 20000 per tick _(1 tick)_\n2: Blindness (1)\nDestroy Keeper Jilam 0/1 (House of Thule)\nDestroy Keeper Barja 0/1 (House of Thule)\nDestroy Keeper Nujoi 0/1 (House of Thule)\nDestroy the Beast of Horror 0/1 (House of Thule)\nThe Beast of Horror skitters towards you, eager to end your life.\nCurse of Poison: PB AE 400', Unresistable (0)\n1: Increase Incoming Spell Damage by 20%\n2: Limit: Resist (Poison allowed)\n3: Increase Poison Counter by 50\nNightmarish Venom: Single Target, Poison (-700)\n1: Decrease Hitpoints by 8000 per tick\n2: Decrease Mana by 5000 per tick\n3: Decrease Endurance by 800 per tick\n4: Increase Poison Counter by 30\nDestroy Keeper Tyoan 0/1 (House of Thule)\nDestroy Keeper Zilkan 0/1 (House of Thule)\nDestroy Keeper Moian 0/1 (House of Thule)\nDestroy the Beast of Rage 0/1 (House of Thule)\nThe Beast of Rage becomes enraged and rushes to the attack!\nCurse of Frost: PB AE 400', Unresistable (0)\n1: Increase Incoming Spell Damage by 20%\n2: Limit: Resist (Cold allowed)\n3: Increase Curse Counter by 50\nIcy Blow: Single Target, Cold (-700)\n1: Decrease Hitpoints by 30000\n2: Stun (5.00 sec)\nSpeak with Researcher Breoro 0/1 (House of Thule)\nYou say, 'Hail, Researcher Breoro'\nResearcher Breoro says 'I can no longer feel the presence of the beasts. Thanks to you fools, I am now able to control my nightmare and have more power than I could have ever imagined. Your services will no longer be needed.'\nDefend yourself against Researcher Breoro 0/1 (House of Thule)\n_Researcher Breoro hits for a max ~8,000, has 650,000 hitpoints, and casts a standard set of wizard spells._\n_He also procs the spell \"Dream Splinter\" on his target:_\nDream Splinter: Magic (-650)\n1: Decrease Hitpoints by 15000\n_As his health approaches 0%, he goes inactive._\nStop! Stop fighting! This is madness! We must stop this at once!\nSpeak with Researcher Breoro 0/1 (House of Thule)\nResearcher Breoro says 'I don't know what came over me. I am truly sorry. I could not resist the rush of power dangled before my eyes. Let me know when you are ready to [leave] this place.'\nCollect your reward from the ornate chest 0/1 (House of Thule)\n_An ornate chest spawns nearby with loot._\n\n---\n\n_Task Rewards:_\nExperience (about 6% regular exp at Level 86 or 4 AAs worth)\n315 platinum\n20 Dream Motes\nFaction with Dream Delvers\n_Known chest rewards (1 item + 1 spell per task):_\nAcorn of Spite\nAxe of the Woodcutter\nDeathpoint\nGanborn's Rod of Curses\nHardened Dragon's Tear\nJagged Metal Knuckles\nRing of Restless Sleep\nRing of the Fearborn\nSlippery Slimerock\nTerror Infused Linked Vambraces\nMinor Nebulous Dream Fragment\nLesser Nebulous Dream Fragment\nMedian Nebulous Dream Fragment\nGreater Nebulous Dream Fragment\nGlowing Nebulous Dream Fragment",
    },
    {
      id = "5146",
      title = "Find My Brudders",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Groot",
      loc = nil,
      triggers = {
        "Hail, Groot",
        "I can help!",
        "You... not go?",
        "I",
        "Hail, Krantz",
        "Hail, Huorun",
        "Hail, Gumbor",
        "Hail, Torlan",
      },
      items_required = {
      },
      rewards = {
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- House of Thule, Lower Floors [zone=748]\n**Who:**\n- Groot [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Success Lockout Timer**: 06:00:00\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Creatures:**\n- Gumbor [npc=35777]\n- Huorun [npc=35776]\n- Korlof [npc=35806]\n- Krantz [npc=36319]\n- Torlan [npc=35778]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Oct 25 20:18:03 2010\nModified: Tue Dec 5 05:21:04 2023 | | _This solo task begins with Groot, an ogre at the zone-in area of the House of Thule (lower floors)._\nYou say, 'Hail, Groot'\nGroot says 'You not look like search party, but mebbe you can [help] anyway.'\nYou say, 'I can help!'\nGroot says 'Me and my brudders find dis strange house. Dey went inside, but I [not go].'\nYou say, 'You... not go?'\nGroot says 'No, me not scared. Just don't have me favorite club to smash dem critters in dere. Anyway, you think you could go in house and [find] my brudders?'\nYou say, 'I'll find them'\nGroot says 'Thank you for help. My brudders not be so smart like me, so I little bit worried about dem.'\nYou have been assigned the task 'Find My Brudders'.\nGroot wants you to find his brothers who have gone missing in the House of Thule.\n\n---\n\n_In-game /locations:_\nKrantz: 305, -40, 13 (in the room with the staircases leading to the Upper Floors)\nHuorun: 500, 245, 13 (in the hallway leading to the Library)\nGumbor: 645, 200, 13 (in the area leading to the Grounds)\nTorlan: 685, -740, -60 (in a corner in the basement's largest room)\nKorlof: 515, -385, 13 (end of the hall with the Erudin Burning entrance)\n_Map locations for thulehouse.txt:_\nP 40.0000, -305.0000, 13.0000, 0, 0, 0, 3, Krantz\nP -245.0000, -500.0000, 13.0000, 0, 0, 0, 3, Huorun\nP 200.0000, -645.0000, 13.0000, 0, 0, 0, 3, Gumbor\nP 740.0000, -685.0000, -60.0000, 0, 0, 0, 3, Torlan\nP 385.0000, -515.0000, 13.0000, 0, 0, 0, 3, Korlof\nFind Krantz on the first floor of the House of Thule 0/1 (House of Thule)\nYou say, 'Hail, Krantz'\nKrantz says 'Groot send you to look for me? Okay, den I not bash you in da head. Next time you see him, tell him dat I am okay.'\nFind Huorun on the first floor of the House of Thule 0/1 (House of Thule)\nYou say, 'Hail, Huorun'\nHuorun says 'Groot send you in here? He is big chicken. I can take care myself. You go now.'\nFind Gumbor on the first floor of the House of Thule 0/1 (House of Thule)\nYou say, 'Hail, Gumbor'\nGumbor says 'Dis place be so wonderful. Look how pretty it be. Tell Groot to go home. He is weak and not belong in such good place.'\nFind Torlan on the first floor of the House of Thule 0/1 (House of Thule)\nYou say, 'Hail, Torlan'\nTorlan says 'Dis house is like good dream. Me not be leaving. Go back to Groot and tell him to take coward self home. If you see Korlof, you be careful. He become undead skelly. Mebbe you can bash him for us.'\nKorlof has become an undead abomination! Defeat him! 0/1 (House of Thule)\n_Korlof can be pulled single from the room he's in (the haunts won't assist him). He hits for a max ~6,000 (averages much lower) and has no special abilities._\nKorlof has been slain by \\_\\_\\_\\_\\_!\nKorlof's corpse crumbles into a huge pile of bones.\nReturn to Groot 0/1 (House of Thule)\nYou say, 'Hail, Groot'\nGroot says 'Korlof become undead? Poor Korlof. He not smart like me and stay out of house. Me thank you for finding brudders. Guess dey like house and wanna stay. Me stay here too for while I guess. Bye.'\n_Rewards:_\n158 platinum\nExperience (1.5 AAs worth)\nFaction with Dream Delvers\n5 Dream Motes\n- Dream Mote [item=90255]",
    },
    {
      id = "5148",
      title = "Thinning Out Their Numbers: Skeletons and Bone Golems",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Ruppoc Rockjumper",
      loc = nil,
      triggers = {
        "Hail, Ruppoc Rockjumper",
        "Tell me about that something you found...",
        "What problem?",
        "I",
        "I could thin their numbers",
        "Skeletons and bone golems",
        "_Quests_",
        "found",
      },
      items_required = {
      },
      rewards = {
        { id = 116606, name = "Heroic Bleakburn Goo", type = "item" },
        { id = 118321, name = "Heroic Bleakburn Goo", type = "item" },
        { id = 125086, name = "Heroic Bleakburn Goo", type = "item" },
        { id = 116981, name = "Heroic Bleakburn Goo", type = "item" },
        { id = 122719, name = "Heroic Bleakburn Goo", type = "item" },
        { id = 116462, name = "Heroic Signet of Devotion", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- House of Thule, Lower Floors [zone=748]\n**Who:**\n- Ruppoc Rockjumper [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Creatures:**\n- a bone golem [npc=35784]\n- a frightening skeleton [npc=35786]\n- a frightful skeleton [npc=35787]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Oct 25 20:34:06 2010\nModified: Thu Apr 2 00:59:29 2020 | | _This is one of five solo kill tasks that are offered by a froglok named Ruppoc Rockjumper at the zone-in of the House of Thule (lower floors)._\nYou say, 'Hail, Ruppoc Rockjumper'\nRuppoc Rockjumper says 'Hey, are you looking for mushrooms and moss to eat too? You're not? Well let me tell you about something I [found] anyway.'\nYou say, 'Tell me about that something you found...'\nRuppoc Rockjumper says 'I was walking through the jungle the other day, looking for some delectable moss and mushrooms for dinner, when I came across this gate you passed through. It just appeared one day. I thought that was strange, so I came inside to check it out. It is a treasure trove of delicious but strange-looking moss! There is one [problem] though.'\nYou say, 'What problem?'\nRuppoc Rockjumper says 'This place is crawling with nightmarish creatures. I managed to sneak around a bit, gathering a few samples of the delicious moss that grows in here, but the monsters eventually spotted me, and I had to flee back to the gate. I really want more of that moss. Think you could [help] me out?'\nYou say, 'I'll help you out'\nRuppoc Rockjumper says 'I can't get any more of that moss with all these critters in here. Do you think you could [thin] their numbers out a bit?'\nYou say, 'I could thin their numbers'\nRuppoc Rockjumper says 'You are too kind! What would you like to kill? [rot dogs] and [snakes], [skeletons] and [bone golems], [terror guards], [terror spinners] and [sleeper cubes], or [bone crafters] and [quaking haunts]?'\nYou say, 'Skeletons and bone golems'\nRuppoc Rockjumper says 'Eww, nasty creatures those are. The frightful skeletons and bone golems are inside the house. Be careful, for they don't care about eating delectible moss. They like warm flesh!'\nYou have been assigned the task 'Thinning Out Their Numbers: Skeletons and Bone Golems'.\n\n---\n\nKill 4 skeletons 0/4 (House of Thule)\nKill 4 bone golems 0/4 (House of Thule)\nReport to Ruppoc Rockjumper 0/1 (House of Thule)\nYou say, 'Hail, Ruppoc Rockjumper'\nRuppoc Rockjumper says 'Thanks for taking care of those horrible skeletons and golems. I hate things that pretend they are alive but aren't!'\n_Rewards:_\nExperience (about 1 AA worth)\nMinor Faction with Dream Delvers\n- Heroic Bleakburn Goo [item=116606]\n- Heroic Bleakburn Goo [item=118321]\n- Heroic Bleakburn Goo [item=125086]\n- Heroic Bleakburn Goo [item=116981]\n- Heroic Bleakburn Goo [item=122719]\n- Heroic Signet of Devotion [item=116462]\n- Heroic Signet of Devotion [item=116813]\n- Heroic Signet of Devotion [item=116626]",
    },
    {
      id = "5149",
      title = "Thinning Out Their Numbers: Terror Guards",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Ruppoc Rockjumper",
      loc = nil,
      triggers = {
        "Hail, Ruppoc Rockjumper",
        "Tell me about that something you found...",
        "What problem?",
        "I",
        "I could thin their numbers",
        "Terror guards",
        "_Quests_",
        "found",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- House of Thule, Lower Floors [zone=748]\n**Who:**\n- Ruppoc Rockjumper [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +5\n**Factions Lowered:**\n**Related Creatures:**\n- a fright guard [npc=35748]\n- a horror guard [npc=35773]\n- a terror guard [npc=35767]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Oct 25 20:34:18 2010\nModified: Sat Mar 25 09:54:11 2023 | | _This is one of five solo kill tasks that are offered by a froglok named Ruppoc Rockjumper at the zone-in of the House of Thule (lower floors)._\nYou say, 'Hail, Ruppoc Rockjumper'\nRuppoc Rockjumper says 'Hey, are you looking for mushrooms and moss to eat too? You're not? Well let me tell you about something I [found] anyway.'\nYou say, 'Tell me about that something you found...'\nRuppoc Rockjumper says 'I was walking through the jungle the other day, looking for some delectable moss and mushrooms for dinner, when I came across this gate you passed through. It just appeared one day. I thought that was strange, so I came inside to check it out. It is a treasure trove of delicious but strange-looking moss! There is one [problem] though.'\nYou say, 'What problem?'\nRuppoc Rockjumper says 'This place is crawling with nightmarish creatures. I managed to sneak around a bit, gathering a few samples of the delicious moss that grows in here, but the monsters eventually spotted me, and I had to flee back to the gate. I really want more of that moss. Think you could [help] me out?'\nYou say, 'I'll help you out'\nRuppoc Rockjumper says 'I can't get any more of that moss with all these critters in here. Do you think you could [thin] their numbers out a bit?'\nYou say, 'I could thin their numbers'\nRuppoc Rockjumper says 'You are too kind! What would you like to kill? [rot dogs] and [snakes], [skeletons] and [bone golems], [terror guards], [terror spinners] and [sleeper cubes], or [bone crafters] and [quaking haunts]?'\nYou say, 'Terror guards'\nRuppoc Rockjumper says 'You want to kill some of the terror guards? They are pretty tough. I don't think they even feel pain. Be careful!'\nYou have been assigned the task 'Thinning Out Their Numbers: Terror Guards'.\n\n---\n\nKill 8 guards 0/8 (House of Thule)\nReport to Ruppoc Rockjumper 0/1 (House of Thule)\nYou say, 'Hail, Ruppoc Rockjumper'\nRuppoc Rockjumper says 'You cleared out a bunch of those terror guards? Thanks! Maybe now I can sneak in to look for some more moss!'\n_Rewards:_\nExperience (about 1 AA worth)\nMinor Faction with Dream Delvers\n- Heroic Rockomancy Diamond [Heal Amount: +3]\n- Heroic Rockomancy Diamond [STA: +3]\n- Heroic Rockomancy Diamond [AC: 30, AGI: +3]\n- Heroic Rockomancy Diamond [AC:20, STR: +3]\n- Heroic Rockomancy Diamond [Spell Damage: +3]",
    },
    {
      id = "5151",
      title = "Thinning Out Their Numbers: Terror Spinners and Sleeper Cubes",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Ruppoc Rockjumper",
      loc = nil,
      triggers = {
        "Hail, Ruppoc Rockjumper",
        "Tell me about that something you found...",
        "What problem?",
        "I",
        "I could thin their numbers",
        "Terror spinners and sleeping cubes",
        "_Quests_",
        "found",
      },
      items_required = {
        { name = "me the creeps! Thanks for thinning them out", count = 1 },
      },
      rewards = {
        { id = 122721, name = "Heroic Echoing Shriek", type = "item" },
        { id = 125867, name = "Heroic Echoing Shriek", type = "item" },
        { id = 116768, name = "Heroic Echoing Shriek", type = "item" },
        { id = 118325, name = "Heroic Echoing Shriek", type = "item" },
        { id = 128049, name = "Heroic Echoing Shriek", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- House of Thule, Lower Floors [zone=748]\n**Who:**\n- Ruppoc Rockjumper [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +5\n**Factions Lowered:**\n**Related Creatures:**\n- a fright spinner [npc=35746]\n- a sleeper cube [npc=35779]\n- a terror spinner [npc=35768]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Oct 25 20:34:58 2010\nModified: Tue Jan 26 19:49:11 2021 | | _This is one of five solo kill tasks that are offered by a froglok named Ruppoc Rockjumper at the zone-in of the House of Thule (lower floors)._\nYou say, 'Hail, Ruppoc Rockjumper'\nRuppoc Rockjumper says 'Hey, are you looking for mushrooms and moss to eat too? You're not? Well let me tell you about something I [found] anyway.'\nYou say, 'Tell me about that something you found...'\nRuppoc Rockjumper says 'I was walking through the jungle the other day, looking for some delectable moss and mushrooms for dinner, when I came across this gate you passed through. It just appeared one day. I thought that was strange, so I came inside to check it out. It is a treasure trove of delicious but strange-looking moss! There is one [problem] though.'\nYou say, 'What problem?'\nRuppoc Rockjumper says 'This place is crawling with nightmarish creatures. I managed to sneak around a bit, gathering a few samples of the delicious moss that grows in here, but the monsters eventually spotted me, and I had to flee back to the gate. I really want more of that moss. Think you could [help] me out?'\nYou say, 'I'll help you out'\nRuppoc Rockjumper says 'I can't get any more of that moss with all these critters in here. Do you think you could [thin] their numbers out a bit?'\nYou say, 'I could thin their numbers'\nRuppoc Rockjumper says 'You are too kind! What would you like to kill? [rot dogs] and [snakes], [skeletons] and [bone golems], [terror guards], [terror spinners] and [sleeper cubes], or [bone crafters] and [quaking haunts]?'\nYou say, 'Terror spinners and sleeping cubes'\nRuppoc Rockjumper says 'You want to defeat some of the terror spinners and sleeper cubes? I hate spiders, and don't even get me started with goos! Please take care when dealing with them! They both roam around inside the house.'\nYou have been assigned the task 'Thinning Out Their Numbers: Terror Spinners and Sleeper Cubes'.\n\n---\n\nKill 2 spinners 0/2 (House of Thule)\nKill 4 cubes 0/4 (House of Thule)\nReport to Ruppoc Rockjumper 0/1 (House of Thule)\nYou say, 'Hail, Ruppoc Rockjumper'\nRuppoc Rockjumper says 'You killed some of those horrible terror spinners and sleeper cubes? They sure do give me the creeps! Thanks for thinning them out.'\n_Rewards:_\nExperience (about 1 AA worth)\nMinor Faction with Dream Delvers\n- Heroic Echoing Shriek [item=122721]\n- Heroic Echoing Shriek [item=125867]\n- Heroic Echoing Shriek [item=116768]\n- Heroic Echoing Shriek [item=118325]\n- Heroic Echoing Shriek [item=128049]",
    },
    {
      id = "5197",
      title = "Morzad Chronicle - Argan's Memoir (\\#1)",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Abbit Scribbletch",
      loc = nil,
      triggers = {
        "Hail, Abbit Scribbletch",
        "What happened?",
        "Who are the Morzad?",
        "Who",
        "I",
        "Hail, Keega",
        "Abbit sent me...",
        "Hail, Khalis",
      },
      items_required = {
        { name = "you the book", count = 1 },
      },
      rewards = {
        { id = 92742, name = "Argan's Memoir", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- House of Thule, Upper Floors [zone=753]\n**Who:**\n- Abbit Scribbletch [ _Quest_]\nRating:\n0/2**_\\*__\\*__\\*__\\*__\\*_**\n(Average from 2 ratings)\nInformation:\n**Level:** | 90\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Faction\n- Money\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Quest Items:**\n- Argan's Memoir [item=92742]\n**Related Creatures:**\n- Keega [npc=36297]\n- Khalis [npc=36314]\n- a protective imp [npc=36313]\n**Related Quests:**\n- Morzad Chronicle - Abbit's Betrayal (#2) [quest=5198]\n- Morzad Chronicle - Dead or Alive or Other (#4) [quest=5200]\n- Morzad Chronicle - Never Trust a Morzad (#3) [quest=5199]\n- Morzad Chronicle - The Morzad Confrontation (#5) [quest=5201]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Nov 8 23:31:00 2010\nModified: Sat Oct 22 20:55:41 2011 | | _This task is the first in a series of five that begins with Abbit Scribbletch, a gnome found in the first room on the left immediately on entering the northeastern wing of the House of Thule's Upper Floors._\nYou say, 'Hail, Abbit Scribbletch'\nAbbit Scribbletch says 'I cannot believe this has [happened]. I should know better than to trust a source with whom I do not normally deal with. But I was so close!'\nYou say, 'What happened?'\nAbbit Scribbletch says 'I am a collector, of many things, but books are my main passion. I was so close, or so I thought, to finding the lost memoirs of the [Morzad] leader Argan. '\nYou say, 'Who are the Morzad?'\nAbbit Scribbletch says 'It makes sense that you've never heard of the Morzad. They were an underground group of explorers and archeologists who sought powerful relics in order to gain more power for themselves. No one really knew to what end. The Morzad were thought to have vanished after [Argan] was killed by Cazic Thule himself.'\nYou say, 'Who's Argan?'\nAbbit Scribbletch says 'I was getting to that! Argan made note of every relic the Morzad ever found and kept in a book along with its location. The book has come to be known as Argan's Memoir. This is why I am here. I thought I had good information that the book was here, but as soon as I arrived, I have been plagued by attackers. I am a collector, not a combatant! And now I am stuck here it seems. Will you [help] me?'\nYou say, 'I'll help you'\nAbbit Scribbletch says 'Excellent! I was to meet someone named Keega here. You must find him and talk to him in my stead. But you must hurry. I am sure he has been waiting for me, but I have been unable to move. '\nYou have been assigned the task 'Morzad Chronicle - Argan's Memoir'.\nAbbit Scribbletch is stuck here while looking for Argan's Memoir. He has asked for your help in meeting the one who knows where the book can be found.\n\n---\n\nSpeak to Keega 0/1 (House of Thule, Upper Floors)\n_Keega is an Erudite found in the first hall of the northwestern wing._\nYou say, 'Hail, Keega'\nKeega says 'You are not [Abbit]!'\nYou say, 'Abbit sent me...'\nKeega says 'Very well... The book he seeks is being held by an imp who calls himself Khalis. He is especially annoying. But it shouldn't take much to get the book from him. He seems to not know, or care, what it is.'\nKill 2 protective imps 0/2 (House of Thule, Upper Floors)\n_To get to Khalis and his protective imps, keep going through the northwestern wing until you come to the rotdog room. From there, go south and through that hall to Khalis' room._\n_Note: The protective imps used to be triggered spawns by hailing Keega. A patch changed them to regular spawns, so they'll always be up next to Khalis (unless someone's very recently killed them)._\n_Khalis is not aggro, but the imps are as well as a number of undead in the room. They each hit for a max ~6,500._\na protective imp says 'I will pry those pretty little eyes from your skull and feast like a king upon your every fleshy nerve!'\na protective imp has been slain by \\_\\_\\_\\_\\_!\na protective imp's corpse says 'Oops! Back to The Faceless I go. I'll be back, and your eyes will be mine!'\nSpeak to Khalis 0/1 (House of Thule, Upper Floors)\nYou say, 'Hail, Khalis'\nKhalis says 'What have we here? How do I know? Quiet, let me talk! What book? You know what book! Ah, that book! I will give you the book. But first, you must answer something for me. What can burn but is not fire, and has a way of destroying rationality? '\nAnswer Khalis' riddle 0/1 (House of Thule, Upper Floors)\nYou say, 'Hate'\nKhalis says 'Correct! I don't get it? Hush! It was too easy! You have answered correctly, so here is the book.'\n_You receive Argan's Memoir._\nDeliver Argan's Memoir to Abbit Scribbletch 0/1 (House of Thule, Upper Floors)\n_On hand-in:_\nYour task 'Morzad Chronicle - Argan's Memoir' has been updated.\nAbbit Scribbletch says 'I cannot believe you retrieved it, and so easily! Thank you.'\nYou have found the book that in which Abbit was looking.\nYour faction standing with Dream Delvers got better.\n_Rewards:_\n158 platinum\nExperience\nFaction with Dream Delvers\n15 Dream Motes\n- Dream Mote [item=90255]",
    },
    {
      id = "5198",
      title = "Morzad Chronicle - Abbit's Betrayal (\\#2)",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Abbit Scribbletch",
      loc = nil,
      triggers = {
        "Hail, Abbit Scribbletch",
        "Fake?",
        "Hail, Keega",
        "Hail, Agent of Morzad",
        "_Quest_",
        "fake",
      },
      items_required = {
      },
      rewards = {
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- House of Thule, Upper Floors [zone=753]\n**Who:**\n- Abbit Scribbletch [ _Quest_]\nRating:\n0/2**_\\*__\\*__\\*__\\*__\\*_**\n(Average from 2 ratings)\nInformation:\n**Level:** | 90\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Faction\n- Money\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Creatures:**\n- Agent of Morzad [npc=36309]\n- Keega [npc=36297]\n- Morzad Agent [npc=36577]\n- Swindler Keega [npc=36579]\n**Related Quests:**\n- Morzad Chronicle - Argan's Memoir (#1) [quest=5197]\n- Morzad Chronicle - Dead or Alive or Other (#4) [quest=5200]\n- Morzad Chronicle - Never Trust a Morzad (#3) [quest=5199]\n- Morzad Chronicle - The Morzad Confrontation (#5) [quest=5201]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Mon Nov 8 23:31:06 2010\nModified: Tue Mar 22 23:02:53 2011 | | _This task is the second in a series of five that begins with Abbit Scribbletch, a gnome found in the first room on the left immediately on entering the northeastern wing of the House of Thule's Upper Floors._\n_You must have completed his first task prior to being able to request this one._\nYou say, 'Hail, Abbit Scribbletch'\nAbbit Scribbletch says 'Unbelievable! The book is a [fake]!'\nYou say, 'Fake?'\nAbbit Scribbletch says 'Yes! You must find Keega and find out what in Norrath is going on!'\nYou have been assigned the task 'Morzad Chronicle - Abbit's Betrayal'.\nAbbit Scribbletch is angry over Keega's betrayal. You must help him find out where the real memoir is located.\n\n---\n\nSpeak to Keega 0/1 (House of Thule, Upper Floors)\nYou say, 'Hail, Keega'\nKeega says 'You are in over your head!'\n_Keega respawns as Swindler Keega and attacks. He hits for a max ~7,200._\nDefeat the Swindler Keega! 0/1 (House of Thule, Upper Floors)\nSwindler Keega has been slain by \\_\\_\\_\\_\\_!\nSpeak to Keega 0/1 (House of Thule, Upper Floors)\nYou say, 'Hail, Keega'\nKeega says 'Enough... It is not my fault. An agent of the Morzad contacted me while back. I was to lure that Abbit fellow here, and then make sure he got the fake copy of the book! I am sure he is still here in the northeastern wing.'\nSpeak to Agent of Morzad 0/1 (House of Thule, Upper Floors)\n_A Dwarf called \"Agent of Morzad\" spawns in the far northeast part of the zone. He's in a room alongside the Morzad Watercaster (for a later task) and some undead._\n_NOTE: An ambush spawns right after you hail him. You can do this hail while invis as the ambushers do not see invisibility._\nYou say, 'Hail, Agent of Morzad'\nAgent of Morzad says 'That fool, Keega! I knew he could not be trusted! I am not sure what you hope to gain. I have nothing to say to you.'\n_Three Morzad Agents spawn around the room and attack. They don't see invisibility. They each hit for a max ~6,500 and are susceptible to most forms of crowd control: mezzable, rootable/snareable, and stunnable._\nDefend yourself from the Morzad ambush 0/3 (House of Thule, Upper Floors)\n_Note: The spawned Agents only stay up for a certain period of time (it's several minutes). If you wipe out and they despawn, you have to start the task from the beginning._\nSpeak to Abbit Scribbletch 0/1 (House of Thule, Upper Floors)\nYou say, 'Hail, Abbit Scribbletch'\nAbbit Scribbletch says 'I cannot believe they thought they could fool me with that counterfeit book! Thank you for all you have done for me so far. When you return, if you should return, I may have another contact from who we may get some answers.'\nYou have discovered that Keega was working for the Morzad. The books location is still in question.\nYour faction standing with Dream Delvers got better.\n_Rewards:_\n220 platinum\nExperience\nFaction with Dream Delvers\n20 Dream Motes\n- Dream Mote [item=90255]",
    },
    {
      id = "5204",
      title = "Of Ice and Men",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Karivei Skyflare",
      loc = nil,
      triggers = {
        "Hail, Karivei Skyflare",
        "Examine the elements?",
        "Entails...?",
        "Ice?",
        "I",
        "_Quests_",
        "examine the elements",
        "entails",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- House of Thule, Upper Floors [zone=753]\n**Who:**\n- Karivei Skyflare [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 90\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Creatures:**\n- a nightmarish beast [npc=36290]\n- a soul devourer [npc=36289]\n- an iceworn guardian [npc=36296]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 9 22:06:58 2010\nModified: Tue Nov 9 22:12:28 2010 | | _This is a solo kill task that begins with Karivei Skyflare in the House of Thule's Upper Floors (located at the western zone-in)._\nYou say, 'Hail, Karivei Skyflare'\nKarivei Skyflare says 'Vasha. Are you also here to [examine the elements] who have taken residence in the House? '\nYou say, 'Examine the elements?'\nKarivei Skyflare says 'I was promised a group of adventurers, but clearly they've yet to arrive. I can only hope you'll all be suitable replacements.' She smugly grins back at \\_\\_\\_\\_\\_. 'I hope you know what all this [entails].'\nYou say, 'Entails...?'\nKarivei Skyflare says 'There are two particular sets of element-based life forms about the second floor. While I know many of them are not elementals, their life still seems to be drawn by the elements they enhabit: [fire] and [ice].'\nYou say, 'Ice?'\nKarivei Skyflare says 'These certainly don't appear to be of the elements, directly, but their existance alone and how they seem to have sprung up with the magical ice that inhabits those halls is something to [investigate], if you're willing.'\nYou say, 'I'll investigate'\nKarivei Skyflare says 'Karui, slaughter a few and get back to me on your understanding of them. And quickly, because I'm not the most patient.'\nYou have been assigned the task 'Of Ice and Men'.\nKarivei Skyflare has been awaiting a group of hired adventurers for assistance in his research, but they have yet to arrive. She has taken you on as a replacement, requesting that you kill and research the elements of ice and frost as they are manifest in the house.\n\n---\n\nKill nightmarish beasts for research 0/6 (House of Thule, Upper Floors)\nKill soul devourers for research 0/2 (House of Thule, Upper Floors)\nKill iceworn guardians for research 0/2 (House of Thule, Upper Floors)\n_The above mobs are all confined to the southwestern wing of the zone._\nReport your findings back to Karivei 0/1 (House of Thule, Upper Floors)\nYou say, 'Hail, Karivei Skyflare'\nKarivei Skyflare hears your report on the ice creatures of the second floor and jotting down the details you've supplied, she nods his head in thanks.\n_Rewards:_\nExperience _(around 1 AA worth at Level 90)_\nMinor Faction with Dream Delvers",
    },
    {
      id = "5205",
      title = "Spirit Bound",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Andre MacDonnal",
      loc = nil,
      triggers = {
        "Hail, Andre MacDonnal",
        "What first step?",
        "What denizens?",
        "What something would that be?",
        "I",
        "first step",
        "denizens",
        "something",
      },
      items_required = {
        { name = "will help this old shaman", count = 1 },
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- House of Thule, Upper Floors [zone=753]\n**Who:**\n- Andre MacDonnal [npc=36303]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 90\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Creatures:**\n- a cheerless apparition [npc=36293]\n- a ghostly vision [npc=36273]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 9 22:07:02 2010\nModified: Tue Nov 9 22:12:36 2010 | | _This is a solo kill task that begins with Andre MacDonnal in the House of Thule's Upper Floors (located at the eastern zone-in)._\nYou say, 'Hail, Andre MacDonnal'\nAndre MacDonnal sleepily looks up. 'Hail and well met, \\_\\_\\_\\_\\_. I've been trying to get back to the waking world through sleep, but it doesn't seem to help. At least I believe I hit the [first step] by being aware that I'm dreaming, wouldn't you say?'\nYou say, 'What first step?'\nAndre MacDonnal nods. 'You know, I'd get out of here before you're stuck, too. I'm pretty sure the denizens about would be detrimental to you in the waking world should they find you here. Death here may very well be permanant. I almost wonder if some of the [denizens] here may be the result of that exact thing.'\nYou say, 'What denizens?'\nAndre MacDonnal says 'Well, many of the undead share similarities with the spirit world, so I'm unsure if they were trapped here through death, or if they are too stuck in a dream state. In that respect, would you mind doing [something] for me?'\nYou say, 'What something would that be?'\nAndre MacDonnal says 'Would you [engage] some of the undead in battle and report to me on their behavior? I am curious as to what their true manifestation is, and any behavioral analysis you can give will help this old shaman.'\nYou say, 'I'll engage them...'\nAndre MacDonnal nods approvingly, a smile flashing. 'Many thanks, \\_\\_\\_\\_\\_. Report back to me soon, and good luck.'\nYou have been assigned the task 'Spirit Bound'.\nThe shaman Andre MacDonnal is aware he's in a dream state that he's attempting to shake. However, in the meantime, he's not quite sure the state of the spiritual manifestations on the second floor. Curious, he's asked for information on how they behave in battle and death, seeking your assistance.\n\n---\n\nEngage and kill several ghostly visions 0/4 (House of Thule, Upper Floors)\nEngage and kill cheerless apparitions 0/5 (House of Thule, Upper Floors)\n_These mobs are found in many areas throughout the zone._\nHail Andre MacDonnal 0/1 (House of Thule, Upper Floors)\nYou say, 'Hail, Andre MacDonnal'\nAndre MacDonnal looks up in worry. 'You mean to say that they appear to have become trapped through their dreams and nightmares and that is why they wander as spirits so? This is troubling and makes our predicament even more precarious. ...Thank you for looking into it.'\n_Rewards:_\nExperience _(around 1 AA worth at Level 90)_\nMinor Faction with Dream Delvers",
    },
    {
      id = "5216",
      title = "Catastrophic Power",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Elard Velsorn",
      loc = nil,
      triggers = {
        "Hail, Elard Velsorn",
        "Power over me?",
        "What beings?",
        "His sleep?",
        "I",
        "Hail, Dreezil Stickens, Pocketdip",
        "Fighting back?",
        "What happened?",
      },
      items_required = {
      },
      rewards = {
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- House of Thule, Upper Floors [zone=753]\n**Who:**\n- Elard Velsorn [npc=36299]\nRating:\n0/2**_\\*__\\*__\\*__\\*__\\*_**\n(Average from 2 ratings)\nInformation:\n**Level:** | 90\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Faction\n- Loot\n- Money\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Zones:**\n- Al'Kabor's Nightmare: Catastrophic Power [zone=775]\n**Related Creatures:**\n- Al`Kabor [npc=36733]\n- Dreezil Stickens, Pocketdip [npc=36729]\n- an angry beetle [npc=36731]\n- an angry snake [npc=36730]\n- an angry wasp - Al'Kabor's Nightmare [npc=36732]\n- an ornate chest - Catastrophic Power [npc=36728]\n**Related Quests:**\n- Faydark's Shadow [quest=5210]\n- The Rivervale Ruins [quest=5208]\n- Wastelands of Everfrost [quest=5209]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Thu Nov 11 22:54:36 2010\nModified: Sun Apr 14 07:05:23 2013 | | _This is a group progression task that begins with Elard Velsorn in the upper floors of the House of Thule (just outside the zone-in to Al'Kabor's Nightmare)._\n_You must have completed the Al'Kabor tasks \"The Rivervale Ruins\", \"Wastelands of Everfrost\", and \"Faydark's Shadow\" in order to request this task._\n_Note: The Well mission \"What Lies Below\" also used to be required. However, a patch on December 8, 2010, eliminated this requirement._\nYou say, 'Hail, Elard Velsorn'\nElard Velsorn says 'You traverse these halls with ease and purpose, unlike many of the denizens I see wandering about mindlessly. Tell me, does the house not hold [power] over you?'\nYou say, 'Power over me?'\nElard Velsorn says 'It seems some of the most powerful [beings] have been held captive by their dreams while here in this house. It's a curious thing, to be certain.'\nYou say, 'What beings?'\nElard Velsorn says 'I came here, trailing the infamous wizard, Al`Kabor. I've always had my suspicions about his abilities, but the fact that the house chose to ensnare him in [sleep] must mean there is more to him than he lets on.'\nYou say, 'His sleep?'\nElard Velsorn says 'He rests, rather tumultuously. I'm immensely curious what plagues his mind. Those who are able to [enter] his dreams might gain insight into the true nature of Al`kabor and see a side that he seems to keep hidden from the waking world.'\nYou say, 'I'll enter the dreams...'\nElard Velsorn says '[Proceed] with caution and a keen eye, \\_\\_\\_\\_\\_.'\nYou have been assigned the task 'Catastrophic Power'.\nYou have entered the dreams of the infamous wizard, Al'Kabor, and have been tasked with discovering what troubles him in his sleep.\n_Say \"proceed\" to zone into the instance._\n\n---\n\n_Mobs in this task hit for a max ~7,000 and are all mezzable. All but the ice giants are stunnable. None are linked to each other, so they can all be split. None see invisibility, so you can set up wherever you'd like._\nInvestigate the source of the screams 0/1 (Al'Kabor's Nightmare)\nOh, please! Will someone help get these critters away from me?!\nShoo, pests! Shoo!\n_A little ways east from the zone-in, you'll find Dreezil in a ruined hut with three angry snakes nearby._\nDefend Dreezil from the angry snakes 0/3 (Al'Kabor's Nightmare)\nDefend Dreezil from the angry beetles 0/3 (Al'Kabor's Nightmare)\n_Note: Once the snakes are dead, someone has to move to Dreezil's location in order to activate the beetles. The same goes for the wasps in the next step._\nDefend Dreezil from the angry wasps 0/3 (Al'Kabor's Nightmare)\nSpeak to Dreezil 0/1 (Al'Kabor's Nightmare)\nYou say, 'Hail, Dreezil Stickens, Pocketdip'\nDreezil Stickens, Pocketdip says 'Well hello there, \\_\\_\\_\\_\\_. Welcome to the end of the world, and many thanks for saving my hide. I'm not sure how long I would have made it if you hadn't of shown up. Of course I've always said that as long as you're alive there's no point in giving up. You can stop [fighting back] once you're dead.'\nYou say, 'Fighting back?'\nDreezil Stickens, Pocketdip says 'Ah, well, not much that I can see to do to make things better. I mean, heck, everything just blew up.' The halfling's voice changes slightly for a moment, 'I'm too ignorant and stupid to know when I'm in trouble over my diminutive head.' Then he continues in his normal voice, not missing a beat or appearing to notice what just happened. 'I suppose there's enough food for now, though the deputies are having trouble. I just wish I knew [what happened].'\nYou say, 'What happened?'\nDreezil Stickens, Pocketdip says 'I really don't know. I can't even remember anything before this happened. Whatever it was must have caused me to black out, and I woke up locked up in the wall guard tower. All the guards I talked to remember, or, well, don't remember it the same way. It's like the whole world shut off and restarted with a huge [explosion].'\nYou say, 'An explosion?'\nDreezil Stickens, Pocketdip says 'Shattered the world, I figure. The real problem is that the only place that I can see that might have something tasty to drink is floating just out of reach. I suppose we could try [jumpin'] over to the next hunk of rock. Looks a lot like Everfrost to me. But then I'm not a fan of water, especially the frozen kind.'\nYou say, 'Jumpin'?'\nDreezil Stickens, Pocketdip says 'I was just kidding! Don't do that, you'd never make it. I know a trick, though. If you really need to get over there, all you have to do is let me know and I'll help you get to the chunk of all that's left of [Everfrost]. But I can't help feeling that there's something missing, something I need to do, or need you to do.'\n_Say \"Everfrost\" to him to port over._\nSeek out Dagda Icefury on the Everfrost island 0/1 (Al'Kabor's Nightmare)\n_Dagda Icefury is found outside a building in the northeastern part of the island._\nYou say, 'Hail, Dagda Icefury'\nDagda Icefury says 'Hello. Move aside, I need a clear field of vision. It's ridiculous that all these icy jerks survived the end of the world and so few of my kin did. I can't hold this place forever. Sooner or later I'll fall, and so will my [friends]. I can't allow that.'\nYou say, 'Your friends?'\nDagda Icefury says 'Ognit appears to have been injured in the... the whatever it was. Dabner thinks that he's physically fine, but that he's just being stubborn and refusing to regain consciousness. That seems crazy to me, but then Dabner's the healer, not me. I'm the [killer].'\nYou say, 'The killer?'\nDagda Icefury says 'I guess it takes the end of everything to force me to recognize who I really am. I've spent my life killing people to protect people that I care about. How righteous and proud I was, thinking that my strength made me and mine worthy and other people not.' As she speaks her eyes glint for a moment and a shadow seems to pass across her face. 'All I have left now are these two. Trouble makers for sure, but friends nonetheless. If we had [Ognit] we might be able to survive the next assault. There can't be an infinite number of those Marr-cursed giants.'\nYou say, 'Ognit?'\nDagda Icefury says 'Aye, Ognit. He doesn't look like much, but he's a very powerful wizard. But then, perhaps you could help. It seems to me that you have more reason to help me than to help the wretched ice giants. Stay here and help me defend my friends. Obviously I can't offer you any reward, other than my assistance in defeating them. After all, we're some of the last people alive, and those giants would kill you as readily as they would kill me and my friends. Will you [stay] and help defend them?'\nYou say, 'I'll stay'\nDagda Icefury says 'Thank you. I doubt it will be long before they decide to attack us, so prepare yourselves. I'll stay here and guard Dabner and Ognit, if you can fend off the ice giants.'\n_The nearby ice giants (previously unaggro) all converge on the tower. There are six of them. They're mezzable, but not stunnable, and can be split from one another._\nDefend Dagda and her friends from the ice giants 0/6 (Al'Kabor's Nightmare)\nSpeak to Dagda 0/1 (Al'Kabor's Nightmare)\nYou say, 'Hail, Dagda Icefury'\nDagda Icefury says 'Thank you for your help. I don't know if you understand how important it is for me to have friends here at the end of all things. It's almost like I'd be hollow without them. Perhaps now with the giants dead we can think about helping those left. I've seen movement on the green chunk of land, but can't tell who or what it was. It certainly looks like [Kelethin] from here, though.'\nYou say, 'Kelethin?'\nDagda Icefury says 'I never had the sharpest eyes, but I'm fairly certain the rubble to the east is from Kelethin. I can't leave here until Ognit is better, but maybe Dabner can get you there to help out any survivors.'\nSpeak to Dabner 0/1 (Al'Kabor's Nightmare)\n_Dabner and Ognit are inside the building._\nYou say, 'Hail, Dabner Drednever'\nDabner Drednever says 'Hello. I'm sorry for being rude earlier, but you've saved Dagda's life, and I appreciate that. Certainly she would have gotten herself killed if you weren't here. She was talking about hiding us someplace and going out to distract the ice giants. Some fool idea about making a defensive stand at one of the edges and making it look like we fell off before she dies fighting them. Foolish. I think that girl would be happiest if she could die saving someone, the only trouble is that she's too skilled to die and too worried that we wouldn't be able to get along without her. And we probably wouldn't. No doubt [Ognit] here would have met his fate a long time ago.'\nYou say, 'Ognit?'\nDabner Drednever says 'The great Ognit Eznertob. Bah. He thinks himself the greatest wizard ever, and the greatest tinker. But he's blown up more copper contraptions than I could count. Oh, no doubt he's powerful... why you should have seen the contraption he created once while trying to make a heater for these barbarians! No doubt if Dagda hadn't smashed the thing it would have killed half the population of Halas. But he's no Solist, no Porlo. He's certainly not as powerful as... Odd, I... Well, anyway, he's my best friend, so that's enough for me. If only he'd [listen] to me.'\nYou say, 'He won't listen to you?'\nDabner Drednever says 'He never listens to me, but now he really needs to. He's in there trying to will himself dead. I don't know why, but I'm sure that's what's going on. It's almost as if... No, it can't be.' Ognit turns to Dabner with a thoughtful expression on his face. 'You always did have a magnificently powerful ability to overestimate yourself.''\nDabner Drednever shouts, 'You are not responsible for this! Ognit, you fool, you DID NOT blow up the world! This is not your fault!'\nOgnit Eznertob stirs a bit and begins to murmur, 'Exploded. Everything exploded. Must have been me, only me.' Then in a stronger, oddly accented voice, 'I've always been foolish and free with my power. My irresponsibility was dangerous and stupid.' Immediately after speaking, Ognit falls still once again.\nDabner Drednever says 'He obviously isn't going to listen, but I'll get through eventually. Let me see if I can get you to [Kelethin].'\nYour task 'Catastrophic Power' has been updated.\nYou see, 'Get me to Kelethin...'\nDabner Drednever says 'Good luck, and thank you.'\nSeek out Firiona Vie on the Faydark island 0/1 (Al'Kabor's Nightmare)\n_Firiona Vie is found in the southeastern part of the island, overlooking the Dreadlands._\nYou say, 'Hail, Firiona Vie'\nFiriona Vie says 'Hello, \\_\\_\\_\\_\\_. I am glad to find others alive in this horrible world. As I stare out over the edge of existence I wonder [how] it is that this came to be. I doubt that I'll ever know, and I'm afraid all hope has been lost.'\nYou say, 'How?'\nFiriona Vie says 'The only person that might know is Sionachie. She's very smart. I'm certain she could help us if only there weren't so many nasty Orcs trying to kill us.'\nSpeak to Sionachie 0/1 (Al'Kabor's Nightmare)\n_Sionachie is found within the ruins of Felwithe (in a tunnel just inside the front gate)._\nYou say, 'Hail, Sionachie Heartsinger'\nSionachie Heartsinger smiles wanly, 'Hello,' she shakes her head, 'it's hard to believe that we few are the last people alive. I mean, sure, it seems that someone would probably be here if we were not, but why us? I can't help but think, why am I alive? [What does it mean]?\nYou say, 'What does it mean?'\nSionachie Heartsinger says 'I really don't know. But if Dreezil, Dagda and the others are still alive, along with the four of us here, that must mean something. Sure, we're all seasoned adventurers, but there were many seasoned adventurers.' Sionachie sighs deeply. 'I'd set off and seek answers, but I cannot leave Felwithe in such a state. [Orcs] have invaded her walls.''\nYou say, 'Orcs?'\nSionachie Heartsinger says 'I suppose they struggle like us, lone survivors living in ruins, fighting for the last square mile of land. Firiona has given up the fight, but I will not let what's left of Felwithe fall. Together we can vanquish the Orcs, and find answers to the questions that plague my mind.'\nClear Felwithe's ruins of the orc invaders 0/6 (Al'Kabor's Nightmare)\n_Orc invaders can be found wandering throughout Felwithe's ruins._\nReturn to Sionachie 0/1 (Al'Kabor's Nightmare)\nYou say, 'Hail, Sionachie Heartsinger'\nSionachie Heartsinger says 'The ruins of Felwithe have been reclaimed; you have my thanks, \\_\\_\\_\\_\\_. I'm afraid my [questions] still linger.'\nYou say, 'Questions?'\nSionachie Heartsinger says 'Questions, always questions. Rarely answers. I suppose if I can live long enough I might figure it out. There's something nagging in the back of my head trying to tell me the answer, but I'm apparently not ready to hear it.' She tilts her head, 'You've been to several of the remaining chunks of the world. Perhaps if I sent you to the chunk that appears to be the remnants of the Dreadlands you will be able to find the [answer].'\nYou say, 'What's the answer?'\nSionachie Heartsinger says 'I can't help but think that there is one. Dreadlands is certainly a place of power. I will send you there if you wish. I'm not at all certain how knowing why the world ended will help me accept it, but I'm sure it will. I can send you to the [Dreadlands] chunk whenever you are ready.'\nYou say, 'Send me to the Dreadlands'\nSionachie Heartsinger says 'Stay safe, \\_\\_\\_\\_\\_. I will meet you in what remains of the Dreadlands as soon as I can, and together, we will uncover the truth.'\nConfront Al'Kabor in the Dreadlands isle 0/1 (Al'Kabor's Nightmare)\n_NOTE: Sionachie despawns once you hail Al`Kabor (no one else will be able to port up to the Dreadlands isle)._\nYou say, 'Hail, Al`Kabor'\nAl`Kabor says 'Who are you? You don't belong here. You should be dead like the rest of them. Go away. The world is over. You're dead. The world is dead. And I have finally achieved eternal life. The irony is not lost on me. So, what happens now? Do my 'companions' have anything else to say to me, or shall we just stare at each other for a while longer?'\nSionachie Heartsinger shouts 'I see now, I finally understand. You think you blew up the world. You think that your great power is responsible for this. In your arrogance you've created this fantasy... no, this nightmare. The all-powerful Al'Kabor, learner of secrets and the greatest living wizard, and you needed your companions to show you the truth, to save you from your own fears.'\nSionachie Heartsinger shouts 'It was Dreezil that always gave us hope, and hope is what you needed. You needed him to tell you that even though you made a terrible mistake, somehow it would be fine. You needed him to tell you that things would get better.'\nSionachie Heartsinger shouts 'In Ognit and Dabner you saw a reflection of what you believed you had done. Those two were always getting in trouble, and yet they usually made it through unscathed. You used to call them fools, but never yourself. You thought that if those fools could recover from their mistakes, then so could you.'\nSionachie Heartsinger shouts 'Dagda. Strong and faithful Dagda. She never gave up. She never let her friends down and was always our protector. But that wasn't what you needed from her, was it? No, you never needed help or protection. From her you needed the undying faith and love she had for those she called friends. You needed someone to love you despite what you'd done.'\nSionachie Heartsinger shouts 'Firiona had nothing for you, did she? She was ever out of reach of your understanding. Her motivations never made sense to you, since nobility didn't exist in any part of you. So why Felwithe? Why Kelethin? Why were they not destroyed along with the rest of the world?'\nSionachie Heartsinger shouts 'Of course, I see it now! It was me. You thought of me as a fellow seeker of knowledge. I was the only one that had a chance to understand something that you couldn't grasp. And of course the thing you could never understand was yourself. After all, how can you have a true nightmare without coming to understand some horrible truth about yourself?'\nSionachie Heartsinger shouts 'Here's the truth of it. You've spent your life reaching for a goal that you believe should be in your reach and you've been frustrated. Others have done it, others with lesser power perhaps. But those were people that never had what you had. Each of them was willing to cast aside everything for their goal, but you can't. You have friends. Not just that, but you value them, despite your self-delusions to the contrary.'\nSionachie Heartsinger shouts 'Well, you've done it now. In this place you have allowed your friends to perish. Not by your actions but by your inaction. So now you have nothing. Nothing to gain and nothing to lose. Only now can you achieve your heart's desire. Now you may live forever. Into eternity you go, taking nothing with you.'\nAl`Kabor shouts 'Aaaaarrrr!' The once living Erudite uncurls from the racking pain of his transformation and looks about. 'So, I am completely alone, am I? Of course, you are correct. And if you are correct, then you can't really be here either, Sionachie.''\nAl`Kabor shouts 'Clever child, Sionachie. Of course, she was only clever because she was a product of my imagination, a manifestation of my power in her image. She claims that this is a dream or nightmare. I know this to be the truth. For decades I have withheld my true power. I've rightfully feared what might happen if I used all of my might, focused myself on one end. All of this came about because I grew weary of waiting for the perfect time and place to enact my plan to become immortal.'\nAl`Kabor shouts 'And so I have destroyed Norrath. It seems that only you and I remain. Perhaps now I can teach a few of you my true magics? The petty magic that I have taught to others over the years pales in comparison to my real strength!'\nAl`Kabor shouts 'Sionachie was terribly wrong. A nightmare this may be, but this is also reality. I have destroyed the world so that I might live forever. I wish it were not so, but it is. The proof lies all around you. The sadness in this all is that now that I've finally become immortal, I wish that I could die.'\nAl`Kabor writhes with anguish as his gaze falls upon you.\n_Al'Kabor attacks. He hits for a max (???) and casts a few AEs:_\nAbolishing Flames: PB AE 500', Fire (-700)\n1: Decrease Hitpoints by 9000 per tick\n2: Increase Curse Counter by 50\nBone Chill: Single Target, Cold (-700)\n1: Decrease HP when cast by 37000\n2: Illusion: Skeleton\nDefeat Al'Kabor 0/1 (Al'Kabor's Nightmare)\n_Note: The task locks upon Al'Kabor's death._\nAl`Kabor has been slain by \\_\\_\\_\\_\\_!\nAl`Kabor's corpse falls to the ground, sending a surge of magical energy through the air.\nClaim your reward from the ornate chest 0/1 (Al'Kabor's Nightmare)\nYou have defeated the arrogant wizard, Al`Kabor, and proven to all that he is not quite as powerful as he boasts.\n\n---\n\n_Task Rewards:_\nExperience\n262 platinum\n50 Dream Motes\nFaction with Dream Delvers\n_Known chest rewards (1 item + 1 spell per task):_\nArgendev's Shroud\nHeadcracker\nInsania Stone\nLeather Gloves of Overkill\nMagical Lint\nMammoth Bone Bow\nMooto's Stone\nPatriarch's Bone Earring\nSpectral Bloodsword\nVile Tormentor Skin\nMinor Nebulous Dream Fragment\nLesser Nebulous Dream Fragment\nMedian Nebulous Dream Fragment\nGreater Nebulous Dream Fragment\nGlowing Nebulous Dream Fragment\n- Dream Mote [item=90255]",
    },
  },
}
