-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Thurgadina (thurgadina)
-- Total Quests: 12
-- ============================================================================

return {
  zone = "thurgadina",
  zone_name = "Thurgadina",
  quests = {
    {
      id = "8299",
      title = "Cleric Thurgadin Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 45,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Loremaster Dorinan",
      loc = { y = -162.0, x = 773.0, z = -16.0 },
      triggers = {
        "Hail, Loremaster Dorinan",
        "I am a cleric.",
        "I wish your aid.",
        "bracers",
        "boots",
        "armplates",
        "gauntlets",
        "helm",
      },
      items_required = {
      },
      rewards = {
        { id = 4511, name = "Boots of Forbidden Rites", type = "item" },
        { id = 4336, name = "Bracers of Forbidden Rites", type = "item" },
        { id = 4954, name = "Breastplate of Forbidden Rites", type = "item" },
        { id = 4474, name = "Crown of Forbidden Rites", type = "item" },
        { id = 4475, name = "Gauntlets of Forbidden Rites", type = "item" },
        { id = 4423, name = "Greaves of Forbidden Rites", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 45\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nLoremaster Dorinan in the in the Thurgadin library offers a series of quests for cleric to obtain a set of Forbidden Rites Armor. She can be found around location -162, 773, -16.\nYou must be at least KINDLY with Coldain in order to complete these quests.\nYou say, 'Hail, Loremaster Dorinan'\nLoremaster Dorinan says, 'Greetings to you. You are far away from your homelands, stranger. I am looking for someone. We here at the Temple of Lore are always seeking fellow priests of various faiths. Tell me, Human, are you a cleric?'\nYou say, 'I am a cleric.'\nLoremaster Dorinan says, 'Ah, a most pious one indeed. I sense the aura of your devotion and conviction and they are strong about you. A shame you are so short-lived. But I see potential in you and for that I shall aid you in your calling, cleric. Do you wish my aid?'\nYou say, 'I wish your aid.'\nLoremaster Dorinan says, 'Then I have a set of goals for you. Once you have achieved them, you shall be rewarded with such as these: a helm, a breastplate, armplates, bracers, gauntlets, greaves and boots. May they protect you from your enemies.'\nCorroded Plate Armor molds drop from giants in the Kael Arena. Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Opal + Corroded Plate Bracelet\nBoots  - 3x Crushed Flame Emerald + Corroded Plate Boots\nArms - 3x Jaundice Gem + Corroded Plate Vambraces\nGloves - 3x Crushed Lava Ruby + Corroded Plate Gauntlets\nHelm - 3x Crushed Onyx Sapphire + Corroded Plate Helmet\nLegs - 3x Chipped Onyx Sapphire + Corroded Plate Greaves\nChest - 3x Black Marble + Corroded Breastplate\nBracer\nYou say, 'bracers'\nLoremaster Dorinan says, 'Bracers are quite easy to imbue. Simply find three crushed opals and a Corroded Plate plate bracer and I will complete the ritual to enchant them.'\nGive Dorinan 3x Crushed Opal and a Corroded Plate Bracer\nLoremaster Dorinan smiles warmly as she hands you your reward.\nLoremaster Dorinan says 'You have done well.'\nYou receive: Bracers of Forbidden Rites\nBoots\nYou say, 'boots'\nLoremaster Dorinan says, 'Simply bring me a set of three crushed flame emeralds and a pair of Corroded Plate plate boots and I will imbue them. I bid you good luck in finding such things.'\nGive Dorinan 3x Crushed Flame Emerald and a Corroded Plate Boots\nLoremaster Dorinan smiles warmly as she hands you your reward.\nLoremaster Dorinan says 'You have done well.'\nYou receive: Boots of Forbidden Rites\nArms\nYou say, 'armplates'\nLoremaster Dorinan says, 'Three jaundice gems and a set of Corroded Plate plate vambraces might be an interesting combination. The powers of the gems may be harvested to imbue the vambraces.'\nGive Dorinan 3x Jaundice Gem and a Corroded Plate Vambraces\nLoremaster Dorinan smiles warmly as she hands you your reward.\nLoremaster Dorinan says 'You have done well.'\nYou receive: Vambraces of Forbidden Rites\nGloves\nYou say, 'gauntlets'\nLoremaster Dorinan says, 'Strong protection for one's hands is important. I may be able to craft you a set of powerful plate gauntlets if you find a set of Corroded Plate plate gauntlets and three crushed lava rubies.'\nGive Dorinan 3x Crushed Lava Ruby and a Corroded Plate Gauntlets\nLoremaster Dorinan smiles warmly as she hands you your reward.\nLoremaster Dorinan says 'You have done well.'\nYou receive: Gauntlets of Forbidden Rites\nHelm\nYou say, 'helm'\nLoremaster Dorinan says, 'Those who are wise as we are know that protection of the head is most important. I may be able to forge you something most interesting if you were to bring me a Corroded Plate plate helm and three pieces of crushed onyx sapphire.'\nGive Dorinan 3x Crushed Onyx Sapphire and an Corroded Plate Plate Helm\nLoremaster Dorinan smiles warmly as she hands you your reward.\nLoremaster Dorinan says 'You have done well.'\nYou receive: Crown of Forbidden Rites\nLegs\nYou say, 'greaves'\nLoremaster Dorinan says, 'A set of Corroded Plate greaves might be salvageable if you were to find three chipped onyx sapphires. With the right techniques almost anything is possible.'\nGive Dorinan 3x Chipped Onyx Sapphire and a Corroded Plate Greaves\nLoremaster Dorinan smiles warmly as she hands you your reward.\nLoremaster Dorinan says 'You have done well.'\nYou receive: Greaves of Forbidden Rites\nChest\nYou say, 'breastplate'\nLoremaster Dorinan says, 'If you find a Corroded Plate breastplate and three pieces of black marble bring them to me and I shall attempt to create an enchanted breastplate that will serve you well.'\nGive Dorinan 3x Black Marble and a Corroded Breastplate\nLoremaster Dorinan smiles warmly as she hands you your reward.\nLoremaster Dorinan says 'You have done well.'\nYou receive: Breastplate of Forbidden Rites\nSubmitted by: BobbybickRewards:\n- Boots of Forbidden Rites [item=4511]\n- Bracers of Forbidden Rites [item=4336]\n- Breastplate of Forbidden Rites [item=4954]\n- Crown of Forbidden Rites [item=4474]\n- Gauntlets of Forbidden Rites [item=4475]\n- Greaves of Forbidden Rites [item=4423]\n- Vambraces of Forbidden Rites [item=4653]\n[",
    },
    {
      id = "8301",
      title = "Shadowknight Thurgadin Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 45,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Dalgrim Underbelly",
      loc = { y = -435.0, x = -134.0, z = 0.0 },
      triggers = {
        "Hail, Dalgrim Underbelly",
        "right materials",
        "bracers",
        "boots",
        "armplates",
        "gauntlets",
        "helm",
        "greaves",
      },
      items_required = {
      },
      rewards = {
        { id = 4603, name = "Dark Runed Boots", type = "item" },
        { id = 4602, name = "Dark Runed Bracer", type = "item" },
        { id = 5889, name = "Dark Runed Breastplate", type = "item" },
        { id = 5598, name = "Dark Runed Crown", type = "item" },
        { id = 4547, name = "Dark Runed Gauntlets", type = "item" },
        { id = 4627, name = "Dark Runed Greaves", type = "item" },
      },
      factions = {
        { name = "Coldain", change = 75 },
        { name = "Dain Frostreaver IV", change = 18 },
        { name = "Kromzek", change = -7 },
        { name = "Coldain", change = 75 },
        { name = "Dain Frostreaver IV", change = 18 },
        { name = "Kromzek", change = -7 },
      },
      walkthrough = "**Level:** 45\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nDalgrim Underbelly in the in the Underbelly Arms offers a series of quests for shadowknights to obtain a set of Dark Runed Armor. He can be found around location -435, -134.\nYou must be at least KINDLY with Coldain in order to complete these quests.\nYou say, 'Hail, Dalgrim Underbelly'\nDalgrim Underbelly says, 'I wasn't always just a merchant, ye know, I used to work at the temple and spent most of my time in the study of ancient texts and arts. I actually learned a lot about the dark arts in those days. Ye know... necromancy. Oh, I'd never touch the stuff, mind ye, but I'll bet I could make a fine set of plate fer shadowknights if'n I had the right materials.'\nYou say, 'right materials'\nDalgrim Underbelly says, 'Glad to see ye're interested, $name. The materials would vary by the piece of armor o' course. I could probably forge a fine set of bracers, gauntlets, greaves, boots, armplates, a helm, or a breastplate.'\nCorroded Armor molds drop from giants in the Kael Arena. Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Flame Emerald + Corroded Plate Bracelet\nBoots - 3x Crushed Black Marble + Corroded Plate Boots\nArms - 3x Flawed Emerald + Corroded Plate Vambraces\nGloves - 3x Crushed Topaz + Corroded Plate Gauntlets\nHelm - 3x Crushed Coral + Corroded Plate Helmet\nLegs - 3x Flawed Sea Sapphire + Corroded Plate Greaves\nChest - 3x Flawless Diamond + Corroded Breastplate\nBracer\nYou say, 'bracers'\nDalgrim Underbelly says, 'For the bracers, I will require a corroded plate bracer and a set of three crushed flame emeralds. Return to me if you happen to find these things in your travels.'\nGive Dalgrim 3x Crushed Flame Emerald and a Corroded Plate Bracer\nDalgrim Underbelly smiles warmly as he hands you your reward.\nDalgrim Underbelly says 'You have done well.'\nYou receive: Dark Runed Bracer\nBoots\nYou say, 'boots'\nDalgrim Underbelly says, 'Boots made for battle are not always the most comfortable available. However if you seek a fine set for battle bring me a set of corroded plate boots and three pieces of crushed black marble.'\nGive Dalgrim 3x Crushed Black Marble and a Corroded Plate Boots\nDalgrim Underbelly smiles warmly as he hands you your reward.\nDalgrim Underbelly says 'You have done well.'\nYou receive: Dark Runed Boots\nArms\nYou say, 'armplates'\nDalgrim Underbelly says, 'Protection for your arms will come at the price of a set of corroded plate vambraces and three flawed emeralds.'\nGive Dalgrim 3x Flawed Emerald and a Corroded Plate Vambraces\nDalgrim Underbelly smiles warmly as he hands you your reward.\nDalgrim Underbelly says 'You have done well.'\nYou receive: Dark Runed Vambraces\nGloves\nYou say, 'gauntlets'\nDalgrim Underbelly says, 'Protecting your hands is very important. I can forge protection for your hands if you bring me a pair of corroded plate gauntlets and three crushed topaz.'\nGive Dalgrim 3x Crushed Topaz and a Corroded Plate Gauntlets\nDalgrim Underbelly smiles warmly as he hands you your reward.\nDalgrim Underbelly says 'You have done well.'\nYou receive: Dark Runed Gauntlets\nHelm\nYou say, 'helm'\nDalgrim Underbelly says, 'To create a piece of armor to protect your skull I will require three pieces of crushed coral as well as a corroded plate helmet.'\nGive Dalgrim 3x Crushed Coral and an Corroded Plate Plate Helm\nDalgrim Underbelly smiles warmly as he hands you your reward.\nDalgrim Underbelly says 'You have done well.'\nYour faction standing with Coldain has been adjusted by 75\nYour faction standing with Dain Frostreaver IV has been adjusted by 18\nYour faction standing with Kromzek has been adjusted by -7\nYour faction standing with Kromrif has been adjusted by ?\nYou receive: Dark Runed Crown\nLegs\nYou say, 'greaves'\nDalgrim Underbelly says, 'A set of corroded greaves might be salvageable if you were to find three flawed sea sapphires. With the right techniques almost anything is possible.'\nGive Dalgrim 3x Flawed Sea Sapphire and a Corroded Plate Greaves\nDalgrim Underbelly smiles warmly as he hands you your reward.\nDalgrim Underbelly says 'You have done well.'\nYour faction standing with Coldain has been adjusted by 75\nYour faction standing with Dain Frostreaver IV has been adjusted by 18\nYour faction standing with Kromzek has been adjusted by -7\nYour faction standing with Kromrif has been adjusted by ?\nYou receive: Dark Runed Greaves\nChest\nYou say, 'breastplate'\nDalgrim Underbelly says, 'For the breastplate, I will need a corroded breastplate and three flawless diamonds. Once I have them in my possession it will not take long to craft a sturdy breastplate.'\nGive Dalgrim 3x Flawless Diamond and a Corroded Breastplate\nDalgrim Underbelly smiles warmly as he hands you your reward.\nDalgrim Underbelly says 'You have done well.'\nYou receive: Dark Runed Breastplate\nSubmitted by: BobbybickRewards:\n- Dark Runed Boots [item=4603]\n- Dark Runed Bracer [item=4602]\n- Dark Runed Breastplate [item=5889]\n- Dark Runed Crown [item=5598]\n- Dark Runed Gauntlets [item=4547]\n- Dark Runed Greaves [item=4627]\n- Dark Runed Vambraces [item=5027]\n[",
    },
    {
      id = "8302",
      title = "Paladin Thurgadin Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 45,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Battlepriest Daragor",
      loc = { y = -227.0, x = 558.0, z = 0.0 },
      triggers = {
        "Hail, Battlepriest Daragor",
        "I am a paladin",
        "I will partake of your quests",
        "bracers",
        "boots",
        "armplates",
        "gauntlets",
        "helm",
      },
      items_required = {
      },
      rewards = {
        { id = 4343, name = "Runed Protector's Boots", type = "item" },
        { id = 4533, name = "Runed Protector's Bracer", type = "item" },
        { id = 4562, name = "Runed Protector's Breastplate", type = "item" },
        { id = 4327, name = "Runed Protector's Gauntlets", type = "item" },
        { id = 4370, name = "Runed Protector's Greaves", type = "item" },
        { id = 5346, name = "Runed Protector's Helm", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 45\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nBattlepriest Daragor up on a balcony offers a series of quests for paladins to obtain a set of Runed Protector's Armor. He can be found around location -227, 558.\nYou must be at least KINDLY with Coldain in order to complete these quests.\nYou say, 'Hail, Battlepriest Daragor'\nBattlepriest Daragor says, 'Greetings to you. I seek the service of devout knights who have distinguished themselves. Are you a paladin, (playername)?'\nYou say, 'I am a paladin'\nBattlepriest Daragor says, 'A paladin of your kind has not made it this far for quite some time. Well, I wonder what it is you seek here? Do you seek heroic and chivalrous deeds to distinguish yourself from your brethren? Do you need accoutrements to aid you in your battles perhaps? You are in luck, knight, for I have both for you. Do you wish to partake of my quests?'\nYou say, 'I will partake of your quests'\nBattlepriest Daragor says, 'Excellent! By serving my cause, you, in turn, will further your own. I require certain components and if you bring them to me I shall reward you for your honorable service. You may choose from among these items: a helm, a breastplate, armplates, bracers, gauntlets, greaves, and boots.'\nCorroded Armor molds drop from giants in the Kael Arena. Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Flame Emerald + Corroded Plate Bracelet\nBoots - 3x Crushed Black Marble + Corroded Plate Boots\nArms - 3x Flawed Emerald + Corroded Plate Vambraces\nGloves - 3x Crushed Topaz + Corroded Plate Gauntlets\nHelm - 3x Crushed Coral + Corroded Plate Helmet\nLegs - 3x Flawed Sea Sapphire + Corroded Plate Greaves\nChest - 3x Flawless Diamond + Corroded Breastplate\nBracer\nYou say, 'bracers'\nBattlepriest Daragor says, 'For the bracers, I will require a corroded plate bracer and a set of three crushed flame emeralds. Return to me if you happen to find these things in your travels.'\nGive Daragor 3x Crushed Flame Emerald and a Corroded Plate Bracer\nBattlepriest Daragor smiles warmly as he hands you your reward.\nBattlepriest Daragor says 'You have done well.'\nYou receive: Runed Protector's Bracer\nBoots\nYou say, 'boots'\nBattlepriest Daragor says, 'Boots made for battle are not always the most comfortable available. However if you seek a fine set for battle bring me a set of corroded plate boots and three pieces of crushed black marble.'\nGive Daragor 3x Crushed Black Marble and a Corroded Plate Boots\nBattlepriest Daragor smiles warmly as he hands you your reward.\nBattlepriest Daragor says 'You have done well.'\nYou receive: Runed Protector's Boots\nArms\nYou say, 'armplates'\nBattlepriest Daragor says, 'Protection for your arms will come at the price of a set of corroded plate vambraces and three flawed emeralds.'\nGive Daragor 3x Flawed Emerald and a Corroded Plate Vambraces\nBattlepriest Daragor smiles warmly as he hands you your reward.\nBattlepriest Daragor says 'You have done well.'\nYou receive: Runed Protector's Vambraces\nGloves\nYou say, 'gauntlets'\nBattlepriest Daragor says, 'Protecting your hands is very important. I can forge protection for your hands if you bring me a pair of corroded plate gauntlets and three crushed topaz.'\nGive Daragor 3x Crushed Topaz and a Corroded Plate Gauntlets\nBattlepriest Daragor smiles warmly as he hands you your reward.\nBattlepriest Daragor says 'You have done well.'\nYou receive: Runed Protector's Gauntlets\nHelm\nYou say, 'helm'\nBattlepriest Daragor says, 'To create a piece of armor to protect your skull I will require three pieces of crushed coral as well as a corroded plate helmet.'\nGive Daragor 3x Crushed Coral and an Corroded Plate Plate Helm\nBattlepriest Daragor smiles warmly as he hands you your reward.\nBattlepriest Daragor says 'You have done well.'\nYou receive: Runed Protector's Crown\nLegs\nYou say, 'greaves'\nBattlepriest Daragor says, 'A set of corroded greaves might be salvageable if you were to find three flawed sea sapphires. With the right techniques almost anything is possible.'\nGive Daragor 3x Flawed Sea Sapphire and a Corroded Plate Greaves\nBattlepriest Daragor smiles warmly as he hands you your reward.\nBattlepriest Daragor says 'You have done well.'\nYou receive: Runed Protector's Greaves\nChest\nYou say, 'breastplate'\nBattlepriest Daragor says, 'For the breastplate, I will need a corroded breastplate and three flawless diamonds. Once I have them in my possession it will not take long to craft a sturdy breastplate.'\nGive Daragor 3x Flawless Diamond and a Corroded Breastplate\nBattlepriest Daragor smiles warmly as he hands you your reward.\nBattlepriest Daragor says 'You have done well.'\nYou receive: Runed Protector's Breastplate\nSubmitted by: BobbybcikRewards:\n- Runed Protector's Boots [item=4343]\n- Runed Protector's Bracer [item=4533]\n- Runed Protector's Breastplate [item=4562]\n- Runed Protector's Gauntlets [item=4327]\n- Runed Protector's Greaves [item=4370]\n- Runed Protector's Helm [item=5346]\n- Runed Protector's Vambraces [item=4221]\n[",
    },
    {
      id = "8303",
      title = "Bard Thurgadin Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 45,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Leifur",
      loc = { y = -322.0, x = 5.0, z = 0.0 },
      triggers = {
        "Hail, Leifur",
        "components",
        "bracers",
        "boots",
        "armplates",
        "gauntlets",
        "helm",
        "greaves",
      },
      items_required = {
      },
      rewards = {
        { id = 4574, name = "Resonant Boots", type = "item" },
        { id = 4667, name = "Resonant Bracer", type = "item" },
        { id = 4967, name = "Resonant Breastplate", type = "item" },
        { id = 5279, name = "Resonant Gauntlets", type = "item" },
        { id = 4897, name = "Resonant Greaves", type = "item" },
        { id = 4749, name = "Resonant Helm", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 45\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nLeifur in a bar near the beginning of the zone offers a series of quests for bards to obtain a set of Resonant Armor. He can be found around location -322, 5.\nYou must be at least KINDLY with Coldain in order to complete these quests.\nYou say, 'Hail, Leifur'\nLeifur says, 'The one thing this bar is sorely missin' is a good bard I tell ye. Ye know, someone to sing a catchy tune and tell us a story from time to time. Forgive me fer seemin' a bit sentimental but my family has always had close ties with bards datin' back ta even before we crossed the ocean. In fact, me great-great-grandfather used ta forge enchanted armor for the ancient bards of Faydark. Oh, the set of bard velium armor I could make if only I had the right components!'\nYou say, 'components'\nLeifur says, 'With the proper components I could make a helm, a breastplate, armplates, bracers, gauntlets, greaves, and even a pair o' boots!'\nCorroded Armor molds drop from giants in the Kael Arena. Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Flame Emerald + Corroded Plate Bracelet\nBoots - 3x Crushed Black Marble + Corroded Plate Boots\nArms - 3x Flawed Emerald + Corroded Plate Vambraces\nGloves - 3x Crushed Topaz + Corroded Plate Gauntlets\nHelm - 3x Crushed Coral + Corroded Plate Helmet\nLegs - 3x Flawed Sea Sapphire + Corroded Plate Greaves\nChest - 3x Flawless Diamond + Corroded Breastplate\nBracer\nYou say, 'bracers'\nLeifur says, 'For the bracers, I will require a corroded plate bracer and a set of three crushed flame emeralds. Return to me if you happen to find these things in your travels.'\nGive Leifur 3x Crushed Flame Emerald and a Corroded Plate Bracer\nLeifur smiles warmly as he hands you your reward.\nLeifur says 'You have done well.'\nYou receive: Resonant Bracer\nBoots\nYou say, 'boots'\nLeifur says, 'Boots made for battle are not always the most comfortable available. However if you seek a fine set for battle bring me a set of corroded plate boots and three pieces of crushed black marble.'\nGive Leifur 3x Crushed Black Marble and a Corroded Plate Boots\nLeifur smiles warmly as he hands you your reward.\nLeifur says 'You have done well.'\nYou receive: Resonant Boots\nArms\nYou say, 'armplates'\nLeifur says, 'Protection for your arms will come at the price of a set of corroded plate vambraces and three flawed emeralds.'\nGive Leifur 3x Flawed Emerald and a Corroded Plate Vambraces\nLeifur smiles warmly as he hands you your reward.\nLeifur says 'You have done well.'\nYou receive: Resonant Vambraces\nGloves\nYou say, 'gauntlets'\nLeifur says, 'Protecting your hands is very important. I can forge protection for your hands if you bring me a pair of corroded plate gauntlets and three crushed topaz.'\nGive Leifur 3x Crushed Topaz and a Corroded Plate Gauntlets\nLeifur smiles warmly as he hands you your reward.\nLeifur says 'You have done well.'\nYou receive: Resonant Gauntlets\nHelm\nYou say, 'helm'\nLeifur says, 'To create a piece of armor to protect your skull I will require three pieces of crushed coral as well as a corroded plate helmet.'\nGive Leifur 3x Crushed Coral and an Corroded Plate Plate Helm\nLeifur smiles warmly as he hands you your reward.\nLeifur says 'You have done well.'\nYou receive: Resonant Crown\nLegs\nYou say, 'greaves'\nLeifur says, 'A set of corroded greaves might be salvageable if you were to find three flawed sea sapphires. With the right techniques almost anything is possible.'\nGive Leifur 3x Flawed Sea Sapphire and a Corroded Plate Greaves\nLeifur smiles warmly as he hands you your reward.\nLeifur says 'You have done well.'\nYou receive: Resonant Greaves\nChest\nYou say, 'breastplate'\nLeifur says, 'For the breastplate, I will need a corroded breastplate and three flawless diamonds. Once I have them in my possession it will not take long to craft a sturdy breastplate.'\nGive Leifur 3x Flawless Diamond and a Corroded Breastplate\nLeifur smiles warmly as he hands you your reward.\nLeifur says 'You have done well.'\nYou receive: Resonant Breastplate\nSubmitted by: BobbybickRewards:\n- Resonant Boots [item=4574]\n- Resonant Bracer [item=4667]\n- Resonant Breastplate [item=4967]\n- Resonant Gauntlets [item=5279]\n- Resonant Greaves [item=4897]\n- Resonant Helm [item=4749]\n- Resonant Vambraces [item=4673]\n[",
    },
    {
      id = "8304",
      title = "Monk Thurgadin Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 45,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Lorekeeper Einar",
      loc = { y = -650.0, x = 45.0, z = 0.0 },
      triggers = {
        "Hail, Lorekeeper Einar",
        "I am a monk",
        "bracers",
        "boots",
        "sleeves",
        "gloves",
        "cap",
        "leggings",
      },
      items_required = {
      },
      rewards = {
        { id = 5331, name = "Fist of the Grand Master", type = "item" },
        { id = 4898, name = "Grand Master's Arm Wraps", type = "item" },
        { id = 5028, name = "Grand Master's Chest Wraps", type = "item" },
        { id = 4512, name = "Grand Master's Headband", type = "item" },
        { id = 4513, name = "Grand Master's Leg Wraps", type = "item" },
        { id = 4698, name = "Grand Master's Slippers", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 45\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nLorekeeper Einar in the barracks near beginning of the zone offers a series of quests for monks to obtain a set of Grand Master's Armor. He can be found around location -650, 45.\nYou must be at least KINDLY with Coldain in order to complete these quests.\nYou say, 'Hail, Lorekeeper Einar'\nLorekeeper Einar says, 'Greetings to you. I seek one that has chosen the path of monkhood. What do you call yourself?'\nYou say, 'I am a monk'\nLorekeeper Einar says, 'Good. I had hoped you were one. I have heard that as seeker of the way you are in constant training to push yourself to your physical and mental limits. It is an admirable quality and I wish to aid you. I will provide you with a cap, a tunic, sleeves, bracers, gloves, leggings and boots.'\nEroded Armor molds drop from giants in the Kael Arena. Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Flame Emerald + Eroded Leather Bracelet\nBoots - 3x Crushed Black Marble + Eroded Leather Boots\nArms - 3x Flawed Emerald + Eroded Leather Sleeves\nGloves - 3x Crushed Topaz + Eroded Leather Gloves\nHelm - 3x Crushed Coral + Eroded Leather Cap\nLegs - 3x Flawed Sea Sapphire + Eroded Leather Leggings\nChest - 3x Flawless Diamond + Eroded Leather Tunic\nBracer\nYou say, 'bracers'\nLorekeeper Einar says, 'For the bracers, I will require a eroded leather bracelet as well as three crushed flame emeralds. Return to me when you find such things.'\nGive Lorekeeper Einar 3x Crushed Flame Emerald and a Eroded Leather Wristband\nLorekeeper Einar smiles warmly as he hands you your reward.\nLorekeeper Einar says 'You have done well.'\nYou receive: Grand Master's Wrist Wraps\nBoots\nYou say, 'boots'\nLorekeeper Einar says, 'We use our feet so often, should not they be protected as well as any other portion of our bodies? If you seek fine protection for your feet return to me with three pieces of crushed black marble and a pair of eroded leather boots.'\nGive Lorekeeper Einar 3x Crushed Black Marble and a Eroded Leather Boots\nLorekeeper Einar smiles warmly as he hands you your reward.\nLorekeeper Einar says 'You have done well.'\nYou receive: Grand Master's Slippers\nArms\nYou say, 'sleeves'\nLorekeeper Einar says, 'Protection for your arms will come at the price of three flawed emeralds and a set of eroded leather sleeves.'\nGive Lorekeeper Einar 3x Flawed Emerald and a Eroded Leather Sleeves\nLorekeeper Einar smiles warmly as he hands you your reward.\nLorekeeper Einar says 'You have done well.'\nYou receive: Grand Master's Arm Wraps\nGloves\nYou say, 'gloves'\nLorekeeper Einar says, 'Protecting your hands is very important. I can create some excellent protection for your hands if you bring me three crushed topaz and a pair of eroded leather gloves.'\nGive Lorekeeper Einar 3x Crushed Topaz and a Eroded Leather Gloves\nLorekeeper Einar smiles warmly as he hands you your reward.\nLorekeeper Einar says 'You have done well.'\nYou receive: Fist of the Grand Master\nHelm\nYou say, 'cap'\nLorekeeper Einar says, 'To create a piece of armor to protect your sensitive skull I will require three pieces of crushed coral as well as a eroded leather cap.'\nGive Lorekeeper Einar 3x Crushed Coral and an Eroded Leather Cap\nLorekeeper Einar smiles warmly as he hands you your reward.\nLorekeeper Einar says 'You have done well.'\nYou receive: Grand Master's Headband\nLegs\nYou say, 'leggings'\nLorekeeper Einar says, 'I may be able to craft a set of wondrous leggings from a set of old eroded leather leggings and three flawed sea sapphires. It is amazing what you can do with a bit of magic.'\nGive Lorekeeper Einar 3x Flawed Sea Sapphire and a Eroded Leather Leggings\nLorekeeper Einar smiles warmly as he hands you your reward.\nLorekeeper Einar says 'You have done well.'\nYou receive: Grand Master's Leg Wraps\nChest\nYou say, 'tunic'\nLorekeeper Einar says, 'To create a spectacular tunic fit for your kind I will require three flawless diamonds and an eroded leather tunic. With the gems and my skills I may be able to draw out some of its magical powers.'\nGive Lorekeeper Einar 3x Flawless Diamond and a Corroded Leather Tunic\nLorekeeper Einar smiles warmly as he hands you your reward.\nLorekeeper Einar says 'You have done well.'\nYou receive: Grand Master's Chest Wraps\nSubmitted by: BobbybickRewards:\n- Fist of the Grand Master [item=5331]\n- Grand Master's Arm Wraps [item=4898]\n- Grand Master's Chest Wraps [item=5028]\n- Grand Master's Headband [item=4512]\n- Grand Master's Leg Wraps [item=4513]\n- Grand Master's Slippers [item=4698]\n- Grand Master's Wrist Wraps [item=4514]\n[",
    },
    {
      id = "8307",
      title = "Rogue Thurgadin Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 45,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Foreman Felspar",
      loc = { y = 46.0, x = -140.0, z = 0.0 },
      triggers = {
        "Hail, Foreman Felspar",
        "New set of armor",
        "bracers",
        "boots",
        "sleeves",
        "gauntlets",
        "coif",
        "leggings",
      },
      items_required = {
      },
      rewards = {
        { id = 4561, name = "Brigand's Boots", type = "item" },
        { id = 5479, name = "Brigand's Bracer", type = "item" },
        { id = 4981, name = "Brigand's Chestguard", type = "item" },
        { id = 4980, name = "Brigand's Circlet", type = "item" },
        { id = 4979, name = "Brigand's Gauntlets", type = "item" },
        { id = 5637, name = "Brigand's Greaves", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 45\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nForeman Felspar found near the mines in Thurgadin offers a series of quests for rogues to obtain a set of Brigand's Armor. He can be found around location 46, -140.\nYou must be at least KINDLY with Coldain in order to complete these quests.\nYou say, 'Hail, Foreman Felspar'\nForeman Felspar says, 'Welcome to the Thurgadin Minin' Company, (playerrace). As foreman it's my job to see that me lads are well trained and well cared fer. Unfortunately, we're not in too good shape right now. Ye see, it seems a new vein was struck recently and a bunch of unwelcome critters have come crawlin outta the works attackin' me lads. In order ta help combat this menace I've engineered a new set of armor for the miners, but need some raw materials to get them started.'\nYou say, 'New set of armor'\nForeman Felspar says, 'Excellent, (playername)! I knew ye were the right (playerrace) for the job. The pieces I can make are a coif, a tunic, sleeves, bracers, gauntlets, leggings, and boots. This stuff might not be fitting ya if ye're not stealthy like us miners though.'\nCorroded Armor molds drop from giants in the Kael Arena. Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Flame Emerald + Corroded Chain Bracer\nBoots - 3x Crushed Black Marble + Corroded Chain Boots\nArms - 3x Flawed Emerald + Corroded Chain Sleeves\nGloves - 3x Crushed Topaz + Corroded Chain Gauntlets\nHelm - 3x Crushed Coral + Corroded Chain Coif\nLegs - 3x Flawed Sea Sapphire + Corroded Chain Leggings\nChest - 3x Flawless Diamond + Corroded Chain Tunic\nBracer\nYou say, 'bracers'\nForeman Felspar says, 'For the bracers, I will require a corroded chain bracer as well as three crushed flame emeralds.  Return to me when you find such things, (playername).'\nGive Felspar 3x Crushed Flame Emerald and a Corroded Chain Bracer\nForeman Felspar smiles warmly as he hands you your reward.\nForeman Felspar says 'You have done well.'\nYou receive: Brigand's Bracer\nBoots\nYou say, 'boots'\nForeman Felspar says, 'We use our feet so often, should not they be protected as well as any other portion of our bodies?  If you seek fine protection for your feet, return to me with three pieces of crushed black marble and a set of corroded chain boots.'\nGive Felspar 3x Crushed Black Marble and a Corroded Chain Boots\nForeman Felspar smiles warmly as he hands you your reward.\nForeman Felspar says 'You have done well.'\nYou receive: Brigand's Boots\nArms\nYou say, 'sleeves'\nForeman Felspar says, 'Protection for your arms will come at the price of three flawed emeralds and a set of corroded chain sleeves.'\nGive Felspar 3x Flawed Emerald and a Corroded Chain Sleeves\nForeman Felspar smiles warmly as he hands you your reward.\nForeman Felspar says 'You have done well.'\nYou receive: Brigand's Vambraces\nGloves\nYou say, 'gauntlets'\nForeman Felspar says, 'Protecting your hands is very important.  I can forge protection for your hands if you bring me a pair of corroded chain gauntlets and three crushed topaz.'\nGive Felspar 3x Crushed Topaz and a Corroded Chain Gauntlets\nForeman Felspar smiles warmly as he hands you your reward.\nForeman Felspar says 'You have done well.'\nYou receive: Brigand's Gauntlets\nHelm\nYou say, 'coif'\nForeman Felspar says, 'To create a piece of armor to protect your sensitive skull. I will require three pieces of crushed coral as well as a corroded chain coif.'\nGive Felspar 3x Crushed Coral and an Corroded Chain Coif\nForeman Felspar smiles warmly as he hands you your reward.\nForeman Felspar says 'You have done well.'\nYou receive: Brigand's Circlet\nLegs\nYou say, 'leggings'\nForeman Felspar says, 'A set of corroded chain leggings might be salvageable if you were to find three flawed sea sapphires.  With the right techniques and ingredients almost anything is possible.'\nGive Felspar 3x Flawed Sea Sapphire and a Corroded Chain Leggings\nForeman Felspar smiles warmly as he hands you your reward.\nForeman Felspar says 'You have done well.'\nYou receive: Brigand's Greaves\nChest\nYou say, 'tunic'\nForeman Felspar says, 'To forge a spectacular chain tunic I will require three flawless diamonds and a corroded chain tunic.  With the gems and my skills I may be able to draw out some of its magical powers.'\nGive Felspar 3x Flawless Diamond and a Corroded Chain Tunic\nForeman Felspar smiles warmly as he hands you your reward.\nForeman Felspar says 'You have done well.'\nYou receive: Brigand's Chestguard\nSubmitted by: BobbybickRewards:\n- Brigand's Boots [item=4561]\n- Brigand's Bracer [item=5479]\n- Brigand's Chestguard [item=4981]\n- Brigand's Circlet [item=4980]\n- Brigand's Gauntlets [item=4979]\n- Brigand's Greaves [item=5637]\n- Brigand's Vambraces [item=4996]\n[",
    },
    {
      id = "8308",
      title = "Shaman Thurgadin Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 45,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Terman Underbelly",
      loc = { y = -421.0, x = -120.0, z = 0.0 },
      triggers = {
        "Hail, Terman Underbelly",
        "I am a shaman",
        "armor",
        "bracers",
        "boots",
        "sleeves",
        "gauntlets",
        "coif",
      },
      items_required = {
        { name = "Terman 3x Black Marble and a Corroded Chain Tunic", count = 1 },
      },
      rewards = {
        { id = 4438, name = "Rune Crafter's Boots", type = "item" },
        { id = 4300, name = "Rune Crafter's Bracer", type = "item" },
        { id = 4995, name = "Rune Crafter's Breastplate", type = "item" },
        { id = 4422, name = "Rune Crafter's Gauntlets", type = "item" },
        { id = 4866, name = "Rune Crafter's Greaves", type = "item" },
        { id = 4994, name = "Rune Crafter's Helm", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 45\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nTerman Underbelly found inside Underbelly Arms in Thurgadin offers a series of quests for shamans to obtain a set of Rune Crafter's Armor. He can be found around location -421, -120.\nYou must be at least KINDLY with Coldain in order to complete these quests.\nYou say, 'Hail, Terman Underbelly'\nTerman Underbelly speaks in a rumbling tone.\nTerman Underbelly says, 'Greetings. I only wish to speak to a shaman. Are you a shaman?'\nYou say, 'I am a shaman'\nTerman Underbelly says, 'I sense the strength of your mystical powers within you and they vibrate with power.  You have learned much from your travels and I shall help you by providing you with protection from harm and the elements in the form of armor.'\nYou say, 'armor'\nTerman Underbelly says, 'For you I shall make a coif, tunic, sleeves, bracers, gauntlets, leggings, and boots. Each piece is a quest unto itself. To find the components you must search the lands for them and test the power of the spirit within.'\nCorroded Armor molds drop from giants in the Kael Arena. Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Opal + Corroded Chain Bracer\nBoots - 3x Crushed Flame Emerald + Corroded Chain Boots\nArms - 3x Jaundice Gem + Corroded Chain Sleeves\nGloves - 3x Crushed Lava Ruby + Corroded Chain Gauntlets\nHelm - 3x Crushed Onyx Sapphire + Corroded Chain Coif\nLegs - 3x Chipped Onyx Sapphire + Corroded Chain Leggings\nChest - 3x Black Marble + Corroded Chain Tunic\nBracer\nYou say, 'bracers'\nTerman Underbelly says, 'Bracers are quite easy to imbue. Simply find three crushed opals and a corroded chain bracer and I will complete the ritual to enchant them.'\nGive Terman 3x Crushed Opal and a Corroded Chain Bracer\nTerman Underbelly smiles warmly as he hands you your reward.\nTerman Underbelly says 'You have done well.'\nYou receive: Rune Crafter's Bracer\nBoots\nYou say, 'boots'\nTerman Underbelly says, 'Simply bring me a set of three crushed flame emeralds and a pair of corroded chain boots and I will imbue them. I bid you good luck in finding such things.'\nGive Terman 3x Crushed Flame Emerald and a Corroded Chain Boots\nTerman Underbelly smiles warmly as he hands you your reward.\nTerman Underbelly says 'You have done well.'\nYou receive: Rune Crafter's Boots\nArms\nYou say, 'sleeves'\nTerman Underbelly says, 'Three jaundice gems and a set of corroded chain sleeves might be an interesting combination. The powers of the gems may be harnessed to imbue the sleeves.'\nGive Terman 3x Jaundice Gem and a Corroded Chain Sleeves\nTerman Underbelly smiles warmly as he hands you your reward.\nTerman Underbelly says 'You have done well.'\nYou receive: Rune Crafter's Vambraces\nGloves\nYou say, 'gauntlets'\nTerman Underbelly says, 'Strong protection for one's hands is important. I may be able to craft you a set of powerful chain gauntlets if you find a set of corroded chain gauntlets and three crushed lava rubies.'\nGive Terman 3x Crushed Lava Ruby and a Corroded Chain Gauntlets\nTerman Underbelly smiles warmly as he hands you your reward.\nTerman Underbelly says 'You have done well.'\nYou receive: Rune Crafter's Gauntlets\nHelm\nYou say, 'coif'\nTerman Underbelly says, 'Those who are wise as we are know that protection of the head is most important. I may be able to forge you something most interesting if you were to bring me a corroded chain coif and three pieces of crushed onyx sapphire.'\nGive Terman 3x Crushed Onyx Sapphire and an Corroded Chain Coif\nTerman Underbelly smiles warmly as he hands you your reward.\nTerman Underbelly says 'You have done well.'\nYou receive: Rune Crafter's Helm\nLegs\nYou say, 'leggings'\nTerman Underbelly says, 'Leggings are a bit trickier to imbue. Three chipped onyx sapphires will allow me to channel the correct energies into a pair of corroded chain leggings. However, those chipped onyx sapphires are somewhat rare. Return to me if you find such things in your journeys.'\nGive Terman 3x Chipped Onyx Sapphire and a Corroded Chain Leggings\nTerman Underbelly smiles warmly as he hands you your reward.\nTerman Underbelly says 'You have done well.'\nYou receive: Rune Crafter's Greaves\nChest\nYou say, 'tunic'\nTerman Underbelly says, 'If you find a corroded chain tunic and three pieces of black marble bring them to me and I shall attempt to create an enchanted tunic that will serve you well.'\nGive Terman 3x Black Marble and a Corroded Chain Tunic\nTerman Underbelly smiles warmly as he hands you your reward.\nTerman Underbelly says 'You have done well.'\nYou receive: Rune Crafter's Breastplate\nSubmitted by: BobbybickRewards:\n- Rune Crafter's Boots [item=4438]\n- Rune Crafter's Bracer [item=4300]\n- Rune Crafter's Breastplate [item=4995]\n- Rune Crafter's Gauntlets [item=4422]\n- Rune Crafter's Greaves [item=4866]\n- Rune Crafter's Helm [item=4994]\n- Rune Crafter's Vambraces [item=4583]\n[",
    },
    {
      id = "8309",
      title = "Druid Thurgadin Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 45,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Cobi Frostbeard",
      loc = { y = -114.0, x = 219.0, z = 0.0 },
      triggers = {
        "Hail, Cobi Frostbeard",
        "I am a druid",
        "armor",
        "bracers",
        "boots",
        "sleeves",
        "Gloves",
        "cap",
      },
      items_required = {
        { name = "Cobi 3x Jaundice Gem and a Eroded Leather Sleeves", count = 1 },
        { name = "Cobi 3x Black Marble and a Eroded Leather Tunic", count = 1 },
      },
      rewards = {
        { id = 4345, name = "Rowyl's Boots of Nature", type = "item" },
        { id = 4126, name = "Rowyl's Bracer of Nature", type = "item" },
        { id = 4895, name = "Rowyl's Chestguard of Nature", type = "item" },
        { id = 5572, name = "Rowyl's Circlet of Nature", type = "item" },
        { id = 4520, name = "Rowyl's Gauntlets of Nature", type = "item" },
        { id = 4127, name = "Rowyl's Greaves of Nature", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 45\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nCobi Frostbeard found inside a small shop in northwest Thurgadin offers a series of quests for druids to obtain a set of Rowyl's Armor of Nature. He can be found around location -114, 219.\nYou must be at least KINDLY with Coldain in order to complete these quests.\nYou say, 'Hail, Cobi Frostbeard'\nCobi Frostbeard says, 'Greetings to you. I seek one who calls himself a druid. What do you call yourself, manling?'\nYou say, 'I am a druid'\nCobi Frostbeard says, 'Good. I had hoped you were one. As nature's guardian, you fight the never-ending struggle against those who seek to defile it. It is an admirable quality and I wish to aid you. I will provide you with a cap, a tunic, sleeves, bracers, gloves, leggings, and boots.'\nYou say, 'armor'\nEroded Armor molds drop from giants in the Kael Arena. Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracelet - 3x Crushed Opal + Eroded Leather Bracelet\nBoots - 3x Crushed Flame Emerald + Eroded Leather Boots\nArms - 3x Jaundice Gem + Eroded Leather Sleeves\nGloves - 3x Crushed Lava Ruby + Eroded Leather Gloves\nHelm - 3x Crushed Onyx Sapphire + Eroded Leather Cap\nLegs - 3x Chipped Onyx Sapphire + Eroded Leather Leggings\nChest - 3x Black Marble + Eroded Leather Tunic\nBracer\nYou say, 'bracers'\nCobi Frostbeard says, 'Bracers are quite easy to imbue. Simply find three crushed opals and an eroded leather bracer and I will complete the ritual to enchant them.'\nGive Cobi 3x Crushed Opal and a Eroded Leather Bracelet\nCobi Frostbeard smiles warmly as he hands you your reward.\nCobi Frostbeard says 'You have done well.'\nYou receive: Rowyl's Bracer of Nature\nBoots\nYou say, 'boots'\nCobi Frostbeard says, 'Simply bring me a set of three crushed flame emeralds and a pair of eroded leather boots and I will imbue them. I bid you good luck in finding such things.'\nGive Cobi 3x Crushed Flame Emerald and a Eroded Leather Boots\nCobi Frostbeard smiles warmly as he hands you your reward.\nCobi Frostbeard says 'You have done well.'\nYou receive: Rowyl's Boots of Nature\nArms\nYou say, 'sleeves'\nCobi Frostbeard says, 'Three jaundice gems and a set of eroded leather sleeves might be an interesting combination. The powers of the gems may be harvested to imbue the sleeves.'\nGive Cobi 3x Jaundice Gem and a Eroded Leather Sleeves\nCobi Frostbeard smiles warmly as he hands you your reward.\nCobi Frostbeard says 'You have done well.'\nYou receive: Rowyl's Vambraces of Nature\nGloves\nYou say, 'Gloves'\nCobi Frostbeard says, 'Strong protection for one's hands is important. I may be able to craft you a set of powerful leather gloves if you find a set of eroded leather gloves and three crushed lava rubies.'\nGive Cobi 3x Crushed Lava Ruby and a Eroded Leather Gloves\nCobi Frostbeard smiles warmly as he hands you your reward.\nCobi Frostbeard says 'You have done well.'\nYou receive: Rowyl's Gauntlets of Nature\nHelm\nYou say, 'cap'\nCobi Frostbeard says, 'Those who are as wise as we are know that protection of the head is most important. I may be able to forge you something most interesting if you were to bring me three pieces of crushed onyx sapphire and an eroded leather cap.'\nGive Cobi 3x Crushed Onyx Sapphire and an Eroded Leather Cap\nCobi Frostbeard smiles warmly as he hands you your reward.\nCobi Frostbeard says 'You have done well.'\nYou receive: Rowyl's Circlet of Nature\nLegs\nYou say, 'leggings'\nCobi Frostbeard says, 'Leggings are a bit trickier to imbue. Three chipped onyx sapphires will allow me to channel the correct energies into a pair of eroded leather leggings. However, those chipped onyx sapphires are somewhat rare. Return to me if you find such things in your journeys.'\nGive Cobi 3x Chipped Onyx Sapphire and a Eroded Leather Leggings\nCobi Frostbeard smiles warmly as he hands you your reward.\nCobi Frostbeard says 'You have done well.'\nYou receive: Rowyl's Greaves of Nature\nChest\nYou say, 'tunic'\nCobi Frostbeard says, 'If you find an eroded leather tunic and three pieces of black marble bring them to me and I shall attempt to create an enchanted tunic that will serve you well.'\nGive Cobi 3x Black Marble and a Eroded Leather Tunic\nCobi Frostbeard smiles warmly as he hands you your reward.\nCobi Frostbeard says 'You have done well.'\nYou receive: Rowyl's Chestguard of Nature\nSubmitted by: BobbybcikRewards:\n- Rowyl's Boots of Nature [item=4345]\n- Rowyl's Bracer of Nature [item=4126]\n- Rowyl's Chestguard of Nature [item=4895]\n- Rowyl's Circlet of Nature [item=5572]\n- Rowyl's Gauntlets of Nature [item=4520]\n- Rowyl's Greaves of Nature [item=4127]\n- Rowyl's Vambraces of Nature [item=4337]\n[",
    },
    {
      id = "8310",
      title = "Enchanter Thurgadin Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 45,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Lorekeeper Brita",
      loc = { y = -170.0, x = 800.0, z = 0.0 },
      triggers = {
        "Hail, Lorekeeper Brita",
        "I am an enchanter",
        "wristbands",
        "boots",
        "sleeves",
        "gloves",
        "cap",
        "leggings",
      },
      items_required = {
        { id = 1427, name = "Beguiler's Slippers", count = 1 },
        { id = 1417, name = "Item #1417", count = 1 },
        { id = 1427, name = "Item #1427", count = 1 },
      },
      rewards = {
        { id = 4545, name = "Beguiler's Crown", type = "item" },
        { id = 4541, name = "Beguiler's Gloves", type = "item" },
        { id = 4892, name = "Beguiler's Robe", type = "item" },
        { id = 4147, name = "Beguiler's Sleeves", type = "item" },
        { id = 3952, name = "Beguiler's Slippers", type = "item" },
        { id = 4872, name = "Beguiler's Trousers", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 45\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nLorekeeper Brita found inside the library of Thurgadin offers a series of quests for enchanters to obtain a set of Beguiler's Armor. She can be found around location -170, 800.\nYou must be at least KINDLY with Coldain in order to complete these quests.\nYou say, 'Hail, Lorekeeper Brita'\nLorekeeper Brita says, 'Greetings to you.  I seek those who call themselves enchanters.  Are you an enchanter?'\nYou say, 'I am an enchanter'\nLorekeeper Brita says, 'I thought so.  I have several tasks for you accomplish.  Once you have completed them I will have a cap, a robe, sleeves, wristbands, gloves, leggings and boots to reward you with.'\nTorn Enchanted Silk armor molds drop from giants in the Kael Arena. Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Onyx Sapphire + Torn Enchanted Silk Wristband\nBoots  - 3x Crushed Jaundice Gem + Torn Enchanted Silk Boots\nArms - 3x Flawed Topaz + Torn Enchanted Silk Sleeves\nGloves - 3x Crushed Topaz + Torn Enchanted Silk Gloves\nHelm - 3x Crushed Flame Opal + Torn Enchanted Silk Turban\nLegs - 3x Nephrite + Torn Enchanted Silk Pantaloons\nChest - 3x Pristine Emerald + Torn Enchanted Silk Robe\nBracer\nYou say, 'wristbands'\nLorekeeper Brita says 'An enchanted silk wristguard and three crushed onyx sapphires is all that I require to create an imbued wrist wrap of great power.  Seek out these items and return to me when you have acquired them.'\nGive Brita 3x Crushed Onyx Sapphire and a Torn Enchanted Silk Wristband\nLorekeeper Brita smiles warmly as she hands you your reward.\nLorekeeper Brita says 'You have done well.'\nYou receive: Beguiler's Wristguard\nBoots\nYou say, 'boots'\nLorekeeper Brita says 'Three crushed jaundice gems combined with torn enchanted silk boots would make a most interesting set of footwear.  The latent powers of the gems can be harnessed to create magical effects.'\nGive Brita 3x Crushed Jaundice Gem and a Torn Enchanted Silk Boots\nLorekeeper Brita smiles warmly as she hands you your reward.\nLorekeeper Brita says 'You have done well.'\nYou receive: Beguiler's Slippers\nArms\nYou say, 'sleeves'\nLorekeeper Brita says 'Bring unto me a set of torn enchanted silk sleeves as well as three flawed topaz.  With these in my possession I can create a set of enchanted sleeves the likes of which spellcasters like you dream of.'\nGive Brita 3x Flawed Topaz and a Torn Enchanted Silk Sleeves\nLorekeeper Brita smiles warmly as she hands you your reward.\nLorekeeper Brita says 'You have done well.'\nYou receive:  Beguiler's Sleeves\nGloves\nYou say, 'gloves'\nLorekeeper Brita says 'If you seek gloves of great power, bring to me three crushed topaz and a pair of torn enchanted silk gloves.  I will use the power of the gems to imbue the gloves.'\nGive Brita 3x Crushed Topaz and a Torn Enchanted Silk Gloves\nLorekeeper Brita smiles warmly as she hands you your reward.\nLorekeeper Brita says 'You have done well.'\nYou receive:  Beguiler's Gloves\nHelm\nYou say, 'cap'\nLorekeeper Brita says 'For an enchanted head guard bring me a torn enchanted silk turban as well as three pieces of crushed flame opal.'\nGive Brita 3x Crushed Flame Opal and an Torn Enchanted Silk Turban\nLorekeeper Brita smiles warmly as she hands you your reward.\nLorekeeper Brita says 'You have done well.'\nYou receive: Beguiler's Crown\nLegs\nYou say, 'leggings'\nLorekeeper Brita says 'Three nephrite and a pair of torn enchanted silk leggings will net you a fine set of pantaloons.'\nGive Brita 3x Nephrite and a Torn Enchanted Silk Pantaloons\nLorekeeper Brita smiles warmly as she hands you your reward.\nLorekeeper Brita says 'You have done well.'\nYou receive: Beguiler's Trousers\nChest\nYou say, 'robe'\nLorekeeper Brita says 'With three pristine emeralds and a torn enchanted silk robe I will fashion a wonderous robe for you.'\nGive Brita 3x Pristine Emerald and a Torn Enchanted Silk Robe\nLorekeeper Brita smiles warmly as she hands you your reward.\nLorekeeper Brita says 'You have done well.'\nYou receive: Beguiler's Robe\nSubmitted by: BobbybickRewards:\n- Beguiler's Crown [item=4545]\n- Beguiler's Gloves [item=4541]\n- Beguiler's Robe [item=4892]\n- Beguiler's Sleeves [item=4147]\n- Beguiler's Slippers [item=3952]\n- Beguiler's Trousers [item=4872]\n- Beguiler's Wristguard [item=4771]\n[",
    },
    {
      id = "8311",
      title = "Magician Thurgadin Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 45,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Kyla Frostbeard",
      loc = { y = -122.0, x = 231.0, z = 0.0 },
      triggers = {
        "Hail, Kyla Frostbeard",
        "I am a magician",
        "wristbands",
        "boots",
        "sleeves",
        "gloves",
        "cap",
        "leggings",
      },
      items_required = {
      },
      rewards = {
        { id = 4570, name = "Arch Mage's Boots", type = "item" },
        { id = 4509, name = "Arch Mage's Crown", type = "item" },
        { id = 4799, name = "Arch Mage's Gloves", type = "item" },
        { id = 4701, name = "Arch Mage's Pantaloons", type = "item" },
        { id = 5096, name = "Arch Mage's Robe", type = "item" },
        { id = 4843, name = "Arch Mage's Sleeves", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 45\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nKyla Frostbeard found inside Frostbeard's Furs and Leather offers a series of quests for magicians to obtain a set of Arch Mage's Armor. She can be found around location -122, 231.\nYou must be at least KINDLY with Coldain in order to complete these quests.\nYou say, 'Hail, Kyla Frostbeard'\nKyla Frostbeard says, 'Greetings to you. I seek those who call themselves magicians. Are you a magician, little one?'\nYou say, 'I am a magician'\nKyla Frostbeard says, 'I thought so.  I have several tasks for you accomplish.  Once you have completed them I will have a cap, a robe, sleeves, wristbands, gloves, leggings and boots to reward you with.'\nTorn Enchanted Silk armor molds drop from giants in the Kael Arena. Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Onyx Sapphire + Torn Enchanted Silk Wristband\nBoots  - 3x Crushed Jaundice Gem + Torn Enchanted Silk Boots\nArms - 3x Flawed Topaz + Torn Enchanted Silk Sleeves\nGloves - 3x Crushed Topaz + Torn Enchanted Silk Gloves\nHelm - 3x Crushed Flame Opal + Torn Enchanted Silk Turban\nLegs - 3x Nephrite + Torn Enchanted Silk Pantaloons\nChest - 3x Pristine Emerald + Torn Enchanted Silk Robe\nBracer\nYou say, 'wristbands'\nKyla Frostbeard says 'An enchanted silk wristguard and three crushed onyx sapphires is all that I require to create an imbued wrist wrap of great power.  Seek out these items and return to me when you have acquired them.'\nGive Kyla 3x Crushed Onyx Sapphire and a Torn Enchanted Silk Wristband\nKyla Frostbeard smiles warmly as he hands you your reward.\nKyla Frostbeard says 'You have done well.'\nYou receive: Arch Mage's Warband\nBoots\nYou say, 'boots'\nKyla Frostbeard says 'Three crushed jaundice gems combined with torn enchanted silk boots would make a most interesting set of footwear.  The latent powers of the gems can be harnessed to create magical effects.'\nGive Kyla 3x Crushed Jaundice Gem and a Torn Enchanted Silk Boots\nKyla Frostbeard smiles warmly as he hands you your reward.\nKyla Frostbeard says 'You have done well.'\nYou receive: Arch Mage's Boots\nArms\nYou say, 'sleeves'\nKyla Frostbeard says 'Bring unto me a set of torn enchanted silk sleeves as well as three flawed topaz.  With these in my possession I can create a set of enchanted sleeves the likes of which spellcasters like you dream of.'\nGive Kyla 3x Flawed Topaz and a Torn Enchanted Silk Sleeves\nKyla Frostbeard smiles warmly as he hands you your reward.\nKyla Frostbeard says 'You have done well.'\nYou receive:  Arch Mage's Sleeves\nGloves\nYou say, 'gloves'\nKyla Frostbeard says 'If you seek gloves of great power, bring to me three crushed topaz and a pair of torn enchanted silk gloves.  I will use the power of the gems to imbue the gloves.'\nGive Kyla 3x Crushed Topaz and a Torn Enchanted Silk Gloves\nKyla Frostbeard smiles warmly as he hands you your reward.\nKyla Frostbeard says 'You have done well.'\nYou receive:  Arch Mage's Gloves\nHelm\nYou say, 'cap'\nKyla Frostbeard says 'For an enchanted head guard bring me a torn enchanted silk turban as well as three pieces of crushed flame opal.'\nGive Kyla 3x Crushed Flame Opal and an Torn Enchanted Silk Turban\nKyla Frostbeard smiles warmly as he hands you your reward.\nKyla Frostbeard says 'You have done well.'\nYou receive: Arch Mage's Crown\nLegs\nYou say, 'leggings'\nKyla Frostbeard says 'Three nephrite and a pair of torn enchanted silk leggings will net you a fine set of pantaloons.'\nGive Kyla 3x Nephrite and a Torn Enchanted Silk Pantaloons\nKyla Frostbeard smiles warmly as he hands you your reward.\nKyla Frostbeard says 'You have done well.'\nYou receive: Arch Mage's Pantaloons\nChest\nYou say, 'robe'\nKyla Frostbeard says 'With three pristine emeralds and a torn enchanted silk robe I will fashion a wonderous robe for you.'\nGive Kyla 3x Pristine Emerald and a Torn Enchanted Silk Robe\nKyla Frostbeard smiles warmly as he hands you your reward.\nKyla Frostbeard says 'You have done well.'\nYou receive: Arch Mage's Robe\nSubmitted by: BobbybickRewards:\n- Arch Mage's Boots [item=4570]\n- Arch Mage's Crown [item=4509]\n- Arch Mage's Gloves [item=4799]\n- Arch Mage's Pantaloons [item=4701]\n- Arch Mage's Robe [item=5096]\n- Arch Mage's Sleeves [item=4843]\n- Arch Mage's Warband [item=4465]\n[",
    },
    {
      id = "8312",
      title = "Necromancer Thurgadin Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 45,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Lorekeeper Zorik",
      loc = { y = -92.0, x = 774.0, z = 0.0 },
      triggers = {
        "Hail, Lorekeeper Zorik",
        "I am a necromancer",
        "I will undertake your tasks",
        "wristbands",
        "boots",
        "sleeves",
        "gloves",
        "cap",
      },
      items_required = {
      },
      rewards = {
        { id = 5005, name = "Warlock's Boots", type = "item" },
        { id = 4584, name = "Warlock's Crown", type = "item" },
        { id = 4666, name = "Warlock's Gloves", type = "item" },
        { id = 4697, name = "Warlock's Pantaloons", type = "item" },
        { id = 4968, name = "Warlock's Robe", type = "item" },
        { id = 4601, name = "Warlock's Sleeves", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 45\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nLorekeeper Zorik found inside the Thurgadin Library offers a series of quests for necromancers to obtain a set of Warlock's Armor. She can be found around location -92, 774.\nYou must be at least KINDLY with Coldain in order to complete these quests.\nYou say, 'Hail, Lorekeeper Zorik'\nLorekeeper Zorik says, 'I seek those who practice the art of dark magicks. I seek those who call themselves necromancers. Are you a necromancer'\nYou say, 'I am a necromancer'\nLorekeeper Zorik says, 'Excellent. Are you sure enough of your skills to undertake my tasks? If not, get out of my sight, weakling!'\nYou say, 'I will undertake your tasks'\nLorekeeper Zorik says, 'I thought so. One should never back down from a challenge. Once you have completed them, I will have a cap, a robe, sleeves, wristbands, gloves, leggings and boots to reward you with.'\nTorn Enchanted Silk armor molds drop from giants in the Kael Arena. Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Onyx Sapphire + Torn Enchanted Silk Wristband\nBoots  - 3x Crushed Jaundice Gem + Torn Enchanted Silk Boots\nArms - 3x Flawed Topaz + Torn Enchanted Silk Sleeves\nGloves - 3x Crushed Topaz + Torn Enchanted Silk Gloves\nHelm - 3x Crushed Flame Opal + Torn Enchanted Silk Turban\nLegs - 3x Nephrite + Torn Enchanted Silk Pantaloons\nChest - 3x Pristine Emerald + Torn Enchanted Silk Robe\nBracer\nYou say, 'wristbands'\nLorekeeper Zorik says 'An enchanted silk wristguard and three crushed onyx sapphires is all that I require to create an imbued wrist wrap of great power.  Seek out these items and return to me when you have acquired them.'\nGive Zorik 3x Crushed Onyx Sapphire and a Torn Enchanted Silk Wristband\nLorekeeper Zorik smiles warmly as she hands you your reward.\nLorekeeper Zorik says 'You have done well.'\nYou receive: Warlock's Wristguard\nBoots\nYou say, 'boots'\nLorekeeper Zorik says 'Three crushed jaundice gems combined with torn enchanted silk boots would make a most interesting set of footwear.  The latent powers of the gems can be harnessed to create magical effects.'\nGive Zorik 3x Crushed Jaundice Gem and a Torn Enchanted Silk Boots\nLorekeeper Zorik smiles warmly as she hands you your reward.\nLorekeeper Zorik says 'You have done well.'\nYou receive: Warlock's Boots\nArms\nYou say, 'sleeves'\nLorekeeper Zorik says 'Bring unto me a set of torn enchanted silk sleeves as well as three flawed topaz. With these in my possession I can create a set of enchanted sleeves the likes of which spellcasters like you dream of.'\nGive Zorik 3x Flawed Topaz and a Torn Enchanted Silk Sleeves\nLorekeeper Zorik smiles warmly as she hands you your reward.\nLorekeeper Zorik says 'You have done well.'\nYou receive:  Warlock's Sleeves\nGloves\nYou say, 'gloves'\nLorekeeper Zorik says 'If you seek gloves of great power, bring to me three crushed topaz and a pair of torn enchanted silk gloves.  I will use the power of the gems to imbue the gloves.'\nGive Zorik 3x Crushed Topaz and a Torn Enchanted Silk Gloves\nLorekeeper Zorik smiles warmly as she hands you your reward.\nLorekeeper Zorik says 'You have done well.'\nYou receive:  Warlock's Gloves\nHelm\nYou say, 'cap'\nLorekeeper Zorik says 'For an enchanted head guard bring me a torn enchanted silk turban as well as three pieces of crushed flame opal.'\nGive Zorik 3x Crushed Flame Opal and an Torn Enchanted Silk Turban\nLorekeeper Zorik smiles warmly as she hands you your reward.\nLorekeeper Zorik says 'You have done well.'\nYou receive: Warlock's Crown\nLegs\nYou say, 'leggings'\nLorekeeper Zorik says 'Three nephrite and a pair of torn enchanted silk leggings will net you a fine set of pantaloons.'\nGive Zorik 3x Nephrite and a Torn Enchanted Silk Pantaloons\nLorekeeper Zorik smiles warmly as she hands you your reward.\nLorekeeper Zorik says 'You have done well.'\nYou receive: Warlock's Pantaloons\nChest\nYou say, 'robe'\nLorekeeper Zorik says 'If you wish to have a fine robe, bring unto me a torn enchanted silk robe and three pristine emeralds. Then you will receive a robe beyond your wildest dreams.'\nGive Zorik 3x Pristine Emerald and a Torn Enchanted Silk Robe\nLorekeeper Zorik smiles warmly as she hands you your reward.\nLorekeeper Zorik says 'You have done well.'\nYou receive: Warlock's Robe\nSubmitted by: BobbybickRewards:\n- Warlock's Boots [item=5005]\n- Warlock's Crown [item=4584]\n- Warlock's Gloves [item=4666]\n- Warlock's Pantaloons [item=4697]\n- Warlock's Robe [item=4968]\n- Warlock's Sleeves [item=4601]\n- Warlock's Wristguard [item=4891]\n[",
    },
    {
      id = "8314",
      title = "Berserker Thurgadin Armor",
      exp = "02",
      exp_name = "The Scars of Velious",
      min_lvl = 45,
      max_lvl = 125,
      quest_type = "Quest",
      repeatable = true,
      group_size = "Solo",
      npc = "Glatigi",
      loc = { y = 5.0, x = -545.0, z = 0.0 },
      triggers = {
        "Hail, Glatigi",
        "I am interested",
        "bracers",
        "boots",
        "sleeves",
        "gauntlets",
        "coif",
        "leggings",
      },
      items_required = {
      },
      rewards = {
        { id = 26701, name = "Icefury Boots", type = "item" },
        { id = 26516, name = "Icefury Bracer", type = "item" },
        { id = 29787, name = "Icefury Coif", type = "item" },
        { id = 26703, name = "Icefury Gauntlets", type = "item" },
        { id = 26702, name = "Icefury Greaves", type = "item" },
        { id = 26518, name = "Icefury Sleeves", type = "item" },
      },
      factions = {
      },
      walkthrough = "**Level:** 45\n**Maximum Level:** 125\n**Monster Mission:** No\n**Repeatable:** Yes\n**Can Be Shrouded?:** No\n**Quest Type:** Quest\n**Group Size:** Solo\n\nGlatigi found near the mines in Thurgadin offers a series of quests for berserkers to obtain a set of Icefury Armor. He can be found around location 5, -545.\nYou must be at least KINDLY with Coldain in order to complete these quests.\nYou say, 'Hail, Glatigi'\nGlatigi says, 'Well met, (playerrace)! I am Glatigi. If ye seek ta join our ranks, I welcome ye with open arms and have an offer to make if you are interested. If ye seek to be our enemy, I hope ye can run swifter than my archers arrows.'\nYou say, 'I am interested'\nGlatigi says, 'Aye, I thought ye might be. My elite Berserkers are in sore need of some enchanted armor. Unfortunately, I canâ€™t spare the men to go out and fetch me the components. If you can do this for me, Iâ€™ll gladly reward you with a piece of it. I need materials for a coif, a tunic, sleeves, bracers, gauntlets, leggings, and boots.'\nCorroded Armor molds drop from giants in the Kael Arena. Gems can be found on a variety of different creatures throughout velious with some, such as diamonds, coming from higher level creatures.\nQUICK LIST\nBracer - 3x Crushed Flame Emerald + Corroded Chain Bracer\nBoots - 3x Crushed Black Marble + Corroded Chain Boots\nArms - 3x Flawed Emerald + Corroded Chain Sleeves\nGloves - 3x Crushed Topaz + Corroded Chain Gauntlets\nHelm - 3x Crushed Coral + Corroded Chain Coif\nLegs - 3x Flawed Sea Sapphire + Corroded Chain Leggings\nChest - 3x Flawless Diamond + Corroded Chain Tunic\nBracer\nYou say, 'bracers'\nGlatigi says, 'For the bracers, I will require a corroded chain bracer as well as three crushed flame emeralds.  Return to me when you find such things, (playername).'\nGive Glatigi 3x Crushed Flame Emerald and a Corroded Chain Bracer\nGlatigi smiles warmly as he hands you your reward.\nGlatigi says 'You have done well.'\nYou receive: Icefury Bracer\nBoots\nYou say, 'boots'\nGlatigi says, 'We use our feet so often, should not they be protected as well as any other portion of our bodies?  If you seek fine protection for your feet, return to me with three pieces of crushed black marble and a set of corroded chain boots.'\nGive Glatigi 3x Crushed Black Marble and a Corroded Chain Boots\nGlatigi smiles warmly as he hands you your reward.\nGlatigi says 'You have done well.'\nYou receive: Icefury Boots\nArms\nYou say, 'sleeves'\nGlatigi says, 'Protection for your arms will come at the price of three flawed emeralds and a set of corroded chain sleeves.'\nGive Glatigi 3x Flawed Emerald and a Corroded Chain Sleeves\nGlatigi smiles warmly as he hands you your reward.\nGlatigi says 'You have done well.'\nYou receive: Icefury Sleeves\nGloves\nYou say, 'gauntlets'\nGlatigi says, 'Protecting your hands is very important.  I can forge protection for your hands if you bring me a pair of corroded chain gauntlets and three crushed topaz.'\nGive Glatigi 3x Crushed Topaz and a Corroded Chain Gauntlets\nGlatigi smiles warmly as he hands you your reward.\nGlatigi says 'You have done well.'\nYou receive: Icefury Gauntlets\nHelm\nYou say, 'coif'\nGlatigi says, 'To create a piece of armor to protect your sensitive skull. I will require three pieces of crushed coral as well as a corroded chain coif.'\nGive Glatigi 3x Crushed Coral and an Corroded Chain Coif\nGlatigi smiles warmly as he hands you your reward.\nGlatigi says 'You have done well.'\nYou receive: Icefury Coif\nLegs\nYou say, 'leggings'\nGlatigi says, 'A set of corroded chain leggings might be salvageable if you were to find three flawed sea sapphires.  With the right techniques and ingredients almost anything is possible.'\nGive Glatigi 3x Flawed Sea Sapphire and a Corroded Chain Leggings\nGlatigi smiles warmly as he hands you your reward.\nGlatigi says 'You have done well.'\nYou receive: Icefury Greaves\nChest\nYou say, 'tunic'\nGlatigi says, 'For the breastplate, I will need a corroded chain tunic and three flawless diamonds. Once I have them in my possession it will not take long to craft a sturdy tunic.'\nGive Glatigi 3x Flawless Diamond and a Corroded Chain Tunic\nGlatigi smiles warmly as he hands you your reward.\nGlatigi says 'You have done well.'\nYou receive: Icefury Tunic\nSubmitted by: BobbybickRewards:\n- Icefury Boots [item=26701]\n- Icefury Bracer [item=26516]\n- Icefury Coif [item=29787]\n- Icefury Gauntlets [item=26703]\n- Icefury Greaves [item=26702]\n- Icefury Sleeves [item=26518]\n- Icefury Tunic [item=26517]\n[",
    },
  },
}
