-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for Unkempt Woods (unkemptwoods)
-- Total Quests: 6
-- ============================================================================

return {
  zone = "unkemptwoods",
  zone_name = "Unkempt Woods",
  quests = {
    {
      id = "12621",
      title = "Avian Threat",
      exp = "30",
      exp_name = "Laurion's Song",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Bowyer Essana",
      loc = nil,
      triggers = {
        "Hail, Bowyer Essana",
        "I would like to restore the balance.",
        "I can take on the Aviak population.",
        "I can reduce their population.",
        "_Quests_",
        "balance",
        "pest control",
        "Rallosians",
      },
      items_required = {
      },
      rewards = {
        { id = 148417, name = "Intact Aviak Feather", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Unkempt Woods [zone=1326]\n**Who:**\n- Bowyer Essana [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 110\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n**Quest Items:**\n- Intact Aviak Feather [item=148417]\n**Related Creatures:**\n- an aviak clutchtender [npc=59429]\n- an aviak elder [npc=59430]\n- an aviak hunter [npc=59431]\n**Era:** | !Laurion's Song\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Fri Nov 3 03:25:03 2023\nModified: Sat Jan 27 07:59:24 2024 | | **Laurion's Song Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this solo task from Bowyer Essana [npc=59438] in Unkempt Woods. You can find Bowyer Essana at /waypoint -2236, -2975, -298 in the far southeast corner of the zone in the Elddar camp. He is on the find tool as well CTRL F.\nYou say, 'Hail, Bowyer Essana'\nBowyer Essana says, 'Welcome. I do not have anything for your manner of weapon, but if you are here for work, I may have a few assignments to restore the [balance] of the land.'\nYou say, 'I would like to restore the balance.'\nBowyer Essana says, 'Very good. You may have your pick from the job lists.' She looks over her sheet. 'It looks like we have [pest control], going to the frontlines with the [Rallosians], or reducing the [Aviak] population. Do you have a preference?'\nYou say, 'I can take on the Aviak population.'\nBowyer Essana says, 'I fear the Aviaks have grown distrustful of our people, and others here. They are a danger to our people, the dwarves, and each other. It is difficult, as they could have once been allies, but we believe they will continue to wreak havoc on the land as long as the Rallosians are initiating the chaos. Could you [reduce] the number of Aviaks in the area?'\nYou say, 'I can reduce their population.'\nYou have been assigned the task 'Avian Threat'.\nBowyer Essana says, 'Please bring their intact feathers as proof of the job done. The Elddar give their thanks for your assistance with thining out the Aviaks of the Wood.'\n\n---\n\nAs in-tune with nature as the Elddar Elves are, Bowyer Essana has some recommendations to help ease the balance of the Unkempt Woods. With the Rallosians causing havoc with the land, the Aviaks have grown untrusting of everything. It saddens Essana, but in order for the young Elddar to be safe, the Aviak numbers must be reduced.\n1\\. Gather 5 Intact Aviak Feathers 0/5 Unkempt Woods\nIntact Aviak Feather [item=148417] drops off aviaks in the southwest corner.\n\n---\n\nReward(s):\n141 platinum 6 gold 6 silver 7 copper\nYou gain experience!\n**Submitted by:** Gidono",
    },
    {
      id = "12622",
      title = "Balancing Biodiversity",
      exp = "30",
      exp_name = "Laurion's Song",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Bowyer Essana",
      loc = nil,
      triggers = {
        "Hail, Bowyer Essana",
        "I would like to restore the balance.",
        "I",
        "I accept.",
        "_Quests_",
        "balance",
        "pest control",
        "Rallosians",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Unkempt Woods [zone=1326]\n**Who:**\n- Bowyer Essana [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 120\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Era:** | !Laurion's Song\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Fri Nov 3 03:26:34 2023\nModified: Sat Mar 2 13:20:24 2024 | | **Laurion's Song Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this solo task from Bowyer Essana [npc=59438] in Unkempt Woods. You can find Bowyer Essana at /waypoint -2236, -2975, -298 in the far southeast corner of the zone in the Elddar camp. He is on the find tool as well CTRL F.\nYou say, 'Hail, Bowyer Essana'\nBowyer Essana says, 'Welcome. I do not have anything for your manner of weapon, but if you are here for work, I may have a few assignments to restore the [balance] of the land.'\nYou say, 'I would like to restore the balance.'\nBowyer Essana says, 'Very good. You may have your pick from the job lists.' She looks over her sheet. 'It looks like we have [pest control], going to the frontlines with the [Rallosians], or reducing the [Aviak] population. Do you have a preference?'\nYou say, 'I'm interested in pest control.'\nBowyer Essana says, 'Okay, I shall make this quick then. You have no doubt seen the destruction in the northwest. As a result of the deforestation occurring near the shoreline, there is a severe loss of local fauna. This has actually allowed the area, and the rest of the Woods, to become a breeding ground for various pests, taking the area out of balance. We seek someone\nwho can reduce the population of bats, beetles, and spiders that have made their home here.\nDo you [accept] this quest?'\nYou say, 'I accept.'\nYou have been assigned the task 'Balancing Biodiversity'.\nBowyer Essana says, 'Very good. I have your name down for taking out the local pests. Also, thank you for your service to the land.'\n\n---\n\nAs in-tune with nature as the Elddar Elves are, Bowyer Essana has some recommendations to help ease the balance of the Unkempt Woods. The deforestation done by the Rallosians has decreased the amount of space for fauna to graze, and has resulted in an increase in the population of spiders, beetles, and bats in the area. She has requested a few to be killed to help restore the balance.\n1\\. Kill 8 spiders, beetles, and bats within Unkempt Woods 0/8 Unkempt Woods\n\n---\n\nReward(s):\n141pp 6gp 6sp 7cp\nExperience: At Level 124 - 1.035%\n**Submitted by:** Gidono",
    },
    {
      id = "12623",
      title = "Invasive Species",
      exp = "30",
      exp_name = "Laurion's Song",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Bowyer Essana",
      loc = nil,
      triggers = {
        "Hail, Bowyer Essana",
        "I would like to restore the balance.",
        "I can take down some Rallosians.",
        "I want to take on the invaders.",
        "_Quests_",
        "balance",
        "pest control",
        "Rallosians",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Unkempt Woods [zone=1326]\n**Who:**\n- Bowyer Essana [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 120\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Era:** | !Laurion's Song\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Fri Nov 3 03:28:48 2023\nModified: Sat Mar 2 13:21:23 2024 | | **Laurion's Song Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this solo task from Bowyer Essana [npc=59438] in Unkempt Woods. You can find Bowyer Essana at /waypoint -2236, -2975, -298 in the far southeast corner of the zone in the Elddar camp. He is on the find tool as well CTRL F.\nYou say, 'Hail, Bowyer Essana'\nBowyer Essana says, 'Welcome. I do not have anything for your manner of weapon, but if you are here for work, I may have a few assignments to restore the [balance] of the land.'\nYou say, 'I would like to restore the balance.'\nBowyer Essana says, 'Very good. You may have your pick from the job lists.' She looks over her sheet. 'It looks like we have [pest control], going to the frontlines with the [Rallosians], or reducing the [Aviak] population. Do you have a preference?'\nYou say, 'I can take down some Rallosians.'\nBowyer Essana says, 'This is not your war to fight, however if you do wish to run to the front lines to take care of the invaders, it would not be without thanks by me and my kin. Please mindfully consider if this is what you [want to] do.'\nYou say, 'I want to take on the invaders.'\nYou have been assigned the task 'Invasive Species'.\nBowyer Essana says, 'I am surprised. That is the most dangerous of the lot. I have your name down for the Rallosians. Do be careful out there. Thank you for your service to the land.'\n\n---\n\nAs in-tune with nature as the Elddar Elves are, Bowyer Essana has some recommendations to help ease the balance of the Unkempt Woods. The deforestation done by the Rallosians has caused many issues to the Elddar and others attempting to live here naturally. Please help reduce their number to keep the war, and damage to nature, from growing.\n1\\. Kill 10 Rallosians within Unkempt Woods 0/10 Unkempt Woods\n\n---\n\nReward(s):\n141pp 6gp 6sp 7cp\nExperience: At Level 124 - 1.035% and 1 Mercenary AA point\n**Submitted by:** Gidono",
    },
    {
      id = "12624",
      title = "Righteous Reforestation",
      exp = "30",
      exp_name = "Laurion's Song",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Thornel Grayleaf - Unkempt Woods",
      loc = nil,
      triggers = {
        "Hail, Thornel Grayleaf",
        "I appreciate the welcome.",
        "Tell me about this great land.",
        "A test?",
        "I have a moment. I can plant a seed or two.",
        "Hail, Provisioner Aiwyn",
        "_Quests_",
        "_General Goods_",
      },
      items_required = {
      },
      rewards = {
        { id = 148427, name = "Compiled Rallosian Intelligence", type = "item" },
        { id = 148424, name = "Empty Watering Pitcher", type = "item" },
        { id = 148425, name = "Filled Watering Pitcher", type = "item" },
        { id = 148423, name = "Hearty Seed Packet", type = "item" },
        { id = 148426, name = "Rallosian Intelligence", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Unkempt Woods [zone=1326]\n**Who:**\n- Thornel Grayleaf - Unkempt Woods [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 120\n**Maximum Level:** | 130\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Compiled Rallosian Intelligence [item=148427]\n- Empty Watering Pitcher [item=148424]\n- Filled Watering Pitcher [item=148425]\n- Hearty Seed Packet [item=148423]\n- Rallosian Intelligence [item=148426]\n**Related Creatures:**\n- Provisioner Aiwyn [ _General Goods_]\n**Related Quests:**\n- Partisan of Unkempt Woods (15 Points) [quest=12659]\n**Era:** | !Laurion's Song\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Fri Nov 3 03:31:58 2023\nModified: Tue Apr 28 11:14:49 2026 | | **Laurion's Song Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\nYou can obtain this solo task from Thornel Grayleaf [npc=59668] in Unkempt Woods. You can find Thornel at /waypoint +2648, -3283, -279 . He is on the find tool as well CTRL-F.\nYou say, 'Hail, Thornel Grayleaf'\nThornel Grayleaf says, 'Hail and well met, newcomer. [Welcome] to the Unkempt Woods. I do hope you did not suffer any troubles to get to us, particularly considering the aggression at the river. '\nYou say, 'I appreciate the welcome.'\nThornel Grayleaf says, 'Good, good! Please, allow me to introduce myself. I am Thornel Grayleaf of the Elddar. My newfound friend here is Dagnor.'\nDagnor Butcherblock smiles and waves a well-worked hand. 'Hey. Good ta meetcha'.'\nThornel Grayleaf says, 'I have no doubt you were directed here, as we were, by the great Mother Tunare herself to tend to this [great land].'\nYou say, 'Tell me about this great land.'\nThornel Grayleaf says, 'The Elddar were pulled here - our hearts were pulled here - by the great goddess Tunare, herself. We are to be the wardens of this land, along with our dwarven neighbors. Yet... we are faced with our first [test] of our patience and dedication to the cause.'\nYou say, 'A test?'\nDagnor Butcherblock says, 'Aye, the damned Rallosians 'ave come ta shore. They be strippin' tha woods of all flora, leavin' it but dirt.'\nThornel Grayleaf mournfully shakes his head as he looks out to the western horizon. 'And not a [seed] planted to replace the bounty they have spoiled.'\nYou say, 'I have a moment. I can plant a seed or two.'\nYou have been assigned the task 'Righteous Reforestation'.\nThornel Grayleaf says, 'If it was that easy, our guards would have done it hundreds of times over by now, but alas, the frontline is a warzone. Our people have fallen back to regroup, but the Rallosians are not so keen on taking a break for our benefit. However, if you are up to the challenge, then I will not turn away an offer sent from the gods to keep and restore our beautiful land. Please go south to the Elddar village, and find the provisioner. Ask her for seeds, and she can assist from there.'\n\n---\n\n1\\. Hail Provisioner Aiwyn at the Elddar camp to request the seeds for Thornel 0/1 Unkempt Woods\nProvisioner Aiwyn [npc=59444] is located in the far southeastern part of the zone in the Elddar camp, near Bowyer Essana [npc=59438].\nYou say, 'Hail, Provisioner Aiwyn'\nYour task 'Righteous Reforestation' has been updated.\nProvisioner Aiwyn says, 'Oh, friend, hello! You say you need some seeds? For Thornel, I presume? I have some nice hardy specimens here that should put up with a bit of a beating.' She reaches into a small rucksack and pulls out a thin packet of seeds. 'Here you go, free of charge so long as they are planted within the Woods. While you are at it, you will need some quality water. I would recommend pulling from the southern shore, but be mindful of the local aviaks.'\nYou receive a Hearty Seed Packet [item=148423] and an Empty Watering Pitcher [item=148424].\n2\\. Gather water from the clean south end of the river 0/1 Unkempt Woods\nGather water at /way -2495, +2661, -296.\n3\\. Take down several Rallosians who may interfere 0/7 Unkempt Woods\n_Rallosian Intelligence appears on your cursor after the 7th Rallosian is killed. Plenty of Rallosians in the north west part of the zone._\n4\\. Plant and water a seed in the clearcut area 0/1 Unkempt Woods\n_/way 1215, 1720, -295 is one of the locations to plant the seeds, little mounds of dirt in the northwest section of the zone._\n5\\. Take the Rallosian Intelligence you found to Thornel Grayleaf 0/1 Unkempt Woods\nYou offered 1 Rallosian Intelligence to Thornel Grayleaf.\nYour task 'Righteous Reforestation' has been updated.\nThornel Grayleaf says, 'Oh, you found intel during your task? Magnificent, friend.'\nYou complete the trade with Thornel Grayleaf.\n6\\. Bring Thornel the Hearty Seed Packet you got from Provisioner Aiwyn 0/1 Unkempt Woods\nYou offered 1 Hearty Seed Packet to Thornel Grayleaf.\nYour task 'Righteous Reforestation' has been updated.\nThornel Grayleaf says, 'Ah, the seeds! Perfect. These are good quality seeds, too. Thanks for planting a few. I will try to get the others planted soon.'\nYou complete the trade with Thornel Grayleaf.\n7\\. Bring Thornel the Filled Watering Pitcher 0/1 Unkempt Woods\nYou offered 1 Filled Watering Pitcher to Thornel Grayleaf.\nYour task 'Righteous Reforestation' has been updated.\nThornel Grayleaf says, 'There is some water left. Great! I will hold onto this for later.'\nYou complete the trade with Thornel Grayleaf.\n8\\. Check in with Thornel Grayleaf for your next steps 0/1 Unkempt Woods\nYou say, 'Hail, Thornel Grayleaf'\nYou have been given: Compiled Rallosian Intelligence\nYour task 'Righteous Reforestation' has been updated.\nThornel Grayleaf says, 'You not only managed to get a seed planted within the barren soil, but found some intelligence from our enemy. You are truly a gift from Tunare herself. Please, take this intel, posthaste, to the Dal'Vie Captain back at the village. He will know what to do with it from there.'\n9\\. Take the Compiled Rallosian Intelligence to the Dal`Vie Captain in the Elddar Village 0/1 Unkempt Woods\nYou offered 1 Compiled Rallosian Intelligence to Dal`Vie Captain.\nYour task 'Righteous Reforestation' has been updated.\nDal`Vie Captain pauses and looks over the documentation provided by the adventurer. 'We will comb through this, newcomer. Thank you. Additionally, please let Thornel know that he also has our thanks.'\nYou complete the trade with Dal`Vie Captain.\n10\\. Hail Thornel Grayleaf again to let him know the status of the delivery 0/1 Unkempt Woods\nYou say, 'Hail, Thornel Grayleaf'\nYour task 'Righteous Reforestation' has been updated.\nThornel Grayleaf appreciates your assistance in helping restore the Unkempt Woods.\nYou receive 7 copper .\nYou receive 6 silver .\nYou receive 6 gold .\nYou receive 141 platinum .\nYou have gained 1 mercenary ability point(s)!\nYou have gained 10 ability point(s)!\nYou gain experience! (1.122%) - At Level 123\nThornel Grayleaf says, 'I am eternally thankful for your assistance in trying to restore our beautiful Woods. The battle is not over, so if you do have some time to spare, please speak with Dagnor here, and he will be able to fill you in on some next steps.'\n\n---\n\nReward(s):\n141pp 6g 6s 7cp\nExperience\n**Submitted by:** Gidono",
    },
    {
      id = "12856",
      title = "The Blades of My Enemy",
      exp = "30",
      exp_name = "Laurion's Song",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Dagnor Butcherblock",
      loc = nil,
      triggers = {
        "Hail, Dagnor Butcherblock",
        "What request is that?",
        "Do you want me to take care of this threat?",
        "The ore?",
        "I",
        "_Quests_",
        "request",
        "threat",
      },
      items_required = {
      },
      rewards = {
        { id = 148435, name = "Bladesmith's Kit", type = "item" },
        { id = 148441, name = "Broken Dwarven-Rallosian Concept Sword", type = "item" },
        { id = 148440, name = "Dwarven-Rallosian Concept Sword", type = "item" },
        { id = 146359, name = "Rallosian Ore Chest", type = "item" },
        { id = 148433, name = "Rallosian Warblade", type = "item" },
        { id = 148434, name = "Thick Treant Branch", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Unkempt Woods [zone=1326]\n**Who:**\n- Dagnor Butcherblock [ _Quests_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 120\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Bladesmith's Kit [item=148435]\n- Broken Dwarven-Rallosian Concept Sword [item=148441]\n- Dwarven-Rallosian Concept Sword [item=148440]\n- Rallosian Ore Chest [item=146359]\n- Rallosian Warblade [item=148433]\n- Thick Treant Branch [item=148434]\n**Related Creatures:**\n- an enchanted dummy [npc=59436]\n**Related Quests:**\n- Partisan of Unkempt Woods (15 Points) [quest=12659]\n- Righteous Reforestation [quest=12624]\n**Era:** | !Laurion's Song\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Fri Dec 22 02:20:09 2023\nModified: Mon Jun 22 18:45:46 2026 | | **Laurion's Song Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\n**Prerequisite Task: Righteous Reforestation [quest=12624]**\n\n---\n\nYou can obtain this solo task from Dagnor Butcherblock [npc=59439] in Unkempt Woods. You can find Dagnor at the far northeastern corner of the zone at /way 2650, -3271, -280 He is on the find tool as well CTRL F.\nYou say, 'Hail, Dagnor Butcherblock'\nDagnor Butcherblock says, 'Oy. Thanks fer helpin' Thornel here. Frankly, I 'ave a [request] meself.'\nYou say, 'What request is that?'\nDagnor Butcherblock says, 'The war is greater than just strippin' the soil. That's just the start! We dwarves appreciate the world beneath our feet, down ta the Valley o' the Dawn, but threats ta the world above is a [threat] ta the world below.'\nYou say, 'Do you want me to take care of this threat?'\nDagnor Butcherblock says, 'We'll need ta strike the Rallosians head on, lest they get bold. Not just that, but ye could pull the rug out from under them by takin' their [ore].'\nYou say, 'The ore?'\nDagnor Butcherblock says, 'Aye, their ore n' weapons. Disarm 'em while givin' us some intelligence on their arsenal. I 'ave been wantin' to get me hands on their smithin'. Are ye [up to it]?'\nYou say, 'I'm up to it.'\nDagnor Butcherblock says, 'Thanks, n' remember, I need ye to snag some ore n' weapons. The ore's likely closer ta their ships, but ye might 'ave ta fight 'em fer their weapons.'\nYou have been assigned the task 'The Blades of My Enemy'.\n\n---\n\nThornel Grayleaf's cohort, Dagnor Butcherblock, is eager to take things into his own hands, or rather, into the adventurer's hands. He doesn't just want to directly attack the Rallosians, but also to confiscate their ore. Between the confiscated ore and some examples of ogre-crafted weapons using that ore, Dagnor should be able to reverse engineer their weapons.\nTry to sneak onto the Rallosian ships to find the shipments of ore.\n1\\. Sneak onto the Rallosian ships and search for the ore 0/1 Unkempt Woods\nUpdates when you get near a ship or on the ships themselves.\n2\\. Collect 3 Rallosian Ore Chests 0/3 Unkempt Woods\nRallosian Ore Chests [item=146359] are on the ships and the shore on crates. You don't break invis. Respawn time isn't bad. I'm tri-boxing and by the time the first is done, the 2nd can go.\n\\- for me, top 2 ships had the treasure in the room (I'm not a sailor, sorry for not knowing the lingo). The south boat had it on the bow behind the room. Or maybe the stern. I can't tell which way is forward.\n3\\. Collect 8 Rallosian Warblades from Rallosian forces 0/8 Unkempt Woods\nKill Rallosians, until you get 8 Rallosian Warblade.\n4\\. Return 3 Rallosian Ore Chests to Dagnor Butcherblock 0/3 Unkempt Woods\nYou offered 3 Rallosian Ore Chest to Dagnor Butcherblock.\nYour task 'The Blades of My Enemy' has been updated.\nYour task 'The Blades of My Enemy' has been updated.\nYour task 'The Blades of My Enemy' has been updated.\nDagnor Butcherblock says, 'Aye, this is the stuff.'\nYou complete the trade with Dagnor Butcherblock.\n5\\. Return 8 Rallosian Warblades to Dagnor Butcherblock 0/8 Unkempt Woods\nYou offered 8 Rallosian Warblade to Dagnor Butcherblock.\nYour task 'The Blades of My Enemy' has been updated.\nYour task 'The Blades of My Enemy' has been updated.\nYour task 'The Blades of My Enemy' has been updated.\nYour task 'The Blades of My Enemy' has been updated.\nYour task 'The Blades of My Enemy' has been updated.\nYour task 'The Blades of My Enemy' has been updated.\nYour task 'The Blades of My Enemy' has been updated.\nYour task 'The Blades of My Enemy' has been updated.\nDagnor Butcherblock says, 'Great weapon. Used, but of good quality.'\nYou complete the trade with Dagnor Butcherblock.\n6\\. Check in with Dagnor Butcherblock for you next steps 0/1 Unkempt Woods\nYou say, 'Hail, Dagnor Butcherblock'\nYour task 'The Blades of My Enemy' has been updated.\nDagnor Butcherblock says, 'Ah, that's some good work there. I'm gon' get a good dwarven blade hammered from some o' the ore, so if ye've time, can ye snag somethin' more fer me? If ye can go up on the Treant Hill n' gather a branch from the treants there, I can use that as a hilt. By the time ye get back, yer other parts'll be done n' ready for buildin' out the sword.'\n7\\. Obtain 1 Thick Treant Branch on Treant Hill 0/1 Unkempt Woods\nTreants are found in the high country, a bit SE of the boats. The area can be reached from the west with ease. Map shows one spot from the south. Treants are aggro. One kill dropped 3 branches (3 players in the group).\n8\\. Return 1 Thick Treant Branch to Dagnor Butcherblock 0/1 Unkempt Woods\nHe gives you a Bladesmith's Kit [item=148435] as well as Dwarven-Rallosian Blade [item=148438], Dwarven-Rallosian Guard [item=148436], Dwarven-Rallosian Hilt [item=148439] and Dwarven-Rallosian Pommel [item=148437].\n9\\. Construct the Dwarven-Rallosian Concept Sword in the Bladesmith's kit 0/1 ALL\nPut the 4 in the Bladesmith's Kit and combine to make a Dwarven-Rallosian Concept Sword [item=148440].\n10\\. Test the Dwarven-Rallosian Concept Sword on an enchanted dummy 0/1 Unkempt Woods\nan enchanted dummy [npc=59436] is in the south camp. You don't have to equip the blade. Just target a dummy and right-click on it 3 times.\n11\\. Return the weapon shards to Dagnor Butcherblock 0/1 Unkempt Woods\nHand him your Broken Dwarven-Rallosian Concept Sword [item=148441].\nYou offered 1 Broken Dwarven-Rallosian Concept Sword to Dagnor Butcherblock.\nYour task 'The Blades of My Enemy' has been updated.\nAlthough the concept blade could not withstand use on the enchanted armor dummies in the Elddar village, this provides a lot of intel regarding Rallosian blade style and ore.\nYou receive 7 copper .\nYou receive 6 silver .\nYou receive 6 gold .\nYou receive 141 platinum .\nYou have gained 1 mercenary ability point(s)!\nYou have gained 10 ability point(s)!\nYou gain experience! (1.122%) - At level 123\nYou complete the trade with Dagnor Butcherblock.\n\n---\n\nReward(s):\n141 platinum 6 gold 6 silver 7 copper\nYou gain experience!\n**Submitted by:** Evilel",
    },
    {
      id = "12857",
      title = "A Gift of Fish",
      exp = "30",
      exp_name = "Laurion's Song",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Wegadas",
      loc = nil,
      triggers = {
        "Hail, Wegadas",
        "I can find some supplies for you.",
        "No, I insist. I don",
        "Yes, I can get one.",
        "The situation is I was ambushed by a Rallosian.",
        "The Rallosian was a shaman and had a strange signet on her.",
        "The signet has some strange markings on it.",
        "Yes, please, I could use a magnifying glass.",
      },
      items_required = {
        { name = "Wegadas the Thunder Chum 0/1 Unkempt Woods", count = 1 },
        { name = "the Jeweler's Glass to Wegadas 0/1 Unkempt Woods", count = 1 },
      },
      rewards = {
        { id = 148422, name = "Elaborate Peace Offering", type = "item" },
        { id = 148421, name = "Jeweler's Glass", type = "item" },
        { id = 148420, name = "Mysterious Signet", type = "item" },
        { id = 148419, name = "Thunder Chum", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- Unkempt Woods [zone=1326]\n**Who:**\n- Wegadas [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 120\n**Maximum Level:** | 130\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Quest\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Elaborate Peace Offering [item=148422]\n- Jeweler's Glass [item=148421]\n- Mysterious Signet [item=148420]\n- Thunder Chum [item=148419]\n**Related Creatures:**\n- Rallosian Darksergeant [npc=59446]\n- Rallosian Deathsergeant [npc=59447]\n- Rallosian Warsergeant [npc=59448]\n- a Rallosian attacker [npc=59769]\n**Related Quests:**\n- Partisan of Unkempt Woods (15 Points) [quest=12659]\n- The Blades of My Enemy [quest=12856]\n**Era:** | !Laurion's Song\nRecommended:\n**Group Size:** | Solo\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Fri Dec 22 02:35:25 2023\nModified: Tue Jan 30 17:59:05 2024 | | **Laurion's Song Info & Guides: Overview \\| Progression & Task List \\| Raiding \\| Visible Armor**\n\n---\n\n**Prerequisites: The Blades of My Enemy [quest=12856]**\n\n---\n\nYou can obtain this solo task from Wegadas [npc=59454] in Unkempt Woods. You can find Wegadas at the far southeastern corner of the zone at /way -2236, -2976, -300 He is on the find tool as well CTRL F.\nYou say, 'Hail, Wegadas'\nWegadas says, 'Oh, guests! Please, please, come and stay awhile!' He waves the adventurer closer. 'Welcome to our humble settlement. I would offer you some of the best Elddar hospitality, but I'm afraid I am woefully underprepared for it. I am low on [supplies], you see. But... BUT... I can share abundant stories.''\nYou say, 'I can find some supplies for you.'\nWegadas says, 'Oh no, I wouldn't do that to you.' He emphatically shakes his head. 'You are guests here among us, it would be rather rude of me to send you on an [errand].'\nYou say, 'No, I insist. I don't mind an errand.'\nWegadas says, 'You are very insistent, indeed.' He shakes his head in resignation and smiles to the adventurer. 'Well, if I was to honor you with our hospitality, I would recommend one of the local fish, the Thunder Chum. It is exquisite. It can be fished along the southern end of the river. But... no more than that. For the love of Tunare, no more than that! It would be the opposite of hospitable if I made you work for it. If you can [get one], I can cook it up for you in our traditional style.'\nYou say, 'Yes, I can get one.'\nYou have been assigned the task 'A Gift of Fish'.\nWegadas says, 'You will love it, I assure you. Remember, one Thunder Chum, and I'll be right here waiting for you when you get back.'\n\n---\n\nWegadas is a young druid intent on showing hospitality to the adventurers on their visit to the Elddar village. As he doesn't have the appropriate fish for the occasion, he's asked if you don't mind getting it and he'll prepare it. Nothing is ever so easy in the Unkempt Woods.\nWegadas mentioned the fish can be fished from the southern end of the river. That should be near the aviaks.\n1\\. Head to the southern end of the Unkempt river, and prepare to fish 0/1 Unkempt Woods\nOnce you are at the southern end of the river, equipping a fishing pole will immediately spawn a Rallosian attacker so be ready. Killing the Rallosian attacker will count for others in the group so you don't have to do this step for each person in the group.\n2\\. Defend yourself, and kill the Rallosian attacker 0/1 Unkempt Woods\n3\\. Loot a Mysterious Signet 0/1 Unkempt Woods\nThe Rallosian attacker drops this, loot it.\n4\\. Give Wegadas the Thunder Chum 0/1 Unkempt Woods\nYou offered 1 Thunder Chum to Wegadas.\nYour task 'A Gift of Fish' has been updated.\nWegadas says, 'This is perfect! Let me start the preparation of this fine specimen.'\nYou complete the trade with Wegadas.\n5\\. Check in with Wegads regarding what occurred 0/1 Unkempt Woods\nYou say, 'Hail, Wegadas'\nWegadas says, 'Wait, do you mean there's more to the [situation]?'\nYou say, 'The situation is I was ambushed by a Rallosian.'\nWegadas says, 'In the south? Are you sure?' He pauses in his preparation of the fish. 'Was there anything notable about [the Rallosian]?''\nYou say, 'The Rallosian was a shaman and had a strange signet on her.'\nYour task 'A Gift of Fish' has been updated.\nWegadas says, 'Oh really...' He cleans off his hands, and puts his full attention on the adventurer. 'Can you tell me more of this [signet]?''\nYou say, 'The signet has some strange markings on it.'\nWegadas says, 'Oh, do tell. Could you tell me of the markings? I can spare a [magnifying glass] if it helps.'\nYou say, 'Yes, please, I could use a magnifying glass.'\nWegadas says, 'Here you go. Don't lose it. I only have so many of them!'\n6\\. Study the inscribed imagery on the signet 0/5 Unkempt Woods\nRight click the Jeweler's Glass he gave you 5 times.\nThe first mark appears as a rough symbol of Drinal. It may be of the moon of Norrath, or of the demigod, but it is difficult to tell in this Age.\nYour task 'A Gift of Fish' has been updated.\nYou begin casting Examine Signet.\nThe second mark appears as though it was worn down over time. Just how old is this signet even in this time period?\nYour task 'A Gift of Fish' has been updated.\nYou begin casting Examine Signet.\nThe third mark appears as a bear head, the visual clear as day.\nYour task 'A Gift of Fish' has been updated.\nYou begin casting Examine Signet.\nThe fourth mark is partially chipped away, but appears as a general symbol of nature.\nYour task 'A Gift of Fish' has been updated.\nYou begin casting Examine Signet.\nThe fifth and final mark is partially chipped away, but appears as an ancient symbol of Tunare, the Mother of All. It's not like a Rallosian to hold an artifact of Tunare...\nYour task 'A Gift of Fish' has been updated.\n7\\. Give the Mysterious Signet to Wegadas 0/1 Unkempt Woods\nYou offered 1 Mysterious Signet to Wegadas.\nYour task 'A Gift of Fish' has been updated.\nWegadas says, 'This signet is... Amazing!'\nYou complete the trade with Wegadas.\n8\\. Give the Jeweler's Glass to Wegadas 0/1 Unkempt Woods\nYou offered 1 Jeweler's Glass to Wegadas.\nYour task 'A Gift of Fish' has been updated.\nWegadas says, 'This is much appreciated. Thank you for giving it back.'\nYou complete the trade with Wegadas.\n9\\. Discuss the Signet with Wegadas 0/1 Unkempt Woods\nYou say, 'Hail, Wegadas'\nWegadas says, 'This signet, based off of what you told me, and the materials it's made from, may...' He pauses as he tries to work through the logic of it all. 'It may belong to the mythical [Gihjna]. I have never seen them, but I assure you that they would not be allied with the Rallosians.'\nYou say, 'What are the Gihjna?'\nWegadas says, 'The Gihjna are great bear spirits native to this land, and the lands between the lands, and the lands beyond the lands. They and the Lujien, the great wolf spirits, were here before, and they will be here after. At least, that's what the stories say; until now, until this signet, I haven't taken much [faith] in it.'\nYou say, 'I am sorry if this discovery has shaken your faith.'\nWegadas says, 'Don't be. Don't apologize. If we're not all on a path of growth, then what are we doing with ourselves?' Shaking his head slowly, he reexamines the signet in his hand. 'I have an idea. If, and I mean IF, the Gihjna are here among us, and they have had a run-in with the Rallosians, we must [show that] we are not of the same heart as our invaders. We wish to share this land in harmony...'\nYou say, 'How do we show that?'\nWegadas says, 'I am not sure which is the best method, honestly. Should we perform a show of force to let them know that we do not appreciate the bloodthirsty invaders here? Should we offer a peace offering to show them our friendship? Should we try [both]? I am not sure if that would be too heavy-handed.'\nYou say, 'Perhaps both may be best.'\nYour task 'A Gift of Fish' has been updated.\nWegadas says, 'I suppose you're right. It's the most likely to get their attention, and the attacks on the Rallosians can only help our soldiers with pushing the invaders back.' He turns his attention towards the Thunder Chum. 'I hope you don't mind, but I will prepare this for the offering while you work your magic against the Rallosians.'\n10\\. Kill 3 Rallosian leaders 0/3 Unkempt Woods\nAny number of Rallosian Darksergeant's, Deathsergeant's, and Warsergeant's count for this step.\nRares do not count towards this step\n11\\. Kill 10 Rallosians 0/10 Unkempt Woods\nAny \"a Rallosian \\_\\_\\_\\_\\_\\_\\_\" will work for this step.\nRares and Rallosian \\_\\_\\_sergeants do not count towards this step\n12\\. Check in with Wegadas again 0/1 Unkempt Woods\nYou say, 'Hail, Wegadas'\nYou have been given: Elaborate Peace Offering\nYour task 'A Gift of Fish' has been updated.\nWegadas says, 'You have done an immense service to the Elddar people. Please know that even if this comes down to nothing, that you have helped us beyond measure. Oh! On that note...' From behind himself, he pulls out an urn, but the contents within smell savory and tantalize the senses. 'Take this to the caverns to the north. The dwarves are mining it out, but it is also the closest we have to touching the Valley of the Dawn. If they are there, they will see it and accept it.'\n13\\. Take a Peace Offering to the Dwarven tunnels 0/1 Unkempt Woods\nAt /way 2859, -3573, -429 in the middle of the pool of water inside the dwarven tunnel to the north near the zone in, right click Elaborate Peace Offering.\nThe offering sits, silent and unmoving. Nothing is happening.\nThe offering glows a soft green, as though nature itself is accepting the gift.\nWithin moments, the offering is gone. Was it sufficient? Did it go to its intended recipients?\nYour task 'A Gift of Fish' has been updated.\n14\\. Let Wegadas know how it went 0/1 Unkempt Woods\nYou say, 'Hail, Wegadas'\nYour task 'A Gift of Fish' has been updated.\nWegadas says, 'You're back! How did it go? Did you see them? Was it [accepted]?'\nYou say, 'I believe it was accepted. The urn glowed and then was simply gone.'\nWegadas says, 'I never thought we would have contact with such spirits of nature. I will endeavor to seek them out. Maybe we can grow in our knowledge of each other. Thank you. If you don't mind, can you let Thornel know? Our greatest druid should be alerted to this discovery.'\n15\\. Update Thornel Grayleaf on the situation 0/1 Unkempt Woods\nYou say, 'Hail, Thornel Grayleaf'\nYour task 'A Gift of Fish' has been updated.\nWhat was intended to be a gift to the adventurer became a gift for the Gihjna. There's magics in the Unkempt Woods that have yet to be revealed, and Thornel Grayleaf and Wegadas will be there for it.\nYou receive 7 copper .\nYou receive 6 silver .\nYou receive 6 gold .\nYou receive 141 platinum .\nYou have gained 1 mercenary ability point(s)!\nYou have gained 10 ability point(s)!\nYou gain experience! (1.122%) - At Level 123\nThornel Grayleaf says, 'You are telling me that you, and Wegadas, initiated contact with the Gihjna? If the story of them is true, then it is of utmost importance to nurture our relationship with them, and fight harder to save these shores from the Rallosians. Thank you for what you have done for the Elddar and the people of Tunare.'\nYou have gained 20 ability point(s)!\nYou have gained 8 mercenary ability point(s)!\nYou gain experience! (11.356%)\nYou have completed achievement: Partisan of Unkempt Woods\n\n---\n\nReward(s):\n141pp 6g 6s 7cp\nExperience\n**Submitted by:** NecroPost",
    },
  },
}
