-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for The Well (well)
-- Total Quests: 10
-- ============================================================================

return {
  zone = "well",
  zone_name = "The Well",
  quests = {
    {
      id = "5153",
      title = "Dtaemi \\#1: Down the Hole",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Dtaemi",
      loc = { y = -515.0, x = -780.0, z = 16.0 },
      triggers = {
        "Hail, Dtaemi",
        "Your mother?",
        "The well?",
        "How did you get stuck?",
        "I",
        "Hail, Giladan the Botanist",
        "Hail, Shalma",
        "_Quests_",
      },
      items_required = {
      },
      rewards = {
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Well [zone=750]\n**Who:**\n- Dtaemi [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Success Lockout Timer**: 06:00:00\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Zones:**\n- Feerrott, the Dream [zone=747]\n- The Grounds [zone=749]\n**Related Creatures:**\n- Giladan the Botanist [ _Quests_]\n- Shalma [npc=35810]\n- a rotdog [npc=35731]\n**Related Quests:**\n- Dtaemi #2: All Alone [quest=5154]\n- Dtaemi #3: At Peace I Will Be [quest=5155]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Oct 26 19:44:09 2010\nModified: Tue Dec 5 05:21:04 2023 | | _This is the first of three tasks in a series that begins with Dtaemi in The Well. He's found at location -515, -780, 16 (in the southern part of the easternmost cavern)._\nYou say, 'Hail, Dtaemi'\nDtaemi says 'Hello? Please help me. I've been down here a long time. My [mother] must be worried something fierce.'\nYou say, 'Your mother?'\nDtaemi says 'We came to the garden and I ran off. I knew I wasn't supposed to, but she wouldn't let me do anything. So I snuck off and found the [well].'\nYou say, 'The well?'\nDtaemi says 'I just wanted to get a closer look. But when I leaned over the edge I fell. I've been here ever since. At first I heard voices from above, but when I yelled back they couldn't hear me. Now I am [stuck] down here.'\nYou say, 'How did you get stuck?'\nDtaemi says 'I died trying to find a way out. I cannot go on knowing my mother is still looking for me. She needs to know what happened. If you can [find] her, I can finally be at rest.'\nYou say, 'I'll find her'\nDtaemi says 'Thank you. I don't know where she is now, but we had talked to one scientist type guy who was here looking at the plants. Maybe he knows where she is.'\nYou have been assigned the task 'Down the Hole'.\nDtaemi needs your help to track down his mother, who has not seen him since he was lost long ago.\n\n---\n\nSpeak to Giladan the Botanist 0/1 (The Grounds)\n_Giladan the Botanist is found at location -65, -1700, -105 (due east of the zone-in; just east of the central garden and next to Spensur, the Rk. III spell NPC)._\nYou say, 'Hail, Giladan the Botanist'\nGiladan the Botanist says 'I've got too much going on right now to answer questions. If someone can deal with those rotdogs, I am sure I would have more time for inquiries.'\nKill 5 rotdogs 0/5 (The Grounds)\n_Kill any five rotdogs to update this step. Note: Only \"a rotdog\" will update this task._\nSpeak to Giladan the Botanist 0/1 (The Grounds)\nYou say, 'Hail, Giladan the Botanist'\nGiladan the Botanist says 'A young boy? I do remember a while back some mother looking for her son. He'd apparently gotten lost but they could not find him. Quite a few searchers fell to the creature here in the garden looking for him. So they eventually had to call off the search. She finally left and went back to speak to Shalma in Feerrott about supplies. But I never saw her again.'\nSpeak to Shalma in the Feerrott 0/1 (The Feerrott)\n_Shalma is found in the Feerrott just north of the zone-in from the House of Thule. She's on the east side of the riverbank. There are undead mobs in the water, so keep a lookout._\nYou say, 'Hail, Shalma'\nShalma says 'Yes, I remember that woman. She had no means to pay for anything. But besides that, no one was willing to go look for her son since there were too many who had not returned from the last time they searched. I'd look for any signs that she'd been killed here in Feerrott.'\nKill 10 Tae Ew 0/10 (The Feerrott)\n_Any \"a Tae Ew \\_\\_\\_\\_\\_\" will do._\nSpeak to Dtaemi 0/1 (The Well)\nYou say, 'Hail, Dtaemi'\nYou have found out that Dtaemi's mother most likely died trying to search for him.\nDtaemi says 'But if she has moved on, what is keeping me here? Thank you, but I may need your help again soon.'\n_Rewards:_\n262 platinum\nExperience (about 3 AAs worth)\nFaction with Dream Delvers\n17 Dream Motes\n- Dream Mote [item=90255]",
    },
    {
      id = "5154",
      title = "Dtaemi \\#2: All Alone",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Dtaemi",
      loc = { y = -515.0, x = -780.0, z = 16.0 },
      triggers = {
        "Hail, Dtaemi",
        "What could be keeping you?",
        "Here?",
        "I don",
        "_Quests_",
        "passed",
        "keeping",
        "here",
      },
      items_required = {
      },
      rewards = {
        { id = 93220, name = "Cela's Necklace", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Well [zone=750]\n**Who:**\n- Dtaemi [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Success Lockout Timer**: 06:00:00\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Quest Items:**\n- Cela's Necklace [item=93220]\n**Related Zones:**\n- The Grounds [zone=749]\n**Related Creatures:**\n- a rotdog [npc=35731]\n- a servant of Thule [npc=36209]\n- a souring treant [npc=35738]\n**Related Quests:**\n- Dtaemi #1: Down the Hole [quest=5153]\n- Dtaemi #3: At Peace I Will Be [quest=5155]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Oct 26 19:44:15 2010\nModified: Tue Oct 26 19:50:33 2010 | | _This is the second of three tasks in a series that begins with Dtaemi in The Well. He's found at location -515, -780, 16 (in the southern part of the easternmost cavern)._\n_You must have completed his first task, \"Down the Hole\" before you can request this one._\nYou say, 'Hail, Dtaemi'\nDtaemi says 'Good, you've returned. I've been thinking about it, and there can only be two options. Either my mother, Cela, has not [passed] on, or something else is [keeping] me here.'\nYou say, 'What could be keeping you?'\nDtaemi says 'If she has died, that means that something else in the well is keeping me [here]. And we need to find out what that might be.'\nYou say, 'Here?'\nDtaemi says 'You will need to find which of these possible things is keeping me here. If you don't mind still [helping] me that is.'\nYou say, 'I don't mind still helping'\nDtaemi says 'Thank you! I would think you will need to start in the garden.'\nYou have been assigned the task 'All Alone'.\nDtaemi is convinced that his mother may still be alive. You will need to help him find evidence of her death or proof that she is alive.\n\n---\n\nKill 3 rotdogs 0/3 (The Grounds)\nKill 3 souring treants 0/3 (The Grounds)\nKill 3 servants of Thule 0/3 (The Grounds)\nLoot Cela's Necklace from a servant of Thule 0/1 (The Grounds)\n_This is a common drop from the servants._\nReturn Cela's Necklace to Dtaemi 0/1 (The Well)\nSpeak with Dtaemi 0/1 (The Well)\nYou have discovered proof of Dtaemi's mother's death. This means that something else is keeping him here.\nDtaemi says 'You found her necklace? I guess I was hoping that she was still out there somewhere. Thank you. Now at least I know that something else is keeping me here. I'll just have to find out what.'\n_Rewards:_\n262 platinum\nExperience (about 3 AAs worth)\nFaction with Dream Delvers\n17 Dream Motes\n- Dream Mote [item=90255]",
    },
    {
      id = "5155",
      title = "Dtaemi \\#3: At Peace I Will Be",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Dtaemi",
      loc = { y = -515.0, x = -780.0, z = 16.0 },
      triggers = {
        "Hail, Dtaemi",
        "What reason?",
        "I",
        "Hail, Ikaena the Bonesmith",
        "_Quests_",
        "reason",
        "Bonesmith",
      },
      items_required = {
      },
      rewards = {
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Well [zone=750]\n**Who:**\n- Dtaemi [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Success Lockout Timer**: 06:00:00\n**Factions Raised:**\n- Dream Delvers +10\n**Factions Lowered:**\n**Related Zones:**\n- The Grounds [zone=749]\n**Related Creatures:**\n- Ikaena the Bonesmith [npc=36088]\n- The Adversary [npc=36340]\n- a bone golem [npc=36087]\n- a mouth of insanity [npc=36131]\n**Related Quests:**\n- Dtaemi #1: Down the Hole [quest=5153]\n- Dtaemi #2: All Alone [quest=5154]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Oct 26 19:44:19 2010\nModified: Fri Nov 19 00:07:53 2010 | | _This is the third of three tasks in a series that begins with Dtaemi in The Well. He's found at location -515, -780, 16 (in the southern part of the easternmost cavern)._\n_You must have completed his prior two tasks before you can request this one._\nYou say, 'Hail, Dtaemi'\nDtaemi says 'I am sad about my mother's end, but I will see her again. There has to be a [reason] I am still here.'\nYou say, 'What reason?'\nDtaemi says 'I wish I knew for sure. Perhaps the [Bonesmith] can help. He knows more about this place and its inhabitants than anyone.'\nYou say, 'I'll talk to the Bonesmith'\nDtaemi says 'Thank you and be careful. The bone golems are not too smart and tend to be overly aggressive from what I remember.'\nYou have been assigned the task 'At Peace I Will Be'.\nAfter finding out that his mother is truly dead, Dtaemi asks you to find out what is keeping him here in the well.\n\n---\n\nKill 3 bone golems 0/3 (The Grounds)\nSpeak to Ikaena the Bonesmith 0/1 (The Grounds)\n_Bone golems are found throughout the northeastern corner of the Grounds. The Bonesmith is found inside the building in the same area._\nYou say, 'Hail, Ikaena the Bonesmith'\nIkaena the Bonesmith says 'If Dtaemi will not move on, it is because of the Adversary. It lives to corrupt everything good. It is the main reason nothing ever returns from the well. It is bound to the mouths of insanity that inhabit the well. I'd start there.'\nKill 2 mouths of insanity 0/2 (The Well)\n_The mouths of insanity are located all along the tunnel leading up from the pit in the northwest corner of the zone. There's also one in the tunnel south of Retta Kole._\nSpeak to the Adversary 0/1 (The Well)\n_The Adversary spawns on top of the second mouth of insanity you kill. Hail it._\n_Note: Your entire group can hail the adversary before it goes active, so everyone can get the update._\nThe Adversary says 'I knew I would be seeing you soon enough! I will devour your soul after I rend the flesh from your bones as I did to that boy!'\nThe Adversary says 'You will never leave this place alive!'\nKill the Adversary 0/1 (The Well)\n_Its difficulty is on par with trash mobs in the zone. WARNING: If you die during this step, or otherwise cause the Adversary to lose aggro and despawn, you may have to repeat the entire task to respawn him._\nThe Adversary has been slain by \\_\\_\\_\\_\\_!\nThe Adversary's corpse says 'This cannot be!'\nReturn to Dtaemi 0/1 (The Well)\nYou say, 'Hail, Dtaemi'\nYou have succeeded in freeing Dtaemi from the well so that he may join his mother.\nDtaemi says 'You mean I am finally free? I can be with my mother? Thank you for everything you have done for me. You will not be forgotten.'\n_Rewards:_\n262 platinum\nExperience (about 3 AAs worth)\nFaction with Dream Delvers\n17 Dream Motes\n\n---\n\n_Completion of this task leads into the Well's progression mission, \"No Freedom in Death\" from the Fallen Soul._\n- Dream Mote [item=90255]",
    },
    {
      id = "5156",
      title = "No Freedom in Death",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Fallen Soul",
      loc = nil,
      triggers = {
        "Hail, Fallen Soul",
        "Lost souls?",
        "What body?",
        "You think you",
        "We will help!",
        "Ready",
        "_Mission_",
        "lost souls",
      },
      items_required = {
      },
      rewards = {
        { id = 91897, name = "Tending\nPetrified Skull of the Unworthy\nRaze's Brainstem\nStolen Spear of the Soothsayer\nSword of Frozen Wind\nThulian Linked Bracer\nThulian Linked Breastplate\nVisage of Kijaemz\nMinor Nebulous Dream Fragment\nLesser Nebulous Dream Fragment\nMedian Nebulous Dream Fragment\nGreater Nebulous Dream Fragment\nGlowing Nebulous Dream Fragment\n- Distraught Tendril", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
        { id = 92613, name = "Fantastic Gem of the Garden", type = "item" },
        { id = 92626, name = "Minadra's Band of Hive-Tending", type = "item" },
        { id = 90552, name = "Petrified Skull of the Unworthy", type = "item" },
        { id = 91664, name = "Raze's Brainstem", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Well [zone=750]\n**Who:**\n- Fallen Soul [ _Mission_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Faction\n- Loot\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 06:00:00\n**Factions Raised:**\n- Dream Delvers +?\n**Factions Lowered:**\n**Related Zones:**\n- The Well: No Freedom in Death [zone=764]\n**Related Creatures:**\n- Fallen Soul [npc=36341]\n- Higher Denizen [npc=36349]\n- Lower Denizen [npc=36348]\n- Warden of the Well [npc=36350]\n- a heavy chest [npc=36342]\n- a lost soul [npc=36345]\n**Related Quests:**\n- Dtaemi #1: Down the Hole [quest=5153]\n- Dtaemi #2: All Alone [quest=5154]\n- Dtaemi #3: At Peace I Will Be [quest=5155]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Oct 26 20:25:36 2010\nModified: Tue Dec 19 17:37:26 2023 | | _This is a group progression mission (3-6 players) that begins with the Fallen Soul in the Well (located in the northern part of the large western cavern)._\n_You must have completed Dtaemi's three solo tasks prior to being able to request this task._\nYou say, 'Hail, Fallen Soul'\nFallen Soul says 'I have watched you, and others like you come and go. Some trying to help the boy, while others were fated to becoming one of the [lost souls] here.'\nYou say, 'Lost souls?'\nFallen Soul says 'I was like you once. Long ago, I came to help find the boy that was lost here, but was killed for my efforts. But instead of my soul moving on, I found myself trapped within the [body] of one of the creatures here in the well. At first it was a spider, but once that body perished, I found myself in the body of a scorpion. This has continued for a very long time. To make matters worse, I have noticed that I appear to lose just a little bit more of myself each time my soul is transferred.'\nYou say, 'What body?'\nFallen Soul says 'I believe that most of the creatures here entomb the soul of someone lost to the dangers of the cave. It seems that the more of us that die around the same time, the longer it takes before we are cast into another body. Why, I do not know... Perhaps, if all of us were [released] around the same time, we'd be freed permanently from this fate.'\nYou say, 'You think you'd be released?'\nFallen Soul says 'I don't know if that is the case, but it seems just as good an idea as any. I would guess that there appears to be about twenty of us here. The window to release us is fairly short though, so I would hurry. After some time, we seem to lose any control over our physical bodies and will attack almost anything before finally waking to find that we are, yet again, entombed within some creature. Will you [help] me... us! Will you help... Us...?'\nYou say, 'We will help!'\nFallen Soul says 'Thank you and good luck. Let me know when you are [ready] to proceed.'\nYou have been assigned the task 'No Freedom in Death'.\nYou are tasked with freeing the many souls that have been taken and entombed within the bodies of the creatures here in the well. You have only a limited amount of time to release all the souls so that they may be free from the horrible and cruel circle of pain they currently endure.\nYou must find and kill the creatures in the well in order to free the captured souls within.\nYou say, 'Ready'\nFallen Soul says 'Be careful and good luck!'\nLOADING, PLEASE WAIT...\nYou have entered The Well.\n\n---\n\nFree the lost souls within the corrupted creatures 0/20 (The Well)\n_Kill 20 of the corrupted mobs found throughout the zone._\n_Note: As of a patch in September 2012, \"a lost soul\" becomes KOS 35 minutes after its spawn. (These see invis.) The task can be completed within this time frame, but if you take longer, you may have to contend with these spawns in addition to the other parts of the task._\nSpeak to the Fallen Soul 0/1 (The Well)\nYou say, 'Hail, Fallen Soul'\nFallen Soul says 'You've done it! But you need to kill the warden. To do this you will need to kill the Lower and Higher Denizens. Then, and only then, will the Warden appear. When you do this, in the presence of the Warden, the souls you have released may attack you.'\n_This opens up the next two steps._\nKill the Lower Denizen 0/1 (The Well)\n_The Lower Denizen is found in the mud hole. (From the zone-in, take the eastern tunnel.) It hits for a max ~7,500; single-target rampages; and casts \"Power of the Low\":_\nPower of the Low: PB AE 100', Magic (-675)\n1: Decrease Hitpoints by 20000 per tick _(3 ticks)_\n2: Decrease HP when cast by 10000\n3: Slow Push (100)\n4: Increase Disease Counter by 18\nLower Denizen has been slain by \\_\\_\\_\\_\\_!\nLower Denizen's corpse explodes in meaty chunks.\nKill the Higher Denizen 0/1 (The Well)\n_The Higher Denizen is found in the southern part of the easternmost cavern._\n_It hits for a max ~7,500; flurries; and casts \"Power of the High\":_\nPower of the High: PB AE 100', Magic (-675)\n1: Decrease Hitpoints by 38000\n2: Stun (2.00 sec)\nHigher Denizen has been slain by \\_\\_\\_\\_\\_!\nHigher Denizen's corpse explodes in meaty chunks.\nKill the Warden of the Well 0/1 (The Well)\n_The Warden of the Well spawns in the center of the easternmost cavern. It hits for a max ~8,000; AE rampages; and casts \"Breath of Soul Corruption\":_\nBreath of Soul Corruption: NPC Hatelist 0', Corruption (-25)\n1: Illusion: Unknown(608)\n2: Unknown #430\n3: Unknown #431\n4: Decrease Hitpoints by 14000 per tick _(10 ticks)_\n5: Decrease Movement by 50%\n_Any Lost Souls that happen to be nearby will assist the Warden._\nWarden of the Well has been slain by \\_\\_\\_\\_\\_!\nWarden of the Well's corpse explodes in meaty chunks.\nSpeak to the Fallen Soul 0/1 (The Well)\nYou say, 'Hail, Fallen Soul'\nFallen Soul says 'We have been freed! Maybe for good this time. You have done more than I could have ever hoped. Here is what little I have to offer. Take it with my thanks. Let me know when you are ready to [go back].'\nClaim your reward from the heavy chest 0/1 (The Well)\n\n---\n\n_Task Rewards:_\nExperience (about 3% regular exp at Level 86 or 1-2 AAs worth)\n315 platinum\n60 Dream Motes\nFaction with Dream Delvers\n_Known chest rewards (1 item + 1 spell per task):_\nDistraught Tendril\nFantastic Gem of the Garden\nMinadra's Band of Hive-Tending\nPetrified Skull of the Unworthy\nRaze's Brainstem\nStolen Spear of the Soothsayer\nSword of Frozen Wind\nThulian Linked Bracer\nThulian Linked Breastplate\nVisage of Kijaemz\nMinor Nebulous Dream Fragment\nLesser Nebulous Dream Fragment\nMedian Nebulous Dream Fragment\nGreater Nebulous Dream Fragment\nGlowing Nebulous Dream Fragment\n- Distraught Tendril [item=91897]\n- Dream Mote [item=90255]\n- Fantastic Gem of the Garden [item=92613]\n- Minadra's Band of Hive-Tending [item=92626]\n- Petrified Skull of the Unworthy [item=90552]\n- Raze's Brainstem [item=91664]\n- Stolen Spear of the Soothsayer [item=93614]\n- Thulian Linked Bracer [item=90062]\n- Thulian Linked Breastplate [item=91902]\n- Visage of Kijaemz [item=94331]",
    },
    {
      id = "5175",
      title = "Aquaphobia",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Retta Kole",
      loc = { y = -430.0, x = -260.0, z = 40.0 },
      triggers = {
        "Hail, Retta Kole",
        "Camp site?",
        "Why can",
        "_Quests_",
        "camp",
        "leave",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Well [zone=750]\n**Who:**\n- Retta Kole [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +5\n**Factions Lowered:**\n**Related Creatures:**\n- a grown nayat [npc=36132]\n- a young nayat [npc=36545]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 2 01:44:39 2010\nModified: Thu Oct 20 06:59:25 2011 | | _This is a solo kill task that begins with Retta Kole in The Well. She's located at -430, -260, 40 (in the southern part of the first open cavern)._\nYou say, 'Hail, Retta Kole'\nRetta Kole says 'You there! Where are we? I knew I should not have left the [camp] site. They'll dock my pay if I don't show up by dawn!'\nYou say, 'Camp site?'\nRetta Kole says 'My employer and my friends are there. I'm a sellsword; a mercenary. And my team is going to be missing me if I don't show up. I must have been exploring the area and hit my head, since I have a really awful headache. But more importantly, I can't even [leave].'\nYou say, 'Why can't you leave?'\nRetta Kole says 'Look, I fear nothing on the battlefield. Retta Kole is no coward. However, deep water makes my skin crawl. I can't explain it. And those nayats here, and in the water outside this tunnel. They cling to you and keep you down! I can't go out there. You have no idea how embarrassing this is to admit, but I just can't do it. Please, destroy the nayats. You'll have my eternal gratitude. In the meantime, I have to conjure the courage to swim in that water.'\nYou have been assigned the task 'Aquaphobia'.\nRetta has asked you to destroy the nayats infesting the waters and caverns. While capable of fighting herself, she fears the deep water, and refuses to confront them in this situation. Kill all the nayats and return to Retta with the news.\n\n---\n\nDestroy the young nayats 0/3 (The Well)\nDestroy the grown nayats 0/3 (The Well)\n_Nayats are found throughout the tunnels and caverns in the zone._\nSpeak with Retta Kole 0/1 (The Well)\nYou say, 'Hail, Retta Kole'\nThe jelly creatures called nayets have been destroyed. Retta the mercenary can now escape, assuming she can conquer her fear of swimming in deep water.\n_Rewards:_\nExperience\nMinor Faction with Dream Delvers",
    },
    {
      id = "5176",
      title = "Slithering",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Morrin Fredricks",
      loc = { y = -140.0, x = -860.0, z = 22.0 },
      triggers = {
        "Hail, Morrin Fredricks",
        "I see them...",
        "_Quests_",
        "see",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Well [zone=750]\n**Who:**\n- Morrin Fredricks [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +5\n**Factions Lowered:**\n**Related Creatures:**\n- a cave viper [npc=36547]\n- a pit viper [npc=36550]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 2 01:44:44 2010\nModified: Thu May 30 23:26:46 2019 | | _This is a solo kill task that begins with Morrin Fredricks in The Well. He's located at -140, -860, 22 (in the northern part of the easternmost open cavern)._\nYou say, 'Hail, Morrin Fredricks'\nMorrin Fredricks says 'Oh! You startled me. I'm in a bit of a panic at the moment, I'm afraid. Didn't you [see] them?'\nYou say, 'I see them...'\nMorrin Fredricks says 'Snakes! Scorpions! Spiders! All sorts of creepy crawlies. I can't stand any of them. I'm a baker, not a pest exterminator! Please help me! I just want to get out of here.'\n_A task window opens up offering three tasks._\nYou have been assigned the task 'Slithering'.\nYou've been asked to eliminate the snakes that are slithering around the cavern. Morrin is too frightened to even attempt to escape for fear of being bitten and poisoned.\n\n---\n\nExterminate cave vipers 0/3 (The Well)\nExterminate pit vipers 0/2 (The Well)\nSpeak with Morrin Fredricks 0/1 (The Well)\nYou say, 'Hail, Morrin Fredricks'\nYou've killed off a majority of the snakes that have infested the caverns. This should put Morrin's mind at ease.\nYour faction with Dream Delvers got better.\n_Rewards:_\nExperience and Minor Faction with Dream Delvers based on your level\nAt level 85, 5 Faction and 1% EXP\n- Faction and Experience",
    },
    {
      id = "5177",
      title = "Spider Fright",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Morrin Fredricks",
      loc = { y = -140.0, x = -860.0, z = 22.0 },
      triggers = {
        "Hail, Morrin Fredricks",
        "I see them...",
        "_Quests_",
        "see",
      },
      items_required = {
        { name = "him the good news", count = 1 },
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Well [zone=750]\n**Who:**\n- Morrin Fredricks [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +5\n**Factions Lowered:**\n**Related Creatures:**\n- a dark spider [npc=36122]\n- a pit spider [npc=36126]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 2 01:44:47 2010\nModified: Sun Oct 23 05:22:00 2011 | | _This is a solo kill task that begins with Morrin Fredricks in The Well. He's located at -140, -860, 22 (in the northern part of the easternmost open cavern)._\nYou say, 'Hail, Morrin Fredricks'\nMorrin Fredricks says 'Oh! You startled me. I'm in a bit of a panic at the moment, I'm afraid. Didn't you [see] them?'\nYou say, 'I see them...'\nMorrin Fredricks says 'Snakes! Scorpions! Spiders! All sorts of creepy crawlies. I can't stand any of them. I'm a baker, not a pest exterminator! Please help me! I just want to get out of here.'\n_A task window opens up offering three tasks._\nYou have been assigned the task 'Spider Fright'.\nMorrin has asked you to kill the spiders that are creeping around the cavern. Once you've destroyed them, return to Morrin and give him the good news.\n\n---\n\nExterminate dark spiders 0/3 (The Well)\nExterminate pit spiders 0/2 (The Well)\nSpeak with Morrin Fredricks 0/1 (The Well)\nYou say, 'Hail, Morrin Fredricks'\nThe spiders have been cleared out thanks to your work. Morrin and any others trapped in this cave can now move a little more freely.\nYour faction standing with Dream Delvers got better.\n_Rewards:_\nExperience\nMinor Faction with Dream Delvers",
    },
    {
      id = "5179",
      title = "Drowned in Mud",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Dahlmar Raltend",
      loc = { y = 15.0, x = -335.0, z = -35.0 },
      triggers = {
        "Hail, Dahlmar Raltend",
        "You didn",
        "What mud?",
        "_Quests_",
        "map",
        "mud",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Well [zone=750]\n**Who:**\n- Dahlmar Raltend [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n**Factions Raised:**\n- Dream Delvers +5\n**Factions Lowered:**\n**Related Creatures:**\n- a mud golem [npc=36544]\n- a sludge golem [npc=36130]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 2 01:44:54 2010\nModified: Tue Jul 7 00:37:08 2015 | | _This is a solo kill task that begins with Dahlmar Raltend in The Well. He's an Erudite located at 15, -335, -35 (next to the mud pool at the end of the tunnel east from the zone-in)._\nYou say, 'Hail, Dahlmar Raltend'\nDahlmar Raltend says 'Where am I? How did we get here? Those horrid mud creatures are closing in, and I can't find an exit! I can't remember how I got here, and I didn't even bring a [map].'\nYou say, 'You didn't bring a map?'\nDahlmar Raltend says 'I'm a cartographer, so I always have my maps on me. Still, would it even help me? Especially with all of this [mud] here. I'm going to lose my mind if I can't get out of here!'\nYou say, 'What mud?'\nDahlmar Raltend says 'This mud. It reminds me of the quicksand that almost killed me when I was a child. I nearly drowned in it! I can't shake the horrible memories. Please, you have to help me. I'm sure I can help us get out of here, but you'll need to destroy these mud creatures first. I'm no fighter!'\nYou have been assigned the task 'Drowned in Mud'.\nYou've been asked to destroy the mud creatures that are terrorizing Dahlmar. They seem to be emerging from the slippery mud pool room, but might be elsewhere as well.\n\n---\n\nDestroy mud golems 0/3 (The Well)\nDestroy sludge golems 0/3 (The Well)\n_Golems can be found in the mud pool room as well as the tunnel leading out of the area (there's a small pit in the bottom of the mud pool that leads to the tunnel out)._\nSpeak with Dahlmar Raltend 0/1 (The Well)\nYou say, 'Hail, Dahlmar Raltend'\nYour task 'Drowned in Mud' has been updated.\nYou've cleared out the mud golems and given Dahlmar some peace of mind. There are bound to be more emerging from the muck, however.\nDahlmar Raltend says 'Thank you so much. Maybe I can find a way out of here now!'\n_Rewards:_\nExperience\nMinor Faction with Dream Delvers (+5)",
    },
    {
      id = "5180",
      title = "All Is Not Forgotten Part 1",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Traelphor",
      loc = { y = -310.0, x = -665.0, z = 30.0 },
      triggers = {
        "Hail, Traelphor",
        "It",
        "Whole?",
        "Your soul?",
        "I can help",
        "_Quest_",
        "_Lackey_",
        "time",
      },
      items_required = {
        { name = "Traelphor the Primary scroll", count = 1 },
        { name = "Traelphor the Secondary scroll", count = 1 },
        { name = "Traelphor the Tertiary scroll", count = 1 },
      },
      rewards = {
        { id = 93036, name = "Traelphor's Primary Scroll", type = "item" },
        { id = 93038, name = "Traelphor's Secondary Scroll", type = "item" },
        { id = 93037, name = "Traelphor's Tertiary Scroll", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Well [zone=750]\n**Who:**\n- Traelphor [ _Quest_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Factions Raised:**\n- Dream Delvers +10\n**Factions Lowered:**\n**Quest Items:**\n- Traelphor's Primary Scroll [item=93036]\n- Traelphor's Secondary Scroll [item=93038]\n- Traelphor's Tertiary Scroll [item=93037]\n**Related Zones:**\n- The Grounds [zone=749]\n**Related Creatures:**\n- Argamis [npc=36552]\n- Plomaedis [ _Lackey_]\n- a mouth of insanity [npc=36131]\n**Related Quests:**\n- All Is Not Forgotten Part 2 [quest=5181]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 2 02:12:02 2010\nModified: Mon Dec 13 02:43:55 2010 | | _This shared task (1-6 players) is the first of two that begins with Traelphor in The Well. He's located at -310, -665, 30 ((n the tunnel that leads out of the easternmost cavern -- its entrance is a false wall)._\nYou say, 'Hail, Traelphor'\nTraelphor says 'Is it [time]? I am here. Always here.'\nYou say, 'It's time'\nTraelphor says 'But I am not ready! I am not complete! I cannot leave. No life! No life will I have until I am [whole]!'\nYou say, 'Whole?'\nTraelphor says 'A sly one you are! You take my [soul] and leave me here to rot, and now you pretend to not remember! What manner of game is this?'\nYou say, 'Your soul?'\nTraelphor says 'Is that it then? You wish me to relive my agony? My despair? I have not forgotten! I will never forget! And to make matters worse, you hide the location of my very being from anyone who might have helped. Now no one will [help]!'\nYou say, 'I can help'\nTraelphor says 'Surely you will deceiver! Teller of lies! You would do best to stick with mocking your lackey Plomaedis in the garden. I am sure he will do whatever it takes to please your wickedness. '\nYou have been assigned the task 'All Is Not Forgotten Part 1'.\nTraelphor is still unconvinced that you are trying to help him. You must find out what you can from Plomaedis about what you need to do to help Traelphor.\nFor someone who has so little time for anything, Plomaedis sure talks a lot. You may only need to listen to him to get the clue you need.\n\n---\n\nTalk to Plomaedis 0/1 (The Grounds)\n_Plomaedis is found at location -840, -2435, -235 in the Grounds._\nKill Plomaedis' pet, Argamis 0/1 (The Grounds)\nRetrieve the Primary scroll from the well. 0/1 (The Well)\nRetrieve the Secondary scroll from the well. 0/1 (The Well)\nRetrieve the Tertiary scroll from the well. 0/1 (The Well)\n_The above scrolls are random drops through The Well._\nReturn to Traelphor and speak with him. 0/1 (The Well)\nGive Traelphor the Primary scroll. 0/1 (The Well)\nGive Traelphor the Secondary scroll. 0/1 (The Well)\nGive Traelphor the Tertiary scroll. 0/1 (The Well)\nSpeak with Traelphor. 0/1 (The Well)\n_Rewards:_\n315 platinum\nExperience (about 4 AAs worth)\nFaction with Dream Delvers\n20 Dream Motes\n\n---\n\n_Completion of this task leads into a second task, \"All Is Not Forgotten, Part 2\"._\n- Dream Mote [item=90255]",
    },
    {
      id = "5181",
      title = "All Is Not Forgotten Part 2",
      exp = "17",
      exp_name = "House of Thule",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Traelphor",
      loc = { y = -310.0, x = -665.0, z = 30.0 },
      triggers = {
        "Hail, Traelphor",
        "The scrolls are clues?",
        "Where",
        "What is the Maorda?",
        "_Quest_",
        "_Devourer of Souls_",
        "time",
        "scrolls",
      },
      items_required = {
      },
      rewards = {
        { id = 93040, name = "Traelphor's Final Scroll", type = "item" },
        { id = 90255, name = "Dream Mote", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- The Well [zone=750]\n**Who:**\n- Traelphor [ _Quest_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 85\n**Maximum Level:** | 90\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Faction\n- Money\n**Factions Raised:**\n- Dream Delvers +10\n**Factions Lowered:**\n**Quest Items:**\n- Traelphor's Final Scroll [item=93040]\n**Related Creatures:**\n- Maorda [npc=36551]\n- Raejic [ _Devourer of Souls_]\n**Related Quests:**\n- All Is Not Forgotten Part 1 [quest=5180]\n**Era:** | !House of Thule\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Tue Nov 2 02:12:20 2010\nModified: Tue Jan 4 21:48:42 2011 | | _This shared task (1-6 players) is the second of two that begins with Traelphor in The Well. He's located at -310, -665, 30 ((n the tunnel that leads out of the easternmost cavern -- its entrance is a false wall)._\n_You must have completed his first task, \"All Is Not Forgotten Part 1\" before you can request this one._\nYou say, 'Hail, Traelphor'\nTraelphor says 'I am surprised you have returned this [time]. No one has made much of effort to help me in the past. And those who have tried have never returned. But I see that the [scrolls] you have found are indeed the clues to name of the one responsible for my present condition.'\nYou say, 'The scrolls are clues?'\nTraelphor says 'It appears that the answers to the scrolls are the key to deciphering the [final] scroll. The writings within it will no doubt appear to be gibberish. But by applying the key properly, you should be able to read it.'\nYou say, 'Where's the final one?'\nTraelphor says 'You will need to find the final scroll here in the well. I have been pondering this. And I think it is the [Maorda] that has it. '\nYou say, 'What is the Maorda?'\nTraelphor says 'A vile creature in the employ of the one responsible. It occasionally appears to feast on creatures here in the well. It seems to have a particular taste for spiders. I am sure if you bait him with the dead bodies of the spiders, it will come to feast.'\nYou have been assigned the task 'All Is Not Forgotten Part 2'.\n\n---\n\nKill 10 spiders 0/10 (The Well)\nSpeak to Traelphor 0/1 (The Well)\n_NOTE: Hailing Traelphor triggers the spawn of Maorda. You may want to clear nearby trash mobs before doing this as Maorda flees at low health. He doesn't cast any spells._\nKill Maorda 0/1 (The Well)\n_Maorda is slowable and snareable, and not much harder than other trash mobs in the zone._\nLoot the Final Scroll from Maorda 0/1 (The Well)\nTell Traelphor the name you deciphered from the Final Scroll 0/1 (The Well)\n_Translation of the final scroll's text:_\nHe lives to deceive, for he is the deceiver. He is Raejic, the devourer of souls.\n_Say to Traelphor, \"Raejic\"._\nKill Raejic 0/1 (The Well)\n_Raejic is the same as Maorda: Slowable and snareable, and not much harder than other trash mobs in the zone. He doesn't cast any spells._\n_The task auto-completes as Raejic dies._\n_Rewards:_\n? platinum\nExperience\nFaction with Dream Delvers\n? Dream Motes\n- Dream Mote [item=90255]",
    },
  },
}
