-- ============================================================================
-- TRIUNE QUEST GUIDE: Zone Package for East Wastes, Zeixshi-Kar's Awakening (zeixshi-kar's awakening=eastwastesshard)
-- Total Quests: 12
-- ============================================================================

return {
  zone = "zeixshi-kar's awakening=eastwastesshard",
  zone_name = "East Wastes, Zeixshi-Kar's Awakening",
  quests = {
    {
      id = "6042",
      title = "HO-HO-Help!",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Silnik",
      loc = { y = -1820.0, x = 2930.0, z = 144.0 },
      triggers = {
        "Hail, Silnik",
        "Fall?",
        "Your companions?",
        "Backfired?",
        "I will help",
        "_Quest_",
        "fall",
        "companions",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- East Wastes, Zeixshi-Kar's Awakening [zone=868]\n**Who:**\n- Silnik [ _Quest_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Related Creatures:**\n- a Ry`Gorr legionnaire [npc=41545]\n- a coldain missionary [npc=41529]\n- a frost giant savage [npc=41536]\n- mystic of Ry`Gorr [npc=41580]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 28 18:38:24 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with a giant named Silnik ( map) at /location -1820, 2930, 144 in Zeixshi-Kar's Awakening (outside the giant fort in the northwestern part of the zone)._\nYou say, 'Hail, Silnik'\nSilnik glances down, then suddenly turns pale and closes his eyes, and starts to clutch desperately at the banner behind him, 'Dear Brell! I'm going to [fall]!'\nYou say, 'Fall?'\nSilnik says 'I'm not good with heights; they make me dizzy. Gnomes just aren't cut out for things like this!' He opens one eye carefully, keeping his gaze carefully skyward. After a few deep breaths he relaxes a bit and asks hopefully, in your general direction, 'I don't suppose my [companions] sent you to help me?'\nYou say, 'Your companions?'\nSilnik says 'Baffod, Taelanie, and Tramric. Baffod somehow managed to get lost - again - and I wound up being left alone while Taelanie went to find him, and Tramric went to scout ahead. So when I saw a pair of giants approaching, I cast an illusion, to disguise myself as a giant, in the hopes of avoiding a fight. But it [backfired].'\nYou say, 'Backfired?'\nSilnik says 'The next thing I knew, I'd been recruited to join their army. I can't even sneak away to escape; whenever I move I get dizzy. It's all because of this blasted illusion! If I could just turn back into a Gnome, I'd be fine, but I don't dare take off my disguise with so many enemies around. Won't you [help] me?'\nYou say, 'I will help'\nSilnik says 'Thank Brell! If you could cause a distraction - maybe rid the fort here of some of its inhabitants? - that might allow me to sneak away unnoticed.'\nYou have been assigned the task 'HO-HO-Help!'.\nSilnik has asked you to slay the inhabitants of the fort so she can finally remove her disguise and return to her friends.\n\n---\n\nSlay the inhabitants of the fort 0/8 (Zeixshi-Kar's Awakening)\n_Kill mobs inside the giant fort._\n_Note: You may need to be inside the giant fort in order to get credit. If you pull mobs outside the fort, then only the first player to aggro the mob will get credit (or no credit will be given at all)._\nSpeak with Silnik 0/1 (Zeixshi-Kar's Awakening)\n_Reward:_\n112 platinum, 5 gold\nExperience",
    },
    {
      id = "5981",
      title = "Hunter of East Wastes: Zeixshi-Kar's Awakening",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Unknown",
      loc = nil,
      triggers = {
        "_Rain of Fear_",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- East Wastes, Zeixshi-Kar's Awakening [zone=868]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | No\n**Can Be Shrouded?:** | No\n**Quest Type:** | Achievement\n**Quest Goal:**\n- Advancement\n**Related Creatures:**\n- Boradain Glacierbane [npc=41153]\n- Chief Ry`Gorr [npc=41154]\n- Corbin Blackwell [npc=41155]\n- Drummon Coldshanks [npc=41156]\n- Ekelng Thunderstone [npc=41157]\n- Firband the Black [npc=41158]\n- Fjloaren Icebane - East Wastes [npc=41159]\n- Galrok the Cold [npc=41160]\n- Ghrek Squatnot [npc=41161]\n- Kurlok the Mad [npc=41162]\n- Nightmane [npc=41163]\n- Tain Hammerfrost [ _Rain of Fear_]\n- Tungo [npc=41165]\n- Warden Bruke [npc=41166]\n- Yngaln the Frozen [npc=41167]\n**Related Quests:**\n- Adept Hunter of Rain of Fear [quest=6205]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 28 05:27:02 2012\nModified: Tue Aug 12 11:25:06 2025 | | This is a Hunter achievement for Rain of Fear.\nThis achievement is gained upon defeating the following rare monsters in Zeixshi-Kar's Awakening:\nBoradain Glacierbane\nChief Ry`Gorr\nCorbin Blackwell\nDrummon Coldshanks\nEkelng Thunderstone\nFirband the Black\nFjloaren Icebane\nGalrok the Cold\nGhrek Squatnot\nKurlok the Mad\nNightmane\nTain Hammerfrost\nTungo\nWarden Bruke\nYngaln the Frozen\n_Reward:_\nNone\n\n---\n\n_\"eastwastesshard\" map file (also click links to the left for location information):_\nP 2029.26, 7792.53, 147.56, 127, 0, 0, 1, Boradain\\_Glacierbane\nP 4395.33, 3338.22, 144.47, 127, 0, 0, 1, Chief\\_Ry`Gorr\nP 3137.49, 598.43, 154.83, 127, 0, 0, 1, Corbin\\_Blackwell\nP -450.61, 3786.56, 145.13, 127, 0, 0, 1, Firband\\_the\\_Black\nP -267.61, 3878.17, 149.02, 127, 0, 0, 1, Firband\\_the\\_Black\nP -3004.54, 5987.90, 144.48, 127, 0, 0, 1, Fjloaren\\_Icebane\nP -3344.76, 6156.53, 164.95, 127, 0, 0, 1, Fjloaren\\_Icebane\nP -3065.74, 6511.07, 171.73, 127, 0, 0, 1, Fjloaren\\_Icebane\nP 277.82, 7742.19, 182.44, 127, 0, 0, 1, Galrok\\_the\\_Cold\nP -3464.75, 2092.28, 154.95, 127, 0, 0, 1, Ghrek\\_Squatnot\nP -2045.54, 8384.85, 183.07, 127, 0, 0, 1, Tungo\\_(general\\_vicinity)\nP -1898.62, 1932.75, 168.11, 127, 0, 0, 1, Warden\\_Bruke\nP -4676.12, 8758.12, 157.12, 127, 0, 0, 1, Nightmare\nP -4773.12, 8212.12, 149.12, 127, 0, 0, 1, Nightmare\nP -4443.12, 805.122, 168.12, 127, 0, 0, 1, Nightmare\nP -389.12, -96.12, 11.12, 127, 0, 0, 1, Kurlok\\_the\\_Mad\nP 120.12, -500.12, 11.12, 127, 0, 0, 1, Kurlok\\_the\\_Mad\nP 468.97, -32.88, -13.25, 127, 0, 0, 1, Kurlok\\_the\\_Mad\nP -2400.12, 130.12, 145.12, 127, 0, 0, 1, Drummon\\_Coldshaks\nP -253.85, 3552.92, 147.80, 127, 0, 0, 1, Tain\\_Hammerfrost\nP -150.93, 3636.54, 147.76, 127, 0, 0, 1, Tain\\_Hammerfrost\nP -1310.8231, 3353.2146, 255.4815, 127, 0, 0, 2, Yngaln\\_the\\_Frozen\nP -1128.5681, 3122.6614, 223.5883, 127, 0, 0, 2, Yngaln\\_the\\_Frozen\nP -1249.9794, 3570.5708, 194.7695, 127, 0, 0, 2, Yngaln\\_the\\_Frozen\nP -3166.03, 1470.91, 157.46, 127, 0, 0, 2, Ekelng\\_Thunderstone",
    },
    {
      id = "6026",
      title = "Zeixshi-Kar \\#1: Scaring Up Some Information",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Gildorn Icebreath",
      loc = { y = -8115.0, x = 3160.0, z = 147.0 },
      triggers = {
        "Hail, Gildorn Icebreath",
        "Really use?",
        "Where did they wander off?",
        "I will help",
        "Hail, Treasure Hunter Robairn",
        "Stop them, how?",
        "Robairn sent me.",
        "_Quests_",
      },
      items_required = {
        { name = "us a clue to what is happening", count = 1 },
        { name = "the coin", count = 1 },
      },
      rewards = {
        { id = 107996, name = "Mysterious Token", type = "item" },
        { id = 106475, name = "Samhain Costume", type = "item" },
        { id = 107790, name = "Samhain Head", type = "item" },
        { id = 107791, name = "Tattered Clothing", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- East Wastes, Zeixshi-Kar's Awakening [zone=868]\n**Who:**\n- Gildorn Icebreath [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Mysterious Token [item=107996]\n- Samhain Costume [item=106475]\n- Samhain Head [item=107790]\n- Tattered Clothing [item=107791]\n**Related Creatures:**\n- Falmia [npc=41572]\n- Jornin [npc=41577]\n- Treasure Hunter Robairn [npc=41582]\n- Yalfi [npc=41585]\n- a suspicious Ry`Gorr [npc=41556]\n- a suspicious coldain [npc=41554]\n- a suspicious frost giant [npc=41555]\n**Related Quests:**\n- Confronting Your Fears [quest=6030]\n- Defeat Zeixshi-Kar [quest=6031]\n- Raid Expedition: Zeixshi-Kar's Shard [quest=6032]\n- Zeixshi-Kar #2: Indoctrination [quest=6027]\n- Zeixshi-Kar #3: The Sacrifice [quest=6028]\n- Zeixshi-Kar #4: The Sweet Taste of Revenge [quest=6029]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 28 18:06:26 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is the first task in a series of four, a shared task (1-6 players) that begins with Gildorn Icebreath ( map) in Zeixshi-Kar's Awakening. He is found at /location -8115, 3160, 147 (outside some Coldain huts that are due south of the entrance to the canyon that leads to Kael Drakkel)._\n_Pre-Requisites:_\n\\- Level 85\n\\- No tasks\nYou say, 'Hail, Gildorn Icebreath'\nGildorn Icebreath says 'I don't know if you are extremely foolish, or just brave to a fault to be traveling these lands right now, but either way I could [really use] your help right about now.'\nYou say, 'Really use?'\nGildorn Icebreath says 'Ever since that strange shard fell from the sky and embedded itself in the tundra, strange things have been going on. First, the nightmarish creatures appeared, and then my entire clan decided to [wander off] and not return.'\nYou say, 'Where did they wander off?'\nGildorn Icebreath says 'My clan was once twenty strong, and now only I remain. My entire clan disappeared the other night while I was asleep and never returned. Yesterday, I saw one of my clan members near the shard. I hailed him and he just ignored me as if he didn't know who I was. When I tried to get closer to see if he was perhaps injured, he ran off. I gave chase, but was attacked by a fearsome steed of pure darkness. Perhaps you can try to [help] me figure out what is going on?'\nYou say, 'I will help'\nGildorn Icebreath says 'I have seen some Coldain, Ry`Gorr, and Frost Giants doing something near the shard recently. Perhaps if you could defeat one of these suspicious beings, you might find something on their corpse to give us a clue to what is happening.'\nYou have been assigned the task 'Scaring Up Some Information'.\nGildorn Icebreath needs your help to learn why his clan disappeared into the Wastes.\nFind and defeat a suspicious Coldain, Ry'Gorr, or Frost Giant. Gildorn has seen them near the site of the shard's impact.\n\n---\n\nFind and defeat a suspicious Coldain, Ry'Gorr, or frost giant 0/1 (Zeixshi-Kar's Awakening)\n_The Ry`Gorr ( map) is known to appear at -5160, -115, 160 (a little ways south-southeast of Crystal Caverns)._\n_The Coldain ( map) is known to appear at -4735, -780, 150 (southeast of the Crystal Caverns)._\n_The Frost Giant ( map) is known to appear at -5150, 545, 153 (directly south of the Crystal Caverns entrance)._\n_Note: These cast a targeted AE called \"Taste of Fear\" (decreases spell haste by 50%)._\nLoot a mysterious coin from the suspicious Coldain, Ry'Gorr, or frost giant's corpse 0/1 (Zeixshi-Kar's Awakening)\n\n---\n\nGive the mysterious coin to Gildorn Icebreath 0/1 (Zeixshi-Kar's Awakening)\nSpeak with Gildorn Icebreath 0/1 (Zeixshi-Kar's Awakening)\nYou say, 'Hail, Gildorn Icebreath'\nGildorn Icebreath says 'You say you found this on one of the corpses of the suspicious beings? I have no idea what this is, but I do know someone who may be able to tell you more. His name is Robairn. He is more concerned with his treasure hunting than the dilemma here in the East Wastes, but hopefully he will help you. Robairn's camp is to the southwest of here.'\nGive the mysterious coin to Treasure Hunter Robairn to see if he can decipher it 0/1 (Zeixshi-Kar's Awakening)\nTreasure Hunter Robairn ( map) is located at approximately -9220, 4680, 257, in the southwest corner of the zone.\nSpeak with Treasure Hunter Robairn 0/1 (Zeixshi-Kar's Awakening)\nYou say, 'Hail, Treasure Hunter Robairn'\nTreasure Hunter Robairn says 'It appears we have a budding treasure hunter in our midst. What an odd token. You wish for me to tell you where it came from? I may be able to help you with that, but first, I need you to take care of a little problem I am having. Some thieves have been invading my camp at night in an attempt to steal my treasure. [Stop] them, and I will attempt to decipher this token for you.'\nYou say, 'Stop them, how?'\nTreasure Hunter Robairn says 'I have quite an ingenious plan all cooked up, I just need you to execute it. Go into the wastes and gather a head and some tattered clothing from a samhain. Return these items to me, and then the real fun can begin.'\n\n---\n\nLoot a samhain head from a samhain 0/1 (Zeixshi-Kar's Awakening)\n_Samhains are found most commonly scattered around the outer areas of the zone, towards the zone boundaries._\nObtain some tattered clothing from a samhain 0/1 (Zeixshi-Kar's Awakening)\nReturn the samhain head to Treasure Hunter Robairn 0/1 (Zeixshi-Kar's Awakening)\nReturn the tattered clothing to Treasure Hunter Robairn 0/1 (Zeixshi-Kar's Awakening)\nSpeak with Treasure Hunter Robairn 0/1 (Zeixshi-Kar's Awakening)\nYou say, 'Hail, Treasure Hunter Robairn'\nTreasure Hunter Robairn takes the samhain head and tattered clothing and quickly fashions a rather frightening costume. \"This ought to do the trick. Put this costume on and find the thieves. The thieves' names are Falmia, Jornin, and Yalfi. They normally hide out to the northeast, in and around some ruins. Once you find them, let them know that I sent you.\"\n\n---\n\nUse the samhain mask to scare Falmia 0/1 (Zeixshi-Kar's Awakening)\n_At the last step, you received a Samhain Costume, a TEMPORARY scarecrow illusion click-effect item. For each of the next three steps, make sure to have the illusion up before saying \"Robairn sent me.\" to the NPC's. These are Coldains found among the ruins in the north-central part of the zone._\n_The ruins are located at about 400, -45, 3. Falmia ( map) is west of this location; Yalfi ( map) is east of it; Jornin ( map) is south of it._\nYou say, 'Robairn sent me.'\nFalmia says 'Tell Robairn I won't bother his treasure anymore!'\nUse the samhain mask to scare Jornin 0/1 (Zeixshi-Kar's Awakening)\nYou say, 'Robairn sent me.'\nJornin says 'It's a monster! Tell Robairn I am sorry!'\nUse the samhain mask to scare Yalfi 0/1 (Zeixshi-Kar's Awakening)\nYou say, 'Robairn sent me.'\nYalfi says 'OK, OK! Tell Robairn I promise not to steal from him anymore!'\nReturn to Treasure Hunter Robairn and have him decipher the mysterious coin 0/1 (Zeixshi-Kar's Awakening)\nHand in the coin.\nTreasure Hunter Robairn says 'Have you scared those pitiful thieves yet? You did? I wish I could have been there to see their faces! Now let's take a look at this token. There appears to be some runes and an engraving of a dragon upon it. Roughly translated, the runes say, Zeixshi-Kar. I have not heard this name before. Unfortunately that's all I can tell from looking at the token. Thanks for your help, and I hope I was able to help you in some small way.'\nSpeak with Gildorn Icebreath 0/1 (Zeixshi-Kar's Awakening)\nYou say, 'Hail, Gildorn Icebreath'\nGildorn Icebreath says 'Zeixshi-Kar? Dragon? Perhaps that is the name of the dragon engraved on the token. We will need to do some more investigating. Speak with me again if you are able to help me further.'\n_Rewards:_\n150 platinum\nExperience (2 AAs)",
    },
    {
      id = "6027",
      title = "Zeixshi-Kar \\#2: Indoctrination",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Gildorn Icebreath",
      loc = { y = -8115.0, x = 3160.0, z = 147.0 },
      triggers = {
        "Hail, Gildorn Icebreath",
        "What happened?",
        "A Coldain?",
        "Hail, Dirgen",
        "Hail, Welken",
        "_Quests_",
        "_Quests_",
        "happened",
      },
      items_required = {
      },
      rewards = {
        { id = 106453, name = "Journal", type = "item" },
        { id = 108022, name = "Partially Digested Lichen", type = "item" },
        { id = 106584, name = "Rabbit's Foot", type = "item" },
        { id = 106538, name = "Ulthork Blubber", type = "item" },
        { id = 108729, name = "Vial of Medicine", type = "item" },
        { id = 108149, name = "Wooly Rhino Horn", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- East Wastes, Zeixshi-Kar's Awakening [zone=868]\n**Who:**\n- Gildorn Icebreath [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Time Limit:** | 06:00:00\n**Quest Items:**\n- Journal [item=106453]\n- Partially Digested Lichen [item=108022]\n- Rabbit's Foot [item=106584]\n- Ulthork Blubber [item=106538]\n- Vial of Medicine [item=108729]\n- Wooly Rhino Horn [item=108149]\n**Related Creatures:**\n- Dirgen [ _Quests_]\n- Welken [npc=41584]\n- a snow bunny [npc=41550]\n- a wooly mammoth - East Wastes - RoF - 1 [npc=41560]\n- a wooly rhino [npc=41561]\n- an ulthork hunter [npc=41567]\n- an ulthork man o war [npc=41568]\n- an ulthork warrior [npc=41569]\n**Related Quests:**\n- Confronting Your Fears [quest=6030]\n- Defeat Zeixshi-Kar [quest=6031]\n- Raid Expedition: Zeixshi-Kar's Shard [quest=6032]\n- Zeixshi-Kar #1: Scaring Up Some Information [quest=6026]\n- Zeixshi-Kar #3: The Sacrifice [quest=6028]\n- Zeixshi-Kar #4: The Sweet Taste of Revenge [quest=6029]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 28 18:06:31 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is the second task in a series of four. It's a shared task that begins with Gildorn Icebreath ( map) in Zeixshi-Kar's Awakening. He is found at /location -8115, 3160, 147 (outside some Coldain huts that are due south of the entrance to the canyon that leads to Kael Drakkel)._\n_Pre-Requisites:_\n\\- Level 85\n\\- Completed \"Scaring Up Some Information\"\nYou say, 'Hail, Gildorn Icebreath'\nGildorn Icebreath says 'I have heard tales of a couple of adventurers that set out to investigate some sort of disturbance near the old giant fort to the north. That was at least two days ago and nobody has seen them since. Perhaps you can look for them to see what may have [happened]? Perhaps they found something of interest.'\nYou say, 'What happened?'\nGildorn Icebreath says 'You may want to search the outside of the fort first, as entering the fort itself is taking your own life in its hands. Return to me if you find anything.'\nYou have been assigned the task 'Indoctrination'.\nGildorn Icebreath would like for you to search for some missing adventurers near the old giant fort in East Wastes. Perhaps they stumbled onto some important information.\n\n---\n\nSee if you can locate the missing adventurers near the giant fort 0/1 (East Wastes: Zeixshi-Kar's Awakening)\n_This update is outside the giant fort in the northwest part of the zone (about -1900, 3050, 145)._\nFind the journal near the dead adventurers and return it to Gildorn Icebreath 0/1 (East Wastes: Zeixshi-Kar's Awakening)\n_The journal is a ground spawn at the same location._\nSpeak with Gildorn Icebreath 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nYou say, 'Hail, Gildorn Icebreath'\nGildorn Icebreath says ''You found this journal near the bodies of the dead adventurers? Let me take a look at it.' Gildorn peruses the pages for a few moments. 'According to the notes written in this journal, the giant fort has been taken over by a fearsome dragon. This must be Zeixshi-Kar, mentioned on the token you found. It also says that they saw a [Coldain] running from the fort, being chased by several Frost Giants. If we can find this Coldain, perhaps they can clue us in on some more information.'\nYou say, 'A Coldain?'\nGildorn Icebreath says 'The last entry in the journal mentions that the adventurers were planning on helping the Coldain, who fled northwest from the fort. Obviously, they didn't make it that far.'\n\n---\n\nFind the Coldain who was fleeing from the giant fort 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nSpeak with Dirgen 0/1 (East Wastes: Zeixshi-Kar's Awakening)\n_Find Dirgen ( map) and hail him. He is in the extreme northwestern part of the zone at about 230, 4900, 400._\nYou say, 'Hail, Dirgen'\nDirgen says 'Please help. . . so sick. . . troops made me eat dust from fear shard. . . Won't last much longer.'\nSpeak with Gildorn Icebreath 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nYou say, 'Hail, Gildorn Icebreath'\nGildorn Icebreath says 'You have found the Coldain? If what he says is true about ingesting dust from the fear shard, then he is in dire trouble. I am afraid the only option we have available to help him would be a local hermit named Welken. Welken is seen as nothing more than a madman, but he is the only shaman I know of right now that might be able to help. Seek him out to the east.'\nSpeak with Welken 0/1 (East Wastes: Zeixshi-Kar's Awakening)\n_Welken ( map) is found at /location -9130, -4180, 144 (this is the zone-in: he is behind the purple crystal overlooking the coast)._\nYou say, 'Hail, Welken'\nWelken says 'You are not welcome here. I am thrown out of my clan like garbage, but yet when help is needed I am the one who is supposed to rescue them? I will put aside my differences and try to help Dirgen though. I cannot in good faith let a brother Coldain suffer. If what you say is true, then Dirgen does not have much time left. Some very specific [ingredients] are needed to concoct a cure.'\n\n---\n\nLoot a rabbit's foot from a snow bunny 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nLoot a wooly rhino horn from a wooly rhino 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nLoot some ulthork blubber from an ulthork 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nLoot some partially digested lichen from the stomach of a mammoth 0/1 (East Wastes: Zeixshi-Kar's Awakening)\n_Bunnies and mammoths tend to be found in the eastern and southern areas of the zone; rhinos are found in most areas; ulthorks are found in the northern part of the zone (ruins in the north) and in the far southwest._\nGive the rabbit's foot to Welken 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nGive the wooly rhino horn to Welken 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nGive the ulthork blubber to Welken 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nGive the partially digested lichen to Welken 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nSpeak with Welken 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nYou say, 'Hail, Welken'\nWelken takes the ingredients from you and quickly performs a series of rituals and incantations. When he is done, a small vial of putrid-looking liquid is all that's left. 'Take this to Dirgen and have him drink it. It should counteract the effects of the shard.'\n_You receive a Vial of Medicine._\nGive the vial of medicine to Dirgen 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nSpeak with Dirgen 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nYou say, 'Hail, Dirgen'\nDirgen quickly quaffs down the medicine. 'Thank you. I am feeling better. Leave me for now. I must get some rest.'\nSpeak with Gildorn Icebreath 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nYou say, 'Hail, Gildorn Icebreath'\nGildorn Icebreath says 'You were able to save Dirgen? That is good news. Let him rest for a while and then speak with me again. We have much to do.'\n_Rewards:_\n187 platinum, 5 gold\nExperience",
    },
    {
      id = "6028",
      title = "Zeixshi-Kar \\#3: The Sacrifice",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Gildorn Icebreath",
      loc = { y = -8115.0, x = 3160.0, z = 147.0 },
      triggers = {
        "Hail, Gildorn Icebreath",
        "I will check on him again.",
        "Hail, Dirgen",
        "Hail, Welken",
        "Perform?",
        "Snow bunny blood?",
        "Enchanted snow?",
        "Seashell of Calming Sounds?",
      },
      items_required = {
        { name = "Jorga the items you collected", count = 1 },
        { name = "the sample of pure bunny snow to Dirgen's wife", count = 1 },
        { name = "the enchanted snow to Dirgen's wife", count = 1 },
        { name = "the seashell of calming sounds to Dirgen's wife", count = 1 },
      },
      rewards = {
        { id = 106602, name = "Enchanted Snow", type = "item" },
        { id = 106419, name = "Sample of Pure Snow Bunny Blood", type = "item" },
        { id = 108364, name = "Seashell of Calming Sounds", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- East Wastes, Zeixshi-Kar's Awakening [zone=868]\n**Who:**\n- Gildorn Icebreath [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Money\n**Quest Items:**\n- Enchanted Snow [item=106602]\n- Sample of Pure Snow Bunny Blood [item=106419]\n- Seashell of Calming Sounds [item=108364]\n**Related Creatures:**\n- Dirgen [ _Quests_]\n- Jorga [npc=41576]\n- Mirlil [npc=41579]\n- Welken [npc=41584]\n- Zebexiban [npc=41586]\n- a snow bunny [npc=41550]\n**Related Quests:**\n- Confronting Your Fears [quest=6030]\n- Defeat Zeixshi-Kar [quest=6031]\n- Raid Expedition: Zeixshi-Kar's Shard [quest=6032]\n- Zeixshi-Kar #1: Scaring Up Some Information [quest=6026]\n- Zeixshi-Kar #2: Indoctrination [quest=6027]\n- Zeixshi-Kar #4: The Sweet Taste of Revenge [quest=6029]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 28 18:06:35 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is the third task in a series of four. It's a shared task that begins with Gildorn Icebreath ( map) in Zeixshi-Kar's Awakening. He is found at /location -8115, 3160, 147 (outside some Coldain huts that are due south of the entrance to the canyon that leads to Kael Drakkel)._\n_Pre-Requisites:_\n\\- Level 85\n\\- Completed \"Scaring Up Some Information\"\n\\- Completed \"Indoctrination\"\nYou say, 'Hail, Gildorn Icebreath'\nGildorn Icebreath says 'I think you should go [check] on Dirgen again. He may have some valuable information about Zeixshi-Kar.'\nYou say, 'I will check on him again.'\nGildorn Icebreath says 'Be safe, my friend.'\nYou have been assigned the task 'The Sacrifice'.\nNow that Dirgen has hopefully recovered, speak with him to see if he has more information on Zeixshi-Kar's army.\n\n---\n\nSpeak with Dirgen 0/1 (Zeixshi-Kar's Awakening)\n_Dirgen ( map) is in the extreme northwestern part of the zone at about 230, 4900, 400._\nYou say, 'Hail, Dirgen'\nDirgen says 'I thank you for saving my life, but perhaps you shouldn't have. I am a coward. My wife Jorga is about to be sacrificed to a powerful being from the Plane of Fear known as, Zebexiban. Zeixshi-Kar hopes that if he sacrifices enough souls to this creature, that Zebexiban will become his ally. I beg of you, please save her. I am too weak to do so myself. Please speak with Welken again. Maybe he knows how to save her.'\nSpeak with Welken 0/1 (Zeixshi-Kar's Awakening)\n_Welken ( map) is found at /location -9130, -4180, 144 (this is the zone-in: he is behind the purple crystal overlooking the coast)._\nYou say, 'Hail, Welken'\nWelken says 'My, my. I have become quite popular for a hermit as of late. What can I do for you now? An exorcism you say? I have performed them in the past, but they are far too dangerous to attempt. I cannot risk an evil spirit corrupting my body and using the knowledge I have for evil. Perhaps you can try to [perform] it however.'\nYou say, 'Perform?'\nWelken says 'You will need to gather a few items that will be used in the ceremony to transfer the victim's soul back into their own body. A sample of pure [snow bunny blood], some [enchanted snow], and a [Seashell of Calming Sounds] will be required.'\nYou say, 'Snow bunny blood?'\nWelken says 'I would imagine that you can get snow bunny blood from snow bunnies. Are you sure you are up to performing this exorcism?'\nYou say, 'Enchanted snow?'\nWelken says 'The Snow Dervishes are made almost entirely of enchanted snow. Kill some of them and perhaps you can get enough snow from them.'\nYou say, 'Seashell of Calming Sounds?'\nWelken says 'Unfortunately the shell may not be as easy to obtain as the other two items are. The shell is guarded by a Siren named, [Mirlil]. She perverts the shell's magic to lull victims into her clutches. I am afraid you will need to try to kill Mirlil to obtain the shell.'\nYou say, 'Mirlil?'\nWelken says 'Mirlil appeared not long after the shard struck. A pirate ship approached the southwest shore and when they tried to leave the ship, Mirlil struck and turned the entire crew into mindless thralls. Find the ship and kill Mirlil to obtain the Shell of Calming Sounds.'\n\n---\n\nLoot a sample of pure snow bunny blood from a snow bunny 0/1 (Zeixshi-Kar's Awakening)\nLoot some enchanted snow from a snow dervish 0/1 (Zeixshi-Kar's Awakening)\nDefeat the siren, Mirlil 0/1 (Zeixshi-Kar's Awakening)\n_Mirlil ( map) spawns under a shipwreck in the far southwest part of the zone. She is surrounded by several thralls. (/location -9900, 3850, -90)_\n_Note: Thralls are immune to snare, root, mez, and stun. Mirlil, herself, casts \"Entrancing Silence\" (pull spell)._\nLoot a Seashell of Calming Sounds from the siren 0/1 (Zeixshi-Kar's Awakening)\n\n---\n\nSpeak with Welken 0/1 (Zeixshi-Kar's Awakening)\nYou say, 'Hail, Welken'\nWelken says 'You survived your encounter with Mirlil I see. Perhaps you are strong enough to perform the exorcism. Let me know when you're [ready to begin].'\nYou say, 'Ready to begin!'\nWelken says 'To perform the exorcism, give Jorga the items you collected. These items will hopefully help to protect her during the violent struggle. Once you have given her the three items, you must then chant the following phrase to her: 'Vesius juluira ornanai'. This should force the creature who is feeding on her soul into our plane of existence.'\n\n---\n\nGive the sample of pure bunny snow to Dirgen's wife, Jorga 0/1 (Zeixshi-Kar's Awakening)\nGive the enchanted snow to Dirgen's wife, Jorga 0/1 (Zeixshi-Kar's Awakening)\nGive the seashell of calming sounds to Dirgen's wife, Jorga 0/1 (Zeixshi-Kar's Awakening)\n_Jorga ( map) is located east-northeast of the giant fort (and almost due north of the Ry'Gorr fort) at /location -645, 700, 160._\nTell Jorga: \"Vesius juluira ornanai\" 0/1 (Zeixshi-Kar's Awakening)\nYou say, 'Vesius Juluira Ornanai'\n_This triggers the spawn of Zebexiban (casts \"Consume Soul\", a self-buff haste/attack/regen)._\nZebexiban does not look pleased that you are trying to interrupt its feeding.\nZebexiban has been slain by \\_\\_\\_\\_\\_!\nZebexiban's corpse slumps pitifuly to the ground.\nJorga unfortunately did not survive the ritual. Her soul has been completely consumed by Zebexiban.\n\n---\n\nSpeak with Dirgen 0/1 (Zeixshi-Kar's Awakening)\nYou say, 'Hail, Dirgen'\nDirgen says 'My Jorga did not survive the exorcism, did she? You did what you could, and I am thankful for that. I should have found help sooner, instead of fleeing like a worthless coward. Please go for now and let me mourn. When I have composed myself, speak with me again. Zeixshi-Kar will pay for what he has done.'\n_Rewards:_\n112 platinum, 5 gold\nExperience",
    },
    {
      id = "6031",
      title = "Defeat Zeixshi-Kar",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Dirgen",
      loc = nil,
      triggers = {
        "Hail, Dirgen",
        "How can we destroy him?",
        "We are willing",
        "Send me there",
        "Hail, Zeixshi-Kar",
        "What power?",
        "Stupid?!",
        "It shall be your death!",
      },
      items_required = {
        { name = "you one chance to [leave]", count = 1 },
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- East Wastes, Zeixshi-Kar's Awakening [zone=868]\n**Who:**\n- Dirgen [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 100\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Advancement\n- Experience\n- Loot\n- Money\n**Time Limit:** | 06:00:00\n**Success Lockout Timer**: 06:00:00\n**Related Zones:**\n- East Wastes: Defeat Zeixshi-Kar [zone=882]\n**Related Creatures:**\n- Dirgen [npc=42555]\n- Zeixshi-Kar [npc=42472]\n- a coldain captain [npc=45464]\n- a coldain soldier [npc=42553]\n- a coldain warrior [npc=42552]\n- a feartattered drake [npc=42548]\n- a kromrif captain [npc=42551]\n- a kromrif guard [npc=42550]\n- a kromrif soldier [npc=42549]\n- an amazing chest [npc=42448]\n- crystallized fear [npc=42554]\n**Related Quests:**\n- Confronting Your Fears [quest=6030]\n- Raid Expedition: Zeixshi-Kar's Shard [quest=6032]\n- Zeixshi-Kar #1: Scaring Up Some Information [quest=6026]\n- Zeixshi-Kar #2: Indoctrination [quest=6027]\n- Zeixshi-Kar #3: The Sacrifice [quest=6028]\n- Zeixshi-Kar #4: The Sweet Taste of Revenge [quest=6029]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Group\n**Min. # of Players:** | 3\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 28 18:06:46 2012\nModified: Thu Sep 26 06:33:40 2024 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This group mission begins with Dirgen ( map) in Zeixshi-Kar's Awakening. He is in the extreme northwestern part of the zone at about 230, 4900, 400._\n_Pre-Requisites:_\n\\- Level 85\n\\- Completed \"Scaring Up Some Information\"\n\\- Completed \"Indoctrination\"\n\\- Completed \"The Sacrifice\"\n\\- Completed \"The Sweet Taste of Revenge\"\n\\- Completed \"Confronting Your Fears\" (group mission)\nYou say, 'Hail, Dirgen'\nDirgen says 'Zeixshi-Kar has fallen into a state of depression, or at least it appears that way to me. He stirs little within is protective dome. Now is the time to strike a final blow. Your [confrontation] with the great dragon earlier has affected him. He was not [prepared] for your efforts, nor the disruption you caused by helping to [save] Jorga. But now is the time for you to attempt a final blow, to try to [destroy] the great fear drake while he is weak and distracted.'\nYou say, 'How can we destroy him?'\nDirgen says 'I can send into the dome, but leaving might be impossible. Defeating the dragon will be up to you. Are you [willing] to risk everything?'\nYou say, 'We are willing'\nDirgen says 'Good then. You continue to prove your bravery. Let me know when you wish me to [send] you into the dome.'\nYou have been assigned the task 'Defeat Zeixshi-Kar'.\nNow is your chance to defeat the tyrannical Zeixshi-Kar and reduce the effect of the shard of fear.\nYou say, 'Send me there'\nLOADING, PLEASE WAIT...\nYou have entered Zeixshi-Kar's Shard.\n_NOTE: You cannot campfire into this instanced zone._\n\n---\n\nKill Zeixshi-Kar 0/1 (Zeixshi-Kar's Awakening)\nBring your group together, then open the chest to gather your rewards 0/1 (Zeixshi-Kar's Awakening)\n\n---\n\n_Note: This event is triggered through dialogue (not aggro until trigger - keyword \"death\")._\nYou say, 'Hail, Zeixshi-Kar'\nZeixshi-Kar shouts 'What? How did mortals get in here to disturb me? Ah, you defeated those fools that I trusted with my [power]. And now you've used it to get in here to bother me.'\nYou say, 'What power?'\nZeixshi-Kar shouts 'A mortal like you would never fully understand what I have learned, the power that I have been able to drag from this... this shard of Fear. Its power has become mine. You should consider this. I was strong before, but now, now you should run. You should fear me. But then, you're not bright enough for that, are you. There is one thing I understand clearly now; the truly [stupid] can't be frightened.'\nYou say, 'Stupid?!'\nZeixshi-Kar shouts 'Most like to call it bravery, but I know differently. Willingness to die for something is only a misunderstanding of facts. Dying for something is meaningless and stupid. So I will give you one chance to [leave]. The other option for you is [death].'\nYou say, 'It shall be your death!'\nZeixshi-Kar shouts 'This is what I expected of you.'\n_Zeixshi-Kar wakes up and starts flying around the zone (he is still non-aggro at this point, but casts a \"Lava Breath\" AE/dispell, avoidable by staying away from him)._\n_Here, you will have adds to contend with:_\n\\- First Wave: 4x \"a feartattered drake\" (spawn shortly after event trigger)\n\\- Second Wave: Mix of several Coldain/Giants (spawns 10:00 after trigger, or after drakes die - whichever occurs first)\n\\- Third Wave: Mix of several Coldain/Giants (spawns 11:30 after trigger, or after previous wave dies - whichever occurs first)\n\\- Fourth Wave: Two captains? One Coldain / One Giant (spawns 13:00 after trigger, or after previous wave dies, whichever occurs first))\n\\- Fifth Wave: Zeixshi-Kar (spawns 20:00 after trigger, or after previous wave dies, whichever occurs first)\n_Note: all adds in this mission summon from 100% health and have very large aggro ranges._\n_The drakes die fast and easily, hitting for a max ~10,000 (immune to mez/root/stun)._\n_Giants and Coldain also hit for a max ~10,000 and are immune to mez, root, and stun. Those with \"soldier\" in their name can be charmed, except the charm doesn't work as a regular charm - the mob doesn't become your pet, but will attack mobs of the opposing race._\n_Note: Prior to a patch on May 14, 2013, there was an anti-kite mechanic on the adds, where If you tried kiting them, you would spawn an additional add. This was removed in that patch._\n_When an add is killed, a short timer starts (10 seconds?), and then the corpse casts an AE: \"Sweltering Carcass\" (PBAE 20' range nuke for 42,000 damage)._\n\n---\n\n_Zeixshi-Kar goes live after all adds have been killed or after a certain amount of time has passed since the event was triggered (this timer appears to be 20 minutes from the time of trigger)._\n_He has a lot of hitpoints; hits for a max ~28,000; and single-target rampages (does not flurry). NOTE: His melee damage and health were decreased in a patch on May 14, 2013. He may hit for less than 28,000 now._\n_He casts \"Sweeping Tail\", a rear AE and knockback, every 15 seconds:_\nSweeping Tail: Directional 200', Unresistable (-800)\n1: Decrease Hitpoints by 27000\n2: Knockback (2) and Toss Up (4)\n_He casts the PBAE 400' range knockback \"Wing Buffet\" every 30 seconds:_\nWing Buffet: PB AE 400', Chromatic (-825)\n1: Decrease Hitpoints by 19000\n_He casts the PBAE 200' range \"Lava Breath\" every 25 seconds:_\nLava Breath: PB AE 200', Fire (-800)\n1: Decrease Hitpoints by 35000\n2: Cancel Magic (9)\n_And every 45 seconds, he casts \"Crystallized Fear\" on a random player, encasing them in place:_\nCrystallizing Fear: Single Target, Magic (-10000)\n1: Mesmerize (0) _(5 minutes)_\n2: Invulnerability\n_The player inflicted with \"Crystallized Fear\" cannot cast or attack, and is invulnerable. The freeze lasts five minutes. To free the target, you need to DPS the crystal dead. It's a good idea to free them as soon as possible since the dragon will soon cast the crystal freeze again. (Due to the nature of this mechanic, it's beneficial to have at least two healers in the group)._\n_Kill Zeixshi-Kar and open the chest to complete the task._\nZeixshi-Kar has been slain by \\_\\_\\_\\_\\_!\nThe dome of fear protecting the shard fades away.\n_Rewards:_\n450 platinum\nExperience\n_Possible Chest Loot [npc=42448] (1 Item + 1 Dreadmote per task):_\nAlgid Conjurer's Mantle\nBlackwell's Loop\nBone Choker of the Frozen Priest\nFrozen Lunatic's Hammer\nSable Band of the Wastes\nSnowflake Sash of the Tundra\nThe Mad's Raving\nWool Sponge\nMinor Dreadmote\nLesser Dreadmote\nMedian Dreadmote\nGreater Dreadmote",
    },
    {
      id = "6034",
      title = "If I Had My Hammer",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Blacksmith Galrim",
      loc = { y = -8650.0, x = 2115.0, z = 144.0 },
      triggers = {
        "Hail, Blacksmith Galrim",
        "Smithing hammer and tools?",
        "I",
        "_Quest_",
        "smithing hammer and tools",
        "get them back",
      },
      items_required = {
      },
      rewards = {
        { id = 108436, name = "Brittle Dragon-Forged Weapon", type = "item" },
        { id = 108434, name = "Corrosive Substance", type = "item" },
        { id = 108435, name = "Dragon-Forged Weapon", type = "item" },
        { id = 107880, name = "Fear Shardling Crystal", type = "item" },
        { id = 108429, name = "Galrim's Smithing Hammer", type = "item" },
        { id = 108430, name = "Galrim's Toolbox", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- East Wastes, Zeixshi-Kar's Awakening [zone=868]\n**Who:**\n- Blacksmith Galrim [ _Quest_]\nRating:\n0/1**_\\*__\\*__\\*__\\*__\\*_**\n(From 1 rating)\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Quest Items:**\n- Brittle Dragon-Forged Weapon [item=108436]\n- Corrosive Substance [item=108434]\n- Dragon-Forged Weapon [item=108435]\n- Fear Shardling Crystal [item=107880]\n- Galrim's Smithing Hammer [item=108429]\n- Galrim's Toolbox [item=108430]\n- Sample of Manticore Saliva [item=106587]\n- Sample of Spinechiller Venom [item=108318]\n- Small Cauldron [item=108738]\n- Walrus Tusk [item=108213]\n**Related Creatures:**\n- a coldain blacksmith [npc=41524]\n- a crate of weapons [npc=41532]\n- a fear shardling [npc=41493]\n- a manticore [npc=41538]\n- a spinechiller spider [npc=41553]\n- a walrus [npc=41559]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 28 18:24:24 2012\nModified: Fri Jan 10 07:15:29 2025 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a shared task (1-6 players) that begins with Blacksmith Galrim ( map) in East Wastes: Zeixshi-Kar's Awakening. This is a Coldain located at -8650, 2115, 144 (along the southern coast, a little southeast of the entrance canyon to Kael Drakkel)._\n_Pre-Requisites:_\n\\- Level 85\n\\- No tasks\nYou say, 'Hail, Blacksmith Galrim'\nBlacksmith Galrim says 'Fear not, I am not with Zeixshi-Kar's army. The dragon sent a couple of his goons to try to convince me to forge weapons for them, but I refused. Unfortunately that resulted in them taking away my prized [smithing hammer and tools].'\nYou say, 'Smithing hammer and tools?'\nBlacksmith Galrim says 'I am nothing without my smithing hammer and tools. They are enchanted to help me make exceptionally well-crafted weapons. If you could perhaps [get them back] for me, I would happily reward you.'\nYou say, 'I'll get them back'\nBlacksmith Galrim says 'Unfortunately I do not know where they may be now. Your best bet would be to check some of the huts throughout the tundra that Zeixshi-Kar's forces now use as outposts.'\nYou have been assigned the task 'If I Had My Hammer'.\n_Note: The task has no lock point (can add people until the very last step is completed)._\nGalrim refused to smith weapons for Zeixshi-Kar's army, so the dragon sent some of his goons to steal Galrim's prized smithing hammer and tools. He has asked you to get them back for him.\nFind Galrim's Smithing Hammer and Toolbox. He suggests you search near the huts.\n\n---\n\nFind Galrim's Smithing Hammer 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nFind Galrim's Toolbox 0/1 (East Wastes: Zeixshi-Kar's Awakening)\n_These items are looted from coldain blacksmiths (these spawn in and around the Coldain huts in various parts of the zone)._\n_Three known locations are -500, 3150, 149 (in the far northeast); -3300, -4500, 143 (just north of the bridge to Iceclad); and -7900, -2200, 150 (a ways southeast of Sleeper's Tomb)._\nGive Galrim's Smithing Hammer to Blacksmith Galrim 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nGive Galrim's Toolbox to Blacksmith Galrim 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nSpeak with Blacksmith Blacksmith Galrim 0/1 (East Wastes: Zeixshi-Kar's Awakening)\n_You receive a Small Cauldron._\nLoot a Sample of Spinechiller Venom 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nLoot a Sample of Manticore Saliva 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nLoot some Walrus Tusks 0/2 (East Wastes: Zeixshi-Kar's Awakening)\nLoot some Fear Shardling Crystals 0/3 (East Wastes: Zeixshi-Kar's Awakening)\nCreate the Corrosive Essence and give it to Blacksmith Galrim 0/1 (East Wastes: Zeixshi-Kar's Awakening)\n_Combine the above four looted items inside the Small Cauldron to create a Corrosive Substance._\nSpeak with Blacksmith Galrim 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nLoot some Dragon-Forged Weapons from weapon crates 0/4 (East Wastes: Zeixshi-Kar's Awakening)\n_Weapon crates are found inside various Coldain huts around the zone._\nDeliver the Dragon-Forged Weapons to Blacksmith Galrim 0/4 (East Wastes: Zeixshi-Kar's Awakening)\nSpeak with Blacksmith Galrim 0/1 (East Wastes: Zeixshi-Kar's Awakening)\n_You receive 4x Brittle Dragon-Forged weapons._\nPlace the Brittle Dragon-Forged weapons back into the weapon crates 0/1 (East Wastes: Zeixshi-Kar's Awakening)\nSpeak with Blacksmith Galrim 0/1 (East Wastes: Zeixshi-Kar's Awakening)\n_Rewards:_\n225 platinum\nExperience (3 AAs)",
    },
    {
      id = "6035",
      title = "Falmonius \\#1: This Can't Be Good!",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Hurble",
      loc = { y = 500.0, x = -1715.0, z = 145.0 },
      triggers = {
        "Hail, Hurble",
        "What help?",
        "What",
        "I will take care of it",
        "You want me to be your fall guy with Falmonius?",
        "Hail, Falmonius",
        "How would they be rebound?",
        "_Quest_",
      },
      items_required = {
        { name = "it to him", count = 1 },
      },
      rewards = {
        { id = 108214, name = "Glowing Page", type = "item" },
        { id = 108516, name = "Mysterious Tome", type = "item" },
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- East Wastes, Zeixshi-Kar's Awakening [zone=868]\n**Who:**\n- Hurble [ _Quest_]\nRating:\n0/2**_\\*__\\*__\\*__\\*__\\*_**\n(Average from 2 ratings)\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Quest Items:**\n- Glowing Page [item=108214]\n- Mysterious Tome [item=108516]\n**Related Zones:**\n- The Plane of Knowledge [zone=158]\n**Related Creatures:**\n- Falmonius [ _Quest_]\n- an animated spell book [npc=41491]\n**Related Quests:**\n- Falmonius #2: Stalking the Shadows [quest=6036]\n- Falmonius #3: Masters of Fear [quest=6037]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 6\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 28 18:27:48 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is the first task in a series of three; a shared task (1-6 players) that begins with a gnome named Hurble ( map) in Zeixshi-Kar's Awakening. It's located at 500, -1715, 145 close to the northern cost in the northeastern part of the zone, nearby a blimp)._\n_Pre-Requisites:_\n\\- Level 85\n\\- No tasks\nYou say, 'Hail, Hurble'\nHurble says 'I don't know what is going on around here, but I could really use your [help].'\nYou say, 'What help?'\nHurble says 'I am the captain of the merchant airship you see behind me. Two days ago I set sail from Erudin on my way to Felwithe with a shipment of spell books. As I approached the Buried Sea, strong winds beset my airship and carried me all the way here, and eventually forced me to make an emergency landing. That is not the [worst part] though.'\nYou say, 'What's the worst part?'\nHurble says 'The shipment of spell books I was carrying have sprung to life! It's the darndest thing I have ever seen! I need someone to [take care] of this mess. My crew fled into the icy wastes once the books started flying around, so I have no one else to help me.'\nYou say, 'I will take care of it'\nHurble says 'Um, something else you may need to know. I may have, um, stolen a particularly powerful spell book from a rather cantankerous wizard. When we crashed here, the other spell books ripped the mysterious tome to shreds, eating some very important pages. I need to get those pages back.'\nYou have been assigned the task 'This Can't Be Good!'.\nHurble was transporting some spell books on his airship when he crashed in the Eastern Wastes. The spell books have come alive and must be dealt with.\nKill animated spell books near the airship wreckage and collect glowing pages.\n\n---\n\nLoot glowing pages from animated spell books 0/6 (Zeixshi-Kar's Awakening)\nDeliver the glowing pages to Hurble 0/6 (Zeixshi-Kar's Awakening)\nSpeak with Hurble 0/1 (Zeixshi-Kar's Awakening)\n_You receive a Mysterious Tome._\nGive the Mysterious Tome to Falmonius 0/1 (Plane of Knowledge)\n_Falmonius is located in the Plane of Knowledge at 5, 1110, 34 (library's main floor, across from the elevator, up the ladder)._\nSpeak with Falmonius 0/1 (Plane of Knowledge)\nFalmonius is an Erudite in yellow robes on the top shelf of the PoK library entry tier, right next to a Magician vendor.\nIf people care these days about the quest text being here on the quest page, here it is:\nAfter handing in pages:\nHurble places the pages into the badly tattered spell book and the tome begins to glow. Hurble quickly throws the tome to the ground. 'Um, you may want to stand back.' The tome erupts in purple flames. The flames grow in intensity and a mass of magical energy bursts forth, almost knocking you to the ground. Six motes of light fly from the book and head into various directions further into the Eastern Wastes. Hurble looks worried. 'I don't think that was supposed to happen. I suppose I have no choice, but to tell you what's [really going on].'\nYou say, 'What's really going on?'\nHurble says, 'The truth is that I stole these spell books from my master, Falmonius and when he finds out, he will not be very pleased with me to put it mildly. This particular spell book was used to imprison six very angry shadows that Falmonius captured while in the Plane of Shadow. There must be some sort of mysterious magic here that has animated the spell books. I am afraid I am going to have to ask you to talk to [Falmonius].'\nYou say, 'You want me to be your fall guy with Falmonius?'\nHurble says, 'He is not going to be pleased, but he needs to know what has happened here. I would talk to him, but I am pretty sure he would incinerate me on the spot when he found out what I have done. When he isn't stalking the various planes of existence, he can be found perusing the spell vendors in the Plane of Knowledge. Take the spell book and give it to him. He will know what must be done.'\nAfter handing in book:\nYou say, 'Hail, Falmonius'\nFalmonius's brow furrows as you explain what just took place in the Eastern Wastes. 'Hurble! That idiot! I shall deal with him later. In the meantime it is vital that those shadows be [rebound] to the tome.'\nYou say, 'How would they be rebound?'\nFalmonius says 'From what you have described, those motes of light that escaped the tome are most likely the shadows, escaping their prison. Those shadows must be contained! Gather some adventuring supplies and once you are ready to continue, speak with me again.\n_Rewards:_\n337 platinum, 5 gold\nExperience (3-4% in Level 96 + 4 AAs)\n_NOTE: The Crystal Caverns task \"Stalking the Shadows\" follows this one (given by Falmonius)._",
    },
    {
      id = "6038",
      title = "Lost Without a Compass",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Baffod the Wayward",
      loc = { y = -4050.0, x = 40.0, z = 136.0 },
      triggers = {
        "Hail, Baffod the Wayward",
        "What place?",
        "Find your allies?",
        "I will help",
        "What about the giants?",
        "_Quests_",
        "place",
        "find",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- East Wastes, Zeixshi-Kar's Awakening [zone=868]\n**Who:**\n- Baffod the Wayward [ _Quests_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Related Creatures:**\n- a frost giant [npc=41534]\n- a frost giant captain [npc=41535]\n- a frost giant savage [npc=41536]\n- a frost giant scout [npc=41537]\n- a suspicious frost giant [npc=41555]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 28 18:38:04 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with Baffod the Wayward ( map) in Zeixshi-Kar's Awakening at /location -4050, 40, 136 (outside the Ry'Gorr fort in the middle of the zone; southeast corner)._\n_Pre-Requisites:_\n\\- Level 85\n\\- No other pre-requisites\nYou say, 'Hail, Baffod the Wayward'\nBaffod the Wayward says 'Ach! 'Tis good to see a fellow adventurer out here. What brings you to this [place]?'\nYou say, 'What place?'\nBaffod the Wayward says 'Sadly, tis a wee bit changed since last I was out this way. Speaking of which, I don't suppose yeh've seen a group of adventurers roamin' about nearby? I'm tryin' ta [find] me allies.'\nYou say, 'Find your allies?'\nBaffod the Wayward says 'Ach, nay. I dunnae need any [help] findin' me way back. I only lost track of 'em fer a moment, I tell yeh.'\nYou say, 'I will help'\nBaffod the Wayward scratches his beard thoughtfully, 'Well, I'm sure I'll find me friends again in no time, but if yer lookin' ta be useful, I'm guess I'm a li'l low on [food]. And those blasted [giants] could kill a Dwarf, trapsin' aroun' like they own the bloody place!'\nYou say, 'What about the giants?'\nBaffod the Wayward says 'Those blasted giants're everywhere, and dunnae seem to care who they step on. It'd be a right favor if yeh could help me by cutting some of the big lugs down ta size, if yeh get me drift.'\nYou have been assigned the task 'Lost Without a Compass'.\nBaffod has asked you to slay some giants, so that he can find his way back to his friends without getting trampled.\n\n---\n\nSlay 10 frost giants 0/10 (Zeixshi-Kar's Awakening)\nSpeak with Baffod 0/1 (Zeixshi-Kar's Awakening)\nYou say, 'Hail, Baffod the Wayward'\nYour task 'Lost Without a Compass' has been updated.\nBaffod the Wayward shakes your hand with violent enthusiasm, 'Much obliged to ye, friend!'\n_Rewards:_\n112 platinum, 5 gold\nExperience",
    },
    {
      id = "6039",
      title = "A Feast Fit for a Coldain",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Baffod the Wayward",
      loc = { y = -4050.0, x = 40.0, z = 136.0 },
      triggers = {
        "Hail, Baffod the Wayward",
        "What place?",
        "Find your allies?",
        "I will help",
        "What food?",
        "_Quests_",
        "place",
        "find",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- East Wastes, Zeixshi-Kar's Awakening [zone=868]\n**Who:**\n- Baffod the Wayward [ _Quests_]\n- Elder Ekron [npc=52891]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Related Creatures:**\n- a snow bunny [npc=41550]\n- a snow griffin - East Wastes - RoF - 1 [npc=41498]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 28 18:38:09 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with Baffod the Wayward ( map) in Zeixshi-Kar's Awakening at /location -4050, 40, 136 (outside the Ry'Gorr fort in the middle of the zone; southeast corner)._\n_Pre-Requisites:_\n\\- Level 85\n\\- No other pre-requisites\nYou say, 'Hail, Baffod the Wayward'\nBaffod the Wayward says 'Ach! 'Tis good to see a fellow adventurer out here. What brings you to this [place]?'\nYou say, 'What place?'\nBaffod the Wayward says 'Sadly, tis a wee bit changed since last I was out this way. Speaking of which, I don't suppose yeh've seen a group of adventurers roamin' about nearby? I'm tryin' ta [find] me allies.'\nYou say, 'Find your allies?'\nBaffod the Wayward says 'Ach, nay. I dunnae need any [help] findin' me way back. I only lost track of 'em fer a moment, I tell yeh.'\nYou say, 'I will help'\nBaffod the Wayward scratches his beard thoughtfully, 'Well, I'm sure I'll find me friends again in no time, but if yer lookin' ta be useful, I'm guess I'm a li'l low on [food]. And those blasted [giants] could kill a Dwarf, trapsin' aroun' like they own the bloody place!'\nYou say, 'What food?'\nBaffod the Wayward smacks his lips, 'Yeh know, I've heard the Coldain make some of the best food in the region, using frost bunny meat and snow griffin eggs. I don't suppose yeh'd be willin' to pick me up some o' those so I can try those famous dishes?'\nYou have been assigned the task 'A Feast Fit for a Coldain'.\n\n---\n\nCollect five pieces of frost bunny meat from snow bunnies 0/5 (Zeixshi-Kar's Awakening)\nCollect three eggs from snow griffins 0/3 (Zeixshi-Kar's Awakening)\n_Note: These are not actual items; rather, random updates as you kill._\nReturn to Baffod 0/1 (Zeixshi-Kar's Awakening)\nYou say, 'Hail, Baffod the Wayward'\nYour task 'A Feast Fit for a Coldain' has been updated.\nBaffod the Wayward dances about delightedly for a moment, then suddenly freezes in horror, 'I jus' remembered: I dunnae know how ta cook!'\n_Rewards:_\n112 platinum, 5 gold\nExperience",
    },
    {
      id = "6040",
      title = "Where Adventurers Fear to Tread",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Taelanie Oakenheart",
      loc = { y = -5375.0, x = 1050.0, z = 160.0 },
      triggers = {
        "Hail, Taelanie Oakenheart",
        "Something?",
        "Reach?",
        "I will help",
        "_Quest_",
        "something",
        "reach",
        "help",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- East Wastes, Zeixshi-Kar's Awakening [zone=868]\n**Who:**\n- Taelanie Oakenheart [ _Quest_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Related Creatures:**\n- a fear shardling [npc=41493]\n- an Amygdalan knight [npc=41563]\n- an Amygdalan warrior [npc=41564]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 28 18:38:13 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with Taelanie Oakenheart ( map) in Zeixshi-Kar's Awakening at /location -5375, 1050, 160 (out in the middle of nowhere and partially obscured by a tree; this location is a fair distance southwest of the Ry'Gorr fort in the middle of the zone)._\nYou say, 'Hail, Taelanie Oakenheart'\nTaelanie Oakenheart says 'What are you doing?! Quick - get down, before [something] sees you!'\nYou say, 'Something?'\nTaelanie Oakenheart says 'Those shardlings and the things - with the tentacles!' She shudders, and continues, 'That foolhardy Dwarf, Baffod, managed to get himself lost again, but I can't [reach] him because those, those - things - keep attacking me!'\nYou say, 'Reach?'\nTaelanie Oakenheart says 'Oh! If you could [help] me by taking down some of those horrifying creatures, I'd be eternally grateful!'\nYou say, 'I will help'\nYou have been assigned the task 'Where Adventurers Fear to Tread'.\nTaelanie has asked you to kill some of the fear shardlings and amygdalans which are in her way.\n\n---\n\nKill 10 fear shardlings or amygdalans 0/10 (Zeixshi-Kar's Awakening)\nReturn to Taelanie 0/1 (Zeixshi-Kar's Awakening)\n_Rewards:_\n112 platinum, 5 gold\nExperience",
    },
    {
      id = "6043",
      title = "Never Say 'Hi'",
      exp = "19",
      exp_name = "Rain of Fear",
      min_lvl = 1,
      max_lvl = 125,
      quest_type = "",
      repeatable = false,
      group_size = "",
      npc = "Tramric the Pessimistic",
      loc = { y = -5500.0, x = -3280.0, z = 230.0 },
      triggers = {
        "Hail, Tramric the Pessimistic",
        "Others?",
        "Doomed?",
        "Get through alive?",
        "Defeat them?",
        "_Quest_",
        "others",
        "doomed",
      },
      items_required = {
      },
      rewards = {
      },
      factions = {
      },
      walkthrough = "Quest Started By: | Description:\n**Where:**\n- East Wastes, Zeixshi-Kar's Awakening [zone=868]\n**Who:**\n- Tramric the Pessimistic [ _Quest_]\nRating:\n0/0**_\\*__\\*__\\*__\\*__\\*_**\nInformation:\n**Level:** | 95\n**Maximum Level:** | 125\n**Monster Mission:** | No\n**Repeatable:** | Yes\n**Can Be Shrouded?:** | No\n**Quest Type:** | Task\n**Quest Goal:**\n- Experience\n- Money\n**Related Creatures:**\n- a snow cougar - East Wastes - RoF [npc=41551]\n- a snow dervish [npc=41552]\n**Era:** | !Rain of Fear\nRecommended:\n**Group Size:** | Solo\n**Min. # of Players:** | 1\n**Max. # of Players:** | 1\n**Appropriate Classes:**\n- All\n**Appropriate Races:**\n- All\nEntered: Wed Nov 28 18:38:29 2012\nModified: Tue Dec 5 05:21:04 2023 | | **Rain of Fear Information & Guides: An Overview \\| Group Progression & Task List \\| Raid Progression \\| Visible Armor**\n\n---\n\n_This is a kill task that begins with Tramric the Pessimistic ( map) in Zeixshi-Kar's Awakening at /location -5500, -3280, 230 (out in the middle of nowhere and partially obscured by a tree, if you're coming from the north -- this loc is a little ways southwest of the bridge to Iceclad)._\nYou say, 'Hail, Tramric the Pessimistic'\nTramric the Pessimistic says 'Hail?! Here?? Oh dear, and I didn't bring a rain-skin or anything! Do you think it will pass quickly? Maybe I should go find a cave to sit in, and just wait it out. I hope the [others] will be ok if it's going to be a bad storm.'\nYou say, 'Others?'\nTramric the Pessimistic says 'Yes, my party. I left them to scout ahead in the hopes of finding a safe route \\*sigh\\*, but I think we're all [doomed], now.'\nYou say, 'Doomed?'\nTramric the Pessimistic says 'There are snow cougars and snow dervishes everywhere, and now you're telling me a hailstorm is coming. I knew we should never have come here. There's no way we'll [get through] alive.'\nYou say, 'Get through alive?'\nTramric the Pessimistic says 'What's that? You say there's no hailstorm after all? Are you sure? It looks like it might, you know. And unless I can find some way to [defeat] all these obstacles, there's no point in fighting our way through a hailstorm just to get mauled by a cougar.'\nYou say, 'Defeat them?'\nTramric the Pessimistic says 'You want to help us by cutting down the number of cougars and dervishes? I guess I can't stop you, but if it starts to hail, I recommend finding a safe place to take shelter. That's what I intend to do.'\nYou have been assigned the task 'Never Say 'Hi''.\nTramric has abandoned all hope of getting through the Eastern Wastes alive. He seems almost determined to be mauled by snow cougars, pulverized by snow dervishes, and pummeled by hail stones. Help Tramric regain hope by slaying the snow cougars and snow dervishes in the area.\n\n---\n\nKill 10 snow cougars or snow dervishes 0/10 (Zeixshi-Kar's Awakening)\nSpeak with Tramric 0/1 (Zeixshi-Kar's Awakening)\n_Rewards:_\n112 platinum, 5 gold\nExperience",
    },
  },
}
