[General]
KissAssistVer=12.002
CharInfo=Beastlord|11|GOLD

Role=Hunter

CampRadius=35
CampRadiusExceed=400
ReturnToCamp=0
ChaseAssist=0
ChaseDistance=25
CampfireOn=0

MedOn=1
MedStart=0
MedStop=100
MedCombat=0

RezAcceptOn=1|10
AcceptInvitesOn=1
GroupWatchOn=0
GroupWatchCheck=FALSE
CorpseRecoveryOn=0

EQBCOn=1
DanNetOn=1

ScatterOn=1
LOSBeforeCombat=1
LootOn=1
DanNetDelay=20
IRCOn=1
DefaultUI=TRUE
DPSMeter=1
UseSpawnMaster=0
XTSlot=1

[Buffs]
BuffsOn=1
BuffsSize=4
## ------ Auras (placeholder) ------ ##
Buffs1=Scale Skin
## ------ Beginner Buffs ------ ##
Buffs2=command:/useitem Worn Totem|Dual|Blessing of Swiftness|Cond6
## ------ Group Buffs ------ ##
Buffs3=Endure Cold|Cond7
## ------ Click off the Free to play nag popup ------ ##
Buffs4=command:/notify AlertWnd ALW_Dismiss_Button leftmouseup
RebuffOn=1
CheckBuffsTimer=10
PowerSource=NULL

[Melee]
AssistAt=98
MeleeOn=1
FaceMobOn=2
MeleeDistance=10
StickHow=snaproll !front
AutoFireOn=0
UseMQ2Melee=1
TargetSwitchingOn=1
PetTauntOverride=0

[Heals]
HealsOn=1
HealsSize=2
Heals1=Salve|40
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
HealInterval=0
AutoRezOn=0
Heals2=NULL
XTarHeal=0
XTarHealList=Xtar slots here Example: 5|6|7
HealGroupPetsOn=0
RezMeLast=0

[Cures]
CuresOn=1
CuresSize=2
Cures1=Cure Disease|Disease
Cures2=NULL

[Burn]
BurnAllNamed=0
UseTribute=0
BurnSize=1
Burn1=Intensity of the Resolute

[KConditions]
ConOn=1
CondSize=7
## ------ Basic ------ ##
Cond1=TRUE
Cond2=FALSE
## ------ Target Properties (placeholder) ------ ##
Cond3=${Target.ConColor.Equal[White]} || ${Target.ConColor.Equal[Yellow]} || ${Target.ConColor.Equal[Red]}
Cond4=${Target.Named} && (${Target.ConColor.Equal[Yellow]} || ${Target.ConColor.Equal[Red]})
Cond5=${Me.GroupAssistTarget.Named}
## ------ Buff Stacking ------ ##
Cond6=!${Me.Buff[Blessing of Swiftness].ID} && ${Spell[Blessing of Swiftness].Stacks}
Cond7=!${Target.Buff[Endure Cold].ID} && ${Spell[Endure Cold].StacksTarget}


[Spells]
Gem1=Minor Healing
Gem2=NULL
Gem3=NULL
Gem4=NULL
Gem5=Cure Disease
Gem6=Endure Cold
Gem7=
Gem8=NULL
MiscGem=8
MiscGemLW=0
MiscGemRemem=1
LoadSpellSet=0
SpellSetName=KissAssist
CastingInterruptOn=1
CheckStuckGem=1
[GoM]
GoMSHelp=Format - Spell|Target, MA Me or Mob, i.e. Rampaging Servant Rk. II|Mob
GoMSize=3
GoMSpell1=NULL
GoMSpell2=NULL
GoMSpell3=NULL
[AE]
AEOn=0
AESize=10
AERadius=50
AE1=NULL
AE2=NULL
AE3=NULL
AE4=NULL
AE5=NULL
AE6=NULL
AE7=NULL
AE8=NULL
AE9=NULL
AE10=NULL
[DPS]
DPSOn=0
DPSSize=20
DPSSkip=20
DPSInterval=2
DPS1=NULL
DPS2=NULL
DPS3=NULL
DPS4=NULL
DPS5=NULL
DPS6=NULL
DPS7=NULL
DPS8=NULL
DPS9=NULL
DPS10=NULL
DPS11=NULL
DPS12=NULL
DPS13=NULL
DPS14=NULL
DPS15=NULL
DPS16=NULL
DPS17=NULL
DPS18=NULL
DPS19=NULL
DPS20=NULL
DebuffAllOn=0
[Aggro]
AggroOn=0
AggroSize=5
Aggro1=NULL
Aggro2=NULL
Aggro3=NULL
Aggro4=NULL
Aggro5=NULL
[Pet]
PetOn=0
PetSpell=YourPetSpell
PetFocus=NULL
PetShrinkOn=0
PetShrinkSpell=Tiny Companion
PetBuffsOn=0
PetBuffsSize=8
PetBuffs1=NULL
PetBuffs2=NULL
PetBuffs3=NULL
PetBuffs4=NULL
PetBuffs5=NULL
PetBuffs6=NULL
PetBuffs7=NULL
PetBuffs8=NULL
PetCombatOn=1
PetAssistAt=95
PetAttackDistance=115
PetToysSize=6
PetBreakMezSpell=NULL
PullWait=0
PetSuspend=0
MoveWhenHit=0
PetHoldOn=1
PetForceHealOnMed=0
PetRampPullWait=0
[Merc]
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercOn=0
MercAssistAt=92
[Pull]
PullWith=Melee
PullMeleeStick=1

MaxZRange=5555
UseWayPointZ=1
PullWait=0
PullRadiusToUse=5000
PullRoleToggle=1
ChainPull=1
ChainPullHP=90
PullPause=0|0
PullLevel=1|100
PullArcWidth=360
PullOnReturn=1
MaxRadius=350
[PullAdvanced]
PullLocsOn=1
[AFKTools]
AFKHelp=AFKGMAction=0 Off, 1 Pause Macro, 2 End Macro, 3 Unload MQ2, 4 Quit Game
AFKToolsOn=1
AFKGMAction=1
AFKPCRadius=500
CampOnDeath=0
ClickBacktoCamp=0
[KissError]
LastCMD:=/if (!37) {
ErrorDateTime:=09/09/2024 08:50:25
ErrorMsg:=DoCommand - Couldn't parse '/looton 1'
DataError:=NULL
SyntaxError:=NULL
RunningTime:=2383654
BuildDate:=20240904
CurrentUI:=Default
